### ISSUE TITLE
SETUP Error 101 with excel

### ISSUE THREAD

**Issue by MichalM95** [usnistgov/REFPROP-wrappers#101]
Hello,
I follow all instruction form here, and I have that issue:
![Refprop](https://user-images.githubusercontent.com/48439079/54161208-c2a2ce00-4451-11e9-8d06-ad201a7012e0.png)
Can anyone help me?
Excel is from 2016.

**Comment by EricLemmon** [comment]
Take a look at the following and see if it helps:

https://pages.nist.gov/REFPROP-docs/#resolving-problems-linking-with-excel

**Comment by MichalM95** [comment]
Thank You!

Point 4 helped,  Uninstall Refprop and reinstalling it outside of the Program Files, in my case" C/Refprop".

**Comment by EricLemmon** [comment]
That's great!  That's always been my most recommended option.

Can this issue be closed now?
