### ISSUE TITLE
SATP Error 144

### ISSUE THREAD

**Issue by alighaffarti** [usnistgov/REFPROP-wrappers#102]
I am a Researcher and i am using Refprop in Matlab For Solving a Transient Problem. R245fa is used as working fluid. after few time steps an error appears and Stops the program:

[PHFLSH error 242] dew point calculation did not converge:  [SATP error 144] iteration for saturation state did not
converge; P =         NaN MPa. 

Please let me know what do i have to do? and also what does this error mean?

**Comment by ianhbell** [comment]
Please fill out the entire issue template.  This is to save us time asking for information already requested in the issue template.  

In this case, we need to know what version of REFPROP you use, how you called REFPROP and what inputs caused this problem.
