### ISSUE TITLE
Refprop10 interface with matlab

### ISSUE THREAD

**Issue by parthpdpu** [usnistgov/REFPROP-wrappers#103]
We have purchased latest version of Refprop10 developed by NIST through their official website. 

On successful completion of payment, we could download NIST2310.EXE file which we installed in our system with required configurations and upon installing the same, it is working fine. 

However we are unable to interface the same with Matlab. We even looked for the help file to interface two softwares but are unable to do so. We didn't received any license file and any other file pertaining to interface it with Matlab. 

I hereby request you to guide us regarding the same. Looking forward for your kind support and response.

**Comment by ianhbell** [comment]
Hello! Please see https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB for interfacing with MATLAB.  If you have any problems, please open a new issue in this repository.
