### ISSUE TITLE
MATLAB and REFPROP

### ISSUE THREAD

**Issue by atit-sut** [usnistgov/REFPROP-wrappers#104]
I am simulating a power plant by developing a MATLAB code. The code takes the fluid properties from REFPROP. Previously, I used REFPROP 9.1. However, I encountered a problem when I simulate a mixture of ammonia and water. REFPROP has a convergent problem when the mixture is around the saturation point. With some helps from REFPROP, now I use the Beta Version (December 17, 2018) of REFPROP. I got a recommendation to switch over to the new MATLAB wrapper for version 10 using Python, which I totally agree. However, I do not know the commands to be used in MATLAB for asking REPROP 10 to return the fluid properties. For example, I do not know the commands to calculate the enthalpy and entropy of a mixture of ammonia and water at a given temperature and pressure. Where can I find these commands?

Thank you very much.

Atit

**Comment by EricLemmon** [comment]
Here's a link to the bug Ian referred to:  #74 

Are you still having non-convergence errors?  If not, and if you have no further errors, could you close this issue?
