### ISSUE TITLE
Issue with Installation of REFPROP In MATLAB

### ISSUE THREAD

**Issue by shant7** [usnistgov/REFPROP-wrappers#108]
### Description
I tried installing REFPROP in my MATLAB using the link given below.
https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB

After installing ctREFPROP, when I use the below command, I get the error given below.

``` python
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')
```
Error that occurs ->

``` python
Python Error: OSError: [WinError 193] %1 is not a valid Win32 application
```

My system specifications are,
**REFPROP Version:** REFPROP V8.0
**Operating System and Version:** Windows 10, 64bit   

PLEASE HELP!

Attaching a screenshot below,

![Capture](https://user-images.githubusercontent.com/17909809/54839982-f7d0db00-4cf1-11e9-8f7d-6fe1e3de38a0.JPG)

**Comment by ianhbell** [comment]
The Python interface is intended for REFPROP version 9+.  I haven't tested it with REFPROP 8.  This probably means that the folder that contains your DLL is not on the path, and it is missing additional runtimes.  If you upgade to REFPROP 10, it should work seamlessly.

**Comment by EricLemmon** [comment]
Can this issue be closed now?

**Comment by shant7** [comment]
Sure. Thanks a lot.
