### ISSUE TITLE
Add Formula Categories and Function Descriptions

### ISSUE THREAD

**Issue by NickAtNight2017** [usnistgov/REFPROP-wrappers#12]
Example:   Shows 5 Refprop Categories for Functions.

![image](https://user-images.githubusercontent.com/31464824/29987369-83828a9c-8f2d-11e7-9709-665bc2b5bd3f.png)

Example:  Shows Description for Temperature.

{Okay, this one is a mess. Experimenting a bit }

![image](https://user-images.githubusercontent.com/31464824/29987421-c49e8f4e-8f2d-11e7-9142-680b0229a64b.png)

See[ this location ](http://www.ozgrid.com/VBA/udf-cat-description.htm)for the source:

I added this code to the "This Workbook" sheed of the Refprop.xlam file.

`
Private Sub Workbook_Open()

Sheet1.Visible = xlSheetVisible

AddCategoryDescription

Sheet1.Visible = xlSheetHidden

End Sub

Sub AddCategoryDescription()

'General Help Text
        strInpCode = Chr(10) & "InpCode is name and order of Prop1 and Prop2.  Properties are: T, P, D, S, E, Q, H.  For Sat Fluids Or Tliq, Tvap, Pliq, Pvap"
        strUnits = Chr(10) & "Units are SI, "
        strProps = Chr(10) & "Properties are T, P, D, S ..."
'Refprop Fluid
        strCategory = "RefProp Fluid"
        
        
        strFunction = "Temperature"
        strDescription = "Calculate Temperature of Fluid." & Chr(10) & _
            "Example: =Temperature(" & Chr(34) & "hydrogen" & Chr(34) & "," & Chr(34) & "PS" & Chr(34) & _
            "," & Chr(34) & "SI" & Chr(34) & ",10,20)" & _
            strInpCode & _
            strUnits & _
            strProps
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "Pressure"
        strDescription = "Calculate Pressure of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
        
        strFunction = "Density"
        strDescription = "Calculate Density of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "LiquidDensity"
        strDescription = "Calculate Liquid Denisty of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "VaporDensity"
        strDescription = "Calculate Vapor Density of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "Volume"
        strDescription = "Calculate Volume of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "CompressibilityFactor"
        strDescription = "Calculate Compressibility Factor (z) of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "Energy"
        strDescription = "Calculate Energy of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "Enthalpy"
        strDescription = "Calculate Enthalpy of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "LiquidEnthalpy"
        strDescription = "Calculate Liquid Enthalpy of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "VaporEnthalpy"
        strDescription = "Calculate Vapor Enthalpy of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "Entropy"
        strDescription = "Calculate Entropy of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "IsochoricHeatCapacity"
        strDescription = "Calculate Isochoric Heat Capacity of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "Cv"
        strDescription = "Calculate Cv of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "IsobaricHeatCapacity"
        strDescription = "Calculate Isobaric Heat Capacity of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "Cp"
        strDescription = "Calculate Cp of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "SpecificHeatInput"
        strDescription = "Calculate Specific Heat Input of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "Csat"
        strDescription = "Calculate Csat of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "SpeedOfSound"
        strDescription = "Calculate Speed of Sound of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "Sound"
        strDescription = "Calculate Sound of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

'Refprop differential group
        strCategory = "RefProp Differentials"
        
        strFunction = "dPdrho"
        strDescription = "Calculate (dP/dRHO) of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "d2Pdrho2"
        strDescription = "Calculate (dP/dRHO)^2 of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "dPdT"
        strDescription = "Calculate (dP/dT) of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "dPdTsat"
        strDescription = "Calculate (dP/dTsat) of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "drhodT"
        strDescription = "Calculate (dRHO/dT) of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "dHdT_D"
        strDescription = "Calculate (dH/dT)_D of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "dHdT_P"
        strDescription = "Calculate (dH/dT)_P of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "dHdD_T"
        strDescription = "Calculate (dH/dD)_T of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "dHdD_P"
        strDescription = "Calculate (dH/dD)_P of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "dHdP_T"
        strDescription = "Calculate (dH/dP)_T of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "dHdP_D"
        strDescription = "Calculate (dH/dP)_D of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
        
'Refprop Quality Group
        strCategory = "RefProp Quality"
        
        strFunction = "Cstar"
        strDescription = "Calculate Cstar of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "Quality"
        strDescription = "Calculate Quality of Fluid (fraction vapor)"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "QualityMole"
        strDescription = "Calculate Molar Quality of Fluid (faction vapor)"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "QualityMass"
        strDescription = "Calculate Mass Quality of Fluid (fraction vapor)"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "LatentHeat"
        strDescription = "Calculate Latent Heat of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "HeatOfVaporization"
        strDescription = "Calculate Heat of Vaporization of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "HeatOfCombustion"
        strDescription = "Calculate Heat of Combustion of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "GrossHeatingValue"
        strDescription = "Calculate Gross Heating Value of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "NetHeatingValue"
        strDescription = "Calculate Net Heating Value of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "JouleThomson"
        strDescription = "Calculate Joule Thomson of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "IsentropicExpansionCoef"
        strDescription = "Calculate Isentropic Expansion Coefficient of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "IsothermalCompressibility"
        strDescription = "Calculate Isothermal Compressibility of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "VolumeExpansivity"
        strDescription = "Calculate Volume Expansivity of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "AdiabaticCompressibility"
        strDescription = "Calculate Adiabatic Compressibility of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "AdiabaticBulkModulus"
        strDescription = "Calculate Adiabatic Bulk Modulus of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "IsothermalExpansionCoef"
        strDescription = "Calculate Isothermal expansion coefficient"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "IsothermalBulkModulus"
        strDescription = "Calculate Isothermal Bulk Modulus of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "SecondVirial"
        strDescription = "Calculate Second Virial of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

'Refprop Transport Properties Group
        strCategory = "RefProp Transport"
        
        strFunction = "Viscosity"
        strDescription = "Calculate Viscosity of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "KinematicViscosity"
        strDescription = "Calculate Kinematic Viscosity of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "ThermalConductivity"
        strDescription = "Calculate Thermal Conductivity of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "ThermalDiffusivity"
        strDescription = "Calculate Thermal Diffusivity of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "Prandtl"
        strDescription = "Calculate Prandtl number of Fluid (momentum diffusivity/thermal diffusivity)"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "SurfaceTension"
        strDescription = "Calculate Surface Tension of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "DielectricConstant"
        strDescription = "Calculate Dielectric Constant of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

'Refprop EOS Group
        strCategory = "RefProp Transport"
        
        strFunction = "MolarMass"
        strDescription = "Calculate Molar Mass of Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "EOSMax"
        strDescription = "Calculate EOS Max Temperature for Fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "EOSMin"
        strDescription = "Calculate EOS Min Temperature for fluid"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

'Refprop EOS Group
        strCategory = "RefProp Fluid Names"
        
        strFunction = "LiquidFluidString"
        strDescription = "Calculate Liquid Fluid String"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "VaporFluidString"
        strDescription = "Calculate Vapor Fluid String"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "FluidString"
        strDescription = "Calculate Fluid String"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "PropertyUnits"
        strDescription = "Calculate Property Units"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "ComponentName"
        strDescription = "Calculate Component Name"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "MoleFraction"
        strDescription = "Calculate Mole Fraction"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "MassFraction"
        strDescription = "Calculate Mass Fraction"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "LiquidMoleFraction"
        strDescription = "Calculate Liquid Mole Fraction"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "VaporMoleFraction"
        strDescription = "Calculate Vapor Mole Fraction"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

        strFunction = "LiquidMassFraction"
        strDescription = "Calculate Liquid Mass Fraction"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
        
        strFunction = "VaporMassFraction"
        strDescription = "Calculate Vapor Mass Fraction"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
       
        strFunction = "Activity"
        strDescription = "Calculate Activity of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
       
        strFunction = "ActivityCoefficient"
        strDescription = "Calculate Activity Coefficient of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
               
        strFunction = "ChemicalPotential"
        strDescription = "Calculate Chemical Potential of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
               
        strFunction = "Fugacity"
        strDescription = "Calculate Fugacity of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
               
        strFunction = "FugacityCoefficient"
        strDescription = "Calculate Fugacity Coefficient of Fluid"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
               
        strFunction = "Mole2Mass"
        strDescription = "Convert Mole fractions to Mass Fractions"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
               
        strFunction = "Mass2Mole"
        strDescription = "Convert Mass Fractions to Mole Factions"
        strCat = "RefProp 1"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
               
'Refprop Workbook Functions
        strCategory = "RefProp Workbook"
        
        strFunction = "WorkBookName"
        strDescription = "What is the name of the Workbook"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
               
        strFunction = "RefpropXLSVersionNumber"
        strDescription = "What Refprop XLS version is running"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
               
        strFunction = "RefpropDLLVersionNumber"
        strDescription = "What Refprop DLL version is running?"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
               
        strFunction = "WhereAreREFPROPfunctions"
        strDescription = "Where are the Refprop functions"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
               
        strFunction = "WhereIsWorkbook"
        strDescription = "Where is the Workbook"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
               
        strFunction = "SeeFileLinkSources"
        strDescription = "What are the Sources for the linked files?"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory
                       
        strFunction = "SelectedDefaultUnits"
        strDescription = "Selected default units"
        Application.MacroOptions Macro:=strFunction, Description:=strDescription, Category:=strCategory

End Sub
`

**Comment by ianhbell** [comment]
It would be best if you used the beta of Eric for version 10 and worked with the REFPROP function from the DLL.  All the functions you are playing with here will be deprecated in the new Excel wrapper in favor of a thin Excel wrapper.  Otherwise, it is a maintenance nightmare since you can't version control VBA code.

**Comment by NickAtNight2017** [comment]
Do you have a link to the beta?

**Comment by ianhbell** [comment]
You have to email Eric Lemmon: eric.lemmon@nist.gov

**Comment by ianhbell** [comment]
The key principle for me is to keep the Excel interface as simple as possible.  So that means as little code in the VBA as possible.  If you want to make examples and add other Excel modules that you will personally commit to supporting, go for it !

**Comment by NickAtNight2017** [comment]
Interesting.  I learned a few new tricks.  I cleaned up the display for the test temperature function.

So now the temperature function:
1.  Is listed in the "RefProp Fluid" category
2:  Displays an Example when viewed in the Insert Function box.
3:  Pressing "Help on this Function" loads the Refprop.chm file ...
     ... and opens it to the "Excel Spreadsheets" section.
4:  Displays Examples and a line of help for each of the Function Arguments.

![image](https://user-images.githubusercontent.com/31464824/29990741-286dfa7c-8f43-11e7-8322-50985c215009.png)

`'Refprop Fluid
        strCategory = "RefProp Fluid"
        strFunction = "Temperature"
        strDescription = "Example: =Temperature(" & Chr(34) & "hydrogen" & Chr(34) & "," & Chr(34) & "PS" & Chr(34) & _
            "," & Chr(34) & "SI" & Chr(34) & ",273.15,0.101325)" & Chr(10) & _
            "Calculate the Temperature of the Fluid."

        Application.MacroOptions _
            Macro:=strFunction, _
            Description:=strDescription, _
            Category:=strCategory, _
            HelpFile:="C:\Program Files (x86)\REFPROP\refprop.chm", _
            HelpContextID:=833, _
            HasShortcutKey:=True, _
            ShortcutKey:="T", _
            ArgumentDescriptions:=Array( _
                "Ex: Hydrogen, Butane, or R134a" & Chr(10) & "Enter a valid fluid name", _
                "Ex: TP  Specify first and second property" & Chr(10) & "Props(T,P,D,H,S,E,Q)" & Chr(10) & "or Tliq,Tvap,Pliq,Pvap  ", _
                "Ex: SI" & Chr(10) & "SI, SI with C, E, Molar E," & Chr(10) & "MEunits, Molar SI, mks, cgs, Mixed", _
                "Enter a value for first property specified", _
                "Enter a value for the second property specified")`

**Comment by NickAtNight2017** [comment]
Thank you.  The new Wizard looks great !
