### ISSUE TITLE
Reference state in EXCEL 

### ISSUE THREAD

**Issue by MichalM95** [usnistgov/REFPROP-wrappers#133]
Hello,

I'm trying to change References state in excel to IIR (Enthalpy = 200 kJ/kg, Entropy = 1 kJ/kg*K for the saturated liquid at 0 C)  for all fluids, but I can't. I tried instruction from REFPROP v10:  'o change the default in the Excel file, press Alt-F11 to bring up the VB code.  If the code does not appear, make sure the project explorer is visible (View/Project Explorer), and then click on modules and then on module1.  Search for the call to SETREF, and change the second input from 2& to 1&. ' but change from 2& to 1& or any value change nothing.  Any ideas? 

REFPROP v9,0
Excel 2016

**Comment by EricLemmon** [comment]
Change the code in the VBA (for the section that you discussed above) with the code below and see if it works.  This is a new issue that we did not realize was broken.  We will get it fixed in the Fortran code so that the call to load propane in the new code shown below is not needed.  But for now this change will make all work.

```
        'Use the following lines to set a reference state to one of those available in the REFPROP program.
        'See notes at the top of this section about restarting Excel and saving this file.
        'The call to load propane is needed to deal with an issue in Version 10 that will not set the flag for reference states when a fluid has not been loaded.
          'hFld = "Propane": hIn = "": hOut = ""
          'Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, 2&, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)
          'hIn = "SETREF": hFld = ""
          'hOut = "NBP"  '*****Do NOT use this line with the one below; select only one. Valid inputs are DEF, NBP, IIR, ASH, and NA.
                         'hOut = "OTH; 11.11; 22.22; 298.15; 101.325"    'To set your own reference state, use this line with OTH.  In this example, a reference state of h=11.11 J/mol, S=22.22 J/mol-K, T=298.15 K, and P=101.325 kPa would look like this.  The units for this option are the default REFPROP units.  Do not use the line directly above when using OTH.
          'Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, 2&, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)

```

**Comment by EricLemmon** [comment]
I believe this is fixed now.  Could you send me an email that I can use to send you an updated GUI that you can use to check this?

**Comment by MichalM95** [comment]
Thanks a lot for Your help!

I'm not IT guy so i can make something wrong.

I just open VB window, go to module 1 and saw something like that:
![refprop ref state](https://user-images.githubusercontent.com/48439079/55498259-76f3d680-5643-11e9-875e-dd9455a008ab.png)

then, I took Your code and paste it like that:
![refprop po zmianach](https://user-images.githubusercontent.com/48439079/55498305-93900e80-5643-11e9-85e9-ff875089608a.png)

after that, I save it in VB window and close it and excel. There is no difference. If i change from "NBP" to "IRR" nothing changes.

**Comment by MichalM95** [comment]
I modified code a little and it show an error: 
![errrror](https://user-images.githubusercontent.com/48439079/55501446-b70a8780-564a-11e9-95bc-953e5550484f.png)

**Comment by EricLemmon** [comment]
Can you post your code here so that I can look at it?  Or send it to me directly if you don't want anyone to be able to access it.

**Comment by EricLemmon** [comment]
Have you been able to resolve this issue?  If so, could you close it?  If not, is there more that we can help with?
