### ISSUE TITLE
Add dielectric constant as refpropm variable

### ISSUE THREAD

**Issue by DDGaulke** [usnistgov/REFPROP-wrappers#14]
Please add a possibility to access the dielectric constant of a fluid using the matlab refpropm routine. At the moment there seems to be no associated variable for this property. 

Thank you!

**Comment by ianhbell** [comment]
What variable would you recommend for the dielectric constant?

**Comment by DDGaulke** [comment]
Hi,

We usually use ‘eps’ or ‘epsilon’, but I think it needs to be a one-sign-variable; so, ‘§’ or ‘&’ seem to be still free and should be available on all keyboards?

Thanks!
Diana

**Comment by ianhbell** [comment]
‘&’ it is then.  I’ll do that today.

**Comment by ianhbell** [comment]
Had to be ‘{‘ since ‘&’ was already in use
