### ISSUE TITLE
Whether to support multi-threaded calls？

### ISSUE THREAD

**Issue by wenminluo** [usnistgov/REFPROP-wrappers#148]
Hello,
   Can the exported function in "Refprop.dll" support multi-threaded calls?If not, is there anyone who has implemented it in a special way?

**Comment by ianhbell** [comment]
If two threads will ever, possibly, read from the same files at the same time, you need to make separate copies for each process (REFPROP uses blocking reads). Assume you need to make such copies, unless proven otherwise.

**Comment by alfred-stokespace** [comment]
Thanks @ianhbell prompt as usual.  Can you confirm that linux environment is also limited in the same ways?  ie. is Linux `.so` also not thread-safe and linux `.so` reading fluid files needs copies of those files per-process?

**Comment by ianhbell** [comment]
Yes, it is fundamental problem with the architecture of REFPROP, so all platforms are impacted.
