### ISSUE TITLE
Pure Substance Property Look-up with Entropy and Internal Energy

### ISSUE THREAD

**Issue by julienbarber** [usnistgov/REFPROP-wrappers#15]
Hi! I have been using the MATLAB/REFPROP wrapper provided through GitHub, and it has been great! I am wondering if there is a way to call a pure substance property using entropy (S) as the first input character. I am solving some problems where I know entropy (S) and internal energy (U) and want to find the associated temperature/pressure/density etc. Do you know of any add on or way to build that in to the code?

Thanks!

**Comment by ianhbell** [comment]
Yup, it’s something like (for pressure P and internal energy U):
``` matlab
>> refpropm('T','P',101.325,'U',4,'WATER')
ans =
  273.1605
```
Other combinations (e.g., S,U) follow the same pattern, just replace the 'P' with a 'S' and replace the value of 101.325 kPa with the entropy

**Comment by julienbarber** [comment]
So I have tried that, but it doesnt seem to work. In the refprop code it states:

%       spec1           first input character:  T, P, H, D, C, R, or M
%                         T, P, H, D:  see above
%                         C:  properties at the critical point
%                         R:  properties at the triple point
%                         M:  properties at Tmax and Pmax
%                            (Note: if a fluid's lower limit is higher
%                             than the triple point, the lower limit will
%                             be returned)
%
%       value1          first input value
%
%       spec2           second input character:  P, D, H, S, U or Q
%
%       value2          second input value

It doesnt seem to accept S as the first character at gives the following error:

	>> refpropm('P','S',3000,'U',U2(g),'helium')
	Error using refpropm (line 421)
	Provided value 1 is not P, T, H, D, C, R, or M

Julien Barber
——
Massachussetts Institute of Technology
S.M Candidate, Mechanical Engineering 
Research Assistant
Plasma Science and Fusion Center
jbarber@mit.edu | (857) 452-7007

**Comment by ianhbell** [comment]
Yup, looks like that hasn’t been added to the wrapper yet.  Let me fix that.

**Comment by julienbarber** [comment]
Oh great! Thanks!

JB

**Comment by ianhbell** [comment]
So….  I think I have “fixed” it, but there seem to be some bugs with this function in REFPROP.  If you can use other state variables than u,s, do so.

**Comment by julienbarber** [comment]
Shoot, ya I don't really have a way around it. Do you think it's possible and maybe just needs more time?

Sent from my iPhone

On Sep 29, 2017, at 11:40 AM, Ian Bell <notifications@github.com<mailto:notifications@github.com>> wrote:

So…. I think I have “fixed” it, but there seem to be some bugs with this function in REFPROP. If you can use other state variables than u,s, do so.

**Comment by julienbarber** [comment]
Hi Ian, was there every any success in adding in the entropy lookup?

**Comment by ianhbell** [comment]
The refpropm.m interface has been deprecated in version 10, though it still works, so this issue is being closed.
