### ISSUE TITLE
Problem with Refprop Excel VBA macros calculating dew point pressures

### ISSUE THREAD

**Issue by luckyoneputt** [usnistgov/REFPROP-wrappers#150]
### Description

I am having problems with an Excel program calculating physical properties using REPROP 10.
 
When I generate the dew point pressure for R404A at 70 degree C in REFROP itself I get a value of 3.5725 MPa. However, when I calculate this dew point pressure in Excel I get a value of 3.564011157 MPa i.e. the values do not match.

### Steps to Reproduce

In Excel perform the following:

1. =FluidString10 (with the values for R404A using components and mole fractions) 
2. =REFPROP(“P”, <value from FluidString10>, TQ, SI with C, 70, 1)

**Expected behavior:** [What you expect to happen]

When I generate the dew point pressure for R404A at 70 degree C in REFROP itself I get a value of 3.5725 MPa.

**Actual behavior:** [What actually happens]

However, when I calculate this dew point pressure in Excel I get a value of 3.564011157 MPa.

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 10
**Access Method:** Excel VBA

### Additional Information

BTW: I have noticed that if I use the name as the argument for FluidString10 (i.e. FluidString(“R404A”)) then the values do match but they don’t if it is specified by composition. Can this be explained as, really, I am having the above problem with a custom mixture and cannot get the refprop program and refprop excel values to match.

In the refprop excel spreadsheet I do not seem to be able to specify the custom mixture as an argument as I get an error saying the file cannot be opened. Indeed when I view the contents of C:\Program Files (x86)\REFPROP\MIXTURES I cannot see my custom mixture files. However they are listed in the refprop program. Also, if I attempt to store a new mixture, I can see my custom mixture files in the popup i.e. the contents of the REFPROP\MIXTURES folder then shows the custom mixtures. Can you explain what is going on?

**Comment by EricLemmon** [comment]
If we have answered your question, could you close this issue?  If you have more questions, please let us know.
