### ISSUE TITLE
TRNPRP and TRNECS warnings

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-wrappers#151]
Running RefProp 10.0 on Windows 10 64bit, calling the DLL from Modelica using a wrapper developed by Modelon.

For some ph input, I get a warning from the transport property calculation:
```
[TRNPRP warning -510] Pure fluid correlation out of range; attempted to use ECS method, it generated error: [TRNECS warning -508] Invalid region for viscosity of reference fluid 1. 
```
Would it be possible to enhance this warning to also print the input values, including units? 
It might be this warning is limited due to the wrapper I am using, but looking at the Fortran code I think the warning as shown is printed directly from TRNSP.FOR. 
Again, I cannot reproduce this warning from the RefProp GUI, only when calling from the wrapper. So, getting more information from the warning message would help me with my debugging.

**Comment by EricLemmon** [comment]
I've updated the code to print out something like this, would that be sufficient?

```
[TRNPRP warning -510] Pure fluid correlation out of range; T = 88.0000 K, D = 14.4441 mol/L; attempted to use ECS method, it generated error: [TRNECS warning -508] Invalid region for viscosity of reference fluid 1.  
```

**Comment by thorade** [comment]
Thank you, yes that should already make my debugging a lot easier, closing this issue!
My original input is p and mass based h, but I can convert that back.
