### ISSUE TITLE
Get 

### ISSUE THREAD

**Issue by rpinquie** [usnistgov/REFPROP-wrappers#16]
Hi,

Does anyone know what are the Maltab commands to access the following properties:
- Saturation temperature
- Saturated liquid enthalpy
- Saturated vapour enthalpy

In Xsteam, the commands are XSteam('Tsat_P',P), XSteam('hL_P',P) and XSteam('vL_p',P), respectively.

**Comment by ianhbell** [comment]
'T' for temperature: e.g. ``refpropm('T','P',101.325,'Q',0,'WATER')``
'H' for enthalpy, so to get the liquid enthalpy also provide the vapor quality:  e.g. ``refpropm('H','P',101.325,'Q',0,'WATER')`` for liquid and ``refpropm('H','P',101.325,'Q',1,'WATER')`` for vapor

**Comment by rpinquie** [comment]
Thanks Ian. If I enter the command "refpropm('T','P',200,'Q',0,'WATER')" to get the saturation temperature of water at 2 bars, I get 393.3601 rather than 120.2115.

Do you have any clue why?

Cheers,

Romain

**Comment by ianhbell** [comment]
Temperatures are in K, not C :)

**Comment by rpinquie** [comment]
Indeed, I took me a few minutes to get it... :)
