### ISSUE TITLE
ABFLSHdll not working as expected

### ISSUE THREAD

**Issue by Shishir-Jaiswal** [usnistgov/REFPROP-wrappers#161]
ABFLSHdll not working.

Below is the code snippet.
```
C++
```
#include "pch.h"
#include <iostream>
#include "stdafx.h"
#define REFPROP_IMPLEMENTATION
#define REFPROP_FUNCTION_MODIFIER
#include "REFPROP_lib.h"
#undef REFPROP_FUNCTION_MODIFIER
#undef REFPROP_IMPLEMENTATION

#include <stdlib.h>
#include <stdio.h>

int main()
{
	
	// Load the shared library
	std::string err;
	bool loaded_REFPROP = load_REFPROP(err, L"C:\\Users\\sxj20\\Desktop\\OLD BACKUP\\Old backup 27Mar19\\Refprop to Sysim\\refpropDLLFromPrem", L"REFPRP64.DLL");
	printf("Loaded refprop (in main.cpp): %s @ address %zu\n", loaded_REFPROP ? "true" : "false", REFPROP_address());
	if (!loaded_REFPROP) {
		return EXIT_FAILURE;
	}

	SETPATHdll("C:\\Users\\sxj20\\Desktop\\OLD BACKUP\\Old backup 27Mar19\\Refprop to Sysim\\refpropDLLFromPrem", 400);

        char hfld[] = "R410A.PPF";
	char hln[] = "PT";
	int iMass = 0;
	int iFlag = 100;
	double z[] = {1}, x[] = {1}, y[] = {1}, T = 320.0, p = 2500.0, d = -1, dl = -1, dv = -1, h = 0, s = -1, u = -1, cp = -1, cv = -1, q = -1, w = -1;
	int ierr = 0;
	char herr[255];
	
	SETFLUIDSdll(hfld, ierr, 255);
	ABFLSHdll(hln, p, T, z, iFlag, T, p, d, dl, dv, x, y, q, u, h, s, cv, cp, w, ierr, herr, 2, 255);
	if (ierr > 0) printf("This ierr: %d herr: %s\n", ierr, herr);
	printf("\n %d", d, "\n %d", dl, "\n %d", dv, "\n %d", q);

return EXIT_SUCCESS;
}

### Description

ABFLSHdll should return the density and other properties at P = 2500 kPa and T = 320 K, Although ierr flag is returning no error,

### Steps to Reproduce
1. please run the snippet.

**Expected behavior:** Correct values of outputs. D = 1.3779kmol/m3, h = 31539 kJ/mol, s = 127.41 kJ/kmol-K

**Actual behavior:** Outputs are not correct. Also value of inputs (P and T) are changing at the end of execution. 

### Versions

**REFPROP Version:** REFPROP 10  
**Operating System and Version:** Windows 10  
**Access Method:** C++

**Comment by ianhbell** [comment]
Your strings are all the wrong lengths.  They must be padded out to the correct lengths with spaces, and and you might also want to leave an additional character for the trailing NULL.  

Note: When you make standalone example, please don't use stdafx or PCH -- it makes the example only runnable on windows.

**Comment by ianhbell** [comment]
Also, x, y, and z are all too small (need to be 20 elements).
