### ISSUE TITLE
Python wrapper switch model example

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-wrappers#162]
Can I switch between different models (e.g. VS7 and ECS for Viscosity) from the Python wrapper for RefProp?
If yes, could you point me to an example, or give a short example here?
If no, would there be any workaround? Like, edit the .FLD file, either manually or from Python? 
Could you also give instructions what to change in the FLD file? Swap `#ETA` and `@ETA` ??
Thanks!

The end goal is to do a contour plot for comparing VS7 viscosity versus ECS viscosity for R1234yf, similar to this:
![eta](https://user-images.githubusercontent.com/314571/56735129-e6517780-6764-11e9-97b0-61f71d2c38c5.png)

Currently, values are stored in Python variables, but storing in .csv files would also be fine, if that makes things easier.
I would be happy to share this as a jupyter notebook once done!

**Comment by EricLemmon** [comment]
One way would be to make a copy of the fluid file, and then inside of the copied file switch the @ and # signs on the two different models.  You could then load a "mixture" of the two files, set the composition to 0,1 or 1,0 to switch back and forth, and calculate the properties of each.  That way there's no reloading the fluid files once SETUP has been called.

**Comment by thorade** [comment]
Thank you! 
That sounds like a sufficient workaround, I am closing this issue.
I will still report back once I have some progress!
