### ISSUE TITLE
HEMAXX from python wrapper

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-wrappers#163]
The following ph digram for R1234yf is taken from the Akasaka 2010 paper:
https://doi.org/10.1016/j.ijrefrig.2009.09.004
![R1234yf_ph_Akasaka2010_max](https://user-images.githubusercontent.com/314571/56719290-bd1ef000-6740-11e9-910c-0d185c3f3d8d.png)

Marked in pink is the maximum saturated vapour enthalpy (does this point have a special name?). 
The `SATH` routine in `SAT_SUB.FOR` calls the `HEMAXX` routine to get this point.
Is that routine also callable from the python wrapper?

In the RTD pages I could not find HEMAXX mentioned:
https://refprop-docs.readthedocs.io/en/latest/search.html?q=hemaxx

**Comment by EricLemmon** [comment]
I don't know if it has a name, but perhaps we could make up one, similar to cricondenbar and cricondentherm.  How about cricondenthalp?

The value is not available through the DLL, but could perhaps be added, either through the PASSCMNdll routine or the REFPROPdll routine (via ALLPROPS).  Do you have a preference?

**Comment by thorade** [comment]
cricondenthalp sounds reasonable, and also makes a good keyword for searching the code.

I would be interested in being able to call that function, I do not have a preference through which routine, because I do not yet understand how these two work, and what is the difference, sorry.

**Comment by ianhbell** [comment]
Or how about hmaxcond?

**Comment by thorade** [comment]
Also good :-)

**Comment by EricLemmon** [comment]
This has now been added to the fortran code and DLL, along with values for the entropy.  Below are all the comments I added to the ALLPROPS routine to explain what is available, along with some details about entropy maximums and minimums because of the complexity involved.
```
c    HMAXT      T at maximum saturation enthalpy               [K]                      [K]
c    HMAXD      D at maximum saturation enthalpy               [mol/dm^3]               [kg/m^3]
c    HMAXH      Maximum saturation enthalpy                    [J/mol]                  [kJ/kg]
c    For maximum and minimum entropies, multiple states are possible.
c    For example, for butane, a maximum entropy along the saturated vapor line occurs near 398 K, at which point
c      the saturation curve heads towards a minimum entropy at 272 K, and then the entropy increases with a true EOS
c      maximum at the vapor triple point.  The true EOS minimum entropy occurs at the triple point in the liquid phase.
c    For ammonia, the liquid triple point entropy is not the lowest possible value, rather this state happens along
c      the melting line at 204 K (about 9 degrees above the triple point temperature).  In the vapor phase, ammonia
c      does not bend backwards as with butane, but simply increases till it hits the triple point.
c    For docosane, the entropy at the vapor triple point is actually less than that at the highest saturation root.
c    The values for the liquid or vapor at the triple point are not returned here since those values can be obtained
c      directly from the EOS at Ttrp.
c    For all fluids, making a T-S plot in the GUI will show its behavior, which varies widely from fluid to fluid.
c    Values of -1 for the temperatures will be returned if no root exists.
c    TMAXS      T at maximum saturation entropy                [K]                      [K]
c    DMAXS      D at maximum saturation entropy                [mol/dm^3]               [kg/m^3]
c    SMAXS      Maximum saturation entropy                     [J/(mol*K)]              [(kJ/kg)/K]
c    TMINS      T at minimum saturation entropy                [K]                      [K]
c    DMINS      D at minimum saturation entropy                [mol/dm^3]               [kg/m^3]
c    SMINS      Minimum saturation entropy                     [J/(mol*K)]              [(kJ/kg)/K]
c    TMINSM     T at minimum melting entropy                   [K]                      [K]
c    DMINSM     D at minimum melting entropy                   [mol/dm^3]               [kg/m^3]
c    SMINSM     Minimum melting entropy                        [J/(mol*K)]              [(kJ/kg)/K]
```

Let me know if you want the updated DLL!

**Comment by thorade** [comment]
Thank you very much and sorry for getting back late. We are using a workaround for now, so I do not need the updated DLL for now. 
Closing this issue, as it seems to be done.

**Comment by thorade** [comment]
just a note: maximum saturation enthalpy (on saturated vapour line) is referred to as **maxcondenthalp** in this paper
https://docs.lib.purdue.edu/iracc/2258/
