### ISSUE TITLE
Refprop 10: Need to build our projects in .net framework 4.0 and above, I am facing problems with Refprp64 bit dll.

### ISSUE THREAD

**Issue by krushnaeicp** [usnistgov/REFPROP-wrappers#166]
### Description

**Refprop 10:** Need to build our projects in .net framework 4.0 and above, I am facing an problems with Refprp64 bit dll. Attached is the complete code.

### Steps to Reproduce

1) Open the attached solution in Visual studio 2010 or higher IDE and click on the calculate button.
2) On the click of Calculate button, I am trying to calculate saturated temperature at specified pressure for CO2 fluid. The attached code is running fine, If I select Refprop 32 bit dll and .net framework 3.5 and x86 build settings but failing with Refprp64 bit and .net framework 4.0 and above.
3) I have selected .net framework 4.0 with different build options like x86, x64, Any CPU but getting different errors. Please try running the source code at various build settings, .net framework version and refprop dll (32 bit or 64 bit - enable in code) and see the errors.

**Expected behavior:** 
I should get the saturated temperature value as ~41.54F

**Actual behavior:** 
Getting Different errors if I switch between Refprop dll version + .Net Framework version + Build settings (x86, x64, Any CPU)

### Versions

**REFPROP Version:** Refprop 10 64 bit version
**Operating System and Version:** Windows 7 Professional Service Pack 1, 64 bit OS
**Access Method:** .Net 4.0 Windows form application (Later will be converted into class library dll)
### Additional Information

If possible, please post examples and/or screenshots of the issue.
[PerfDLLRefProp10_ForNIST.zip](https://github.com/usnistgov/REFPROP-wrappers/files/3155962/PerfDLLRefProp10_ForNIST.zip)

**Comment by ianhbell** [comment]
Have you tried to use the wrappers from here: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Csharp ? Please try that first, as they do the hard work for you.
