### ISSUE TITLE
Use refprop.m (REFPROP 9.1) in Matlab 19a

### ISSUE THREAD

**Issue by RinaldoMiorini** [usnistgov/REFPROP-wrappers#168]
I want to call refpropm.m (REFPROP 9.1) in a Matlab 19a script. 
Copied refpropm.m in work folder.
Tried it out on command line:

>> refpropm('D','T',273,'P',101,'air.mix')
Error using refpropm/get_header_path (line 745)
Could not find header file for loading library
Error in refpropm (line 224)
        prototype = get_header_path();

I suspect I need to do some prep work on Matlab (maybe copy some files in MATLAB/toolbox) in order for this to work. I can find info only on REFPROP 10 / python wrapper.

If anybody could reply with the complete workflow (what files besides refpropm.m and where to copy them) I would appreciate it!

Thanks!

**Comment by ianhbell** [comment]
Please see https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB.  The refpropm file is deprecated, and only the python interface for MATLAB is actively supported.  It still works with the functions from REFPROP 9.1

**Comment by RinaldoMiorini** [comment]
I have issues setting up the wrapper.

Matlab sees Python, [...] means I cannot disclose:

> pyversion
> 
>     version: '3.7'
>     executable: 'C:\Users\[...]\python.exe'
>     library: 'C:\Users\[...]\python37.dll'
>     home: 'C:\Users\[...]'
>     isloaded: 0

But I have issues with ctREFPROP:

>> [v,e] = pyversion; system([e,' -m pip install --proxy=[...]:8080 --user -U ctREFPROP'])
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. 
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Could not fetch URL https://pypi.org/simple/ctrefprop/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ctrefprop/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping 
Requirement already up-to-date: ctREFPROP in c:\users\212350863\appdata\local\continuum\anaconda3dot7\lib\site-packages (0.7.3) 
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. 
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping 

ans =

     0


this works:

>> RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')

RP = 

  Python REFPROPInstance with properties:

               dll: [1×1 py.ctypes.WinDLL]
    managed_handle: [1×1 py.NoneType]

    <ctREFPROP.ctREFPROP.REFPROPInstance object at 0x0000000004941A58>

>> RP.RPVersion()

ans = 

  Python str with no properties.

    9.1


but this does not:

r = RP.REFPROPdll('Water','PQ','T',int8(0),int8(0),int8(0),101.325,0.0,{1.0})
Error using ctREFPROP>REFPROPdll (line 2479)
Python Error: ValueError: The function REFPROPdll could not be loaded from the shared library.


Looks like I have issues loading ctREFPROP but the proxy is set correctly in the line [v,e] = ...

Please help, thanks!

**Comment by ianhbell** [comment]
That is correct.  With REFPROP 9.1, the REFPROPdll function is not available.  I would recommend to upgrade to version 10, or read the docs for the legacy interface (available in 9.1): https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html

**Comment by ianhbell** [comment]
MATLAB seems to modify the system PATH variable, breaking SSL support in Python.  You may need to install python from an Anaconda prompt (rather than from within MATLAB), with ``pip install -U ctREFPROP``

**Comment by ianhbell** [comment]
Please see https://github.com/usnistgov/REFPROP-wrappers/commit/d09be07b878f0add47b869e6bf925d5dd537bad6

**Comment by ianhbell** [comment]
REFPROP 9.1 is working fine.  It's just that the new functions we introduced in REFPROP 10 (https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html) are not included in REFPROP 9.1

**Comment by RinaldoMiorini** [comment]
I followed the instructions from d09be07 and installed the wheeler successfully from Anaconda prompt.

(base) C:\Users\212350863>pip install -U C:\ctREFPROP-0.7.3-py3-none-any.whl
Processing c:\ctrefprop-0.7.3-py3-none-any.whl
Installing collected packages: ctREFPROP
Found existing installation: ctREFPROP 0.7.3
Uninstalling ctREFPROP-0.7.3:
Successfully uninstalled ctREFPROP-0.7.3
Successfully installed ctREFPROP-0.7.3

then in Matlab v19:

RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')

RP =

Python REFPROPInstance with properties:

managed_handle: [1×1 py.NoneType]
           dll: [1×1 py.ctypes.WinDLL]

<ctREFPROP.ctREFPROP.REFPROPInstance object at 0x00000001545F1B00>
RP.RPVersion()

ans =

Python str with no properties.

9.1
r = RP.REFPROPdll('Water','PQ','T',int8(0),int8(0),int8(0),101.325,0.0,{1.0})
Error using ctREFPROP>REFPROPdll (line 2479)
Python Error: ValueError: The function REFPROPdll could not be loaded from the shared library.

is there a way to make REFPROP 9.1 work?

Thanks!

**Comment by ianhbell** [comment]
Please see my comment above.

**Comment by RinaldoMiorini** [comment]
Ok so I ended up purchasing REFPROP 10, I know I should read all the notes about the wrapper but could you tell me why the lines below do not provide the correct density of water at 25 degC and almost ambient pressure? Also, what is the meaning of the last argument {1.0} in the subroutine calling REFPROP?

>> RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
>> LookUpRefprop = RP.REFPROPdll('Water','TP','D',int8(0),int8(0),int8(0),298,101,{1.0});
>> State = double(LookUpRefprop.Output);
>> Density = State(1);
>> Density

Density =

   55.3467


Thanks!

**Comment by RinaldoMiorini** [comment]
It seems like "q" contains the right answer but I can't get the parallel with your example that calculates the water's boiling point... :(

**Comment by ianhbell** [comment]
@RinaldoMiorini please don't hijack existing issues, rather open a new one.  

You are have specified the DEFAULT units system.  Therefore your outputs are in molar units

**Comment by ianhbell** [comment]
The last argument is the array of (in this case), mole fractions.

**Comment by ianhbell** [comment]
@RinaldoMiorini Sorry I didn't realize that you were adding onto your own issue.  That's my mistake and I shouldn't have been so curt with you.
