### ISSUE TITLE
PHFlash convergence issue

### ISSUE THREAD

**Issue by GZALAT** [usnistgov/REFPROP-wrappers#169]
Hello,
I tried to calculate an isenthalpic expansion of a subcooled liquid for a molar mixture of 1%N2 and 99%CH4; the fluid should remain single phase. In Refprop 9.1108 this works well, but in v10 the error message 
"#[PHFLSH error 248] Single-phase iteration did not converge for P = 0.115000 MPa and H = -348.404 J/mol." is returned (see attached file).
[PHFlash Issue.xlsx](https://github.com/usnistgov/REFPROP-issues/files/3153476/PHFlash.Issue.xlsx)
When activating GERG the flash calculates well, but this is no viable workaround.
Thank you

### Versions

**REFPROP Version:** v10
**Operating System and Version:** Win10
**Access Method:** MSExcel 2013

**Comment by EricLemmon** [comment]
I transferred your issue to the Refprop-wrappers github site since this deals with Excel.

To make this work, see the information at #106.

**Comment by GZALAT** [comment]
Thank you - this works out for some cases but still seems to be less stable than in v9.1

**Comment by EricLemmon** [comment]
Can you give me a specific example so that I can debug into the code to try to find the problem?  Just one example is enough, don't send a list of everything that does not work.

**Comment by GZALAT** [comment]
If you take the Excel file I joined to my initial message, then with 1.01% N2 instead of 1%N2 I get the error 248 with both iFlag=0 and iFlag=1
Thank you

**Comment by EricLemmon** [comment]
In processing old issues, I realized I never addressed this one (unless we did it via email).  I checked now and the points all converged here, at least through the Fortran code. 
...
I just now tried it in Excel as well, and with iFlag=1 then it also works.

If you wish an updated DLL, email me at eric.lemmon@nist.gov

**Comment by GZALAT** [comment]
I just got the automatic reply from your email account, so I post
the message here, too:
I still have this convergence problem under MS Excel, with both states for
the iFlag option. So if you have an updated dll that converges better, I'd
really appreciate it if you could send me a copy.

Golo ZICK

---------- Forwarded message ---------
De : ZICK, Golo <golo.zick@airliquide.com>
Date: mer. 15 juil. 2020 à 08:52
Subject: Re: [usnistgov/REFPROP-wrappers] PHFlash convergence issue (#169)
To: Eric W. Lemmon <eric.lemmon@nist.gov>


Hello,
Thank you very much for reopening this issue. I still have this convergence
problem under MS Excel, with both states for the iFlag option. So if you
have an updated dll that converges better, I'd really appreciate it if you
could send me a copy.
Best regards,

Golo ZICK Process Simulation Group / Innovation Department

2 rue de Clémencière

BP 15 - 38360 Sassenage - France

Tel: +33 (0)4 76 43 66 38
Mob: +33 (0)6 26 32 65 63 www.airliquideadvancedtechnologies.com
