### ISSUE TITLE
TwoPhaseFluidTables function error

### ISSUE THREAD

**Issue by rpinquie** [usnistgov/REFPROP-wrappers#17]
Hello,

When I enter the command
`twoPhaseFluidTables([30,4000],[0.01,15],25,25,60,'propene','C:\Program Files (x86)\REFPROP')`, I get the error:

> Error using twoPhaseFluidTables>refpropInitialize (line 285)
> REFPROP file propene.fld or propene.ppf cannot be found in C:\Program Files (x86)\REFPROP\fluids.
> 
> Error in twoPhaseFluidTables (line 95)
> [libName, molw] = refpropInitialize(refpropPath, substance);

Do you have any idea why?

Romain

**Comment by ianhbell** [comment]
No idea, what version of MATLAB do you use?  Is it a case-sensitivity problem? It shouldn't be though because windows is basically not case sensitive.



________________________________

**Comment by rpinquie** [comment]
R2017a. According to the MAthWorks support team (https://fr.mathworks.com/matlabcentral/answers/348295-why-do-i-get-an-error-when-using-twophasefluidtables-with-refprop-9-1-1-in-simscape-fluid-r2017a), REFPROP 9.1.1 changed the function signature of the MATLAB interface functions. But I can't figure out what has really changed...

**Comment by ianhbell** [comment]
I'm afraid you will have to take this up with Mathworks, we are not in the business of supporting MATLAB libraries.

________________________________
