### ISSUE TITLE
Include Refprop in C++

### ISSUE THREAD

**Issue by KayvanA** [usnistgov/REFPROP-wrappers#170]
I would like to use Refprop in C++. Ideally, I would like to have a small code where I call Refprop to give me the properties of R410A refrigerant. The function I would be calling the most will be REFPROP1. For example, the Fortran version of this code is shown below. I would like to create something similar in C++.

``` FORTRAN
program test_call
      implicit none
      integer, parameter :: ncmax=20
      integer, parameter :: ipropmax=200
      double precision x(ncmax),y(ncmax),x3(ncmax),z(ncmax)
      double precision P,T,V,Output,q,qcalc
      dimension Output(ipropmax)
      integer iUnit,iMass,ierr,iFlag,iOut
      character*255 hOut,herr
  
      call GETENUM(0,'SI with C',iUnit,ierr,herr) ! SI with C; 
      iMass=1 ! Mass basis properties
  
      call REFPROP ('R410A',' ',' ',iUnit,iMass,0,
     &              0d0,0d0,z,Output,hout,iOut,x,y,x3,q,ierr,herr) 
  
      T=20 ! Celsius
      q=1  ! quality
      call REFPROP1('TQ','P',iUnit,iMass,T,q,z,P,qcalc,ierr,herr)
      Print *,'Dew-point pressure at the temperature',T,' (Celsius)is: ',P,'(MPa)'
end
```

I have downloaded all the files from the link below and added them to the Source Files of my C++ project. 
https://github.com/CoolProp/REFPROP-headers

However, when I compile the project (Build Solution) I get this error in refprop_lib.h, line 737:

error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

Could you please help me?

Thanks,
Kayvan

**Comment by ianhbell** [comment]
That is just a warning...  Unless you have forced your compiler to convert all warnings to errors (I wouldn't recommend that).  You can also define that preprocessor macro and the error would go away.

In Python your example would be: 
``` python
# Setup
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root+'/REFPRP64.DLL') ;
RP.SETPATHdll(root)
MOLSI = RP.GETENUMdll(0,'MOLAR BASE SI').iEnum

# Do calculation
q = 1 # [-]
T = 293.15 # [K]
iMass = 0
RP.SETFLUIDSdll('R410A.PPF')
r = RP.REFPROP1dll('QT','P', MOLSI, iMass, q, T, [1.0]+[0.0]*19)
print(r)
```

**Comment by KayvanA** [comment]
ok, I turned that warning off in the C++ PreProcessor. But now I get another error: 

> Unhandled exception at 0x73B7CB49 in Refprop_test.exe: 0xC0000005: Access violation executing location 0x00000000.

This error pertains to the command:

` SETUPdll(nc,hfld,hhmx,href,ierr,herr,10000,255,3,255);`

which is in the subroutine below.

`void another_file()`

**Comment by ianhbell** [comment]
You didn’t load REFPROP successfully, which is why the SETUPdll call fails.  Did you call the load_REFPROP function?  What preprocessor macros did you define around the include of REFPROP_lib.h?  Start with the example in the repo and build from there I would recommend.

**Comment by KayvanA** [comment]
I did not make any function calls, i.e. I did not develop any code, yet. All I did was copied all the files from the Repo, from the link below. Once I have a working example, I can trim it to my need, probably for R410A. Should I add something else to the project to make it work?

https://github.com/CoolProp/REFPROP-headers

**Comment by KayvanA** [comment]
To be more specific, the only C++ codes that are included in my project are main.cpp and other.cpp , which I got from the Repo link in my previous comment. I have also '_Added_' all the other files from that link into the '_Source Files_' of my project. Please let me know if I am doing something wrong. Thanks.

**Comment by ianhbell** [comment]
Does the sample code that is in REFPROP-headers work for you?  Please make sure that code runs first.  Then, and only then, add your changes for REFPROP1dll

**Comment by KayvanA** [comment]
I think are referring to the two C++ files that are in Refprop headers: main.cpp and other.cpp

Unfortunately, no, they did not work. I have included all the other files in Refprop-headers in my project.

I have not made any changes to any of the codes that I downloaded.

**Comment by ianhbell** [comment]
Add the files main.cpp and other.cpp to a new project in C++.  Add the REFPROP_lib.h file  to the same folder.  Compile.  Please report any errors.  That is step #1.  Then comes everything else.

**Comment by KayvanA** [comment]
I followed your steps precisely. Yet, I got the same error as before. Please see the attached pictures. One of them shows the files that I have included in my project, and the other one shows the error. I also tried copying the REFPROP_lib.h file into the project folder and the project solution folder, but I still got the same error.

![files](https://user-images.githubusercontent.com/16560926/57810166-cb9f6c80-772c-11e9-9eb5-d1f053a753a5.PNG)



![error](https://user-images.githubusercontent.com/16560926/57810178-d0fcb700-772c-11e9-8b16-08b5572dc5ba.PNG)

**Comment by KayvanA** [comment]
I should mention that the project does compile successfully. However, when I run it, I get the aforementioned error.

**Comment by ianhbell** [comment]
You need to change the path to your REFPROP installation in the call to load_REFPROP.  There would have been output in the shell to that effect.  It would have to told you that REFPROP didn't load, which is why the pointers are all NULL pointers.

**Comment by KayvanA** [comment]
I changed the path to my Refprop folder in the command, as shown below:

 bool loaded_REFPROP = load_REFPROP(err, "C:\Program Files (x86)\REFPROP", "REFPRP64.DLL");

Here is the folder that Refprop is installed, so I copied the same folder name into the command above.

![RefpropPath](https://user-images.githubusercontent.com/16560926/57862917-c2f77680-77be-11e9-8184-625ca556e23d.PNG)


However, I still got the same error as before. The shell output is in the attached picture below.

![shell_output](https://user-images.githubusercontent.com/16560926/57862887-b70bb480-77be-11e9-9ae7-53242b747dd5.PNG)

It seems that I need a separate subroutine called **load_Refprop**. Is it in REFPROP_lib.h? I have included that file both in my project folder, solution folder,  and also '_added_' it to the project '_Source Files_' as shown below.

![1](https://user-images.githubusercontent.com/16560926/57865374-179cf080-77c3-11e9-9ec4-9214f8b1300e.PNG)

![2](https://user-images.githubusercontent.com/16560926/57865385-1d92d180-77c3-11e9-9979-b283f9588231.PNG)

![project_source_files](https://user-images.githubusercontent.com/16560926/57865869-fa1c5680-77c3-11e9-85f1-72f06539eff1.PNG)

So, unfortunately, the project still does not run.

**Comment by ianhbell** [comment]
Hmm... That's weird.  It should have worked.  Is your project 32-bit or 64-bit?  If 32-bit, you want to load REFPROP.DLL rather than REFPRP64.DLL.

**Comment by KayvanA** [comment]
Where should I check if my project 32-bit or 64-bit?

Under the Linker->Input, I see a bunch of files that end in 32.lib. Please see the below picture.

![3](https://user-images.githubusercontent.com/16560926/57868330-64cf9100-77c8-11e9-89f9-70643af27e82.PNG)

Also, there is a drop-down menu at the top of the editor, which reads **Win32**, as shown below.

![4](https://user-images.githubusercontent.com/16560926/57868438-99434d00-77c8-11e9-8dce-f56fd8af7e8f.PNG)
If I click on it, then I can go to '_Configuration Manager..._', shown below. Should I change something there? If so, could you please tell me what I should type and where? Thanks.

![5](https://user-images.githubusercontent.com/16560926/57868511-bd069300-77c8-11e9-99d9-a7c5bc34c8a2.PNG)

![6](https://user-images.githubusercontent.com/16560926/57868518-c1cb4700-77c8-11e9-9e9d-5895e0a6f41e.PNG)

I also changed REFPRP64.DLL to REFPROP.DLL. However, I still got the same error.

![7](https://user-images.githubusercontent.com/16560926/57868850-5d5cb780-77c9-11e9-9d8d-c9ca5bc851ca.PNG)

**Comment by ianhbell** [comment]
You have selected a Win32arch (as opposed to an x64 arch), therefore it is 32-bit.

**Comment by KayvanA** [comment]
I don't see the word "_Win32arch_" anywhere, but I take your word for it. In any event, unfortunately, when I switched REFPRP64.DLL to REFPROP.DLL to account for the 32-bit architecture, the project still did not work.

**Comment by ianhbell** [comment]
You picked the Win32 architecture in Visual Studio, therefore your build is 32-bit.

**Comment by ianhbell** [comment]
What error this time?

**Comment by KayvanA** [comment]
I got the same error:

![8](https://user-images.githubusercontent.com/16560926/57869751-520a8b80-77cb-11e9-8385-de52d2f0c856.PNG)

**Comment by ianhbell** [comment]
Hum.  It seems like you had REFPROP 9.1 installed and then installed REFPROP 10.  I never do that, and I always fully uninstall REFPROP 9.1 first.  But I doubt that is the problem.

Did you try forward-slashes in the path?  Sometimes windows doesn't like backslashes.. 

I made some updates to main.cpp and other.cpp and it works for me. 

Open a command prompt
1. git clone https://github.com/CoolProp/REFPROP-headers
2. cd REFPROP-headers
3. mkdir msvc
4. cd msvc
5. cmake .. -G "Visual Studio 14 2015 Win64"
6. Open the Visual Studio .sln, change the path to REFPROP as needed
7. Build, compile, run

You'll need to install git and cmake if not already installed, google for more info.

**Comment by KayvanA** [comment]
I downloaded git and cmake. I opened a command prompt and entered the lines that you wrote. But I get an error for cmake. Please see the below screenshot.

![9](https://user-images.githubusercontent.com/16560926/57882523-81c88c00-77e9-11e9-9a09-8e6b72ea66da.PNG)


Before I opened the command prompt, I had unzipped the cmake, which gave me the folder shown below. I cannot find an install file in the cmake folder. It is sitting in my Downloads folder. Should I move this to a specific folder?

![10](https://user-images.githubusercontent.com/16560926/57882528-84c37c80-77e9-11e9-9aee-056c82f88a40.PNG)

**Comment by KayvanA** [comment]
Also, a side note: I don't have Refprop 9.1 on my laptop. I am pretty sure that either I uninstalled it myself before I install the 10.0 version, or the install process asked me to uninstall it. Below is a screenshot of the programs list in the Control Panel, which shows I have the 10.0 version only.

![11](https://user-images.githubusercontent.com/16560926/57883005-ab35e780-77ea-11e9-82d6-9d138935c551.PNG)

**Comment by ianhbell** [comment]
https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4-win64-x64.msi

**Comment by KayvanA** [comment]
Thank you, Ian. I downloaded and installed cmake. I repeated the cmake command in the Command Prompt. But it gave me the same error.

![12](https://user-images.githubusercontent.com/16560926/57885411-82185580-77f0-11e9-8bfd-fe1646be6f49.PNG)


should I close the command prompt and start over? I assume if I do so, then I should skip some steps?

**Comment by ianhbell** [comment]
You may need to open a new shell, the PATH environment variable gets set at the start of shell session.

In a new shell, do: cmake -version

to make sure it is properly installed
