### ISSUE TITLE
Problem in calculating predefined mixture properties in Python

### ISSUE THREAD

**Issue by kbansal13** [usnistgov/REFPROP-wrappers#171]
### Description

Using Refprop 10 wrapper with Python 3.7. Not able to calculate predefined mixture properties using the REFPROPdll subroutine.

### Steps to Reproduce

1. Run the example below.

**Expected behavior:** [Expect to calculate fluid properties (in this case saturated vapor and liquid pressures at the two specified temperatures) for all the 4 REFPROPdll calls.]

**Actual behavior:** [Program is calculating the pressure for the very first REFPROPdll call only. The following three calls output error values.]

### Versions

**REFPROP Version:** [REFPROP 10]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [Python3.7]  

### Additional Information

Example Python code:
``` python
import os; os.environ['RPPREFIX'] = r'C:/Program Files (x86)/REFPROPPy'
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

## Setup Refprop
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
ENGLISH = RP.GETENUMdll(0,"ENGLISH").iEnum


## Variable Model Inputs
fluid_base = "R404A.MIX"
T_dew_evap = -10
T_dew_cond = 95

## Saturation Temperatures and Pressures
P_evap_vap = RP.REFPROPdll(fluid_base,"TQ","P",ENGLISH,1,0,T_dew_evap,1,[0.44,0.04,0.52]).Output[0]
P_evap_liq = RP.REFPROPdll(fluid_base,"TQ","P",ENGLISH,1,0,T_dew_evap,0,[0.44,0.04,0.52]).Output[0]
P_cond_vap = RP.REFPROPdll(fluid_base,"TQ","P",ENGLISH,1,0,T_dew_cond,1,[0.44,0.04,0.52]).Output[0]
P_cond_liq = RP.REFPROPdll(fluid_base,"TQ","P",ENGLISH,1,0,T_dew_cond,0,[0.44,0.04,0.52]).Output[0]

print ('P_evap_vap = ',P_evap_vap,'[PSIA]')
print ('P_evap_liq = ',P_evap_liq,'[PSIA]')
print ('P_cond_vap = ',P_cond_vap,'[PSIA]')
print ('P_cond_liq = ',P_cond_liq,'[PSIA]')
```

Output:

P_evap_vap =  38.3213514191496 [PSIA]
P_evap_liq =  -9999990.0 [PSIA]
P_cond_vap =  -9999990.0 [PSIA]
P_cond_liq =  -9999990.0 [PSIA]

**Comment by ianhbell** [comment]
Your first problem is the units system :)   But really, the internal calculations of REFPROP are always in molar SI units, so that is the first thing you should check to isolate the issue.

I think you might be getting bit by the molar fractions bug again.  Can you please try the same calculations but not specifying the composition?  Specifying the predefined mixture should be enough.

**Comment by ianhbell** [comment]
Hum, I get (from your code, just changing the path to REFPROP).  Do you also have REFPROP 9.1 installed on this machine? I think there might some clash with REFPROP versions.  For that reason I always call SETPATHdll after loading the DLL

My output:
```
P_evap_vap =  38.32135141910902 [PSIA]
P_evap_liq =  39.25578027274587 [PSIA]
P_cond_vap =  232.80268606107214 [PSIA]
P_cond_liq =  234.8937446692968 [PSIA]
```

**Comment by kbansal13** [comment]
Strange that it works on your computer. I do not have any other version of Refprop installed. I tried changing units, removing mass fractions, and changing path, but nothing solved the issue. Interestingly, the same code works fine with pure fluids. I don't know if it is relevant, but I should mention that calling RP.RPVersion() gives *****.

**Comment by ianhbell** [comment]
Can you please email me for a patch (ian.bell@nist.gov<mailto:ian.bell@nist.gov>)?  That will fix at least RPVersion, and maybe more.

**Comment by kbansal13** [comment]
Ian, thanks for sharing the patch. It did solved the version issue, but the property calculation issue with pre-defined mixtures is still there. Please let me know if you have any other inputs.

**Comment by ianhbell** [comment]
Are you 32-bit or 64-bit?

**Comment by kbansal13** [comment]
My operating system is 64 bit and the Python 32 bit.

**Comment by ianhbell** [comment]
I would use 64-bit Python (doesn’t make sense to use 32-bit unless your OS is).  Then we could have what should be a one-to-one comparison.  In theory both 32-bit and 64-bit would be identical, but you never know…

**Comment by ibell** [comment]
Please see https://github.com/CoolProp/CoolProp/issues/1829 .  This is a bug in REFPROP in that a lower-case fluid file is being used in the SETUP, whereas REFPROP should have used an uppercase fluid.

**Comment by kbansal13** [comment]
I tried installing 64-bit Python, it didn't solved the issue either. For now, I am switching to CoolProp, as it seems to be working fine. Thanks.

**Comment by ianhbell** [comment]
I think there is something funny with your installation of REFPROP.  I would reinstall if it were me.

**Comment by abehfar** [comment]
Hello all, 

I get a similar issue for R448A and air mixture. Calling REFPROPdll mostly results in -9999990 values. Any help is appreciated. Thank you.

`import os, numpy as np
import math
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RP = REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP\REFPROP.DLL')
RP.SETPATHdll(os.environ['RPPREFIX'])
English = RP.GETENUMdll(0, "English").iEnum
z_air = [0.7812, 0.0092, 0.2096]
z_448 = [0.431218202, 0.186914131, 0.151319256, 0.177586674, 0.052961736]

def wsh(ref, Tri, Pri, Tai):

    cpa = RP.REFPROPdll("Air.mix", "TP&", "CP", English, 0, 0, Tai, 14.7, z_air).Output[0]
    airvis = RP.REFPROPdll("Air.mix", "TP&", "VIS", English, 0, 0, Tai, 14.7, z_air).Output[0]
    aird = RP.REFPROPdll("Air.mix", "TP&", "D", English, 0, 0, Tai, 14.7, z_air).Output[0]
    cpr = RP.REFPROPdll(ref, "TP", "CP", English, 0, 0, Tri, Pri, z_448).Output[0]
    eta = RP.REFPROPdll(ref, "PQ", "VIS", English, 0, 0, Pri, 1, z_448).Output[0]
    rho = RP.REFPROPdll(ref, "PQ", "D", English, 0, 0, Pri, 1, z_448).Output[0]
    tdewr = RP.REFPROPdll(ref, "PQ", "T", English, 0, 0, Pri, 1, z_448).Output[0]
    return cpa

output = wsh("R448A", 150, 250, 80)
print (output)`

**Comment by abehfar** [comment]
I get the following error:
813 [REFPROP error 813] The input composition must match that of the predefined mixture when the mixture name is included in the call to REFPROP.  To use a different composition, leave the fluid name blank. -9999990.0

How not to specify the composition (z array) for a pre-defined mixture?

**Comment by EricLemmon** [comment]
For predefined mixtures you do not need to enter the composition.

Actually, it's better to not send it the mixture name each time.  This would be best:

```
cpa = RP.REFPROPdll("Air.mix", " ", " ", English, 0, 0, Tai, 14.7, z_air).Output[0]
cpa = RP.REFPROPdll(" ", "TP&", "CP", English, 0, 0, Tai, 14.7, z_air).Output[0]
airvis = RP.REFPROPdll(" ", "TP&", "VIS", English, 0, 0, Tai, 14.7, z_air).Output[0]
aird = RP.REFPROPdll(" ", "TP&", "D", English, 0, 0, Tai, 14.7, z_air).Output[0]
cpr = RP.REFPROPdll(ref, " ", " ", English, 0, 0, Tri, Pri, z_448).Output[0]
cpr = RP.REFPROPdll(" ", "TP", "CP", English, 0, 0, Tri, Pri, z_448).Output[0]
eta = RP.REFPROPdll(" ", "PQ", "VIS", English, 0, 0, Pri, 1, z_448).Output[0]
rho = RP.REFPROPdll(" ", "PQ", "D", English, 0, 0, Pri, 1, z_448).Output[0]
tdewr = RP.REFPROPdll(" ", "PQ", "T", English, 0, 0, Pri, 1, z_448).Output[0]
```
(Note, I don't use Python, so I'm only guessing at the syntax).

**Comment by ianhbell** [comment]
And also: 

Don't specify the composition of a predefined mixture, get it from ``SETMIXTUREdll``: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/SETMIXTUREdll

**Comment by EricLemmon** [comment]
Great!

Go ahead and close this issue if all is resolved.

**Comment by EricLemmon** [comment]
Oops, nevermind, this issue has already been closed.
