### ISSUE TITLE
Python Wrapper with return by reference

### ISSUE THREAD

**Issue by michaelUrsa** [usnistgov/REFPROP-wrappers#172]
I am trying to use the `SETMIXTUREdll` function to setup a mixture. The general REFPROP documentation indicates that the fluid will be setup and the z array passed in will be modified to reflect the composition of the mixture. 

From what I can tell the z list that I input is not changed to reflect the composition in the mixture file. The mixture, however, is properly setup as calls made afterwards with a manually created z array work fine. 

    z_array = [0]*20
    output = RP.SETMIXTUREdll(fluid, z_array)
    print(z_array)
Returns an array of 0s

I believe this is due to the fact that the inputted z list (a mutable type) is not modified, but instead set as a new array `z = (len(z)*ct.c_double)(*z)` severing the connection between the z array in the function and the reference to the z array passed in. 

If I return the z array at the end of the `SETMIXTUREdll` function in addition to `ierr`

    def SETMIXTUREdll(self, hMixNme, z):
        """
        ierr = SETMIXTUREdll(hMixNme,z)
        """
        hMixNme = ct.create_string_buffer(hMixNme.encode('utf-8'), 10000)
        z = (len(z)*ct.c_double)(*z)
        ierr = ct.c_long()

        if self._SETMIXTUREdll is None:
            raise ValueError(
                "The function SETMIXTUREdll could not be loaded from the shared library.")
        self._SETMIXTUREdll(hMixNme, z, ct.byref(ierr), 10000)

        return ierr.value, to_double_array(z)

I get the composition I expect, so the internal z array is updated, but it is not outputted from the python wrapper function in any way (without modification).

I am not very familiar with REFPROP or the python wrapper, so maybe I am just doing this wrong. Is there a specific way I should be handling this to allow the return by reference to work better?

Using REFPROP 10 (10.0002)
Windows 10
Python

**Comment by ianhbell** [comment]
This was a bug in REFPROP, now fixed, and I will update the wrapper to reflect these changes (I thought mistakenly that I had already done so).

**Comment by michaelUrsa** [comment]
Thanks Ian,

Can you ping this when you update the wrapper so I know when to update?

**Comment by ianhbell** [comment]
Working on it right now

**Comment by ianhbell** [comment]
Pushed.  You'll need to update the Python wrapper.

**Comment by ianhbell** [comment]
With a ``pip install -U ctREFPROP``

**Comment by michaelUrsa** [comment]
Awesome. Seems to be working.
