### ISSUE TITLE
MatLAB RefProp Installation Error with SSL Module

### ISSUE THREAD

**Issue by Yili-Zhang** [usnistgov/REFPROP-wrappers#173]
Hi,

I have been using RefProp for more than half a year, and when I initially try to install RefProp with MatLAB, I encountered the issue of SSL module being unavailable, and I solved that issue by decreasing the Python from version 3.7 to 2.7.

However, recently, when I run the program, I got the "deprecation" below:
``` python
>> [v,e] = pyversion; system([e,' -m pip install --user -U ctREFPROP'])
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. 
```
Previously, after this warning, the program keeps running normally, but the program would freeze after this warning starting this afternoon.

Then, I upgrade the python into version 3.7, and I kept getting the old issue:
``` python
>> [v,e] = pyversion; system([e,' -m pip install --user -U ctREFPROP'])
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. 
Collecting ctREFPROP 
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
  Could not fetch URL https://pypi.org/simple/ctrefprop/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ctrefprop/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping 
  ERROR: Could not find a version that satisfies the requirement ctREFPROP (from versions: none) 
ERROR: No matching distribution found for ctREFPROP 

ans =

     1
```

Except this statement does not work, every other codes in the instruction page works well.

May anyone give me some constructive advice on fix? I need it to be fixed urgently since it stopped in the middle of an big project.

Thanks,

-Yili

**Comment by ianhbell** [comment]
Here is some relevant information: https://github.com/pypa/virtualenv/issues/1139

Having never run into this problem before, and having helped many users with Python support, this seems to be something particular to your configuration.  I would uninstall Anaconda, see if Python is installed, and uninstall that too if it is installed.  Then I would reinstall Anaconda with python 3.7.

You could also try to install ctREFPROP directly in Python, rather than doing so through MATLAB.  MATLAB does some naughty things with the PATH variables that can cause problems.  The approach for that would be to open a conda prompt (Start->Anaconda prompt).  Then run ``pip install --user -U ctREFPROP``

**Comment by Yili-Zhang** [comment]
Hi,

Thanks for your reply.

I tried your first method, and it did not work. Then, I try to run the commend you provided in the conda propmpt, then I got the following error:

``` python
The system cannot find the path specified.

C:\>pip install --user -U ctREFPROP
'pip' is not recognized as an internal or external command,
operable program or batch file.
```

Do you know what that means?

Thanks,

-Yili

**Comment by ianhbell** [comment]
Are you sure you started a conda prompt rather than a normal prompt?  The program pip should definitely have been installed.  Can you show a screenshot of your efforts in the Anaconda prompt please?

**Comment by Yili-Zhang** [comment]
Yes.

![Conda Prompt](https://user-images.githubusercontent.com/29888537/58387194-40de2d80-7fc8-11e9-98c7-b92a2c01fc9d.PNG)

**Comment by ianhbell** [comment]
So weird....  I think your computer is cursed.  What if you do this instead an an anaconda prompt:
```
pip install -vvv -U ctREFPROP
```

When you installed anaconda, you didn't add Anaconda stuff to the PATH, did you?  The default is to not do that, but I usually do, and that might be part of your issue in this case.

**Comment by ianhbell** [comment]
New idea....  Go here: https://pypi.org/project/ctREFPROP/#files .  Download the Python 3.7 wheel, then in your anaconda prompt, install the wheel directly with something like:
```
pip install -U c:/path/to/ctREFPROP-0.7.3-py3-none-any.whl
```
change ``path/to`` to the appropriate path

**Comment by Yili-Zhang** [comment]
Hi,

Thanks for your reply.

After tried your method, here is what happens:
``` python
C:\Anaconda3\Scripts>pip install -U c:/ctREFPROP-0.7.3-py3-none-any.whl
Processing c:\ctrefprop-0.7.3-py3-none-any.whl
Installing collected packages: ctREFPROP
Successfully installed ctREFPROP-0.7.3

C:\Anaconda3\Scripts>pip install --user -U ctREFPROP
Operation cancelled by user
```
The `Operation cancelled by user` is the command after I terminated the command since it freezes after I typed the `pip install --user -U ctREFPROP`.

**Comment by ianhbell** [comment]
I think your MATLAB interface should work again.  The first of your two commands successfully installed the ctypes wrapper of REFPROP

**Comment by Yili-Zhang** [comment]
No, it doesn't. As I said before, it freezes at the `[v,e] = pyversion; system([e,' -m pip install --user -U ctREFPROP']);` line of code.

**Comment by Yili-Zhang** [comment]
I think I know what you mean. it seems to be working. But I need to go. I'll check tomorrow and let you know.

Thanks,

-Yili

**Comment by ianhbell** [comment]
You don't need to run those system commands anymore now that ctREFPROP is installed.  That is just to install/upgrade the Python interface for REFPROP, which you will call from MATLAB.

**Comment by Yili-Zhang** [comment]
Hi,

You're right! Problem solved! THANKS!

-Yili
