### ISSUE TITLE
To calculate propagation error from enthalpy

### ISSUE THREAD

**Issue by ThanitHinlailoed** [usnistgov/REFPROP-wrappers#174]
Automatic reply brought me here, I actually want to ask Dr. Lemmon, Eric W. but he kind a absent. If anyone ever relate with this field of work, please educate me.

Contents below is the mail that I send him.

Hello, Dr. Lemmon. I’m graduated student in advice of Asist. Prof. Atit Koonsrisuk from SUT, Thailand who recommended you to me. My thesis is about Power plant experimental work that adopt R245fa as working fluid. 
I interested in your article name “Short Fundamental Equations of State for 20 Industrial Fluids”  that proposed Helmholtz energy equations of state for group of special fluids included R245fa. In article provide very detail information but I still can’t follow up. 

In my work I measure parameter Pressure, p and Temperature, T to gather enthalpy of R245fa by Boudon tube Pressure gage and T type thermocouple and those contain certain amount of uncertainty (0-25 bar±1%RD,±0.1 bar, -40-350 ±0.5˚C). I want to calculate propagation error of enthalpy by those uncertainty, but equation 17 of your article propose enthalpy in function of dimensionless density and temperature. Can you guide me which equation I should combine to get enthalpy function by p, T. that I can use compute propagation error of enthalpy. lastly sorry for my broken English.

I attach your article that I mentioned.
[lemmon2006.pdf](https://github.com/usnistgov/REFPROP-wrappers/files/3226598/lemmon2006.pdf)

**Comment by ianhbell** [comment]
I'm afraid that this question is not appropriate for this venue, as this issue tracking system is intended only for discussion of bug reports and issues with the REFPROP software.  I've closed this issue for that reason. 

There is no way to directly get at the uncertainty in enthalpy from REFPROP.  The uncertainty in an enthalpy *difference* (in a relative sense) is approximately equal to the uncertainty in constant pressure specific heat, which you can determine by reading the appropriate paper, as you have done.

**Comment by ThanitHinlailoed** [comment]
Thank you for fast response. It’s alright to close my issue and I appreciate your helpful answer. I will follow through your suggestion.

Sent from Mail for Windows 10
