### ISSUE TITLE
REFPROPdll quick manual?

### ISSUE THREAD

**Issue by RinaldoMiorini** [usnistgov/REFPROP-wrappers#175]
Sorry, I am a new Github user.

RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
LookUpRefprop = RP.REFPROPdll('Water','TP','D',int8(0),int8(0),int8(0),298,101,{1.0});
State = double(LookUpRefprop.Output);
Density = State(1);
Density

What does {1.0} mean in the syntax above?

Links to provided help pages are focused on the python-refprop interface and since matlab calls python, i read that I should have all the information I need.
Still, I can't figure RP.REFPROPdll out, though. 

How do I select (or not) DEFAULT? Is air.mix still the keyword for air? Is there a page showing how to use RP.REFPROPdll that looks like that showing how to use the old refpropm? With a couple of examples and a list of thermophysical parameters, I mean. Thanks

**Comment by ianhbell** [comment]
1) {1.0} is the array of mole fractions
2) https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll ; You can obtain the desired unit system from GETENUMdll function (recommended).
3) 'AIR.MIX' is for a predefined mixture, 'AIR.PPF' is for a pseudo-pure EOS: (https://doi.org/10.1063/1.1285884)
4) You might want index 0 instead of 1 in State, though MATLAB might have converted the array to MATLAB-style array

**Comment by ianhbell** [comment]
5) You can pass multiple output parameters, delimited with * (a la refpropm)

**Comment by ianhbell** [comment]
Also I added some updates to the example for MATLAB.  I'll freely admit that it left a lot to be desired: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB

**Comment by RinaldoMiorini** [comment]
In https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB, "iMass = int8(0); ' 0: mass fractions; 1: molar fractions" but in the REFPROP 10 Manual Pag. 46 line 7 reads the opposite. Could you clarify? Thanks.

**Comment by RinaldoMiorini** [comment]
The following code:

> clear; clc;
> 
> PathToRefprop = 'C:\Program Files (x86)\REFPROP';
> RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary(PathToRefprop); % connects to the REFPROP library
> 
> hFld = 'WATER'; % fluid type
> hIn = 'TP'; % input parameters
> hOut = 'D'; % output parameters
> iUnits = RP.GETENUMdll(int8(0),'MASS BASE SI').iEnum; % sets the units
> iMass = int8(0); % mixture fraction type: 0 = mass fractions; 1 = molar fractions
> iFlag = int8(0); % call routine SATSPLN: 0 = no; 1 = yes
> a = 298.15; % [K]
> b = 101325; % [Pa]
> z = {1.0}; % [1]
> 
> tic;
> LookUpRefprop = RP.REFPROPdll(hFld,hIn,hOut,iUnits,iMass,iFlag,a,b,z);
> OutValue = double(LookUpRefprop.Output);
> OutUnit = char(LookUpRefprop.hUnits);
> OutputValue = OutValue(1);
> OutputUnit = OutUnit(1);
> VaporQuality = double(LookUpRefprop.q);
> ErrorString = char(LookUpRefprop.herr);
> toc;
> 
> disp('***');
> disp(OutputValue);
> disp(OutputUnit);
> disp(VaporQuality);
> disp(ErrorString);

returns:

> Elapsed time is 0.001122 seconds.
> ***
>   997.0476
> 
> k
>   -998
> 
> >> 

the unit and quality are not correct. Could you suggest where the error is?
Thanks!

**Comment by RinaldoMiorini** [comment]
Fixed units, its a string variable, not a char.

**Comment by ianhbell** [comment]
My mistake on the iMass, you are entirely correct, docs fixed.

**Comment by ianhbell** [comment]
You are now getting the density in kg/m^3, which is correct, and for q, if 0 > q > 1, it's two-phase, and these inputs are single-phase.  We don't calculate the effective quality, because to do so would require a slow saturation call.

Can you use Python instead of MATLAB?  All the type conversions disappear...

**Comment by RinaldoMiorini** [comment]
Unfortunately I have two years of Matlab scripts that are based on refpropm and I need to rewrite them ASAP, hence the pressure.

I am trying to use air.mix but I do not know what mass fraction to set. I am getting away with Fluid = 'nitrogen;oxygen;argon;carbondioxide' and z = {0.7809,0.2095,0.0093,0.0004}; but it's cumbersome.

What z should I set of air?

**Comment by ianhbell** [comment]
refpropm will still work with REFPROP 10, it's just not supported going forwards.  We're trying to harmonize the interfaces and keep them as thin as possible, and keep all the logic in FORTRAN to avoid differences between interfaces for different languages.

Using AIR.MIX and no fractions (all zero), should work.  Please let me know if not.  We've been tracking down some predefined mixture bugs recently.

**Comment by RinaldoMiorini** [comment]
I confirm that air.mix works with z = {0.0} thanks.

Interesting. Refpropm.m does not work with REFPROP10 in my PC, here's what happens when I run:

> disp("Loading reference air properties");
> RefTemp = C2K(20.0); % [K]
> RefPres = 101.325; % [kPa]
> UnivGasConst = 8.3144598; % [J/(K*mol)]
> RefMolarMass = refpropm('M', 'T', RefTemp, 'P', RefPres, 'air.mix'); % [kg/m3]
> RefSpecGasConst = 1E-3 * UnivGasConst / RefMolarMass; % [kJ/(K*kg)]
> RefCompFact = refpropm('Z', 'T', RefTemp, 'P', RefPres, 'air.mix'); % [1]
> RefSpecEnthalpy = 1E-3 * refpropm('H', 'T', RefTemp, 'P', RefPres, 'air.mix'); % [kJ/kg]
> RefCp = 1E-3 * refpropm('C', 'T', RefTemp, 'P', RefPres, 'air.mix'); % [kJ/(kg*K)]
> RefDynVisc = 1E+3 * refpropm('V', 'T', RefTemp, 'P', RefPres, 'air.mix'); % [uPa*s]
> RefThCond = 1E+3 * refpropm('L', 'T', RefTemp, 'P', RefPres, 'air.mix'); % [mW/(m*K)]

I get:

> Error using refpropm/get_header_path (line 745)
> Could not find header file for loading library
> 
> Error in refpropm (line 224)
>         prototype = get_header_path();

the code worked fine with REFPROP 9.1

**Comment by ianhbell** [comment]
Did you also grab the .H file?  That's needed, as is indicated in that error message.

**Comment by RinaldoMiorini** [comment]
It's complicated. By company policy I had to change PC and just reinstalling REFPROP9.1 did not work. From your comment I suspect I had to do more than that. Is there an old manual for REFPROP9.1 I can use to see if I can still use my old scripts?
Also, can I have REFPROP 9.1 and 10 in the same PC? I suspect not since the folder is Program Files (x86)/REFPROP (folder name not including the version)

**Comment by ianhbell** [comment]
Yes sure you can have parallel installations of 9.1.1 and 10, I did so myself for a long time.  One potential hiccup is that the installer sets the RPPREFIX variable, which is sometimes used to determine where to look for files.  This didn't work properly in 9.1.1, but does now in 10.  

Just install 9.1.1 to somewhere else, I used c:\Progam Files (x86)\REFPROP911 or so.

**Comment by RinaldoMiorini** [comment]
What are the labels and mass based units for dynamic viscosity and thermal conductivity? Used to be V and L but now V is Volume (REFPROP 10 manual pag. 32) and L is a special flag now (?)

**Comment by RinaldoMiorini** [comment]
found them on pag 36

**Comment by RinaldoMiorini** [comment]
REFPROP10 Manual Pag. 32. Molar Mass in g/mol (SI Mass Units) is not correct, should be kg/mol (gives 0.0290 for air)

**Comment by RinaldoMiorini** [comment]
REFPROP10 Manual Pag. 32. Specific enthalpy (H) in kJ/kg (SI Mass Units) is not correct, it appears to be J/kg (2.9341E+5) compared with EES (293.6 kJ/kg) suggests REFPROPdll provides J/kg

**Comment by RinaldoMiorini** [comment]
Cp is calculated is J(kg*K) (not kJ/(kg*K)) and dynamic viscosity in Pa*s (not uPa*s)

**Comment by ianhbell** [comment]
There are two kinds of SI mass unit systems, which are you referring to?  See https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll.  There's "MASS BASE SI" and "MASS SI".  

Personally I *only* use "MOLAR BASE SI", because in this unit system there are NEVER any unit conversions.

**Comment by RinaldoMiorini** [comment]
I am using MASS BASE SI. I got your point, there are 2 mass based SI systems but the manual specifies units for only one of them (not sure which, "SI Mass Units")

**Comment by ianhbell** [comment]
Hmm.. That's unfortunate.  I'll make sure we fix those docs in the next release; thanks for pointing that out.  Meanwhile, if you use the MASS BASE SI system, there's never any confusion, since it is always J, kg, Pa, etc.

**Comment by nathan-kamphuis** [comment]
HI Ian,

As a new user to REFPROP 10 and an old user of REFPROP 9 who used MatLab and the refpropm.m function call. Can you point to the resources necessary to learn how to call REFPROP using the new method? I.E. REFPROPM.m provided an easy to use function call that took care of the details of calling the correct functions in the dll in the correct order to obtain user friendly results. Is there a user friendly way of calling REFPROP 10 in MatLab that is supported in the future? Or do the users need to learn to call REFPROPdll functions in order to use REFPROP in MatLab?

**Comment by ianhbell** [comment]
@nathan-kamphuis If you want close to a one-to-one experience of the refpropm interface, then your best bet is the REFPROPdll function.  There are examples in the Python tutorial of how to do useful things with it, and the MATLAB interface is nominally the same as the Python interface with only tiny differences.  If you wanted, you could write your own refpropm shim function that would mirror the behavior you had before.
