### ISSUE TITLE
export data in T-x and P-x Diagram

### ISSUE THREAD

**Issue by yangmengnist** [usnistgov/REFPROP-wrappers#176]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

[how i can export the data in T-x and P-x Diagram. for example, the T-x diagram, i want the pressure of bubble (saturated liquid) and dew (saturated vapor) lines. ]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

**REFPROP Version:** [REFPROP version you are using]  
**Operating System and Version:** [OS you are running REFPROP on]  
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
Please fill out the template.

**Comment by yangmengnist** [comment]
Description
[how i can export the data in T-x and P-x Diagram. for example, the T-x diagram, i want the pressure of bubble (saturated liquid) and dew (saturated vapor) lines. ]

Steps to Reproduce
draw the T-x or P-x Diagram, and then i want to export the data of this diagram.
Expected behavior: [export the data of  T-x or P-x Diagram]



Versions
REFPROP Version: [REFPROP version 10]
Operating System and Version: [win 10]

**Comment by ianhbell** [comment]
Yup, it is also documented in the documentation (https://refprop-docs.readthedocs.io/en/latest/GUI/Menu%20Commands/Edit%20Menu/saveplotdatapoints.html), but to be fair its not so easy to find.  The protocol goes like this:
1) Make your P-x diagram
2) Menu->Edit->Save Plot Data Points, select the file to write them to
3) Make your plot from the data in the file
4) Cite our paper in your work (https://dx.doi.org/10.1002/aic.16074) :)

**Comment by yangmengnist** [comment]
thanks a lot
