### ISSUE TITLE
Failure loading predefined mixture

### ISSUE THREAD

**Issue by mchristians** [usnistgov/REFPROP-wrappers#179]
Hi,
I recently upgraded REFPROP to v10 and successfully compiled the REFPROP.h and librefprop.dylib from your instructions (thanks for the detailed instructions).  

However, I'm getting a odd error when running the refpropm Matlab script *only when calling mixtures*:

When I call, for example: 

```Tsat = refpropm('T','P',300,'Q',0,'R134a')```
this results in the expected answer:
```Tsat = 273.8221```

However, when I call:
```Tsat = refpropm('T','P',300,'Q',0,'R454B.MIX')```
this results in:
```Error using refpropm (line 301)```
```[SETUP error 101] Error in opening file for component 1: filename = R32.FLD ```

I can get any individual FLD file to output a result for any of the property conditions I've tried, but can't get any of the MIX files to work.

As corrective actions:
1. I've tried changing the file case (upper to lower, etc) just in case with no results.
2. I've also tried to see if I could diagnose the issue myself and all of the inputs into the 'calllib' on line 274 are correct – the outputs, including the suppressed ones (particularly output 5 which would be the string 'R32.FLD|R1234YF.FLD') all point to the right locations/info.
3. I tried changing the case and location of the folders (FLDs always work, but the MIX files don't).
4. Not sure what else is possible?

I am, at the same time, looking to migrate to the Python calls but this will take a bit of time for me to accomplish as it's new for me, and I've got a whole lot of legacy code I need to convert.

### Versions
**REFPROP Version:** v10
**Operating System and Version:** OS X 10.14.5, Mojave  
**Access Method:** refpropm.m legacy call
**MATLAB:** 2017b / 9.3.0.713579

**Comment by ianhbell** [comment]
Bug: https://github.com/usnistgov/REFPROP-issues/issues/168

**Comment by ianhbell** [comment]
Specifying the mixture composition directly should still work; you may need to pass absolute paths to fluids.  Recommend to upgrade to Python interface ASAP

**Comment by mchristians** [comment]
Thanks for the response – while I work to upgrade the legacy code to python, I've put together an addendum script to the refpropm code that takes the input mix file in the /mixtures/ folders and outputs the constituent FLDs and molar fractions:

```function [fluids,mf] = refmix(REF)

BasePath = '/Users/dmc/Library/Mobile Documents/com~apple~CloudDocs/MATLAB/refprop/'; %Pointer to your /refprop/ folder
libName = 'refprop'; 

mixdir = [BasePath,'mixtures/'];
mixdirstrct = dir([mixdir,'*.mix']);
mixlist = {mixdirstrct.name};

fluidType = REF;

%%this section is 100% from refpropm original other than hardcoding ierr = 0, since I'm not using it for that, and assigning variables to required outputs

if strfind(lower(fluidType), '.mix') ~= 0
    mixFlag = 1;
    fluidName = fluidType;
    fluidFile = [BasePath,'mixtures/',fluidName];
    hmxnme = char(32*ones(1,255)); % Pad out the string with spaces (32: ASCII code for space)
    hmxnme(1:length(fluidFile)) = fluidFile;
    mixFile = [BasePath,'fluids/','hmx.bnc'];
    hmix = char(32*ones(1,255)); % Pad out the string with spaces (32: ASCII code for space)
    hmix(1:length(mixFile)) = mixFile;
    href = 'DEF';
    ierr = 0;
    herr = char(32*ones(1,255)); % Pad out the string with spaces (32: ASCII code for space)
    ncc = 1;
    [~,~,~,nc,ncomp,z,~,~] = calllib(libName,'SETMIXdll',hmxnme,hmix,href,ncc,char(32*ones(1,10000)),zeros(1,20),ierr,herr,255,255,3,10e3,255);
end

mf = nonzeros(z);

fluids = cell(1,length(mf));
strt = 1;

for ii = 1:length(mf)
    fluids(ii) = extractBetween(ncomp,strt,'|');
    strt = strt+length(fluids{ii})+1;
end
```

As an example, you can use the above by calling
 ```[fluids,mf] = refmix(REF)``` where ```REF='R410a.mix'``` and following up with
 ```T = refpropm('T','P',600,'Q',0,fluids{:},mf)``` 
which outputs 
```T = 264.0368```

Lots of ways to go about this but I thought others may want to see this.

I ran this code against all of the predefined mixtures in the mixture file and no errors.

More FYI than anything, and hope it's useful to others.

**Comment by ianhbell** [comment]
This is very useful! Thanks for the post.  A caution: I don't think this would work on linux, since linux is actually case-sensitive, and OSX is semi-case-sensitive

**Comment by EricLemmon** [comment]
I'm closing this issue since the bug has been reported elsewhere, but I've added the "documentation" label to remind later to add this to the new FAQ section for others to find your code easily.
