### ISSUE TITLE
Method was not found?

### ISSUE THREAD

**Issue by khoopes** [usnistgov/REFPROP-wrappers#18]
I am trying to install the refprop wrapper for matlab and am having this issue whenever I call refpropm

Error using calllib
Method was not found.

Error in refpropm (line 294)
        [nc, ~,~,~,ierr,errTxt] =
        calllib(libName,'SETUPdll',numComponents,path,hmix,href,0,herr,10000,255,3,255);

I have all the files in the correct place, is there something I am missing?

THanks,

**Comment by khoopes** [comment]
I am not sure what was casuing this, but I was able to get it working by reinstalling REFPROP and following the instructions again.

**Comment by Shapexx01** [comment]
PLEASE COULD YOU GIVE ME THE STEPS TO GET THIS WORKING ON MATLAB R2018A. I HAVE DOEN EVERYTHING BUT IT GIVES ME ERRORS

**Comment by ianhbell** [comment]
@Shapexx01 Please don't yell, open a new thread, show what you did, and what errors you got.  Otherwise we have no idea how to help you.
