### ISSUE TITLE
Wrong enthalpy values calculated with Labview wrapper

### ISSUE THREAD

**Issue by sdurand89** [usnistgov/REFPROP-wrappers#180]
Hello

I have been trying to use the wrapper in some labview code for calculating enthalpy and I am running into some issues that I do not understand.
I am sorry if this issue was already known or if it is me that don't understand what I'm doing.

### Description
I tried calculating the enthalpy for a fluid (R32) based on the temperature and pressure. I only tried the calculation in labview with the VI called "Refprop_example_main.vi" that is in the wrapper. So no modification from my side and no VI development. 
The problem is that the enthalpy values I get with the labview wrapper are wrong. 

### Steps to Reproduce
The attached excel file shows the tests and some screenshots.
[refprop in labview bug.xlsx](https://github.com/usnistgov/REFPROP-wrappers/files/3289394/refprop.in.labview.bug.xlsx)

This is what I get in different applications
T° = 100°C / Pressure = 3 MPa
-Excel : H = 589 kJ/kg
-REFPROP : H =589 kJ/kg
-Labview : H = 628 kJ/kg

T° = 29°C / Pressure = 3 MPa
-Excel : H = 252 kJ/kg
-REFPROP : H =252 kJ/kg
-Labview : H = 565 kJ/kg

I tried differents units, different values, different fluids, ... in the VI but I never get the same enthalpy as in Excel or Refprop. 

### Versions
-DLL version 9.1
-Labview version 2017 32 bits
-Windows 10 64 bits

I have to point out that the test of the wrapper done with REFPROP High Level API Tester.lvproj was not successful. There are errors in VIs like "SETMIXTUREdll.vi" where Labview tells me that multiple functions called in the DLL were not found (e.g. `void  SETMIXTUREdll(CStr hmixnme, double *z, int32_t *ierr, int32_t hmixnme_length)` ).
However the "Refprop_example_main.vi" seems to work without errors, but maybe the wrong calculation are because these DLL errors?

Any help appreciated.

Thank you

Regards

**Comment by ianhbell** [comment]
A good question with a complicated answer.  This all comes down to reference states: https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences .  If you change the reference state in the GUI, you should be able to get the "right" enthalpy, but there is no such thing as the "right" enthalpy.  Enthalpy is always relative.  In Labview, you could consider to call the SETREF function which would allow you to determine which reference state you want.  Better would be to always consider enthalpy differences, rather than absolute values.

The missing functions are for REFPROP 10, and you use REFPROP 9.1.  You should consider to upgrade to REFPROP 10.

**Comment by sdurand89** [comment]
Thank you for your reply.
I understand that "absolute" enthalpy means nothing. But if I understand correctly, between two sets of values, I should get the same enthalpy difference in Excel and in Labview.
If I take my example:
Point 1 : T° = 100°C / Pressure = 3 MPa 
Point 2 : T° = 29°C / Pressure = 3 MPa
In Excel : Enthalpy difference = 589 - 252 = 337 kJ/kg
In Labview : 628 - 565 = 63 kJ/kg.

Whatever is the reference point, I should have the same difference, right? 
Point 1 is in vapor state, point 2 in liquid state. Is it possible that the Labview wrapper struggles to identify this state?

**Comment by ianhbell** [comment]
Yeah, I was guessing it was a unit problem.  Please close the issue if it is resolved.
