### ISSUE TITLE
Excel and Office 365

### ISSUE THREAD

**Issue by matwell1234** [usnistgov/REFPROP-wrappers#182]
I recently installed Refprop 10.0 and attempted to link it to Microsoft Excel using the instructions posted on GitHub. I am running Windows 10 with Office 365. My experience attempting to get the add-in to work matches that of the user on this thread almost exactly: https://github.com/usnistgov/REFPROP-wrappers/issues/121, but so far nothing in the list of recommended fixes seems to help. My installation location is C:\Program Files (x86)\REFPROP\, this location has been added as a trusted location (including subfolders), the add-in was successfully enabled, the path variables have all been set under Environment Variables, and as a result I can call the Refprop function in a blank cell. However, when I call this function, no matter the input, the result is always "#VALUE!".

In addition, when I open the "Refprop.xls" file in the installation directory, the Refprop DLL version in cell C3 reads "#VALUE!", as does every other cell attempting to call the function. I'm wondering if this might have something to do with the fact that I am using Office 365? 

Thanks for your help.

**Comment by EricLemmon** [comment]
Can you send me a personal email at eric.lemmon@nist.gov?  If possible, I would like to log into your machine to help figure out what is going on, and then add what we find to this link:

https://github.com/usnistgov/REFPROP-docs/blob/nist-pages/index.md#resolving-problems-linking-with-excel

**Comment by NickAtNight2017** [comment]
I use Office 365. No problems.

**Comment by NickAtNight2017** [comment]
System:  Refprop10    Windows10   Office365.   on a DELL.
My installation location is C:\Program Files (x86)\REFPROP

I open the Refpropl.xls file using Excel2016 (Desktop version).   
     Cell C3 shows a value of '10.0'    Formula in the cell is:  =REFPROP("DLL#")

Are you talking about running the Online version of Excel in Office365?

**Comment by NickAtNight2017** [comment]
With respect to:  "the add-in was successfully enabled"

1. Go to the Developer tab
2. Go to the Excel Add-ins in "Add-ins" group
3. There should be 2 add-ins with a check box
         REFPROP Addins
         REFPROP Ribbon

See attached graphic.

![Annotation 2019-06-27 144435](https://user-images.githubusercontent.com/31464824/60295903-7ee1b080-98ea-11e9-9640-41aca64dc0c6.png)

**Comment by NickAtNight2017** [comment]
If the add-ins are installed correctly, then the REFPROP tab should show on your computer screen.  (See screen shot)

If you click on this tab, you should get the listed Menu options.

Are you able to run the Wizard?   {Click on the Wizard} Icon.

![Annotation 2019-06-27 144435](https://user-images.githubusercontent.com/31464824/60296111-ffa0ac80-98ea-11e9-9c60-b8c828192c87.png)

**Comment by NickAtNight2017** [comment]
Next test step is to click on the Wizard.  
- A window should pop up with some default properties filled in.
- In this window, click the 'Enable instant calculation' if it is not selected.  
- Does the Wizard show you a calculated result?  
--  In this example it is the Density of air being 1.27 kg/m3 at 273 K and 0.1 MPa.

If that is working, is the Excel string shown for this calculation?
     =refprop("D","Air","TP","SI",273.15,0.1,0)

If you click on the Calculate button, the formula is added to your excel sheet in whatever cell you have currently selected.  

Alternatively click the Compose button to get the Property name and units added to the Excel sheet.

If you follow these steps, are you getting a result or still getting 'value' ?

![Annotation 2019-06-27 145902](https://user-images.githubusercontent.com/31464824/60296714-4fcc3e80-98ec-11e9-80c8-a5d0a634e493.png)

**Comment by matwell1234** [comment]
I am using the desktop version of Excel. Both add-ins show up in the add-in box and I am able to select them.
![image](https://user-images.githubusercontent.com/52259463/60346382-a1260d80-9980-11e9-9f74-fecaf3d3045c.png)

I do get the ribbon after enabling the ribbon add-in, and I am able to use the GUI. However, when I click the calculate button I get the error shown below: "#Make sure the REFPROP.XLA add-in is enabled to calculate items in the cells." If I enter the formula directly into a cell I get the "#VALUE!" result. 

![image](https://user-images.githubusercontent.com/52259463/60346350-90759780-9980-11e9-90d8-4c6dd57523d9.png)

**Comment by matwell1234** [comment]
Okay, it turns out the issue was in linking to the .dll file. For whatever reason, even though I modified the path statement in my environment variables, Excel was still not able to connect to the .dll file. To fix this, I opened the VBA module (alt+F11), went to the Refprop10Code module in the REFPROP.XLA spreadsheet, and modified the code pointing to the .dll file to the correct path. (The default path in the code was incorrect). So the new code should look like:

Private Declare PtrSafe Sub REFPROPdll Lib "C:\<correct path>\REFPRP64.DLL"

Private Declare Sub REFPROPdll Lib "C:\<correct path>\REFPROP.DLL"

Note, you may have to change the location of your Refprop directory. Windows seems to have an issue allowing these edits if your path is in the "Program Files" or "Program Files (x86)" directory. At first this modification did not work, but then I modified my installation location to C:\REFPROP\, then performed the above VBA code modification, and now the link works.

Kudos to Eric for helping me solve this.
