### ISSUE TITLE
What does "PHASE" represent for?

### ISSUE THREAD

**Issue by Yili-Zhang** [usnistgov/REFPROP-wrappers#183]
Hi,

I recently encountered an error where I try to determine the phase of a state of my system, instead of returning a valid phase such as "Subcooled liquid" or "Superheated gas", it returned "PHASE". I wonder what state it represents for?

In addition, is there any source you may provide for me to refer all the possible phases in useing Rerfprop as well as their corresponding outcome strings?

Lots of thanks!

-Yili

**Comment by ianhbell** [comment]
Can you please fill out the issue template?  Otherwise, a lot of important information is missing from this question.

**Comment by Yili-Zhang** [comment]
### Description

I recently encountered an error with MatLAB Refprop "Phase" function. In my code, I could recognize phases that are "Two-phase", "Supercritical", "Saturated vapor", "Superheated gas","Subcooled liquid" or "Saturated liquid", and my code worked fine. However, after upgrading my model (codes), there comes a new phase state called "PHASE". I failed on understanding what phase it stands for, and here is the two lines of code where I failed:

``` python
    PHASE=RP.REFPROPdll(hFld,'PH','PHASE',MASS_SI,int8(0),int8(0),P19,h19,{1.0});
    PHASE19=convertCharsToStrings(char(PHASE.hUnits));
```
I used this codes a lot under other conditions, and it works fine. Therefore, I don't think it is the code format's problem; instead, it should be due to the combination of the specific condition of "hFld", "P" and "H". Thus, I desperately need to know what "PHASE" stands for in RefProp? Or in another word, under which condition would MatLAB Refprop generate the phase as "PHASE"? Also, in order to understand the Refprop better, I would like to know all types of phases the Refprop can generate, as well as their corresponding conditions.

### Steps to Reproduce

1. 
``` python
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
MASS_SI=RP.GETENUMdll(int8(0), "MASS SI").iEnum; % Unit System: Mass SI
```
2. 
``` python
hFld = 'Methanol';
P19 = 4.3681; % [MPa]
h19 = -1e7; 
```
3. 
``` python
PHASE=RP.REFPROPdll(hFld,'PH','PHASE',MASS_SI,int8(0),int8(0),P19,h19,{1.0});
PHASE19=convertCharsToStrings(char(PHASE.hUnits));
```

**Expected behavior:** PHASE19 = Any regular phase mentioned above

**Actual behavior:** PHASE19 = "PHASE"
### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** Windows 10 Enterprise
**Access Method:** MatLAB 

### Additional Information
N/A

**Comment by ianhbell** [comment]
Hmm... This seems like a bug to me in REFPROP.  What is the value of ierr returned in the PHASE data structure?

**Comment by Yili-Zhang** [comment]
Sorry, I don't have it available now...I tested my codes in my colleague's computer over the weekend, and I don't have access now.

**Comment by Yili-Zhang** [comment]
Hi,

As the timeline of my current project is very pushy, will you just be able to tell me what "PHASE" stands for in refprop phase function?

Thanks,

-Yili

**Comment by ianhbell** [comment]
I don't know...  I need to know what the precise inputs were that you put into the REFPROPdll function so that I can test on my side.

**Comment by Yili-Zhang** [comment]
Okay. I'll run it on my computer again...What is the code to find ierr?

Thanks,

-Yili

**Comment by ianhbell** [comment]
Confirmed.  On my side:
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RP = REFPROPFunctionLibrary('D:\Program Files (x86)\REFPROP')
MASS_SI = RP.GETENUMdll(0, "MASS SI").iEnum# ; % Unit System: Mass SI

hFld = 'Methanol'
P19 = 4.3681 # [MPa]
h19 = -1e7 

PHASE = RP.REFPROPdll(hFld,'PH','PHASE',MASS_SI,0,0,P19,h19,[1.0]);
print(PHASE.hUnits)
```
yields
```
PHASE

**Comment by ianhbell** [comment]
And this time printing the error code -- there was an error.  Moral of the story, as I think I have mentioned before, 100% of the time that you call the function REFPROPdll you need to check for an error code.  If ierr > 100, that is a fatal error.  But it is a bug that some phase string is returned when the calculation fails.

```
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RP = REFPROPFunctionLibrary('D:\Program Files (x86)\REFPROP')
MASS_SI = RP.GETENUMdll(0, "MASS SI").iEnum# ; % Unit System: Mass SI

hFld = 'Methanol'
P19 = 4.3681 # [MPa]
h19 = -1e7 

PHASE = RP.REFPROPdll(hFld,'PH','PHASE',MASS_SI,0,0,P19,h19,[1.0]);
print(PHASE.ierr, PHASE.herr)
print(PHASE.hUnits)
```
yields
```
248 [PHFLSH error 248] Single-phase iteration did not converge for P = 4.36810 MPa and H = -0.320422E+09 J/mol.
PHASE
```

**Comment by Yili-Zhang** [comment]
Thanks. But in this code, where exactly the calculation failed?

**Comment by ianhbell** [comment]
The flash calculation --> determining T,rho (independent variables of the EOS) as a function of enthalpy and pressure.  Are you sure that set of P,H is reasonable?

**Comment by Yili-Zhang** [comment]
P is reasonable, but H might be off. I think this is simply not a design point in my system. I'll mark any design points with "PHASE" as a result as non-design point.

Thanks.

**Comment by ianhbell** [comment]
Much better solution would be to reject points based on ierr > 100, rather than on PHASE.

**Comment by Yili-Zhang** [comment]
Okay, I'll try it out. Thanks for the suggestions.

-Yili
