### ISSUE TITLE
Properties at a specified saturation temperature

### ISSUE THREAD

**Issue by agshaligram** [usnistgov/REFPROP-wrappers#184]
Hi,

I have used Refprop 10 but independently. Now I am integrating it with Matlab through Python interface. What I want is what is the command syntax to get a thermodynamic or transport property ( for example dynamic viscosity or specific enthalpy) for a fluid ( again take as an example refrigerant R1233zd(E)) at a specified saturation temperature. In short what I want is equivalent command what Coolprop used to provide again in Matlab. 

Let me know. Thanks.

**Comment by ianhbell** [comment]
Please checkout the documentation: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html .  The tutorial could also be helpful: https://nbviewer.jupyter.org/github/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb 

But in your case, the easiest might be to call REFPROP through CoolProp: http://www.coolprop.org/coolprop/REFPROP.html

**Comment by agshaligram** [comment]
Thanks for quick response. I will try the CoolProp way. Earlier I have used CoolProp. I decided to shift to Refprop as it has new HFO single fluids as well as mixtures.
