### ISSUE TITLE
Python function RPVersion is not giving correct REFPROP working version in 10.0 on Red Hat Linux 7.4 

### ISSUE THREAD

**Issue by tfpetersen** [usnistgov/REFPROP-wrappers#185]
### Description
Dear NIST team.

I have installed REFPROP 10.0 on Red Hat Enterprise 7.4. When I use the function “RP.RPVersion()” in Python 3 I get "******" as the result and not the correct version of REFPROP.

### Steps to Reproduce

1. Compile the REFPROP shared object using guide https://github.com/usnistgov/REFPROP-cmake
2. Install python wrapper from pip
3. Ensure paths and environment variables are set correctly
4. Run the code below in python3

``` python
import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

def NBP():
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    RP.SETPATHdll(os.environ['RPPREFIX'])
    print(RP.RPVersion())
    MOLAR_BASE_SI = RP.GETENUMdll(0,"MOLAR BASE SI").iEnum

    r = RP.REFPROPdll("PROPANE","PQ","T",MOLAR_BASE_SI, 0,0,101325, 0, [1.0])
    print(r.ierr, r.herr, r.Output[0])

if __name__=='__main__':

    # Print the version of REFPROP in use and the NBP
    NBP()
```

The code above produced:

```console

******

0  231.03624791008983
```

### Versions

**REFPROP Version:** REFPROP 10  
**Operating System and Version:** Red Hat Enterprise Linux Server release 7.4
**Access Method:** Python wrapper installed with pip and used with python 3  

### Additional Information

The REFPROP shared object was compiled with:
cmake v. 3.7.2
gcc v. 7.3.0
python v. 2.7.15

Python 2.7 was used to compile REFPROP to get access to numpy.f2py, but python 3 is used to access REFPROP.

**Comment by ianhbell** [comment]
You can email me to get updated FORTRAN sources  (ian.bell@nist.gov<mailto:ian.bell@nist.gov>), and/or use the output “DLL#” to obtain the version without this bug from the REFPROP function.  Please see https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll

**Comment by tfpetersen** [comment]
Dear Dr. Bell.
Thank you for your reply, I have sent you an e-mail to get the updated source. Using REFPROPdll with "DLL#" works as expected.

**Comment by tfpetersen** [comment]
Dear Dr. Bell.
Thank you for the updated source code. The update went smoothly and the python script now works as expected.
