### ISSUE TITLE
Specify Vapor or Liquid side in TPRLSHdll.vi

### ISSUE THREAD

**Issue by xu9song** [usnistgov/REFPROP-wrappers#187]
### Description

Is there a way to select Vapor or Liquid side in TPRLSHdll.vi? V or L can be specified in hin field of ``REFPROPdll``. It is very convenient to avoid Refprop confusion.

### Versions

**REFPROP Version:** [REFPROP version you are using]  
**Operating System and Version:** [OS you are running REFPROP on]  
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]

**Comment by ianhbell** [comment]
Do you mean TPFLSHdll?  If so, no, there is no way to specify the phase, but there is in the TPRHOdll function: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/TPRHOdll
