### ISSUE TITLE
Specified State Points(varying composition) command

### ISSUE THREAD

**Issue by yangmengnist** [usnistgov/REFPROP-wrappers#188]
### Description

Different properties of binary refrigerants under varying composition

### Steps to Reproduce

1. define new mixture, we selected HFO1336mzz(Z) and HFO1233zd(E) as a new mixture refrigerant
2. set the mass fraction of HFO1336mzz(Z) and HFO1233zd(E) as 0.1:0.9 and 0.2:0.8 respectively
3. then find the Specified State Points(varying composition) command :calculate-- Specified State Points(varying composition)
4. Input the same condition for the two mass fraction 0.1:0.9 and 0.2:0.8 respectively 

**Expected behavior:** Properties like enthalpy and entropy should be the same

**Actual behavior:** The results of different mass fraction are different

### Versions

**REFPROP Version:** NIST REFPROP v10
**Operating System and Version:** Win 10
**Access Method:** GUI

### Additional Information
the results of different mass fraction are showed in the picture below.
the input condition includes mass fraction、temperature and pressure, but the calculated results are different.
![image](https://user-images.githubusercontent.com/45703839/61761333-085ca380-ae01-11e9-9e56-7766bc0aaf15.png)

**Comment by ianhbell** [comment]
I made some formatting edits to your issue

Can you please be more specific about what version of REFPROP you use?

**Comment by ianhbell** [comment]
I can confirm this behavior. What reference state have you set in your GUI?  I have:
![image](https://user-images.githubusercontent.com/11966765/61808549-d9423400-adf8-11e9-9503-44700c6296c1.png)

I get different values for enthalpy and entropy but see the same erroneous behavior.  When I use different bulk mass compositions but use the same values in the table, the enthalpy and entropy are indeed different, though they should not be.

Inputs (xmass_1336mzz(Z), xmass_1233zd(E), T_K, p_MPa)
``` 
0 | 1 | 398.15 | 1.3504
0.1 | 0.9 | 398.15 | 1.4423
0.2 | 0.8 | 398.15 | 1.5222
0.3 | 0.7 | 398.15 | 1.5924
0.4 | 0.6 | 398.15 | 1.6543
0.5 | 0.5 | 398.15 | 1.7094
0.6 | 0.4 | 398.15 | 1.7585
0.7 | 0.3 | 398.15 | 1.8023
0.8 | 0.2 | 398.15 | 1.8416
0.9 | 0.1 | 398.15 | 1.8767
1 | 0 | 398.15 | 1.908
```

**Comment by yangmengnist** [comment]
i had not edit the "Select Reference State".  I explain what is my question and see the attachment
[Specified State Points(varying composition) command.docx](https://github.com/usnistgov/REFPROP-wrappers/files/3429288/Specified.State.Points.varying.composition.command.docx)
 below

**Comment by ianhbell** [comment]
Yup, I understood from your first question.  This is a bug in the REFPROP GUI.  I don't know how to fix it  (yet).

**Comment by yangmengnist** [comment]
ok, i hope you can fix it as early as possible. thanks.

**Comment by ianhbell** [comment]
This bug should only be present in the GUI, the Excel or Python interfaces should not have this problem

**Comment by yangmengnist** [comment]
ok. i will try it in Excel. thanks.

**Comment by EricLemmon** [comment]
This is an interesting and complex question that has been asked many times.  I started a new issue and tried to explain this in depth, you'll find it here:
https://github.com/usnistgov/REFPROP-issues/issues/222

**Comment by EricLemmon** [comment]
Has this issue been resolved?  If so, could you close it?
