### ISSUE TITLE
RefProp9.1 random behavior on Windows 10

### ISSUE THREAD

**Issue by masaoakei** [usnistgov/REFPROP-wrappers#189]
Hello,

I'm experiencing strange behavior of RefProp 9.1 (on Windows 10).  When I use some of the provided FLSH functions on the Excel wrapper (like "Volume" or "Enthalpy"), it sometimes causes various error mode. I wrote "sometimes" because the error occurs randomly. Even if the same input values are used, RefProp sometimes returns correct values, and sometimes gives different error messages (PHFLSH 247, "Density is zero", etc.).  I posted some of the screen shot pictures below.  One of the error mode was on VBA giving "Type mismatch". The PHFLSH error (247)  sometimes occurs on RepProp program as well (not on Excel).

Above issue does not occur all the time.  Closing the Excel file and open it again sometimes solve the issue.  Sometime I need to reboot the Windows.  Once the system (or Excel) is reset, RefProp (and Excel wrapper) works just fine.  Please see the bottom 3 pictures for successful cases.

I'm wondering if there is any interaction issues between Windows 10 and RefProp.dll (I'd never had similar issues on Windows 7).   I appreciate your help in advance. 

Thank you,
Masao 

**REFPROP Version:** [REFPROP 9.1]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [Excel 2013]  

Error Examples:

![excel_error](https://user-images.githubusercontent.com/53493820/62164579-ad3c1c80-b2ea-11e9-86a2-ea08e4c3be9f.png)

![VBA_error](https://user-images.githubusercontent.com/53493820/62164593-b331fd80-b2ea-11e9-81c3-f38b1e6c5281.png)

![RefProp_error](https://user-images.githubusercontent.com/53493820/62164627-c513a080-b2ea-11e9-8972-2e5afde78753.png)

When system are reset:

![Excel_ok](https://user-images.githubusercontent.com/53493820/62164725-f42a1200-b2ea-11e9-92bc-503c1a26daa1.png)
 
![VBA_ok](https://user-images.githubusercontent.com/53493820/62164797-16239480-b2eb-11e9-9022-b90d51aa7a6c.png)

![RefProp_ok](https://user-images.githubusercontent.com/53493820/62164817-1cb20c00-b2eb-11e9-957c-43104fd4a658.png)

**Comment by masaoakei** [comment]
Sorry I posted a wrong picture (second picture).  Please see below for the VBA giving "Type mismatch" error.

![VBA_error](https://user-images.githubusercontent.com/53493820/62165779-33596280-b2ed-11e9-9a07-99152615887a.png)

**Comment by ianhbell** [comment]
@EricLemmon  is our resident Excel guru, I'll let him dig into this one.

**Comment by masaoakei** [comment]
I'm not sure I'm getting any response on this issue, but I made some progress myself.  
   - I've found that above random errors do not occur when you manually pause (breakpoint) the VBA code at the point where it actually calls the DLL (in Subroutine "Calc"). 
   - If you don't pause the VBA code, the program runs very quickly at the DLL calling and it sometimes gives back errors (such as PHFLSH 247). 
   - It appears it is some kind of access issue between VBA and DLL. I decided to compile RefProp.DLL myself.
   - I used Intel Fortran (IFort: version 16). All Refprop 9.1 source files are re-compiled together.
   - Same random error behavior was seen when IFort compiler options were kept in default. However, when I disable the optimization option (/Od), then the error problems went away. The re-compiled RefProp.DLL gives correct values without VBA pauses.
   - I'm not completely convinced that the compiler option was the cause of the problem.  I would be appreciative if anyone would share any experiences related to this issue.
  (- We use corporate license. Upgrading to version 10 is not an option at this point, unfortunately.)

**Comment by EricLemmon** [comment]
Please excuse my slow response, I've been out of the office for some personal reasons for a while.

I'm not sure why you are getting errors after installing on Windows 10.  The patch below fixes some of the PH flash errors in version 9.1:

https://trc.nist.gov/refprop/91/911PATCH.EXE

It might be possible that I sent you this some time ago when you first started using 9.1, which may be why the un-patched version on your Windows 10 machine is giving you these problems.

Eric

**Comment by masaoakei** [comment]
Eric, thanks for the response. Do you have any documentation regarding this patch (contents, installation, etc.)? I may want to forward it to our person who control corporate license.

**Comment by masaoakei** [comment]
My RefProp version was 9.1. I installed above patch 9.1.1.  It resolved my random error issue. Thank you very much.  I would be grateful if you could briefly tell me what was made in this patch.  You may close this case at your convenience.

**Comment by EricLemmon** [comment]
If I remember right (it was many years ago), there was one small bug in the code that caused the non-convergence issue.  Changing just a few lines corrected the problem.  Other than that, most of the code is unchanged from that in version 9.1.

**Comment by masaoakei** [comment]
Thank you. I will close this topic.
