### ISSUE TITLE
Order of Input to calculate enthalpy from entropy and pressure

### ISSUE THREAD

**Issue by Dhinesht88** [usnistgov/REFPROP-wrappers#19]
Hi,
I just came across an issue with the refprop.m file in R2017a version of the matlab. Atlease case~1 should give an error instead of calculating zero enthalpy. 

Case~1

>> refpropm('h','S',2000,'p',17500,'water')

ans =

     0

Case~2

>> refpropm('h','p',17500,'S',2000,'water')

ans =

   7.1916e+05

Thank you.

**Comment by ianhbell** [comment]
Thank you for a very clear bug report.   I will ensure that you get a better error message!

**Comment by ianhbell** [comment]
The refpropm.m interface has been deprecated in version 10, though it still works, so this issue is being closed.
