### ISSUE TITLE
Google Sheets with Refprop

### ISSUE THREAD

**Issue by VES-ES** [usnistgov/REFPROP-wrappers#190]
Is it possible to create an interface between Google Sheets and Refprop?

**Comment by ianhbell** [comment]
Not sure, but probably not.  The google sheets ecosystem does have the ability to run javascript, but I believe it is a somewhat restricted set of JS, so I doubt it.  Also, REFPROP is FORTRAN based, and cross compilation for JS seems impossible.  But it might be possible with the JS interface of CoolProp, but I don't know of anyone having done that.

**Comment by VES-ES** [comment]
OK thank you
