### ISSUE TITLE
Changing Reference State in Excel

### ISSUE THREAD

**Issue by VES-ES** [usnistgov/REFPROP-wrappers#191]
Does changing reference state in GUI change it in Excel?

**Comment by ianhbell** [comment]
Nope, they are independent

**Comment by VES-ES** [comment]
OK thanks, I did the following but it is not seem to be working:

1. Opened REFPROP.XLS file (in REFPROP folder) in Excel 2016.

2. Changed the following code:
`hIn = "SETREF": hFld = ""
          'hOut = "NBP"  '*****Do NOT use this line with the one below select only one. Valid inputs are DEF, NBP, IIR, ASH, and NA.
          hOut = "OTH; 0; 0; -40; 25.454"    'To set your own reference state, use this line with OTH.  In this example, a reference state of h=11.11 J/mol, S=22.22 J/mol-K, T=298.15 K, and P=101.325 kPa would look like this.  The units for this option are the default REFPROP units.  Do not use the line directly above when using OTH.
          Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, 2&, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)`

I did not change any other code in VB. Also I was not able to open XLA file in Excel was I supposed to change it there as well?

3. I was not able to save as in the REFPROP directory, so I saved it elsewhere and moved to REFPROP directory. I kept the original file there just renamed it as REFPROP_original.


Am I missing something? Was I supposed to change XLA code as well?

Thank you

**Comment by VES-ES** [comment]
Btw, my reference point is based on English units, h=0 Btu/lb, s=0 Btu/lb-ºF, T=-40ºF, P=25.454 psia (at Saturated Liquid point).

**Comment by VES-ES** [comment]
@ianhbell do you have any feedback on above?

**Comment by ianhbell** [comment]
Afraid we need @EricLemmon  to chime in on this one, he's the developer of the Excel interface.  Excel is sometime hard to debug due to the out-of-order evaluation of the cells, but I doubt that is the issue here.

**Comment by VES-ES** [comment]
@EricLemmon could you pls review what I did when you get a chance. Thank you!

**Comment by EricLemmon** [comment]
We found that in some cases this did not work because of the random out-of-order evaluation of the cells in Excel as Ian referred to when a fluid file has not been loaded.  A work around is to have it call any fluid file initially and then proceed to set the reference state.  Try this code here:

```
        'Use the following lines to set a reference state to one of those available in the REFPROP program.
        'See notes at the top of this section about restarting Excel and saving this file.
        'The call to load propane is needed to deal with an issue in Version 10 that will not set the flag for reference states when a fluid has not been loaded.
          hFld = "Propane": hIn = "": hOut = ""
          Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, 2&, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)
          hIn = "SETREF": hFld = ""
          'hOut = "NBP"  '*****Do NOT use this line with the one below; select only one. Valid inputs are DEF, NBP, IIR, ASH, and NA.
                         hOut = "OTH; 11.11; 22.22; 298.15; 101.325"    'To set your own reference state, use this line with OTH.  In this example, a reference state of h=11.11 J/mol, S=22.22 J/mol-K, T=298.15 K, and P=101.325 kPa would look like this.  The units for this option are the default REFPROP units.  Do not use the line directly above when using OTH.
          Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, 2&, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)
```

Also note that, if I remember right, you must use SI molar units in this call.  If your answers don't match when you use English units in this call, convert to SI and try it again.

Eric

**Comment by VES-ES** [comment]
Thank you Eric. I tried pasting this code but now getting "#" in all the cells with =REFPROP formula on my worksheet.

I opened REFPROP.XLS file, VBA code and copied your code to both XLS and XLA scripts and then saved it and restarted.

**Comment by EricLemmon** [comment]
Perhaps go back to your original file and try just pasting in these two lines somewhere in the upper section that only runs once (and above the reference state call).

 hFld = "Propane": hIn = "": hOut = ""
          Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, 2&, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)

**Comment by EricLemmon** [comment]
Has this issue been resolved now?

**Comment by VES-ES** [comment]
yes thank you
