### ISSUE TITLE
Refprop 10 much slower in a fortran project

### ISSUE THREAD

**Issue by isultan1** [usnistgov/REFPROP-wrappers#192]
I use gfortran to compile the refprop fortran code with a fortran 90 program to calculate fluid properties during a compression-expansion process. I noticed that the resulting calcs take 4X the time taken by the fortran code in refprop 9.1.   I do not use the new refprop subroutine but kept using the flash functions which I have alway used.  If there's a fix to the speed problem, this would be great.

**Comment by EricLemmon** [comment]
I transferred your message over to the wrappers repository.

Take a look at the following and see if it helps:

 https://pages.nist.gov/REFPROP-docs/#calculation-of-the-critical-point-and-saturation-states-in-the-critical-region

**Comment by EricLemmon** [comment]
Have you tried the SATSPLN feature yet?
