### ISSUE TITLE
Hello , I am trying to install REFPROP and i get this message ERROR : Could not find a cersion that satisfies the requirement ctREFPROP ERROR: No matching distribution found for ctREFPROP

### ISSUE THREAD

**Issue by reshmamahesan** [usnistgov/REFPROP-wrappers#193]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

**REFPROP Version:** [REFPROP version you are using]  
**Operating System and Version:** [OS you are running REFPROP on]  
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
Please fill out the entire template.  Without more information I don't know how to start to help you.

**Comment by reshmamahesan** [comment]
Description
REFPROP Unable to install
Steps to Reproduce:

I am new to python and Coolprop. I installed Python and Coolprop and not trying to install REFPROP from Anaconda 3 . I did run "pip install REFPROP " and it gave me an error : Coud not find a version that satisfies the requirement of Refprop

And at some point it did show installed.

But after which when i run PropsSI('T','P',101325,'Q',0,'REFPROP::Water') , i get the message you canot use REFPROPMixtureBackend

I tried resintalling REFPROP again , but i get the same version error.

My Python Version 3.7.3

**Comment by ianhbell** [comment]
ctREFPROP and CoolProp are only interfaces to REFPROP.  Note the install command is “pip install ctREFPROP”, not “pip install REFPROP”

To install REFPROP, you can purchase it from https://www.nist.gov/srd/refprop .  Then either the CoolProp or ctREFPROP interfaces should work.
