### ISSUE TITLE
getting started with REFPROP and Matlab wrapper

### ISSUE THREAD

**Issue by Mira14Sam11** [usnistgov/REFPROP-wrappers#194]
I have purchased a copy of REFPROP but am having some trouble getting it to work with MATLAB.
 
I have installed the *.exe file and followed the instructions as best I can in the wrapper documentation.
 
I am not sure how to get the refprop.h file in my folder.  I can not download it directly.
 
I also get an error when I try to run refprop from the Matlab command line that says
 
>> refpropm('T','P',101.325,'Q',0,'WATER')
??? Undefined function or method 'contains' for input arguments of type 'char'.
 
Error in ==> refpropm at 279
            if ~contains(lower(fluidName),'.fld')

**Comment by ianhbell** [comment]
I'm sorry, but the refpropm interface is no longer supported.  The only supported interface for MATLAB is via Python.  Please see these docs: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB#refprop-for-matlab

**Comment by Mira14Sam11** [comment]
I understand that the refpropm interface is not supported.  I am trying to use it with an older version of Matlab (R2011a).  I thought that the legacy wrapper should work with this.

I have not used Python before, so this is not an easy interface for me to use.  I would prefer to use the legacy Matlab wrapper.  Are you able to support that with R2011a Matlab?

**Comment by ianhbell** [comment]
2011a of MATLAB does not support Python interfacing I think.  The legacy wrapper does still work, but  we don't support it anymore.  

Try this link: https://raw.githubusercontent.com/usnistgov/REFPROP-wrappers/master/wrappers/MATLAB/legacy/REFPROP.h

**Comment by Mira14Sam11** [comment]
Thanks Ian.  The link that you sent allows you to save REFPROP.h as a text document.  Is that how it is supposed to be used?  Is there any further help that you can provide?  I am just trying to get started.

**Comment by ianhbell** [comment]
Please read https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB/legacy#instructions-on-windows

**Comment by Mira14Sam11** [comment]
Thanks.  I have read through this previously and, unfortunately, am still not able to solve my issue getting started.  I made the adjustment to the BasePath and tried to run the following but get the following error

loadlibrary('REFPRP64.dll', 'REFPROP.h', 'mfilename', 'rp_proto64.m')
??? Error using ==> loadlibrary>lFullPath at 613
Could not find file REFPROP.h.

Error in ==> loadlibrary at 226
        header=lFullPath(header);

When I run the example suggested I still get the following error:

>> refpropm('T','P',101.325,'Q',0,'WATER')
??? Undefined function or method 'contains' for input arguments of type 'char'.

Error in ==> refpropm at 279
            if ~contains(lower(fluidName),'.fld')

I think I have tried all that you have in the readme file.  Do you have any further suggestions based on the two errors above?

**Comment by ianhbell** [comment]
Can you show the contents of your REFPROP installation folder?

**Comment by ianhbell** [comment]
Also, did you install a compiler?  You need to do so to use loadlibrary in MATLAB.

**Comment by Mira14Sam11** [comment]
Unfortunately, I don't have a Matlab compiler.  Do I need to have one?  Is there a free compiler that I can use if I need one?

Below is a screenshot of my REFPROP installation folder

![REFPROP](https://user-images.githubusercontent.com/54647888/63900856-f26d7000-c9b6-11e9-930c-b48872242db4.jpg)

**Comment by ianhbell** [comment]
Yes, please read MATLAB’s documentation for your release to figure out which free compiler you can use.

Or to avoid all these headaches, you could just use Python for your analysis.

**Comment by Mira14Sam11** [comment]
Got it.  I guess I may have to upgrade the Matlab code I'm using.  I don't seem to be able to setup a compiler with my current computer setup.  Very frustrating!

I appreciate your help.  I'll figure out the next step from here.
