### ISSUE TITLE
FluidString10 vs FluidString

### ISSUE THREAD

**Issue by GZALAT** [usnistgov/REFPROP-wrappers#196]
Hello,
I encountered the issue that properties (in my example the dynamic viscosity) are not at all calculated when using Fluidstring10 syntax, but coherently with RP 9.1108 when using the old syntax:

![image](https://user-images.githubusercontent.com/48068140/64187728-6acda880-ce71-11e9-9dc1-edbe81a49808.png)

Example file:
[HeN2 Viscosity Issue.xlsx](https://github.com/usnistgov/REFPROP-wrappers/files/3570293/HeN2.Viscosity.Issue.xlsx)

Thank you for your advice

### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** Win10 
**Access Method:** Excel

**Comment by ianhbell** [comment]
Did you try also with 0.5,0.5 rather than .5,.5?

**Comment by GZALAT** [comment]
I used the provided "Fluidstring10" function...

**Comment by ianhbell** [comment]
Can you please email me (ian.bell@nist.gov) to get a beta which might fix this.

**Comment by ianhbell** [comment]
I take it you are not using the standard add-in.  This works fine for me: 
![image](https://user-images.githubusercontent.com/11966765/64387071-215b9580-cff8-11e9-87b8-23d3a6eb5d56.png)

You'll need to triage with your provider of the Excel addin.

**Comment by GZALAT** [comment]
I found the problem: it is the "iFlag" option that was set to 1; some other
mixtures did not converge with the default option, so I let this flag set
as new default if the fluid was not a pure one.
 This new option is tricky to use as I see no general rule when to activate
it...
Thank you!

Golo

**Comment by GZALAT** [comment]
Ian, 
Just for your information if you will ever have a similar issue.
I added the following lines to the refprop call

>         Dim propertyExists As Boolean, tempObj
> On Error Resume Next
>         Set tempObj = ActiveWorkbook.CustomDocumentProperties("RefPropiFlag")
>         propertyExists = (Err = 0)
> On Error GoTo 0
>         If propertyExists Then iFlag = tempObj.Value Else iFlag = 0

In this way I can store file per file the necessary option, the CustomDocumentProperty can easily be set by a ribbon control
Golo
