### ISSUE TITLE
Call refpropdll from vba

### ISSUE THREAD

**Issue by cabello1971** [usnistgov/REFPROP-wrappers#197]
Hello

I'm trying to call directly the Refpropdll from excel-vba in order to reduce the calculation time. But when the code is compiled an error window merge with the text "Sub or function not defined"
I am not an expertise programmer so, can you help me with this issue?
I'm using REFPROP v.10 and the corresponding excel file.
I have attached a picture with the error window.
Thanks in advance for your attention.

![Refpropdll-Excel](https://user-images.githubusercontent.com/55500959/65161431-da2dc580-da37-11e9-9007-110f624f67b6.png)

**Comment by EricLemmon** [comment]
Has this issue been resolved yet?  If so, could you close this?

**Comment by cabello1971** [comment]
Hello Eric

Unfortunately I have no enough knowledge as programmer to solve the problem. I tried your advises and recommendations, but the code still doesn't run. 

Thanks for your kindness
