### ISSUE TITLE
Matlab crashes:  Abnormal termination: Access violation

### ISSUE THREAD

**Issue by vytenau** [usnistgov/REFPROP-wrappers#2]
After few cycles matlab crashes. refpropm.m call is  used inside simulink s-function.
Crash file and code attached

[Copy_of_model_HE.txt](https://github.com/usnistgov/REFPROP-wrappers/files/701655/Copy_of_model_HE.txt)
[matlab_crash_dump.txt](https://github.com/usnistgov/REFPROP-wrappers/files/701597/matlab_crash_dump.txt)

**Comment by ianhbell** [comment]
Can you please make a minimal working example that does not use Simulink, and is just a matlab script?  It's quite difficult to debug Simulink errors.

**Comment by vytenau** [comment]
Just made a quick experiment with this code. After running 20 cycles HE_clc.m in while loop, matlab crashed with the same error.
[HE_clc.zip](https://github.com/usnistgov/REFPROP-wrappers/files/703710/HE_clc.zip)

**Comment by ianhbell** [comment]
How do I run your example? Also, just so you know, code you post in issues is publicly visible.

**Comment by ianhbell** [comment]
I ran both HE_calc.m and HE_clc.m, and both succeed.

**Comment by vytenau** [comment]
Run He_clc.m in a loop. After about 20 cycles it will crash Matlab. It does not fail every time.

**Comment by vytenau** [comment]
I retried my tests. Running 
```
a=1;
while a==1;
HE_clc
a=1;
end
```

crashed Matlab after third cycle.

**Comment by ibell** [comment]
Is it possible for you to strip this down to a simple example that doesn't use your code that causes a crash?  With so many things going on, it's hard to know what the problem is.

**Comment by ianhbell** [comment]
Is it possible for you to strip this down to a simple example that doesn't use your code that causes a crash? With so many things going on, it's hard to know what the problem is.

**Comment by ianhbell** [comment]
I did 
``` matlab
for i=1:5; HE_clc; end
```
and it didn't crash.  What version of REFPROP do you use?  I tested with 9.1.1

**Comment by vytenau** [comment]
I am using 9.1.

**Comment by ianhbell** [comment]
Can you update to REFPROP 9.1.1 and try again?  

What version of MATLAB do you use?

**Comment by vytenau** [comment]
Please try to test with atleast 50 loops or more, since crashing is unpredictable: it can crash on the first cycle or 100th. I will try to simplify code, but since it is a tricky problem I am not able do it right now.
Matlab 2016a

**Comment by vytenau** [comment]
We bought REFPROP two weeks ago and thats what we got. Is there any later version?

**Comment by ianhbell** [comment]
I tried 50 loops, no problem.  Please email me at ian.bell@nist.gov and I will send you the link to the 9.1.1 update from 9.1

**Comment by vytenau** [comment]
After updated still gets crashed with an error:
[matlab_crash_dump (2).txt](https://github.com/usnistgov/REFPROP-wrappers/files/710202/matlab_crash_dump.2.txt)

I will try to reduce code in order to find `the problem

**Comment by ianhbell** [comment]
Yes, please reduce the code to the smallest amount that can repeatably cause this failure.

**Comment by ianhbell** [comment]
The refpropm.m interface has been deprecated in version 10, though it still works, so this issue is being closed.
