### ISSUE TITLE
calllib error when attempting the refpropm example in Linux (Ubuntu 17.10) MATLAB 2017-b (64-bit)

### ISSUE THREAD

**Issue by mhannonj** [usnistgov/REFPROP-wrappers#20]
Following the instructions given for the MATLAB wrapper in Unix systems, I still had the following error come up when attempting to run the refpropm example:
```
Error using calllib
Method was not found.

Error in refpropm (line 295)
        [nc, ~,~,~,ierr,errTxt] =
        calllib(libName,'SETUPdll',numComponents,path,hmix,href,0,herr,10000,255,3,255);
```
To overcome this, from the MATLAB command line I had to navigate to the $HOME/refprop/ directory and run the following command:
```
loadlibrary('librefprop.so', 'REFPROP.h', 'mfilename', 'rp_proto64.m');
```

However, i have to do this every time I start up MATLAB.  Is there an edit I should make to refpropm.m to do this automatically?

Thanks!

**Comment by ianhbell** [comment]
Please use markdown formatting when inputting code blocks: https://guides.github.com/features/mastering-markdown/

Please see the docs: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB#potential-problems .   The default path is $HOME/refprop on *nix platforms.

**Comment by mhannonj** [comment]
Thanks for the tips!  Is there somewhere I can place the prototype file so that it's read automatically on startup?

**Comment by ianhbell** [comment]
Yes, in the BasePath directory, $HOME/refprop

**Comment by mhannonj** [comment]
I see.  So do I need to include a command like `loadlibrary(strcat(BasePath,'librefprop.so'), strcat(BasePath,'REFPROP.h'), 'mfilename', strcat(BasePath,'rp_proto64.m'));` to the first line of the function `proto`?

**Comment by ianhbell** [comment]
No, it should be sufficient to make a folder ``refprop`` in your home folder and put all the REFPROP-related stuff in it.  If it doesn't, that is a bug with ``refpropm.m``

**Comment by mhannonj** [comment]
Ok, I think I have everything working now.  Thanks a lot for your help!

**Comment by ianhbell** [comment]
Good, please close your issue then!
