### ISSUE TITLE
Compatibility REFPROP 8 - Win 10 - Excel 365

### ISSUE THREAD

**Issue by kimomenu** [usnistgov/REFPROP-wrappers#201]
Good morning, 

I am a new arrival at my lab, trying to use a REFPROP 8 version on a Excel 365 on new computer with Windows 10. 

Do you have a specific troubleshooting document on how to configure it?

I used to work with Refprop 9.1 on Windows 10/ Excel 2018 and it worked correctly. So I guess it has to be connected with the Windows 10/Excel 365.

Thanks

Quim

**Comment by EricLemmon** [comment]
Is there any news on this issue since July 2nd?  Why did you switch back to version 8 when you had 9.1?

**Comment by kimomenu** [comment]
License always on employer. Worked at a lab with version 9.1 then changed
to a job at a lab with version 8.
