### ISSUE TITLE
Problem with opening an .FLD file

### ISSUE THREAD

**Issue by Xande96** [usnistgov/REFPROP-wrappers#202]
Description:

I'm trying to make a simples code that, i enter with the temperature and pressure of a substantace and gives me back some information, like enthalpy, viscosity. But when i run the code i get this message:
HERR=[SETUP error 101] error in opening file for component #  1; filename = (fluids\R134A.FLD)

I checked all the paths to the fluids directory and it should be working. Also tried to put the FLD files as lib. Nothing is working.

Expected behavior: Calculate some properties of a substance.

Actual behavior: When i call the SETUP subroutine it gives me that error.

REFPROP Version: 8.0
Operating System and Version: Windows 10
Access Method: Fortran
Additional Information: I am using Eclipse as IDE.

**Comment by EricLemmon** [comment]
Have you been able to resolve this issue?  If not, can you send me a personal email at eric.lemmon@nist.gov?
