### ISSUE TITLE
Intel(r) Visual Fortran Run-Time Error on R450A/R448A

### ISSUE THREAD

**Issue by RPVslvd** [usnistgov/REFPROP-wrappers#203]
### Description

I'm trying to create a saturation table for refrigerants R-450A and R-448A, but getting a 'Visual Fortran Run-Time error. Haven't had any issues with other refrigerants, just these two. 

### Steps to Reproduce

1. Open Refprop
2. Click on 'Substance'
3. Select 'Predefined Mixture'
4. Select R450A
5. Get 'Visual Fortran Run-Time Error'
6. Refprop shutsdown

**Expected behavior:** Go into 'Calculate' and create saturation tables

**Actual behavior:** Get run-time error and refprop closes

### Versions

**REFPROP Version:** DLL Version 9.1  
**Operating System and Version:** Windows 10
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by EricLemmon** [comment]
There has been no response to this post, has it been resolved?  If not, could you please reduce your code to as few lines as possible to show the effect so that we can look into it?
