### ISSUE TITLE
Cannot load predefined mixtures on case-sensitive OS

### ISSUE THREAD

**Issue by ibell** [usnistgov/REFPROP-wrappers#205]
Please see CoolProp/CoolProp#1829 . This is a bug in REFPROP in that a lower-case fluid file is being used in the SETUP, whereas REFPROP should have used an uppercase fluid name.

**Comment by ianhbell** [comment]
I don't think this should have been transferred, its a problem with the core of REFPROP

**Comment by ianhbell** [comment]
Fixed in the beta of REFPROP.

**Comment by ahjortland** [comment]
Is there a way to apply this fix / are there plans to release an update?

**Comment by ianhbell** [comment]
Please email me and I can send the beta files : ian.bell@nist.gov.  An official release is coming, but I don't have a prognosis for timing.

**Comment by dcore94** [comment]
I had a similar problem with CoolProp not linking RefProp backend inside a Dockr container with an Ubuntu 18.04 OS for backward compatibility.
