### ISSUE TITLE
Convergence failure for reference state of some PR fluid files when they appear last in MIX file 

### ISSUE THREAD

**Issue by Thuke11** [usnistgov/REFPROP-wrappers#208]
### Description

I'm attaching a PR based FLD file that when added to any MIX file as the _last_ component produces the following error when SETUP (SETMIX) is called. This happens regardless of how I call SETUP, whether through the python wrapper or the GUI itself.

REFPROP_SETMIX_Error: [SETREF error 119] Convergence failure in calculating reference state for component 2: [SATT error 124] Iteration for saturation state did not converge for T = 273.150 K.

Here is a set of parameters for the attached mix file. The R-1234yf file is the same one as is distributed with REFPROP 10.

!
?PR example/R-1234yf
?Simoni (2019-07-31) -- fit to
  xx-xxx-xx    /40377b40     
    KW0    0.991000937 1.034303587 1.000000000 1.000000000  0.000000000          0.
    TC1    0.          0.          0.          0.          0.          0.
    VC1    0.          0.          0.          0.          0.          0.
!

### Steps to Reproduce
I'm attaching the .FLD file and Mix file and KW0 parameters. If you just add them to your directories and HMX file, and attempt to load the mix file this will happen.

### Versions
This is REFPROP 10 on Windows 7.

[fluid and mix file.zip](https://github.com/usnistgov/REFPROP-issues/files/3453358/fluid.and.mix.file.zip)

**Comment by EricLemmon** [comment]
This bug appears to be fixed now.  Please email me directory (eric.lemmon@nist.gov) and I'll send you a new DLL.
