### ISSUE TITLE
HOW TO CALC a mixtures with c/c++?

### ISSUE THREAD

**Issue by birdol** [usnistgov/REFPROP-wrappers#21]
hi there , i got a demo file form http://trc.nist.gov/refprop/LINKING/Linking.htm#NETApplications

the file EX_C2.c in C.ZIP  compile got an error 
```C
i = 3;
	strcpy(hf, "nitrogen.fld");
	strcat(hf, "|argon.fld");
	strcat(hf, "|oxygen.fld");
	strcpy(hfmix, "hmx.bnc");
	strcpy(hrf, "DEF");
	strcpy(herr, "Ok");
	x[0] = .7812;     //Air composition
	x[1] = .0092;
	x[2] = .2096;

	//...Call SETUP to initialize the program
	SETUPdll(&i, hf, hfmix, hrf, &ierr, herr,
		refpropcharlength*ncmax, refpropcharlength,
		lengthofreference, errormessagelength);
	INFOdll(&info_index, &wm, &ttp, &tnbp, &tc, &pc, &dc, &zc, &acf, &dip, &rgas);
```
when i print  pram wm , the anwser is 28.0135 ,
it is the  molecular weight of nitrogen, not for mix（air）, the right anwser is 28.958

anything i can do to fix this？

btw，the file in refprop8.0 install，c++ demo code，have the same question like this。

**Comment by ianhbell** [comment]
Yes, INFOdll is for the pure components, WMOLdll is for the mixture. Please read the manual.txt in the FORTRAN folder of your installation for more info.

**Comment by birdol** [comment]
very thanks， how to use SETMIXdll？   any demo?

**Comment by ianhbell** [comment]
You can find an example here in the source code of CoolProp: https://github.com/CoolProp/CoolProp/blob/master/src/Backends/REFPROP/REFPROPMixtureBackend.cpp#L344-L366
