### ISSUE TITLE
Wrong enthalpy difference results.

### ISSUE THREAD

**Issue by Yili-Zhang** [usnistgov/REFPROP-wrappers#210]
``` python
clear
clc

%% Set Up - Call RefProp in MatLAB
% Refprop MatLAB setup instruction web: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
MASS_SI=RP.GETENUMdll(int8(0), "MASS SI").iEnum; % Unit System: Mass SI

hFld = 'Methanol';

P7_1=0.0813;
T7_1=332.1247;
H=RP.REFPROPdll(hFld,'PT','H',MASS_SI,int8(0),int8(0),P7_1,T7_1,{1.0});
H_num=double(H.Output);
h7_1=H_num(1);

P7_2=0.1083;
T7_2=339.3419;
H=RP.REFPROPdll(hFld,'PT','H',MASS_SI,int8(0),int8(0),P7_2,T7_2,{1.0});
H_num=double(H.Output);
h7_2=H_num(1);
```

### Description

Hi, while I was running my big MatLAB Refprop simulation, I discovered the enthalpy difference between two conditions changed significantly without the condition changing much. In the MatLAB Refprop, with the T7_1, P7_1, T7_2, P7_2 shown in the codes above, I got the h7_1 = -15.4499 kJ/kg; h7_2=1102.6 kJ/kg. To confirm with this answer, I ran the exact condition in the Engineering Equation Solver (EES) software, and got a totally different answer: h7_1 = -1065 kJ/kg; h7_2=-1045 kJ/kg. Given the conditions are not in huge difference, the results from EES seems to be more reasonable. However, as I ran the simulation with RefProp, I wonder why the MatLAB RefProp performs weirdly on that?    

### Steps to Reproduce

Simply use the code above.

**Expected behavior:** diff(h7_1, h7_2) is small

**Actual behavior:** diff(h7_1, h7_2) is super huge

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 10 Enterprise
**Access Method:** MatLAB

**Comment by ianhbell** [comment]
You should also compare densities, as in this case you got a liquid solution for one input, and a gas solution for the other, whereas in EES you didn’t.  If you know inputs are gas or liquid you can specify the phase for the input where the phase is known: 

What EOS does EES implement?  I don’t think it is the same as REFPROP

From https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll  :

Flags to specify certain phases are listed below, for example, ‘TD>’ would specify an input state in the liquid phase but which would normally be two-phase. Those available are:
• **> or **L: When the letter ‘L’ is attached after the two letters that specify the input properties (such as ‘TP’), the routine will assume that the input properties are in the single phase liquid region, or are within the two-phase area as a metastable state. For example: TP>, PH>, HSL.
• **< or **V: The letter ‘V’ (or the sign ‘<’) specifies that the input state for the properties listed in the first two letters is in the single phase vapor (including metastable states). For example: TP<, PH<, HSV.

**Comment by Yili-Zhang** [comment]
Hi,

Thanks for the prompt reply, I tried to use the temperature and quality to find the enthalpy in the EES software, and the results became quite consistent with the one in RefProp. Therefore, I guess the reason for the sharp change in enthalpy between two conditions is due to the phase change?

-Yili

**Comment by ianhbell** [comment]
Indeed, that is my suspicion.  Please check the densities between EES and REFPROP.

**Comment by Yili-Zhang** [comment]
Yeah, the density implies the same results.

Thanks.
-Yili

**Comment by ianhbell** [comment]
Ok, good to have clarification on this point. Thanks for closing the issue.
