### ISSUE TITLE
I get ***** when calling RPVersion() from the python wrapper

### ISSUE THREAD

**Issue by mathieulaurin** [usnistgov/REFPROP-wrappers#211]
I use Win 10 + REFPROP 10 + python wrapper (python 3.7). When I follow your examples, I get  ***** when calling RPVersion(). In the notebook, it says to contact you to get a patch. Thanks

**Comment by ianhbell** [comment]
Yes, please send an email to ian.bell@nist.gov and I'll send you a patch.
