### ISSUE TITLE
Bug in Refprop 10 Excel. Changing mixture doesn't show correct output.

### ISSUE THREAD

**Issue by krushnaeicp** [usnistgov/REFPROP-wrappers#212]
Whenever I load refprop 10 excel or create new sheet using refprop 10 code in the module, it seems like it still refers the old mixture set in Refprop excel.

For example, I used formula =REFPROP("H","R404A.MIX","TP","ENGLISH",120,50) which should give me 116.02 Btu/lbm but it gives me 179.32.

Refprop excel should automatically detect change in mixture/fluid/units and calculate output accordingly.

**Comment by krushnaeicp** [comment]
I think there is some problem either with setting the fluid/mixture or unit conversion.

**Comment by EricLemmon** [comment]
Take a look at this issue and see if it helps: https://github.com/usnistgov/REFPROP-wrappers/issues/133

**Comment by krushnaeicp** [comment]
Per your suggestion, I un-commented this lines but it doesn't gave correct value. 

 'Use the following lines to set a reference state to one of those available in the REFPROP program.
        'See notes at the top of this section about restarting Excel and saving this file.
          hIn = "SETREF": hFld = ""
          hOut = "ASH"  '*****Do NOT use this line with the one below select only one. Valid inputs are DEF, NBP, IIR, ASH, and NA.
          'hOut = "OTH; 11.11; 22.22; 298.15; 101.325"    'To set your own reference state, use this line with OTH.  In this example, a reference state of h=11.11 J/mol, S=22.22 J/mol-K, T=298.15 K, and P=101.325 kPa would look like this.  The units for this option are the default REFPROP units.  Do not use the line directly above when using OTH.
          Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, 2&, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)

**Comment by krushnaeicp** [comment]
I un-commented above lines of code, save, close and re-open excel but it didn't work. 
I see there is big problem with this approach, one can have multiple refrigerants in single workbook and this may create lot of problems. It always takes last refrigerant even though we have used new refrigerant  in formula. It was working very smoothly in refprop 9 without any manual changes to the code. 
If you can send me the Refprop 10 excel with resolution of this problem that will be great. I will email you separately.
