### ISSUE TITLE
Are there alternatives for FLASH functions in Refprop 10? Repeated calls to Flash functions are breaking my C#/VB.net program in .net framework 4.0 and above. 

### ISSUE THREAD

**Issue by krushnaeicp** [usnistgov/REFPROP-wrappers#213]
Are there alternatives for FLASH functions in Refprop 10? Repeated calls to Flash functions is crashing my C#/VB.net program in .net framework 4.0 and above. Same code is working good all the time for .net framework 3.5 or less. The reason why I am using Flash functions is to support both phase state calculation and matching results with Refprop GUI. I am calling SETUP() only once so that shouldn't be a problem.

I heard this problem is there since long but want to know if there is way to overcome. Any help or code sample would be appreciable.

**Comment by ianhbell** [comment]
Without filling out the template, it is hard to know what the problem is, precisely.  But my guess, is that you are still not appropriately padding the strings sent to the REFPROP functions, resulting in a memory corruption.

**Comment by krushnaeicp** [comment]
I am using C# this time and strings are properly padded. Please see my below code running which multiple times with same/different inputs crashes application in .net framework 4.0 or above. Same code runs smoothly in .net framework 3.5 or less. I can sense that this is not problem with Refprop 64 bit dll which I need to definitely use with .net 4.0 and above applications. My actual question is can you suggest simple and fast alternatives for my below code. Thanks in advance.

PSFLSHdll(ref Pressure, ref Entropy, mf, ref T, ref d, ref Dl, ref Dv, xliq, xvap, ref q, ref e, ref h, ref cvcalc, ref cpcalc, ref w, ref ierr, ref herr, ref herrLen);

where variables as declared/initialized as below:
double Pressure, (input = )
double Pressure, (input = )
public double[] mf = new double[20]; (input = )
double T =0;
double d =0;
double Dl =0;
double Dv=0;
public double[] xliq = new double[20]
public double[] xvap = new double[20]
double q=0;
double e = 0;
double h = 0;
double cvcalc = 0;
double cpcalc = 0;
double w = 0;
long ierr = 0;
string herr = new String(' ', 255);
herr = "";
long herrLen;
herrLen = herr.Length

**Comment by ianhbell** [comment]
I think the ``herr = ""`` resets the string to be empty again? But I'm no C# expert. What is the length of ``herr`` after these definitions?  I still very much suspect that one of your functions has the wrong string length padding, resulting in hard-to-track-down memory corruptions that would manifest differently in different .net frameworks.

I don't understand what is "wrong" with this function call.  That's a totally fine way to call the flash routines.  In REFPROP 10, there is also the more generic ``ABFLSHdll`` function.

**Comment by krushnaeicp** [comment]
yes, for 64 bit refprop dll reassigning to herr and herrlen done the trick. Thanks for pointing onto the right direction.
