### ISSUE TITLE
SETMIXdll returns Error in Opening File in C++

### ISSUE THREAD

**Issue by lee-zion** [usnistgov/REFPROP-wrappers#214]
### Description

Hi.
My goal is to get Density, Viscosity, Thermal Conductivity and Isobaric Specific Heat at certain TP points.

In short, 
[Temperature, Pressure] → [REFPROP] → [Density, Viscosity, Thermal Conductivity, Isobaric Specific Heat].

For this purpose, I'm building REFPROP wrapper with Javascript(nodejs).
For the purpose, I'm developing an add-on with node-gyp.
Programming language is C++.

Again, in short,
[Fortran] → [C++] → [Javascript].

**Actual behavior:**
I can get properites for single fluids, but fail on mixtures.
I call SETMIXdll, and its input arguments are seemly correct.

![setmix](https://user-images.githubusercontent.com/34432835/66538644-40ea5e80-eb60-11e9-8d5f-84f5764ab510.JPG)

I've set
```
hMixNme=PATH_TO_.MIX_FILE
hFmix=PATH_TO_HMX.BNC
hrf="DEF"
```
and give output arrays as empty. According to ierr flag, it is 101 which corresponds to "Error in opening file". I don't see something wrong in arguments, but it shows error and seems nobody having trouble like me.

I'm using REFPROP 9.1, and using Windows 10.

BTW, I wish there exists example for FAQs in any programming language.
For example, set of APIs to get Thermal Conductivity (or whatever) of mixture with its limitations may help people to study themselves(including myself).

**Comment by ianhbell** [comment]
C++ is where you should start your tests :) Walk before you run and all that.  Make sure you can get C++ working, _then_ add the JS part.  

Make sure to use the REFPROPdll function.  And there are examples for Python: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python

And the tutorial: https://nbviewer.jupyter.org/github/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb

If you stay in C++, consider wrapping REFPROP via CoolProp: http://www.coolprop.org/coolprop/wrappers/StaticLibrary/index.html#static-library

**Comment by lee-zion** [comment]
Oh, I work on C++, it is my wrapper for js (existing web application is based on js).
REFPROPdll is ver 10.0, so I cannot use ver 9.1? I've seen CoolProp source code with REFPROP.cpp, but there seems no difference with mine.

Again, my wrapper works for single fluids, but not working on mixture. So what I was wondering is that is there any difference in calling APIs except SETUPdll vs SETMIXdll.

**Comment by ianhbell** [comment]
Maybe there is no difference between your code and CoolProp's, but there are a lot of subtle issues (e.g., padding of strings) that if done incorrectly will yield erroneous values or bugs, with no clear explanation of why.  So I would recommend starting there since the CoolProp <-> REFPROP interface is pretty robust and well-tested.  At the very least, make sure you use the REFPROP-headers header file.

If you have REFPROP 10, then I would use only the new API, which is all exposed in the REFPROP header file.
