### ISSUE TITLE
Refprop 10.0 setupdll error in C++

### ISSUE THREAD

**Issue by lee-zion** [usnistgov/REFPROP-wrappers#215]
Recently upgraded REFPROP 9.1 to 10.0 to use High-Level API.

connection test code from [REFPROP-headers repo.](https://github.com/CoolProp/REFPROP-headers/blob/master/other.cpp#L14-L25)

```
int ierr = 0, nc = 1;
char herr[255], hfld[10000] = "R32.FLD", hhmx[255] = "HMX.BNC", href[255] = "DEF";
SETUPdll(nc,hfld,hhmx,href,ierr,herr,10000,255,3,255);
if (ierr > 0) printf("Other ierr: %ld herr: %s\n", ierr, herr);
{
    int ierr = 0;
    char herr[255];
    double z[20] = {1.0}, x[20] = {1.0}, y[20] = {1.0}, T= 300, p = 101.325, d = -1, dl = -1, dv = -1, h = -1, s = -1, u = -1, cp = -1, cv = -1, q = -1, w = -1;
    TPFLSHdll(T, p, z, d, dl, dv, x, y, h,s,u,cp,cv,w,q,ierr,herr,255);
    if (ierr > 0) printf("Other ierr: %ld herr: %s\n", ierr, herr);
    printf("Other d: %g mol/L\n", d);
}
```
And resultant errors are

```
ierr: 101
herr: [SETUP error 101] error in opening file for component #  1; filename = (R32.FLD
```
I see that problem is parenthesis on filename, `(R32.FLD`.
But there is any parenthesis on input, as hard-coded.

Is there any point that I'm missing?

**Comment by ianhbell** [comment]
Where did you install REFPROP?  Do you have REFPROP 9.1 and REFPROP 10 installed on your computer? In my case, I ALWAYS install REFPROP to a non-default path, and call the SETPATHdll function to set the path.  This avoids a lot of fluid file loading issues like you are seeing here.

Also, you probably want to use the SETFLUIDSdll function if you are using REFPROP10.

**Comment by lee-zion** [comment]
node-refprop
 ┣ node_modules
 ┣ REFPROP
 ┃ ┣ FLUIDS
 ┃ ┣ MIXTURES
 ┃ ┣ REFPRP64.DLL
 ┣ src
 ┃ ┣ test.cpp
 ┃ ┣ REFPROP_lib.h written by [REFPROP-headers](https://github.com/CoolProp/REFPROP-headers)
 ┣ test
 ┃ ┗ index.js
 ┣ binding.gyp
 ┣ package-lock.json
 ┣ package.json
 ┗ README.md

I don't understand what you mean by `install`. Do I need any installation for developing wrapper?
I placed dll, FLUIDS and MIXTURES folder in my project.

Actually, my code already include SETPATHdll, but failing.

`test.cpp` 
```
RefpropContext::RefpropContext(v8::Isolate* iso) {
    std::string path = ".\\..\\REFPROP";
    std::string DLL_name = "REFPRP64.DLL";
    std::string err;
    bool loaded_REFPROP = load_REFPROP(err, path, DLL_name);
    printf("path: %s\n", path);
    SETPATHdll(const_cast<char*>(path.c_str()), 400);

    int ierr = 0, nc = 1;
    char herr[255], hfld[10000] = "R32.FLD", hhmx[255] = "HMX.BNC", href[255] = "DEF";
    SETUPdll(nc,hfld,hhmx,href,ierr,herr,10000,255,3,255);
    if (ierr > 0) printf("This ierr: %d herr: %s\n", ierr, herr);
    {
        int ierr = 0;
        char herr[255];
        double z[20] = {1.0}, x[20] = {1.0}, y[20] = {1.0}, T= 300, p = 101.325, d = -1, dl = -1, dv = -1, h = -1, s = -1, u = -1, cp = -1, cv = -1, q = -1, w = -1;
        TPFLSHdll(T, p, z, d, dl, dv, x, y, h,s,u,cp,cv,w,q,ierr,herr,255);
        if (ierr > 0) printf("Other ierr: %ld herr: %s\n", ierr, herr);
        printf("Other d: %g mol/L\n", d);
    }
```
Again, it seems that parenthesis seems the problem, and [REFPROP-headers](https://github.com/CoolProp/REFPROP-headers) is just a header file.
Maybe .DLL have something that do not filter parenthesis `(` at filename.

**Comment by ianhbell** [comment]
Please first run the file provided with REFPROP-headers in C++.  Make sure that works and that you understand how the parts fit together before proceeding.  

For instance, in your case, you need to copy the path passed into SETPATHdll into a char[] of the appropriate length before passing to SETPATHdll; the string MUST be padded to the appropriate length before sending it to SETPATHdll function.  If not, you may run into problems with the FORTRAN code reading random memory locations beyond the string you passed in.  This will fail silently with no warning.
