### ISSUE TITLE
Having problem in linking REFPROP with VB

### ISSUE THREAD

**Issue by jafarialireza** [usnistgov/REFPROP-wrappers#216]
I tried to use the application which is provided by Ian Spanswick to link REFPROP with VB and faced the error as below.

System.DllNotFoundException: 'Unable to load DLL '..\Data\Refrigerant10\REFPRP64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

![image](https://user-images.githubusercontent.com/52477944/66896536-94a8ec00-f027-11e9-9e2b-a0fb4570c622.png)
![image](https://user-images.githubusercontent.com/52477944/66896503-8064ef00-f027-11e9-8ac7-0b147b491a9d.png)

**Comment by ianhbell** [comment]
Can you please provide a link to his wrapper?  I would recommend an absolute path to the DLL to make sure things are working as you expect (current working directory and relative paths can behave in surprising ways).

**Comment by jafarialireza** [comment]
I download the Refprop_.NET_example.vb and added to my project, through the link below.

https://trc.nist.gov/refprop/LINKING/Linking.htm#NETApplications

**Comment by ianhbell** [comment]
Have you tried an absolute path to the DLL?

**Comment by krushnaeicp** [comment]
I have made vb.net refprop 10 project working at my end but I am not using Refprop() function introduced in Refprop 10 instead using refprop 9 routines. If you can share the source code (remove NIST or other your proprietary files), I may try to make your code working and resend it to you. 

Note: I don't work at NIST :).

**Comment by jafarialireza** [comment]
Please find the code through link below. By the way I found the problem, the dll and fluid address should be changed. Thanks to Mr. Ian Spanswick and  Dr. Eric and Dr. Ian
https://trc.nist.gov/refprop/LINKING/Linking.htm#NETApplications

**Comment by EricLemmon** [comment]
While looking through my hard drive for a few things, I found an old file that someone sent me a year ago that links Refprop with VB.net.  I tried running it on my machine, but my version of VS did not work with it.  I've added the file here, perhaps it will be of use to you or others.
[VBsample.zip](https://github.com/usnistgov/REFPROP-wrappers/files/3995391/VBsample.zip)

**Comment by jafarialireza** [comment]
Dear Dr. Eric,
I really appreciate your help.
Best
Ali
