### ISSUE TITLE
Refprop Python question on PQFLSHdll

### ISSUE THREAD

**Issue by mayersre** [usnistgov/REFPROP-wrappers#218]
Hello Refprop Team,

I try to port all my Software for mixtures from the Coolprop/Refprop
interface to the Refprop 10 Legacy interface.

How do I get the
```
- z (20) [double,in] :: Bulk Composition (array of mole fractions)
```
from a predefined mixture to feed it to e.G.  ``PQFLSHdll``. I can not find
this in the documentation.

You find my first attempt below in a python script

kind regards

Reiner Mayers
Bundesfachschule Kälte Klima Technik, Germany

``` python
# my Refprop 10 resides in /opt/rp10
#
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary as rpfl
#
fluid="R407F.MIX"
path = r"/opt/rp10"
os.environ['RPPREFIX'] = path
RP = rpfl(path, "so")
RP.SETPATHdll(os.environ['RPPREFIX'])
print('I see asterikses on the following command')
print(RP.RPVersion())
ierr, herr = RP.SETUPdll(1,fluid,'HMX.BNC','IIR')
p=50.0 # .5 bara
q=0    # liquid
z=[1]  # here get z from predefinition
kp=0 
x=RP.PQFLSHdll(p,q,z,kp)
print(x)
print('here I want the mixture enthalpy IIR scaled')
```

### Description

I cannot properly find how to use the new interface with predefined mixtures

### Steps to Reproduce

see the Python script above

### Additional Information
example above

**Comment by ianhbell** [comment]
First question is why you don't use the ``REFPROPdll`` function in general, or ``SETMIXdll`` for a predefined mixture. If you really want the reference state to be fixed, then you should call ``SETMIXdll`` and then ``SETREFdll``.

The ******* from RPVersion indicates that you need the patch, please email me at ian.bell@nist.gov

**Comment by mayersre** [comment]
I will read the relevant documentation again, but here an example would be very helpful
I will contact you for the patch.

**Comment by ianhbell** [comment]
Here you go:
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
MOLAR_BASE_SI = RP.GETENUMdll(0, "MOLAR BASE SI").iEnum
mix = 'R407F.mix'
sm = RP.SETMIXdll(mix,'HMX.BNC','IIR')
print(sm)
print(RP.SETREFdll('IIR',2,sm.z,0,0,0,0))
r = RP.REFPROPdll("", "QT", "H;S;M", MOLAR_BASE_SI,0,0,0,273.15,sm.z)
Hmolar, Smolar, M = r.Output[0:3]
print(Hmolar/M, Smolar/M)
```
