### ISSUE TITLE
loop over specific energy fails to return quality after few iterations.

### ISSUE THREAD

**Issue by jonasT44** [usnistgov/REFPROP-wrappers#22]
Dear Sir,
I am working with the beta version 9.44 and facing what I think is an issue coming from the wrapper.
A very simple loop over specific energy for a mixture fails to return quality after few iterations.
Please find attached the Matlab code.

```
clear all  
clc
close all
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%TO COMPLETE%%%%%%%%%%%%%%%%%%%%%%%%%%%
%PARAMETERS
%Name of the mixture
       mix='NGSAMPLE.MIX';
%Initial conditions
    rho=227.5851;
    P=101.325;
%number of iterations
    i_max=500;
%%
%%INITIALISATION
    q=0;
    i=1;
    qres=zeros(1,i_max);
%%
[u,version]=refpropm('u0','D',rho,'P',101.325,mix);
version %9.4426
while i<i_max
        [q]=refpropm('Q','D',rho,'U',u,mix);
        if (q<0 || q>1)
            return
        else
        qres(i)=q;
        u=u+1000;
        i=i+1;
        end
end
```

Perhaps, I should try it in the GUI to confirm it’s a wrapper issue ?
Best regards,

**Comment by ianhbell** [comment]
Yes, can you please confirm in the GUI?  I suspect this is a manifestation of a failure of a flash routine...

**Comment by jonasT44** [comment]
My bad. After a check in the GUI, the code and wrapper is fine. The 2-phase flash routine in matlab pops a warning [ierr:226] when  `[q]=refpropm('Q','D',rho,'U',u,mix)` has no solution in the two-phase area.
