### ISSUE TITLE
DLL in OS X

### ISSUE THREAD

**Issue by lee-zion** [usnistgov/REFPROP-wrappers#224]
### Description

I builded [REFPROP-Header](https://github.com/CoolProp/REFPROP-headers), REFPRP64.dll with [node-addon-api](https://github.com/nodejs/node-addon-api) using node-gyp in 64-bit Windows 10.

node worked in Windows environment.
And when running that in deployment environment(linux), it failed on running with following error.
```
Error: /app/src/napi.node: invalid ELF header
```
It seems like it is problem of build environment of mine(which is Windows 10, 64-bit).

So I tried to build in macOS, but it failed. It worked without any errors in Windows, but not in macOS.

I'm thinking about building C++ in Docker, but I want to ask is there any other possibilities without using docker or changing deployment environment.

### Steps to Reproduce

1. [Build C++ Project using REFPROP-Header with node-gyp, Build Result: *.node file]
2. [Bring that result to backend server. In Windows, it worked.]
3. [In Linux(deployment), it failed]

### Versions

REFPROP Version: 10.0
Operating System and Version: Windows 10, 64-bit / Mojave 10.14.6
Access Method: C++(REFPROP-Header)

**Comment by ianhbell** [comment]
It will definitely _never_ work to copy DLL from windows and run directly on linux/OSX.  You must recompile on the correct operating system. Please provide a complete build log for your build on OSX; "it failed" doesn't give me any idea how to help you get it workfing.

I agree that docker is a good option and idea, and I regularly build REFPROP inside docker containers for my projects to ensure that the build doesn't mess with the main operating system.

**Comment by lee-zion** [comment]
C++ build log in OSX
```
> node-gyp rebuild --debug

  SOLINK_MODULE(target) Debug/nothing.node
  CXX(target) Debug/obj.target/testaddon/cppsrc/addon.o
  CXX(target) Debug/obj.target/testaddon/cppsrc/myobj.o
  SOLINK_MODULE(target) Debug/testaddon.node
  COPY ../testaddon.node
  TOUCH Debug/obj.target/action_after_build.stamp
```

When I call `napi.node` in JS,
```
'Could not load REFPROP (refprop.dll) due to: dlopen(/Users/econ/basic-node-addon/refprop/refprop.dll, 2): no suitable image found.  Did find:\n\t/Users/econ/basic-node-addon/refprop/refprop.dll: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00\n\t/Users/econ/basic-node-addon/refprop/refprop.dll: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00. Make sure the library is in your system search path. In case you run 64bit Windows and you have a REFPROP license, try installing the 64bit DLL from NIST. '
```

Same error when I call with REFPRP64.dll

**Comment by ianhbell** [comment]
You must build the shared object of REFPROP on OSX, you cannot use the DLL of windows.  Please see https://github.com/usnistgov/REFPROP-cmake for a build system that you can use.

**Comment by lee-zion** [comment]
Just follow the instruction, but some errors happened.

Python 3.7.4 (with pyenv)

Build logs are attached below.

`cmake .. -DCMAKE_BUILD_TYPE=Release`

```
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 8.2.0
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Check for working Fortran compiler: /usr/local/bin/gfortran
-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes
-- Found PythonInterp: /Users/econ/.pyenv/shims/python (found version "3.7.4") 
-- DEFSYM_FLAG: 
-- darwin
Missing from PASS_CMN_tokens:  []
Missing from REFPROP_lib.h: []

-- Path to libquadmath.a:/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0/../../../libquadmath.a
-- Copied libquadmath.a here.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/econ/refprop-cmake/REFPROP-cmake/build
```

`cmake --build .`
```
Scanning dependencies of target REFPROP_H
[  6%] About to build the REFPROP.h header file w/ /Users/econ/.pyenv/shims/python;-u;/Users/econ/refprop-cmake/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/Users/econ/refprop-cmake/REFPROP-cmake/fortran/DLLFILES;--python-exe;/Users/econ/.pyenv/shims/python
Traceback (most recent call last):
  File "/Users/econ/refprop-cmake/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 2, in <module>
    import subprocess, sys, six, os, re
ModuleNotFoundError: No module named 'six'
make[2]: *** [REFPROP.h.stamp] Error 1
make[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ianhbell** [comment]
You just need to do a ``pip install six``.  I'll add that to documentation.  Strongly recommend to use the Anaconda python distribution, or start with miniconda.  It packages six automatically.

Generally, if you get an import error on a package, first thing to try is to pip install it.

**Comment by lee-zion** [comment]
Succeed on build, and using that .dylib in OSX fails on load_REFPROP again.

Error message is below:
```
'Could not load REFPROP (librefprop.dylib) due to: dlopen(/Users/econ/ref-backend/src/refprop/librefprop.dylib, 2): image not found. Make sure the library is in your system search path. In case you run 64bit Windows and you have a REFPROP license, try installing the 64bit DLL from NIST. '
```

BTW, would build with docker make environment independent .node file?

**Comment by ianhbell** [comment]
Please show your failing C++ code. 

A docker environment would allow you to run code *inside* the container, but that would not yield a platform-independent node file (to my knowledge)

**Comment by lee-zion** [comment]
Part of code related to load_REFPROP

```
Napi::Object SetUp(const Napi::CallbackInfo &info)
{
    Env env = info.Env();
    std::string absPath = info[0].As<String>().Utf8Value();
    std::string dllName = info[1].As<String>().Utf8Value();
    std::string err;
    bool loaded_REFPROP = load_REFPROP(err, absPath, dllName);
    if (!loaded_REFPROP)
    {
        Napi::Value retValue = Napi::String::New(env, err.c_str());
        return retValue.ToObject();
    }
   ...
}
```

And called that in nodejs returns error I've previously attached
```
import noderefprop from '../../refprop/noderefprop.

const dllPath = path.join(__dirname, '..', 'refprop');
const dllName = 'librefprop.dylib'
const result = noderefprop.setUp(dllPath, dllName, ...);
...
```

JS Directory Structures are
```
root
-- refprop
    -- librefprop.dylib
-- src
    -- JS files
```

**Comment by ianhbell** [comment]
Before you jump into node, please make sure that you can run the standard C++ code: https://github.com/coolprop/REFPROP-headers

I should warn you that I have zero experience with C++/node marshalling, so I'm not sure how much help I can provide.

**Comment by lee-zion** [comment]
I've checked C++ working, and then wrote that Napi:: for node in C++.

I must say it was very helpful, so much thanks to you!
I think I'll do rest of it.

**Comment by ianhbell** [comment]
This feels like a path problem.  OSX is sometime tricky to get DLL/dylibs loading properly.  Try with an absolute path to the dylib?

**Comment by lee-zion** [comment]
I thought the same.
I built .dylib and .node in docker, and resultant .node works fine in my production environment!
So, it seems not a problem of path. Maybe problem of build environment difference.

**Comment by ianhbell** [comment]
Could be DLL dependencies.  You could try to statically link the runtimes, which is what I usually do, though there are some good reasons to not do that.

**Comment by lee-zion** [comment]
I think that error in macOS is a problem of path, as you said.

REFPROP_lib.h (from [REFPROP-Headers](https://github.com/CoolProp/REFPROP-headers)) call dlopen function, and its [documentation](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/dlopen.3.html) is defining it as
```
dlopen(const char* path, int mode);
```
and REFPROP_lib.h uses dlopen
```
            #elif ( defined(__RPISLINUX__) || defined(__RPISAPPLE__) )
                // Load library
                RefpropdllInstance = dlopen(RP_join_path(shared_library_path, shared_lib).c_str(), RTLD_NOW); 
                // Error handling
                if (RefpropdllInstance == NULL) 
                {
                    const char *errstr = dlerror();
                    if (errstr != NULL) 
                    {
                        msg = errstr;
                    }
                } else {
                    RPPath_loaded = RP_join_path(shared_library_path, shared_lib);
                }
```
Since they treat Linux and OSX with same API, and Linux works while OSX does not.
Maybe there is problem in my .dylib, but .so works fine as they got same build process.
So, I'm suspecting nothing, and just build in Docker is the best option I got.

Maybe I should test the performance b/w current version of program and build with statically linked one.
Because I just borrow the computational resources, I wished to minimize the computational loads or sizes. Quite abstract anxiety because I haven't compared them :)

**Comment by ianhbell** [comment]
Linux and OSX use different logic for determining how to locate the shared library and its dependent libraries.  The most reliable method is usually to provide an absolute path to the library, rather than counting on the operating system to find it by its automatic methods.
