### ISSUE TITLE
Problem refprop integration with Excel

### ISSUE THREAD

**Issue by danres3** [usnistgov/REFPROP-wrappers#225]
### Description

I am contacting you about an issue that I found using Refprop (version 10) in Excel (both compiling directly in Excel or using VBA). For some refrigerants, in particular for mixture fluids, such as R410A, R448A, R449A, when calculating density, enthalpy or entropy with respect to pressure and quality (i.e. H(P,Q)), Refprop is not able to calculate the value if I am just above the critical pressure. The value that it gives back is "#undefined" (using VBA) or this error:

"#[PQFL2 error 223] Bubble point calculation did not converge"

My aim is to realize a table, where in the x axes I put the quality from 0 to 1, in the y axes I put the pressure, from the critical one (calculated with Refprop)  to the minimum one of the single refrigerant.
I attach a picture of the excel file.
Do you know if someone else had the same problem and how can I solve it?
Doing the same calculation directly in Refprop, the problem does not appear for R410A; for R448A and R449A only some points do not converge, while using Refprop in Excel lots of points do not converge.

### Steps to Reproduce

In Excel perform the following:

=REFPROP(“H”,"R410A", "QP", "SI with C", 0.02, 4.8)

**Expected behavior:** [What you expect to happen]

I use R410A as example. Writing the previuos formula (=REFPROP(“H”,"R410A", "QP", "SI with C", 0.02, 4.8)), I should get the numerical result

**Actual behavior:** [What actually happens]

Generating points from the critical pressure (4.9 MPa) to a lower pressure (4.5 MPa), hte calculation do not converge and in the excel cell will appear the error:
"#[PQFL2 error 223] Bubble point calculation did not converge"

### Versions

REFPROP Version: 10
Operating System and Version: Windows 10
Access Method: Excel VBA

### Additional Information

I attach a picture of the Excel file

![refprop_excel](https://user-images.githubusercontent.com/57407576/68226385-449fc280-fff2-11e9-94fb-888777c432c2.png)

**Comment by EricLemmon** [comment]
Take a look at this and see if it helps:  https://github.com/usnistgov/REFPROP-wrappers/issues/106

**Comment by danres3** [comment]
Thank you, now is partially working: if I use Excel directly, with the formula "=REFPROP(“H”,"R410A", "QP", "SI with C", 0.02, 4.8)" applied to a single cell, the calculation is done for more points than before, except for the critical one (I tried both R410A, R448A and R449A) and for some "random" points, always quite near to the critical pressure. I attach a new picture, to let you see what I meant.

 Using VBA is not working; my VBA is actually using the refprop 9.1 way of writing (=Enthalpy("R410A","QP","SiwithC",val1,val2)), could be this one the reason why is not working?
Thanks

![refprop_excel_iFlag_on](https://user-images.githubusercontent.com/57407576/68288346-85481c00-0084-11ea-892e-f2fb7f79823c.png)

**Comment by EricLemmon** [comment]
Can you either post your spreadsheet or email it to me directly (eric.lemmon@nist.gov)?  That will make debugging this much easier.

**Comment by EricLemmon** [comment]
I have not heard back about this, is this still an issue?  If so, could you post an example for me to look at?

**Comment by danres3** [comment]
I actually wrote directly to you on November 13th, not receving any response. I'll forward it again to you

**Comment by EricLemmon** [comment]
I've worked on your spreadsheet several times over the past few months, but I keep getting so many errors in the VBA code that I've never actually made it to the point where I could get the spreadsheet to run.  The errors are generally associated with the declaration of the variables.  If I declare a variable in one place, then it messes up another section, some of which deal with the cells in the spreadsheet that can't be declared, and so on.  I'm not sure why yours works and mine does not.

However, I have made a lot of fixes to the Fortran code since you last wrote and possibly this is fixed anyway.  If you would like to try the latest DLL, please send me a private email and I'll send it to you.

**Comment by EricLemmon** [comment]
If you have further questions, please let me know.  I'm going to close this, but we can always reopen it.
