### ISSUE TITLE
mole fraction array changed after REFPROPdll call

### ISSUE THREAD

**Issue by lee-zion** [usnistgov/REFPROP-wrappers#229]
I'm using REFPROP as object library and build some system with the library.
Currently, I'm facing issue to calculate table of properties within user-specified range and interval.

Just a function with some for loops seemed fine for me, and it works in pure fluids well. (Fast and valid).
However, when I use mixture for my fluid, it fail with Error message
```
[REFPROP error 813] The input composition must match that of the predefined mixture when the mixture name is included in the call to REFPROP. To use a different composition, leave the fluid name blank.
```
And found the reason.

When I set R410A for my fluid, and call SETMIXTUREdll set mole fraction array as `[0.697615 0.302385]`.
After REFPROPdll, it becomes `[0.5 0.5]`. 

In documentation, mole fraction array is `[double, in]`, so I'm somehow confused.
What point am I missing?

**Comment by EricLemmon** [comment]
Take a look at this issue and see if it answers your question:

https://github.com/usnistgov/REFPROP-wrappers/issues/74

**Comment by ianhbell** [comment]
You can always just pass the fluid name ``R410A.mix`` to ``REFPROPdll`` function, avoiding this issue entirely.

**Comment by lee-zion** [comment]
Sorry for late response. I just copied variable just before execute REFPROPdll, and overwrapped copied to argument fraction, since there seems no performance issue by this.
Maybe string handling to add `.fld` or `.mix` in name seems heavier to me, and since there is no issue till now, I'll just use coping now.
Thanks!
