### ISSUE TITLE
Carbon dioxide - methanol mixtures in Matlab

### ISSUE THREAD

**Issue by mariyanasavova** [usnistgov/REFPROP-wrappers#231]
As I am new to REFPROP, I have a couple of basic questions. 
I have REFPROPv10, and I would like to use it Matlab. Is there a document/tutorial/example scripts I can refer to for more information on what function are available? 

I am particularly interested in calculating the density of Carbon dioxide-Methanol mixtures. What function should I use for that? 

Is it also possible to calculate the volume fraction of methanol for the mixture given the same input parameters: the mass fraction, T, P.

**Comment by ianhbell** [comment]
Please read the docs for MATLAB in their entirety:  https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB#refprop-for-matlab

The REFPROPdll function is what you want: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB#use

And the docs for this function are here: https://refprop-docs.readthedocs.io/en/latest/
