### ISSUE TITLE
Request about error on using REFPROP 10 with Labview

### ISSUE THREAD

**Issue by MatteoM8831** [usnistgov/REFPROP-wrappers#232]
Dear Refprop support,
I hope you can help me on my issue.
###REfprop Dll rel 10
###Labview 18
We are trying to use the Refprop DLL (release10) on Labview (2018) to do a continuous calculations, still we use just one fluid (R410, R744  or glicol) the system works without any issue, but if we run calculation with more than one fluid, R744 + glicol (because we have different devices and system that works together), after a certain time that the application run (more or less 30000 interaction with any delay time) Labview crash due to impossibility to open the Refprop files.

Into our applications we usually use more than one refrigerant to carry out our continuous thermodynamic calculations.

To perform these calculations we are forced to use the SubVI "Utility initialization" every time we use a different refrigerant because, inside this VI, the dlls are configured for the specific file we use.
We have already verified that if this block is called only once before entering the loop for the calculations the results are incorrect.

We have also already tried to divide the calculations based on the refrigerant in use so as to limit as much as possible the calls to the aforementioned SubVI and forcing a wait between one calculation and another but this action has only delayed the problem.

What do you think? 
Do you have an idea how to solve this issue? 

Thanks a lot for your kind cooperation on that.
Best regards.

**Comment by ianhbell** [comment]
Do you have the same problem with REFPROP 9.x?

Also, an alternative solution might be to call Python wrapper from Labview, I gather that is possible, and we have no reports of weird memory-related issues like this in the Python wrapper.
