### ISSUE TITLE
problem whith the REFPROP upgrade to version 10

### ISSUE THREAD

**Issue by MMCampagna** [usnistgov/REFPROP-wrappers#233]
I have a REFPROP 9.1.1 version (32 bit) and I just purchased the upgrade to the REFPROP10 version.
I followed the instructions for the installation given at the link: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB.
Then I tried to run a simple test code in MatLab as follows:

 ``` matlab
close all
clear all
clc
 
%INPUT section start=========================================
gas='ARGON';
vapor='WATER';
yv=0.001;
 
T1=300; %K
p1=10e5; %Pa
p2=5.5e5; %Pa
%INPUT section end===========================================
 
yg=1-yv;
y=[yg,yv];
mix=sprintf("%s;%s",gas,vapor);
 
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP\REFPRP64.dll');
UNITS = RP.GETENUMdll(int8(0),"MOLAR BASE SI").iEnum;
r = RP.REFPROPdll(mix, "PTV","S",UNITS,int8(0),int8(0),p1, T1,y);
o = double(r.Output);
s1=o(1); %(J/kg)/K
s2=s1;
r = RP.REFPROPdll(mix, "PSV","T",UNITS,int8(0),int8(0),p2, s2,y);
o = double(r.Output);
T2=o(1); %K
 ```

Doing that, I get the following error
```
Error using py.ctREFPROP.ctREFPROP.REFPROPInstance/GETENUMdll
'iEnum' is already defined as a property.
```
Is it possible to get assistance for this issue? I didn’t find any similar problem on the FAQs available.

**Comment by ianhbell** [comment]
This is a new one for me...

What version of MATLAB and Python?

**Comment by MMCampagna** [comment]
MATLAB R2017b and Python 2.7.
If it can help, when I run 

--------------
>> RP.RPVersion()
--------------

I get:

-----------------
ans = 

  Python unicode with no properties.

    ******
----------------

**Comment by ianhbell** [comment]
Please see my edits with backticks for code blocks...

**Comment by ianhbell** [comment]
For your particular problem, if you use the most recent version of ctREFPROP, you should also be able to do:
```
r = RP.REFPROPdll(mix, "PTV","S",RP.MOLAR_BASE_SI,int8(0),int8(0),p1, T1,y);
```
which avoids the call to GETNUMdll.  I have no problem on my side, weird.

**Comment by ianhbell** [comment]
Also, not related, ``"PTV"`` is not a valid spec.

**Comment by MMCampagna** [comment]
With the line

r = RP.REFPROPdll(mix, "PTV","S",RP.MOLAR_BASE_SI,int8(0),int8(0),p1, T1,y);

I get:

Error using py.ctREFPROP.ctREFPROP.REFPROPInstance/REFPROPdll
'z' is already defined as a property.

**Comment by ianhbell** [comment]
Here is a working example in Python:
``` python 
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

gas='ARGON'
vapor='WATER'
yv=0.001

T1=300 #K
p1=10e5 #Pa
p2=5.5e5 #Pa

yg=1-yv
y=[yg,yv]
mix = gas+';'+vapor

root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
r = RP.REFPROPdll(mix, "PT","S",RP.MOLAR_BASE_SI,0,0,p1, T1, y);
print(r.Output[0])
s2=r.Output[0];
r = RP.REFPROPdll(mix, "PS","T",RP.MOLAR_BASE_SI,0,0,p2, s2, y);
print(r.Output[0])
```
yielding
```
135.66592320655278
236.1794933120743
```

**Comment by ianhbell** [comment]
I think you want the SETPATH call.

**Comment by MMCampagna** [comment]
I did it by running

pyversion C:\Users\MCampagn\AppData\Local\Continuum\anaconda2\python.exe

**Comment by ianhbell** [comment]
You probably want python 3.x at this point, but I don't think that is the problem.

**Comment by MMCampagna** [comment]
I tried with python and your script works. Thank you for your prompt replies. At least I can do my calculations with Python if I cannot fix this problem with Matlab. 
I tried also to install python 3 but I have the same problem. 
When I open the Anaconda prompt to check where is my python I get the following:

(base) PS C:\> where python
Where-Object : Cannot bind parameter 'FilterScript'. Cannot convert the "python
" value of type "System.String" to type "System.Management.Automation.ScriptBlo
ck".
At line:1 char:6
+ where <<<<  python
    + CategoryInfo          : InvalidArgument: (:) [Where-Object], ParameterBi
   ndingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerSh
   ell.Commands.WhereObjectCommand

(base) PS C:\>

**Comment by ianhbell** [comment]
Whoah, never seen that before...  My guess is your friends in the IT department have blocked something according to that error message?

**Comment by MMCampagna** [comment]
Then I will have a talk with my friends in the IT department :D. Anyway do you think this problems are somehow related?

**Comment by ianhbell** [comment]
Maybe?  If your python is unhappy, I don't see how the MATLAB+Python interfacing is going to work properly.

**Comment by MMCampagna** [comment]
When I run your python script, my python seems to enjoy it. Mybe he doesn't like Matlab, but it seems to like Refprop10.

**Comment by ianhbell** [comment]
But there's a lot of special sauce in between MATLAB and Python, and MATLAB does all kinds of naughty things with changing system configuration variables silently, so who knows?

**Comment by MMCampagna** [comment]
I tried the same procedure with my personal laptop. Exactly the same problem:

```
Error using py.ctREFPROP.ctREFPROP.REFPROPInstance/GETENUMdll
'iEnum' is already defined as a property.
```
Maybe I am doing something wrong, but I am not getting where is the problem.

**Comment by ianhbell** [comment]
My guess is this is a bug in the MATLAB <-> Python interface, since the code works in Python.  I think you'll have to connect with Mathworks.  But first, maybe upgrade to MATLAB 2019?
