### ISSUE TITLE
python wrapper - if this gives ***** with REFPROP 10.0.0, please see us to get a patch

### ISSUE THREAD

**Issue by dferguso** [usnistgov/REFPROP-wrappers#234]
### Description

When I run print(RP.RPVersion()) in Jupyter Notebook I get "******".  I was instructed to request a patch.

### Versions
**REFPROP Version:10.0
**Operating System and Version:** Windows 10
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  Python

**Comment by ianhbell** [comment]
Please email me at ian.bell@nist.gov.

**Comment by dferguso** [comment]
Fixed with an update to some of the dll's.
