### ISSUE TITLE
Issues using REFPROP Excel add-in

### ISSUE THREAD

**Issue by GOliveira-SC** [usnistgov/REFPROP-wrappers#235]
I'm part of the Air Liquide Brazil IT team, and one of our colleagues is having issues using the add-in to check her sheet.
I tried reinstalling Excel (both x86 and x64), downloading a new add-in I found online, I reinstalled NIST REFPROP, but none helped with this issue.
 
As you can see in the picture below, the results are shown as "NAME?" (sometimes as "VALUE?"), instead of the values of the materials she's trying to reach.
![image](https://user-images.githubusercontent.com/59116183/71308436-44f5f080-23db-11ea-9549-ab0b0f829faf.png)

Is there any solution I didn't try using as I described above?

**Comment by EricLemmon** [comment]
Take a look at the comments at the website below.  Most problems can be solved with the information there.
https://pages.nist.gov/REFPROP-docs/#resolving-problems-linking-with-excel
