### ISSUE TITLE
Refprop 9.1:The function GETENUMdll could not be loaded from the shared library.

### ISSUE THREAD

**Issue by patelpp82** [usnistgov/REFPROP-wrappers#236]
### Description

I followed all steps for refprop 9.1 but still geting "The function GETENUMdll could not be loaded from the shared library." error
### Steps to Reproduce

import os; os.environ['RPPREFIX'] = r'C:/Program Files (x86)/REFPROP/REFPRP64.DLL'
import numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

def NBP():
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    print(RP.RPVersion())
    RP.SETPATHdll(os.environ['RPPREFIX'])
    r = RP.SETUPdll(1,"PROPANE.FLD","HMX.BNC","DEF")
    assert(r.ierr == 0)
    print(RP.PQFLSHdll(101.325, 0, [1.0], 0))

if __name__=='__main__':
    # Print the version of REFPROP in use and the NBP
    NBP()

**Expected behavior:** [Clean Output]

**Actual behavior:** [ValueError                                Traceback (most recent call last)
<ipython-input-10-017ab36bdb23> in <module>
     12 if __name__=='__main__':
     13     # Print the version of REFPROP in use and the NBP
---> 14     NBP()

<ipython-input-10-017ab36bdb23> in NBP()
      3 
      4 def NBP():
----> 5     RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
      6     print(RP.RPVersion())
      7     RP.SETPATHdll(os.environ['RPPREFIX'])

~\AppData\Local\Continuum\anaconda3\lib\site-packages\ctREFPROP\ctREFPROP.py in REFPROPFunctionLibrary(name, shared_extension)
    165 
    166     managed_handle = None # Not part of the manager, we are creating a standalone instance of REFPROP
--> 167     return REFPROPInstance(dll, managed_handle)
    168 
    169 class REFPROPInstance(object):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\ctREFPROP\ctREFPROP.py in __init__(self, dll, managed_handle)
    539         self._XMOLEdll = self._getfcn(self.dll, 'XMOLEdll')
    540 
--> 541         self.DEFAULT = self.GETENUMdll(0, 'DEFAULT').iEnum
    542         self.MOLE_SI = self.GETENUMdll(0, 'MOLE SI').iEnum
    543         self.MASS_SI = self.GETENUMdll(0, 'MASS SI').iEnum

~\AppData\Local\Continuum\anaconda3\lib\site-packages\ctREFPROP\ctREFPROP.py in GETENUMdll(self, iFlag, hEnum)
   1555         herr = ct.create_string_buffer(255)
   1556 
-> 1557         if self._GETENUMdll is None: raise ValueError("The function GETENUMdll could not be loaded from the shared library.")
   1558         self._GETENUMdll(ct.byref(iFlag),hEnum,ct.byref(iEnum),ct.byref(ierr),herr,255,255)
   1559 

ValueError: The function GETENUMdll could not be loaded from the shared library.]

### Versions

**REFPROP Version:** [REFPROP 9.1]  
**Operating System and Version:** [Windows 10 64 bit]  
**Access Method:** [Python wrapper)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by EricLemmon** [comment]
Refprop 9.1 did not have the GETENUM function nor the new REFPROP subroutine.  Those are all new in version 10, and are possibility one of the best parts of version 10, that being where you don't have to know 50 subroutines and their calling conventions anymore, you simply have one routine and most of the inputs are intuitive (at least for some of us...).
