### ISSUE TITLE
The issue of enthaply calculation when using predifined mixture R410A

### ISSUE THREAD

**Issue by gautam-subburaj** [usnistgov/REFPROP-wrappers#238]
@ibell 
I have been using REFPROP 10 for calculating enthalpy of R410A.
Below program shows the calculation part.
I am not getting an exact value when compared with the data from REFPROP program
Please tell me the reason why i am getting this problem.

``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')
Mass_BASE_SI = RP.GETENUMdll(0,"MASS BASE SI").iEnum
r = RP.REFPROPdll("R32;R125","tQMASS","h",Mass_BASE_SI, 0,0,300, 0, [0.5,0.5])
M=float(r.Output[0])
print(M)
```

**Result from program**
`M: 241034.68256593106 J/Kg
`

**Result from REFPROP program:**

![image](https://user-images.githubusercontent.com/59637885/71957748-97754080-3214-11ea-90e6-1b78392b030c.png)

**Comment by ianhbell** [comment]
I think you are getting burned by the mass fraction bug, but maybe not.

I tried
```
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(r'D:\Program Files (x86)\REFPROP')
r = RP.REFPROPdll("R410A.MIX","TQMOLAR","h",RP.MASS_BASE_SI, 0,0,300, 0, [0.0])
print(r.Output[0])
```
and got
```
244210.8595521985
```
Now we have a third answer :)

**Comment by ianhbell** [comment]
One thing that I noted with your code is that you set iMass to 0, while it should be 1 : 

![image](https://user-images.githubusercontent.com/11966765/71992652-fb870d00-31f2-11ea-837f-34eaafa247cb.png)

But we (@EricLemmon and I) are discussing how it *should* work, because changing it doesn't do what it should.  In your example it doesn't change the results if you change iMass.  As workarounds for you (either should fix it):

1. Use "R410A.MIX" as your fluid name
2. Use mole fractions.

**Comment by gautam-subburaj** [comment]
Thank you.

**Comment by gautam-subburaj** [comment]
but this value does not come close to the value from the REFPROP software

**Comment by ianhbell** [comment]
@EricLemmon what do you think?

**Comment by gautam-subburaj** [comment]
i have been using matlab to code using refprop.
so i connected matlab and excel to get back the exact value as compared to erroneous value from python.
i have attached the program for it and i get the same value as the REFPROP Program.

```
function y=refprop(fluid_in,input_var,output_var,units,a,b)
Excel = actxserver('Excel.Application');

% Open file on disk

Excel.Workbooks.Open('C:\Program Files (x86)\REFPROP\REFPROP.xla');

% Use this method to execute any Auto_Run macros.

Excel.Workbooks.Item('REFPROP.xla').RunAutoMacros(1);

% Now that the Add-in is loaded, execute the macro it contains:

str=['=REFPROP("' output_var '","' fluid_in '","' input_var '","' units '",' num2str(a) ',' num2str(b) ')'];

xlswrite('F:\REFPROP\e.xlsx',cellstr(str),'Sheet1','A1');

%Finally, make Excel visible.

% Open Excel

excelWorkbook = Excel.workbooks.Open('F:\REFPROP\e.xlsx');

% Save the workbook

Excel.ActiveWorkbook.Save();

% % Close the workbook.

excelWorkbook.Close(false);

% % Shut down Excel.

Excel.Quit;

y = xlsread('F:\REFPROP\e.xlsx','sheet1','A1');
```

**Comment by ianhbell** [comment]
What contents get written to that cell?  Would help to debug what is going on.  I think the key problem with the Python calls is that the REFPROPdll function doesn't appear to allow mass fractions as inputs as the array.

**Comment by gautam-subburaj** [comment]
the excel does not ask us any mass or molar function.
so i think this is defined based on the units (that is whether it is mass SI or others) that we define in the refprop function.

**Comment by ianhbell** [comment]
What are the contents of the Excel cell that work?

**Comment by gautam-subburaj** [comment]
As per the program we send the refprop function based on the formula of the excel.
That is we send =REFPROP("h","water","tqmass","si",300,1) to the excel formula bar from matlab.
This calculates the value in the background and then we xlsread this value in matlab.

**Comment by ianhbell** [comment]
I think you shouldn't need to do this Excel interchanging and we should be able to find a workaround with the Python interface.  Can you please provide the Excel cell contents used for the call at the beginning of this issue?  Python and Excel call the same dll :)

**Comment by gautam-subburaj** [comment]
We have not changed anything in the dll file. we are just using the refprop function in the excel.

**Comment by gautam-subburaj** [comment]
excel works perfectly for us as it gives exact value as given by the REFPROP software.

**Comment by gautam-subburaj** [comment]
maybe there is some problem in the ctREFPROP library of python?.
Also can the above program in maltab run faster ?

**Comment by ianhbell** [comment]
It is possible that there is a bug in the Python interface, but very unlikely.  What call in excel "gives the exact value as in the REFPROP software". 

Yes, use a language like Python or C++.

**Comment by gautam-subburaj** [comment]
thank you

**Comment by ianhbell** [comment]
Can you please answer the question of what call in excel "gives the exact value as in the REFPROP software".

**Comment by gautam-subburaj** [comment]
Sorry for the delay.
We call the function **=REFPROP("h","r410a","tqmass","si",300,0)** in excel and get back the data to MATLAB which gives the value of **242.997 kJ/kg**.
Whereas Refprop program is giving us a value of 243 kJ/kg.
We are only using the REFPROP addin and ribbon to calculate through excel.
**I do not understand what you mean by the call in excel.**

**Comment by ianhbell** [comment]
I think this might be a question of reference state.  What reference state option have you selected in the GUI?  Also, you should 100% of the time indicate whether you mean the pseudo-pure fluid ("R410A.PPF") or the predefined mixture ("R410A.MIX")

**Comment by EricLemmon** [comment]
Take a look at this issue and see if it helps:
https://github.com/usnistgov/REFPROP-issues/issues/222

**Comment by gautam-subburaj** [comment]
Thank you i have understood the problem that the python wrapper considers the usage of default reference property and the GUI uses a different reference.

**Comment by mayersre** [comment]
Hello,

possibly I missed a part of this mailing ...

actually you can set the reference of state in the Refprop GUI and in
the python wrapper.
In the gui it is somewhere in the Menu.

In the python wrapper you can set it like this:

import CoolProp.CoolProp as cp
#
cp.set_reference_state('n-Propane','IIR')

In the documentation of CoolProp 6.3 you will find the alternatives to
'IIR'.

kind regards
Reiner

Am 02.02.20 um 08:12 schrieb gautam-subburaj:

**Comment by gautam-subburaj** [comment]
how do i set REFPROP referece property for mixture in python?

**Comment by gautam-subburaj** [comment]
do i need to use setrefdll command? i do not know the porper syntax for the command

**Comment by mayersre** [comment]
Here comes a start of a class with init ....


import os, sys, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary as rpfl
#
import numpy as np
#
class rpfluid():
    '''
    '''
   
    def __init__(self,fluid="R407F.MIX"):
        '''
        '''
        self.fluid=fluid
        #
        path = r"/opt/rp10"
        os.environ['RPPREFIX'] = path
        #
        self.RP = rpfl(path, "so")
        self.RP.SETPATHdll(os.environ['RPPREFIX'])
        print(self.RP.RPVersion())
        self.MASS_BASE_SI = self.RP.GETENUMdll(0,"MASS BASE SI").iEnum
        #
        ierr, herr = self.RP.SETUPdll(1,self.fluid,'HMX.BNC','IIR')
       
        r =
self.RP.REFPROPdll(self.fluid,"PQ","TMIN|TMAX|PMAX|DMAX|TCEST|PCEST",self.MASS_BASE_SI,
0,0,101325, 0, [1.0])
        self.TMIN=r.Output[0]
        self.TMAX=r.Output[1]
        self.PMAX=r.Output[2]
        self.DMAX=r.Output[3]
        self.TCRIT=r.Output[4]
        self.PCRIT=r.Output[5]
        r2 = self.RP.REFPROPdll(self.fluid,"TQ","P",self.MASS_BASE_SI,
0,0,self.TMIN, 0, [1.0])
        self.PMIN=r.Output[0]
        print('Model Limits :')
        print('TMIN = {} °C'.format(self.TMIN-273.15))
        print('TMAX = {} °C'.format(self.TMAX-273.15))
        print('TCRIT = {} °C'.format(self.TCRIT-273.15))
        print('PMIN = {} bara'.format(self.PMIN/100000))
        print('PMAX = {} bara'.format(self.PMAX/100000))
        print('PCRIT = {} bara'.format(self.PCRIT/100000))
        print('DMAX = {} kg/m³'.format(self.DMAX))
   
I run this with Ubuntu 18.x and refprop library installed in
/opt/refprop, you have to adapt to 'dll' and
use the proper path with windows.

Read the solved issues, they contain a lot of Information.

/Reiner

Am 02.02.20 um 10:56 schrieb gautam-subburaj:

**Comment by gautam-subburaj** [comment]
In GUI i found reference state setting as 
![image](https://user-images.githubusercontent.com/59637885/73716726-e0e67c00-473d-11ea-8180-4fcc8fd3135b.png)

How do i change this in python program?

**Comment by ianhbell** [comment]
Please see: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SETREFdll

**Comment by EricLemmon** [comment]
Has this issue been resolved?

**Comment by gautam-subburaj** [comment]
yes thank you.
