### ISSUE TITLE
Different values of Density for LNG on saturated lines.

### ISSUE THREAD

**Issue by EsterC24** [usnistgov/REFPROP-wrappers#24]
Hi,
I'm testing the beta 9.4438(021) with matlab wrapper. I'm studing LNG properties. I would like to evaluate density, also for the liquid and vapor phase, on the liquid and vapor saturated lines (quality equal to 0 and 1).
If I use as inputs pressure and quality everything is fine, and the values obtained are equal to the ones found in REFPROP software. (D_l1 = 451.9610, D_v1 = 1.8438, D1 = 451.9610).
If I use pressure and the value of Enthalpy evaluated for the same pressure and quality, the values of densities obtained are wrong and different from the previous ones. (D_l2 = 147.4800, D_v2 = 0.9883, D2= 94.1627).
I tried with different values of pressure, and quality equals to 0 and 1. With quality equals to 1 we have problems only with the value of the liquid density. The values of enthalpy in the first and second case are equal (H=Hmin), the same as quality (Q=Q1). Why I have these problems for the density?

```
clc
clear all
close all

oldpath = path;
path(oldpath,'C:\Refprop\REFPROP_944_38_21')

mix='NGSAMPLE.MIX';
Q=0;

[H,D_l1,D_v1,D1]=refpropm('H+-D','P',101.325,'Q',Q, mix);
H
D_l1
D_v1
D1

Hmin=refpropm('H','P',101.325,'Q',Q,mix);

[Q1,D_l2,D_v2,D2]=refpropm('Q+-D','P',101.325,'H',Hmin, mix);
Q1
D_l2
D_v2
D2
```
Thank you for the attention,
Ester

**Comment by ianhbell** [comment]
Thanks for the report, I have forwarded the issue to our resident flash calculation guru.

In the future, this issue should probably be directed to https://github.com/usnistgov/REFPROP-issues/issues because it is an issue with REFPROP itself, not the wrappers around it.

Have a nice day!

**Comment by EsterC24** [comment]
Ok, it will surely be done. 
Thank you for your time.
Ester
