### ISSUE TITLE
Call Csat

### ISSUE THREAD

**Issue by angi1540** [usnistgov/REFPROP-wrappers#240]
How i can call Csat (Saturated heat capacity) using refpropm on matlab?

**Comment by ianhbell** [comment]
That parameter is not accessible in the refpropm wrapper.  Also, the refpropm wrapper is no longer supported, and lacks many features available in the Python-based interface, so I recommend you upgrade.

**Comment by ianhbell** [comment]
The python-based interface gives you the full functionality of the new REFPROPdll function, which does include Csat.
