### ISSUE TITLE
Mixture list difference between GUI and dll

### ISSUE THREAD

**Issue by lee-zion** [usnistgov/REFPROP-wrappers#241]
### Description

I'm trying to calculate some properties of R452B.
I can see R452B as predefined mixture in Windows GUI program, but R452B.MIX do not exist in fluid data of source code.

I have two question.
1. Is there any reason for different fluid data directory between GUI program and source code?
2. Can I copy R452B.MIX from Windows GUI and paste to fluid data in fortran source code?

### Versions

**REFPROP Version:** REFPROP 10.0
**Operating System and Version:** Windows 10
**Access Method:** Use R452B.MIX through C++

**Comment by ianhbell** [comment]
You'll find R452B.MIX in the MIXTURES folder:
![image](https://user-images.githubusercontent.com/11966765/72770952-a49f1180-3bbc-11ea-9df8-d725e21ca59d.png)

**Comment by lee-zion** [comment]
Yes, I can see R452B.MIX only in Installed REFPROP's directory.
Fortran source code also have mixtures, but there is no R452B.MIX

I was asking that there is difference in fluid list, and is there any technical reason for the difference.

**Comment by ianhbell** [comment]
I assume therefore that your "Fortran source" is from version 9.x, which did not include this predefined mixture, if I remember correctly.  In either version you could define the mixture explicitly.  The predefined mixtures are only there for convenience.

**Comment by EricLemmon** [comment]
I don't know the equivalent call in C++, but in VB you can request a .mix file to be loaded by simply sending the name of the mixture file in the first argument to the REFPROPdll call:
```
  hFld="R452B.mix"
  Call REFPROPdll(hFld, hIn, hOut, iUnits, iMass, iFlag, a, b, z(1), Output(1), hUnits, iUCode, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)
```
Just be sure to include the letters ".mix" in the string that you send to the routine.
