### ISSUE TITLE
Refprop 10 I have installed now on two fresh machines and followed the installation proceedure but all I get is #VALUE! responses. I am running in a macro allowed 

### ISSUE THREAD

**Issue by kennethwmartin301** [usnistgov/REFPROP-wrappers#243]

**Comment by AndrewPrice775** [comment]
I had this issue as well. 
When I opened REFPROP.xls, the equations worked but not in a new blank workbook (#VALUES error) even thought the refprop formulas were coming up. I copied the file paths from the working workbook's vba (REFPROP.xls) into the .xla file's vba (this is the code read from new workbooks) and that solved the issue in my case.

**Comment by EricLemmon** [comment]
Thanks for this excellent comment!  I have just added this concept to the FAQ site under the Excel section.
