### ISSUE TITLE
Temperature off on MatLAB RefProp 

### ISSUE THREAD

**Issue by Yili-Zhang** [usnistgov/REFPROP-wrappers#244]
``` python
%% Set Up - Call RefProp in MatLAB
% Refprop MatLAB setup instruction web: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
MASS_SI=RP.GETENUMdll(int8(0), "MASS SI").iEnum; % Unit System: Mass SI

hFld = 'Water';

P11=2.5163 % [MPa]
h11=177.8723 [kJ/kg]
```

### Description

Hi, I have a state pressure and enthalpy, as shown of the code above. I would like to find the corresponding temperature [K] with the P11 and h11, but no matter what I do, the answer is always off from what is calculated in the Engineering Equation Solver, which is 315.1 K

### Steps to Reproduce

1. When I directly use P11 and h11 to produce entropy S11, then use S11 and P11 to produce the temperature, or use P11 and h11 to produce entropy S11 first, then use h11 and s11 to produce T11, I have the answer as T11=313.4931 [K], and here is the partial code:
``` python
S=RP.REFPROPdll(hFld,'PH','S',MASS_SI,int8(0),int8(0),P11,h11,{1.0});
S_num=double(S.Output);
S11=S_num(1); 

T=RP.REFPROPdll(hFld,'PS','T',MASS_SI,int8(0),int8(0),P11,S11,{1.0});
T_num=double(T.Output);
T11=T_num(1);
```
or
``` python
S=RP.REFPROPdll(hFld,'PH','S',MASS_SI,int8(0),int8(0),P11,h11,{1.0});
S_num=double(S.Output);
S11=S_num(1); 

T=RP.REFPROPdll(hFld,'HS','T',MASS_SI,int8(0),int8(0),h11,S11,{1.0});
T_num=double(T.Output);
T11=T_num(1);
```

2. When I use P11 and h11 to produce quality, and then use pressure and quality to produce the temperature, I got the temperature as: T11=300 [K], and here is the partial code:
``` python
Q=RP.REFPROPdll(hFld,'PH','QMASS',MASS_SI,int8(0),int8(0),P11,h11,{1.0});
Q_num=double(Q.Output);
Q11=Q_num(1);

T=RP.REFPROPdll(hFld,'PQMASS','T',MASS_SI,int8(0),int8(0),P11,Q11,{1.0});
T_num=double(T.Output);
T11=T_num(1);
```

3. When I directly use P11 and h11 to produce the temperature, T11, or I use P11 and h11 to find the density first, then use density to find the temperature, I got the temperature as: T11=199.8669 [K], and here is the code:
``` python
T=RP.REFPROPdll(hFld,'PH','T',MASS_SI,int8(0),int8(0),P11,h11,{1.0});
T_num=double(T.Output);
T11=T_num(1);
```
or
``` python
D=RP.REFPROPdll(hFld,'PH','D',MASS_SI,int8(0),int8(0),P11,h11,{1.0});
D_num=double(D.Output);
D11=D_num(1);

T=RP.REFPROPdll(hFld,'PD','T',MASS_SI,int8(0),int8(0),P11,D11,{1.0});
T_num=double(T.Output);
T11=T_num(1);
```

**Expected behavior:** T11=315.1 [K]

**Actual behavior:** T11=313.4931 [K] or T11=300 [K] or T11=199.8669 [K]

### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** Windows 10 Enterprise
**Access Method:** MATLAB

### Additional Information

The state 11 in my simulation system is the state after water going through a pump, where the state before entering pump has the temperature as T10=314.817 [K]. Although the closest answer is T11=313.4931, which is only 1.5 K off from the right answer, it is still incorrect because it should at lease be greater than T10.

I would like to know why I could never get the correct answer? Why is that the results are different with different approach? what went wrong with my approach? Or it is just the RefProp bug? Thanks a ton!

**Comment by ianhbell** [comment]
Please see: https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences

To test this problem, start off with a set of properties that do not have a reference state in them, for instance, temperature and pressure, then at that state point calculate h, and see whether both libraries are using the same reference state (I suspect they are not). Unless the reference states are the same, you cannot take enthalpies or entropies from one library or table and use them in another one.

I'm 99.999% sure that this is the problem; its the #1 FAQ with REFPROP.

**Comment by Yili-Zhang** [comment]
Hi , Thanks for the reply. 

Before state 11, the enthalpy at state 10 is accurate, and the enthalpy at state 11 is calculated from: h11=h10+h_diff, where h_diff is the enthalpy difference between state 10 and 11. Thus, the enthalpy calculated at state 11 is also correct. The problem is, with the correct pressure and enthalpy at state 11, the corresponding temperature is off. In comparison, with the given pressure and correct enthalpy at state 8, the temperature was correct.

That's being said, I still did an experiment of calculating the enthalpy at state 11 given the correct pressure and enthalpy, the results showed that the calculated enthalpy was off as well...

I don' know how to fix this problem, for pressure and enthalpy is the only two things I know at state 11 and I need to find the corresponding temperature.

Looking forward to your reply.

Thanks,

-Yili

**Comment by ianhbell** [comment]
What is the state point 10?

**Comment by ianhbell** [comment]
And what enthalpy do you get in EES at that state point?

**Comment by Yili-Zhang** [comment]
The enthalpy at state 10 in MATLAB RefProp is 174.5013; while in EES is 174.5;
The enthalpy at state 11 in MATLABRefProp is  177.8723; while in EES is 177.4 (Okay, I just realized it is off here)

However, it was all accurate for the states before. For example, at state 8, the enthalpy from MatLAB RefProp is 2264.2; while in EES is 2264, which is calculated in a similar way as in State 11.

Why is that the results start to be inaccurate from the middle of the system, instead of being inaccurate right from the beginning...?

**Comment by ianhbell** [comment]
What are the other thermodynamic properties at state points 8,10? One question is whether EES is using the same reference state.  Knowing the enthalpy with no other thermodynamic properties isn't enough to debug what is going on.

What information does EES provide for what equation of state is being used for water?

**Comment by EricLemmon** [comment]
Did you get an exact temperature of 300 for T in the third step?  If so, that would indicate an error happened.  Are you checking the error values at each step?  The next problem is that you might be getting hit by a bug that finds a second root in the water equation of state at low temperatures.  It's a "real root" according to the EOS, but Refprop should not be looking down there for it.  We have fixed that and can send you an updated DLL for you to test.  Send one of us an email so that we can get that to you.  (eric.lemmon@nist.gov or ian.bell@nist.gov).  But first, be sure to check the error value!!!

**Comment by Yili-Zhang** [comment]
Hey Thanks guys!!

I just had a meeting with my professor. He said the pressure goes up like 300 times from state 10 to state 11, so that the effects of difference of the equation of states starts to become more obvious. However, the temperature of the water doesn't have to increase after going through a pump, while the pressure would definitely go up.

Thus, I guess I am fine with the results for now, but I will let you guys know if this is gonna be a problem for my system in the future.

Please feel free to close this comment, and I really appreciate help from you guys!!

Best,

-Yili

**Comment by ianhbell** [comment]
Couple of things:

* Feel free to click the close button when you are satisfied that the issue is resolved.
* Is EES really not using exactly the same EOS as REFPROP?  There's only one international standard for water, and EES should definitely be using it.  What EOS do they use?
* The temperature going through the pump should always increase.  Maybe not a lot, but unless you have external heat transfer, it must increase because W_pump = mdot*(Delta h) is positive, and therefore, the change in enthalpy must be positive, and if we assume cp to be constant and positive, the temperature must rise.
