### ISSUE TITLE
Vapor quality calculation in single-phase

### ISSUE THREAD

**Issue by TDS-Lux** [usnistgov/REFPROP-wrappers#246]
RefProp version 10.
EXCEL/VBA wrapper
 
Dear all,

In the previous versions (before 10), RefProp was calculating the vapor quality even if the fluid is not in 2-phase state. The quality > 1 for superheated state and < 1 for subcooled state.
Unfortunately, with the version 10, RefProp refuses to calculate the quality outside 2-phase flow domain. Is there a way to change this? here is the instruction I'm using 
“x = REFPROP("Qmass", “R134a”, "PH", "USER", P, h)”. It works perfectly as long as the fluid is in 2-phase flow. 

Indeed, the quality in single-phase doesn't have a physics meaning but I need it to plot the evolution of the quality from superheated region to subcooled region for condensers. 

Thanks a lot for your precious help,

**Comment by EricLemmon** [comment]
We're looking into this and trying to find a better way to give back Q outside of the two-phase region since it can be defined several way.  We'll get back to you soon.

**Comment by ianhbell** [comment]
There are a few reasons why providing this parameter is problematic.  One is that to do so requires the calculation of the phase equilibria, which means a _much_ slower calculation for the single-phase states.  I've done a lot of heat exchanger modeling, so I am sympathetic to your need for this parameter in particular.

What definition of single-phase vapor quality do you expect?

**Comment by TDS-Lux** [comment]
Dear Eric, Ian,

Thank you very much for your quick reply.

The way how I modeled heat exchangers (abrv. HEX) requires the calculation of vapor quality (noted ''x'') at the inlet of a each pass. The fluid state at the inlet of each pass is not known a priori due to the fact that the pressure drop in the manifold could change the fluid state. In addition, I discretize HEX in small segments and during iteration within a segment the fluid state could change from 2-phase flow to single phase and then RefProp 10 will highlight an error if the vapour quality is calculated for single-phase.  For that, when there is a risk to be in single-phase, to calculate "x", I calculate first saturated vapor enthalpy (h_sv) and saturated liquid enthalpy (h_ls) and then x = (h_i - h_sl)/(h_sv-h_sl). That's work perfectly. The only thing is that I have more code lines and two calculations (h_sv and h_sl) instead to calculate directly the quality with RefProp.

Since I didn't have such "issue" with previous versions of RefProp, I thought it would be easy to force RefProp 10 to calculate "x" even in single phase. 

Since it's not straightforward to do this with the version 10 or because of a slower execution, I cancel my request and I continue to calculate "x" according to "h-sv" and "h-sl". My program works perfectly.
I really thank you for the efforts you spent to add new fluids and to increase the execution speed of RefProp; my programs run faster. 

For your information, I developed a simulation tool dedicated to performance prediction of any type of automotive HEX (single- and two-phase flow) and simulation tools for household refrigeration HEX. 

With all my best regards,
Fadil

**Comment by ianhbell** [comment]
I think for now it is best that REFPROP doesn't try to be too "smart", because you could do what you did in a number of different ways (and we haven't even started talking about mixtures yet).  Glad to hear you have your code working again.

**Comment by EricLemmon** [comment]
I've added the label "feature-request" to remind us to come back to this someday when we have a good solution.  For now I will close this issue.  Please feel free to reopen it if you wish to further comment with ideas for implementing your request.
