### ISSUE TITLE
GETENUMdll() failed with none, I am using win10, Refprop 9.1, anaconda conda 4.7.12, python 3.7.4

### ISSUE THREAD

**Issue by wangdehui20180506** [usnistgov/REFPROP-wrappers#247]
could you please help with the issue of 
GETENUMdll() failed with none
I am using win10, Refprop 9.1, anaconda conda 4.7.12, python 3.7.4, 
thank you in advance!

**Comment by EricLemmon** [comment]
The subroutine GETENUM is something new in Version 10 and not available with 9.1.  You have to do things the hard way with 9.1!

**Comment by wangdehui20180506** [comment]
thank you!
