### ISSUE TITLE
Trouble with REFPROP version command

### ISSUE THREAD

**Issue by HarrisonSkye** [usnistgov/REFPROP-wrappers#251]
### Description
I typed the following command into MATLAB:

> RP.RPVersion()

and it returns

>  ans = 
> 
>   Python str with no properties.
> 
>     ******

What can I do to get the actual REFPROP version, rather than "******"

**REFPROP Version:** [10.0]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [Python 3.7.6]

**Comment by ianhbell** [comment]
You are welcomed to email me for the patch, another workaround is the DLL# option in REFPROPdll: 
![image](https://user-images.githubusercontent.com/11966765/74891389-ea363200-5354-11ea-8862-c64513053033.png)

**Comment by HarrisonSkye** [comment]
The emailed patch fixed the problem, thank you very much!
