### ISSUE TITLE
Can't save the REFPROP XLA

### ISSUE THREAD

**Issue by mcconnde** [usnistgov/REFPROP-wrappers#252]
### Description
I could not see the macro to convert V9.1 calls to V10.  I didn't want to use the patch, so I started going through the list of things to do that has been provided

I was trying to simply append the full path to the 64 bit refprop dll and it will not save.  I have even deleted the original XLA (after saving a copy and renaming it) and edited the XLS sheet saved IT as the REFPROP.XLA. and still no joy.  Has anyone ever seen this.  It almost sounds like a policy some intrusive IT security type in my company has implemented, but that would SEEM stupid.

I have updated the environment variables

### Steps to Reproduce
No steps to reproduce.  It either does it or it doesn't (or I am missing something really subtle)

**Expected behavior:** I expect to be able to see the macro to convert old sheet calls to v10

**Actual behavior:** Changes in code are not saved, not change in being able to see the macro (I can't)

### Versions

**REFPROP Version:** using V10.0]  
**Operating System and Version:** [Windows 10 64 bit]  
**Access Method:** [in Excel, through DLL calls]

**Comment by EricLemmon** [comment]
Can you try uninstalling the program and then reinstalling it some where outside of the Windows "special" places.  Windows has become quite sensitive over the last few years to changes inside of its directories, and this has caused a lot of Excel-Refprop problems.  A few comments about this can be found here:
https://github.com/usnistgov/REFPROP-issues/issues/103

Let me know if this doesn't work and I'll see if I can find a different solution.
