### ISSUE TITLE
Make a code for python (unit 'USER')

### ISSUE THREAD

**Issue by JHulk5623** [usnistgov/REFPROP-wrappers#253]
Hi, I am on the first step of python. 
 
 But I have used refprop for a few years. So, I understand how to use it.

 Question.
 
 How can I use the unit "user" in python code?
 I mean I want to change units what I want to use.
 For example, 
 1) the pressure. kPa
 2) the temperature C, so on.
 
 I knew the code number of each unit according to 'CONSTS.inc'

 Just let me know how to use unit "USER" and easy to change unit in code.

 Thank you very much and please understand my short english.

**Comment by ianhbell** [comment]
Have you read these docs: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll ?

**Comment by JHulk5623** [comment]
Yes, I did. But I couldn't revise unit 'USER' and it didn't work when I use unit 'USER' and checked the unit.

Every reference is using 'Molar SI'. 

As you know I am on a first step on computational language. Please let me know more detail.

 Thank you.

**Comment by ianhbell** [comment]
Can you please show your runnable standalone code for what you tried and what output you received?

**Comment by JHulk5623** [comment]
import os
from win32com.client import Dispatch
import pandas as pd
import numpy as np
import glob

from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])

above code is just copied. It is not big deal to me even if I don't understand.
anyways, Below is main issue.
------------------------------------------------
USER = RP.GETENUMdll(0, "USER").iEnum

p_kPa = 106   # kPa  <- I want to use this unit on 'USER'.
t_C = 25  # <- I want to use this unit on 'USER'.
r = r = RP.REFPROPdll("Water","PT","D",USER,0,0,p_kPa,t_C,[1.0])

**Comment by ianhbell** [comment]
Hopefully @EricLemmon can chime in here on how to do what you want.  From my standpoint, I never ever use anything other MASS_BASE_SI or MOLAR_BASE_SI.  Those are the only two unit systems where everything "just works".  I've made the mistake of using others before, but I have introduced so many unit conversion errors.  Since switching to only base SI units, the number of errors are massively reduced.

I made some edits to clean up the last posting and add code formatting.

**Comment by JHulk5623** [comment]
Thank you for your kindness. I also hope Lemmon can help me again as usual.

**Comment by EricLemmon** [comment]
There are examples of how to do this in the Excel file Refprop.xls. I have copied the code below for you to look at.  I have not yet jumped into the Python programming language, so I cannot help out more than what you see below.  I hope there is enough to show how to do it.

However, I fully agree with Ian's statements.  Mixing units may be convenient now, but eventually you will spend a lot of time trying to figure out why something is not working, only to discover later that it is just a units conversion problem.  It's better to start off with a standard set of units as he discussed.

```
'User-defined units can be selected by entering the unit codes from the CONSTS.INC file in your REFPROP\Fortran directory for T, P, D, H, S, W, KV, VIS, TCX, and STN.
'To set just one (or more), enter zeros for all others.  To activate a new set, exit Excel and restart after making changes.  Because these numbers are just enumerators, they are subject to change between versions.
'Two sets can be set up as shown below with hOut equal to either "UnitUser" or "UnitUser2".
   hIn = "102;162;204;304;353;401;452;502;552;601;751": hOut = "UnitUser"
   Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, 0&, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)
   hIn = "102;151;203;307;354;402;451;501;551;602;752": hOut = "UnitUser2"
   Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, 0&, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)
```

**Comment by ianhbell** [comment]
So @EricLemmon gave a nice demonstration that should get you going hopefully (thanks).  But I stand by my original statement that I cannot recommend the approach of using any unit system other than base SI (either mass or molar).

**Comment by JHulk5623** [comment]
Thank you for all. I will use standard units as you recommended.
