### ISSUE TITLE
Error opening files for LabView wrapper

### ISSUE THREAD

**Issue by aditya-pillai009** [usnistgov/REFPROP-wrappers#254]
Having downloaded the LabView wrapper, I tried opening the 'REFPROP High Level API Tester.Ivproj' and other files like 'ABFLSH_Test.vi' without success. I get the error saying that the ''Project or Library file is corrupt'' and that the ''dynamic library failed to load because of missing external symbols or dependencies''

I could however access the refprop dll and the my fluid file (*.fld) using VIs I obtained from this thread: https://forums.ni.com/t5/LabVIEW/refprop/td-p/272079?profile.language=en 

![Capture3](https://user-images.githubusercontent.com/45597729/75138040-8a8bae00-56e9-11ea-809e-4d528b135e9f.PNG)

Refprop version: 10
OS: Windows 7 Enterprise

Error screens:

![1](https://user-images.githubusercontent.com/45597729/75137600-55cb2700-56e8-11ea-9de7-4205aa8bce61.PNG)
![2](https://user-images.githubusercontent.com/45597729/75137604-5663bd80-56e8-11ea-87ea-1d945223b026.PNG)
![3](https://user-images.githubusercontent.com/45597729/75137605-56fc5400-56e8-11ea-8c07-099337b2bb0f.PNG)
![4](https://user-images.githubusercontent.com/45597729/75137607-56fc5400-56e8-11ea-974d-41710898c163.PNG)

**Comment by ianhbell** [comment]
@damianlauria can you please help this user?

**Comment by dslauria** [comment]
Well based on those errors, it looks like either the REFPROP dll isn't in the expected location or somehow you've got a corrupted project. Have you added the dll to your folder structure per the readme? [https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/Labview/README.md](here)  If you've tried that, I'd suggest re-downloading the wrapper. If those two things don't work, please let me know and I'll keep digging.

**Comment by aditya-pillai009** [comment]
Solved!
I did everything according to the readme the first time but it didn't work.
Then I re-downloaded the wrapper as per your suggestion and everything works as expected.
Thank you!
