### ISSUE TITLE
How to check ABFLSHdll's units?

### ISSUE THREAD

**Issue by JHulk5623** [usnistgov/REFPROP-wrappers#256]
Hi guys, I am reading and doing step by step according to High-level API doc.

Doc says ABFLSHdll function is faster than REFPROPdll. So, I tried to use ABFLSHdll.

subroutineABFLSHdll(ab, a, b, z, iFlag, T, P, D, Dl, Dv, x, y, q, e, h, s, Cv, Cp, w, ierr, herr, ab_length, herr_length)

Based on this function, how can I get the units information of each properties?

For example,
Comp_Name =  "Nitrogen;Methane;Ethane;Propane;Butane;Isobutane;Pentane;Isopentane"    
Comp_Value = [0.1, 0.9, 0, 0, 0, 0, 0, 0]

RP.SETFLUIDSdll("Comp_Name")
r = RP.ABFLSHdll("PT",0.2,110,Comp_Value,0)
print (r)

Q1. The way how to get the units of this function
Q2. iFlag doesn't work when I used '001', '100' like that.

Thank you.

**Comment by EricLemmon** [comment]
Unless you are trying to make thousands of calculations every second or so, then calling ABFLSHdll vs. REFPROPdll will have very little speed impact.  The only difference is the string handling in the latter and a few extra checks to make sure all is setup.  Just stay with the REFPROPdll routine and then you won't get stuck with problems coming from the minor issues of getting all the flags correct, the units you want, and so on.

**Comment by EricLemmon** [comment]
Also, take a look here:  https://github.com/usnistgov/REFPROP-wrappers/issues/143
