### ISSUE TITLE
SyntaxError on import of REFPROPFunctionLibrary

### ISSUE THREAD

**Issue by ChrisChaput** [usnistgov/REFPROP-wrappers#257]
### Prerequisites
Python 3 installation and ctREFPROP Python wrappers.

### Description
When trying to import REFPROPFunctionLibrary, there is a SyntaxError. There is a ":" after a pass statement at line 555. Deleting the ":" fixes the error.

### Steps to Reproduce

1. start python3
2. import the function: 
`from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary`

**Expected behavior:**
I expect it to import without error.

**Actual behavior:**
The import fails because of a SyntaxError:
`
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/exxeno/anaconda3/lib/python3.7/site-packages/ctREFPROP/ctREFPROP.py", line 555
    pass:
`

### Versions

**REFPROP Version:** [0.8.1]  
**Operating System and Version:** [Ubuntu 18.04]  
**Access Method:** [Python]

**Comment by ianhbell** [comment]
Thanks, fixing right now.  Three minutes 😊

**Comment by ianhbell** [comment]
Ok, 7 minutes, but fixed now.
