### ISSUE TITLE
Conversion 9 to 10 - Excel language calls,

### ISSUE THREAD

**Issue by fabienwahl** [usnistgov/REFPROP-wrappers#258]
### Description
There are few excel calls which fall through the conversion procedure, see examples below.
*	Library change prefixes the library name (then lib name disappears after the conversion)
*	If the call is not immediately behind an “=” 
*	(and yes, sub is better than function)

### Steps to Reproduce 

1. Open existing worksheet linked to REFPROP -9
2. launch the RefpropConversion utility to upgrade the worksheet to REFPROP-10

**Expected behavior:** [What you expect to happen]
All REFPOP -9 calls to be updated to REFPROP -10 calls

**Actual behavior:** [What actually happens]
Nothing because
a/ Excel keeps the library name if front of the call, such as 
``=REFPROP.XLA!Temperature``

b/ some calls are not right behind an "=", such as
``=if(test,Temperature(),Temperature())``

### Versions

**REFPROP Version:** REFPROP -10 (download from NIST 27FEB2020)
**Operating System and Version:** Win10
**Access Method:** Excel, using REFPROP.XLA

### Additional Information
Screen shot of issue and proposed script in file attached.

[REFPROP -9 to -10.pdf](https://github.com/usnistgov/REFPROP-issues/files/4269219/REFPROP.-9.to.-10.pdf)

**Comment by EricLemmon** [comment]
This problem has been fixed, along with a few other issues.  Please download the attached text file, then delete the code in your current ConvertRefprop9to10 routine and replace it with the text here.  Let me know if this does not fix everything.
[NewConvertRefprop9to10.txt](https://github.com/usnistgov/REFPROP-wrappers/files/4269345/NewConvertRefprop9to10.txt)

**Comment by fabienwahl** [comment]
Hi Eric,

Yes indeed, does the same
(actually, when skipping the “=”, then no need for REFPROP.XLA! prefix)

Best Regards,

Fabien Wahl, M.Aero.E.
Director Product Development
Nikkiso Cryo Inc.
Cell: +1 702 378 2767
Direct EMail: fabien.wahl@nikkisocryo.com<mailto:fabien.wahl@nikkisocryo.com>

“Everything must be made as simple as possible. But not simpler.”
“Creativity is intelligence having fun.”
― Albert Einstein<https://url.emailprotection.link/?bh19w6CrATMFc4XwIAZ91RdbYBCLlLb8Yp9vilh8EmHXFTrBossHoYmzhNr-MbliholmL2z6Um5vtBVFDwDuxFbhiYiUFYOcXE6jOPzlxD0n8N8d_Ms-8OveBGaniWg94>
“Creativity is a drug I cannot live without.”
― Cecil B. DeMille<https://url.emailprotection.link/?bh19w6CrATMFc4XwIAZ91RdbYBCLlLb8Yp9vilh8EmHXFTrBossHoYmzhNr-MbliholmL2z6Um5vtBVFDwDuxFbhiYiUFYOcXE6jOPzlxD0n8N8d_Ms-8OveBGaniWg94>

**Comment by EricLemmon** [comment]
I'm not sure if you are saying that yes, all is fixed, or that yes, it's not fixed and the same problems appear.  Could you give a few more details?

**Comment by fabienwahl** [comment]
All is fixed, working, no more issues, with the new patch supplied.
Suggestion is now to put this new patch in the downloadable .xla

Best Regards,

Fabien Wahl, M.Aero.E.
Director Product Development
Nikkiso Cryo Inc.
Cell: +1 702 378 2767
Direct EMail: fabien.wahl@nikkisocryo.com<mailto:fabien.wahl@nikkisocryo.com>

“Everything must be made as simple as possible. But not simpler.”
“Creativity is intelligence having fun.”
― Albert Einstein<https://url.emailprotection.link/?bh19w6CrATMFc4XwIAZ91RdbYBCLlLb8Yp9vilh8EmHXFTrBossHoYmzhNr-MbliholmL2z6Um5vtBVFDwDuxFbhiYiUFYOcXE6jOPzlxD0n8N8d_Ms-8OveBGaniWg94>
“Creativity is a drug I cannot live without.”
― Cecil B. DeMille<https://url.emailprotection.link/?bh19w6CrATMFc4XwIAZ91RdbYBCLlLb8Yp9vilh8EmHXFTrBossHoYmzhNr-MbliholmL2z6Um5vtBVFDwDuxFbhiYiUFYOcXE6jOPzlxD0n8N8d_Ms-8OveBGaniWg94>

**Comment by EricLemmon** [comment]
That I definitely will do (when I get back to NIST from travels).

**Comment by EricLemmon** [comment]
The file has now been uploaded and can be found here:

https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Excel
