### ISSUE TITLE
Matlab reports wrong values for viscosity, enthalpy, entropy for Air

### ISSUE THREAD

**Issue by ahmadke** [usnistgov/REFPROP-wrappers#260]
coupled REFPROP and MATLAB through Python wrapper in the was explained in the GTIHUB. The problem is that Python (consequently Matlab) gives is totally wrong number for viscosity, enthalpy, entropy for Air. For example, REFPROP reports 22.208 micro Pa.Sec  at 400 K, 100 KPa but Matlab/Python reports 1.1875 Pa.Sec which is very off.

Could you please help us to figure out this problem?

**Comment by ianhbell** [comment]
Please show the code you ran.  Otherwise it is hard to know what sort of debugging is needed.  You should also always specify either ``AIR.PPF`` or ``AIR.MIX`` (they are not the same thing, and the defaults differ if you write just ``AIR``)

**Comment by ahmadke** [comment]
Bellow is my code. It only reports correct values for Enthalpy and Entropy if air.mix is used but the problem is that before each air.mix call you have to call air.ppf as shown bellow. if you call air.mix at the beginning it gives error.  

clear global;
%
%
T1 = 400;
P1 = 100;
Rho = refpropm('D','T',T1,'P',P1,'air.ppf');
fprintf('Density: %d\n',Rho);
enth = refpropm('H','T',T1,'P',P1,'air.mix');
fprintf('Enthalpy: %d\n',enth);
Mu = refpropm('vis','T',T1,'P',P1,'air.ppf');
fprintf('Viscosity: %d\n',Mu);
ent = refpropm('s','T',T1,'P',P1,'air.mix');
fprintf('Entropy: %d\n',ent);
nue = refpropm('kv','T',T1,'P',P1,'air.ppf');
fprintf('Kin. Viscosity: %d\n',nue);

**Comment by ianhbell** [comment]
Can you try with the new Python interface?  We don't support the legacy interface anymore.

**Comment by ahmadke** [comment]
This is with new Python wrapper

**Comment by ianhbell** [comment]
Well, at least the snippet you show is with the old refpropm interface.  Can you please show your code with the new Python interface?

**Comment by ahmadke** [comment]
As you can see bellow, refpropm is not the one for the legacy matlab. It's a Python wrapper which we made and named it similarly:


% Everything is in MKS. Use kPa, Kelvin, etc. 
% Inputs: Desired output, input 1 letter, input 1 value, input 2 letter,
% input 2 value, medium
function res = refpropm(o_str, i1_str, i1_val, i2_str, i2_val, medium)
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
MOLSI = RP.GETENUMdll(int8(0),'MKS').iEnum;
iMass = int8(0); % 0: molar fractions; 1: mass fractions
iFlag = int8(0); % 0: don't call SATSPLN; 1: call SATSPLN
z = {1.0};

r = double(RP.REFPROPdll(medium,strcat(i1_str, i2_str),o_str,MOLSI,iMass,iFlag,i1_val,i2_val,z).Output);
res = r(1);

end

**Comment by ianhbell** [comment]
I think you need to pass around the RP instance rather than to re-instantiate it in each call.

**Comment by EricLemmon** [comment]
Has this issue been resolved?  If so, can you close it?

**Comment by ahmadke** [comment]
No It has not been solved yet, I use to use refperp with Matlab back in
2014 and never bump into this kind of problem. The new version is not good
at all. It has full of bugs.

—
Ahmad

**Comment by ianhbell** [comment]
Sorry to hear you are having problems with REFPROP 10. Can you please report the issues so that we can fix them?

**Comment by EricLemmon** [comment]
We have not heard back from you, please email us directly if you have further questions and we will work with you individually to solve them.  (eric.lemmon@nist.gov or ian.bell@nist.gov).
