### ISSUE TITLE
How to set Reference State from MatLab?

### ISSUE THREAD

**Issue by Railnolds** [usnistgov/REFPROP-wrappers#264]
Hi.
I have a little problem with my calculations due to difference between Reference state in Matlab and the diagram for ammonia. The ammonia diagram was built for the state IIR (200 kJ/kg of enthalpy for 0 degree). But when I try to get the ammonia properies from Matlab, the enthalpy not the same like in diagram.
I can set IIR state inside the Refprop, but I dont know how to do it in Matlab. By the way, this problem is only for ammonia. For other fluids all is ok.
I use **refpropm** function to get properties, like this.

```
Refrigerant='ammonia';
H3=round (refpropm('H','P',P3,'Q',1,Refrigerant));
```

Maybe somebody know how to change Reference state in Matlab for my situation?

**Comment by ianhbell** [comment]
The ``refpropm`` interface is no longer supported for a host of reasons, among which are limitations like you identify here.

In the new Python-based interface in MATLAB, you can call ``SETREFdll`` to set the reference state to the desired reference state.

**Comment by Railnolds** [comment]
Thank you for your reply.
Could you recommend some literature or manuals about Python-based interface in MATLAB? I have never used it before.

**Comment by ianhbell** [comment]
Please see: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB

And also: https://refprop-docs.readthedocs.io/en/latest/DLL/index.html

**Comment by Railnolds** [comment]
Thank you. I will read your links to understand.
