### ISSUE TITLE
REFPROP for MACOSX Excel 2019

### ISSUE THREAD

**Issue by HCSpin** [usnistgov/REFPROP-wrappers#266]
After following the procedures to generate librefprop.dylib using cmake on OSX,
https://github.com/usnistgov/REFPROP-cmake,

I have followed the procedures outlined for Excel for Office 365 in 
https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Excel,
but 
=REFPROP("DLL#")  yields #VALUE!

Does the code work in Excel for OSX any more?

**Comment by ianhbell** [comment]
Can you please provide more information on what OS/Excel versions you are using, etc.? Without it is hard to know.  Debugging REFPROP+OSX+Excel has proven to be a real nightmare since they are all continually moving targets.

Can you by any chance use Python?  It "just works" in Python.

**Comment by HCSpin** [comment]
OSX 10.15.3
Excel for Mac 16.35 (Excel 2019)

I can use python for some purposes, but I am trying to work with a substantial spreadsheet written by someone else.  I'd like to be able to just use it as is, then perhaps translate later to python.

**Comment by ianhbell** [comment]
In theory it should work (and did at some point). 

* Are you able to add the add-ins and pick them up in Excel?
* Did you properly add the paths? 
* Can you step-debug the call to REFPROP() to see where it dies?

**Comment by HCSpin** [comment]
Yes
Yes
I don't believe this is possible with this version of Excel!

**Comment by ianhbell** [comment]
I think debugging in the VBA is still possible on OSX, at least that is my recollection, but I don't have a working OSX+Excel currently to test in.

**Comment by HCSpin** [comment]
Perhaps a clue.  I've been using CoolProp with python for a while, but am just learning Refprop.  Working through the Jupyter tutorial, https://nbviewer.jupyter.org/github/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb, it says:

# The version of REFPROP (if this gives ***** with REFPROP 10.0.0, please see us to get a patch)
RP.RPVersion()

I do get *****

**Comment by ianhbell** [comment]
Please email me (ian.bell .at. nist.gov) for an updated DLL.  Are you on windows?

**Comment by HCSpin** [comment]
The Excel issue seems to have cleared up by forcing a recalculate of all cells with: Ctrl+Alt+F9.
(Now that I  have done that, I see that key combination referenced lower on the "Welcome" tab. Oh, well.  ) 
Thanks for your help!

**Comment by ianhbell** [comment]
Ah great, good to hear.  Can you please close the issue if your problem has been resolved?
