### ISSUE TITLE
 The results between Python and GUI are different for mixture.

### ISSUE THREAD

**Issue by Yoco233** [usnistgov/REFPROP-wrappers#267]
``` python
import os; os.environ['RPPREFIX'] = r'C:\Program Files (x86)\REFPROP'
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
MOLSI = RP.GETENUMdll(0, "MASS BASE SI").iEnum

#setup the mixture
RP.SETFLUIDSdll('R32*R1234YF')
z=[0.22021116,0.77978884]+[0]*18
RP.SETREFdll('IIR',2,z,-1,-1,-1,-1)

#test1
T=18.638999982122527 #[C]
P=706.7906373925449 #[kPa]

h=RP.REFPROPdll('','TP','H',MOLSI,1,0,T+273.15,P*1e3,z).Output[0]/1000 #[kJ/kg)]
s=RP.REFPROPdll('','TP','S',MOLSI,1,0,T+273.15,P*1e3,z).Output[0]/1000 #[kJ/kg*K^-1]

print('h=',h)
print('s=',s)
print()

#test2
T=60.295486402378856 #[C]
P=1633.4495934813624 #[kPa]

h=RP.REFPROPdll('','TP','H',MOLSI,1,0,T+273.15,P*1e3,z).Output[0]/1000 #[kJ/kg)]
s=RP.REFPROPdll('','TP','S',MOLSI,1,0,T+273.15,P*1e3,z).Output[0]/1000 #[kJ/kg*K^-1]

print('h=',h)
print('s=',s)
print()

#test3
T=32.46376266503023 #[C]
P=1633.4495934813624 #[kPa]

h=RP.REFPROPdll('','TP','H',MOLSI,1,0,T+273.15,P*1e3,z).Output[0]/1000 #[kJ/kg)]
s=RP.REFPROPdll('','TP','S',MOLSI,1,0,T+273.15,P*1e3,z).Output[0]/1000 #[kJ/kg*K^-1]

print('h=',h)
print('s=',s)
print()
```

### Description
I want to define a new mixture. When I try to use the code above by python, the results come out. Then I verify the results with GUI, but they are a bit different. 
The reference are both setup as IIR.
These problems often come out.when I try a mixture fluid? What cause these problem?  And how can I solve them?

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
The output should be the same between python and GUI.
**Actual behavior:** [What actually happens]
The output from python are a little higher then that from GUI.

### Versions

**REFPROP Version: REFPROP10** 
**Operating System and Version: Windows 10 Pro**
**Access Method: Python3.7**

### Additional Information
The result from python:
![Capture1](https://user-images.githubusercontent.com/46733524/77526438-e6ef1280-6ecd-11ea-86f1-c88d20f4914b.PNG)

The result from GUI:
![Capture](https://user-images.githubusercontent.com/46733524/77526492-01c18700-6ece-11ea-998d-ab5970970327.PNG)

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
I cleaned up your code block, see above, but also, this is interesting.  Do you get the same densities in the GUI and Python wrapper? That is the first thing to check, because the reference states are not invoked in the calculation of density, but are invoked in the calculation of entropy and enthalpy.

One possibility, though I think it is unlikely, is that this is a 32-bit/64-bit issue since the python code will call the 64-bit DLL, while the GUI calls the 32-bit DLL.

**Comment by Yoco233** [comment]
Thank you for your reply. It is interesting that the densities in the GUI and python are the same. In this case, what cause the different of the enthalpy and entropy?
![2](https://user-images.githubusercontent.com/46733524/77618776-3b4fcc00-6f7a-11ea-9dfb-4346fda9a99a.PNG)
![1](https://user-images.githubusercontent.com/46733524/77618783-3e4abc80-6f7a-11ea-95fa-a0c2c49b7ec7.PNG)

**Comment by ianhbell** [comment]
Have you played around with the reference state options in the GUI?  Maybe one of them will give you the same values as the DLL?

**Comment by Yoco233** [comment]
I set up IIR in the GUI. And then I get the closest result compared to  the python. I wonder if there are any problems or mistakes about the reference option in my python code.
![3](https://user-images.githubusercontent.com/46733524/77726634-bc22cc80-703b-11ea-9fea-289aa1625114.PNG)

**Comment by Yoco233** [comment]
I find that when I use function: REFPROPdll, if I setup the composition given in mole fraction, the results are the same as GUI when GUI is also use mole fraction. But when I try to use mass fraction, the previous different come out again.

When use the code as follow, the results are same as GUI:
`
D=RP.REFPROPdll('','TP','D',MOLSI,0,0,T+273.15,P*1e3,z).Output[0]
h=RP.REFPROPdll('','TP','H',MOLSI,0,0,T+273.15,P*1e3,z).Output[0]/1000 #[kJ/kg)]
s=RP.REFPROPdll('','TP','S',MOLSI,0,0,T+273.15,P*1e3,z).Output[0]/1000 #[kJ/kg*K^-1]
`

When I try to use mass fraction, the results are different.
`D=RP.REFPROPdll('','TP','D',MOLSI,1,0,T+273.15,P*1e3,z).Output[0]
h=RP.REFPROPdll('','TP','H',MOLSI,1,0,T+273.15,P*1e3,z).Output[0]/1000 #[kJ/kg)]
s=RP.REFPROPdll('','TP','S',MOLSI,1,0,T+273.15,P*1e3,z).Output[0]/1000 #[kJ/kg*K^-1]
`

**Comment by Yoco233** [comment]
Thank you for your help. I have solve the problem. The different of the results are cause by function 'SETREFdll'. Because SETREFdll can only input composition array of mole fraction. So when using the mass fraction it will make problem.

**Comment by ianhbell** [comment]
Yes, you should always use mole fractions, it is what is used internally within the code and the most likely to work properly.  There is a function to convert from mass fractions to mole fractions: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/XMOLEdll which you can call after a call to ``SETFLUIDSdll``, and then leave off the list of fluids in REFPROPdll.  And then use the mole fractions in all the rest of your code.
