### ISSUE TITLE
RIEM for REFPROP

### ISSUE THREAD

**Issue by markgibbons67** [usnistgov/REFPROP-wrappers#269]
Dear NIST

Are you able to advise how the RIEM module can be obtained and plugged into REFPROP (ver 9.1)? I am seeking to calculate and plot curvature R.

Many thanks & regards

Mark Gibbons

**Comment by ianhbell** [comment]
Sorry Mark, I gave you the wrong location for the issue, I moved it over to REFPROP-wrappers

**Comment by ianhbell** [comment]
From what environment do you want to call this function?  The function ``RIEM`` is available in the DLL, exposed as ``RIEMdll``

**Comment by markgibbons67** [comment]
Hi Ian, from Excel - would you be able to provide an example please?

 

Mark

 

  _____

**Comment by ianhbell** [comment]
Ugh...  Calling other DLL functions in Excel is not so much fun. Can you use Python or MATLAB?  It's a one-liner in those environments.

**Comment by ianhbell** [comment]
But if not, we can get it working.

**Comment by markgibbons67** [comment]
I've never used either of those, Ian. What would you suggest (I'm not a
programmer)?

 

  _____

**Comment by markgibbons67** [comment]
Great, please let me know...

 

  _____

**Comment by ianhbell** [comment]
I will ask our resident Excel expert to give you the necessary information: @EricLemmon 

What version of Excel do you use? What operating system?

**Comment by markgibbons67** [comment]
Thanks Ian

 

I have Excel 2003 on Windows 10.

 

  _____

**Comment by ianhbell** [comment]
Hmm, Excel 2003 is really old nowadays, I think though that Eric has something that will still work with Excel 2003

**Comment by markgibbons67** [comment]
I could always push up to Excel 2007 if needed!

 

  _____

**Comment by ianhbell** [comment]
Let's let @EricLemmon see what he thinks.

**Comment by markgibbons67** [comment]
Hi Ian

 

No word from Eric yet. Do you think using pxyll would be a good way to go?

 

Many thanks

 

  _____

**Comment by ianhbell** [comment]
I would just use Python natively.  The Excel interface is crippled compared with the one in Python.

Here's an minimal example for your problem:
```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
r = RP.REFPROPdll('Water','TQ','RIEM',RP.MOLAR_BASE_SI,0,0,300,0,[1.0])
if r.ierr <=0:
    print(r.Output[0])
else:
    print(r.herr)
```
yielding
```
0.0017435799290100875
```

If you want, you could also drop me a line to chat about this quantity itself.  I have some thoughts.

**Comment by markgibbons67** [comment]
Any suggestions where to source Python to start with?

 

  _____

**Comment by ianhbell** [comment]
This (https://www.anaconda.com/distribution/#download-section) comes with all the things you need to get started.

**Comment by markgibbons67** [comment]
This is what I have - doesn't seem right, Ian

 



 

  _____

**Comment by ianhbell** [comment]
Sorry can't see anything, did you intend to attach a screenshot?  If so, please do so in the web interface.

**Comment by markgibbons67** [comment]
Thank you Eric

So if I upgrade to version 10 will you be able to help with calling the RIEM calculation in Excel 2003 or 2007?

Regards 

Mark

**Comment by ianhbell** [comment]
You'll want to copy-paste my script into a text file.  If you use the spyder user interface that comes with Anaconda, you can paste into a new file there and hit F5 to run.  

Otherwsise, at the command prompt, like you did, it would be : ``python name_of_file.py`` where ``name_of_file.py`` is the name of the file you wrote.

Before you can do that, at the command prompt you will need to install the Python interface with ``pip install ctREFPROP``.

**Comment by ianhbell** [comment]
Happy to help you work through the learning curve of Python.

**Comment by EricLemmon** [comment]
Indeed, the information that Ian and I put up here is useful to others as well, and we are always glad to help out.  Many will benefit from your questions and the answers.  Be sure to look at the Refprop.xls file that comes with version 10, the examples there show just about everything that is possible.  And Ian's Python wrappers at this link are a great resource:
https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python

**Comment by markgibbons67** [comment]
I've upgraded to version 10 now but having problems getting the Excel 'Fluid
String' to work.

 

It works OK on a mass basis (=FluidString10(F13:F15,G13:G15,"mass")

 

But what's the format on a molar basis? Is there any significance to the 10
after FluidString?

 

Then I need to bring the RIEM function into Excel to work on my Fluid
String- could you please advise how this is done?

 

Sorry, I don't understand what a 'wrapper' is and how to use it - is it
relevant to what I want to achieve?

 

Thank you

 

 

  _____

**Comment by ianhbell** [comment]
Yes, it is relevant, because the core of REFPROP is a DLL written in Fortran, and any other interface (be it Excel, Python), "wraps" the functionality of REFPROP to make it useful in the environment you use. In that way, there is no fundamental difference between the interfaces in Python and Excel, except that the Python one allows you to do much more powerful analysis, and fiddle with things that are not exposed in the Excel interface.

For REFPROP 10, you wouldn't need to do anything new to get the Riemmanian curvature, please see the sample workbook provided with REFPROP that shows how to obtain parameters from the REFPROP interface in Excel.

**Comment by markgibbons67** [comment]
Please can we go through this step by step?

 

Step 1.

 

If the fluid string for mass is (=FluidString10(F13:F15,G13:G15,"mass")

 

what is the fluid string for moles?

 

  _____

**Comment by ianhbell** [comment]
Have you used the REFPROP 10 wrapper in Excel already?  Please read the examples in the provided worksheet to see how to work with mixtures.

Regarding the Riemannian curvature, I think the jury is out if it is a meaningful quantity for pure fluids, nevermind mixtures.

**Comment by markgibbons67** [comment]
I looked at the worksheet for 2 hours and couldn't see any way to get a
mixture based on moles.

 

If the Riemannian curvature is not meaningful, why did Eric advise me to
upgrade to Refprop version 10? There has been no point to these enquiries if
I cannot get a meaningful Riemannian curvature for mixtures.

 

  _____

**Comment by ianhbell** [comment]
You can leave off the "mass" and put to "" for molar composition (the default in REFPROP).

Here is an example: ``=REFPROP("RIEM","WATER","QT","SI",0,300)`` (to get the same value as above)

Then for a equimolar mixture of nitrogen and argon at one atmosphere;

``=REFPROP("RIEM", "NITROGEN;ARGON|0.5;0.5", "TP", "MOLAR BASE SI", 300, 101325)``

**Comment by markgibbons67** [comment]
Thanks Ian

 

I see what's happening now. REFPROP 10 is giving 2-phase errors where there
were none with 9.1. This occurs when I change the Fluid String from Mass to
Moles- so causing the confusion.

 

This is the message now for various parameters:

 

#[TPFL2 error 226] 2-phase iteration did not converge.

 

The charts in 9.1 represented experimental results better than those in 10 -
ie. the liquid-vapour saturation line, isotherms, etc. agreed with
experimental findings.

 

Regards

  _____

**Comment by ianhbell** [comment]
Can you please provide some examples where 9.1 "represented experimental results better" than in 10?

**Comment by markgibbons67** [comment]
This is a bit tricky, Ian, as it's a formulation I have for a new type of
heat engine cycle. So IP/ confidentiality issues are involved.

 

  _____

**Comment by ianhbell** [comment]
Got it - also watch out that your email responses to the issue from github are publicly viewable.  So be careful on that front.

Can you come up with illustrative systems (not those that you are actually interested in) that demonstrate the problem?

If you are concerned about IP, you can also email Eric and myself privately.  It's not preferred in general, but we understand that it is sometimes necessary.

**Comment by EricLemmon** [comment]
Mark,

Can you send me a personal email (Eric.Lemmon@nist.gov).  Please ignore the out-of-office message that will be sent back to you.)

Eric

**Comment by EricLemmon** [comment]
We have taken this issue offline and will deal with it remotely.
