### ISSUE TITLE
Calculation of solubility

### ISSUE THREAD

**Issue by Benjapepman** [usnistgov/REFPROP-wrappers#270]
REFPROP version 10
MATLAB/Python wrapper

This may be an ignorant question, but is there functionality in REFPROP to evaluate the solubility of a gas in a liquid?

Specifically, I would like to work with a mixture that is comprised of a liquid and gas at standard conditions and evaluate the fraction of gas dissolved in the liquid at a specific state point. I could then use this to evaluate the gasses dissolution behavior when the mixture is cooled through the 2-phase region.

Thanks!

**Comment by ianhbell** [comment]
What is the composition in the bulk ? If you know that you can do a phase equilibrium calculation to get the composition of the other phase.

**Comment by Benjapepman** [comment]
Assume it's a 10/90 composition ratio. I am also curious how the bubble/dew point assumption in REFPROP affects this since it appears to fix the composition in either the liquid or gas phase and in reality they should both be variable.

**Comment by ianhbell** [comment]
10/90 of what? Doesn't need to be precisely the mixture you are looking at, but something relatively analogous.

**Comment by Benjapepman** [comment]
Apologies for the non-specificity. 10%/90% of CO2/Methanol

**Comment by ianhbell** [comment]
Mass or molar?

**Comment by Benjapepman** [comment]
Molar fraction

**Comment by ianhbell** [comment]
Let's suppose you are at 298 K. In that case, if you do a dewpoint calculation with REFPROP to get the composition of the liquid phase, that will tell you what you need to know.  So here's the code for it in python:
```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
iMass = 0 # mass composition output
iFlag = 1 # Call SATSPLN
r = RP.REFPROPdll('CO2*METHANOL','QT','XLIQ',RP.MOLAR_BASE_SI,iMass,iFlag,1,298.15,[0.1,0.9])
print(r.x[0:2])
```
yields
```
array('d', [0.00014144761649603765, 0.999858552383504])
```
where that is your co-existing liquid phase composition (molar)
