### ISSUE TITLE
REFPROP Excel Add-In with Shared Files.

### ISSUE THREAD

**Issue by FloatingSam** [usnistgov/REFPROP-wrappers#271]
### Description

Several of my users are using the REFPROP Excel Add-In for the formulas it offers. We're running into issue with shared files where cells will show “NAME" Because a different user is trying to access the file and it's still pointing to the file path for the add-in of the original user. How do we share files across our company and still use the add-in?

### Steps to Reproduce

1. Upload or create a file in SharePoint (our platform.)
2. Use the REFPROP Excel Add-In to reference a formula.
3. A different user accesses the file on SharePoint. The answer is initially cached but after a very short delay the field updates and the cell will show "NAME" and it references the user folder of whoever initially referenced the formula.

### Versions

**REFPROP Version:** [Product Version 8.0]
**Operating System and Version:** [OS you are running REFPROP on]  
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]

**Comment by EricLemmon** [comment]
Here are a few good sites to look at:

https://pages.nist.gov/REFPROP-docs/#resolving-problems-linking-with-excel
https://github.com/usnistgov/REFPROP-wrappers/issues/121
https://github.com/usnistgov/REFPROP-wrappers/issues/99
https://github.com/usnistgov/REFPROP-wrappers/issues/243

If any of these help, please post what you find so that others can benefit.

**Comment by FloatingSam** [comment]
Objective:
To have a centralized location of where this REFPROP.XLA add in lives so that when users collaborate on the same file that the calculations remain the same.

Steps I've run through with some success:
1. Upload the files to a Networked file path. (\\fs1\public\Excel_AddIns\REPFROP\REFPROP.XLA)
2. Add two registry keys for the user(s) at **HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Excel\Options**
/v "OPEN"
/t REG_SZ
/d "\\fs1\public\Excel_AddIns\REPFROP\REFPROP.XLA"

and

**HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Excel\Add-in Manager**
/v "\\fs1\public\Excel_AddIns\REPFROP\REFPROP.XLA"
/t REG_SZ
Leave /d blank.


So this effectively works the first time that Excel is launched.

The add in is functional and all calculations work. No issues with using it. End user doesn't have to do anything.
However closing Excel and re-opening Excel stops the Add-In from working. It still exists and it shows as "Active" under Excel > Options > Add  Ins

But in order to get it working again for new calculations we have to uncheck the box under Excel > Options > Add Ins.

I've tried adding the PATH System Environment Variable and no difference.

I'm getting close, but not quite there. 
![SaveMe](https://user-images.githubusercontent.com/62899983/79489944-ee877000-7fd0-11ea-9a75-c10eab7b6bfe.PNG)

**Comment by ianhbell** [comment]
Is the file getting locked by a user, and then not unlocked?

**Comment by FloatingSam** [comment]
I'm the only one testing with this right now, so no, it's not possible that anyone else is accessing the file. 

The situation is always the same. When I first deploy the registry keys, the very first attempt at launching Excel proves succesful. 
Add in works, All the formulas are there. It's perfect. Closing the application and relaunching it a second time will always stop it from working. Like in the above screenshot the add in is still "Active" but the ability to do anything like "=density" doesn't show up anymore, the only way to get it working again is to uncheck the box and then to check it again.

**Comment by ianhbell** [comment]
Sometimes windows just doesn't like shared drives, and handles files on them in different ways, are you getting bit by that?

Do you have to use Excel?

**Comment by FloatingSam** [comment]
I have to do more research on windows dealing with shared network drives. Maybe I have to adjust the default permissions for the Add In File. I'll keep looking around for a solution.

If I don't use Excel, what's the alternative? I feel like there ought to be a way to use the REFPROP Add In and still collaborate with multiple users on the same document.

**Comment by ianhbell** [comment]
You could use Python for your analysis, and then you would get versioning, environments, etc.  Bit of a learning curve, but not too steps, tons of resources online, etc..

**Comment by EricLemmon** [comment]
Has this issue been resolved?  If not, would you like me to log into your machine and work with you to solve it?  If so, please email me at eric.lemmon@nist.gov

**Comment by FloatingSam** [comment]
No it hasn't been resolved. Still at the same dead-end. I'm only ever able to get the app working for the first time after deploying the registry changes. Every subsequent attempt to launch Excel renders the add-in not functional until the "Add In box" (under Excel > Options > Add Ins) is checked again. 
I'll email you separately.

**Comment by FloatingSam** [comment]
This is resolved. 

Follow these steps to resolve.
1. Upload the REFPROP files to a Networked file path. (\\fileserver\Excel_AddIns\REPFROP\REFPROP.XLA)
2. Add two registry keys for the user(s) at **HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Excel\Options**
/v "OPEN"
/t REG_SZ
/d "\\fileserver\Excel_AddIns\REPFROP\REFPROP.XLA"

and

**HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Excel\Add-in Manager**
/v "\\fileserver\Excel_AddIns\REPFROP\REFPROP.XLA"
/t REG_SZ
Leave /d blank.


In my environment we're deploying a script remotely to add the above registry keys to the computers. The initial problems I ran into of where the registry changes only worked the first time of laucning Excel were fixed by re-uploading the REFPROP files to the networked location. 

We also have a service called Hubstor that we use to dedupe and back up the location. There is a likelihood that there may have been some interference with the service. Between my last attempt of getting the registry values to work and now the service was updated.

**Comment by EricLemmon** [comment]
Thanks for this information!  I've added the label "documentation" so that this is easier for people to find.  I use that label whenever the material contains a lot of detail on a subject or is something new and quite useful to others.  This way someone can do a search for all issues labeled as such for reading (when bored!) to get a better overview of the program.

Again, thanks!
