### ISSUE TITLE
Unit of inputs in ABFLSHdll() is always mole based

### ISSUE THREAD

**Issue by djs97** [usnistgov/REFPROP-wrappers#272]
Hallo, 

I try to use ABFLSHdll() to calculate some fluid properties. According to the REFPROP dll documentation, the units of input can be change by setting the iFlags. (see screenshot below)

![image](https://user-images.githubusercontent.com/56409735/78033900-500bd580-7367-11ea-9ad7-5c7baaff9abf.png)

Under my understanding, that means: 
iFlags = 001 ------> all input and output is mass based, e.g. S is in [kJ/(kg*K)]
iFlags = 000 ------> all input and output is mass based, e.g. S is in [J/(mol*K)]

However, the result does not match my expectation.(see below)

1. setup

``` python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
rp = REFPROPFunctionLibrary(os.environ['RPPREFIX'] + '\REFPROP.dll')
rp.SETPATHdll((os.environ['RPPREFIX']))
rp.SETFLUIDSdll('R32')
```

2. calculation using ABFLSHdll()
I intended to use mass based inputs.

```
result = rp.ABFLSHdll('TP' ,283.15 , 813.1, [1], 1) # mass based unit
print(result.s)
```
yields
```
2.196888937620143
```
I intended to reproduce this state.
```
result = rp.ABFLSHdll('TS' ,283.15 , 2.1969, [1], 1)
print(result.P)
print(result.s)
```
yields
```
2704994.971661029
0.04222837521851921
```
They don't match the state in In[1].

3. comparision
Now I calculate the entropy in mole based unit.
```
result = rp.ABFLSHdll('TP' ,283.15 , 813.1, [1], 0) # mole based unit
print(result.s)
```
yields
```
114.29095009075031
```
Use this mole based entropy as input in In[2].
```
result = rp.ABFLSHdll('TS' ,283.15 , 114.29095009075031, [1], 1)
result.P
result.s
```
yields
```
P = 813.0999768033532
s = 2.196888944267275
```
Now they match the state in In[1].

Similar problems also occur with internal energy 'E' and enthalpy 'H '. It shows that, iFlags may not be able to set the units of inputs properly. Or if I made some mistakes when setting the iFlags?
Thank you for your patient!

### Versions

REFPROP Version: 10.0.0.02
Operating System and Version: windows 10
Access Method: Python 3.7 32-bit

**Comment by ianhbell** [comment]
I tried to clean up the formatting of your issue a little bit.  Hopefully @EricLemmon can explain what is going on here.

**Comment by EricLemmon** [comment]
This is a bug that was first brought up here:

https://github.com/usnistgov/REFPROP-wrappers/issues/143

Please let us know if you want the updated DLL (eric.lemmon@nist.gov or ian.bell@nist.gov)

**Comment by djs97** [comment]
Ok! Thanks a lot.
