### ISSUE TITLE
REFPROPdll wrapper returning an error but REFPROP returns a result for Z

### ISSUE THREAD

**Issue by monstrorivas** [usnistgov/REFPROP-wrappers#273]
This is a continuation of the conversation in https://github.com/CoolProp/CoolProp/issues/1887 but specific to ctREFPROP

I tried the code below

```
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
mixture = 'REFPROP::hydrogen[0.0873168583740243]&methane[0.330988014885575]&ethylene [0.0159890480666283]&ethane[0.137210032670966]&propane[0.088069682553442]&propylene[0.0397985569518283]&isobutane[0.0101718560899523]&butane[0.0239397277407483]&butene[0.00716078027576751]&isobutene[0.00616795718009513]&trans-Butene[0.00293146448233885]&cis-Butene[0.00189185726296182]&isopentane[6.88999845679751E-4]&neopentane[0.020447972570614]&Carbon monoxide[0.00329884102709941]&hydrogen sulfide [0.178986084981603]&nitrogen[2.8465742647463E-132]&water[0.0251806534609712]&hexane[0.0197616115797051]'
components = mixture.split("::")[1].split('&')
fractions = [float(x[x.find('[')+1: x.find(']')]) for x in components]
names = [x[: x.find('[')] for x in components]
hFld = ";".join(names)
hIn = "TP"
MASS_BASE_SI = RP.GETENUMdll(0, "MASS BASE SI").iEnum
r = RP.REFPROPdll(hFld, hIn, "Z", MASS_BASE_SI, 0, 0, 305.57192585999996, 203080.3622, fractions)
```

but I still get the following error
 `herr='[TPFL2 error 213] Density iteration did not converge.'`

where REFPROP GUI returns a valid value

I'm using `ctREFPROP==0.8.2`

**Comment by ianhbell** [comment]
Firstly, I would use the low-level interface of CoolProp, which has a much more natural mapping with that of the native-Python wrapper of REFPROP.

In both cases, I could recommend to either in the case of the Python wrapper enable the calculation of saturation splines with iFlag, and in the case of the low-level interface of CoolProp, force the calculation of the phase envelope with build_phase_envelope (can't be done in high-level interface of CoolProp).

**Comment by monstrorivas** [comment]
My bad, I forgot to activate the SATSPLN function. You are right, once I pass iFlag=1 it solves correctly.

So, for completeness. This works:
```r = RP.REFPROPdll(hFld, hIn, "Z", MASS_BASE_SI, 0, 0, 305.57192585999996, 203080.3622, fractions)
r.Output[0]
0.989705

Do you have a sense of what has better performance, low-level interface of CoolProp or REFPROPdll (ctREFPROP)? Does the more natural mapping with native-Python wrapper of REFPROP help with performance?

**Comment by ianhbell** [comment]
I would guess that performance-wise, they should be close to identical, but it depends on how you handle things.  Overall I think I would recommend ctREFPROP interface, unless you need other things from CoolProp, like humid air or incompressible fluids, that are not in REFPROP.

If you pass the names of fluids only on the first time to REFPROPdll, that will speed things up, since subsequent calls will skip evaluation of SETUP.  You can also look into ABFLSHdll and SETFLUIDSdll, which can further speed things up because they skip string evaluations.  But if you are looking at multi-component mixtures, it doesn't matter because those flash calculations are certainly the pinch point in terms of computational speed, so everything else is irreelevant (I think).

As usual, test for your particular problem!

**Comment by monstrorivas** [comment]
Thanks for the info. The use case I'm looking at is for multi-component mixture with changing compositions (molar fractions) over time. Is there a way to load the components first by name (not by component file). 

That is, if I have a string of components (or a list or array) with just the names:
```'hydrogen;methane;ethylene ;ethane;propane;propylene;isobutane;butane;butene;isobutene;trans-Butene;cis-Butene;isopentane;neopentane;Carbon monoxide;hydrogen sulfide ;nitrogen;water;hexane'
```
can I load those components to the RP object first without issuing REFPROPdll? I saw an example of SETMIXTUREdll but it looks at a pre-defined mixture

**Comment by ianhbell** [comment]
What you describe is precisely the use case for ``SETFLUIDSdll`` :)

**Comment by monstrorivas** [comment]
ahh... I see. I thought SETFLUIDSdll was only for individual components. I got it now. Ok, Thanks!! I guess we can close this issue since it turned out to be not an issue in ctREFPROP :)
Thanks again!

**Comment by ianhbell** [comment]
My pleasure! Go ahead and close the issue.
