### ISSUE TITLE
Excel wrapper problem with office365

### ISSUE THREAD

**Issue by Lokanath13** [usnistgov/REFPROP-wrappers#274]
I am trying to use Excel wrapper for Refprop. It used to work for me as an addin with Office 2013. Recently, my computer was upgraded to office 365 and it stopped working. 

I have followed the following set of instructions 
https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Excel

I was also trying to resolve following the steps here 
(https://github.com/usnistgov/REFPROP-docs/blob/nist-pages/index.md#resolving-problems-linking-with-excel)

1. Refprop.xls does not give me any values it returns #NAME 
2. I don't have RPprefix in the environment variable
3. I have one refprop.dll in another location apart from main installion directory. But I must have that for an internal tool

**Comment by EricLemmon** [comment]
Can you email me directly?  This is situation where I may need to log into your machine to try to find the problem.  I'm at eric.lemmon@nist.gov

**Comment by EricLemmon** [comment]
We were able to fix this problem yesterday.  Moving the Refprop directory outside of the Program files directory and into his Users directory solved the problems because he is now able to save the XLA and other files in that directory without administrative rights.

**Comment by Lokanath13** [comment]
Thank you Eric. Appreciate your help
