### ISSUE TITLE
Inquiry regarding refprop under matlab

### ISSUE THREAD

**Issue by taqy25100** [usnistgov/REFPROP-wrappers#277]
Currently, I'm working on modelling of organic rankine cycles (ORC) using Matlab, and I'm using Refprop function in **matlab** to generate the thermo-physical properties (such as enthalpy and entropy) of different organic fluids such as pentane, R134a,....etc. While I didn't face any issue to generate these properties under the **saturated phase** according to the defined command "example of R134a enthalpy, h=refpropm('H','T',...,'P',...,'R134a')", I couldn't find the command to call these properties in the **"compressed liquid**" and "**superheated**" regions at defined pressure and temperature.
Thanks in advance.

**Comment by ianhbell** [comment]
The refpropm interface is no longer supported. Please transition to the Python-based one. 

Please see the docs: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB#refprop-for-matlab .  There are some linked examples, some even showing what you ask about.

**Comment by blaubacher** [comment]
Hi Ian,  I used a script written last year that used refprop.m to find Z data for various gases z(P,T).  I would like to use the z values for refprop 10.  Is it not possible to simply replace the fluid files from 9.1 to 10 and rerun the script to obtain updated Z(P,T) tables? 
what about writing a fortran double loop that uses refprop.dll to obtain z surfaces?  Lastly, I'll try to learn the python wrapper approach, it.s just I'm not famililar with Python.  Thanks Brian

**Comment by ianhbell** [comment]
In theory, yes. In practice, maybe. You can make a double-loop in MATLAB to do the same thing. You don't need to learn Python to use the wrapper, just how to call the functions.  Otherwise you can live in MATLAB-land.  

Or you could use the high-level interface of CoolProp: http://www.coolprop.org/coolprop/wrappers/MATLAB/index.html#matlab.  It supports vectorized inputs.

**Comment by blaubacher** [comment]
thanks much Ian, I'll try to re-use the matlab scripts since they're already written.  I'll explore the new calls that I have to incorporate..  take care
Brian

**Comment by Fanch84103** [comment]
Hello Ian, I'm working with "blaubacher" on the same topic (ie building Z(P,T) for several pure gases). I want to try CoolProp thru SCILAB and call RefProp. I have no idea how to start. I still need to read the CoolProp website. My first question is "how to install CoolProp?"
François

**Comment by ianhbell** [comment]
A good place to start answering this question is on the CoolProp website :) By the way, there are no native wrappers for scilab.  I wrote some, but I couldn't keep them maintained, so you have to call Python from scilab (or just use Python directly).
