### ISSUE TITLE
Error in calling Air Properties in Excel

### ISSUE THREAD

**Issue by jafarialireza** [usnistgov/REFPROP-wrappers#278]
Dear Sir,
I appreciate your help in advance. I faced an issue as shown in attached picture.
Best
Ali

![REFPROP Eror](https://user-images.githubusercontent.com/52477944/80065749-36783b00-856d-11ea-972a-b2e4e5304934.jpg)

**Comment by ianhbell** [comment]
It is true that the cp cannot be defined if the mixture is two-phase, but your temperature is WAY above the critical temperature, which is estimated to be:

![image](https://user-images.githubusercontent.com/11966765/80100626-3280f480-853e-11ea-9941-426e3aa725f5.png)

**Comment by jafarialireza** [comment]
The fluid is Air, which is usually in supercritical condition. I didn't call the air properties in two phase state. I need to get Cp value in specified state points by excel file using "TP". If you check the REFPROP software (as shown in picture) the Cp value is 1.0930 kJ/kg-k, but there is an issue in excel and VB.net.

**Comment by ianhbell** [comment]
This is a bug.  I confirm on my side: 
```
=refprop("cp","Air.mix","TP","molar SI", 278.15, 5)
```
yields the same error too, but other kinds of outputs are fine.  

Same issue in Python, so bug is in REFPROP core:
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'D:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
r = RP.REFPROPdll('Air.mix','TP','Qmass;Cp', RP.MOLAR_BASE_SI, 0, 0, 278.15, 5e6,[])
print(r.Output[0], r.herr)
```
yields (quality, and error code, clearly an impossible case of 0 < Q < 1 since we are at temperature multiple times the critical temperature)
```
2.5143293981043495e-08 [REFPROP warning -810] One or more of the input properties is not thermophysically defined for two-phase states and cannot be calculated.
```

**Comment by jafarialireza** [comment]
Dear Ian,
When do you think this issue can be solved?

**Comment by EricLemmon** [comment]
I've been looking into this and some things that seem simple are not always so.  Any fix that I add has the potential to break other working applications, so it is something that needs to be done very carefully.  In the meantime, I would suggest the use of ">" or "<" as explained here:

https://pages.nist.gov/REFPROP-docs/#convergence-failures-and-forcing-phase-calculations

**Comment by jafarialireza** [comment]
Dear Eric,
Thanks for your guidance.

**Comment by EricLemmon** [comment]
I've found a way to check enough variables to hopefully ensure that a state identified as two phase is in reality single phase.  Your problem here now calculates correctly.  If you would like an updated DLL, please email me (eric.lemmon@nist.gov).  There is still the chance that this affects other calculations, but we will run all of our tests to make sure they all pass.

Another option would be to set iFlag=1 in the XLA code.  See #106.
