### ISSUE TITLE
Discrepancy between GUI and Dll fluid properties

### ISSUE THREAD

**Issue by Statworthy** [usnistgov/REFPROP-wrappers#280]
Hello Ian, 

I was trying to calculate Density, Specific heat, Enthalpy and Viscosity of Propane at 100F and 14.7 psia: The GUI values and Dll python code values are significantly different. Not sure as to why this is the case. Please help with this issue. Thank you.

My code is in the below file (please refer to the array output and compare that to the GUI.

![REFPROP DLL code](https://user-images.githubusercontent.com/15170144/80286952-2ff3ea00-874c-11ea-9d5c-c2233ed90665.JPG)

GUI result is in the below file:
![REFPROP GUI](https://user-images.githubusercontent.com/15170144/80287013-9842cb80-874c-11ea-939f-cb60f1c8b532.JPG)

None of the values match. My REFPROP version is 10.0 and I understand that there is a patch for it. Not sure if this is why I am getting drastically different values.

**Comment by ianhbell** [comment]
The GUI and the DLL use different reference states by default, but it is not a good sign that the densities differ, because that has no reference state dependence.

Can you please try in SI units?  IP units invoke unit conversions internally and I'd like to see if that is the culprit.

**Comment by ianhbell** [comment]
Nice description of the problem by the way!

**Comment by Statworthy** [comment]
Hello Ian, 

     Thank you for the quick feedback and positive comment. I ran this in Mass base SI and the discrepancy still exists.
See code below and the GUI file below that:
![REFPROP DLL code-SI](https://user-images.githubusercontent.com/15170144/80287770-da6e0c00-8750-11ea-8a65-bb9f284979d3.JPG)
GUI image:
![REFPROP GUI-SI](https://user-images.githubusercontent.com/15170144/80287786-e8239180-8750-11ea-935a-cd2a54e717be.JPG)

Let me know what you think. Thank you.

**Comment by Statworthy** [comment]
Ian, I believe only the Viscosity value is matching perfectly. The rest are far apart. Thanks.

**Comment by Statworthy** [comment]
Ian, I think the iMass flag in the dll code is not working. Even if I change that from 0 to 1 or 2, I get the same result. Therefore the values are possibly coming out in molar basis rather than on mass basis. There is also some inconsistency with the units in general that is causing this problem I believe. Let me know if you find the issue. I will look into this further in a few hours. Thank you again.

**Comment by ianhbell** [comment]
Are your PT inputs saturated?  If so, one might have given the liquid solution, the other, the gas solution.

**Comment by ianhbell** [comment]
That's not what iMass is about; iMass deals with compositions.  Mass and molar properties are determined based on the unit system selected.

**Comment by ianhbell** [comment]
``MASS_BASE_SI`` uses Pa as the pressure unit, I think that is the problem here

**Comment by Statworthy** [comment]
Hello Ian, 

    Now with pressure units being in Pa, the values are even more different. See below:
![image](https://user-images.githubusercontent.com/15170144/80295219-9c8fd880-878e-11ea-858d-4a13d95f2b87.png)
These are not saturation inputs. I did check carefully. 

If the change the properties to molar units, the results are closer when the pressure units were in MPa and not in Pa in the dll code:
![image](https://user-images.githubusercontent.com/15170144/80295405-0492ee80-8790-11ea-9fd1-b6e081e60c83.png)

The dll code with the pressure units in MPa:
![image](https://user-images.githubusercontent.com/15170144/80295513-cf3ad080-8790-11ea-9c7b-1b109ee5bd80.png)
The enthalpy values are still off; but, they are heading in the right direction, and the density values are three decimals apart from the GUI. The CP and VIS values are pretty close. 

Therefore, I feel that there is a bug on how the units are interpreted using the Dll code. Maybe it has to do with my version of REFPROP which is 10.0. I am not sure.

**Comment by Statworthy** [comment]
Hello Ian, 

    I now converted everything to Molar base SI units in the Dll code and used Pa as pressure units. The results are similar to the Dll results above with some decimals being off for density and viscosity:
![image](https://user-images.githubusercontent.com/15170144/80296052-905b4980-8795-11ea-9f75-e3b2ce14c458.png)

Thought this info might be helpful as well. 

Regards
Satya

**Comment by ianhbell** [comment]
Bugs filed:
https://github.com/usnistgov/REFPROP-issues/issues/287
https://github.com/usnistgov/REFPROP-issues/issues/288

**Comment by ianhbell** [comment]
When you are testing like this, it is best to start from a clean Jupyter kernel.  REFPROP keeps a lot of things around in memory, so it can be hard to debug unless you start from scratch.  My bugs I filed are examples of what I mean.  

Also, scripts are much easier to work with on our side than screenshots of Jupyter notebooks, but I get why that is convenient.

**Comment by Statworthy** [comment]
Thanks Ian, I will keep that in mind. When do you think this issue can be fixed?

**Comment by ianhbell** [comment]
Not sure, I'll forward to Eric Lemmon to look into

**Comment by EricLemmon** [comment]
Have you tried the 10.0.0.77 beta yet?  If not, can you send Ian or me a personal email to get the link to the patch?  (Ian.Bell@nist.gov or Eric.Lemmon@nist.gov)

**Comment by Statworthy** [comment]
Sure, will do. Thank you Ian and Eric.

**Comment by Statworthy** [comment]
Hello Ian,

        Ok, I will try. Eric created an alpha version that I will try as
well. Thank you!
Regards
Satya.

**Comment by EricLemmon** [comment]
Did the alpha version resolve the issue?  If so, could you close this?

**Comment by Statworthy** [comment]
Eric,

   Sorry, I haven't tried the alpha version yet. I started interfacing with
Refprop using Excel, so trying that out currently. However, I prefer to
interact with Refprop directly; therefore, I will try out the alpha version
and will close the case if it the data coming out of it is correct.

Give me a few days. I don't want to change my excel tool that I am
building.

Regards
Satya

**Comment by Statworthy** [comment]
Eric, I installed the alpha version and it is yielding much better results. 
For instance, this is a Methane/Ethane mix and each property value that I get is spot on except "H" which is the enthalpy. That property is off by about 50 both at 60C and at 80C. 
hFld='Methane;Ethane|0.8;0.2'
r_me= RP.REFPROPdll(hFld, "PT", "D;H;CP;TCX;VIS", SI_WITH_C, 0, 0, 5.101325, 60, z)
print(r_me.Output[0:5], "::::::")

r_me= RP.REFPROPdll(hFld, "PT", "D;H;CP;TCX;VIS", SI_WITH_C, 0, 0, 5.101325, 80, z)
print(r_me.Output[0:5], "::::::")

![image](https://user-images.githubusercontent.com/15170144/85261889-86e71880-b48a-11ea-8d9f-dd14b6f7dd55.png)



![image](https://user-images.githubusercontent.com/15170144/85261805-5ef7b500-b48a-11ea-92ad-9bf08f8c4dea.png)

Not sure why this is the case. Enthalpy is a key property, so we should be able to get the right answers, or at least there should be a consistency between the GUI and python wrapper code values. Way better results though! 

Regards
Satya

**Comment by ianhbell** [comment]
Default reference states differ between the GUI and the DLL for historical reason that I won't get into here.  Changing the GUI to this reference state yields the same values:

![image](https://user-images.githubusercontent.com/11966765/85292561-16c89a80-b46a-11ea-9bed-c8a548cb38c2.png)

**Comment by Statworthy** [comment]
Ian,

  Ok, Thanks. Here are my comments:

1) My version is 10.0.0.80 (alpha version) and even when I pick the option
you picked for reference state, I get the same Enthalpy values as before.

2) Why would Enthalpy and Entropy be zero at NBP? Thermodynamically, fluid
behavior during phase change would indicate that these two values would be
much much higher. Enthalpy will be zero at absolute zero (-273.15C or 0
Kelvin) if I am not mistaken. I don’t see this option in my Refprop version.

3) What value does Refprop assume for Enthalpy at the default reference
state?

I appreciate your support. I just want to make sure that I am getting the
correct values.

Regards
Satya

**Comment by ianhbell** [comment]
1) Did you also change the option in the bottom right corner for whether it applies to each component or to the mixture?

2) Reference states have no physical significance at all.  They are mathematical conveniences, the right reference state is absolute zero, which gives very enormous values which nobody wants to work with, which is why we pick reference states closer to our desired region of operation

3) It depends on the reference state, they are shown in the screenshot in my last post in this thread.

**Comment by Statworthy** [comment]
Ian, Thanks for the additional clarification. I am getting the values you
showed. Mine was set for the current mixture rather than for each
component. With regards to reference states, I am glad that this is mainly
set for mathematical convenience purposes. I suppose we can close this
issue.

Regards
Satya

**Comment by ianhbell** [comment]
My pleasure. Glad that helped.
