### ISSUE TITLE
REFPROP FILE version 10.0 to 9.1 (or 8.0) 

### ISSUE THREAD

**Issue by Salim-byl** [usnistgov/REFPROP-wrappers#281]
Hi,

We have difficulties to use the REFPROP version 10.0 file with simulation software.
It seems that we need older version (REFPROP 9.1 or 8.0) of the files.

Do you think I can create it from a version 10.0 file ?
Is there a version converter ?
Do you know what are the differences ?

Best regards,

**Comment by ianhbell** [comment]
What problems are you having?  REFPROP 10 is not backwards compatible with versions 8 or 9, but most of the old interface was retained for historical reasons.

**Comment by Salim-byl** [comment]
Hi,

I'm not talking about Refprop or the macro excel.
I'm talking about importing .FLD fluid files into simulation software (GT-SUITE) which only uses versions 8.0 and 9.1.
The solution for me is to convert the version 10 fluids files to version 9.1 or 8.0 so that the software can read them

Do you think you can help me?

Best regards,

Salim  AOUALI
Stagiaire, Trainee
[cid:4ee95e7c-78a3-4623-b22b-25eb8b5a3989]

Rankine Technology

M :  +33 7 53 09 96 83
Tel :  +33 9 72 50 30 86

www.exoes.com<http://www.exoes.com/>

________________________________

*This electronic message contains information from EXOES SAS, which may be privileged and confidential. The information is intended to be used by the individual(s) or entity named above only. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of the content of this information is prohibited. In this case, kindly notify us by telephone or e-mail immediately and delete this message from your system permanently.

________________________________
De : Ian Bell <notifications@github.com>
Envoyé : mardi 28 avril 2020 16:16
À : usnistgov/REFPROP-wrappers <REFPROP-wrappers@noreply.github.com>
Cc : Salim Aouali <salim.aouali@exoes.com>; Author <author@noreply.github.com>
Objet : Re: [usnistgov/REFPROP-wrappers] REFPROP FILE version 10.0 to 9.1 (or 8.0) (#281)


What problems are you having? REFPROP 10 is not backwards compatible with versions 8 or 9, but most of the old interface was retained for historical reasons.

**Comment by ianhbell** [comment]
Sorry, somehow I deleted your comment, but I replaced it here:

I'm not talking about Refprop or the macro excel.
I'm talking about importing .FLD fluid files into simulation software (GT-SUITE) which only uses versions 8.0 and 9.1.
The solution for me is to convert the version 10 fluids files to version 9.1 or 8.0 so that the software can read them

Do you think you can help me?

**Comment by Salim-byl** [comment]
I'm not talking about Refprop or the macro excel.
I'm talking about importing .FLD fluid files into simulation software which only uses versions 8.0 and 9.1.
The solution for me is to convert the version 10 fluids files to version 9.1 or 8.0 so that the software can read them.

**Comment by ianhbell** [comment]
(Sorry I think I might have accidentally deleted your comment)...

Ah then you need to 
a) Get your simulation tool to support our REFPROP 10 fluid files
b) Manually convert them, as you are doing.

**Comment by Salim-byl** [comment]
Ok I see.
My question is How can I convert them manually ?

**Comment by ianhbell** [comment]
You have to take the fluid files, and figure out the format of the old fluid files, and convert them (or better, use a script) to put them into the old format.  We don't have any tools developed for this task.  Better would be to get you simulator to fix their code :)

**Comment by Salim-byl** [comment]
Thank you,
I will try this solution.
