### ISSUE TITLE
Doubts with REFPROP and CoolProp

### ISSUE THREAD

**Issue by 28tanuj** [usnistgov/REFPROP-wrappers#282]
Hello there,
I want to calculate properties of Supercritical Carbon dioxide in codeblock c++ using REFPROP and CoolProp. I basically need a small code for this purpose, as I am new to this environment and have less knowledge about the files needed for this purpose. I have a few issues, which will clear my basic doubt and will help me as well as to those who have a weak background in these environments in the future and those are following-
1) Do I need a static or dynamic library? (I guess static as mentioned in [here](https://github.com/CoolProp/CoolProp/issues/853)) . That's not a big issue though.

2) I want to have a simple one-line command in code something like -
 std::cout << PropsSI("Dmolar","T",298,"P",1e5,"REFPROP::Propane[0.5]&Ethane[0.5]") << std::endl;
which I took from this [link](http://www.coolprop.org/coolprop/HighLevelAPI.html#c-sample-code).

Here in this example, they have not used REFPROP library, but they have used "REFPROP" (as you can see in the command that I pasted above). So REFPROP library is essential or not (though I have download that as well). SImilar thing I also found [here](http://www.coolprop.org/v4/examples/C++/example.html).

3) Do I need the files as mentioned [here](https://github.com/ibell/coolprop) and [here](https://github.com/CoolProp/CoolProp)? If yes then are they location-specific inside my computer?

4) What are the other files needed to get this code run? I have seen the requisites from [here](http://www.coolprop.org/coolprop/wrappers/index.html#windows). Though they have mentioned [here](http://www.coolprop.org/coolprop/wrappers/index.html#windows). Are CMake, 7z, and git mandatory?

5) I have seen in code that they have used "PropSI", is it a separate library or included inside coolprop library? 

It would be very helpful if you clear these doubts of mine and these will help me in building my small code. Thanks in advance.

Regards,
Tanuj

**Comment by ianhbell** [comment]
If you just want to call REFPROP from C++, make sure you have purchased a copy from NIST SRD. If you confirm this, then I can explain how to call REFPROP from C++ in general.

If your question is about using CoolProp, please open the issue there.
