### ISSUE TITLE
MATLAB equation solver (fsolve) error with REFPROP call

### ISSUE THREAD

**Issue by mpm268** [usnistgov/REFPROP-wrappers#284]
### Description

I am looking to use MATLAB's "fsolve" in order to solve a system of non-linear equations, in which some equations contain REFPROP calls. However, I am getting the following error, which seems to be a problem with how MATLAB using the “fsolve” function (using symbolic variables): 
_Error using cell2mat (line 52)_
_CELL2MAT does not support cell arrays containing cell arrays or objects._

_Error in refpropm (line 295)_
_propVal1 = cell2mat(varargin(3));_

Has anyone found a way around this? I have included sample code below that produces the error, as well as a screen shot of the error.

### Code
Sample code (eventually will have a larger system of equations):
``` matlab
%% eqn solver
syms Tout
eqn = 1/refpropm('D','T',Tout,'P',101,'air.ppf') - 2000;

sol = fsolve(eqn)
```

### Versions

**REFPROP Version:** 9.1  
**Operating System and Version:** Windows 10
**Access Method:** MATLAB, refpropm.m

**Comment by ianhbell** [comment]
Two comments:

1) You need to upgrade to the Python-based interface, the refpropm one is deprecated.
2) Unfortunately, this will never work; REFPROP operates on floating point values only.  If you want the temperature at the given density and pressure, then you can provide the density and pressure and get the temperature as output.

**Comment by mpm268** [comment]
Thank you for the quick response. I am doing heat transfer design and have to solve multiple non-linear equations, all of which are either temperature dependent and/or will impact the temperature. So, I don't think your second comment applies because I really need to solve for temperatures and/or pressures. However, it sounds like I need to move past MATLAB. 

Regarding your first comment, I don't know Python; do you have any comment on possibly using EES (http://fchartsoftware.com/ees/) for this application?

**Comment by ianhbell** [comment]
From MATLAB: Python is only used for the interface to the DLL of REFPROP, you can still live in MATLAB. EES is also possible, but does not generally implement the most accurate thermophysical property models.

Personally, I have been using Python + REFPROP to do things like you mention for more than a decade (e.g., https://github.com/CenterHighPerformanceBuildingsPurdue/ACHP). That way _you_ are in control, and have some chance to debug what is going on.

**Comment by mpm268** [comment]
I see! Sounds like that could work well. 

Can you point me to any instructions on how to use Python as the interface to the DLL of REFPROP? Any sample codes, instructions on setup, etc. would be VERY appreciated. Thanks again!

**Comment by ianhbell** [comment]
Please see https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python
