### ISSUE TITLE
Using REFPROP in node.js application

### ISSUE THREAD

**Issue by tonywilliams1990** [usnistgov/REFPROP-wrappers#285]
What is the best way to integrate REFPROP into a node.js application?

**Comment by ianhbell** [comment]
Not sure, but it isn't too bad to integrate into C++, and I gather C++ and node.js are close cousins.  If you can call Python directly from node.js, that would be your best bet.

**Comment by tonywilliams1990** [comment]
Is there a way of directly calling the dll using javascript?

**Comment by ianhbell** [comment]
No, I shouldn't think so.  At least not in native javascript (node.js is something quite different).  Pretty different architectures.  I'd start with C++, make sure you understand what is going on there, then try with node.js

**Comment by EricLemmon** [comment]
Can this issue be closed?
