### ISSUE TITLE
GETENUMdll could not be loaded from the shared library

### ISSUE THREAD

**Issue by mpm268** [usnistgov/REFPROP-wrappers#286]
### Description
I got all the way to the 'first practical example' in https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB instructions. However, when I run the code referenced, I get an error: 
Error using ctREFPROP>GETENUMdll (line 1544)
Python Error: ValueError: The function GETENUMdll could not be loaded from the shared library.

The code I ran:
``` matlab

MOLSI = RP.GETENUMdll(int8(0),'MOLAR BASE SI').iEnum;
iMass = int8(0); % 0: molar fractions; 1: mass fractions
iFlag = int8(0); % 0: don't call SATSPLN; 1: call SATSPLN
z = {1.0};
r = RP.REFPROPdll('Water','PQ','T',MOLSI,iMass,iFlag,101325,0.0,z)
```
I was successful in getting to this point in the file, so I loaded the ctREFPROP (although I did have to download the .whl manually and use the ```pip install -U c:/path/to/ctREFPROP-0.7.3-py3-none-any.whl``` code within Anaconda. (Note, I could not get anything to work when I just downloaded Python 3.8. Needed to download the full Anaconda.)

### Versions

**REFPROP Version:9.1  
**Operating System and Version:** Windows 10  
**Access Method:** Python Wrapper

### Additional Information
This is my first time using a Python wrapper; is there a repository of sample codes/syntax? I am used to the legacy syntax, 
``` matlab
enthalpy = refpropm('H','T',298,'P',101.325,'water');
```
A syntax tutorial would be very much appreciated to help me convert to this new (improved) method.

**Comment by ianhbell** [comment]
Correct, ``GETENUMdll`` is only available in version 10 of REFPROP. And so are the other nice functions with a clear mapping to refpropm

The examples in Python linked in the docs show the legacy calls.  Recommend to upgrade to REFPROP 10 for a nicer interface.

**Comment by mpm268** [comment]
Ok, upgraded to V10 of REFPROP. That resolved the error with GETENUMdll. A few other issues persisting; will open new issue to keep these separated. Thanks.

**Comment by ianhbell** [comment]
Thanks, yes that is the right strategy
