### ISSUE TITLE
#NAME Error Still Displaying Despite NIST Suggestions

### ISSUE THREAD

**Issue by davisjohn17** [usnistgov/REFPROP-wrappers#287]
Despite doing my best to follow all of the instructions provided at https://pages.nist.gov/REFPROP-docs/#resolving-problems-linking-with-exce, items my excel still displays as #NAME. Part 12 of the document states that if problems persist, contacting you is necessary. 

The trouble started when I updated from REFPROP 9.1 to Version 10.

The spreadsheet contains Version 10 Commands that start with =@REFPROP

I am not the very best with computers, but I can usually hold my own pretty well and don't know where to go from here. It could easily just be an problem with how I am doing things. Perhaps you can see an error in my steps, or if not suggest another fix. Thanks!

Steps
1. Reinstalled REFPROP in users directory.
1. Ensured directory where REFPROP is installed was included in the path.
2. Searched for anything not in the newly installed directory with V10 that might need to be deleted (didn't find anything).
4. Entered Command =REFPROP(“DLL#”). Nothing happened. 
5. Of course attached the add in to Excel and disabled any security functions that may have prevented it from working. 
6. Ensured appropriate files were running while looking at the VBA code. 

**REFPROP Version: 10 
**Operating System and Version: Windows 10

**Comment by EricLemmon** [comment]
Can you send me a personal email at eric.lemmon@nist.gov.  I will need to log into your computer to find out what is wrong.

**Comment by EricLemmon** [comment]
This was resolved by simply moving the Refprop directory out of the Program Files directory and into the root directory of C:, thus removing any issues with Windows no longer allowing users to make changes inside of its system directories.

The path and the RPprefix environment variable need to be changed when implementing this solution.
