### ISSUE TITLE
No shared libraries were found in the folder "C:\Program Files (x86)\MINI-REFPROP"

### ISSUE THREAD

**Issue by ganralf75** [usnistgov/REFPROP-wrappers#289]
I get the following error message when trying to access REFPROP from Python. I have installed Mini-REFPROP on Windows 10 and set RPPREFIX as environment variable. REFPROP.DLL is available in the installation folder "C:\Program Files (x86)\MINI-REFPROP".

What am I doing wrong? Thanks in advance.

![image](https://user-images.githubusercontent.com/47909064/82595548-0e005280-9ba6-11ea-9b6f-3c32e3d4fec9.png)

**Comment by ianhbell** [comment]
You need to purchase REFPROP to use the python interface with 64-bit python.  REFPROP-MINI is intentionally minimal, but would work with 32-bit python.

**Comment by ganralf75** [comment]
That solved my problem, thanks a lot!
