### ISSUE TITLE
Wrapper not working with Refprop /94/10

### ISSUE THREAD

**Issue by johnnrr** [usnistgov/REFPROP-wrappers#29]
Hi,

wrapper worked with 94 beta (early one). After latest update (03/04/18) wrapper is not working anymore.
Is there a new one for Refprop 10?

Thanks for help

**Comment by johnnrr** [comment]
Hi Ian,

I downloaded the ZIP archive, built the new shared library via the Fortran files under linux with no errors.
Put everthing in the refprop folder in my home directory.
I set the path in Matlab (2015b) to the refprop folder.
I executed the file `testRP.m` which resulted in the following:
![grafik](https://user-images.githubusercontent.com/33105376/38294476-3f92d438-37eb-11e8-841c-fc7ac270d78b.png)

I renamed the `librefprop.so` in `libREFPRP64.so`.
After again exectuting testRP.m:
![grafik](https://user-images.githubusercontent.com/33105376/38294604-aa3366cc-37eb-11e8-80b5-1ff82d8bac2b.png)

Regards

Johannes

**Comment by padevel** [comment]
That last one looks like refpropm.m is not in your matlab path. Is the .m file in a subdirectory that is not explicitly listed in MATLAB's path?

I can't comment specifically on the linux version, but in windows refprop.dll and refprop64.dll are different files, and renaming wouldn't be enough to replace one with the other.

If the new refprop build doesn't produce libREFPRP64.so, I'd be starting to think that something has changed in the libraries (rather than the wrapper). It certainly looks like v10 is bringing a different interface, so this may not be too surprising. Do you have a link to any documentation concerning the "beta 94" version you are using?

**Comment by johnnrr** [comment]
Hi Ian,

the path is surely included in Matlab. Otherwise `testRP.m `would not be working.
You are right, libREFPRP64.so is not produced by the build.
I was expecting that renaming would not be the way, but I gave it a try.
The 94 Version I used before, was a version from 10/11/2017. I was in touch with eric lemmon, who made some changes to the fortran code. But no further documentation on that, sorry.

**Comment by padevel** [comment]
Does `>> which refpropm` give the expected result?

**Comment by johnnrr** [comment]
Hi Ian,

no result

![grafik](https://user-images.githubusercontent.com/33105376/38307402-ef08ea06-3813-11e8-9e94-a84a3a8ffc08.png)

**Comment by johnnrr** [comment]
any other m-file within that folder is working.

**Comment by ianhbell** [comment]
How did you build your DLL/SO?  On linux, you should use my cmake build system: https://github.com/usnistgov/REFPROP-cmake.  I can confirm that refpropm has been working fine for me on linux.  But personally, I don't use MATLAB, I use python for everything, and eventually refpropm will be fully deprecated, replaced with a python interface, called from MATLAB.

**Comment by ianhbell** [comment]
Also, did you read the instructions about the case-sensitivity of the path?  That is crucially important on linux and not important on windows.

**Comment by johnnrr** [comment]
I did everything like explained on `https://github.com/usnistgov/REFPROP-cmake`, but I forgot to copy the refpropm.m in the refprop folder, bad mistake :-(
Now I started again, and downloaded the current refpropm.m from here `https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB`, put refprop folder in the Matlabpath.

Testing `refpropm('T','P',101.325,'Q',0,'WATER')` leads to 

![grafik](https://user-images.githubusercontent.com/33105376/38361216-f3b45a36-38cc-11e8-9019-572d50693363.png)

Testing the file `testRP.m` workes at first time and produces error at second time:

![grafik](https://user-images.githubusercontent.com/33105376/38361239-06f73cbc-38cd-11e8-8c40-c91c6af18eda.png)

refprop folder looks like
![grafik](https://user-images.githubusercontent.com/33105376/38361433-9ce2c55c-38cd-11e8-8e45-35603efc0b60.png)

Matlab Version 2015b

**Comment by johnnrr** [comment]
I found out that function `contains(str,pattern)` was introduced to Matlab since version 2016b. 
I use Version 2015b.
Can you provide older versions of repropm.m for older Matlabversions. Otherwise I will try to modify the unsupported functions.

**Comment by johnnrr** [comment]
Tried a bit. Replaced all `contains()` statements with `findstr()` statements.
Changing line 522 from
`if contains(propReq,'g') || contains(propReq,'n')`
to
`if (strfind(propReq,'g')) ,OR (strfind(propReq,'n'))`
otherwise it was not working
and line 532 from
`if contains(propReq,'v') || contains(propReq,'l') || contains(propReq,'$') || contains(propReq,'%') || contains(propReq,'^')`
to
`if strfind(propReq,'v') ,OR (strfind(propReq,'l')) ,OR (strfind(propReq,'$')) ,OR (strfind(propReq,'%')) ,OR (strfind(propReq,'^'))`

Workes now for C, Q, D from water and hydrogen.
But at the end, I am not sure, if there are some more incompatibilities with older versions of Matlab and for all parts of the code.

**Comment by padevel** [comment]
Hi @johnnrr,

Great - looks like it can find refpropm.m now, and we've got a more usable error string.

The change from `strfind` --> `contains` was part of a few syntax updates I suggested, and it appears backward compatibility may be an issue.

Can you confirm your suggested changes above fix not just the first error ("error in refpropm...") but **also** the issue with loading libREFPROP64.so?

@ianhbell I'm not sure what version(s) of MATLAB you wish to assume for your wrapper. If a requirement of 2016b+ is a bit strict, I can prep the necessary commit. The alternatives of leaving users behind or maintaining a separate 'legacy' branch seem not so appealing.

**Comment by johnnrr** [comment]
Some additional changes were necessary:
line 522:
```
%if contains(propReq,'g') || contains(propReq,'n')
if ~isempty([strfind(propReq,'g'),strfind(propReq,'n')])
```
line 534:
```
% if contains(propReq,'v') || contains(propReq,'l') || contains(propReq,'$') || contains(propReq,'%') || contains(propReq,'^')
if ~isempty([strfind(propReq,'v'),strfind(propReq,'l'),strfind(propReq,'$'),strfind(propReq,'%'),strfind(propReq,'^')])
``` 
line 279:
```
if isempty(strfind(lower(fluidName),'.fld'))
   if isempty(strfind(lower(fluidName),'.ppf'))
      fluidName = strcat(fluidName,'.fld');
    end
end
end
```
We prefer to use Matlab 2015b, because that´s the version for which all our licenses are suitable.

Still got the error with testRP.m
it works only once

**Comment by padevel** [comment]
Forgive me if I'm missing something - is testRP.m your own file? I can't find it in the repository.

If so, can you post the code? Otherwise, let me know where the little fellow lives.

**Comment by johnnrr** [comment]
Its from the repo of the cmake procedure
`https://github.com/usnistgov/REFPROP-cmake`
But anyway, I dont need that. I was just wondering, why it workes only once.

**Comment by padevel** [comment]
Here's my suspicion based on [https://github.com/usnistgov/REFPROP-cmake/blob/master/testRP.m](url)
It executes correctly the first time, because you've already loaded the library using refpropm.m or another method. (I.e. TestRP.m doesn't need to use line13, because `if ~libisloaded('refprop')` check on line8 returns `false`.)

Then, the second time it tries to load the library and fails. This suggests that the path you were using on your previous `libREFPROP64.so` covered the appropriate file, but your current environment does not. Alternatively, the previous loading of the library may have been via an absolute path.

**Comment by ianhbell** [comment]
The refpropm.m interface has been deprecated in version 10, though it still works, so this issue is being closed.

**Comment by herambraj** [comment]
i am getting same error in the windows. 
![image](https://user-images.githubusercontent.com/54817106/132071180-c74c70c0-10e0-48c9-a674-84df100386b9.png)
what should I do to solve  it

**Comment by herambraj** [comment]
please help

**Comment by padevel** [comment]
‘Contains’ is a function present in newer versions of matlab. You’ll need either:
- A newer version of matlab
- An older version of refprop wrappers
- to adjust the string comparison code
- To move to python or another currently supported red prop access method

**Comment by padevel** [comment]
The older version mentioned in https://github.com/usnistgov/REFPROP-wrappers/issues/80#issuecomment-446039656 may be appropriate.
