### ISSUE TITLE
Conflict between Refprop 10.0 and Trend 4.0

### ISSUE THREAD

**Issue by DLozanoMartin** [usnistgov/REFPROP-wrappers#290]
### Description

I have Refprop 10.0 and Trend 4.0 linked to Excel. The (small) problem appears when I try to open either the Refprop 10 ribbon of excel either the file REFPROP.XLS in the default directory. I have attached a picture of the error. After the error message my excel spreadsheet closes suddenly. I think is a conflict between the names of the fluid files of Refprop and Trend. Anyway, I'm not having any other issue when writing formulas in the same excel with these softwares.

### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** Windows 10
**Access Method:** Excel 2019

### Additional Information

![11](https://user-images.githubusercontent.com/48202122/70523890-e065a680-1b3b-11ea-8add-ef8f57c6578f.png)

**Comment by EricLemmon** [comment]
I transferred your issue to the Refprop-wrappers site since it deals with Excel and the DLL.
