### ISSUE TITLE
REFPROP in Excel, Mixture Content Must Add to 1.00

### ISSUE THREAD

**Issue by atticusmech** [usnistgov/REFPROP-wrappers#294]
I upgraded to REFPROP 10 a few months ago but have primarily been using the old 9.1 Excel VBA modules. I'm starting to move over to the new 10.0 modules but now get an error message on fluid compositions that do not add to 1.00

Example
methane    95%
ethane       3%
propane    1%
isobutane  0.5%

fluidstring10 evaluates to methane;ethane;propane;isobutane|.95;.03;.01;.005

But when I try to calculate any properties I get the following error:

#[REFPROP error 805] The composition of the mixture does not sum to one, further calculation of properties will result in erroneous values or failure of the routines and/or DLL.

REFPROP 9.1 would reevaluate the composition automatically to sum to 1.00. If this is by intent, is there any thought of adding an optional input to fluidstring10 to provide a re-scaling calculation similar to what was done in 9.1?

**Comment by EricLemmon** [comment]
I've been thinking of this one for a while now as to which route is the best to take.  Normalizing the mixture is definitely a nice feature to have, but ONLY if you really entered the correct composition.  If you made a mistake then having an error message appear can save you significant frustration down the road.

Maintaining backwards compatibility is only a good thing if the past application worked correctly.  If user's of 9.1 and then of 10 do not like the new setup, changing the code is quite simple.  But if that same user finds that his or her spreadsheet no longer works and digs in to find the problem, the functionality of version 10 might help them pinpoint a problem they were not able to find before.  I think it is necessary and important to leave the program as is and let the user decide how they wish to proceed.

I've closed the issue, but please feel free to make further comments if you have more questions or opinions!
