### ISSUE TITLE
Input string in GETENUMdll; output arrays of ALLPROPS1dll and Refprop1dll

### ISSUE THREAD

**Issue by kit-sg** [usnistgov/REFPROP-wrappers#296]
Hallo,

According to the REFPROP 10.0 documentation, GETENUMdll takes the same input string format as ALLPROPS or GETUNIT. An input string like 'T,P,D,H,E,S' should be permitted, but when calling GETENUMdll that way it returns error 811 'Input string not recognized'. Also the return parameter is a simple integer reference, not an array or pointer.

The parameter c in ALLPROPS1dll is defined as double&, not double* (which would be appropriate for an array or list). So this routine returns only a single value, the documentation states that it should be an array of size 200.

The parameters c and q in REFPROP1dll are defined as double& as well. So this routine returns only single valueS, whereas the documentation states that it should be arrays of size 200.

Best regards,
Steffen

**Comment by ianhbell** [comment]
Hi Steffen,

Regarding ``GETENUMdll``, it is one parameter at a time, so for instance:
```
RP.GETENUMdll('MOLAR BASE SI').iEnum
```
to get the molar base SI unit system enumerated value from Python.  The documentation is correct, in that the strings that can go in there are the same, but the format is not same.

Regarding the other two questions, are you referring to the header from CoolProp/REFPROP-headers? If so, this might just be a typo on my side when I added them to the header.  I don't use those functions, I only ever use ``REFPROPdll``, so I wouldn't have run into trouble so far.  Also, CoolProp still uses the legacy API for compatability with REFPROP 9.1.

**Comment by kit-sg** [comment]
Hi Ian,

Yes, we are using the CoolProp/REFPROP-headers from https://github.com/CoolProp/REFPROP-headers/blob/master/REFPROP_lib.h.

Best regards,
Steffen

**Comment by ianhbell** [comment]
REFPROP1dll only returns a single value (snip from PYF interface generated as part of build):
```
subroutine REFPROP1dll(hIn,hOut,iUnits,iMass,a,b,z,c,q,ierr,herr) 
    character*255 intent(in) :: hIn
    character*255 intent(in) :: hOut
    integer intent(in) :: iUnits
    integer intent(in) :: iMass
    double precision intent(in) :: a
    double precision intent(in) :: b
    double precision dimension(20),intent(inout) :: z
    double precision intent(out) :: c
    double precision intent(out) :: q
    integer intent(out) :: ierr
    character*255 intent(out) :: herr
end subroutine REFPROP1dll
```
and the definition in PASS_FTN.FOR:
``` fortran
      subroutine REFPROP1dll (hIn,hOut,iUnits,iMass,a,b,z,c,q,ierr,herr)
c
      include 'CONSTS.INC'
      character, intent(in) :: hIn*255, hOut*255
      integer, intent(in) :: iUnits, iMass
      double precision, intent(in) :: a, b
      double precision, intent(inout) :: z(ncmax)
      double precision, intent(out) :: c, q
      integer, intent(out) :: ierr
      character, intent(out) :: herr*255
      character hIn2*255, hOut2*255
cDEC$ ATTRIBUTES DLLEXPORT, Decorate, Alias: "REFPROP1dll"::REFPROP1dll
cDEC$ ATTRIBUTES STDCALL, REFERENCE::REFPROP1dll
c     dll_export REFPROP1dll
      i2=INDEX(hIn, CHAR(0))-1
      i3=INDEX(hOut,CHAR(0))-1
      if (i2.lt.0) i2=LEN(hIn)
      if (i3.lt.0) i3=LEN(hOut)
      hIn2 =hIn (:i2)
      hOut2=hOut(:i3)
      call REFPROP1 (hIn2,hOut2,iUnits,iMass,a,b,z,c,q,ierr,herr)
      herr(255:255)=CHAR(0)
      end
```

In REFPROP2dll, the arguments are:
```
#define REFPROP2dll_ARGS char *,char *,char *,INT_REF,INT_REF,DOUBLE_REF,DOUBLE_REF,double *,double *,DOUBLE_REF,INT_REF,char *,RP_SIZE_T,RP_SIZE_T,RP_SIZE_T,RP_SIZE_T
```
coming from
```
subroutine REFPROP2dll(hFld,hIn,hOut,iUnits,iFlag,a,b,z,Output,q,ierr,herr) 
    character*10000 intent(in) :: hFld
    character*255 intent(in) :: hIn
    character*255 intent(in) :: hOut
    integer intent(in) :: iUnits
    integer intent(in) :: iFlag
    double precision intent(in) :: a
    double precision intent(in) :: b
    double precision dimension(20),intent(inout) :: z
    double precision dimension(200),intent(out) :: Output
    double precision intent(out) :: q
    integer intent(out) :: ierr
    character*255 intent(out) :: herr
end subroutine REFPROP2dll
```
Note: the function arguments can be generated by running the script scrape_PASS_FTN.py in CoolProp/REFPROP-headers

**Comment by ianhbell** [comment]
So the ``1`` variant is a single output, the ``2`` variant is shorthand for 200 outputs.

**Comment by EricLemmon** [comment]
Has this issue been resolved?

**Comment by kit-sg** [comment]
Dear Eric,

We haven't followed up this path any further and moved over to the Coolprop wrapper, as suggested by Ian.

Best regards,
Steffen

**Comment by EricLemmon** [comment]
Thanks for letting us know.  I'll close this, but feel free to reopen it anytime if you need more help with it.
