### ISSUE TITLE
Problems from the start

### ISSUE THREAD

**Issue by anderscl** [usnistgov/REFPROP-wrappers#298]
I downloaded REFPROP and put the folder where it suggested: c:\Program Files (x86)\Refprop. I followed the instructions and step 1 was see if the calcs worked in REFPROP.xls and yes, they did. But getting the DLL links working...I was stopped by too many errors to mention.

I sent an email to Eric and Ian and Eric suggested to first move the folder out of the C drive. I did that but now Step 1 is a bust. The output values have an error: Error in opening file for....

Am I beyond hope?

**Comment by EricLemmon** [comment]
Concerning your question about reinstalling without repurchasing the program, see this:
https://github.com/usnistgov/REFPROP-issues/issues/227

There are two methods to get Refprop working outside of the program files directory.  First is installing it somewhere else and then the installer will do all the work of setting up the environment variables.  But, as you are finding out, this may be troublesome in some cases.  If so, there's another troublesome method that might work:

If you have access to the environmental variables and are comfortable changing them, type in "environment variables" in your Windows search menu, which will hopefully lead you to the box shown below.

![image](https://user-images.githubusercontent.com/42392984/83794436-3e8ec480-a65b-11ea-9c29-a8a8c03e1205.png)

Click on the button near the bottom on that page to change the variables.  Then find the RPprefix variable as shown in the picture below.

![image](https://user-images.githubusercontent.com/42392984/83795194-56b31380-a65c-11ea-88b4-c9e0ec37fa6d.png)

Either edit it there as shown below, or delete it and readd it under the "User variables for ..." section.  This edit is only to change the path to the new path where Refprop is now located.

![image](https://user-images.githubusercontent.com/42392984/83795225-62063f00-a65c-11ea-9c27-41f4a35edb76.png)

Next, edit the Path setting in the upper section and add your new path as shown below.  It is best to not edit the path values in the System variables section.  If you make a mistake, your computer may stop working.

![image](https://user-images.githubusercontent.com/42392984/83794870-db516200-a65b-11ea-8edf-84e2223109de.png)

If this is successful, once you restart Excel it should be able to find the DLL, and the DLL should be able to find the fluid and mixture files needed to run the program.

If things still do not work, rebooting the computer often helps.  I have also seen many instances where the user needed to install all new Windows updates and reboot.

**Comment by EricLemmon** [comment]
Has this issue been resolved?

**Comment by anderscl** [comment]
Eric,

Thanks for following up. No, its still not working. I got distracted and
have not gotten back to it.

Could you help me thru it?

Best Regards,


*Charlie Anderson*
(M) 302 981 4028

**Comment by EricLemmon** [comment]
Can you send me a personal email?  I'd like to log into your machine and see what's going on.
eric.lemmon@nist.gov

**Comment by anderscl** [comment]
Eric,

Yes. Thank you very much. For you to login is very much what I need.  This
email works. And I can try to be available any time.

Best Regards,


*Charlie Anderson*
(M) 302 981 4028

**Comment by EricLemmon** [comment]
I logged into his machine and made a few changes.  Most important one was to move the Refprop folder outside of the Program Files directory and into his User's folder.  This also required changing the Path and RPprefix environment variables.  Once done, all worked great.

**Comment by anderscl** [comment]
Thanks very much Eric.  Much appreciated.

Best Regards,


*Charlie Anderson*
(M) 302 981 4028
