### ISSUE TITLE
Calculations not converging in Excel

### ISSUE THREAD

**Issue by quantsnus** [usnistgov/REFPROP-wrappers#3]
When using the wrapper for Excel, installed as described in the Readme, in certain situations some functions like temperature/density and others depending on enthalpy and pressure show a convergence error:
`#[PHFLSH error 247] density iteration for single-phase state did not converge:  [TPRHO error 202] liquid iteration has not converged for T =  300.00 K, P = 0.10000 MPa, rho (last guess) =   10.731 mol/L, compositions =   0.00000`

The same problem is happening for several fluids like Ethane,CO2,... with different working parameter ranges.
For example calculating the temperature of ethane at an enthalpy of 682kJ/kg/K and below and pressure of 0.1MPa is not working. It seems that a certain enthalpy exists below which the convergence is not achieved.
[excelWrapperProblem_minimalExample.xlsx](https://github.com/usnistgov/REFPROP-wrappers/files/704334/excelWrapperProblem_minimalExample.xlsx)
`=Temperature("ethane";"PH";"C";0.1;682)`

The original REFPROP 9.1 program gives a result in those cases without an issue. 

I don't see this behavior is related to any physical reason (like a phase change). Are there hints on this issue?

**Comment by ianhbell** [comment]
This sounds like a failure of the flash routine, and not related to the wrapper itself.  My colleague has been working tirelessly to improve these calculations in our new version of REFPROP.  Are you interested in being a beta tester?  If so, please email me at ian.bell@.nist.gov
