### ISSUE TITLE
Error linking refrop with matlab

### ISSUE THREAD

**Issue by amwesigye** [usnistgov/REFPROP-wrappers#30]
I can not figure out what the problem is. I get the following error, when trying to get refrigerant properties in matlab. I have followed all the instructions, but somehow, it is not working. 

>> refpropm('T','P',101.325,'Q',0,'WATER')
Error using loadlibrary (line 419)
The specified module could not be found.

Error in refpropm (line 242)
            [~,~] = loadlibrary(strcat(BasePath,dllName),prototype,'alias',libName);

**Comment by ianhbell** [comment]
Can you please show a screenshot of the contents of your REFPROP installation folder?

**Comment by amwesigye** [comment]
![image](https://user-images.githubusercontent.com/38106737/38377093-1e22d8ce-38c8-11e8-97ed-c7ae928a707d.png)

**Comment by ianhbell** [comment]
I believe you are missing the thunk file?

**Comment by amwesigye** [comment]
Yes, I think it is true. I had it in and then removed it. I have put it back and it gives me this error
Error using loadlibrary (line 419)
C:\Program Files\REFPROP\REFPRP64_thunk_pcwin64.dll is not a valid Win32 application.



Error in refpropm (line 242)
            [~,~] = loadlibrary(strcat(BasePath,dllName),prototype,'alias',libName)
 
>> 
I think it is because my matlap is 32 bit. How can i get the thunk file for 32 bit?

**Comment by ianhbell** [comment]
Ah, you only need the thunk file for 64-bit.

What version of REFPROP do you use?

**Comment by amwesigye** [comment]
I am at the moment using miniREFPROP

**Comment by ianhbell** [comment]
Ah, I see.  Officially we do not offer any technical support for miniREFPROP.  You'll have to purchase a copy of the full version of REFPROP.

**Comment by ianhbell** [comment]
Yes, absolutely, we have loads of MATLAB users of REFPROP
