### ISSUE TITLE
Inconsistency between Refprop10 software and Refprop10 addon for excel

### ISSUE THREAD

**Issue by coolbizgr** [usnistgov/REFPROP-wrappers#301]
I noticed an inconsistency between Refprop10 software and Refprop10 addon for excel when calculating R449A. The results do not match. For example the calculation of  critical density: 
Refprop10 software : 479.39kg/m^3
Refprop10 Excel addon: 496.853kg/m^3
And that is just an example. Please find attached screenshots
![2020-06-04 (2)](https://user-images.githubusercontent.com/66459581/83842887-90dbee00-a70c-11ea-85f3-207987954052.png)
![2020-06-04](https://user-images.githubusercontent.com/66459581/83842902-946f7500-a70c-11ea-9ed8-3353a3202845.png)

**Comment by coolbizgr** [comment]
> I believe the issues in this particular case is that you have entered mole fractions in Excel, mass fractions in the GUI.

Thank you! Just curious. Is there a way to enter mass fraction in Excel?

**Comment by ianhbell** [comment]
Yes, add " mass" after the compositions (without the quotes)
