### ISSUE TITLE
Call between Matlab&Simulink and Refprop

### ISSUE THREAD

**Issue by caidiner** [usnistgov/REFPROP-wrappers#302]
The dynamic model of organic Rankine cycle (thermodynamic system) is established based on S function. Meanwhile, mixture (e.g. R245fa/R134a) is used as the working fluid. After running the dynamic model in Simulink, the error "MATLAB has encountered an internal problem and needs to close" occurs. This problem don't occur in dynamic model simulation for mixtures when I switch to Win 7 operating system. Further, the dynamic model simulation for pure fluid (e.g. R245fa) performs well on Win 10 operating system. In addition, the call of thermophysical property for mixture in ordinary Matlab function behaves normally.  Hence, I don't know what causes the crash of Matlab&Simulink on win 10.]

**REFPROP Version:** [REFPROP v9.0]  
**Operating System and Version:** [Windows 10]  
**Access Method:**[The function "refpropm" is used to call thermophysical property from Refprop on MATLAB.]

**Comment by ianhbell** [comment]
See #50

**Comment by caidiner** [comment]
Mr Bell, thanks for your kindly assistance.+1:   I will refer to the link you provided : https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB/legacy#instructions-on-windows :

**Comment by caidiner** [comment]
Mr Bell, I would like to consult about thermophysical properties calculation of CO2. I built a dynamic model of thermal fluid system in simulink environment and interface function "Refpropm" was adopted to obtain CO2 properties required for heat transfer calculation. We found that it takes a lot of time to call refprop and this obviously affects the simulation speed of the dynamic model. To speed up the calculation, I wonder if there is a way, such as writing a function by myself referring to the CO2 equation of state used by refprop to achieve thermophysical properties calculation. The paper authored by Roland Span, and Wolfgang Wagner, which is titled as  "A New Equation of State for Carbon Dioxide Covering the Fluid Region from the Triple-
Point Temperature to 1100 K at Pressures up to 800 MPa" , provides plenty of equations and data. Is it sufficient to achieve the calculation of thermophysical properties of CO2. Thanks for your kind assistance.

**Comment by ianhbell** [comment]
In general, please open a new issue for new questions; not related to the initial issue.

a) I would not use MATLAB if you care about speed
b) I would use the tabular interpolation of the EOS of some kind.  Perhaps with this (which can also use REFPROP as the provider of the EOS values): http://www.coolprop.org/coolprop/Tabular.html#tabular-interpolation .  I wouldn't recommend to implement it yourself, I have, several times now, and it is not a small task.

**Comment by caidiner** [comment]
Thanks your help. I will try to implement your suggestion. Your contribution concerning fluid thermophysical properties calculation deserves my respect. Thank you again.
