### ISSUE TITLE
Property extraction from REFPROP to Python 

### ISSUE THREAD

**Issue by tolikparahovnik** [usnistgov/REFPROP-wrappers#303]
Hello

I am looking for a way to extract single properties from REFROP 9.1 into Phyton (Spyder). 
(Unfortunately, upgrading to REFPROP 10 is not en option)

I am looking for something similar to the function "refpropm.m" available in MATLAB.

I was able to access REFPROP however I fail to be able to extract the desired properties, using code 
I have adapted from 
"https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python".
But I am failing to be able to alter it for my needs.

I would really appreciate it if you could help me with some documentation/ examples/tutorials.

Thank you very much

**Comment by tolikparahovnik** [comment]
Thank you, I will look into that

**Comment by tolikparahovnik** [comment]
Hi 
I tried to implement the CoolProp script, the code was:

from CoolProp.CoolProp import PropsSI

PropsSI.set_config_string(PropsSI.ALTERNATIVE_REFPROP_PATH, 'C:\Program Files (x86)\REFPROP\REFPRP64.DLL')

PropsSI("T","P",101325,"Q",0,"REFPROP::Water")

and the error I got was:
runfile('C:/Users/Anatoly/Desktop/PhD studies/Python tutorial/refprop_Connection.py', wdir='C:/Users/Anatoly/Desktop/PhD studies/Python tutorial')
Traceback (most recent call last):

  File "C:\Users\Anatoly\Desktop\PhD studies\Python tutorial\refprop_Connection.py", line 4, in <module>
    PropsSI.set_config_string(PropsSI.ALTERNATIVE_REFPROP_PATH, 'C:\Program Files (x86)\REFPROP\REFPRP64.DLL')

AttributeError: 'builtin_function_or_method' object has no attribute 'set_config_string'

and without the path definition I got the following error :

"runfile('C:/Users/Anatoly/Desktop/PhD studies/Python tutorial/refprop_Connection.py', wdir='C:/Users/Anatoly/Desktop/PhD studies/Python tutorial')
Traceback (most recent call last):

  File "C:\Users\Anatoly\Desktop\PhD studies\Python tutorial\refprop_Connection.py", line 4, in <module>
    PropsSI("T","P",101325,"Q",0,"REFPROP::Water")

  File "CoolProp\CoolProp.pyx", line 373, in CoolProp.CoolProp.PropsSI

  File "CoolProp\CoolProp.pyx", line 453, in CoolProp.CoolProp.PropsSI

  File "CoolProp\CoolProp.pyx", line 340, in CoolProp.CoolProp.__Props_err2

ValueError: Initialize failed for backend: "REFPROP", fluid: "Water" fractions "[ 1.0000000000 ]"; error: fluid directories "FLUIDS" or "fluids" could not be found in the directory [C:\Program Files (x86)\REFPROP\REFPRP64.DLL] : PropsSI("T","P",101325,"Q",0,"REFPROP::Water")"

I would greatly appreciate it if you could advise what should be my next steps?

**Comment by ianhbell** [comment]
Should be:
```python

import CoolProp.CoolProp as CP

CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, 'C:\Program Files (x86)\REFPROP')

CP.PropsSI("T","P",101325,"Q",0,"REFPROP::Water")

**Comment by tolikparahovnik** [comment]
Thank you very much it is working

**Comment by ianhbell** [comment]
Please go ahead and close the issue then.
