### ISSUE TITLE
old wrappers for matlab crashes randomly

### ISSUE THREAD

**Issue by AleDebo** [usnistgov/REFPROP-wrappers#304]
Hi I know that the old wrappers for Matlab is not supported anymore, I try to ask nonetheless... The wrappers wroks in matlab. Problem is every now and then matlab crashes. 

This is the report of the crash.I tryed asking mathworks, and it seems that matlab cannot find the REFPRP64.dll file. Problem is sometimes it works and sometime not so I don't know where the problem is

--------------------------------------------------------------------------------
          Access violation detected at gio giu 11 01:38:42 2020 +0200
--------------------------------------------------------------------------------

Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : windows-1252
  Deployed                 : false
  Graphics Driver          : NVIDIA Corporation GeForce GTX 850M/PCIe/SSE2 Version 4.6.0 NVIDIA 445.87
  Graphics card 1          : Intel Corporation ( 0x8086 ) Intel(R) HD Graphics Family Version 10.18.15.4279 (2015-8-24)
  Graphics card 2          : NVIDIA ( 0x10de ) NVIDIA GeForce GTX 850M Version 26.21.14.4587 (2020-4-3)
  Java Version             : Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : win64
  MATLAB Entitlement ID    : 1849657
  MATLAB Root              : C:\Program Files\MATLAB\R2020a
  MATLAB Version           : 9.8.0.1359463 (R2020a) Update 1
  OpenGL                   : hardware
  Operating System         : Microsoft Windows 10 Home
  Process ID               : 22320
  Processor ID             : x86 Family 6 Model 69 Stepping 1, GenuineIntel
  Session Key              : 4eda75fd-eaa8-4dfb-8f86-3c757e2bc02e
  Window System            : Version 10.0 (Build 18363)

Fault Count: 1

Abnormal termination:
Access violation

Register State (from fault):
  RAX = 0000000000000000  RBX = 000002b70dbb8e8c
  RCX = 000002b70dbb7b40  RDX = 0000000014ac84c0
  RSP = 000000efb5bf7a48  RBP = 000002b706b833c0
  RSI = 000002b706b833c0  RDI = 000002b72267ff60
 
   R8 = 00000000000000ff   R9 = 0000000000000002
  R10 = 0000000000000000  R11 = 000002b70dbb7aa0
  R12 = 000002b7121391b0  R13 = 000002b712139300
  R14 = 000002b7121394e0  R15 = 000002b706b83910
 
  RIP = 0000000066b9e2e0  EFL = 00010202
 
   CS = 0033   FS = 0053   GS = 002b

Stack Trace (from fault):
[  0] 0x0000000066b9e2e0 C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9619_none_08e065a3a84109b0\MSVCR90.dll+00123616 memmove+00000176
[  1] 0x000002b70d9a21a8        C:\Program Files (x86)\REFPROP\REFPRP64.DLL+00401832 PASSCMN+00075864
[  2] 0x00007ff897215ac1 C:\Program Files (x86)\REFPROP\REFPRP64_thunk_pcwin64.dll+00023233 voidvoidPtrcstringcstringcstringvoidPtrcstringint32int32int32int32Thunk+00000465
[  3] 0x00007ff89731f43d C:\Program Files\MATLAB\R2020a\bin\win64\libmwcli.dll+00062525
[  4] 0x00007ff8973238cb C:\Program Files\MATLAB\R2020a\bin\win64\libmwcli.dll+00080075 mwboost::serialization::singleton_module::get_lock+00000555
[  5] 0x00007ff897343083 C:\Program Files\MATLAB\R2020a\bin\win64\libmwcli.dll+00209027 PointerMapSize+00102067
[  6] 0x00007ff89734453d C:\Program Files\MATLAB\R2020a\bin\win64\libmwcli.dll+00214333 PointerMapSize+00107373
[  7] 0x00007ff87c11b3bc                     bin\win64\pgo\m_dispatcher.dll+00046012 Mfh_MATLAB_fn_impl::dispatch_mf_with_reuse+00000172
[  8] 0x00007ff87c121f12                     bin\win64\pgo\m_dispatcher.dll+00073490 Mlm_file::needToCheckoutLicense+00002674
[  9] 0x00007ff87c12143d                     bin\win64\pgo\m_dispatcher.dll+00070717 Mfh_MATLAB_fn_impl::dispatch+00000045
[ 10] 0x00007ff8610d4002                            bin\win64\pgo\m_lxe.dll+00540674
[ 11] 0x00007ff8610d1ce4                            bin\win64\pgo\m_lxe.dll+00531684
[ 12] 0x00007ff8611b0179                            bin\win64\pgo\m_lxe.dll+01442169 MathWorks::lxe::StartupLxeEngine+00239509
[ 13] 0x00007ff8610d033b                            bin\win64\pgo\m_lxe.dll+00525115
[ 14] 0x00007ff8610ce6ff                            bin\win64\pgo\m_lxe.dll+00517887
[ 15] 0x00007ff8610c562e                            bin\win64\pgo\m_lxe.dll+00480814
[ 16] 0x00007ff8610c46ac                            bin\win64\pgo\m_lxe.dll+00476844
[ 17] 0x00007ff86107f715                            bin\win64\pgo\m_lxe.dll+00194325
[ 18] 0x00007ff8610c44b0                            bin\win64\pgo\m_lxe.dll+00476336
[ 19] 0x00007ff8610c3fdc                            bin\win64\pgo\m_lxe.dll+00475100
[ 20] 0x00007ff87c1225d0                     bin\win64\pgo\m_dispatcher.dll+00075216 AutoPushingExecutionFrame::~AutoPushingExecutionFrame+00000784
[ 21] 0x00007ff87c12226d                     bin\win64\pgo\m_dispatcher.dll+00074349 Mfh_file::dispatch_with_reuse+00000045
[ 22] 0x00007ff8610d317b                            bin\win64\pgo\m_lxe.dll+00536955
[ 23] 0x00007ff8610d0d47                            bin\win64\pgo\m_lxe.dll+00527687
[ 24] 0x00007ff8611e2c65                            bin\win64\pgo\m_lxe.dll+01649765 MathWorks::lxe::ShutdownLxeEngine+00057593
[ 25] 0x00007ff8611e2b8f                            bin\win64\pgo\m_lxe.dll+01649551 MathWorks::lxe::ShutdownLxeEngine+00057379
[ 26] 0x00007ff8611e29c3                            bin\win64\pgo\m_lxe.dll+01649091 MathWorks::lxe::ShutdownLxeEngine+00056919
[ 27] 0x00007ff8610d1ce4                            bin\win64\pgo\m_lxe.dll+00531684
[ 28] 0x00007ff86120ad51                            bin\win64\pgo\m_lxe.dll+01813841 mwboost::archive::detail::oserializer<mwboost::archive::binaryTerm_oarchive,ir::IrTree>::oserializer<mwboost::archive::binaryTerm_oarchive,ir::IrTree>+00059517
[ 29] 0x00007ff8610d033b                            bin\win64\pgo\m_lxe.dll+00525115
[ 30] 0x00007ff8610ce6ff                            bin\win64\pgo\m_lxe.dll+00517887
[ 31] 0x00007ff8610c562e                            bin\win64\pgo\m_lxe.dll+00480814
[ 32] 0x00007ff8610c46ac                            bin\win64\pgo\m_lxe.dll+00476844
[ 33] 0x00007ff86116c981                            bin\win64\pgo\m_lxe.dll+01165697
[ 34] 0x00007ff8610c4490                            bin\win64\pgo\m_lxe.dll+00476304
[ 35] 0x00007ff86120a2ad                            bin\win64\pgo\m_lxe.dll+01811117 mwboost::archive::detail::oserializer<mwboost::archive::binaryTerm_oarchive,ir::IrTree>::oserializer<mwboost::archive::binaryTerm_oarchive,ir::IrTree>+00056793
[ 36] 0x00007ff87c1aaebd                     bin\win64\pgo\m_dispatcher.dll+00634557 Mfh_file::dispatch_file_common+00000165
[ 37] 0x00007ff87c1aa54d                     bin\win64\pgo\m_dispatcher.dll+00632141 Mfh_error::lookup+00006517
[ 38] 0x00007ff87c1aae11                     bin\win64\pgo\m_dispatcher.dll+00634385 Mfh_file::dispatch+00000045
[ 39] 0x00007ff8610d3898                            bin\win64\pgo\m_lxe.dll+00538776
[ 40] 0x00007ff86109c386                            bin\win64\pgo\m_lxe.dll+00312198
[ 41] 0x00007ff86109c270                            bin\win64\pgo\m_lxe.dll+00311920
[ 42] 0x00007ff8610d1ce4                            bin\win64\pgo\m_lxe.dll+00531684
[ 43] 0x00007ff8611e89b1                            bin\win64\pgo\m_lxe.dll+01673649 MathWorks::lxe::ShutdownLxeEngine+00081477
[ 44] 0x00007ff8610c3f8d                            bin\win64\pgo\m_lxe.dll+00475021
[ 45] 0x00007ff8610c6344                            bin\win64\pgo\m_lxe.dll+00484164
[ 46] 0x00007ff8610c745d                            bin\win64\pgo\m_lxe.dll+00488541
[ 47] 0x00007ff8610c704f                            bin\win64\pgo\m_lxe.dll+00487503
[ 48] 0x00007ff8611d0fb4                            bin\win64\pgo\m_lxe.dll+01576884 MathWorks::lxe::StartupLxeEngine+00374224
[ 49] 0x00007ff8610cf30b                            bin\win64\pgo\m_lxe.dll+00520971
[ 50] 0x00007ff8610c562e                            bin\win64\pgo\m_lxe.dll+00480814
[ 51] 0x00007ff8610c46ac                            bin\win64\pgo\m_lxe.dll+00476844
[ 52] 0x00007ff861135abf                            bin\win64\pgo\m_lxe.dll+00940735
[ 53] 0x00007ff861135c2b                            bin\win64\pgo\m_lxe.dll+00941099
[ 54] 0x00007ff861135b22                            bin\win64\pgo\m_lxe.dll+00940834
[ 55] 0x00007ff86116ce70                            bin\win64\pgo\m_lxe.dll+01166960
[ 56] 0x00007ff86116ce1e                            bin\win64\pgo\m_lxe.dll+01166878
[ 57] 0x00007ff862b84ef8                            bin\win64\pgo\m_lxe.dll+28528376 MathWorks::lxe::profiler::IMexProfilingSupport::~IMexProfilingSupport+00083312
[ 58] 0x00007ff889bbda8c C:\Program Files\MATLAB\R2020a\bin\win64\libmwbridge.dll+00187020 mnParser+00001212
[ 59] 0x00007ff87c426a99   C:\Program Files\MATLAB\R2020a\bin\win64\mcr.dll+00551577 mcr_set_enableReadingFromStdin+00016745
[ 60] 0x00007ff87c3ba05a   C:\Program Files\MATLAB\R2020a\bin\win64\mcr.dll+00106586 mcrOptions::set_use_license_manager+00071962
[ 61] 0x00007ff87c3db04a   C:\Program Files\MATLAB\R2020a\bin\win64\mcr.dll+00241738 mcrOptions::set_use_license_manager+00207114
[ 62] 0x00007ff87da0653e   C:\Program Files\MATLAB\R2020a\bin\win64\iqm.dll+00615742 iqm::PackagedTaskPlugin::execute+00000862
[ 63] 0x00007ff87da063c9   C:\Program Files\MATLAB\R2020a\bin\win64\iqm.dll+00615369 iqm::PackagedTaskPlugin::execute+00000489
[ 64] 0x00007ff87c42084e   C:\Program Files\MATLAB\R2020a\bin\win64\mcr.dll+00526414 mcrIsExternalAvailableBuiltin+00045518
[ 65] 0x00007ff87d9dca03   C:\Program Files\MATLAB\R2020a\bin\win64\iqm.dll+00444931 iqm::Iqm::setupIqmFcnPtrs+00100227
[ 66] 0x00007ff87d9b4e2f   C:\Program Files\MATLAB\R2020a\bin\win64\iqm.dll+00282159 iqm::Iqm::create+00009279
[ 67] 0x00007ff87d9b4428   C:\Program Files\MATLAB\R2020a\bin\win64\iqm.dll+00279592 iqm::Iqm::create+00006712
[ 68] 0x00007ff87c3f7d06   C:\Program Files\MATLAB\R2020a\bin\win64\mcr.dll+00359686 mcrInstantiationError::operator=+00012150
[ 69] 0x00007ff87c3f830c   C:\Program Files\MATLAB\R2020a\bin\win64\mcr.dll+00361228 mcrInstantiationError::operator=+00013692
[ 70] 0x00007ff87c3f5f0c   C:\Program Files\MATLAB\R2020a\bin\win64\mcr.dll+00352012 mcrInstantiationError::operator=+00004476
[ 71] 0x00007ff8a5aaa203 C:\Program Files\MATLAB\R2020a\bin\win64\mwboost_thread-vc141-mt-x64-1_70.dll+00041475 mwboost::thread::swap+00000083
[ 72] 0x00007ff8cad40e82                   C:\WINDOWS\System32\ucrtbase.dll+00134786 beginthreadex+00000322
[ 73] 0x00007ff8ccbf7bd4                   C:\WINDOWS\System32\KERNEL32.DLL+00097236 BaseThreadInitThunk+00000020
[ 74] 0x00007ff8cd20ce51                      C:\WINDOWS\SYSTEM32\ntdll.dll+00446033 RtlUserThreadStart+00000033

**Comment by ianhbell** [comment]
As you correctly note, the legacy wrapper is no longer supported.  The REFPROPdll function of REFPROP 10 covers all the capabilities of refpropm, and more.

**Comment by AleDebo** [comment]
do you have any clue why I get this error randomly? I most of the time the wrapper works , but sometimes it crashes. If someone could help me would be appreciated

**Comment by ianhbell** [comment]
Can you convert to the new wrapper?  I haven't heard of any similar reports with the new wrapper.

**Comment by AleDebo** [comment]
Is it supported for version 9.1?

**Comment by ianhbell** [comment]
Yup.  All the functions of REFPROP 9.1 are exposed, you just need to know which ones to call, which is a bit annoying.  Recommend to upgrade to REFPROP 10 for this an other improvements.
