### ISSUE TITLE
Host in both PyPi and CONDA?

### ISSUE THREAD

**Issue by AbramYorde** [usnistgov/REFPROP-wrappers#305]
More of a question I suppose, I'm not too fluent in python so hopefully this isn't a big ask.

We have a few internal processes that use REFPROP to append some thermodynamic properties during compressor tests. Recently we have seen a push to move the execution of this into a cloud environment. This has been successful running manually from a VM, but we hit a roadblock when we tried to execute in an automated workflow. 

In Azure to have this run in a pipeline it needs to be capable of spinning up a VM where it has resources, and without a custom docker image it only has access to CONDA hosted libraries. It would be significantly easier if we could avoid the custom image, what is required for this to be hosted in both PyPi and CONDA?

Thanks!

**Comment by ianhbell** [comment]
Well, the _wrapper_ can be installed via pip, which will work in any of these containers that have conda, but building REFPROP for your container will be not so nice (I can show some examples in docker containers we use for testing).  I can't see any easy solution to that problem, this is one of the challenges of mixing proprietary and non-proprietary software when it comes to cloud computing.

**Comment by EricLemmon** [comment]
Has this issue been resolved?  If so, could you close it?

**Comment by AbramYorde** [comment]
Yes, for closure the workaround was to have an initial script which installed the dependencies / ctREFPROP when the VMs were spun up.

**Comment by ianhbell** [comment]
With docker, I usually build them into the container itself, it saves some spin-up time.
