### ISSUE TITLE
Excel Wrapper not communicating between REFPROP and Excel sheets

### ISSUE THREAD

**Issue by rarnold787** [usnistgov/REFPROP-wrappers#306]
### Description

I have downloaded REFPROP 10 and the .XLS and .XLA files located on the GitHub website. I've folloewd the 7 steps over 10 times trying to play with different parameters and even (attempting) adding the DLL to the path. Whenever I attempt to write out a command (e.g. =REFPROP(...) a "#VALUE" message appears in the boxes. I've unlocked every file, and I've verified the add-ins are installed to my Excel document, and for whatever reason the DLL isn't talking to Excel. I attempted to go into the VBA code and find where to locate the file directory within the code but didn't have any luck.

Also, when I first download the XLS spreadsheet to save as an add-in and what not, when the spreadsheet is in the protected view all the sub-spreadsheets are full of data and numbers. When I take it out of Protected View to "save-as" the numbers nearly turn into error messages on most of the pages. I am unsure of what else to do, I've been attempting to figure this out for 8 hours now. Also, in the off-chance I got it recognize the fluid names, it doesn't recognize Carbon Dioxide, which coincidentally is the gas I need to examine. Even when it did recognize a couple of the fluids it didn't produce any useful results.

I typed in the exact example command it says to model other commands off of in the Welcome page and it yields another #VALUE symbol.

Steps 1 through 5 don't have any issues, as far as it throwing errors or getting mad in other ways. Step 6 has consistently had a greyed-out "edit links" button and doesn't let me in there. But when I try and type anything in it kicks out gibberish. It knows about the add-in because when I start typing the command, the REFPROP suggested function pops up in the cell, but outputs error messages.

![image](https://user-images.githubusercontent.com/66985597/84730142-0771ba80-af5b-11ea-9c1d-7b1ec0bb1c38.png)

![image](https://user-images.githubusercontent.com/66985597/84730181-19535d80-af5b-11ea-9ed5-d37f9add49ea.png)

### Steps to Reproduce

This is before disabling protected view.
![image](https://user-images.githubusercontent.com/66985597/84729799-350a3400-af5a-11ea-866a-8446e4e3b0d2.png)

This is after it is is off and editing is enabled.
![image](https://user-images.githubusercontent.com/66985597/84729863-5bc86a80-af5a-11ea-83b7-52aabcfadded.png)

**Expected behavior:** I expected to be able to link REFPROP data to an excel spreadsheet for input to the model but it isn't talking to it somehow.

**Actual behavior:** It doesn't reference anything in the DLL or other filesets and if it does it is pulling garbage data, or it is confused.

### Versions

**REFPROP Version:** REFPROP 10
**Operating System and Version:** Windows 10 Home, x64 version.
**Access Method:** Excel wrappers

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by EricLemmon** [comment]
The absolutely best method to get Refprop and Excel to communicate is to move Refprop out of the Windows directories.  See #298 for more information.

**Comment by EricLemmon** [comment]
You should also look through other posts with the "documentation" label.  These are ones where we give more than just quick answers and really try to document the problem.  Here are two links that will take you directly to those searches:
https://github.com/usnistgov/REFPROP-wrappers/issues?q=label%3Adocumentation+
https://github.com/usnistgov/REFPROP-issues/issues?q=label%3Adocumentation+

**Comment by rarnold787** [comment]
Hi Eric,

I've moved the program to a variety of locations (Users, Program Files (not
the x86 variant) and even to the desktop directly with no luck on my end.
I'm encountering a goofy problem where when I download the .XLS file from
GitHub, it comes in as a protected file, meaning I can't edit it without
enabling that feature in the ribbon on the top, see the image below. And I
also can't "save as" the .XLAM file I need it to be so I can add it to the
REFPROP folder.

[image: image.png]

It is interesting because when I don't enable this feature, this
spreadsheet has all the values and cells filled out "properly", complete
without the #VALUE and #REF! error messages. See below, which is from the
"Units" subsheet within the file.

[image: image.png]

When I enable editing and the Macros on the file by clicking the "Enable
Editing" button on the top ribbon, this happens:

[image: image.png]

The other subsheets in the file suffer the same fate as this one did,
albeit sometimes with different Excel errors. I'm beginning to think that
the DLL might be working, but it's returning errors because that is all the
downloadable .XLS file has in it anymore. I've been following the
instructions inside of the VBA code troubleshooting guide and no luck there
either. I'm not sure where to go from here. I've uninstalled and
reinstalled over 20 times now trying to get it to cooperate, and I've
checked the environment variables along with that too. Everything is set up
like the guides say. Any ideas?

Cheers,

Ryan Arnold

**Comment by rarnold787** [comment]
Eric,

Update:

I got the Units page and what not to transition from the #NAME error to
#VALUE, which from what I'm reading means that it is finding the DLL but it
isn't working. When I open the .XLS file directly and I haven't saved it or
enabled editing, in the box with the REFPROP DLL Version number on the top
of the welcome page I saw the command "=REFPROP("DLL#"). In the
troubleshooting guide it says that this the command to enter to confirm if
the fluid files can be found. If it works, the fluid files could be found,
and if not they couldn't be found. It is not working, leading me to believe
the fluid files couldn't be found.

I've gone into the VBA code and modified the line routing to where the DLL
file is saved and referenced by Excel, which didn't change anything. After
that, I noticed there is a location to modify the fluid file reference in
the subsequent section. I'm unfamiliar with the syntax and I'm not
comfortable changing it, but I figured you might know where to go.

Cheers,

Ryan Arnold

**Comment by EricLemmon** [comment]
Hi Ryan,

Can you email me directly, I think I may need to log into your machine to see if I can fix it.

Eric  (eric.lemmon@nist.gov)

P.S.  Your pictures did not come through.  Instead of using email to post messages, use the github website to directly enter your text and paste your pictures.  That also keeps all personal information out of the system.

**Comment by rarnold787** [comment]
Eric dropped the REFPR64.DLL into my directory and it worked fine. Thanks Eric!
