### ISSUE TITLE
No old functions in REFPROP v10 (e.g. "=Temperature(" )

### ISSUE THREAD

**Issue by mv970** [usnistgov/REFPROP-wrappers#307]
Hello, 

I installed Refprop version 10 and I can not use the old functions (e.g. "=Temperature(" )

See attached the images.
1- refprop is installed because I can see the function  (e.g. "=REFPROP(" )
2- The old functions are not there.

This is a big problem for me because I can not open the old files.

Can you help me with that?

Regards,
Marco

<img width="156" alt="1 refprop" src="https://user-images.githubusercontent.com/67296419/85344399-aee68280-b543-11ea-8ea2-4a10456019b1.PNG">
<img width="176" alt="2 no temp" src="https://user-images.githubusercontent.com/67296419/85344401-b0b04600-b543-11ea-9d44-a68fdb7565d9.PNG">

**Comment by ianhbell** [comment]
Please see the conversion macro included as part of the add-in for Excel

**Comment by mv970** [comment]
Hello, 

I am sorry but is not the problem.

REFPROP 10 should read old functions (from version 9.1 or older). 

If you see picture 2, when I try to look for the function "Temperature", I can not see it.

Working with my colleges, they are able to read the old functions.

Can you help me with this problem?

Regards,
Marco

**Comment by EricLemmon** [comment]
Take a look here at the bottom section and see if it helps:

https://pages.nist.gov/REFPROP-docs/#resolving-problems-linking-with-excel

**Comment by mv970** [comment]
Hi Eric,

Refprop should be linked to my excel correctly.
Please see picture 3 a screenshot my system and environmental variables .

Refprop works, but it does not read the old functions.

Do you think the problem is due to the fact I installed only the 10th version of REFPROP in my pc, while my colleagues have updated the old version? 

e.g. a colleague of mine had the version 8, and he updated this version to the 10. 

Do you think this can explain why he can see the old functions and I can't?

Regards,
Marco

<img width="305" alt="3 envoronment and system variables" src="https://user-images.githubusercontent.com/67296419/85348735-9a5cb700-b550-11ea-937f-b76ce5bb1901.PNG">

**Comment by EricLemmon** [comment]
You need to do one of two things, either download the 9.1 XLA file here:

https://trc.nist.gov/refprop/10-PATCH/REFPRP91.XLA

or run the macro called  ConvertRefprop9to10, which is described in the opening screen in the Refprop.xls file, and briefly described here:

https://github.com/usnistgov/REFPROP-wrappers/issues/258

There's no need to load a previous version of Refprop.

**Comment by mv970** [comment]
I'm sorry but your link does not open.

This is what I see.

I tried to open it with Chrome, Explorer but I had no luck with that.

Can you help me?

Regards,
Marco

<img width="959" alt="link" src="https://user-images.githubusercontent.com/67296419/85352856-06441d00-b55b-11ea-9d4e-f3712d86e13e.PNG">

**Comment by EricLemmon** [comment]
Try downloading it here:

https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Excel

**Comment by EricLemmon** [comment]
Have you been able to download the file?  I noticed that the same thing happened to me, but that later it was fixed.  Someone else recently also told me that they were able to download it properly.

**Comment by EricLemmon** [comment]
I'm going to close this issue, but if the problems are not fixed, you can still add new comments or even open the issue again.
