### ISSUE TITLE
REFPROP not returning accurate fluid properties for some fluids

### ISSUE THREAD

**Issue by rarnold787** [usnistgov/REFPROP-wrappers#308]
REFPROP v10 is not returning accurate fluid property data for some of it's fluids in the FLUIDS folder. I am not sure if this a program error in the mathematics or a fluid property error, but I am inclined to believe that it is an issue with specific fluid files since for some fluids REFPROP returns accurate data, and on others it does not. I have not tested all the fluids (that would take a very long time), but some of the fluids I require for my project and models seem to be inaccurate.

So far, I've found that CO2, R134a, and Air (dry) are not returning the correct values for enthalpy(h), entropy(s), and internal energy (u). I haven't done hand calculations for other properties to verify if those are correct. I believe the density and compressiblity parameters to be accurate from initial sanity checks.

I believe this to be the case because when I use the REFPROP tool "Specified State Points" and compare them with that of a standard thermo-property table found in textbooks, the data does not match. More interestingly, for these fluids the property variation deviates by an exact constant across any and all combinations of pressure and temperature. For example, no matter the pressure and temperature inputs, the enthalpy output by REFPROP for R134a is always greater by about 148 KJ/kg (almost exact every time), and entropy is greater by .7956. For CO2, enthalpy output by REFPROP is greater by about 293 KJ/kg (almost exactly once again) no matter the difference in pressure and temperatures selected. In the image below you can see that this trend is shown by taking the difference of enthalpies from the tabulated data and REFPROP outputs. Images for R134a and Air below:

![image](https://user-images.githubusercontent.com/66985597/85955439-379a5f80-b944-11ea-8b34-3b1fe6261a87.png)

![image](https://user-images.githubusercontent.com/66985597/85955612-5e0cca80-b945-11ea-9ae6-c2c14d05a21b.png)

This is odd because water, oxygen, and nitrogen are working fine and the data does match published documentation.

It should be noted I cannot verify this trend is correct for CO2, dry air, and potentially other fluids I have not yet checked if they are outside of the "ideal gas region" since published data is only available to me in the ideal gas region (except for water and R134a), but since R134a is showing this problem outside of the ideal gas region I'm convinced it persists throughout the program bounds of data. I am using REFPROP because I specifically need data outside the ideal gas region and as it stands the model I'm' making will not be accurate given this issue.

I am going to attempt to download the REFPROP mini and see if the same issues arise there as well.

No steps to reproduce.

**Expected behavior:** I'd expect REFPROP to be outputting accurate data, but I am not aware of where to change this "constant addition".

**Actual behavior:** The values of enthalpy, entropy, internal energy, and potentially other properties exist with a seemingly random constant value added to the tabulated data values for these properties in the REFPROP output.

### Versions

**REFPROP Version:** REFPROP 10
**Operating System and Version:** Windows 64 bit
**Access Method:** Microsoft Excel Wrapper

**Comment by ianhbell** [comment]
Please see our most popular FAQ: https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences

**Comment by EricLemmon** [comment]
You've run into the most commonly misunderstood feature of thermodynamics and Refprop:  reference states.

Do a search for "enthalpy reference state" in this github website and you will find a lot of information on this, here's a link to make this easy:
https://github.com/usnistgov/REFPROP-wrappers/issues?page=2&q=enthalpy+reference+state

First, take a look at the ones with the "documentation" label, they will give the most information.

Hope this helps!

**Comment by rarnold787** [comment]
Thank you to you both, I've read the documents and think I understand what's going on. But for my own sanity, I'm going to explain what I think I read, and please correct me if I'm wrong. Knuckle draggers like me should have paid a little more attention in thermo class so it seems. :\

So, the reference state of enthalpy, entropy, etc. is akin to a starting position of an elevator on the ground floor vs floor 10, and if the elevator moves 20 stories the elevators will end on floors 20 and 30 respectively, but the total change of floors remains the same, right? If this is true, my model will still be valid no matter what the enthalpies of the stations of the cycle are as long as they reference the same reference state, correct?

I have no plans to go mucking around the VBA code and breaking things I shouldn't be, and if this is the case I see no point in modifying anything beneath the surface.

Thanks in advance!

**Comment by EricLemmon** [comment]
As long as you are only concerned about enthalpy and entropy differences between two statements, then that is correct.  Although your analogy would be more correct if you imagine the elevator first moving up 20 floors, and then moving over 15 doors, or something like that to make it 3-D.

If all is good, could you close this issue?  (Or whenever you feel that all is cleared up.)
