### ISSUE TITLE
Reference Point IIR Excel Refprop Version 10.0

### ISSUE THREAD

**Issue by Yannikzahrt** [usnistgov/REFPROP-wrappers#311]
I would like to know how to change the reference point from Refprop Version 10.0 at Excel to IIR. Every explanation of the help system in Refprop itself does not led to success. Could you help me in this case? With Refprop 9.11 it was not a problem at all.
Thank you for your help.

**Comment by EricLemmon** [comment]
Download the latest Refprop.xla file located here to fix a bug or two that sometimes prevents it from working:

https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Excel

Also, see #106

**Comment by Yannikzahrt** [comment]
THank you for your help. But I still don't know how to Change the Reference State to IIR in Excel. THis Explanation did not helped me to solve this Problem. At Version 9.11 I just had to Change a value in the VB Code module 1. This does not exist like that in Version 10.0. The help System in Refprop itselfs is not updated.

**Comment by EricLemmon** [comment]
Hum, looks like I sent you to the wrong issue, take a look at #191.  Just change hOut = "NBP" to hOut = "IIR"

**Comment by Yannikzahrt** [comment]
I changed the VB Code to this:
![2020-07-06 09_14_02-Window](https://user-images.githubusercontent.com/67783439/86565977-1ef40000-bf69-11ea-8a29-efffb8665128.jpg)
But still not working, What am I doing wrong?

**Comment by EricLemmon** [comment]
Could be a couple of things:

1 - Exit Excel and start again.  That part of the code is only run once at start up.
2 - Uncomment the lines that start with hFld="Propane" and the one below it.
3 - Be sure you have downloaded the latest files from our website for the XLS or XLA.
4 - If you are using the XLA, make sure it is saved before exiting Excel.  When your restart Excel, check the code and make sure your changes are still there.

**Comment by ianhbell** [comment]
You need to uncomment the last line from your screenshot.  The hOut string is passed into the call to REFPROPdll in the following line.

**Comment by Yannikzahrt** [comment]
Thanky, i already solved the Problem yesterday!
