### ISSUE TITLE
Error to calculate mixtures

### ISSUE THREAD

**Issue by ayunurizza** [usnistgov/REFPROP-wrappers#312]
Hello, 
I have been using REFPROP 10 in matlab without python and using the previous interface (refprop.m). Exactly, it was working well in pure fluid. But, there were different results between REFPROP interface and REFPROP linking to matlab in defined mixtures. 

### Steps to Reproduce

REFPROP interface
![image](https://user-images.githubusercontent.com/67949994/86807345-fa507300-c0a3-11ea-8188-44c90230616a.png)

REFPROP linking to matlab
![image](https://user-images.githubusercontent.com/67949994/86807403-0c321600-c0a4-11ea-8c11-3d3396a134e2.png)

**Actual behavior:**
The value of critical pressure was different between two method. from the matlab was 4.59 MPa and the refprop interface was 3.89 MPa. 

I suspected that maybe there was wrong in the mixing rule parameter. Because binary interaction parameters are not available for the mixtures and alternatives mixing rule from similar substance have been used.  If that's true, what should I do to solve this problem? 

It would mean a lot to me if you can help me and i really appreciate it. 
Thank you.

### Versions

**REFPROP Version:** REFPROP 10 
**Operating System and Version:** Microsoft Windows Home 10
**Access Method:** Matlab (Refprop.m)

**Comment by ianhbell** [comment]
Please upgrade to the new interface (lots of new functionalities).  The refpropm one is no longer supported.

There are a few different ways that critical pressures can be obtained.  The refpropm interface calls the ``CRITPdll`` function to obtain the critical point: https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/MATLAB/legacy/refpropm.m#L395 .  More information on that function is here: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/CRITPdll .

**Comment by ayunurizza** [comment]
Thank you for the response. I've already upgrade the new interface of REFPROP linking to MATLAB.  But the value of the critical pressure is still different. 

**input**
![image](https://user-images.githubusercontent.com/67949994/86913709-3853a280-c149-11ea-83cf-ab57cf04076c.png)
 **output**
![image](https://user-images.githubusercontent.com/67949994/86913747-44d7fb00-c149-11ea-91f3-ab18e8ede96b.png)

the value is 3.73 MPa, but in REFPROP interface is around 3.8 MPa. And I tried in many times with the same code, but i found the different results too, like around 4.3 MPa. Is it just an error or there is something wrong with my instruction?
And I want to ask about the legacy in matlab. What should I use between the legacy API or High level API? 

Thank you
**Versions**
**REFPROP Version:** REFPROP 10
**Operating System and Version:** Microsoft Windows Home 10
**Access Method:** Matlab in Python

**Comment by ianhbell** [comment]
Some notes:

1. The ``pip install`` command is only needed once, and it is stored on your system and need not be run again
2. I'm going to do the same example in Python to confirm your results and that I can get the GUI result.  Watch this space.

**Comment by ianhbell** [comment]
Also, please post code snippets as text, inside triple backticks (as in the template), it is easier for us to work with for debugging.

**Comment by ayunurizza** [comment]
clear all;
close all;
clc;

% Call REFPROP in matlab
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')
MASS_SI = RP.GETENUMdll(int8(0),'MASS SI').iEnum; %Unit System: Mass SI

%Condition
hFld = 'R1234ZEZ; CYCLOPEN';
P=RP.REFPROPdll(hFld,' ','PC',MASS_SI,int8(1),int8(1),int8(1),int8(1),[0.8,0.2]);
P_in = double (P.Output);
P_in(1)

**Comment by ayunurizza** [comment]
okay this is the command

`clear all;
close all;
clc;

% Call REFPROP in matlab
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')
MASS_SI = RP.GETENUMdll(int8(0),'MASS SI').iEnum; %Unit System: Mass SI

%Condition
hFld = 'R1234ZEZ; CYCLOPEN';
P=RP.REFPROPdll(hFld,' ','PC',MASS_SI,int8(1),int8(1),int8(1),int8(1),[0.8,0.2]);
P_in = double (P.Output);
P_in(1)`

**Comment by ianhbell** [comment]
In Python, you get two different values depending on whether iFlag is zero or 1, which is to be expected.  As the warning notes, I wouldn't trust the value with iFlag=0.

```python
import os, numpy as np

from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
os.environ['RPPREFIX'] = r'D:\Program Files (x86)\REFPROP'
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
print('version:', RP.RPVersion())

hFLD = 'R1234zeZ; CYCLOPEN'

print('iFlag Pc err')
print('============')
for iFlag in [0,1]:
    r = RP.REFPROPdll(hFLD, "", "PC", RP.MASS_SI, 1, iFlag,-1,-1, [0.8, 0.2])
    print(iFlag, r.Output[0], r.herr)
```
yields
```
version: 10.0077
iFlag Pc err
============
0 4.3385475912933975 [CRTHMX error or warning 313] Coefficients are not available for critical line calculations (which generally occurs for binary mixtures that are not in the HMX.BNC, or for beta versions of the program where the critical lines have not yet been fitted).
1 3.7316707528539257 
```

**Comment by ianhbell** [comment]
Does this clear things up?

**Comment by ayunurizza** [comment]
So in REFPROP interface the value is wrong? or it just an error of the iteration?

**Comment by ianhbell** [comment]
I think we have still another bug in REFPROPdll function.  It seems that the composition vector is always treated as being molar composition, even if iMass is 1. Bug reported here: https://github.com/usnistgov/REFPROP-issues/issues/311

**Comment by ianhbell** [comment]
Long story short: always use molar compositions

**Comment by ayunurizza** [comment]
oh i see, okay thank you for the response. maybe i will watch out the issue continously, if there will be any solution.
