### ISSUE TITLE
Updating with Patch for Refprop 10

### ISSUE THREAD

**Issue by zenasc** [usnistgov/REFPROP-wrappers#316]
Hello,

I received the patch files but will need clarification on how to update with the files. The only instructions I found were in [#223](https://github.com/usnistgov/REFPROP-wrappers/issues/223) but only mentioned to copy new files to the REFPROP directory and update the ctREFPROP.

What I've done:
### Steps to Reproduce

1. Copy REFPROP.DLL and REFPRP64.DLL to /opt/REFPROP-cmake/build/
2. Unzip 10-00-02.zip to /opt/REFPROP-cmake/fortran/ (overwriting files)

In Matlab:

```
>> pyversion

       version: '3.7'
    executable: '/opt/anaconda3/bin/python'
       library: '/opt/anaconda3/lib/libpython3.7m.so'
          home: '/opt/anaconda3'
      isloaded: 0

>> [v,e] = pyversion; system([e,' -m pip install --user -U /opt/ctREFPROP-0.8.2-py3-none-any.whl'])
Processing /opt/ctREFPROP-0.8.2-py3-none-any.whl
[31mtwisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.[0m
Installing collected packages: ctREFPROP
Successfully installed ctREFPROP-0.8.2

ans =

     0

>> RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('/opt/REFPROP-cmake/build')

RP = 

  Python REFPROPInstance with properties:

           MASS_SI: [1x1 py.int]
               CGS: [1x1 py.int]
           MOLE_SI: [1x1 py.int]
     MOLAR_ENGLISH: [1x1 py.int]
               MKS: [1x1 py.int]
               dll: [1x1 py.ctypes.CDLL]
         SI_WITH_C: [1x1 py.int]
     MOLAR_BASE_SI: [1x1 py.int]
    managed_handle: [1x1 py.NoneType]
      MASS_BASE_SI: [1x1 py.int]
           DEFAULT: [1x1 py.int]
           ENGLISH: [1x1 py.int]
             MIXED: [1x1 py.int]
           MEUNITS: [1x1 py.int]

    <ctREFPROP.ctREFPROP.REFPROPInstance object at 0x7f29a13a2a20>

>> RP.RPVersion()

ans = 

  Python str with no properties.

    ******

>> MOLSI = RP.GETENUMdll(int8(0),'MOLAR BASE SI').iEnum;
>> iMass = int8(0); % 0: molar fractions; 1: mass fractions
>> iFlag = int8(0); % 0; don't call SATSPLN; 1: call SATSPLN
>> z = {1.0};
>> r = RP.REFPROPdll('Water','PQ','T',iMass,iFlag,101325,0.0,z)
No appropriate method, property, or field 'REFPROPdll' for class
'py.ctREFPROP.ctREFPROP.REFPROPInstance'.
```

**Expected behavior:** Running RP.RPVersion() in Matlab will display 10 and yield an answer for ```r = RP.REFPROPdll('Water','PQ','T',iMass,iFlag,101325,0.0,z)```

**Actual behavior:** Running RP.RPVersion() in Matlab still displays ****** and receiving ```No appropriate method, property, or field 'REFPROPdll' for class
'py.ctREFPROP.ctREFPROP.REFPROPInstance'.``` when running ```r = RP.REFPROPdll('Water','PQ','T',iMass,iFlag,101325,0.0,z)```

System info:
**REFPROP Version:** 10
**Operating System and Version:** SuSE Linux 12.3 
**Access Method:** Python 3.7, Matlab 2015

**Comment by ianhbell** [comment]
You need to rebuild the .so with the FORTRAN files in the zip file and overwrite the existing .so.  Build system is here: https://github.com/usnistgov/REFPROP-cmake

**Comment by zenasc** [comment]
Thank you for the instructions! It showed:

RP.RPVersion()

ans = 

    Python str with no properties.
 
        10.0002
