### ISSUE TITLE
TRNPRP error 74

### ISSUE THREAD

**Issue by zenasc** [usnistgov/REFPROP-wrappers#317]
Hello!

Is there a way we can yield results with this:

```
refpropm('V<','T',[49],'P',[0.01],'NITROGEN')
Error using refpropm (line 546)
[TRNPRP error 74] Inputs to the viscosity and thermal conductivity correlations are out of range.
Temperature below triple-point or minimum temperature: T = 49.0000 K, Tmin = 50.0000 K.
```

### Description

It will not yield results when T is below 50 and P is above 0.

### Versions

**REFPROP Version:** 10
**Operating System and Version:** SuSE Linux 12.3
**Access Method:** Python 3.7, Matlab 2015

**Comment by EricLemmon** [comment]
The state point you entered is in the solid phase (the triple point is 62.2 K).  Is 42 K really the temperature you wanted, or perhaps you wanted C instead?

**Comment by zenasc** [comment]
We need to calculate viscosity for gaseous Nitrogen for temperature range between 20 and 35 deg Kelvin, for pressures between 10 to 50 Pascals.
Refprop only gives an answer below 50 K if pressure is set to zero. Anything above zero gives an error.

**Comment by EricLemmon** [comment]
Now I understand, I thought you were looking for liquid phase properties.  Both viscosity and thermal conductivity have some extremely strange behavior as the pressure goes to zero that our equations do not account for.  That is why you will always find publications refer to the "dilute gas viscosity" instead of "ideal gas viscosity".  Are you aware of this, and if so, is this the property value you need?  If not, at the pressures you are requesting, the viscosity will not be any different from that at the values obtained from our dilute gas equations.

**Comment by ianhbell** [comment]
If you really mean 50 Pa, that's a very, very low pressure, and the dilute viscosity is going to give you what you need to an excellent approximation. There are now accurate ab initio calculations down to 70 K for nitrogen (see for instance http://dx.doi.org/10.1021/acs.jced.9b00455), but one caution I would have is that you are outside the range of validity of the model in REFPROP, and some of the dilute gas correlations are not well-behaved at all outside their range of validity.

Also, please migrate to the Python-based interface, at some point we will probably remove the ``refpropm`` interface.

**Comment by nist-aharvey** [comment]
To add to what Eric said, for such low pressures you should make sure you are still in the regime where viscosity is a meaningful concept.  If the gas is so dilute that the mean free path is similar to the length scale of your system (like the width of tubing), then the normal fluid flow equations with viscosity won't apply.  You would need to consult specialized information on "Knudsen flow" or "Knudsen diffusion" in that case.
I don't have a good feel for this regime, but I think 50 Pa is probably still enough to be in the normal flow regime in most cases, as long as you are not talking about flow in micrometer or smaller length scales.  There is something called the "Knudsen number" that can be calculated to see if you are in that regime.

As Ian mentioned, the viscosity at 50 Pa should be essentially identical to that in the zero-density limit.
And you should plot viscosity(T) at zero pressure going from, say, 100 K down to your temperatures to be sure the correlation is not doing anything strange when extrapolated to temperatures below the range where it was fit.  The low-density viscosity should be approximately proportional to the square root of the absolute temperature.

**Comment by ianhbell** [comment]
One way to check the "strangeness" of extrapolation is to consider the effective hardness coming from the dilute-gas formulation at lower temperatures: https://aip.scitation.org/doi/full/10.1063/5.0007583

**Comment by zenasc** [comment]
Gentlemen,

Thank you for your informative responses. I've forwarded them to our analysts and will reply to this thread with their feedback.

**Comment by EricLemmon** [comment]
Has this issue been resolved yet?
