### ISSUE TITLE
Critical Pressure Error in Mixture (Legacy API)

### ISSUE THREAD

**Issue by Debranjan-Das** [usnistgov/REFPROP-wrappers#318]
```import os; os.environ['RPPREFIX'] = r'C:\Program Files\REFPROP\REFPRP64.DLL'
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])

def val_crit(F,z):
    r = RP.SETUPdll(1,F,"HMX.BNC", "DEF")
    assert (r.ierr == 0)
    return ((RP.CRITPdll(z)).Pc)

Mix = 'PROPANE.FLD|CO2.FLD'
PC1=val_crit(Mix,[0.1,0.9])
PC2=val_crit(Mix,[0.2,0.8])
PC3=val_crit(Mix,[0.3,0.7])
PC4=val_crit(Mix,[0.4,0.6])
PC5=val_crit(Mix,[0.5,0.5])

print(PC1,PC2,PC3,PC4,PC5)
```

### Description

I am trying to get the critical pressure of the mixture of propane and carbon dioxide for difference molar concentrations. Unlike the values in the Refprop fluid information window the value of critical pressure for all the molar concentration are the same.

### Steps to Reproduce

1. Check whether the subroutine fits the purpose
2. Obtaining correct value of critical pressure

**Expected behavior:** At different molar concentration varied value of critical pressure is expected.

**Actual behavior:** At any molar concentration the value of critical pressure is constant at 4251.2 kPa.

### Versions

**REFPROP Version:** 9.1
**Operating System and Version:** Windows 8.1
**Access Method:** Python (Spyder) 

### Additional Information

Python Script:

![image](https://user-images.githubusercontent.com/68718528/88353987-1e0eec80-cd25-11ea-8825-c961743aca23.png)

Output:

![image](https://user-images.githubusercontent.com/68718528/88354045-44348c80-cd25-11ea-9bb9-3548dcff1c91.png)

**Comment by ianhbell** [comment]
REFPROP 9.1 didn't warn you, but you passed in two components, but set icomp to 1 in your call to SETUPdll.  Fixed code with REFPROP 10:
``` python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])

def val_crit(F,z):
    r = RP.SETUPdll(2,F,"HMX.BNC", "DEF")
    print(r.herr)
    assert (r.ierr == 0)
    return ((RP.CRITPdll(z)).Pc)

Mix = 'PROPANE.FLD|CO2.FLD'
PC1=val_crit(Mix,[0.1,0.9])
PC2=val_crit(Mix,[0.2,0.8])
PC3=val_crit(Mix,[0.3,0.7])
PC4=val_crit(Mix,[0.4,0.6])
PC5=val_crit(Mix,[0.5,0.5])

print(PC1,PC2,PC3,PC4,PC5)
```
yields
```





6909.544413206034 6766.990837073305 6807.4329590114 6875.1591626065565 6820.00670408811
```

**Comment by Debranjan-Das** [comment]
Thank you.
