### ISSUE TITLE
Density/Quality data when using ">" suffix

### ISSUE THREAD

**Issue by Tuckabag** [usnistgov/REFPROP-wrappers#319]
### Description

Where we have a 2-phase convergence error when calculating density with "TP", I then use "TP>" or "TP<" to provide an output.
If Qmass is > approx 0.5 we get density data that seems to correlate with the density from the std "TP" calls either side of it.  
However if Qmass is <0.5 then the returned density figure is too high.

### Steps to Reproduce

Code to reproduce the error :

1. Dens = Run(REFPR, "D", Fluid, "TP", "C", TempVari, Pressure / 1000)
    If IsNumeric(Dens) = False Then Dens = Run(REFPR, "D", Fluid, "TP>", "C", TempVari, Pressure / 1000)

2. The composition for the below screenshots is as follows.

Methane;Ethane;Propane;Butane;Pentane;Hexane;Heptane;Octane;Nonane;Decane;Undecane;Dodecane\|.819426401518937;8.79384430898371E-02;.049965024482862;.024982512241431;1.49895073448586E-02;9.9930048965724E-04;7.4947536724293E-04;4.9965024482862E-04;2.4982512241431E-04;9.9930048965724E-05;4.9965024482862E-05;4.9965024482862E-05
--

**Expected behavior:** I expect the returned figure to fall in line with the density figures that are performed before/after the "TP>" call.

**Actual behavior:** the returned figure when using "TP>" call is high when Qmass is <0.5.

### Versions

**REFPROP Version:** REFPROP 10
**Operating System and Version:** Win10 Pro x64.
**Access Method:** EXCEL 365 MSO 32 bit (build 16.0.13001.20266)

### Additional Information

Screenshots of results.
The screenshot below shows density data in red that the "TP>" call is returning when qmass <0.5.
![screenshot1](https://user-images.githubusercontent.com/66595828/88119401-aeeda700-cc03-11ea-9d4e-5efa158f9f3d.jpg)

This screenshot shows density data in red that the "TP>" call is retuning when qmass >0.5.  these figures look much more inline with what we expect to see.
![screenshot](https://user-images.githubusercontent.com/66595828/88119331-7ea60880-cc03-11ea-924b-9aecf11a015b.jpg)

Any thoughts on why the returned density data is ok at higher quality?

**Comment by EricLemmon** [comment]
Also, are you calling the SATSPLN routine after you setup your mixture?  You can see how Ian did it in his code.  

https://github.com/usnistgov/REFPROP-wrappers/issues/106 has additional information on this.

**Comment by Tuckabag** [comment]
> Also, are you calling the SATSPLN routine after you setup your mixture? You can see how Ian did it in his code.
> 
> #106 has additional information on this.

Yes, we have removed the apostrophe from the iFlag call in the .xla file.


> Here's some information about spinodals and metastable states that might help: [usnistgov/REFPROP-issues#180](https://github.com/usnistgov/REFPROP-issues/issues/180)

Thank you, I'll have a look through and see if this helps make things clearer for me.  I can see where you are coming from with regards to not using "intuitive" methods with mixtures.  I am modifying my approach to this.

One other quick question I have regarding the use of </>, I have also been trying to use them when creating a dew/bubble point phase envelope for hydrocarbon mixtures as a fallback when refprop can't converge the data for a particular density point using a standard TP call.  This is using the density stepping approach.  The data always seems to correlate nicely, I don't recall seeing any weird numbers when using this approach.  Is this a valid use of the </> suffixes?

**Comment by EricLemmon** [comment]
Do a search in this issues repository for "SATGV" and take a look at the issues that pop up.  This might give you an idea about why density searching works better, and possibly a way for you to calculate saturation states better.

https://github.com/usnistgov/REFPROP-wrappers/issues?q=satgv

**Comment by Tuckabag** [comment]
Thanks for the feedback above.
I've modified how we go about things now.

I use TP for calling density and if this fails and we specifically need data at this point we then interpolate between the last good density figure either side by temp stepping.  Not ideal, but gets us as close as we can get using REFPROP.
We then use TD or if that fails TP calls to get the quality data.  Should both methods fail, we flag an error in the results.
This method seems fairly robust, however we do have some issues with convergence around the critical point, any pointers on how we can reduce these convergence issues?
For reference, currently we are looking at data for hydrocarbon mixtures at constant P, traversing the two-phase envelope as we apply heat.  See below screenshot.
![screenshot](https://user-images.githubusercontent.com/66595828/89123253-57a7da80-d511-11ea-9b19-8e7fb79698d5.JPG)

**Comment by EricLemmon** [comment]
Are you able get Refprop to send back the entire saturation line now?  Your plot shows it being complete, are all those points coming back from the DLL?

**Comment by Tuckabag** [comment]
> Are you able get Refprop to send back the entire saturation line now? Your plot shows it being complete, are all those points coming back from the DLL?

Yes, I am able to get the full saturation line from REFPROP through Excel.
I start @ Critical Point, then density step down for bubble points and density step up for dew points.
I call TSAT using DSAT as the entry and then P using TSAT and DSAT..  If the std TP/TD calls fail, my code then tries to get the metastable data point, and if that fails, it just leaves the cells empty so when I collect the data for the chart Excel simply plots the gap.

As per my last post, we do see some issues sometimes around the critical point, particularly when the mixture has more heavy HC's present.

**Comment by EricLemmon** [comment]
I think we need to talk via phone or some other device about this.  Answering questions one at a time each day or so that it takes to get an answer simply is going to work here.  Could you send me an email at eric.lemmon@nist.gov?  When we get it worked out, you should post a final answer as to the solution we come up with so that others will benefit.

**Comment by EricLemmon** [comment]
I don't remember if I heard back or if we fixed this problem (too many Refprop issues causing brain overload).  Has this issue been resolved and if not can we still help?
