### ISSUE TITLE
REFPROP Convergence problem - High temp, high water content combustion products 

### ISSUE THREAD

**Issue by aquasweep** [usnistgov/REFPROP-wrappers#320]
REFPROP does not seem to converge property calculations (such as enthalpy or entropy given pressure and temperature) in high-temperature, single phase ranges. 
This happens with relatively high water content but counter intuitively it works in lower temperature ranges closer to saturation
Error message indicates two phase iteration problem. 
This seems very odd since the convergence problem only occurs when temperature is an input. 
Inverse calculation such as temperature from pressure and enthalpy works fine.
Example:
Combustion products with relatively high water content
Composition:             D$8:=  Nitrogen;Argon;CO2;SO2;Water\|.7;.0083;.0973;0;.1944
Function:                    REFPROP("H",D$8,"PT","e",14.69,2700)
Result                         #[TPFL2 error 226] 2-phase iteration did   not converge.
[Refprop convergence.xlsx](https://github.com/usnistgov/REFPROP-issues/files/4878748/Refprop.convergence.xlsx)

**Comment by EricLemmon** [comment]
Can you send Ian or me a personal email (ian.bell@nist.gov or eric.lemmon@nist.gov)?  This seems to be fixed, I just tried it here with the code below.  We'll send you the current beta version for you to try.

      i=iGetEnum(0,'english')
      hfl='Nitrogen;Argon;CO2;SO2;Water|.7;.0083;.0973;0;.1944'
      call REFPROP(hfl,'  ',' ',i,0,0,2700d0,14.69d0,z,
     &      Ou,u,iU,x,y,x3,q,ierr,herr)
      call REFPROP(' ','PT','H',i,0,1,2700d0,14.69d0,z,
     &      Ou,u,iU,x,y,x3,q,ierr,herr)

**Comment by aquasweep** [comment]
Version 10.0.0.78 resolved the issue... thank you
