### ISSUE TITLE
Cant install ctREFPROP

### ISSUE THREAD

**Issue by Railnolds** [usnistgov/REFPROP-wrappers#321]
Hi.
I tried to use the Refprop 10 with Matlab. I used the tutorial from this link - https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB
I use the latest version of Pyton 3.8.5.

When I tried to install ctREFPROP I got problem. When I use command **[v,e] = pyversion; system([e,' -m pip install --user -U ctREFPROP'])** I got the message from Matlab **"C: \ Program" is not internal or external command, executable program, or batch file.** The same ansver for command **[v,e] = pyversion; system([e,' -m easy_install pip'])**

How to install ctREFPROP in tnis situation?
Thanks.

**Comment by ianhbell** [comment]
Hmm, this is a new one for me.  What is the output of ``pyversion``?

**Comment by Railnolds** [comment]
Hi. It looks like Pyton was found OK

    version: '3.8'
    executable: 'C:\Program Files\Python38\python.exe'
    library: 'C:\Program Files\Python38\python38.dll'
    home: 'C:\Program Files\Python38'
    isloaded: 0

**Comment by ianhbell** [comment]
and then what is e when you execute ``[v,e] = pyversion``?

**Comment by Railnolds** [comment]
v =    '3.8'

e =    'C:\Program Files\Python38\python.exe'

**Comment by ianhbell** [comment]
Perhaps the issue is the space in the path, but I know it wasn't an issue for me when I did this before.

**Comment by ianhbell** [comment]
What if you add quotes around e in the call to system?

**Comment by Railnolds** [comment]
But Program files is the standart path for the Windows programs.
Maybe I should reinstall Pyton to the folder without space in the name? Like C:\Pyton.

**Comment by Railnolds** [comment]
>> [v,e] = pyversion; 'system([e,' -m easy_install pip'])'
 [v,e] = pyversion; 'system([e,' -m easy_install pip'])'
                                    ↑
Error: Invalid expression. Check for missing multiplication operator, missing or unbalanced delimiters, or other syntax error. To
construct matrices, use brackets instead of parentheses.
 
>> [v,e] = pyversion; system'([e,' -m easy_install pip'])'
 [v,e] = pyversion; system'([e,' -m easy_install pip'])'
                           ↑
Error: Invalid expression. When calling a function or indexing a variable, use parentheses. Otherwise, check for mismatched
delimiters.

**Comment by ianhbell** [comment]
I have in mind ``system(['"', e, '" -m easy_install pip'])``

**Comment by ianhbell** [comment]
That will wrap the path in double-quotes

**Comment by Railnolds** [comment]
Now I get next

[v,e] = pyversion; system(['"', e, '" -m easy_install pip'])
WARNING: The easy_install command is deprecated and will be removed in a future version. 
Searching for pip 
Best match: pip 20.1.1 
Adding pip 20.1.1 to easy-install.pth file 
Installing pip-script.py script to C:\Program Files\Python38\Scripts 
Installing pip.exe script to C:\Program Files\Python38\Scripts 
Installing pip3-script.py script to C:\Program Files\Python38\Scripts 
Installing pip3.exe script to C:\Program Files\Python38\Scripts 
Installing pip3.8-script.py script to C:\Program Files\Python38\Scripts 
Installing pip3.8.exe script to C:\Program Files\Python38\Scripts 
 
Using c:\program files\python38\lib\site-packages 
Processing dependencies for pip 
Finished processing dependencies for pip 

ans =

     0

**Comment by ianhbell** [comment]
Great - now do the same thing with ctREFPROP.  I'll add a note to the README; there should be no harm with adding the quotes in general.  Wonder what changed in MATLAB...

**Comment by Railnolds** [comment]
Now I get the error when I try to use Refprop in my M file

Unable to resolve the name py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary.

Error in New_ERM_without_RHE (line 11)
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');

**Comment by ianhbell** [comment]
What version of MATLAB do you use?

**Comment by ianhbell** [comment]
Did Mathworks change anything regarding Python support?  Do they perhaps not support Python 3.8?

**Comment by Railnolds** [comment]
R2020a 64x.

I have the same version of Matlab on another PC, and there all is working correct.

**Comment by ianhbell** [comment]
That's super weird.

**Comment by Railnolds** [comment]
On the problem PC te Pyton is 3.8.5.

**Comment by ianhbell** [comment]
Does ctREFPROP work properly inside your Python?  Open a shell, run python to start, and then do:

``from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary; REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP') ``

**Comment by Railnolds** [comment]
Doesnt work

>>> from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary; REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ctREFPROP'

**Comment by ianhbell** [comment]
Do you have multiple Python versions on your computer then somehow?  Can you try to use this one:

``"C:\Program Files\Python38\python.exe" -m pip install ctREFPROP``

and then use that same executable to do

``"C:\Program Files\Python38\python.exe" -c "from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary; REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')"``

**Comment by Railnolds** [comment]
I installed ctREFPROP from windows command promt and update PIP

```
C:\Program Files\Python38>python.exe -m pip install ctREFPROP
Collecting ctREFPROP
Downloading ctREFPROP-0.8.2-py3-none-any.whl (19 kB)
Installing collected packages: ctREFPROP
Successfully installed ctREFPROP-0.8.2
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the 'C:\Program Files\Python38\python.exe -m pip install --upgrade pip' command.

C:\Program Files\Python38>python.exe -m pip install --upgrade pip
Collecting pip
Downloading pip-20.2.2-py2.py3-none-any.whl (1.5 MB)
|████████████████████████████████| 1.5 MB 939 kB/s
Installing collected packages: pip
Attempting uninstall: pip
Found existing installation: pip 20.1.1
Uninstalling pip-20.1.1:
Successfully uninstalled pip-20.1.1
Successfully installed pip-20.2.2
```


Now it looks like all is OK!!!! I have not got the error message and in Matlab got this:

```
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')

RP = 

  Python REFPROPInstance with properties:

ENGLISH: [1×1 py.int]
MASS_BASE_SI: [1×1 py.int]
MASS_SI: [1×1 py.int]
MOLAR_BASE_SI: [1×1 py.int]
managed_handle: [1×1 py.NoneType]
MKS: [1×1 py.int]
SI_WITH_C: [1×1 py.int]
MEUNITS: [1×1 py.int]
MIXED: [1×1 py.int]
MOLAR_ENGLISH: [1×1 py.int]
DEFAULT: [1×1 py.int]
CGS: [1×1 py.int]
MOLE_SI: [1×1 py.int]
dll: [1×1 py.ctypes.WinDLL]

<ctREFPROP.ctREFPROP.REFPROPInstance object at 0x000001C31A14BF70>
```

**Comment by ianhbell** [comment]
Woohoo!  I think you are in business.  I can't explain why it didn't work before...

**Comment by Railnolds** [comment]
Thanks alot for your help!!!!!!

**Comment by ianhbell** [comment]
That's my job :)
