### ISSUE TITLE
DOI link goes to Version 9

### ISSUE THREAD

**Issue by Yaykhel** [usnistgov/REFPROP-wrappers#323]
# Description

Need to update the DOI of REFPROP 10

Lately, we were commented that the DOI we used goes to REFPROP 9 and we also confirmed that. The DOI is given in REFPROP 10 manual and "https://refprop-docs.readthedocs.io/en/latest/GUI/Menu%20Commands/Help%20Menu/cite_refprop.html".

### Steps to Reproduce

Click DOI link the manual or go to "http://dx.doi.org/10.18434/T4JS3C".

**Expected behavior:**
Well, it should at least state the version we bought to use.

**Actual behavior:** 
Goes to the old version

### Versions

**REFPROP Version:**
10
**Operating System and Version:** 
Windows 10 
**Access Method:**
C++, Python, Mathematica via CoolProp, Excel, VBA 

### Additional Information

None

**Comment by ianhbell** [comment]
Thanks for the report, now fixed.
