### ISSUE TITLE
Issue calling REFPROP from Matlab

### ISSUE THREAD

**Issue by RinaldoMiorini** [usnistgov/REFPROP-wrappers#324]
Hello! Issue calling REFPROP from Matlab. Thanks for your help!

***
Running
REFPROP 10.0
Matlab R2019a
on WIN10 64bit

REFROP is in c:/Program Files (x386)/REFPROP

Installation folder includes:
REFPROP.h
REFPRP64.DLL (renamed REFPRP64.DLL.OLD, to avoid conflict with:)
REFPRP64_thunk_pcwin64.dll
rp_proto64.m

I move the working folder in Matlab to 'C:\Program Files (x86)\REFPROP'

I type in Matlab's Command:

refpropm('T','P',101.325,'Q',0,'WATER')

I get:

Error using loadlibrary
Too many input arguments.
Error in ==>@()rp_proto64(BasePath) at 211
There was an error running C:\Program Files (x86)\REFPROP\refpropm.m.
Run @()rp_proto64(BasePath) from the command line to reproduce the error and fix
it.

Error in refpropm (line 227)
    [notfound,warnings]=loadlibrary(strcat(BasePath,dllName),prototype,'alias',libName);

Caused by:
    Error using rp_proto64
    Too many input arguments.

I type in the Command window:

>> @()rp_proto64('C:/Program Files (x86)/REFPROP/)

I get:

 @()rp_proto64('C:/Program Files (x86)/REFPROP/)
               ↑
Error: Character vector is not terminated properly.
***

**Comment by ianhbell** [comment]
The refpropm interface is deprecated and will be removed at some point.  Please migrate to the Python-based one.

**Comment by RinaldoMiorini** [comment]
Thanks. Just tried. Everything ok in Anaconda, continuing on Matlab, I get this:

---
>> pyversion

       version: '3.7'
    executable: 'C:\Users\212350863\AppData\Local\Continuum\Anaconda3dot7\python.exe'
       library: 'C:\Users\212350863\AppData\Local\Continuum\Anaconda3dot7\python37.dll'
          home: 'C:\Users\212350863\AppData\Local\Continuum\Anaconda3dot7'
      isloaded: 1
---
--- 
>> [v,e] = pyversion; system(['"', e, '" -m pip install --user -U ctREFPROP'])
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. 
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Could not fetch URL https://pypi.org/simple/ctrefprop/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ctrefprop/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping 
Requirement already up-to-date: ctREFPROP in c:\users\212350863\appdata\local\continuum\anaconda3dot7\lib\site-packages (0.7.3) 
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. 
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping 

ans =

     0
---
---

>> RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')

RP = 

  Python REFPROPInstance with properties:

               dll: [1×1 py.ctypes.WinDLL]
    managed_handle: [1×1 py.NoneType]

    <ctREFPROP.ctREFPROP.REFPROPInstance object at 0x0000000004AFD5C0>
---
---
>> RP.RPVersion()
Error using ctREFPROP>RPVersion (line 2537)
Python Error: ValueError: The function
RPVersion could not be loaded from the
shared library.
---

**Comment by ianhbell** [comment]
Interesting! It looks like the wrapper was installed, it was loaded properly, but yet somehow RPVersion function didn't load properly.  

But I see the issue: renaming the DLL was the problem, please rename it back. Then you can move the thunk files somewhere else (they are not needed for the Python interface).

**Comment by RinaldoMiorini** [comment]
Thanks! I renamed the file back to 'REFPRP64.DLL' and moved 'REFPRP64_thunk_pcwin64.dll' to the thrash.

I restarted following the instructions from here:

***
>> [v,e] = pyversion; system(['"', e, '" -m pip install --user -U ctREFPROP'])
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. 
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
Could not fetch URL https://pypi.org/simple/ctrefprop/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ctrefprop/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping 
Requirement already up-to-date: ctREFPROP in c:\users\212350863\appdata\local\continuum\anaconda3dot7\lib\site-packages (0.7.3) 
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. 
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping 

ans =

     0
***

Matlab's reply above does not sound great to me, but I am not an expert, continuing:

***
>> RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')

RP = 

  Python REFPROPInstance with properties:

               dll: [1×1 py.ctypes.WinDLL]
    managed_handle: [1×1 py.NoneType]

    <ctREFPROP.ctREFPROP.REFPROPInstance object at 0x0000000004A1C4E0>
***
***
>> RP.RPVersion()

ans = 

  Python str with no properties.

    9.1111
***
I actually have REFPROP DLL Version 10.0 [!]

***
>> MOLSI = RP.GETENUMdll(int8(0),'MOLAR BASE SI').iEnum;
iMass = int8(0); % 0: molar fractions; 1: mass fractions
iFlag = int8(0); % 0: don't call SATSPLN; 1: call SATSPLN
z = {1.0};
r = RP.REFPROPdll('Water','PQ','T',MOLSI,iMass,iFlag,101325,0.0,z)
Error using ctREFPROP>GETENUMdll (line
1524)
Python Error: ValueError: The function
GETENUMdll could not be loaded from the
shared library.
***

**Comment by ianhbell** [comment]
Well, seems you didn't install REFPROP 10 properly.  At least the DLL you loaded REFPRP64.DLL is that of REFPROP 9.1, not REFPROP 10.0.  Try to run your code from somewhere else (e.g., the desktop).

P.S. You no longer need to install the wrapper, it is installed properly.

**Comment by RinaldoMiorini** [comment]
Gosh! I didn't realize that the REFPRP64.DLL file I downloaded from:
https://trc.nist.gov/refprop/LINKING/Linking.htm

was not for REFPROP 10.0!

Is there a way to get the right file?
I do not have access to the original installation executable to reinstall REFPROP, is there a way to get just REFPRP64.DLL for 10.0?

**Comment by ianhbell** [comment]
You need to upgrade to REFPROP 10 to get REFPROP 10: https://www.nist.gov/srd/refprop

**Comment by RinaldoMiorini** [comment]
I have REFPROP 10.0 installed. I see that when I launch the software, there is a window with information including the DLL version.

The problem is that I overwrote RFPRP64.DLL with the 9.1.1 version I downloaded from the info page on how to link Matlab to REFPROP. I don't want to purchase another copy of REFPROP 10 and I do not have access to the installation executable, the installation of REFPROP 10 was handled by my company.

Is there way to repair my RFPRP64.DLL by overwriting the 10.0 verison?

**Comment by ianhbell** [comment]
Yes, please email me (ian.bell@nist.gov) and I can help.

**Comment by EricLemmon** [comment]
Just a little side note about licensing so that you and others who read this will understand how we deal with this:

https://github.com/usnistgov/REFPROP-issues/issues/227
