### ISSUE TITLE
byref() argument must be a ctypes instance, not 'float'

### ISSUE THREAD

**Issue by osamaaljolani** [usnistgov/REFPROP-wrappers#327]
When I run my script I have the following error:

Error using ctREFPROP>REFPROPdll (line 2500)
Python Error: TypeError: byref() argument must be a ctypes instance, not 'float'

Can anyone help me to solve this problem?

**Comment by ianhbell** [comment]
Please show the call that failed.  We have an issue template for exactly this reason.

**Comment by osamaaljolani** [comment]
`

**Comment by osamaaljolani** [comment]
> Please show the call that failed. We have an issue template for exactly this reason.

Really my MATLAB was working very well but suddenly since some days I have always this problem whatever the code that I write. For example now I have used your example from ''REFPROP for MATLAB'' issue as follows:

`>> MOLSI = RP.GETENUMdll(int8(0),'MOLAR BASE SI').iEnum;
iMass = int8(0); % 0: molar fractions; 1: mass fractions
iFlag = int8(0); % 0: don't call SATSPLN; 1: call SATSPLN
z = {1.0};
r = RP.REFPROPdll('Water','PQ','T',MOLSI,iMass,iFlag,101325,0.0,z)`

And again I had got the same error as the following:

**Error using ctREFPROP>REFPROPdll (line 2500)
Python Error: TypeError: byref() argument must be a ctypes instance, not 'float'**

So it looks like that the connection between my MATLAB and my REFPROP has a problem. What do you think?

**Comment by ianhbell** [comment]
What version of MATLAB do you use?  There have been reports of issues in MATLAB 2020 with the Python interface.  Can you use Python directly?  That should work without any problems, and if there are, should be much easier to debug.

**Comment by osamaaljolani** [comment]
My MATLAB version is R2019a, REFPROP is version 10 and Python is version 3.7. Everything was working in the right way through the last months but now it doesn't work (when MATLAB connects with REFPROP). Actually I am not familiar with Python to use it to solve the problem. Is there links/articles that can help me to read about that?

Thank you for your time!

**Comment by osamaaljolani** [comment]
One more thing, when I go to the line 2500 in the ctREFPROP.py window it is written there:
''The function REFPROPdll could not be loaded from the shared library." 

Does this help to solve the problem?

**Comment by ianhbell** [comment]
Well, the REPROPdll function is only available in REFPROP 10.0, so it makes sense it can't be found :)  Again, this is why we ask people to fill out the template.

Maybe MATLAB does caching internally somehow, so the error manifests in a different way.

**Comment by osamaaljolani** [comment]
I have filled out a template and opened a new issue, so I will close this issue now.
