### ISSUE TITLE
problem of determining 'T' from 'PH'  for subcooled liquid

### ISSUE THREAD

**Issue by atit-sut** [usnistgov/REFPROP-wrappers#329]
I modeled a Rankine-cycle power plant using MATLAB and determined the working fluid's properties by "MATLAB wrapper for REFPROP version 10 using Python".  Its working fluid is water. The predictions are reasonable. 

However, when I discretized the evaporator to examine the process inside the evaporator, I obtained some weird outputs. I calculated the working fluid's temperatures inside using the pressure and enthalpy. The pressure of the working fluid is constant at 3 Mpa. The hot fluid's inlet temperature is  573.15 K. When the enthalpies are between 196.450 to 210.936 kJ/kg and higher than 309.437 kJ/kg, the obtained working fluid's temperatures are reasonably higher than 319 K. However when the enthalpies are between 211.178 to 309.437 kJ/kg, the obtained temperatures are 198 - 199 K. 

I checked this by running REFPROP and using 'Calculate - Specified State Points'. When I fed "p = 3 MPa" and h is between 211.178 to 309.437 kJ/kg. REFPROP returned the message "[PHFLSH error 16] One or more inputs are out of range; Inputs are within the solid phase". However, REFPROP returned "T = 309.99 K" when I inputted "p = 3 MPa and h = 157 kJ/kg".

Is this a bug? How should I fix this?

I also attached the MATLAB codes that I used to calculate this. When I run "det_ORC_discretization_water_27Aug2020.m", I found that weird predictions.

Thank you very much.

Atit
[MATLAB.zip](https://github.com/usnistgov/REFPROP-issues/files/5174926/MATLAB.zip)

**Comment by EricLemmon** [comment]
Have you sent an email to Ian yet?  If not, can you send me one and I'll send you the patch.  I'm at eric.lemmon@nist.gov
