### ISSUE TITLE
REFPROP 9.1 wrapper for Matlab library not loading all functions

### ISSUE THREAD

**Issue by estebanAIRBUS** [usnistgov/REFPROP-wrappers#332]
### Description

The refprop library is not loading all functions into Matlab. Therefore the function calls produce an error (e.g. SETUPdll method not found in refprop library).

### Steps to Reproduce

I followed the procedure described in:
https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB/legacy

Notably, I did the following:
- Placed REFPRP64_thunk_pcwin64.dll, rp_proto64.m, and REFPROP.h in the same directory as the REFPROP installation.
- Verified paths in refpropm.m
- Added folder to Matlab path

**Expected behavior:** [What you expect to happen]

Test refpropm file with something like (the normal boiling point temperature of water at one atmosphere, or 101.325 kPa):

>> refpropm('T','P',101.325,'Q',0,'WATER')

ans =

  373.1243

**Actual behavior:** [What actually happens]
>> refpropm('T','P',101.325,'Q',0,'WATER')
Error using calllib
Method was not found.

Error in refpropm (line 295)
        [nc,~,~,~,ierr,errTxt] =
        calllib(libName,'SETUPdll',numComponents,path,hmix,href,0,herr,10000,255,3,255);

### Versions

**REFPROP Version:** 9.1  
**Operating System and Version:** Windows 10
**Access Method:** Matlab wrapper refpropm.m

### Additional Information
The line with the error is trying to call the function SETUPdll in the refprop library. But this function was not loaded in the library. The screenshot below below shows the list of loaded functions:
![image](https://user-images.githubusercontent.com/72802866/95862814-b8e6f800-0d63-11eb-9a33-514b7c827dba.png)

**Comment by ianhbell** [comment]
That interface (refpropm) is no longer supported.  Please migrate to the Python interface, which also supports REFPROP 9.1.x.  Also recommend to upgrade to REFPROP 10, much more user friendly interface.

**Comment by estebanAIRBUS** [comment]
Hello Ian,
Thank you for the suggestion. But no possibility to upgrade to REFPROP 10 at the moment. And indeed, the unfriendly user interface for the function call in the 9.1 python wrapper were discouraging me from taking that option.

**Comment by ianhbell** [comment]
Then I would recommend you use the CoolProp interface to REFPROP: http://www.coolprop.org/coolprop/REFPROP.html .  It should look pretty familiar if you are using refpropm, as I modeled it on that to a large extent.

**Comment by estebanAIRBUS** [comment]
Thank you very much for the suggestion. I will have a go at that.
