### ISSUE TITLE
Issue linking REFROP with MATLAB using Python as an intermediate

### ISSUE THREAD

**Issue by Harish-tech1997** [usnistgov/REFPROP-wrappers#334]
Hi Ian,

I have REFPROP 9.1 version and MATLAB 2020b version. I followed the steps that you had suggested with the 9.1 version with the legacy API code on Jupyter notebook. When I ran that code I didn't get any output in Jupyter strangely but the code ran. I also updated my refpropm file as the one you had posted on the link- https://raw.githubusercontent.com/usnistgov/REFPROP-wrappers/master/wrappers/MATLAB/legacy/refpropm.m 

Besides, when I try running the code I have copied below on MATLAB-

```
MOLSI = RP.GETENUMdll(int8(0),'MOLAR BASE SI').iEnum;
iMass = int8(0); % 0: molar fractions; 1: mass fractions
iFlag = int8(0); % 0: don't call SATSPLN; 1: call SATSPLN
z = {1.0};
r = RP.REFPROPdll('Water','PQ','T',MOLSI,iMass,iFlag,101325,0.0,z)
```

I get the following output -
```
Error using ctREFPROP>GETENUMdll (line 1544)
Python Error: ValueError: The function GETENUMdll could not be loaded from the shared library.
```
I have also copied the code for the API below (Im using windows for running the code). 

```
import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

def NBP():
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    print(RP.RPVersion())
    RP.SETPATHdll(os.environ['RPPREFIX'])
    r = RP.SETUPdll(1,"PROPANE.FLD","HMX.BNC","DEF")
    assert(r.ierr == 0)
    print(RP.PQFLSHdll(101.325, 0, [1.0], 0))

if __name__=='__main__':
    # Print the version of REFPROP in use and the NBP
    NBP()
```

I have the latest version of ctREFPROP installed as well.  I had gone through the previous GETENUM cases and they didn't seem to aid in my case. I had also added REFPROP as well as Anaconda to my MATLAB path.
Thanks
Harish Chandrasekar

**Comment by ianhbell** [comment]
A couple of issues: Python is not quite MATLAB, so some (minimal) translation is required.

Your first example is for REFPROP 10, to which you should upgrade at your convenience.

The second example should work, if you update the formatting for MATLAB.  Please post the output that you get when you run the commands so we have some prayer of figuring out what is going on.

**Comment by Harish-tech1997** [comment]
Sure Thanks Ian. When I directly run the second code on Jupyter notebook by calling the function NBP() I get the following output (attached in the photo). Omce this is rectified I think I can modify it for MATLAB and run it there.
![Doc111](https://user-images.githubusercontent.com/71052183/96494206-0821a280-1214-11eb-87ff-b02e1773de0f.jpg)

**Comment by ianhbell** [comment]
I was really confused with the parallel discussions of Jupyter notebooks and MATLAB.  Any reason to not just use Jupyter?  Much easier to interface with REFPROP.

Anyhow, solution is to delete (or rename to some other extension), the thunk file.

**Comment by Harish-tech1997** [comment]
Great! It seemed to work now. The reason why i wanted to link with MATLAB is that i had part of the code there and thought it would be convenient for me to use refprop there and I'm more proficient in MATLAB over Python, but seems like I can manage that part. However, wrt the function NBP() I wanted to know what would be the equivalent of the line  P = refpropm('P','T',373.15,'Q',0,'water') in Python. In case you are aware of other examples which would help me learn how to derive the values from refprop on Python it would be super helpful!

Thanks again for all the help

**Comment by ianhbell** [comment]
If you upgrade to REFPROP 10, it would be something like:

``` python
RP.REFPROPdll('Water','PQ','T',RP.MOLAR_BASE_SI,0,0,101325,0,[1.0])
```

There are docs available: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python#ctypes-wrapper (see the second paragraph and the mini-tutorial).

**Comment by Harish-tech1997** [comment]
Great Thanks Ian for all the help!
