### ISSUE TITLE
ALLPROPS warning -852

### ISSUE THREAD

**Issue by jadepgit** [usnistgov/REFPROP-wrappers#337]
I tried a simple test case with REFPROPdll using 2 components which I made mixed phase by adjusting T and P.  For hIn I used "TP", and for hOut I used "XMOLEVAP".  It ran.  I printed x's, y's, output[] (only 2 entries, rest was -9999990), and q.  All results as expected.

Here's the issue:  output[0] matched y[0] and output[1] matched y[1] correctly.  q was correct.  So everything worked well.  However I got error code -852.  I printed herr and got "[ALLPROPS warning -852] Additional properties are included in the output array, the input string and output array do not line up."  I also printed hUnits and got "XMOLE", which is an ALLPROPS hOut code.  Note I printed the first 8 elements of output[], and only the first 2 contained values, which were the 2 vapor phase compositions.  The remaining 6 were the -9999990, so the herr message doesn't make sense to me as there aren't additional properties in output, just the XMOLEVAP results.

Didn't affect my results, but it makes error trapping difficult.  Please advise.  Thanks for your help.

**Comment by EricLemmon** [comment]
You also posted this issue in the web address below and I gave a response.  Did that solve the problem with this issue?  If so, could you close this one?

https://github.com/usnistgov/REFPROP-issues/issues/346

**Comment by jadepgit** [comment]
Yep, you all took care of me.  Thanks.
