### ISSUE TITLE
Z is not permitted for two-phase states

### ISSUE THREAD

**Issue by monstrorivas** [usnistgov/REFPROP-wrappers#339]
### Description
The Z value for some states is undefined in ctREFPROP but the GUI returns a value. This happens with several combinations of temperature and pressure for this particular mixture, I'm just showing an example below. 

### Steps to Reproduce

With ctREFPROP
``` python
import os
import numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = os.environ['RPPREFIX']
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
RP.FLAGSdll('Cache', 3)
RP.PREOSdll(0)
fractions = [0.79978, 0.08259, 0.05384, 0.02216, 0.01075, 0.0033, 0.00352, 0.00328, 0.001, 0.00046, 0.00018, 0.00101, 0.00027, 0.00035, 7e-05, 0.0008, 4e-05, 0.01408, 0.00252]
fluid_names =['methane', 'ethane', 'propane', 'butane', 'ISOBUTAN', 'pentane', 'IPENTANE', 'hexane', 'heptane', 'PXYLENE', 'octane', 'CYCLOPEN', 'CYCLOHEX', 'benzene', 'OXYLENE', 'nitrogen', 'H2S', 'CO2', 'water']
RP.SETFLUIDSdll('*'.join(fluid_names ))
RP.REFPROPdll('', "PT", "Z", RP.MASS_BASE_SI, 0, 1, 1776325.0, 292.31, fractions).Output[0]
```
The result of the above is `-9999990.0`

However, in REFPROP GUI the result is `0.93533`
![image](https://user-images.githubusercontent.com/28580105/98424048-22ea7880-2056-11eb-9732-2f1266c26f3c.png)

I also want to point out that the discrepancy is only with the Z value. If you change the output property in the python code above to Density, Enthalpy, Quality, etc., the results are consistent between ctREPFROP and the GUI. 

Any ideas what might be happening or how to fix it?

### Versions
**REFPROP Version:** v10.0
**Operating System and Version:** Windows 10

**Comment by ianhbell** [comment]
What ierr and herr values do you get from the REFPROPdll function?

**Comment by monstrorivas** [comment]
```
ierr=810, herr='[REFPROP error 810] One
 or more of the input properties is not thermophysically defined for two-phase states and cannot be calculated.'
```

**Comment by ianhbell** [comment]
There's your answer!  The error message should talk about output properties, but the issue stands.  

You can calculate Z from Z=p/(rho*R*T), so since  you've got all the bits you need to calculate it yourself

I believe this is a bug, since Z should be allowed to be calculated for two-phase states.

**Comment by ianhbell** [comment]
@EricLemmon Also note that the error message should talk about outputs rather than inputs

**Comment by EricLemmon** [comment]
Both of these have been corrected now, but I have the code torn apart for a different project and cannot put up a new patch.  Fortunately it is easy to calculate Z so you should be OK.

**Comment by monstrorivas** [comment]
Thank you @ianhbell and @EricLemmon

Could you please tag me on the version that has the fix? I'd like to pull your fix when available. Thanks!

**Comment by EricLemmon** [comment]
Can you send me a private email at eric.lemmon@nist.gov?
