### ISSUE TITLE
Using REFPROP-wrappers with Simulink - simulation speed question

### ISSUE THREAD

**Issue by Unictu** [usnistgov/REFPROP-wrappers#34]
Hi,

Thank you for developing this tool. The REFPROP-wrappers (REFPROP patch 9.1.1) works flawlessly with Simulink (Matlab 2010b). 

However, there is a little concern with simulation speed. We obtained refrigerant properties via 1D/2D maps prior to using the wrapper. We then use the provided wrapper to access Refprop via S-function. Once switching, there is a significant drop in simulation speed. We already try to limit the amount of call to dLLload() function, only when needed, which improved the situation. We would like to know if there are, other, best practices for speed optimisation. 

Regards,

Unictu

**Comment by ianhbell** [comment]
Which wrapper are you talking about?  The refpropm.m one?  Tabular lookup will almost certainly be MUCH faster.  Sometimes hundreds or thousands of times faster.  If you are comparing EOS with tabular lookup, there is not much at all that we can do.  If you were using Python or C++, I could recommend parallelism that would allow you to get N-times faster evaluation, where N is the number of cores.

**Comment by Unictu** [comment]
Hi Ian,

Thanks for your reply.

Sorry I was not clear we use this wrapper https://trc.nist.gov/refprop/LINKING/C.ZIP.

We use the provided method in Matlab S-functions (mexed C files). From our  Simulink model, there are a lot of these S-functions access REFPROP database repeatedly in time. I think the issue was that we load refprop.dll and SETUPdll to initialize the program every time. Originally it is expected that Matlab/Simulink will unload the dlls when existing the S-function. It is probably not true.

Yesterday, we included a flag to check if dlls load has been done then do not repeat. The Simulink program access REFPROP from all S-functions no problems while the speed has improved significantly. Certainly it is slower than tabular lookup, simulation speed is now acceptable.

**Comment by ianhbell** [comment]
Ok, thanks for the update.  I guess you can go ahead and close the issue.

**Comment by En-pt** [comment]
Hi @Unictu ,

I am working on a project which requires to access Refprop in Simulink. But I do not have any idea how to do it. I wonder how you use this C wrapper in S function, and how you insert this flag to accelerate simulation. It would be much appreciated if you can elaborate.
Thanks in advance!
En-pt
