### ISSUE TITLE
Error calculating water properties

### ISSUE THREAD

**Issue by MichaelHolmes123** [usnistgov/REFPROP-wrappers#340]
Using REFPROP Excel add-in v10.0, having issue where it tells me water is in the solid phase when it should not be. Trying to calculate temperature from pressure and enthalpy. Even feeding REFPROP the enthalpy it calculates for the given conditions then asking it to back-calculate the temperature gives the error.

1.	Calculate water enthalpy at 120°C and 5 MPa 
        a) H = Refprop(“H”,”water”,”TP”,”SI with C”, 120, 5)
        b) H = 507.19 kJ/kg
2.	Use the enthalpy it just calculated to calculate temperature (should give 120°C): 
        a) T = Refprop(“T”,”water”,”HP”,”SI with C”,507.19,5)
        b) #[PHFLSH error 16] One or more inputs are out of range; Inputs are within the solid phase.

**Comment by EricLemmon** [comment]
This is a known bug, can you send me a private email and I'll send you the update?

Eric.Lemmon@nist.gov

**Comment by EricLemmon** [comment]
Also, see this issue for more details about the bug:

https://github.com/usnistgov/REFPROP-issues/issues/270
