### ISSUE TITLE
No "REFPROP_Ribbon.xlam" file provided for OSX install?

### ISSUE THREAD

**Issue by dtgerhardt** [usnistgov/REFPROP-wrappers#341]
# Description

I don't see the referenced "REFPROP_Ribbon.xlam" file in the git repo on https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Excel

Tried following all the OSX instructions except that and couldn't get it to work. Do the instructions need updating or am I missing something?

**Comment by EricLemmon** [comment]
Which version of Refprop are you using?

**Comment by ianhbell** [comment]
I think this is never going to work - the ribbon is for Excel on windows. The ribbon comes with the windows installation of REFPROP 10.0, so for OSX you might want to pull it from there.
