### ISSUE TITLE
REFPROP 10.0 with fortran90

### ISSUE THREAD

**Issue by Fwany77** [usnistgov/REFPROP-wrappers#343]
Hello.

I'm trying to use REFPROP 10.0 with fortran90 in VS2005

But there was some error message, when i build the example code for mixture. 

can you give me any comments?

( when i used REFPROP 9.1 with fortran90, there was no error message ) 

![Ex-Mix](https://user-images.githubusercontent.com/74747744/99745312-bcb52980-2b1c-11eb-928e-338722841cfa.JPG)
![Error](https://user-images.githubusercontent.com/74747744/99745320-bf178380-2b1c-11eb-96e8-ea672e700b34.JPG)

**Comment by EricLemmon** [comment]
Can you post your code, without that it is hard to find out what is wrong.  Also, the list on the right hand side of that picture shows that it is the 9.1 code.  There are only about 15 fortran files in refprop 10.  However, you show the REFPROP.FOR file is included, that is a version 10 file, so I think you have mixed and matched the fortran code between 9.1 and 10!

**Comment by Fwany77** [comment]
Thank you, EricLemmon.

As you said, there were 9.1 and 10 versions mixed.
When I installed version 10, I didn't uninstall version 9.1 completely, so I thought all the files correspond to version 10.

Thanks to you, I was able to solve it.
We can close this issue. 👍

**Comment by EricLemmon** [comment]
Glad to hear that all is working!
