### ISSUE TITLE
Fortran (C) Results not matching GUI

### ISSUE THREAD

**Issue by jadepgit** [usnistgov/REFPROP-wrappers#344]
# Description
Prepared a liquid phase test case of 0.5 Propane, 0.5 nButane in GUI at 291.5K and 0.515 MPa (65F, 60 psig/74.7psia)  Density matched expected.  Enthalpy looked "reasonable" by comparing to saturated vapor on the P-H chart.   Enthalpy reported as 244 kJ/kg. Density 546 kg/m^3

Ran same with REPROP1dll to check QMOLE.  Code -998.  Doc states Code typically means liquid with P>Pc, which is not right.
Ran same with ABFLSHdll as a blind flash.  Same Q, -998.  "D" matched GUI.  Dl = Dv = 10.7 (very low Dl)  Enthaply = 637.6 kJ/kg, which is very high, acting like vapor phase.

Since the GUI is performing as expected, the problem is on my side.  However I ran a previous test case with a 2-phase mix and REPROPdll worked fine.  Do I need to set some flags that I've skipped?  Currently I call SETPATH and SETFLUIDS, then I set the "nc" to 2.  That's all I'm doing for set-up.  Thanks for your help.

### Steps to Reproduce

1. GUI: 50/50 mol% propane/nButane.  291.5K, 0.515 MPa.
2. ABFLASH: same mix. ab = TP,  z[0] = 0.5, z[1] = 0.5, 291.5K, 515 kPa.  iFlag 002.  Using GETENUM result for "English" for units.  For ABFLASH call I'm entering the SI for "a" and "b" (K/kPa).

**Expected behavior: Reasonable Q since P<<Pc.  h = 244.7.  Dl = 546.8

**Actual behavior:** Q= -998, h = 637.6, Dl = 10.7, D = 546.8

### Versions

**REFPROP Version:** 10.0  
**Operating System and Version: Artix Linux / Wine
**Access Method:** refpropdll library from C program  

### Additional Information
I'd like to replicate the GUI "Calculate->Specified State Points functionality in code.

Thanks for your help.

**Comment by jadepgit** [comment]
I actually like the REFPROPdll routine and prefer to use it.  However I switched over to ABFLSH because I was originally dealing with a subcooled liquid.  According to the doc it seems like I can't get a liquid enthalpy or Density on a sub cooled liquid using REFPROPdll (hOut = "HLIQ DLIQ").  If that's the case, using ABFLSHdll with molar units appears to be an option.  Let me know if that is correct.  Again, thanks for your time.

**Comment by EricLemmon** [comment]
You can use the symbols > and < on the inputs to force it to do a liquid or vapor phase calculation.  Thus "TP>" will search given T and P in the liquid phase only, "PH<" will search with P and H in the vapor phase, and so on.  You could also use L and V, such as "TPL" or "PHV".  

Everything available in ABLFSHdll should also be available in REFPROPdll.

**Comment by jadepgit** [comment]
Just to be clear, I've noticed this in the docs for "*LIQ", (e.g. "HLIQ") in the docs:
"*LIQ:(where * is T, P, D, etc.) Return the liquid saturation properties for the property listed as the first
letter. This is only valid for saturation states or 2-phase states."  Does TP< override this and thus return the subcooled enthalpy with hOut = HLIQ?  Is there some other way to return enthalpy and density?  Thanks.

**Comment by jadepgit** [comment]
TP> or TPL.  Typo.

**Comment by jadepgit** [comment]
Ran two cases with subcooled liquids at different temperatures.  Enthalpy and Density definitely changed and are now reasonable.  Used REFPROP TPL and HLIQ and DLIQ.  This solves the problem and I'm closing the issue.  Thanks for your help.

**Comment by EricLemmon** [comment]
Glad to hear you figured it out!  Most of the details are in the manual, but not all.  Let us know if any are unclear or something is missing and we'll fix/add it.
