### ISSUE TITLE
'pyversion' is not defined 

### ISSUE THREAD

**Issue by MFHC11** [usnistgov/REFPROP-wrappers#346]
Hi All, 

I'm trying to set-up the python interpreter so I can use REFPROP with Matlab. I'm following the instructions here: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB. 

When installing the ctREFPROP, I run the following command from the python in a cmd window: 
    [v,e] = pyversion; system(['"', e, '" -m pip install --user -U ctREFPROP'])

I get the following error message: 
  Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    NameError: name 'pyversion' is not defined

Any ideas on how to resolve this?

**Comment by ianhbell** [comment]
What version of MATLAB do you use?

**Comment by ianhbell** [comment]
Seems your version doesn't have ``pyversion``

**Comment by MFHC11** [comment]
Thank you Ian. I was running the command in python and not Matlab, whoops!

**Comment by ianhbell** [comment]
Ah good that's all it was
