### ISSUE TITLE
[Question] Composition summation

### ISSUE THREAD

**Issue by JHulk5623** [usnistgov/REFPROP-wrappers#347]
Hi, teachers.

 I am making a process sheet in excel.
 The fluid is consist of several components such as methane, ethane, nitrogen so on.

 Is there any short cut to composition calculation?

 Each stream has different composition. When the stream combined or separated, I should calculate composition.
 Please let me know the short cut or easy way.

 FluidString10(methane;ethane;nitrogen,0.8;0.15,0.05, "mass"), mass: 100 kg
 FluidString10(methane;ethane;nitrogen,0.9;0.05,0.05, "mass"), mass:   10 kg
 FluidString10(methane;ethane;nitrogen,0.1;0.45,0.45, "mass"), mass: 300 kg

 Thank you and Merry Christmas.

**Comment by EricLemmon** [comment]
The very best way to do things in Excel is to write your own VBA code in a module and have it do all the complicated stuff!  The random cell selection that Excel uses in its calculations of your spreadsheet can sometimes have detrimental effects, mostly for mixtures.  But, this is only my view, and I fully understand that this is not a possibility for most people's applications.  

I don't understand your nomenclature above, what do you mean by "mass: 100 kg"?  Is that something you include in the cell and that you want sent to Refprop?  And do your other questions deal with sending the program different compositions, or are they about obtaining compositions at VLE states where the outputs are not the same as the input compositions?  

Have you studied the mixture page in the Refprop.xls file carefully?  When I made it, I tried to include everything I could think of as inputs and outputs to help explain how to do these things.

**Comment by NickAtNight62** [comment]
I agree with Eric - sometimes a simple VBA code is the best way to go.

However, here is a Sample Spreadsheet to show you some simple tricks - without going into a VBA code.

[Refprop Sample.xlsx](https://github.com/usnistgov/REFPROP-wrappers/files/5762860/Refprop.Sample.xlsx)

To make a composition, enter the Fluids into the yellow cells, B2 to B4 (setup for three component fluid)
Enter the composition for the first two components in C2 to C3.
The final composition is calculated  {=1-C2-C3}

And then B5 calculates the fluid string.   { =FluidString10(B2:B4,C2:C4,"mass") }

![image](https://user-images.githubusercontent.com/58614082/103502660-8820d700-4e17-11eb-8732-c1dd945e4d5b.png)

So what does the spreadsheet do?

We calculate the Critical Pressure and Critical temperature  for the mixture in B7 to E8.
    Critical pressure =refprop(C7,RefName,"TQ",RefUnit,273.15,1,0)
    Critical temperature =refprop(C8,RefName,"TQ",RefUnit,273.15,1,0)

Notice we are also get the units for the calculations.
   Critical pressure units   =refprop("Units",,$C7,RefUnit)  
   Critical temperature units  =refprop("Units",,$C8,RefUnit)

![image](https://user-images.githubusercontent.com/58614082/103502839-2745ce80-4e18-11eb-8fb5-d79853477bae.png)

You set the units with a drop down list in E2.

![image](https://user-images.githubusercontent.com/58614082/103503001-9c190880-4e18-11eb-8a23-f62cafdbcabc.png)

![image](https://user-images.githubusercontent.com/58614082/103502869-3d538f00-4e18-11eb-9544-988e879f6324.png)

The drop down list is set in H6 to H14

![image](https://user-images.githubusercontent.com/58614082/103503028-b05d0580-4e18-11eb-9483-1dcc0a13ef00.png)

And then you develop a list of any particular property.  Use the dropdown list in B10 to set the property.

![image](https://user-images.githubusercontent.com/58614082/103503068-ca96e380-4e18-11eb-9c7d-130595068837.png)

The advantage of dropdown lists is ... well it makes life easy and eliminates errors.  You get to enter the full name of the property, and the drop down list selects the correct property code.  Set in H16 to I48.

![image](https://user-images.githubusercontent.com/58614082/103503111-e8fcdf00-4e18-11eb-99f3-f320c36dd40c.png)

So here are the results for Density.  You can adjust the temperature entries to suit using whatever fancy calculations you want to do... Or just manually enter the numbers you want the results for. 
In this case, the first result is the critical temperature.  =D8
The next result is the integer of the critical temperature.  =INT(C14)
The third result was just manually set to 700.  =C15-5   (a fairly pedestrian way to set the number)
and then each result after for a while reduces by 50 F.  =C17-50

The results are calculated iwth the equations:
  =refprop($B$11,RefName,$C$11,RefUnit,$C26,D$11,0)
   =refprop($B$11,RefName,$C$11,RefUnit,$C26,E$11,0)

B11 being the cell where the property code is entered.
C11 is where the two input properties are entered.  In this case TQ for Temperature and Quality.
Cxx is the reference temperature
D11 and E11 is where the quality is entered. (0 and 1 respectively for liquid and gas)


![image](https://user-images.githubusercontent.com/58614082/103503169-18abe700-4e19-11eb-90df-040198873a5e.png)

**Comment by NickAtNight62** [comment]
Your imagination is your only limit.  From a different spreadsheet.

For example, here is my Ternary diagram for the latent heat of R32, R125 and R134a.

![Latent Heat](https://user-images.githubusercontent.com/58614082/103503580-4ba2aa80-4e1a-11eb-937c-8fba4aa304f4.png)
