### ISSUE TITLE
Use fortran to include Refprop 9.1 in Windows

### ISSUE THREAD

**Issue by Jiang-Jiang-Sun** [usnistgov/REFPROP-wrappers#350]
Dear friends:
       I am a beginer using Refprop 9.1 with fortran program. I have read the manual and  tried the Lahey-Fujitsu Fortran to run the example.for, but failed. I don't know how to include the refprop.dll in my main program example.for. The manual did not give detailed instructions, so I find here to ask you.The relevant part of the manual are attached in Fig. 1.
![6](https://user-images.githubusercontent.com/78197075/106244519-f8b7e980-6245-11eb-8f2f-e69a1ce895bc.png)
Figure 1
The file content of my test is shown in Fig.2, and the compile result is shown in Fig. 3. As shown, the .dll file is not included correctly.
![3](https://user-images.githubusercontent.com/78197075/106244681-42083900-6246-11eb-969a-4e54496be6e4.png)
Figure 2
![4](https://user-images.githubusercontent.com/78197075/106244703-4d5b6480-6246-11eb-8a80-b130ba87554d.png)
Figure 3
Then, I read some discussion online, and tried to compile the fortran file in the compiler CodeBlocks, the project is shown below. However, I don't know why the errors occur.
![1](https://user-images.githubusercontent.com/78197075/106245093-df636d00-6246-11eb-8e10-e7afc3f50515.png)
Figure 4
Could you pls give some advice about it?
Thank you very much.

Jiang

**Comment by ianhbell** [comment]
First issue is that we recommend either gfortran or Intel Fortran, and not Lahey.  gfortran is free. If you are building in fortran, you need the sources, not the DLL.  But also, it looks like you are actually using gfortran in spite of your comment above.

Also, if you have called ``SETPATH``, you no longer need the absolute paths in ``hflnme`` and ``hfmix``.

**Comment by Jiang-Jiang-Sun** [comment]
> First issue is that we recommend either gfortran or Intel Fortran, and not Lahey. gfortran is free. If you are building in fortran, you need the sources, not the DLL. But also, it looks like you are actually using gfortran in spite of your comment above.
> 
> Also, if you have called `SETPATH`, you no longer need the absolute paths in `hflnme` and `hfmix`.

Thank you for your reply!
I got the right results using the Intel Visual Fortran by compiling all the source files (27 source files) in one project.
And I also try to include all the subroutines in the main program, rather than add the rest of 26 fortran files into the project and compile them every time I change the operation conditions. So I make a *.lib file to include them and it works.

**Comment by ianhbell** [comment]
Intel Fortran should always do incremental builds, so the static library should not be necessary.  You shouldn't be fiddling with the REFPROP files unless you know what you are doing.

**Comment by Jiang-Jiang-Sun** [comment]
Thank you for your comment.
