### ISSUE TITLE
When using FORTRAN routines to calculate mixtures (Exhaust gas) it looks not to find correct FEQ

### ISSUE THREAD

**Issue by francmiller** [usnistgov/REFPROP-wrappers#351]

**Comment by francmiller** [comment]
This is the screenshot of code running at Visual Studio:
![image](https://user-images.githubusercontent.com/53828638/106664135-6b490200-6583-11eb-9293-8a0a00bd2d20.png)

it gives a breakpoint at CALL SETFEQ (from SETUP routine).
Find below the code:

'''FORTRAN
 ! Mixture Composition
    hfiles(1)='NITROGEN.FLD'     !Fluid filename
    hfiles(2)='OXYGEN.FLD'         !Fluid filename
    hfiles(3)='WATER.FLD'           !Fluid filename
    hfiles(4)='CO2.FLD'               !Fluid filename
    hfiles(5)='ARGON.FLD'         !Fluid filename
    z(1)=0.73115D0           !Composição N2
    z(2)=0.11838D0           !Composição O2
    z(3)=0.12227D0           !Composição H20
    z(4)=0.022021D0          !Composição CO2
    z(5)=0.006179D0          !Composição AR
    hfmix='hmx.bnc'          !Mixture MODEL
    hrf='DEF'                      !Ref. State - default
            
    CALL SETPATH('C:\Users\km7k\OneDrive - PETROBRAS\Documents\Visual Studio 2010\Projects\Arquivos REFPROP')   ! Localização do arquivo do fluido
    
    CALL SETUP(nc,hfiles,hfmix,hrf,ierr,herr)   !Rotina que define o exausto como fluido de trabalho!
    IF (ierr.ne.0) THEN
        WRITE(*,*) herr
    ENDIF
    
    tt=473.15
    pp=103.3
  
    CALL TPFLSH(tt,pp,z,D,Dl,Dv,x,y,q,Umol,hmol,smol,Cv,Cp,w,ierr,herr)
    IF (ierr.ne.0) THEN
        WRITE(*,*) herr
    ENDIF
'''

**Comment by ianhbell** [comment]
Not sure I understand here.  What error do you get?  Are you sure that your path is valid?

**Comment by francmiller** [comment]
> 
> 
> Not sure I understand here. What error do you get? Are you sure that your path is valid?

@ianhbell yes, the path is valid, and the fluid archives as well as the hmx.bnc are there. 
The problem: when I run the code through Visual Studio, it stops at this point, Call SETFEQ at ICOMP=1, as if it was not finding at HMX.bnc the data for Nitrogen. If I click in Continue it comes back to the same point

**Comment by ianhbell** [comment]
Can you run the GUI with the files in that folder?

**Comment by ianhbell** [comment]
Can you use something like Python?  Maybe its a FORTRAN problem but it's hard to see what you could be doing wrong in the snippet you have posted.  Can you please post your entire runnable script?

**Comment by francmiller** [comment]
@ianhbell 
Yes I run other codes with files in that folder without problem.
I don't use Python, as my codes are all in FORTRAN
Find below the whole code: it was just a test code to see if it works, so that I can use it in other more complex codes:
program Exausto

    
    ! variaveis propriedades
    INTEGER, PARAMETER:: nc=5,ncmax=20              !Numero de componentes, nc max
    INTEGER ierr , i                        !Codigo de erro do acesso ao fluido  
    INTEGER,PARAMETER :: kq=2               !Flag da rotina TQFLSH unidade do título em massa              
    CHARACTER(3) hrf                        !Estado de referência
    CHARACTER(255) hfiles(ncmax),hfmix,herr     !Nome do Fluido, arquivo de mistura, erro
    REAL(8),PARAMETER :: mol=27.689d0       !Conversão da densidade para kg/m3
    REAL(8) z(ncmax),tt,pp,D,Umol,hmol,smol,Cp,Cv,w,Dl,Dv,x(ncmax),y(ncmax),q 
                                            
    !z -> Composição [adim]
    !tt -> Temperatura [K]
    !pp -> Pressão [kPa]
    !D -> Densidade [mol/L],
    !Umol -> Energia Interna [J/mol]
    !hmol -> Entalpia [J/mol]
    !smol -> Entropia [J/mol.K]
    !Cp -> Calor específico isobárico [J/mol.K]
    !Cv -> Calor específico isométrico [J/mol.K]
    !w -> velocidade do som [m/s]
    !Dl -> Densidade Liquido [mol/L]
    !Dv -> Densidade Vapor [mol/L]
    !x -> Composição liquido [adim]
    !y -> Composição vapor [adim]
    !q -> Qualidade do vapor   <0 liq. comp, =0 liq. sat, =1 vapor sat, >1 vapor superaq, 999 supercrit
    !q na rotina TQFLSH   =0  liquido saturado    =1 vapor saturado
    !kph -> Flag de fase do fluido saturado
   
      
    ! Mixture Composition
    hfiles(1)='NITROGEN.FLD'     !Fluid filename
    hfiles(2)='OXYGEN.FLD'       !Fluid filename
    hfiles(3)='WATER.FLD'        !Fluid filename
    hfiles(4)='CO2.FLD'          !Fluid filename
    hfiles(5)='ARGON.FLD'        !Fluid filename
    z(1)=0.73115D0           !Composição N2
    z(2)=0.11838D0           !Composição O2
    z(3)=0.12227D0           !Composição H202
    z(4)=0.022021D0          !Composição CO2
    z(5)=0.006179D0          !Composição AR
    hfmix='hmx.bnc'          !Mixture MODEL
    hrf='DEF'                !Ref. State - default
            
    CALL SETPATH('C:\Users\km7k\OneDrive - PETROBRAS\Documents\Visual Studio 2010\Projects\Arquivos REFPROP')   ! Localização do arquivo do fluido
    
    CALL SETUP(nc,hfiles,hfmix,hrf,ierr,herr)   !Rotina que define o exausto como fluido de trabalho!
    IF (ierr.ne.0) THEN
        WRITE(*,*) herr
    ENDIF
    
    tt=473.15
    pp=103.3
  
    CALL TPFLSH(tt,pp,z,D,Dl,Dv,x,y,q,Umol,hmol,smol,Cv,Cp,w,ierr,herr)
    IF (ierr.ne.0) THEN
        WRITE(*,*) herr
    ENDIF
    
      
    h=hmol/mol
    s=smol/mol
    D=D*mol
        
    write (*,*) "T  p  D  h  s  Cv  Cp"
    write (*,1000) t,p,D,h,s,Cv/mol,Cp/mol

     
      pause

 1000 format (7(F7.2))
      
    end program Exausto

**Comment by ianhbell** [comment]
What if (just as a check) you provide absolute paths to the fluid files?

**Comment by Jiang-Jiang-Sun** [comment]
The transport equations may not be properly solved if the molar concentration of water in your defined mixture is above 5% (this is unphysical). What if change your mixture composition to ensure the  molar concentration of water below 5%?

**Comment by ianhbell** [comment]
@Jiang-Jiang-Sun  - thanks for the idea.  The problem occurs at the ``SETUP`` call, so it is more fundamental

**Comment by francmiller** [comment]
> 
> 
> The transport equations may not be properly solved if the molar concentration of water in your defined mixture is above 5% (this is unphysical). What if change your mixture composition to ensure the molar concentration of water below 5%?

Thank you Jiang I will try to change, and see what happens. Anyway, when I run the REFPROP interface with this composition, the program is able to calculate the porperties.

**Comment by EricLemmon** [comment]
Has this issue been resolved, and if so, could you close it?
