### ISSUE TITLE
Calculation of surface tension for R410A in Python

### ISSUE THREAD

**Issue by saadsaleem2005** [usnistgov/REFPROP-wrappers#352]
Hello!
I am using a refprop wrapper in Python 3.6.5 (on Spyder). The installed version of REFPROP on my Windows 10 machine is REFPROP 10. I am trying to calculate the surface tension for R410A in a heat exchanger model, using the following line

``` python
 sf_t=refprop('R410A','STN','Q',1,'P',1200)
```

However, I get the following error: 

![image](https://user-images.githubusercontent.com/47908701/108095780-d85d9c80-7045-11eb-8a3b-7a268576d068.png)

What am I doing wrong here?
Thanks in advance!

**Comment by ianhbell** [comment]
Is this the deprecated (and no longer supported) refpropm interface that you are using?  Recommend to upgrade to python interface.

**Comment by saadsaleem2005** [comment]
Hi Dr. Bell!
I am not 100 percent sure if this is the deprecated interface. Where can I find the new one?

**Comment by ianhbell** [comment]
Please see https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB
