### ISSUE TITLE
Problem Getting Z Values For Helium Air Mixture in Excel When They Exist Using REFPROP GUI!

### ISSUE THREAD

**Issue by starmanca** [usnistgov/REFPROP-wrappers#353]
[Heluim Air Mixture.xlsx](https://github.com/usnistgov/REFPROP-wrappers/files/6046415/Heluim.Air.Mixture.xlsx)
Any guidance in resolving this will be appreciated.
Joe

**Comment by ianhbell** [comment]
Please also explain your problem in words.  Mixing pseudo-pure air with helium could be an issue; we don't have estimation parameters for this mixture and this mixture is HIGHLY non-ideal. Better might be to use the components of air directly (nitrogen, oxygen, argon).

**Comment by EricLemmon** [comment]
The pseudo-pure fluid file air.ppf should _never_ be used in a mixture.  Instead you will need to setup a four component mixture of nitrogen, oxygen, argon, and helium.  The air composition is 78.12 N2 + 20.96 O2 + 0.92 Ar.  Simply normalize these values with the helium value to get the mixture values.  This is the method that the GUI uses as well for helium+air mixtures.

**Comment by starmanca** [comment]
Trying to get Z for Helium contaminated with air over variable concentrations in an Excel worksheet.
I have been getting errors in P & T ranges I would not expect them. There are two sheets in attached workbook. One sheet sets up the mixtures using the pseudo component air and one in which the mixture is built up using the individual components of air.
Both sheets give similar errors but in different places. Using the multicomponent air description in the setup does not seem to resolve the issue. 
[Heluim Air Mixture.xlsx](https://github.com/usnistgov/REFPROP-wrappers/files/6052534/Heluim.Air.Mixture.xlsx)

**Comment by ianhbell** [comment]
A key point to raise here to is that the models for helium + X are, to put it kindly, not very accurate in some cases. In the GERG model, placeholder models were used, which have since been revised for many systems.  Mixtures with helium represent very challenging cases for phase equilibrium calculations.  This paper can give you a flavor of what is possible: https://doi.org/10.1063/1.5142275

Best would be to look at isopleths of the phase envelope (commonly simply called the phase envelope) to see whether they make sense.  Do you have experimental data for these mixtures?

**Comment by starmanca** [comment]
The phase diagram shows we are single phase for the T & P under consideration. What is strange is for small changes in He concentration we get into and out of trouble. For example when mole fraction of He is 0.92 we get a result but an error when the concentration is 0.925, then when the He mole fraction goes to 0.93 we get a result. Then no results for the next five 0.05 increments to a mole fraction of 0.95. After this we generate results for each 0.05 increment in Helium mole fraction to a maximum of 1.

**Comment by ianhbell** [comment]
Does the isopleth show you are are single phase for each composition?  Do you build saturation splines at each composition?

**Comment by starmanca** [comment]
The attached file presents the PT envelope of the fluids at 92, 92.5 and 93 percent He mole fraction along with the P & T point under consideration in this discussion. As expected the saturation lines do not show any material change (if any) at He concentrations of  92 and 93 percent yet the program seems to have trouble getting saturations lines at 92.5 percent. Also our P & T point is well in a single phase region.
![P-T Diagrams at 92 92_5   93 Percent Helium Mole Fractions](https://user-images.githubusercontent.com/11902596/109363471-e4b5d680-7849-11eb-8bf1-22f01b3b597c.jpg)

**Comment by starmanca** [comment]
In similar fashion to the PT plots in my previous comment the plot below shows the tiled Z-P plots for the same Helium concentrations. As previously noted at 92.5% Helium the program cannot generate saturation lines. But at 92% and 93% Helium concentration there is no problem generating saturation lines. The Excel Z values at these Helium concentrations of 92% and 93 % are 1.001101 and 1.001091 respectively. No reason that jumps out why a value for Z at Helium content 92.5% in the region of 1.00110 should not be expected. Yet the Excel program fails to find a any kind of value.
![Z-P Diagrams at 92 92_5   93 Percent Helium Mole Fractions](https://user-images.githubusercontent.com/11902596/109367683-05832980-7854-11eb-8884-6cedea51ec32.jpg)

**Comment by ianhbell** [comment]
Many compositions cause the isopleth tracer to fail.  That's why the blind flash calculations don't make sense.  You can see that programmatically in the scripts below:

![image](https://user-images.githubusercontent.com/11966765/109429497-f9b97380-79c9-11eb-8b4c-cfe9bf25ba2a.png)


```python
import pandas, io
df = pandas.read_csv(io.StringIO("""Nitrogen    Oxygen    Argon    CarbonDioxide    Neon    Methane    Helium    Krypton    Hydrogen
0    0    0    0    0    0    1    0    0
0.003904211    0.001047383    4.67001E-05    1.57E-06    9.09003E-08    1E-08    0.995    5.70002E-09    2.50001E-09
0.007808423    0.002094766    9.34003E-05    3.14001E-06    1.81801E-07    2.00001E-08    0.99    1.14E-08    5.00001E-09
0.011712634    0.003142149    0.0001401    4.71001E-06    2.72701E-07    3.00001E-08    0.985    1.71001E-08    7.50002E-09
0.015616846    0.004189532    0.000186801    6.28002E-06    3.63601E-07    4.00001E-08    0.98    2.28001E-08    1E-08
0.019521057    0.005236915    0.000233501    7.85002E-06    4.54501E-07    5.00001E-08    0.975    2.85001E-08    1.25E-08
0.023425269    0.006284298    0.000280201    9.42003E-06    5.45402E-07    6.00002E-08    0.97    3.42001E-08    1.5E-08
0.02732948    0.007331682    0.000326901    1.099E-05    6.36302E-07    7.00002E-08    0.965    3.99001E-08    1.75001E-08
0.031233692    0.008379065    0.000373601    1.256E-05    7.27202E-07    8.00002E-08    0.96    4.56001E-08    2.00001E-08
0.035137903    0.009426448    0.000420301    1.413E-05    8.18102E-07    9.00003E-08    0.955    5.13002E-08    2.25001E-08
0.039042115    0.010473831    0.000467001    1.57E-05    9.09003E-07    1E-07    0.95    5.70002E-08    2.50001E-08
0.042946326    0.011521214    0.000513702    1.72701E-05    9.99903E-07    1.1E-07    0.945    6.27002E-08    2.75001E-08
0.046850538    0.012568597    0.000560402    1.88401E-05    1.0908E-06    1.2E-07    0.94    6.84002E-08    3.00001E-08
0.050754749    0.01361598    0.000607102    2.04101E-05    1.1817E-06    1.3E-07    0.935    7.41002E-08    3.25001E-08
0.054658961    0.014663363    0.000653802    2.19801E-05    1.2726E-06    1.4E-07    0.93    7.98002E-08    3.50001E-08
0.058563172    0.015710746    0.000700502    2.35501E-05    1.3635E-06    1.5E-07    0.925    8.55003E-08    3.75001E-08
0.062467384    0.016758129    0.000747202    2.51201E-05    1.4544E-06    1.6E-07    0.92    9.12003E-08    4.00001E-08
0.066371595    0.017805512    0.000793902    2.66901E-05    1.5453E-06    1.7E-07    0.915    9.69003E-08    4.25001E-08
0.070275807    0.018852895    0.000840602    2.82601E-05    1.6362E-06    1.80001E-07    0.91    1.026E-07    4.50001E-08
0.074180018    0.019900279    0.000887303    2.98301E-05    1.72711E-06    1.90001E-07    0.905    1.083E-07    4.75001E-08
0.07808423    0.020947662    0.000934003    3.14001E-05    1.81801E-06    2.00001E-07    0.9    1.14E-07    5.00001E-08
0.081988441    0.021995045    0.000980703    3.29701E-05    1.90891E-06    2.10001E-07    0.895    1.197E-07    5.25002E-08
0.085892653    0.023042428    0.001027403    3.45401E-05    1.99981E-06    2.20001E-07    0.89    1.254E-07    5.50002E-08
0.089796864    0.024089811    0.001074103    3.61101E-05    2.09071E-06    2.30001E-07    0.885    1.311E-07    5.75002E-08
0.093701075    0.025137194    0.001120803    3.76801E-05    2.18161E-06    2.40001E-07    0.88    1.368E-07    6.00002E-08
0.097605287    0.026184577    0.001167503    3.92501E-05    2.27251E-06    2.50001E-07    0.875    1.425E-07    6.25002E-08
0.101509498    0.02723196    0.001214204    4.08201E-05    2.36341E-06    2.60001E-07    0.87    1.482E-07    6.50002E-08
0.10541371    0.028279343    0.001260904    4.23901E-05    2.45431E-06    2.70001E-07    0.865    1.539E-07    6.75002E-08
0.109317921    0.029326726    0.001307604    4.39601E-05    2.54521E-06    2.80001E-07    0.86    1.596E-07    7.00002E-08
0.113222133    0.030374109    0.001354304    4.55301E-05    2.63611E-06    2.90001E-07    0.855    1.653E-07    7.25002E-08
0.117126344    0.031421492    0.001401004    4.71001E-05    2.72701E-06    3.00001E-07    0.85    1.71001E-07    7.50002E-08
0.121030556    0.032468875    0.001447704    4.86701E-05    2.81791E-06    3.10001E-07    0.845    1.76701E-07    7.75002E-08
0.124934767    0.033516259    0.001494404    5.02401E-05    2.90881E-06    3.20001E-07    0.84    1.82401E-07    8.00002E-08
0.128838979    0.034563642    0.001541105    5.18102E-05    2.99971E-06    3.30001E-07    0.835    1.88101E-07    8.25002E-08
0.13274319    0.035611025    0.001587805    5.33802E-05    3.09061E-06    3.40001E-07    0.83    1.93801E-07    8.50002E-08
0.136647402    0.036658408    0.001634505    5.49502E-05    3.18151E-06    3.50001E-07    0.825    1.99501E-07    8.75003E-08
0.140551613    0.037705791    0.001681205    5.65202E-05    3.27241E-06    3.60001E-07    0.82    2.05201E-07    9.00003E-08
0.144455825    0.038753174    0.001727905    5.80902E-05    3.36331E-06    3.70001E-07    0.815    2.10901E-07    9.25003E-08
0.148360036    0.039800557    0.001774605    5.96602E-05    3.45421E-06    3.80001E-07    0.81    2.16601E-07    9.50003E-08
0.152264248    0.04084794    0.001821305    6.12302E-05    3.54511E-06    3.90001E-07    0.805    2.22301E-07    9.75003E-08
0.156168459    0.041895323    0.001868005    6.28002E-05    3.63601E-06    4.00001E-07    0.8    2.28001E-07    1E-07
0.160072671    0.042942706    0.001914706    6.43702E-05    3.72691E-06    4.10001E-07    0.795    2.33701E-07    1.025E-07
0.163976882    0.043990089    0.001961406    6.59402E-05    3.81781E-06    4.20001E-07    0.79    2.39401E-07    1.05E-07"""), sep=r'\s+', engine='python')

import CoolProp.CoolProp as CP 
import matplotlib.pyplot as plt

for ir, row in df.iterrows():
    names, comps = [], []
    for k,v in row.items():
        names.append(k)
        comps.append(v)
    AS = CP.AbstractState('REFPROP', '&'.join(names))
    AS.set_mole_fractions(comps)
    try:
        AS.build_phase_envelope("")
        PE = AS.get_phase_envelope_data()
        plt.plot(PE.T, PE.p)
    except BaseException as BE:
        print(row['Helium'], BE)

plt.gca().set(xlabel='T / K', ylabel='p / Pa')
plt.yscale('log')
plt.show()
```
yielding
```
0.995 [SATSPLN error 355] Spline routine failed.           
0.985 [SATSPLN error 355] Spline routine failed.           
0.98 [SATSPLN error 355] Spline routine failed.            
0.975 [SATSPLN error 355] Spline routine failed.           
0.97 [SATSPLN error 355] Spline routine failed.            
0.965 [SATSPLN error 355] Spline routine failed.           
0.955 [SATSPLN error 355] Spline routine failed.           
0.945 [SATSPLN error 355] Spline routine failed.           
0.94 [SATSPLN error 355] Spline routine failed.            
0.925 [SATSPLN error 355] Spline routine failed.           
0.905 [SATSPLN error 355] Spline routine failed.           
0.9 [SATSPLN error 355] Spline routine failed.             
0.88 [SATSPLN error 355] Spline routine failed.            
0.875 [SATSPLN error 355] Spline routine failed.           
0.87 [SATSPLN error 355] Spline routine failed.            
0.86 [SATSPLN error 355] Spline routine failed.            
0.855 [SATSPLN error 355] Spline routine failed.           
0.85 [SATSPLN error 355] Spline routine failed.            
0.845 [SATSPLN error 355] Spline routine failed.           
0.84 [SATSPLN error 355] Spline routine failed.            
0.825 [SATSPLN error 355] Spline routine failed.           
0.82 [SATSPLN error 355] Spline routine failed.            
```

**Comment by starmanca** [comment]
That looks awesome! Is it possible to implement what you did above in Excel? If yes, are there any tutorials that could help guide me through such an implementation - for example  sample workbooks?

**Comment by ianhbell** [comment]
In VBA, yes, but not in Excel proper. You'll have a fair bit of work to do to get this working. The Python code (calling CoolProp) is rather concise (and already written).
