### ISSUE TITLE
Calculation of Humid air props with REPROP 10

### ISSUE THREAD

**Issue by saadsaleem2005** [usnistgov/REFPROP-wrappers#356]
Hello!

I am using REFPROP 10. I know from the changelog that humid air properties can now be calculated in refprop from this version onwards. However, has this functionality been extended to the excel add-in as well? If yes, where can I find the updated excel add in that does these new calculations?

Thanks in advance

**Comment by ianhbell** [comment]
Can be calculated? Yes.  

Is accurate? Actually, not so much.  I would still recommend the ASHRAE RP-1485 approach. One open-source implementation is in CoolProp: http://www.coolprop.org/fluid_properties/HumidAir.html#humid-air , with Excel wrappers.

If you need/want to change the dry air composition, the only option is the multi-fluid model. You can read more about that here: https://www.sciencedirect.com/science/article/pii/S014070071730381X

**Comment by EricLemmon** [comment]
Has this issue been resolved, and if so, can you close it?
