### ISSUE TITLE
Maximum number of times for calling REFPROP functions?

### ISSUE THREAD

**Issue by RyoAkasaka** [usnistgov/REFPROP-wrappers#357]
Hi everyone,

We face a problem in calling REFPROP functions on Excel. When a certain function is called many times (over a thousand times) in a single calculation, an error message (runtime error 13 type mismatch) appears, and Excel always gets freeze. The error always occurs in the following codes:

``` 
Tw_cond(l) = REFPROP("T", "water", "ph", "c", Pw, hw_cond(l))
sw_cond(l) = REFPROP("s", "water", "ph", "c", Pw, hw_cond(l))
``` 
After the error message is shown, a message box "The exception unknown software exception (0x007828c8) occurred in the application..." sometimes raises, and then Excel freezes.

Someone says, "REFPROP internally defines a maximum number of times that user's subroutines can call the functions. If calling
times exceed it, then an error will occur." Is what he says right? I've never heard of this.

### Versions

**REFPROP Version: 10.0
**Operating System and Version: Windows 10 64bit
**Access Method: Excel VBA (Office 365)

**Comment by ianhbell** [comment]
What are the values of hw_cond causing this problem?  I'll test this in C++/Python and see if I can reproduce this problem. What exact version of REFPROP 10.0 do you have?

**Comment by RyoAkasaka** [comment]
Hi Ian,

These two routines are called many times in a loop, changing hw_cond(1). When the error occurred, the hw_cond(1) value was 165.318756415877 kJ/kg. The version of REFPROP DLL is 10.0. Let me know if you need additional information.

**Comment by ianhbell** [comment]
Without an example of the complete set of steps to get to the failure, I don't know that we are going to be able to do anything here...

**Comment by ianhbell** [comment]
Are you calling this from a single function in VBA, or allowing Excel to do calls from cells?  If from Excel, my guess is that multiple threads are calling REFPROP at the same time, and that is causing collisions.

**Comment by RyoAkasaka** [comment]
Sorry for my late reply. The error always occurs in a subroutine of a large VBA program, so it is difficult to upload the complete set of steps to demonstrate the failure. We tentatively avoided the error using an alternative routine. As you pointed out, the VBA is called from Excel, and the error may come from collisions between threads.

**Comment by ianhbell** [comment]
If you can nail down the problem to a single-threaded VBA function, I think we have a shot to fix it. Otherwise, I think there is probably not much we can do.

**Comment by RyoAkasaka** [comment]
How can we implement a single-threaded VBA function? I want to try doing this.

**Comment by EricLemmon** [comment]
In your File menu, from the same place where you can use the "Save as..." command, there are some additional selections at the bottom labeled Tools or Options, can't remember.  In there is a Calculation menu, and under that is an option to use just one thread.

**Comment by RyoAkasaka** [comment]
Thank you so much. We'll try this!

**Comment by NickAtNight62** [comment]
What are the values of the two input conditions?  P (???) and H  (165kJ/kg)

These may not be the best choice for inlet conditions to provide.  There is a region where dual results are feasible.  This may be causing your failure.

If I try 500 MPa and 165 kJ/kg in Refprop, I get this error.  
Also get this error at 300 MPa.

![image](https://user-images.githubusercontent.com/58614082/119860651-2b17e180-bedc-11eb-9648-e4bf600ff20f.png)

**Comment by NickAtNight62** [comment]
Here is the PvH plot for Water. 
- The red line is for 165 kJ/kg.  Far to the left.
- The yellow line shows the region of dual results.
![image](https://user-images.githubusercontent.com/58614082/119861308-d9238b80-bedc-11eb-8dc2-045c4428503d.png)

**Comment by NickAtNight62** [comment]
So an pressure above 261 MPa may give you an issue.

![image](https://user-images.githubusercontent.com/58614082/119861748-5bac4b00-bedd-11eb-8aef-fd9c036165d9.png)

**Comment by ianhbell** [comment]
> In your File menu, from the same place where you can use the "Save as..." command, there are some additional selections at the bottom labeled Tools or Options, can't remember. In there is a Calculation menu, and under that is an option to use just one thread.

![image](https://user-images.githubusercontent.com/11966765/119874258-6a056180-bef3-11eb-9849-4ba72131d46a.png)
