### ISSUE TITLE
Attempt to Reset HMX.BNC by Python

### ISSUE THREAD

**Issue by Hadisdghni** [usnistgov/REFPROP-wrappers#359]
Dear Dr Bell,

My name is Mirhadi, a PhD student at the University of Western Australia. I'm trying to tune REFPROP BIPs for a binary mixture by using Python. Each time I rewrite my BIPs in HMX.BNC, I tried to force REFPROP to reset the caching flag and read the updated HMX.BNC file by using the FLAGSdll subroutine as below (described in https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll):

RP.FLAGSdll("Reset HMX",1)

However, REFPROP always read the first set of BIPs and never read the updated HMX.BNC files, even if I included the required script. Also, when I print the RP.FLAGSdll output, it shows that kFlag is 0, while it should be 1. I would be grateful if you could advise me on this problem.

Best Regards,
Mirhadi

**Comment by ianhbell** [comment]
Did you check out my code here: https://github.com/ianhbell/binfit ?  I just used it a few weeks ago to fit BIP.  Recommend you follow the approach there.

**Comment by ianhbell** [comment]
Is it an issue of the order of components you are using?

**Comment by EricLemmon** [comment]
You might need the beta or alpha version of the DLL that we have available to fix some of this.  Can you send Ian or me a private email and we will get that to you?  (eric.lemmon@nist.gov or ian.bell@nist.gov)

**Comment by Hadisdghni** [comment]
> Did you check out my code here: https://github.com/ianhbell/binfit ? I just used it a few weeks ago to fit BIP. Recommend you follow the approach there.

Thanks for coming back to me. Yes, I have checked it before to see if I can get any hint. Now, I'm trying to adjust the code for fitting BIPs to my VLE results; Although I'm following the prompts in README, I'm confronting some errors (using Thonny IDE, where some packages are not available). 


> Is it an issue of the order of components you are using?

I chose the same order of the binary as defined in HMX.BNC. For every single run of the script with no loops, I can change the BIPs and see the effects on my calculations. The problem is when I define a loop to examine different BIPs; it will only use the first BIPs set on HMX.BNC stored in the cache. The FLAGSDLL("Reset HMX", 1) do not force the REFPROP to reload the updated HMX.BNC file.

Also, when I checked in my script RP.RPVersion(), it showed ******, indicating that I might need a patch. Do you think it might be the issue causing the problem?

Thank you for your kind consideration.

Best Regards,
Mirhadi

**Comment by Hadisdghni** [comment]
> You might need the beta or alpha version of the DLL that we have available to fix some of this. Can you send Ian or me a private email and we will get that to you? ([eric.lemmon@nist.gov](mailto:eric.lemmon@nist.gov) or [ian.bell@nist.gov](mailto:ian.bell@nist.gov))

Dear Dr Lemmon,

Thanks for your advice. I will shortly send you an email. 

Best Regards,
Mirhadi

**Comment by ianhbell** [comment]
I think Thonny might be *too* simple for this case. Make sure that you can run the unmodified code without any issues or missing packages.

**Comment by ianhbell** [comment]
When you send the email I'll send the files.

**Comment by Hadisdghni** [comment]
Dear Dr Bell and Dr Lemmon,

I have resolved this issue based on your instruction and would like to thank you for your time and advice.
I'm closing this issue.

Best Regards,
Mirhadi
