### ISSUE TITLE
how to call refprop in C program

### ISSUE THREAD

**Issue by caidiner** [usnistgov/REFPROP-wrappers#363]
### Description

I changed the "main.cpp" in folder("REFPROP-headers-master", downloaded from https://github.com/CoolProp/REFPROP-headers) into C program and then ran this program. 
An error "REFPROP_IMPLEMENTATION can only be used in C++ "is reported.

I would like to ask if there is a refprop header file available for C program.

Code snippets of modified C program are attached.

``` 
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#define REFPROP_IMPLEMENTATION
#define REFPROP_FUNCTION_MODIFIER
#include "REFPROP_lib.h"
#undef REFPROP_FUNCTION_MODIFIER
#undef REFPROP_IMPLEMENTATION
int main()
{
    char *path = "c:/Program Files (x86)/REFPROP";
    char *DLL_name = "REFPRP64.dll";
    char *err;
    SETPATHdll(path, 255);
    int ierr = 0, nc = 1;
    char herr[255], hfld[10000] = "AMMONIA|WATER", hhmx[255] = "HMX.BNC", href[4] = "DEF";
    SETUPdll(nc,hfld,hhmx,href,ierr,herr,10000,255,3,255);
    if (ierr > 0) printf("This ierr: %d herr: %s\n", ierr, herr);
    {

        int ierr = 0;
        char herr[255];
        double z[20] = {1.0}, x[20] = {1.0}, y[20] = {1.0};
        double  T= 300, p = 101.325, d = -1, dl = -1, dv = -1, h = -1, s = -1, u = -1, cp = -1, cv = -1, q = -1, w = -1;
        TPFLSHdll(T, p, z, d, dl, dv, x, y, h,s,u,cp,cv,w,q,ierr,herr,255);
        if (ierr > 0) printf("This ierr: %d herr: %s\n", ierr, herr);
        printf("This d: %g mol/L\n", d);
        {
            double T = 293.15; double z[20] = { 0.20209999999999995, 0.7979}; int kph = 1;
            double P, rhol, rhov;
            double x[20], y[20];
            int ierr; char herr[255];
            SATTdll(T, z, kph, P, rhol, rhov, x, y, ierr, herr, 255);
            printf("This p: %g mol/L\n", p);
        }
    }
    return 0;
}
```
### Versions

**REFPROP Version:** [REFPROP version you are using]  
**Operating System and Version:** [Windows 10 home]  
**Access Method:** [include "REFPROP_lib.h" in C program ]  

### Additional Information

The error report in visual studio code is as follows:
![image](https://user-images.githubusercontent.com/52879906/114263640-68eaa480-9a19-11eb-96ab-cd4133860091.png)

**Comment by caidiner** [comment]
The REFPROP Version I'm using includes 10.0a and 9.0 .

**Comment by ianhbell** [comment]
Right, the implementation functions in that header are in C++, but mostly map nicely to C, without all the convenience of STL containers and algorithms, you'll have to do that work yourself. You can get all the pointers and typedefs from the header, which is the tricky bit.  Then you need to cast the pointers to the right type, and you should be in business.

**Comment by caidiner** [comment]
Mr. Bell, thanks for your kind advice, I will try it
