### ISSUE TITLE
Changes in Version 10

### ISSUE THREAD

**Issue by ahfazahmed** [usnistgov/REFPROP-wrappers#364]
Hi Ian, Eric, I have recently acquired Refprop ver 10. I have been a longtime user of ver 9 with Matlab and see a lot of changes with the new version. I need your help with few very basic things to start making use of the new ver. Issue 

1. I am getting '******' upon using RP.RPVersion() 
2. I have created new FLD files with PR EOS and to improve accuracy of density prediction I wish to use volume translation or PC-SAFT. I hope you will be able to help me with these

**Comment by ianhbell** [comment]
I reformatted your issue.  Please put your issue text in the body, not the title

**Comment by ianhbell** [comment]
For 1. please email me at ian.bell@nist.gov
For 2. volume translation can either be applied after the fact by you, or there is a similar option for Peng-Robinson.  There is no PC-SAFT implementation in REFPROP.

**Comment by ahfazahmed** [comment]
Hi Ian,
I went through the tutorial but i couldn’t find a method to calculate density and using volume translation with peng robinson

**Comment by ianhbell** [comment]
Please read the docs: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html .  You'll also want to read the docs of https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/PREOSdll
