### ISSUE TITLE
refprop excel add in installation issue

### ISSUE THREAD

**Issue by juansilvar17** [usnistgov/REFPROP-wrappers#366]
Sorry for asking for help here but its the only way to contact you!.

Could anyone help me to install de refprop excel add in. Im using windows 10 and office 365, i have tried to much but i didn´t get it, my machine is a thinkpad. Thank you so much.

**Comment by ianhbell** [comment]
Moved to REFPROP-wrappers

**Comment by ianhbell** [comment]
The add-in comes with REFPROP 10.  More installation instructions are here: https://github.com/usnistgov/REFPROP-wrappers/issues/105
