### ISSUE TITLE
Mole fractions asignments

### ISSUE THREAD

**Issue by adrianfernandez00** [usnistgov/REFPROP-wrappers#367]
Hi!

I'm just moving from the old versions of refprop to refprop 10 and I'm catching up with the new refprop calls.

I have one simple question: which is the difference between

 RP.REFPROPdll('PROPANE;0.2 * ISOBUTANE;0.6 * BUTANE;0.2','','TCEST',MOLSI,iMass,iFlag,0,0,{0.2 0.6 0.2})

and

RP.REFPROPdll('PROPANE * ISOBUTANE * BUTANE','','TCEST',MOLSI,iMass,iFlag,0,0,{0.2 0.6 0.2})

Thank you!

**Comment by ianhbell** [comment]
In theory there is no difference.  I strongly recommend against encoding the composition in the string.  Also, you should be aware that iMass doesn't always do what you think it should, so mole fractions are recommended to be used with the REFPROPdll function.

**Comment by adrianfernandez00** [comment]
Thank you!
