### ISSUE TITLE
environment building in python

### ISSUE THREAD

**Issue by ZhanchengHuang** [usnistgov/REFPROP-wrappers#370]
Hello， I am very thank you for your help.
I have questions in building environment 
my codes can not run in a new computer. I have installed refprop10.0 yet.
but a new error appears.
![屏幕截图(15)](https://user-images.githubusercontent.com/73510654/116527451-427ba300-a90d-11eb-939b-680b300cdfa6.png)

**Comment by ianhbell** [comment]
Looks like you need to set the environment variable ``RPPREFIX``.  Normally installation of REFPROP sets this variable, but you might need to either set it in your script with ``os.environ['RPPREFIX'] = "/some/path"`` or in your operating system

**Comment by ZhanchengHuang** [comment]
@ibell I succeeded in solving the problem at last. THANK YOU VERY MUCH!!!

**Comment by ianhbell** [comment]
Can you briefly say how you fixed the problem? And then close the issue?

**Comment by ianhbell** [comment]
And you're welcome

**Comment by ZhanchengHuang** [comment]
The version of refprop must be 10.0 in python. And  the environment variable RPPREFIX. may not automatically load. And you need to manually set the path to this variable, which is where the refprop is installed.
![image](https://user-images.githubusercontent.com/73510654/117232568-fde39080-ae53-11eb-9c34-907e093e6113.png)
