### ISSUE TITLE
Error 777 when calling SETFLUIDSdll

### ISSUE THREAD

**Issue by mnotarnicola** [usnistgov/REFPROP-wrappers#376]
### Description

I'm receiving an error code 777 when calling the SETFLUIDSdll using python through matlab.  

### Steps to Reproduce

```
addpath(genpath('C:\Program Files (x86)\REFPROP'));
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP\REFPRP64.DLL');
SI = RP.GETENUMdll(int8(0),'SI').iEnum;
RP.SETFLUIDSdll('Helium');
```

**Expected behavior:** Sets fluid using HELIUMD.FLD file.  Usually returns a 0 for success.

**Actual behavior:** Returning 777.

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Microsoft Windows [Version 10.0.18363.1556]
![SETFLUIDSdll_Error](https://user-images.githubusercontent.com/79946803/120664864-498c5880-c459-11eb-9631-cb9e3ed68a20.jpg)

**Access Method:** Python wrapper through MatLab.

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
I don't think the addpath command should be necessary if you have set up python properly.

Also, for ``SETFLUIDSdll``, once you have a failure, you should check ``ERRMSGdll``.  Example in Python, which works fine for me and demonstrates how to get error from SETFLUIDS.  

What exact version of REFPROP do you have?

```
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(r'C:\Program Files (x86)\REFPROP\REFPRP64.DLL')
SI = RP.GETENUMdll(0, 'SI').iEnum
print(RP.SETFLUIDSdll('Helium'))

SI = RP.GETENUMdll(0, 'SI').iEnum;
ierr = RP.SETFLUIDSdll('Heeeeeeeeeeelium')
print(RP.ERRMSGdll(ierr))
```
yields
```
0
[SETUP error 101] Error in opening file for component 1: filename = Heeeeeeeeeeelium.FLD
```

**Comment by mnotarnicola** [comment]
```
RP.ERRMSGdll(ierr)
```
yields
```
ans = 

  Python str with no properties.

    The REFPROP DLL you are using has expired. Please return to the Refprop website and download the latest installer.
```

I believe I had received a beta DLL a while back regarding another issue.  I just checked the link you had sent me and looks like you just updated the alpha DLL yesterday.  Looks like I should download 10.0.0.97 and replace the DLL?

**Comment by ianhbell** [comment]
Yes, that is right.  I was using 10.0.0 which is why my test worked.

**Comment by mnotarnicola** [comment]
Awesome I'm back in business.  Thanks!
