### ISSUE TITLE
Error in matlab

### ISSUE THREAD

**Issue by sjtupchu** [usnistgov/REFPROP-wrappers#38]
Sorry to bother you, but i have just met a problem "Error in refpropm (line 279)             if ~contains(lower(fluidName),'.fld')"  "
the version of my matlab is 2015a
thanks!

**Comment by ianhbell** [comment]
Please see #29

**Comment by ianhbell** [comment]
Your best solution is to upgrade, or use Python.

**Comment by sametgurgen** [comment]
I installed "Refprop beta version 10.0.0.61"
I have used Matlab R2015a. 
My computer is 64 bit.
I want to use Refprop with MATLAB.
But  I have a problem. 
          Error message: Undefined function 'contains' for input arguments of type 'char'.

           Error in refpropm (line 279)
            
                if ~contains(lower(fluidName),'.fld')

![Ekran Alıntısı](https://user-images.githubusercontent.com/48438708/54121382-54d3b380-440b-11e9-8d91-02c74e762e30.JPG)

Can you help me?

**Comment by ianhbell** [comment]
Please don't hijack existing issues, rather open a new one.  The ``refpropm`` interface is deprecated and no longer supported, but it should still work.  Have you tried the Python interface?
