### ISSUE TITLE
REFPROP "Setup error 101" in OSX 

### ISSUE THREAD

**Issue by gautam-subburaj** [usnistgov/REFPROP-wrappers#381]
@ibell @EricLemmon 
I have recently started using MAC and have installed REFPROP using the instruction from 
[https://github.com/usnistgov/REFPROP-cmake](url).

But when i try to run the code in python with refprop, it shows '[SETUP error 101] Error in opening file for component 1: filename = WATER.FLD'

I have put the FLUIDS and MIXTURES folder in the given directory where i have created libraries using cmake-
/Users/gautams/REFPROP-cmake/

This folder also contains the build where the **librefprop.dylib** is present

Please help me in resolving this issue.

**Comment by ianhbell** [comment]
Please show the code you ran, and show the contents of your REFPROP home folder.

**Comment by gautam-subburaj** [comment]
Code from python
`from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary    
RP = REFPROPFunctionLibrary('/Users/gautams/REFPROP-cmake/build')
Units = RP.GETENUMdll(0,"SI WITH C").iEnum

P=RP.REFPROPdll("WATER",'tq','p',Units, 0,0,100, 0, [1.0])
print(P)`

**Contents of my REFPROP-cmake folder**

CMakeLists.txt       README.md            externals/
FLUIDS/              build/               generate_aliases.py
FORTRAN/             docker/              mixtures/

**Comment by ianhbell** [comment]
FLUIDS needs to be inside build folder

**Comment by gautam-subburaj** [comment]
**Contents of my Build Folder**

CMakeCache.txt       
REFPROP.h            
libquadmath.a
CMakeFiles/         
REFPROP.h.stamp      
librefprop.dylib*
FLUIDS/              
aliases_string.txt   
Makefile             
cmake_install.cmake  

I have tried doing the same with the FLUIDS folder inside the build, but got the same error.

**Comment by ianhbell** [comment]
what are the contents of FLUIDS?

**Comment by gautam-subburaj** [comment]
it contains all the .FLD files.
It also contains the WATER.FLD file as well.
I have confirmed this.

**Comment by ianhbell** [comment]
Are the file names all uppercase?

**Comment by gautam-subburaj** [comment]
Yes

**Comment by ianhbell** [comment]
Maybe you also need the MIXTURES folder? I don't think so, but...

**Comment by ianhbell** [comment]
I don't usually have this problem, but is it possible that the line endings in WATER.FLD are causing problems? Windows and OSX use different line endings.

**Comment by gautam-subburaj** [comment]
I got the same error after i have copied the MIXTURE folder to the build folder.

**Comment by ianhbell** [comment]
You also need a SETPATH:
```python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary    
home = '/Users/gautams/REFPROP-cmake/build'
RP = REFPROPFunctionLibrary(home)
RP.SETPATHdll(home)
Units = RP.GETENUMdll(0,"SI WITH C").iEnum

P=RP.REFPROPdll("WATER",'tq','p',Units, 0,0,100, 0, [1.0])
print(P)
```

**Comment by gautam-subburaj** [comment]
Thanks it works. I have not used SETPATHdll() command.

**Comment by ianhbell** [comment]
You need to on non-windows platforms.  On windows, a registry variable is set, and this step is not usually needed.
