### ISSUE TITLE
CoolProp and REFPROP use in Mac OS

### ISSUE THREAD

**Issue by gautam-subburaj** [usnistgov/REFPROP-wrappers#382]
@ianhbell 
I have installed the REFPROP in Mac OS and its working in python.
My home directory is **home = '/Users/gautams/REFPROP-cmake/build'**
Next it tried to use CoolProp with REFPROP in it.
it shows the following error- 
`>> PropsSI('T','P',101325,'Q',0,"REFPROP::Water")

Traceback (most recent call last):
  File "<pyshell#16>", line 1, in <module>
    PropsSI('T','P',101325,'Q',0,"REFPROP::Water")
  File "CoolProp/CoolProp.pyx", line 377, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 457, in CoolProp.CoolProp.PropsSI
  File "CoolProp/CoolProp.pyx", line 344, in CoolProp.CoolProp.__Props_err2
ValueError: Initialize failed for backend: "REFPROP", fluid: "Water" fractions "[ 1.0000000000 ]"; error: fluid directories "FLUIDS" or "fluids" could not be found in the directory [/opt/refprop] : PropsSI("T","P",101325,"Q",0,"REFPROP::Water")
`
How do I resolve this issue.

**Comment by ianhbell** [comment]
See: http://www.coolprop.org/coolprop/REFPROP.html#path-issues

**Comment by gautam-subburaj** [comment]
I could not solve the issue.
Since I am new to linux and Mac, can you pls help me with this.

**Comment by gautam-subburaj** [comment]
Thanks I have resolve the issue by just copying the header file REFPROP.h to /usr/local/include

**Comment by ianhbell** [comment]
Did you see the link I sent? You need to set a configuration variable in CoolProp to tell it where to look for REFPROP.  Copying the header file is not needed, and not recommended.
