### ISSUE TITLE
Phase identification

### ISSUE THREAD

**Issue by RinaldoMiorini** [usnistgov/REFPROP-wrappers#383]
### Description

I am using REFPROP10 with Matlab and Excel. I would like to get the phase of a fluid based on pressure/temperature or any other combination of independent parameters. I tried 'PIP' as an output identifier for ALLPROPSdll but I get a number so I guess that is not the right identifier. How do I get the phase (solid, liquid, saturated, superheated, supercritical)?

### Steps to Reproduce

In EXCEL:
=REFPROP("PIP","carbondioxide","TP","SI",283.2,4.927,0)
Output: 9.9269

**Expected behavior:** [What you expect to happen]
'saturated' or 'liquid'

**Actual behavior:** [What actually happens]
Output: 9.9269

### Versions

**REFPROP Version: 10.0
**Operating System and Version: Windows 10 Enterprise 64 bit
**Access Method: Excel, Matlab

**Comment by ianhbell** [comment]
In MATLAB, you can get the "PHASE" parameter from REFPROP function, that will return what you want. Example in Python:
```python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = os.environ['RPPREFIX']
RP = REFPROPFunctionLibrary(root)

T = 300; z = [1.0]
r = RP.REFPROPdll("PROPANE", "TQ", "PHASE", RP.MOLAR_BASE_SI, 0,0, 300,0,z)
print(r.hUnits)
```
yields
```
Saturated liquid
```

**Comment by ianhbell** [comment]
I don't know if you can do the same in Excel.

**Comment by RinaldoMiorini** [comment]
Thanks!

Yes, I confirm that the Excel command:

=REFPROP("PHASE","carbondioxide","TP","SI",285.2,4.789,0)

returns the string

Subcooled liquid

Regards,
Rinaldo
