### ISSUE TITLE
Property calculations with pandas dataframe

### ISSUE THREAD

**Issue by dokeun98** [usnistgov/REFPROP-wrappers#384]
Hello

I'm dealing with time-series data using python and trying to create density data from the temperature and pressure of a fluid.

With the REFPROP ver 9.1 and Pandas apply() method, it works but takes too long time to calculate because of big data size. 

From a [post](https://engineering.upside.com/a-beginners-guide-to-optimizing-pandas-code-for-speed-c09ef2c6a4d6), I tried the vectorization but got an error as below

**Main Code**(Success but slow)
`df['rho', 'kg/m3'] = df.apply(lambda x:density_Air(x['T111', 'K'], x['P111','bara']), axis=1)`

**Main Code**(Fail)
`df['rho', 'kg/m3'] = density_Air(df['T111', 'K'].values, df['P111','bara'].values)`

**Function Code**

    def density_Air(Temp, Pressure_bar):
       import os
       import ctREFPROP.ctREFPROP as ct

       RP = ct.REFPROPFunctionLibrary(os.environ['RPPREFIX'],'dll')
       RP.SETPATHdll(os.environ['RPPREFIX'])
    
       z = [~~~] # volume fraction, ref AIR.mix
       ierr, herr = RP.SETUPdll(n, '~~~.FLD', 'HMX.BNC', 'DEF')
    
       #D, Dl, Dv, x, y, q, e, h, s, Cv, Cp, w, ierr, herr = RP.TPFLSHdll(Temp,Pressure,z)
       Pressure_kPa = Pressure_bar*100
    
       result = RP.TPFLSHdll(Temp,Pressure_kPa,z)  # result: D, Dl, Dv, x, y, q, e, h, s, Cv, Cp, w, ierr, here
       wm = RP.WMOLdll(z)                          # molar weight
       rho = result[0]*wm #kg/m3
    
    return rho

**Result**

> TypeError                                 Traceback (most recent call last)
<ipython-input-200-0947b3eee76a> in <module>
     30 
---> 31 df['rho', 'kg/m3'] = density_Air(df['TT111', 'K'].values, df['PT111','barg'].values)
     32 
     33 df.head()
~\Documents\Study\REFPROP\REFPROP.py in density_Air(Temp, Pressure_bar)
     18     Pressure_kPa = Pressure_bar*100
     19 
---> 20     result = RP.TPFLSHdll(Temp,Pressure_kPa,z)  # result: D, Dl, Dv, x, y, q, e, h, s, Cv, Cp, w, ierr, herr
     21     wm = RP.WMOLdll(z)                          # molar weight
     22     
C:\ProgramData\Anaconda3\lib\site-packages\ctREFPROP\ctREFPROP.py in TPFLSHdll(self, T, P, z)
   3326         D,Dl,Dv,x,y,q,e,h,s,Cv,Cp,w,ierr,herr = TPFLSHdll(T,P,z)
   3327         """
-> 3328         T = ct.c_double(T)
   3329         P = ct.c_double(P)
   3330         z = (len(z)*ct.c_double)(*z)
TypeError: only size-1 arrays can be converted to Python scalars

I wonder if REFPROP ver10 has no issue with the problem.  

Addition

From the version 10 document, I knew that TPRHO is faster than TPFLSH.

> Flash calculation given temperature, pressure, and bulk composition. This routine accepts both single-phase and
two-phase states as inputs; for single-phase calculations, the subroutine TPRHO is much faster.

So I looked for the TPRHOdll tooltip and found that D is also defined as an input parameter.

> Definition : TPRHOdll(T, P, z, kph, kguess, D)
> D,ierr,herr = TPRHOdll(T,P,z,kph,kguess,D)

Is it correct? Whatever I put any value for D as an input, result(density) is not different. (I tested it with a colleage's v10)

**Comment by ianhbell** [comment]
First thing I would try is to move 
```
import os
import ctREFPROP.ctREFPROP as ct

RP = ct.REFPROPFunctionLibrary(os.environ['RPPREFIX'],'dll')
RP.SETPATHdll(os.environ['RPPREFIX'])

z = [~~~] # volume fraction, ref AIR.mix
ierr, herr = RP.SETUPdll(n, '~~~.FLD', 'HMX.BNC', 'DEF')
```
out of your function, that need only be done once.  In theory all those steps would be cached, but there is still *some* overhead.  I use apply with pandas dataframes all the time.  If you have really huge timeseries, you might be running up against the flash calculation timing.  REFPROP is not thread-safe, so I can't recommend parallelism as a solution.

Can you tell me how big your timeseries is, with how many components, and how long it takes to ``apply``?

In TPRHO, check out the docs for ``kguess`` parameter, controls what is done with D

**Comment by dokeun98** [comment]
Dear ianhbell

**1. About the time**
The code you pointed out caused the problem. 

The test data size was 22Mb and 240 sec took with the previous one. But it took 0.9 sec with your suggestion. 

**2. About the TPRHOdll**
The code I typed was

`result = RP.TPRHOdll(Temp, Pressure_kPa, z, 1, 0, 1000)`

The kguess flag was 0 for the "No first guess for D provided" option

I really appreciate your generosity and kindness.

**Comment by ianhbell** [comment]
1. Good, that makes sense and matches my experience.
2. Right, and if you provide guess values then density is input and output variable
