### ISSUE TITLE
MINI-REFPROP:  Error using calllib Array must be numeric or logical

### ISSUE THREAD

**Issue by mfochesato** [usnistgov/REFPROP-wrappers#387]
I am using MINI-REFPROP with Matlab legacy refpropm, but when I try this command:

refpropm('H', 'T', 600, 'P', 1.1 * 100, 'NITROGEN.FLD','C:\Program Files (x86)\REFPROP\FLUIDS');

I get the error "Error using calllib Array must be numeric or logical or a pointer to one".

I have already replaced ~ with dummy in the calllib callback as suggested in previous issues, but I did not solve the issue.

How can I solve this problem in MINI-REFPROP? Thanks

**Comment by ianhbell** [comment]
refpropm is deprecated.  Use the python interface: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB

**Comment by mfochesato** [comment]
Thanks for the fast reply! I am now switching to the python interface, but when trying to use the environment with:
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')

I get the following error:
 Python Error: ValueError: No shared libraries were found in the folder "C:\Program Files
(x86)\REFPROP" with the extension ".dll"

I checked the REFPROP folder (which I got from MINI-REFPROP intallation) and it containes a refprop.dll file (it also containes other libraries with the .dll extensions, such as MSSTDFMT.DLL and MSVBVM60.DLL, I though it was a case-sensitive problem so I renamed them in lower case, but still I got the same error).

**Comment by ianhbell** [comment]
Bitness needs to match.  If you use MINI-REFPROP, you need to use 32-bit Python and 32-bit MATLAB.
