### ISSUE TITLE
saturated liquid enthalpy derivative with p

### ISSUE THREAD

**Issue by fuxinniu** [usnistgov/REFPROP-wrappers#388]
Hi Ian,

I am trying to calculate the derivative of saturated liquid enthalpy with respect to pressure. 
First, I tried coolprop by this
h_liq_der[i] = CP.PropsSI('d(H)/d(P)|H','H',h_liq[i],'P',p_min_crit[i],'R134A')
But it does not work.

When I tried to use DHDP_T from REFPROPdll, the result is not what I expected. Is there something wrong with this call?

Molar = RP.REFPROPdll("R134a", "PQ","M", RP.MOLAR_BASE_SI, 0, 0, 26665, 0, [0]).Output[0]
a= RP.REFPROPdll("R134a", "PQ","DHDP_T", RP.MOLAR_BASE_SI, 0, 0, 26665, 0, [0]).Output[0]*26665/Molar

So appreciate your help. 

Frank

**Comment by ianhbell** [comment]
Yes, you need the other function: http://www.coolprop.org/coolprop/LowLevelAPI.html#two-phase-and-saturation-derivatives

**Comment by fuxinniu** [comment]
Hi Ian,

I can't get result after coding this. Would you help me correct it?

CAbs = CoolProp.AbstractState("R134a")
CAbs.update(CoolProp.PQ_INPUTS, 20000, 0)
a = CAbs.first_saturation_deriv(CoolProp.iH, CoolProp.iP)
print(a)

Error
__cinit__() takes exactly 2 positional arguments (1 given)

So appreciate that. 

Frank

**Comment by ianhbell** [comment]
This should work now:
```python
import CoolProp
CAbs = CoolProp.AbstractState("HEOS", "R134a")
CAbs.update(CoolProp.PQ_INPUTS, 20000, 0)
a = CAbs.first_saturation_deriv(CoolProp.iHmolar, CoolProp.iP)
```
but I forgot that I never implemented this for the REFPROP backend.

**Comment by fuxinniu** [comment]
Hi Ian

So appreciate your help and quick reply. 

The result make sense right now. 

Thanks again. 

Frank
