### ISSUE TITLE
CP at critical point

### ISSUE THREAD

**Issue by fuxinniu** [usnistgov/REFPROP-wrappers#390]
Hi Ian,

I got negative value of CP at critical point of R134a. 

dcrit = RP.REFPROPdll(RefName, "CRIT","H;T;V;CP;TCX;VIS;STN", RP.MOLAR_BASE_SI, 0, 0, 0, 0, [0]).Output[0:7]
CP = -32873058.34090567

Is this call correct?

Thanks

Frank

**Comment by ianhbell** [comment]
Runnable example please

**Comment by fuxinniu** [comment]
import os
import  numpy as np

from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])

dcrit = RP.REFPROPdll("R134a", "CRIT","H;T;V;CP;TCX;VIS;STN", RP.MOLAR_BASE_SI, 0, 0, 0, 0, [0]).Output[0:7]
print(dcrit[3])


Thanks

Frank

**Comment by EricLemmon** [comment]
I used the GUI to plot Cp vs. density and indeed there is a small region very close to the critical point where Cp is (incorrectly) negative.  This is shown in the plot below.  The lines are at 374.21, 374.211, 374.212, and 374.213 K, with the red line being the critical point (374.21 K).  The first two lines show a region where Cp is negative.  At T>374.212 K, Cp appears to behave properly.  This is a problem in the equation of state, but also realize that this equation is soon to be 30 years old.  It is an impressive equation for having been done that long ago.


![image](https://user-images.githubusercontent.com/42392984/129100608-946ae174-5c36-4988-942f-ab41328a7081.png)

**Comment by ianhbell** [comment]
Thanks @EricLemmon .  This problem seems to occur for a number of EOS, including propane and R1234ze(E) at first glance, but R1234yf seems good.

**Comment by fuxinniu** [comment]
Thank you @ianhbell @EricLemmon.

I will do the interpolation for this point. 

Thanks

Frank
