### ISSUE TITLE
Derivative calculation question 

### ISSUE THREAD

**Issue by fuxinniu** [usnistgov/REFPROP-wrappers#391]
Hi Ian,

Just want to make sure the call of the derivative functions correct or not. 

Such as DDDT, DDDP, DHDT_P, DHDP_T, I can use PH as inputs to calculate all these derivation, is that correct?

Is there limitation in single phase (liquid or vapor) and two phase ?

import os
import  numpy as np
import csv
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])

DDDT_P = RP.REFPROPdll("R134a", "PH","DDDT;DDDP;DHDT_P;DHDP_T", RP.MOLAR_BASE_SI, 0, 0, 26664.448, 7000, [0]).Output[0]
print(DDDT_P)

So appreciate that. 

Frank

**Comment by ianhbell** [comment]
Single-phase only.  Your inputs are solid though, as you would see if you checked r.ierr, which is 17 in this case.

And via CoolProp:
```python
import os
import numpy as np
import csv
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
print(RP.RPVersion())

r = RP.REFPROPdll("R134a", "PH","T;D;DDDT;DDDP;DHDT_P;DHDP_T", RP.MOLAR_BASE_SI, 0, 0, 26664.448, 7500, [0])
print(r.ierr)
print(r.Output[0:6], r.q)

import CoolProp.CoolProp as CP
for backend in ['REFPROP','HEOS']:
    print(backend)
    print('---')
    AS = CP.AbstractState(backend,'R134a')
    AS.update(CP.HmolarP_INPUTS, 7500, 26664.448)

    print(AS.first_partial_deriv(CP.iDmolar,CP.iT,CP.iP))
    print(AS.first_partial_deriv(CP.iDmolar,CP.iP,CP.iT))
    print(AS.first_partial_deriv(CP.iHmolar,CP.iT,CP.iP))
    print(AS.first_partial_deriv(CP.iHmolar,CP.iP,CP.iT))

```
yields
```
10.0.0.02
0
array('d', [171.5726197124396, 15549.961641608883, -25.876503321169682, 1.1869006124085593e-05, 120.79786753862385, 4.594789959198896e-05]) -0.2578469730993131
REFPROP
---
-25.876503321169675
1.1869006124085593e-05
120.7978675386238
4.594789959198897e-05
HEOS
---
-25.876506419498202
1.1869007505057864e-05
120.79803056347336
4.594788811460347e-05
```

**Comment by fuxinniu** [comment]
Thank you Ian.
