### ISSUE TITLE
Two phase properties

### ISSUE THREAD

**Issue by fuxinniu** [usnistgov/REFPROP-wrappers#393]
Hi Ian,

Can't get two phase properties for given PH or TD? How to get CP;CV;TCX;VIS;W?

Thanks a lot.

Frank

import os
import  numpy as np
import csv
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
General = RP.REFPROPdll("R134a", "PH","T;V;S;CP;CV;TCX;VIS;W", RP.MOLAR_BASE_SI, 0, 0, 26664.44791479838, 13867.55, [0])
print(General.Output[0:8])
print(General.q)
print(General.herr)

General = RP.REFPROPdll("R134a", "TD","CP;CV;TCX;VIS;W", RP.MOLAR_BASE_SI, 0, 0, 221.46073273480454, 1/0.0007485160543592842, [0])
print(General.Output[0:5])
print(General.herr)

**Comment by ianhbell** [comment]
Right.  Some of these are not defined for two-phase states.  Let's first talk about thermodynamic properties (CP,CV,W).  For c_v, there is a definition for two-phase states (from the book of Roland Span, page 44):

![image](https://user-images.githubusercontent.com/11966765/129565369-b2adbc05-e5f9-461d-8515-a0e76c759f27.png)

For CP and W, no such relation exists and they are simply not defined.

For the transport properties, you have one answer for the liquid, and another for the vapor, but there is no single answer for how to calculate a two-phase mixture viscosity or thermal conductivity.  In the literature you will find many approximate answers to that question.

**Comment by fuxinniu** [comment]
Thanks for your explanation. That is helpful.

**Comment by fuxinniu** [comment]
Hi Ian,

The documents indicated ABFLSHdll can get CV by using CV2PK. 

I failed to calculate it. Would you provide an example to use CV2PK?

Thanks a lot.

Frank

![image](https://user-images.githubusercontent.com/58092272/130521512-11da5881-5bab-4a5a-b8af-b0769e11512a.png)

**Comment by ianhbell** [comment]
In theory the input key should be (https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html): 

![image](https://user-images.githubusercontent.com/11966765/130522490-4308fa8c-dba4-4925-a4c6-df172a39cf95.png)

but that doesn't work (which is a bug).

**Comment by ianhbell** [comment]
But we can close this issue for now...
