### ISSUE TITLE
Proper Syntax/Method to call REFPROP Calculations within VBA Excel Code

### ISSUE THREAD

**Issue by Col9** [usnistgov/REFPROP-wrappers#394]
### Description

I successfully added the REFPROP add-in to my excel sheet and can use the =REFPROP(...) Function within the sheet itself to calculate anything I might need. However, I want to use the REFPROP calculations with the VBA code to be able to define certain variables, use if statements and for loops, etc. The answer is probably extremely obvious, but I cannot figure out what syntax or method I need to use to be able to use REFPROP calculations in the VBA code.  I'll include a screenshot as an example of one method I've tried (the standard method for using spreadsheet functions in VBA), and I've tried other methods, but nothing seems to work. Again, it's probably a simple answer that I overlooked somewhere, but any help would be appreciated. Thanks! 

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 10
**Access Method:** Excel

![image](https://user-images.githubusercontent.com/89269023/130266810-dae412ee-152b-4e59-af9c-6bf5f9831e64.png)

**Comment by Col9** [comment]
![image](https://user-images.githubusercontent.com/89269023/130288549-7f56ab70-b546-4403-9bd2-076de469ac02.png)

So to clarify:
hfld = fluid name
hin = input(s)
hout = expected output(s)
iUnits = Units indicator (e.g. "SI BASE UNITS")
iMass = Mass units
iFlag = ??
a = ??
b = ??
z() = ??
Output() = Output again?
hUnits = units again?
q = ??
ierr = ??
herr = ??

And could I then set that "Call REFPROP (...)" value as a variable? Sorry for the confusion, and thanks for the response!

**Comment by EricLemmon** [comment]
Hopefully this will give you all the information you need for the input/output variables.  If not, let us know.

https://www.nist.gov/system/files/documents/2018/05/23/refprop10a.pdf

**Comment by ianhbell** [comment]
There is also an example in the VBA code itself in the function called ''REFPROPexample"
