### ISSUE TITLE
call refprop from matlab 

### ISSUE THREAD

**Issue by LouisLamarche** [usnistgov/REFPROP-wrappers#395]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

**REFPROP Version:** [REFPROP version you are using]  
**Operating System and Version:** [OS you are running REFPROP on]  
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
Please see https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB

**Comment by LouisLamarche** [comment]
Hello 
I was using refpropm.m with matlab but since I changed to refprop 10 it does not work anymore ( forrtl: severe (59): list-directed I/O syntax error,) I saw  that now I have to use python. I followed all the instructions but when I write 
>> RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP\')
I receive the error : 

Python Error: ValueError: Too many loadable shared libraries were found in the folder
"C:\Program Files (x86)\REFPROP\"; obtained libraries were: ['C:\\Program Files
(x86)\\REFPROP\\refprp64.dll', 'C:\\Program Files
(x86)\\REFPROP\\refprp64_thunk_pcwin64.dll'].  You must provide an absolute path to the shared
library you would like to load. 


I tried 
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP\refprp64.dll')

it seems to work but if I write 

>> RP.RPVersion()
Error using ctREFPROP>REFPROPdll (line 2532)
Python Error: ValueError: The function REFPROPdll could not be loaded from the shared
library.

Error in ctREFPROP>RPVersion (line 3742)

Finally I tried: 

>> RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP\refprop.dll')
Error using __init__ (line 373)
Python Error: OSError: [WinError 193] %1 n’est pas une application Win32 valide

Error in ctREFPROP>REFPROPFunctionLibrary (line 164)

ANy hints ? I use matlab (R2020b) ( 64 bits) 
Thank you 
Louis Lamarche

**Comment by ianhbell** [comment]
You could rename the thunk file to something else with a different file extension.  That's the most reliable solution.  I don't understand why REFPROPdll couldn't be loaded.  Are you sure you successfully installed REFPROP 10 to this path? More likely sounds like you somehow still have REFPROP 9.x.

**Comment by ianhbell** [comment]
Also, I just uploaded a version (0.10.2) that should fix this thunk issue (I should have done that long ago).  You'll want to update your python interface.

**Comment by LouisLamarche** [comment]
Thank you for your answer, 
When I remove the thunk file, 

RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')

creates now a REFPROPInstance  but associated to refprp64.dll. If I remove refprp64.dll, it does not load refprop.dll 

Python Error: ValueError: No shared libraries were found in the folder "C:\Program Files
(x86)\REFPROP\" with the extension ".dll"

although it is in the folder. THe program refprop.exe works fine and is associated to refprop.dll version 10.0 
Thank you

**Comment by ianhbell** [comment]
Well, if you have 64-bit computer, then you should:
1) replace the thunk file
2) update ctREFPROP to 0.10.2
3) try again

The GUI is 32-bit, and therefore always uses refprop.dll.  Anything else will use the bitness of your MATLAB (almost certainly 64-bit).

**Comment by ianhbell** [comment]
And in 64-bit land, you'll want REFPRP64.DLL

**Comment by LouisLamarche** [comment]
Thank you 
Now it loads the dll correctly.  However 
RP.RPVersion() returns 
9.111 
I guess that is why I had the fortl error problems. It is probably because the REFPRP64.DLL is associated with version 9 ?

**Comment by LouisLamarche** [comment]
I just found the new REFPRP64.DLL. Now it works thank you very much
