### ISSUE TITLE
Calling Mixtures in Python using REFPROP

### ISSUE THREAD

**Issue by saadsaleem2005** [usnistgov/REFPROP-wrappers#397]
I am trying to call mixture properties using the attached wrapper file (change the file extension to .py from .txt if you wish to run it). I recieve the following error:
RefpropdllError: '[SETUP error 101] error in opening file for component #  1; filename = ('

What is the best way to call mixtures in Python via Refprop?
### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 10
**Access Method:** From Python
[ref wrapper.txt](https://github.com/usnistgov/REFPROP-wrappers/files/7073906/ref.wrapper.txt)

**Comment by saadsaleem2005** [comment]
Note- this works in conjuction with the old REFPROP wrapper of 2012 developed by B.J. Thelen. If mixtures don`t work with it, I would be happy to be pointed to a newer version of the code!
[REFPROP.txt](https://github.com/usnistgov/REFPROP-wrappers/files/7074200/REFPROP.txt)

**Comment by ianhbell** [comment]
This is the new wrapper I made: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python

**Comment by saadsaleem2005** [comment]
Thanks for this! My heat exchanger modelling code is mainly written so that it gets props using the old wrapper, so I am trying if I can get away with either modifying it, or using the cool prop integration.
I tried calling R452B using the basic CoolProp call:

``from CoolProp.CoolProp import PropsSI

T=PropsSI( 'T', 'P', 1002, 'H', 520306.6807,"R452B")
print(T)''

**Comment by ianhbell** [comment]
Right, you need the mixtures: https://github.com/usnistgov/REFPROP-issues/issues/358#issuecomment-872394368

Strongly recommend to use the new wrapper, or at least if you are using CoolProp, to use the low-level interface. MUCH faster for REFPROP because it avoids a whole lot of shared library loading.
