### ISSUE TITLE
Compile Refprop Fortran files to create RGP data generator  

### ISSUE THREAD

**Issue by soumitrdey** [usnistgov/REFPROP-wrappers#398]
Hi, 
I am working on compiling a RGP file generator Fortran code  (F90) using gfortran (MinGw) installed on Windows 10. I have Refprop    ver 9.1.1 installed and using the files under "Fortran" directory to make the object /exe files with the mail code.

I keep getting an "Unexpected end of File" error from two Fortran files "COMMONS.FOR" and COMTRN.FOR" that are Refprop file and are required by the code. Not sure how to debug the same.  Appreciate any help on this issue.

Regards, 
Soumitr 

![image](https://user-images.githubusercontent.com/50708071/131728720-949f381e-e2e7-4b9b-af43-14ace0edbb75.png)

**Comment by ianhbell** [comment]
What is an RGP file?

**Comment by soumitrdey** [comment]
Eric, 
Thanks for your reply. I did that, but I still have issues with compile, as all other .FOR files are looking for the include file "commons. For". Should I go through each of the .FOR codes and comment out the statement include commons. For ? attached below is the screen capture without the two include files.
![image](https://user-images.githubusercontent.com/50708071/131742432-1b10dd31-ea33-4b7e-8f7d-246990624cba.png)

**Comment by EricLemmon** [comment]
Definitely don't comment them out, they are required!  In your compiler you can sometimes set an option that tells it where to look for the include files.  You can also change the lines in the fortran files to include the path, such as this:

      include 'COMMONS.FOR'

to this:

      include 'c:\Program Files (x86)\REFPROP\FORTRAN\COMMONS.INC'

Note that I also changed .FOR to .INC to make your life easier.  Just be sure to rename the two .FOR files.  Once done you can then use *.FOR again as you initially did in the compiler options.

**Comment by soumitrdey** [comment]
@ Ian, a RGP file is a Refprop material property file that is used in ANSYS CFX ( Computational Fluid Dynamics tool) so that we can use NIST material properties for calculations instead CFX material library. Also i actually meant an extension with rgp - "fluid.rgp"  thus called it a RGP file, sorry for the confusion.

**Comment by ianhbell** [comment]
That could give you a shared library, or a static library (I think).  In any case, I'd be happy to fix the build system to meet your needs.   Also, compiling with intel fortran might remove some pain points with mingw.

**Comment by soumitrdey** [comment]
Ian, i have requested a licensed copy (Intel Fortran) , but wanted to test if the main code was working thus was using Mingw, should have my copy in a few days. 

@Eric, yes I have already renamed those two files as .INC and saved then under the folder I am currently running my main source code. Will follow your other recommendation and let you know how it goes.

**Comment by ianhbell** [comment]
You no longer need a license, you can freely download the HPC kit from Intel.  It's a mammoth download though.

**Comment by ianhbell** [comment]
Can you post your ``rgpnist.f90`` code and I can test on my side and get this working?

**Comment by ianhbell** [comment]
Is that your code? Are you allowed to post it?

**Comment by ianhbell** [comment]
Ok, good.  I will find the time to fix REFPROP-cmake to get this to compile on my machine, once the website for Intel is repaired.

**Comment by ianhbell** [comment]
I think fixing this in REFPROP-cmake will be useful to people (and me!), but not trivial, so I'm going to take the time to do this properly. In the meantime, I recommend to follow Eric's recommendations with a slight modification.  I would make a list of files to compile in a batch script, and remove from the list of files to be compiled the common block files that should not be compiled. It would read something like:

```batch
gfortran -c SETUP.FOR
gfortran -c FLASH.FOR
... (fill in as needed, perhaps building this list from a call to dir at the command line)
gfortran -o RGP -c RGPNIST.FOR *.o
```

**Comment by soumitrdey** [comment]
Ian, thanks for the recommendations.

**Comment by ianhbell** [comment]
Please let us know how this works for you

**Comment by soumitrdey** [comment]
Eric and Ian, 
I am able to compile the code with the above recommendations. I tested it out and the code works as intended. Thanks so very much for your support. :)

Regards, 
Soumitr

**Comment by soumitrdey** [comment]
Code works as intended, all NIST files (fluid folder and Fortran files) are required for compiling .  Works on Windows (win 10), have not validated on LINUX or MAC OS.
