### ISSUE TITLE
mixture saturated property close the dome

### ISSUE THREAD

**Issue by fuxinniu** [usnistgov/REFPROP-wrappers#399]
Hi Ian,

Can't get the mixture property close the dome. 

import os
import  numpy as np
import csv
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])

r_sat_liq = RP.REFPROPdll("R407c", "PQ","HLIQ;VLIQ", RP.MOLAR_BASE_SI, 0, 0, 4391507.40643784, 0, [0])
print(r_sat_liq.herr)
r_sat_vap = RP.REFPROPdll("R407c", "PQ","HVAP;VVAP", RP.MOLAR_BASE_SI, 0, 0, 4391507.40643784, 1, [0]).Output[0:2]
print(r_sat_vap)

Any suggestions?

So appreciate that. 

Frank

**Comment by EricLemmon** [comment]
Do a search in this github website for "SATGV", it should return about six hits.  Take a look at these and perhaps they will help you out.

**Comment by fuxinniu** [comment]
Hi Eric,

I did not figure out the solution in python wrapper. You mentioned the density should be used as input to calculate saturated property. 

In my case, the known inputs are P and Q. Would you please provide an python example to calculate the mixture properties based on R407c?

Thanks a lot. 

Frank

For pure refrigerant, it works well to calculate these properties by P and Q. 

    r_liq = RP.REFPROPdll(RefName, "PQ","HLIQ;TLIQ;VLIQ;CPLIQ;TCXLIQ;VISLIQ;STN", RP.MOLAR_BASE_SI, 0, 0, p, 0, [0])
    r_vap = RP.REFPROPdll(RefName, "PQ","HVAP;TVAP;VVAP;CPVAP;TCXVAP;VISVAP", RP.MOLAR_BASE_SI, 0, 0, p, 1, [0])

**Comment by ianhbell** [comment]
You want to enable the saturation spline.  Docs here: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll

Like so:
```python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])

r_sat_liq = RP.REFPROPdll("R407C", "PQ","HLIQ;VLIQ", RP.MOLAR_BASE_SI, 0, 1, 4391507.40643784, 0, [0])
print(r_sat_liq.herr)
r_sat_vap = RP.REFPROPdll("R407C", "PQ","HVAP;VVAP", RP.MOLAR_BASE_SI, 0, 1, 4391507.40643784, 1, [0]).Output[0:2]
print(r_sat_vap)
```
yielding
```

array('d', [34844.42671242859, 0.00026594608206448306])
```

**Comment by fuxinniu** [comment]
Hi Ian,

So appreciate your quick response. I set the wrong iFlag to call SATSPLN.

Frank
