### ISSUE TITLE
refpropm.m in linux. error: "[SETUP error 101]"

### ISSUE THREAD

**Issue by SBahamonde** [usnistgov/REFPROP-wrappers#4]
Hello,
I installed RefProp 9.1.1, and now I am trying to test the matlab wrapper. I tested with the example call
refpropm('T','P',101.325,'Q',0,'WATER')

This error pops up:

Error using refpropm (line 301)
[SETUP error 101] error in opening file for component #  1; filename = (/home/sbahamonde/refprop/fluids/WATER.FLD).

Here a print screen of the folder structure:

![image](https://cloud.githubusercontent.com/assets/13098404/23124320/b205fc7c-f76c-11e6-88a2-ae8d187bb41e.png)

I also tried the file testRP.m, the same error pops up. I wonder if you can give me some advice.
Thanks for your help.

**Comment by ianhbell** [comment]
Linux is case-sensitive.  Please change FLUIDS and MIXTURES to be fluids and mixtures respectively.

**Comment by SBahamonde** [comment]
Hello,
Thanks for your help. I changed the fonts. If I use the testRP file, it works. However, gives the following warning:
- Warning: The function 'MASSFLUXdll' was not found in the library 
- Warning: The function 'UNSETAGAdll' was not found in the library 

The refpropm call did not work, it still gives the error

Error using refpropm (line 301)
[SETUP error 101] error in opening file for component #  1; filename = (/home/sbahamonde/refprop/fluids/WATER.FLD).

I'd like to use the refpropm and of course try to get rid of the warnings.
Thanks again!
Sebastian

Here a screenshot

![image](https://cloud.githubusercontent.com/assets/13098404/23167213/c11c13fe-f843-11e6-9598-fe9c26766cfe.png)

**Comment by ianhbell** [comment]
Look at the path that it is trying to use for refpropm.  You need to move your librefprop.so and fluids and mixtures directories to the refprop directory in your home directory.  That should fix it I think.  I need to update the instructions…

**Comment by SBahamonde** [comment]
You were right, I had to update the Refprop path in the refpropm.m file.
Thanks!
Sebastian
