### ISSUE TITLE
Web application is closing, if we call the Refprop dll using Refprop-wrapper.

### ISSUE THREAD

**Issue by SivaVeeranki** [usnistgov/REFPROP-wrappers#40]
Dear GitHub team,

Currently we are creating WEB API which uses the REFPROP, when we are trying to call the WEBAPI methods which uses the Refprop methods ( Temparatur, pressure) WEB API is closing with below error message.

**Managed Debugging Assistant 'FatalExecutionEngineError' has detected a problem in 'C:\Program Files (x86)\IIS Express\iisexpress.exe'.
Additional information: The runtime has encountered a fatal error. The address of the error was at 0x5fed48ce, on thread 0x2904. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.**

Currently we are using Refprop v9.1

We appreciate your time on this issue.

**Comment by ianhbell** [comment]
Closing this issue because another duplicate is already filed (#41) with more details
