### ISSUE TITLE
Refprop error

### ISSUE THREAD

**Issue by herambraj** [usnistgov/REFPROP-wrappers#400]

**Comment by herambraj** [comment]
[
![error](https://user-images.githubusercontent.com/54817106/132073311-daabcb73-c6e0-43c7-8059-39e009b5fca1.JPG)
](url)

**Comment by ianhbell** [comment]
refpropm is deprecated.  Please use the Python interface: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB#setup
