### ISSUE TITLE
[PSFL2 error 226] 2-phase iteration did not converge.

### ISSUE THREAD

**Issue by fuxinniu** [usnistgov/REFPROP-wrappers#402]
Hi Ian,

Not convergence when calculate density by using PS. 

Any suggestions? So appreciate. 

Frank

``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])

p = 4472625.25
h = 31234.965

entropy = RP.REFPROPdll("R407C", "PH","s", RP.MOLAR_BASE_SI, 0, 0, p, h, [0]).Output[0]
print(entropy)
D1 = RP.REFPROPdll("R407C", "Ps","D", RP.MOLAR_BASE_SI, 0, 0, p + 100, entropy, [0]) #.Output[0]
print(D1.herr)
D2 = RP.REFPROPdll("R407C", "Ps","D", RP.MOLAR_BASE_SI, 0, 0, p - 100, entropy, [0]).Output[0]
```

**Comment by ianhbell** [comment]
Second question: have you tried with saturation splines on?

**Comment by fuxinniu** [comment]
Hi Ian,

It is two phase. Looks like some points work, some points do not work. 

If pick dp = 5, it can come out results. If pick 50 or 100, it can not get results. 

It is not stable. 

Thanks

Frank

import os
import  numpy as np
import csv
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])

p = 4472625.25
h = 31234.965
entropy = RP.REFPROPdll("R407C", "PH","S", RP.MOLAR_BASE_SI, 0, 0, p, h, [0]).Output[0]
print(entropy)
D1 = RP.REFPROPdll("R407C", "PS","D", RP.MOLAR_BASE_SI, 0, 1, p+5, entropy, [0]).Output[0]
print(D1)
D2 = RP.REFPROPdll("R407C", "PS","D", RP.MOLAR_BASE_SI, 0, 1, p-5, entropy, [0]).Output[0]
print(D2)

**Comment by ianhbell** [comment]
One comment: always specify ``R507C.MIX`` or ``R507C.PPF``

You should plot the phase boundary in P-S coordinates and your new point and see where it is relative to the phase boundary.  Maybe it is impossible?

**Comment by EricLemmon** [comment]
Can you provide the T and D that are calculated from the first PH calculation?  That helps to know what reference state you are using.  Second, see this:  https://github.com/usnistgov/REFPROP-issues/issues/222

**Comment by ARVaccaro** [comment]
I have a similar problem attempting to solve for pressure using density and specific enthalpy for a gas mixture. I'm using the following call in Excel: 
=REFPROP("P","CO2;N2|.95;.05 mass","DH","E",44.774,62.655)
and I get the error: 
#[DHFL2 error 226] 2-phase iteration did not converge.

The call works as expected for some values, for example: 
=REFPROP("P","CO2;N2|.95;.05 mass","DH","E",45.529,64.903)
yields:
651.18 psia

I've made a p-h diagram as a sanity check and it appears rational to query this state. More importantly, I can enter the above values for density and specific enthalpy (44.774 lbm/ft3 and 62.655 BTU/lbm) into the REFPROP.EXE application using Calculate > Specified State Points and the following answer is given (which matches what one would expect based on the p-h diagram):
624.02 psia

The density gradients are high in this area of the p-h diagram, so I'm thinking the issue may be that the internal solver is taking steps that are too large and isn't stable. Does anyone know if it's possible to change the step size at the expense of calculation speed?

I'm using Excel 365 Version 2108 (Build 14326.20238 Click-to-Run)
I'm using NIST Standard Reference Database 23, DLL version number 10.0, .XLS version number 10.0

Thanks in advance for the help.
[CO2-N2_95-5 p-h diagram.pdf](https://github.com/usnistgov/REFPROP-wrappers/files/7163626/CO2-N2_95-5.p-h.diagram.pdf)

**Comment by ianhbell** [comment]
For testing, best to do calculations in SI-units to eliminate the possibility that the problem is unit conversions.

Have you tried to follow these recommendations: https://github.com/usnistgov/REFPROP-wrappers/issues/106 ?

**Comment by ARVaccaro** [comment]
Thanks very much Ian. The reference to #106 solved my issues - uncommenting iFlag = 1 allowed the call to converge. Apologies for not seeing that issue prior to asking the question. 

For anyone else new to Github, the closed issues are filtered out by default. It's worth modifying the filter and/or searching the closed issues.
