### ISSUE TITLE
New refprop refrigerants

### ISSUE THREAD

**Issue by danres3** [usnistgov/REFPROP-wrappers#405]
Hello, 
Since I have to work with some new refrigerants, such as R466A, R470A, R515B,  using REFPROP, I was wondering where I can find the new .dll file which includes all the new refrigerants. In particular, I need to calculate some properties using Excel and the REFPROP AddIn.

Thanks

**Comment by ianhbell** [comment]
Please see: https://github.com/usnistgov/REFPROP-issues/issues/358#issuecomment-872394368

**Comment by danres3** [comment]
P

**Comment by danres3** [comment]
Perfect, thank you
