### ISSUE TITLE
Problem Running REFPROP on macOS with Python 3

### ISSUE THREAD

**Issue by fa2812** [usnistgov/REFPROP-wrappers#407]
### Description

I am trying to run REFPROP through the Python wrapper on macOS through Anaconda Spyder 3. I have installed the wrapper through `pip install ctREFPROP` and attempted to run the example code, but end up having the following error code:

``` python
  File "/Users/username/anaconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None

KeyError: 'RPPREFIX'
```

Is there any part of the setup that I am missing?

### Versions

**REFPROP Version:** 0.10.2
**Operating System and Version:** macOS 11.6
**Access Method:** Python through Spyder 3 (Anaconda)

**Comment by ianhbell** [comment]
Which should point to the folder that contains the dylib and the ``FLUIDS`` and ``MIXTURES`` folders
