### ISSUE TITLE
Refprop in Labview discrepancies

### ISSUE THREAD

**Issue by saundemail** [usnistgov/REFPROP-wrappers#408]
I am using the refprop wrapper for Labview.  When I compare the results with Refprop in Excel, the enthalpy and entropy values do not agree.  I am using ASH as the reference state, R404A.MIX, and version 10.
The attached screenshot is the results of tpflsh.  The numbers around the outside are from the Excel wrapper and in the center is Labview.  Note that the enthalpy and entropy values differ.  Why is there a difference?

![differences](https://user-images.githubusercontent.com/25889366/136970603-0063a2ee-00bd-431a-8221-3c1020b4dded.jpg)

**Comment by ianhbell** [comment]
Please see our most popular FAQ: https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences

**Comment by saundemail** [comment]
I am using R404A, so hrf: ASH, isflag: 2, x0: 0.3578167840263, h0: 0, s0: 0, t0: 0, p0: 0

**Comment by dslauria** [comment]
I think there may be an issue with the configuration of the Call Library Function. With all RefPROP related DLL calls, the calling convention MUST be stdcall (WINAPI), and not C. It looks to me like this might be a bug in the origonal tester code, so I'll post an update but it's an easy fix. Just open the Call Library Function node and change it on the function tab
![stdcall](https://user-images.githubusercontent.com/34315230/137348454-2b8e726a-1f70-4abc-b9ed-a275e56d3223.png)
