### ISSUE TITLE
MATLAB wrapper issue

### ISSUE THREAD

**Issue by Rabbit454** [usnistgov/REFPROP-wrappers#409]
Hello everyone!
I wrote a simple routine that utilize the python REFPROP wrapper, the routine is called into MATLAB and a standalone app has been created. 

To call the REFPROP routines and access the dll I followed the guide and utilized the command: 
[v,e] = pyversion; system(['"', e, '" -m pip install --user -U ctREFPROP'])
The app is working fine once installed in my machine. 

The problem is that when i install the same .exe on a different machine with same refprop version (10.0) and same python version (3.8.4), I receive the following error:
"-m" is not recognized as an internal or external command, an executable program or batch file."

Any idea about how to solve this issue?
On my machine everything is working fine without any errors following the same procedure.

Regards

**Comment by Rabbit454** [comment]
Works as usual on my machine but still getting this message error on the second machine:


"" "" is not recognized as an internal or external command,
 an executable program or batch file.

ans =

     1


       version: ''
    executable: ''
       library: ''
          home: ''
      isloaded: 0

"" "" is not recognized as an internal or external command,
 an executable program or batch file.

ans =

     1

Unable to resolve the name py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary.

any idea?

**Comment by ianhbell** [comment]
Please show the call to pyversion setting the path
