### ISSUE TITLE
Why not "PV"?

### ISSUE THREAD

**Issue by OxyCombustion** [usnistgov/REFPROP-wrappers#417]
### Description

I can use the combination of "PV" in the RefProp app but I can't when I make a RefProp.DLL call.    Why are we restricted on the combination of "PV" for the RefProp call?

I want to calculate an adiabatic compression and the easy way to do that is to use gamma.   Using gamma we generate using a RefProp call for my mixed vapors I want to use the relationship of PV^gamma = constant.   From that I can get a resulting volume after compression but then I want to plug back into a RefProp call to get my other properties.   However, I can't use the PV combination.  I went to the app and plugged in my information for P and V and it gave me a reasonable answer for T.    I just need an explanation as to why this won't work (or seems not to work). 

### Steps to Reproduce

1.Plug "PV" into a RefProp.DLL call from Mathematica
2. It gives me an error.

**Expected behavior:**I expect it to give me T.

**Actual behavior:** It gives me an error message.  When I go back to the documentation it seems to say I can't use the PV call.

### Versions

**10.0.0.0
**MS-10 
**Access Method:**Mathematica wrapper.

### Additional Information

If possible, please post examples and/or screenshots of the issue.

I have attached the copy of the notebook as a .txt file as Jeff showed me.   This extends the same file Jeff sent back.  You can find the issue toward the bottom of the file.   Thanks in advance.
[Cant call PV 01.txt](https://github.com/usnistgov/REFPROP-wrappers/files/7464650/Cant.call.PV.01.txt)

**Comment by ianhbell** [comment]
Because the GUI does some magic things.  Just do PD, with D=1/V.

**Comment by OxyCombustion** [comment]
As usual, a perfect answer.   I was beating my head against this because I thought it should work.   Your solution is a great work-around.   Thanks
