### ISSUE TITLE
Excel add-in in REFPROP

### ISSUE THREAD

**Issue by MayaYe001** [usnistgov/REFPROP-wrappers#418]
### Description

I added the add-ins to Excel, but it didn't automatically show the parameters.

### Steps to Reproduce

1. [add add-in to Excel]
2. [the parameter did'n show up automatically]

**Expected behavior:** [parameters automatically pop up]

**Actual behavior:** [didn't show]

### Versions

**REFPROP Version:** [v10.0]  
**Operating System and Version:** [Windows 10, 64 bits]  
**Access Method:** [Excel]  

### Additional Information

screenshot of the issue:
![image](https://user-images.githubusercontent.com/93630253/140026302-5dd181de-d75f-40fb-8579-186cd8b2a0f6.png)

**Comment by ianhbell** [comment]
Evidently you did not successfully add the add-in.  See https://github.com/usnistgov/REFPROP-wrappers/issues/105 .
