### ISSUE TITLE
Excel with REFPROP

### ISSUE THREAD

**Issue by MayaYe001** [usnistgov/REFPROP-wrappers#419]
### Description

This version of Excel cannot recognize the input publicity, so it is not clear where the problem occurs. I want to know whether this Excel is compatible with REFPROP?
![image](https://user-images.githubusercontent.com/93630253/140242991-ada44d00-7801-4d20-9eef-e25e9f598ac6.png)
![image](https://user-images.githubusercontent.com/93630253/140243047-bdbd6b1f-c18d-40ba-8e2e-ec7cecbe651f.png)

**Expected behavior:** Density (" R1234yf ", "TP", "SI with C",283.15,0.1) will be calculated directly

**Actual behavior:**  It shows-#NAME? (Unable to identify).

### Versions

**REFPROP Version:** [REFPROP v10]  
**Operating System and Version:** [windows 10]  
**Access Method:** [Excel]

**Comment by ianhbell** [comment]
Please see #105
