### ISSUE TITLE
Example Jupyter notebook

### ISSUE THREAD

**Issue by masoud-babaei** [usnistgov/REFPROP-wrappers#421]
Is it possible to have a Jupyter Notebook example of obtaining w (speed of sound) for a simple binary mixture please?

**Comment by ianhbell** [comment]
There's this: https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb

**Comment by ianhbell** [comment]
It covers a lot of the things you asked about.

**Comment by masoud-babaei** [comment]
thanks a lot again


Dr Masoud Babaei | Senior Lecturer

Deputy PGR Director of the Department of Chemical Engineering and Analytical Science

C24 The Mill| Faculty of Science and Engineering | University of Manchester

Tel: +44 (0)161 306 4554 | Email: ***@***.******@***.***>

University of Manchester webpage here<https://www.research.manchester.ac.uk/portal/masoud.babaei.html> | Google Scholar profile here<https://scholar.google.co.uk/citations?user=cRm7shsAAAAJ&hl=en>

Link to my group here<https://personalpages.manchester.ac.uk/staff/masoud.babaei/default.htm>  [cid:419f4e92-4485-4ee8-9b07-dc49906528bd]

<https://scholar.google.co.uk/citations?user=cRm7shsAAAAJ&hl=en>

________________________________

**Comment by masoud-babaei** [comment]
Thank you.
