### ISSUE TITLE
Enthaly of two-phase mixture: Can we obtain liquid and vapour phase enthalpies? is H calculated below, the total enthalpy of phases?

### ISSUE THREAD

**Issue by masoud-babaei** [usnistgov/REFPROP-wrappers#426]
```python
import os
os.environ['RPPREFIX'] = r'C:/Program Files (x86)/REFPROP'

# Import the main class from the Python library
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])

RP.SETPATHdll(os.environ['RPPREFIX'])

units = RP.GETENUMdll(0,'DEFAULT').iEnum
o = RP.REFPROPdll("Methane * Decane","TP","XMOLELIQ;XMOLEVAP;D;DLIQ;DVAP;Qmole;H",units,0,0,400,10000,[0.4, 0.6])
x, y, (D, Dl, Dv, Qmole, h) = o.Output[0:2], o.Output[2:4], o.Output[4:9]
print(x, y, D, Dl, Dv, Qmole, h)
```

**Comment by ianhbell** [comment]
Please read the docs: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html .  Search for ``*LIQ``

**Comment by masoud-babaei** [comment]
Basically I wish to obtain the value of total Cp = (dH_total/dt) at constant P. I used the following but I get the generic -9999990:

```
units = RP.GETENUMdll(0,'DEFAULT').iEnum
o = RP.REFPROPdll("Methane * Decane","TP","XMOLELIQ;XMOLEVAP;D;DLIQ;DVAP;Qmole;DHDT_P",units,0,0,400,10000,[0.4, 0.6])
x, y, (D, Dl, Dv, Qmole, dhdT) = o.Output[0:2], o.Output[2:4], o.Output[4:9]
print(x, y, D, Dl, Dv, Qmole, dhdT)
```

**Comment by ianhbell** [comment]
You are looking for the output ``CP`` (please read the docs).  What herr do you get for ``DHDT_P``? That should be a valid input.

**Comment by masoud-babaei** [comment]
Cp is not defined for 2-phase systems. I guess it is also the case for DHDT_P:
```
o.herr
Out[4]: '[REFPROP warning -810] One or more of the input properties is not thermophysically defined for two-phase states and cannot be calculated.'
```
But H itself gives a negative value of -2892.097946914455 J/mol. I aim to calculate the overall two-phase Cp* = (dH*/dT)_P, so I am not sure if H above is reliable. herr does not point to any error for H.

**Comment by ianhbell** [comment]
I forgot your inputs are two-phase.  c_p is not defined for two-phase inputs.  There is a definition of c_v for two-phase, but not c_p. The derivatives like DHDT_P assume the state to be homogeneous.
