### ISSUE TITLE
Error with iUnit setting of REFPROPdll in Matlab

### ISSUE THREAD

**Issue by OlumideOlumayegun** [usnistgov/REFPROP-wrappers#427]
When I set iUnit to 21 (MASS BASE SI), i have the error "[UNITCONV error 610] Requested unit is not available or array indices are out of bounds"

See the code below:
```
>> RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
>> hFld = 'CARBON DIOXIDE;NITROGEN;OXYGEN;WATER';
>> iUnit = RP.GETENUMdll(int8(1),'MOLAR SI').iEnum;
>> iMass = int8(0);
>> iFlag = int8(0);
>> z = {0.09, 0.695, 0.025, 0.19};
>> r = RP.REFPROPdll(hFld,'TP','D',iUnit,iMass,iFlag,873,0.101325,z);
>> output = double(r.Output);
>> result1 = output(1)

result1 =

    0.0140

>> iUnit = RP.GETENUMdll(int8(21),'MASS BASE SI').iEnum; % Now change the unit to MASS BASE SI
>> r = RP.REFPROPdll(hFld,'TP','D',iUnit,iMass,iFlag,873,101325,z);
>> error = r.herr % Check the error message

error = 

  Python str with no properties.

    [UNITCONV error 610] Requested unit is not available or array indices are out of `bounds.`
```

**Comment by ianhbell** [comment]
The problem is your second GETENUMdll call, the first argument should be 1 (or zero), rather than 21.  Also you can access these enumerated values from the instance, like RP.MOLAR_BASE_SI, or RP.MASS_BASE_SI.

**Comment by OlumideOlumayegun** [comment]
Thanks Ian.
Both 0 and 1 give the units in MOLAR BASES, but I would like to work on MASS BASES. According to the REFPROP documentation 21 should give the units in MASS BASE SI
![image](https://user-images.githubusercontent.com/87777436/143053629-ee5ade0c-7ac0-4094-a763-23cd2cc0440b.png)

I have now implemented it as shown below, hope that is the right way:
```
>> RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
>> hFld = 'CARBON DIOXIDE;NITROGEN;OXYGEN;WATER';
>> z = {0.09, 0.695, 0.025, 0.19};
>> iMass = int8(0);
>> iUnit = RP.MASS_BASE_SI

iUnit = 

  Python int with properties:

    denominator: [1×1 py.int]
           imag: [1×1 py.int]
      numerator: [1×1 py.int]
           real: [1×1 py.int]

    21

>> iFlag = int8(0);
>> r = RP.REFPROPdll(hFld,'TP','D',iUnit,iMass,iFlag,873,101325,z);
>> output = double(r.Output);
>> result = output(1)

result =

    0.3859
```

**Comment by EricLemmon** [comment]
Try 100 and 101 instead of 20 or 21, the documentation didn't get updated correctly before we put it out.  See:

https://github.com/usnistgov/REFPROP-wrappers/issues/144

**Comment by ianhbell** [comment]
You should _never_ rely on the number for the unit system; you should always retrieve it (as we note very clearly in the documentation).

Your new code is the recommended way to do it without the calls to GETENUM (which happen behind the scenes in the wrapper)

**Comment by OlumideOlumayegun** [comment]
Thanks @ianhbell and @EricLemmon.
