### ISSUE TITLE
English vs. E

### ISSUE THREAD

**Issue by dwestphalen** [usnistgov/REFPROP-wrappers#428]
### Description

I reinstalled REFPROP10 using a replacement installation file.  The load file requires I call out units using "English" for XLS calls to REFPROP, whereas the version I had on an older computer required "E".  So all the old spreadsheets would have to be changed.  Is there a reason it changed and is there an easy fix?

**Comment by ianhbell** [comment]
You could modify the XLA to substitute ENGLISH if the input is E.  

It was changed because we moved all the units from Excel into the Fortran so that it can be made available to all REFPROP-using applications in C++,python, MATLAB, etc.

**Comment by EricLemmon** [comment]
You can modify the VBA code to fix this as follows:

Press Alt-F11 to go to the modules that contain the VBA code.  
Open up the Refprop10Code module if it is not already so.
Search for the following:
```
'Check if the units need to be reset.
  hOut = "": hUnit = "SI": If Not IsMissing(Units) Then hUnit = Strings.Trim(Units): If hUnit = "" Then hUnit = "SI"
```
Below this add:
```
If Strings.UCase(hUnit) = "E" Then hUnit = "ENGLISH"
```
That line should hopefully fix the problem.

However, I looked at the Fortran code and it looks like it accepts both "E" and "English".  What error message did you get, and what was the command line you sent to the VBA code?  Which version of the DLL did you use?

**Comment by dwestphalen** [comment]
Eric,

Thanks, that resolves the issue.  I was getting a #VALUE result in the cell doing the calculation.  I was using a few things, one of which was =REFPROP("P","R410A","TQ","E",95,1).
It looks like REFPROP.xls says it is DLL version 10.0.

Thanks,
Detlef

**Comment by EricLemmon** [comment]
Glad to hear it is all working now!
