### ISSUE TITLE
How to change previous formula to new formula quickly?

### ISSUE THREAD

**Issue by MayaYe001** [usnistgov/REFPROP-wrappers#429]
Hello,

I want to change the previous formula to a new form. The previous formula is like: Density（“R1234yf“，“TP”，“SI with C”，273.15，0.1，0）. I want to change it to the form like:
=refprop（“D”“”“”“”）.

I want to have a quick way to change all the old formula instead of changing it one by one.

Is there any quick method to make that happen?

Could you please help me with this?

Thanks in advance.

**Comment by EricLemmon** [comment]
In the Refprop.xls file (in the directory where Refprop was installed) you will find a "Welcome" page with a big red and black box on it.  Below that are instructions for converting from commands like "Density" to the new (and only) command "Refprop" with the use of the ConvertRefprop9to10 subroutine.  There are also several discussions below that may help:

https://github.com/usnistgov/REFPROP-docs/blob/nist-pages/index.md#resolving-problems-linking-with-excel
https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Excel
https://github.com/usnistgov/REFPROP-wrappers/issues/107
https://github.com/usnistgov/REFPROP-wrappers/issues/125
https://github.com/usnistgov/REFPROP-wrappers/issues/276
