### ISSUE TITLE
can't use RP.REFPROPdll()

### ISSUE THREAD

**Issue by xiangZgnaix** [usnistgov/REFPROP-wrappers#43]
when a use the function RP.REFPROPdll() ,some error occuars.I did everything as the tutorial said, and below is the feedback of the syntax: Python 错误 ValueError: The function REFPROPdll could not be loaded from the shared library. When a use RP.RPVersion(), it returns the correct str that indicates the version of my refprop.

**Comment by ianhbell** [comment]
Sounds to me like you have REFPROP v <10, in which case the awesome ``REFPROPdll`` function is not available.  Recommend you upgrade to version 10!

**Comment by xiangZgnaix** [comment]
oh very thanks, i will have a try

**Comment by guidoffrate** [comment]
Sorry to bring this up from death, but what we should do in this case? i mean, i have reprop 9.1 and at the end of the installation procedure i got the same error. The reported procedure is not valid for other refprop older versions?

**Comment by ianhbell** [comment]
Simply put, ``REFPROPdll`` is not in REFPROP 9.1.  Therefore you need to use the legacy API.  Please see the second example here: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python#ctypes-wrapper

But better would be to upgrade to REFPROP 10.

**Comment by guidoffrate** [comment]
...And if i could not upgrade it? I don't understand that "second examaple" that you mentioned. I will reformulate my question:
If i want to use REFPROP 9.1 on MATLAB what should i do? Can i use the procedure reported on github?
Given the issue reported here:

https://github.com/usnistgov/REFPROP-wrappers/issues/60

Which points to the page where the above-mentioned procedure (which does not work, as it is, since REFPROPdll is not in REFPROP 9.1) is presented, is there a way to use REPROP 9.1 on a new release of MATLAB?

PS. who is writing use MATLAB 2018b

PPS. I had another occasion to interact with you, on an issue regarding Coolprop on the related GitHub, and i'm astonished by the promptness of your responses, so i just want to express my appreciation for your work, which makes mine a lot easier. Thank you

**Comment by ianhbell** [comment]
Did you try the example from this code that I pointed you to: 
``` python
import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

def NBP():
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    print(RP.RPVersion())
    RP.SETPATHdll(os.environ['RPPREFIX'])
    r = RP.SETUPdll(1,"PROPANE.FLD","HMX.BNC","DEF")
    assert(r.ierr == 0)
    print(RP.PQFLSHdll(101.325, 0, [1.0], 0))

if __name__=='__main__':
    # Print the version of REFPROP in use and the NBP
    NBP()
```
? 

That is the legacy API.  That's the only option you have for REFPROP 9.1.  You can see the functions that are exposed by looking here: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html.

The Python interface in MATLAB is the only option that is supported from here on out, but the legacy MATLAB interface still works.

**Comment by ianhbell** [comment]
That example is in Python, but its a one-to-one mapping to the interface that you can use in MATLAB: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB#refprop-for-matlab

**Comment by ianhbell** [comment]
But the interface is MUCH nicer in REFPROP 10 :)

**Comment by guidoffrate** [comment]
I already bought REFPROP 10, so i will solve all my problems in days (just the time to overcome the bureaucracy wall of an italian university).

In the mean time:

Yes, i run that example in python 3.7 and worked fine. just don't get the connection with my problem. But, ok that's just me... i'll investigate on that.

As for the legacy interface (refpropm)... It does NOT work in matlab 2018b and for refprop 9.1. Aside from the fact that you cannot download it (it will download something else, i don't know why) and you have to open it and copy-paste it on a new file .m by your own, when you try it the following error is issued:

Error using loadlibrary
Impossibile trovare il modulo specificato. (in english is more or less: Unable to find the specified module)

Error in refpropm (line 242)
            [~,~] = loadlibrary(strcat(BasePath,dllName),prototype,'alias',libName);

So, again, how to use REFPROP 9.1 on a new matlab distribution?

**Comment by ianhbell** [comment]
How to use REFPROP 9.1 on a new MATLAB distribution: Use the Python interface for MATLAB, and rather than calling REFPROPdll function, call the legacy API functions, as I described in my prior post.  That (should) works totally fine.  I can put together a running example in MATLAB with calling the legacy API if needed.

Did you try the direct download link for refpropm.m: https://raw.githubusercontent.com/usnistgov/REFPROP-wrappers/master/wrappers/MATLAB/legacy/refpropm.m ?

**Comment by guidoffrate** [comment]
Thanks a lot!
my problem is solved.
The last link that you provide points to a version of the code that can be copied to a new file .m and used. If you do that, then refpropm works (in my case) if, and only if, you put in the installation directory also the other two files:

REFPRP64_thunk_pcwin64.dll
rp_proto64.m

As clearly prescribed. So it was totally my fault.
I put those on the beginning, but with the wrong file .m that you download if you right-click on the "refpropm.m" link on the top of the page, matlab asked to me to remove the additional .dll and so i did. When doing these last experiments i forgot to put the second .dll again in the directory, and that caused the problem.

Thank you very much for your time. And excuse me for my dumbness (i feel a bit ashamed). 
Both coolprop and refprop are great programs, so thanks to you and to all the other developers/contributors.

**Comment by olumighty1** [comment]
I am using REFPROP 9.1 and I was able to solve this problem in Python by installing a lower version of ctREFPROP.
>> pip install ctREFPROP==0.7.3
The default version ctREFPROP-0.10 kept throwing up the error when used with REFPROP 9.1

**Comment by ianhbell** [comment]
The newest version of the wrapper should not have this issue and should gracefully allow use with REFPROP 9.x.  Can you please provide an example?

**Comment by olumighty1** [comment]
After running the code below using ctREFPROP_0.10 (i.e. default wrapper when you do: pip install ctREFPROP) with my REFPROP 9.1:

```
import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
def NBP():
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    print(RP.RPVersion())
    RP.SETPATHdll(os.environ['RPPREFIX'])
    r = RP.SETUPdll(1,"PROPANE.FLD","HMX.BNC","DEF")
    assert(r.ierr == 0)
    print(RP.PQFLSHdll(101.325, 0, [1.0], 0))
if __name__=='__main__':
    # Print the version of REFPROP in use and the NBP
    NBP()_
```
I got the following error:
_ValueError: Too many loadable shared libraries were found in the folder "C:\Program Files (x86)\REFPROP\"; obtained libraries were: ['C:\\Program Files (x86)\\REFPROP\\REFPRP64.DLL', 'C:\\Program Files (x86)\\REFPROP\\REFPRP64_thunk_pcwin64.dll'].  You must provide an absolute path to the shared library you would like to load_

I then provided the absolute path to the REFPROP64.DLL by running the code below:

```
import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
def NBP():
    os.environ['RPPREFIX'] = r'C:\\Program Files (x86)\\REFPROP\\REFPRP64.DLL'
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    print(RP.RPVersion())
    RP.SETPATHdll(os.environ['RPPREFIX'])
    r = RP.SETUPdll(1,"PROPANE.FLD","HMX.BNC","DEF")
    assert(r.ierr == 0)
    print(RP.PQFLSHdll(101.325, 0, [1.0], 0))
if __name__=='__main__':
    # Print the version of REFPROP in use and the NBP
    NBP()_
```
Then I got the error:
_ValueError: The function REFPROPdll could not be loaded from the shared library._

So I uninstall ctREFPROP and install a lower version by doing:
```
pip uninstall ctREFPROP
pip install ctREFPROP==0.7.3
```
Then running the above code again gave the correct output, note that I still needed to provide the absolute path to REFPROP64.DLL:
_9.1
PQFLSHdlloutput(T=231.03621464431757, D=13.173257388258097, Dl=13.173257388258097, Dv=0.054793106634812835, x=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), y=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), e=4417.5816588746275, h=4425.273378319079, s=26.768021829710953, Cv=63.77420408272303, Cp=99.04064396443664, w=1160.8493647028986, ierr=0, herr='')_

**Comment by ianhbell** [comment]
Ah, easy answer: move the thunk file into a subfolder of REFPROP, but pass path to root of REFPROP. That should do it.

**Comment by ianhbell** [comment]
Nice report by the way!

**Comment by ianhbell** [comment]
root : ``os.environ['RPPREFIX']``

**Comment by olumighty1** [comment]
Thanks @ianhbell 

Still getting the error
_ValueError: The function REFPROPdll could not be loaded from the shared library._
with ctREFROP_0.10

However, when I moved the thunk file into a subfolder as you suggested I no longer need to provide the absolute path. But still my code only works with the ctREFPROP_0.7.3 version

**Comment by ianhbell** [comment]
Well that makes sense, ``REFPROPdll`` was added in REFPROP 10 :) Please upgrade, or see the examples for how to call the legacy routines.

**Comment by ianhbell** [comment]
This example should still work for you:
```python
import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

def NBP():
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    print(RP.RPVersion())
    RP.SETPATHdll(os.environ['RPPREFIX'])
    r = RP.SETUPdll(1,"PROPANE.FLD","HMX.BNC","DEF")
    assert(r.ierr == 0)
    print(RP.PQFLSHdll(101.325, 0, [1.0], 0))

if __name__=='__main__':
    # Print the version of REFPROP in use and the NBP
    NBP()
```
