### ISSUE TITLE
error message when looking up helium properties in excel (only seems to be for helium)

### ISSUE THREAD

**Issue by gouckj** [usnistgov/REFPROP-wrappers#430]
### Description

I get the same error message anytime I try a properties call for helium in excel, it only seems to be for this component

### Steps to Reproduce

1. =density("helium","PT","E",14.7,70)
2. [Second Step]
3. [and so on...]

**Expected behavior:** returns density of 0.010346 lb/ft3
**Actual behavior:** get error message instead "#[SETREF error 119] Convergence failure in calculating reference state for component 1: [SATP error 144] Iteration for saturation state did not converge for P = 0.101325 MPa."

### Versions

**REFPROP Version:** [REFPROP version you are using]  10
**Operating System and Version:** [OS you are running REFPROP on]  Windows 10 Enterprise
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  excel add-in

### Additional Information

If possible, please post examples and/or screenshots of the issue.
![image](https://user-images.githubusercontent.com/95702641/145060573-497a31c0-b0a8-4dee-ae6b-97ab02da25cd.png)

**Comment by ianhbell** [comment]
Excel bug. Fine in Python:
```python
import ctREFPROP.ctREFPROP as ct
import os
root = os.getenv('RPPREFIX')
RP = ct.REFPROPFunctionLibrary(root)
r = RP.REFPROPdll("HELIUM","PT","D",RP.ENGLISH,0,0,14.7,70,[1.0])
print(r.ierr, r.herr, r.Output[0], r.hUnits)
```
yielding
```
0  0.010346123525851982 lbm/ft^3
```

**Comment by gouckj** [comment]
the error text does not sound like excel I doubt if they would use thermo physical properties verbiage

**Comment by ianhbell** [comment]
Not excel _per se_, but the error is not coming from the DLL

**Comment by ianhbell** [comment]
More specifically, the error message _is_ coming from the DLL, but does not happen when the DLL is called with the same inputs in Python.  Did you enable setting of the reference state in your XLA? Seems so.

**Comment by gouckj** [comment]
thanks for the feed back, I am not sure how to set a reference state, I know you are not responsible for excel but do you have a clue how to fix this?

**Comment by ianhbell** [comment]
There are lines like these in the XLA, make sure they are commented:

```
        'Use the following lines to set a reference state to one of those available in the REFPROP program.
        'See notes at the top of this section about restarting Excel and saving this file.
          'hIn = "SETREF": hFld = ""
          'hOut = "NBP"  '*****Do NOT use this line with the one below select only one. Valid inputs are DEF, NBP, IIR, ASH, and NA.
          'hOut = "OTH; 11.11; 22.22; 298.15; 101.325"    'To set your own reference state, use this line with OTH.  In this example, a reference state of h=11.11 J/mol, S=22.22 J/mol-K, T=298.15 K, and P=101.325 kPa would look like this.  The units for this option are the default REFPROP units.  Do not use the line directly above when using OTH.
          'Call REFPROPdll(hFld, hIn, hOut, 0&, 0&, 2&, 0#, 0#, z(1), Output(1), hUnits, iUnits, x(1), y(1), x3(1), q, ierr, herr, 10000&, 255&, 255&, 255&, 255&)

```

**Comment by gouckj** [comment]
I notice that REFPRP91.XLA is in my Microsoft add-in folder but does not appear in the REFPROP program files folder I downloaded, could this have something to do with it?

**Comment by EricLemmon** [comment]
That is quite possible.  If it is there, it may not be able to find the DLL or FLD files.  Remove the link to it in Excel, then close Excel, move that file to your Refprop directory, and then re-establish the link.  

We also recommend not installing the Refprop program in the Windows system directories.  It is better to put it in your User's directory or in the root of the C: drive itself.  Windows likes to make ghost files when you attempt to save something in the ProgramFiles directory, and this will avoid that problem.

**Comment by gouckj** [comment]
thanks I will give it a try
