### ISSUE TITLE
HELP: need the use description of fuctions

### ISSUE THREAD

**Issue by MayaYe001** [usnistgov/REFPROP-wrappers#431]
Hi everyone,

Can anyone provide me a description of the use of the function, such as calculating enthalpy, density and other physical properties of the refrigerant?

Thanks in advance.

Regards,
Maya

**Comment by ianhbell** [comment]
Can you please try to ask a more precise question? What precisely are you trying to do?

**Comment by MayaYe001** [comment]
Hi,

I want to know that in the formula "=REFPROP（“D”“R1234yf“，“TP”，“SI with C”，273.15，0.1，0）", what parameter should I input into each " " and what does my input means?

Thanks.

**Comment by ianhbell** [comment]
D: density
R1234yf: name of fluid
TP: inputs, here temperature and pressure are your state variables
SI with C: SI unit system with Celsius for temperature
273.15: temperature
0.1: pressure

**Comment by ianhbell** [comment]
Recommend to read the extensive documentation provided in the Excel spreadsheet

**Comment by EricLemmon** [comment]
There are hundreds of examples, a lot of text with help information in it, and so forth in the REFPROP.XLS file.  

The github website here contains dozens of entries about using Excel, you can search for the label "Excel" to find most of them.  This link will do that for you:

https://github.com/usnistgov/REFPROP-wrappers/issues?q=label%3AExcel+

**Comment by MayaYe001** [comment]
> D: density R1234yf: name of fluid TP: inputs, here temperature and pressure are your state variables SI with C: SI unit system with Celsius for temperature 273.15: temperature 0.1: pressure

Many thanks for your help. Could you please help me with another question?

I want to calculate the enthalpy value. The input conditions are temperature and pressure. If the refrigerant is in a gas-liquid two-phase state, the input pressure at this time is the saturation pressure corresponding to the temperature. The enthalpy value at this time cannot be determined, so which point does the enthalpy value calculated by the function correspond to?

For example, In the formula - REFPROP("E", "R404a", "pt", "si with c", "pressure P1", "saturation temperature T1 corresponds to pressure P1  "), which point does the enthalpy value calculated by the function correspond to?

Hope you can help me with this.

**Comment by ianhbell** [comment]
If you know your inputs are saturated liquid or vapor, you should specify that, with PQ or TQ inputs.  Otherwise, you can specify which solution you would prefer with > or <.  Please read the docs on that topic (https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html), specifically: 

![image](https://user-images.githubusercontent.com/11966765/145656076-f0c9811f-7715-48fd-b9f2-27603e1fcdac.png)
