### ISSUE TITLE
NIST REFPROP for julia

### ISSUE THREAD

**Issue by mana2025** [usnistgov/REFPROP-wrappers#433]
This is more like a general question. I could not find a wrapper for Julia. Is it possible to create one?
Thanks.

**Comment by ianhbell** [comment]
Best bet is to call Python wrapper from Julia. Or you can use the CoolProp wrapper to call REFPROP from Julia: https://github.com/CoolProp/CoolProp.jl and http://www.coolprop.org/coolprop/REFPROP.html

**Comment by mana2025** [comment]
Thanks! https://github.com/CoolProp/CoolProp.jl works well!
