### ISSUE TITLE
2-phase iteration did not converge in Excel but converge in REFPROP 10.0 GUI

### ISSUE THREAD

**Issue by RayleighSun** [usnistgov/REFPROP-wrappers#434]
Hi, 
I am using REFPROP 10.0, when I use EXCEL to calculate isobaric heat capacity of Carbon dioxide + Propane binary mixture (0.5/0.5 mole fraction), it shows that in some temperature and pressure (e.g. 338.15 K and 8 MPa), an error "2-phase iteration did not converge" shows up. I'm not sure if there is the same error at 343.15 and 373.15 K, because only the hash sign is displayed. 
But when I use GUI to caculate the same condition, the results are no error, as shown in the pictures below.

Is this because the operation logic of the GUI is different from that of excel? Is there a solution to avoid this problem in Excel, so that we can calculate the result?

![p1](https://user-images.githubusercontent.com/94279628/146669606-0d060ab6-82b8-4c50-9f6a-4ea3f706aaed.png)
![p2](https://user-images.githubusercontent.com/94279628/146669619-943e0e74-121c-45a0-ad8a-d655f0357916.png)

Thanks for your help!

**Comment by EricLemmon** [comment]
Take a look at this one and see if it answers your questions:

https://github.com/usnistgov/REFPROP-wrappers/issues/106

**Comment by RayleighSun** [comment]
Thanks! Mr. Lemmon, it works! 
![p3](https://user-images.githubusercontent.com/94279628/146719863-618d5016-c12c-4a46-bae3-a1b60750a792.png)
In addition, when I use MATLAB, a same error ([TPFL2 error 226] 2-phase iteration did not converge. ) will be reported at the same state point (338.15 K, 8 MPa 0.5 mole CO2+0.5 mole propane). As for MATLAB, is there similar file can I change the "iFlag"?

Thank you for your help!

**Comment by ianhbell** [comment]
If you use the Python interface in MATLAB, yes.

**Comment by RayleighSun** [comment]
Thanks, Mr. Bell, I used both refpropm.m file you once uploaded, and Python interface. 
My problem is solved when I call Python in MATLAB with REFPROPdll, and set iFlag=1. 
But I didn't find a proper place to change the iFlag in refpropm.m file you given. Is this setting works for that refpropm.m file?
Thanks for your help!

**Comment by ianhbell** [comment]
refpropm is deprecated, so don't use it.

**Comment by RayleighSun** [comment]
Thanks, Mr. Bell, this is how I set iFlag=1 in MATLAB via Python (Hope I wrote it correctly), and it do solved the problem of 2-phase iteration did not converge that occured via refpropm.
```
clear; clc
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
MassSI = RP.GETENUMdll(int8(0),'MASS BASE SI').iEnum; 
iMass = int8(0); % 0: molar fractions; 1: mass fractions
iFlag = int8(1); % 0: don't call SATSPLN; 1: call SATSPLN
hFld='CO2;PROPANE';
z = {0.5,0.5}; % mole fractions
T = 338.15;  % K
p = 8e6;      % Pa
r = RP.REFPROPdll(hFld,'TP','CP',MassSI,iMass,iFlag,T,p,z);
o = double(r.Output);
cp = o(1)/1e3;
fprintf('Isobaric heat capacity = %.4f kJ/(kg K)\n',cp)
```
Thanks!
