### ISSUE TITLE
Error message while trying to import Look-Up-Tables into MATLAB

### ISSUE THREAD

**Issue by malteradecke** [usnistgov/REFPROP-wrappers#437]
### Description

Hello,
I'm trying to import Look-Up-Tables via MATLAB for a model in Simscape. I want to import the thermophysical properties of helium, but somehow I get an error message every time. I tried different limits for the main inputs Internal Energy (Input Vector 1) and Pressure (Input Vecor 2), but when I try to enter the following command in a MATLAB script: 

``
helium_tables = twoPhaseFluidTables([-5,5000],[0.1,1],100,500,300,'helium','C:\Program Files (x86)\REFPROP');
``

I get this error at some point: 

Error using twoPhaseFluidTables>refpropFluidProperties (line 657)
REFPROP failed to return fluid properties
at P = 0.22448 MPa and U = 5.7009 kJ/kg.

Error in twoPhaseFluidTables>@(p,u)refpropFluidProperties(p,u,libName,z,nc,molw) (line 531)
fluidProperties = @(p, u) refpropFluidProperties(p, u, libName, z, nc, molw);

Error in twoPhaseFluidTables (line 233)
                = fluidProperties(p(j), u_liq(i,j));

Error in read_input_data.m (line 10)
helium_tables = twoPhaseFluidTables([-5,5000],[0.1,1],100,500,300,'helium','C:\Program Files (x86)\REFPROP');

Caused by:
    [PEFLSH error 247] density iteration for single-phase state did not converge:  [TPRHO error 202] liquid iteration has not converged for T =  5.1787 K, P = 0.22448 MPa, rho (last guess) =   20.025 mol/L, compositions =   1.00000

I then tried to enter the point of failure in the REFPROP stand-alone and there its working:

![image](https://user-images.githubusercontent.com/70896163/148956759-34909f64-f401-440a-a4d3-c36276a79fa7.png)

I assume it has something to do that I'm in the area where the fluid is only existing in a superheated form, while the MATLAB error message is saying I'm in the two phase area.

### Versions

**REFPROP Version:** REFPROP Version 9.1
**Operating System and Version:** Windows 10 Pro
**Access Method:** MATLAB 

### Additional Information

Here's the MATLAB call I'm trying to use: https://de.mathworks.com/help/physmod/simscape/ref/twophasefluidtables.html

I also thought of using the MATLAB Wrapper via calling Python, but I haven't installed Python yet so I tried it this way.
I would appreciate your help!

Best regards

Malte

**Comment by ianhbell** [comment]
My guess is the reference states are handled differently, which is why one works and the other doesn't.

**Comment by malteradecke** [comment]
Thank you for your fast answer, though I'm not sure how to fix the problem. Maybe its easier to call REFPROP via the MATLAB(/Python) Wrapper.

**Comment by ianhbell** [comment]
Yes, I think so, if you can.  There are a few notes online about using simulink and MATLAB, and I remember that at least one person got it working.

**Comment by malteradecke** [comment]
I'm still trying to fix this issue with the twoPhaseFluidTables command; calling REFPROP via MATLAB(/Python-Wrapper) isn't the convenient way in this scenario. Any idea how I can solve this problem? I tried different input values for the internal energy u, but it doesn't work.

**Comment by ianhbell** [comment]
Time to talk to Mathworks I fear

**Comment by malteradecke** [comment]
In the end I I found this workaround by MathWorks, for everybody who's interested: https://blogs.mathworks.com/simulink/2016/03/22/coolprop-to-the-rescue/

This should work too and needs just be abjusted for REFPROP, but since Helium is also included in CoolProp, there's no adjustment needed right now. This issue can be closed.

**Comment by ianhbell** [comment]
And you can call REFPROP through CoolProp, though I will mention here that the MATLAB interface to CoolProp is only available via Python now.

**Comment by malteradecke** [comment]
That is true. I found something for using REFPROP in Simulink if someone is interested: https://groups.google.com/g/coolprop-users/c/gakJEFWTQwY

**Comment by ianhbell** [comment]
Thanks, I had looked for that post but couldn't remember where it was.  You could do the same thing with the REFPROP native python wrapper, or call CoolProp.
