### ISSUE TITLE
ABFLSH DllImport for C#

### ISSUE THREAD

**Issue by vernturbine** [usnistgov/REFPROP-wrappers#438]
Posted in case anyone could use this. 

        /**********************************************************************************************
        * General flash calculation that handles all inputs of T, P, D, h, e, s, and q.
        ***********************************************************************************************/
        [DllImport("REFPRP64.dll", CharSet = CharSet.Ansi, CallingConvention = CallingConvention.Cdecl)]
        public static extern void ABFLSHdll 
        (
            [In] char[] ab,                                                             // (INPUT) Property code: T, P, D, h, e, s, and q
            [In] ref double a,                                                          // (INPUT) First property value
            [In] ref double b,                                                          // (INPUT) Second property value
            double[] z,                                                                 // (INPUT) Total composition [array of mol frac]
            ref int iFlag,                                                              // (INPUT) multi-purpose option flag
            [In, Out] ref double T,                                                     // (OUTPUT) temperature [K]
            [In, Out] ref double P,                                                     // (OUTPUT) pressure [kPa]
            [In, Out] ref double D,                                                     // (OUTPUT) molar density overall [mol/L]
            [In, Out] ref double Dl,                                                    // (OUTPUT) molar density of saturated liquid [mol/L]
            [In, Out] ref double Dv,                                                    // (OUTPUT) molar density of saturated vapor [mol/L]
            double[] xliq,                                                              // (OUTPUT) liquid phase composition [array of mol frac]
            double[] xvap,                                                              // (OUTPUT) vapor phase composition [array of mol frac]
            [In, Out] ref double q,                                                     // (OUTPUT) quality [lbm/lbm]
            [In, Out] ref double e,                                                     // (OUTPUT) Overall internal energy [J/mol]
            [In, Out] ref double h,                                                     // (OUTPUT) Overall internal enthalpy [J/mol]
            [In, Out] ref double s,                                                     // (OUTPUT) Overall internal entropy [J/mol-K]
            [In, Out] ref double Cv,                                                    // (OUTPUT) Isochoric (constant D) heat capacity [J/mol-K]
            [In, Out] ref double Cp,                                                    // (OUTPUT) Isobaric (constant P) heat capacity [J/mol-K]
            [In, Out] ref double w,                                                     // (OUTPUT) speed of sound [m/s]
            [In, Out] ref int ierr,                                                     // (OUTPUT) error flag
            [In, Out] char[] herr,                                                      // (OUTPUT) error message
            int ablength,                                                               // (OUTPUT) ab array length
            int herrLen);                                                               // (OUTPUT) error array length

**Comment by ianhbell** [comment]
Thanks, do you know about the C# wrapper that was provided by a community member?

**Comment by vernturbine** [comment]
Hi Ian,

 

Yes, and it didn’t have ABFLSH. Getting the “ab” character array to read in correctly was a bit of a struggle.

 

Vern
