### ISSUE TITLE
installed but doesn't work

### ISSUE THREAD

**Issue by hvazini** [usnistgov/REFPROP-wrappers#439]
Greeting,
I have installed ctREFPROP using 'pip install ctREFPROP' in Anaconda Prompt.
This message was shown in the prompt:
Successfully installed ctREFPROP-0.10.2

Then I wrote these codes in python:
```     
import os
os.environ['RPPREFIX'] = r'C:/Program Files (x86)/REFPROP'
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
```
        
But, an error occurred:
"C:/Program Files (x86)/REFPROP" is neither a directory nor a file
        
Please help me to fix this error and use refprop.
        
Thank You.

**Comment by ianhbell** [comment]
Where did you install REFPROP? You need to have REFPROP installed in order to use ctREFPROP (it is only a wrapper)

**Comment by hvazini** [comment]
Could you help me how to install REFPROP?

In the prompt, I'm using: pip install REFPROP.

this error appeared:
ERROR: Could not find a version that satisfies the requirement REFPROP (from versions: none)
ERROR: No matching distribution found for REFPROP

**Comment by ianhbell** [comment]
REFPROP can be purchased from https://www.nist.gov/srd/refprop

**Comment by hvazini** [comment]
I got it. Thank you very much.
