### ISSUE TITLE
Cannot get linux or mac os wrapper to work with Visual Basic .NET

### ISSUE THREAD

**Issue by tripheo0412** [usnistgov/REFPROP-wrappers#441]
### Description
We have a Visual Basic .NET app built into DLL. This has been using refprop and hosted on windows. Now we want to run it on MacOS and Linux as well. But couldn't get it to work.

### Steps to Reproduce

1. I built refprop wrapper for macos according to instruction
![image](https://user-images.githubusercontent.com/25382052/150977245-0eefc25a-a173-4e37-a59d-53fe5b4feed4.png)
2. Adjust code to import `librefprop.dylib`
```
Const ncmax = 19   'Maximum number of components in the mixture (do not change unless the Refprop Fortran code is also changed with the same number in the CONSTS.INC file)
    Const iPropMax = 199 'Number of output properties available in ALLPROPS (also do not change).

    Private Declare Sub REFPROPdll Lib "librefprop.dylib" (ByVal hFld As String, ByVal hIn As String, ByVal hOut As String, ByRef iUnitNumb As Long,
    ByRef iMass As Long, ByRef iFlag As Long, ByRef a As Double, ByRef b As Double, z() As Double, Output() As Double, ByVal hUnits As String,
    ByRef iUnits As Long, x() As Double, y() As Double, x3() As Double, ByRef q As Double, ByRef ierr As Long, ByVal herr As String,
    ByRef ln1 As Long, ByRef ln2 As Long, ByRef ln3 As Long, ByRef ln4 As Long, ByRef ln5 As Long)

```
3. `MIXTURES` and `FLUIDS` folder are in the same directory with `librefprop.dylib`

**Expected behavior:** Refprop would work and return correct result

**Actual behavior:** Refprop didn't work and I got null value

### Versions

**REFPROP Version:** 10
**Operating System and Version:** MacOS Big Sur
**Access Method:** Mac OS wrapper

**Comment by ianhbell** [comment]
Please provide a minimal runnable example of what you tried to run on linux.  Otherwise not sure there is anything I can do to debug.

**Comment by tripheo0412** [comment]
My guessing is VB .NET can only import DLL

**Comment by ianhbell** [comment]
I don't think that is true.  For instance there is this interface to CoolProp for VB.net: http://www.coolprop.org/coolprop/wrappers/VB.net/index.html#vbdotnet (which can be used to call REFPROP)
