### ISSUE TITLE
Cp. Cv and q value from ABFLASH are different from NIST REFPROP program

### ISSUE THREAD

**Issue by wabb176912315** [usnistgov/REFPROP-wrappers#442]
### Description

When I calculate the properties of CO2/H2 mixture with calling ABFLSHdll, the output of Cp, Cv and q indicates the mixture in 2-phase state, but NIST REFPROP program 10.0 shows the mixture in gas state.

### Steps to Reproduce

1. Find Cp, Cv, and q from ABFLSHdll at 346 K and 0.0001 bar
2. Find density from ABFLSHdll at 346 K and 0.0001 bar
3. Find Cp, Cv, and q from ABFLSHdll at 346 K and density from step 2
4. Find Cp, Cv, quality, and phase from NIST REFPROP program 10.0 at the same condition

**Expected behavior:** 
Cp, Cv, and q from step1 and step3/step4 are the same.
**Actual behavior:**
Cp, Cv, and q from step1 and step3/step4 are different.

### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** Win10 pro, 64-bit
**Access Method:** Python 

### Additional Information
My code:

```python
import os
os.environ['RPPREFIX'] = r'C:/Program Files (x86)/REFPROP'
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
RP.SETFLUIDSdll('CO2*H2')


o1 = RP.ABFLSHdll('TP', 346, 0.0001*100, [0.1,0.9], 000)

o2 = RP.ABFLSHdll('TD', 346, o1.D, [0.1,0.9], 000)

print('Mixture of CO2 and H2 with molar ratio of 10%:90%:')
print('At 346 K & 0.0001 bar:') 
print(f'Density is {o1.D} [mol/L]')
print(f'Cp is {o1.Cp} [J/mol-K]')
print(f'Cv is {o1.Cv} [J/mol-K]')
print(f'q is {o1.q}')
print('###############')
print(f'At 346 K & {o1.D} mol/L: ')
print(f'Cp is {o2.Cp} [J/mol-K]')
print(f'Cv is {o2.Cv} [J/mol-K]')
print(f'q is {o2.q}')
```
The Output is:

Mixture of CO2 and H2 with molar ratio of 10%:90%:
At 346 K & 0.0001 bar:
Density is 3.4760785559996385e-06 [mol/L]
Cp is -9999980.0 [J/mol-K]
Cv is -9999990.0 [J/mol-K]
q is 7.606767213141907e-05
###############
At 346 K & 3.4760785559996385e-06 mol/L: 
Cp is 30.089452625655504 [J/mol-K]
Cv is 21.774987056517297 [J/mol-K]
q is 998.0

Result from NIST REFPROP program 10.0:
![image](https://user-images.githubusercontent.com/79348411/152857029-5ea4a671-b6bf-471a-9f44-fd684a5a6468.png)

Please let me know if I did something wrong.
Thank you!

**Comment by ianhbell** [comment]
I think the problem is you picked the wrong mixture :) It's always a good idea to see where these points are relative to the isopleth of the phase envelope.

**Comment by ianhbell** [comment]
Also: try turning on and off the saturation splines.  Almost always the splines help, but sometimes not for very asymmetric mixtures like this one.

**Comment by wabb176912315** [comment]
> I think the problem is you picked the wrong mixture :) It's always a good idea to see where these points are relative to the isopleth of the phase envelope.

Hi Ian, than you for your reply.  But I am confused by "I picked wrong mixture". Did I make mistake in setting up the fluid? Or is the mixture model not satisfied for this mixture, I can't use NIST REFPROP to calculate its properties. 
Thank you again.

**Comment by ianhbell** [comment]
Sorry, bad joke on my part.  I mean more that this is a challenging mixture to model, and the model is not that great, and because the mixture is so asymmetric, algorithms may well get confused.  Which is why I was highlighting that you should sanity check where your state points are.

**Comment by wabb176912315** [comment]
Ah, I am sorry I didn't get the point.😁
I will try your suggestion tomorrow. 
Are the results from Nist refprop program correct? Do the states need to be checked? 
Thank you.

**Comment by ianhbell** [comment]
There seems to be a bug of some kind between ``ABFLSH`` and other higher-level routines. You get two different kinds of results, and they should be precisely the same.

Example:
```python
import os
#os.environ['RPPREFIX'] = r'C:\Users\ihb\Code\REFPROP-cmake\bld\Release'

import os
os.environ['RPPREFIX'] = r'C:/Program Files (x86)/REFPROP'
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
RP.SETFLUIDSdll('CO2*H2')

z = [0.1, 0.9]
RP.SATSPLNdll(z) # Turn on the saturation spline

# Original
o1 = RP.ABFLSHdll('TP', 346, 0.0001*100, z, 000)
print('Mixture of CO2 and H2 with molar ratio of 10%:90%:')
print('At 346 K & 0.0001 bar:') 
print(f'Density is {o1.D} [mol/L]')
print(f'Cp is {o1.Cp} [J/mol-K]')
print(f'Cv is {o1.Cv} [J/mol-K]')
print(f'q is {o1.q}')
print('###############')
o2 = RP.ABFLSHdll('TD', 346, o1.D, z, 000)
print(f'At 346 K & {o1.D} mol/L: ')
print(f'Cp is {o2.Cp} [J/mol-K]')
print(f'Cv is {o2.Cv} [J/mol-K]')
print(f'q is {o2.q}')

print('*********')

# Even higher level
o1 = RP.REFPROPdll('', 'TP', 'D;Cp;Cv;QMOLE', RP.MOLAR_BASE_SI, 1, 0, 346, 0.0001e5, z)
D,Cp,Cv,q = o1.Output[0:4]
print('Mixture of CO2 and H2 with molar ratio of 10%:90%:')
print('At 346 K & 0.0001 bar:') 
print(f'Density is {D} [mol/m3]')
# print(f'Cp is {Cp} [J/mol-K]')
# print(f'Cv is {Cv} [J/mol-K]')
print(f'q is {q}')
o2 = RP.REFPROPdll('', 'TD', 'D;Cp;Cv;QMOLE', RP.MOLAR_BASE_SI, 1, 0, 346, D, z)
print('###############')
D,Cp,Cv,q = o1.Output[0:4]
print(f'At 346 K & {D} mol/m3: ')
# print(f'Cp is {Cp} [J/mol-K]')
# print(f'Cv is {Cv} [J/mol-K]')
print(f'q is {q}')
```
yielding
```
Mixture of CO2 and H2 with molar ratio of 10%:90%:
At 346 K & 0.0001 bar:
Density is 3.4760785560416814e-06 [mol/L]
Cp is 30.089452625655504 [J/mol-K]
Cv is 21.774987056517297 [J/mol-K]
q is 998.0
###############
At 346 K & 3.4760785560416814e-06 mol/L: 
Cp is 30.089452625655504 [J/mol-K]
Cv is 21.774987056517297 [J/mol-K]
q is 998.0
*********
Mixture of CO2 and H2 with molar ratio of 10%:90%:
At 346 K & 0.0001 bar:
Density is 0.0034760805135352216 [mol/m3]
q is -9999990.0
###############
At 346 K & 0.0034760805135352216 mol/m3: 
q is -9999990.0
```

**Comment by wabb176912315** [comment]
Hi Ian,
Thank you for the update. 
I found I understood the documents wrongly. The SATSPLN is off by default. After setting SATSPLN on, I can get the results. 
Thank you so much.

**Comment by lynnrinkui** [comment]
> Sorry, bad joke on my part. I mean more that this is a challenging mixture to model, and the model is not that great, and because the mixture is so asymmetric, algorithms may well get confused. Which is why I was highlighting that you should sanity check where your state points are.

Hi Ian, I'm experiencing a similar issue when calculating a Helium/Oxygen mixture. My problem setup (on MATLAB) is:
`x = double(RP.REFPROPdll('Helium;Oxygen','TP','Z',int8(20),int8(1),int8(1),300,1e5,[0.9 0.1]).Output); x(1)`

which is a 90/10 molar fraction He-O2 mixture at 300K and 1bar. REFPROPdll gives me:
`ans =

    -9999990`
Turning on and off saturation splines does not help.
I assume this is because of the mixture being too close to an ideal gas as Refprop does handle a 50-50 mixture well.

Is there anyway to avoid this error? The mixture I'm working on has a varying composition so I can't easily tell when to not use REFPROPdll.

**Comment by lynnrinkui** [comment]
@ianhbell Thanks for the tip :)
When SATSPLN is on, my herr is
`ierr=355, herr='[SATSPLN error 355] Spline routine failed.')`
Otherwise it's
`ierr=-810, herr='[REFPROP warning -810] One or more of the input properties is not thermophysically defined for two-phase states and cannot be calculated.'`

**Comment by ianhbell** [comment]
You should plot your point along with the phase envelope and see what they look like.  Should give you an indication of what is going on. 

Also, a lot of the Helium + X models are placeholders and SHOULD NOT BE TRUSTED!  This model in particular is a placeholder that uses the Lorentz-Berthelot mixing rules:

```python
import os 
root = os.getenv('RPPREFIX')
import ctREFPROP.ctREFPROP as ct
RP = ct.REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)

RP.SETFLUIDSdll('HELIUM;OXYGEN')
print(RP.GETKTVdll(1,2))
```
yielding
```
GETKTVdlloutput(hmodij='KW0', fij=array('d', [1.0, 1.0, 1.0, 1.0, 0.0, 0.0]), hFmix='HMX.BNC', hfij='BetaT   GammaT  BetaV   GammaV   Fij   not used', hbinp='Helium/Oxygen\r\nKunz and Wagner (2007)', hmxrul='KW0  Kunz and Wagner model for hydrocarbon mixtures')
```

**Comment by lynnrinkui** [comment]
> You should plot your point along with the phase envelope and see what they look like. Should give you an indication of what is going on.
> 
> Also, a lot of the Helium + X models are placeholders and SHOULD NOT BE TRUSTED! This model in particular is a placeholder that uses the Lorentz-Berthelot mixing rules:
> 
> ```python
> import os 
> root = os.getenv('RPPREFIX')
> import ctREFPROP.ctREFPROP as ct
> RP = ct.REFPROPFunctionLibrary(root)
> RP.SETPATHdll(root)
> 
> RP.SETFLUIDSdll('HELIUM;OXYGEN')
> print(RP.GETKTVdll(1,2))
> ```
> 
> yielding
> 
> ```
> GETKTVdlloutput(hmodij='KW0', fij=array('d', [1.0, 1.0, 1.0, 1.0, 0.0, 0.0]), hFmix='HMX.BNC', hfij='BetaT   GammaT  BetaV   GammaV   Fij   not used', hbinp='Helium/Oxygen\r\nKunz and Wagner (2007)', hmxrul='KW0  Kunz and Wagner model for hydrocarbon mixtures')
> ```

Understand. I would say this mixing rule is still better than ideal gas assumption. Also without plotting the phase envelope it's obvious that at 300K and 1bar the He-O2 mixture is purely gas (well above critical temperature even), so I don't know why SATSPLN would fail. Any suggestions?

**Comment by ianhbell** [comment]
Better than ideal gas? Probably, but not a 100% guarantee.  I'm not sure why the isopleth calculation fails, probably because the first point of it fails.
