### ISSUE TITLE
DLL expiration 

### ISSUE THREAD

**Issue by mnotarnicola** [usnistgov/REFPROP-wrappers#444]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

Receiving a notice that when I call Refprop functions that the DLL I'm using is expired.  I believe i'm using a beta version of the DLL.  Is there a new one available?

### Steps to Reproduce

=Density("Water","PT","SIwithC",.101325,22) in excel

**Expected behavior:** return density value

**Actual behavior:** The REFPROP DLL you are using has expired.

### Versions

**REFPROP Version:** 10.0097
**Operating System and Version:** [OS you are running REFPROP on]  
**Access Method:** Python through MATLAB and Excel
### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
Windows? If so, please email me at ian.bell@nist.gov

**Comment by toto0tto** [comment]
How to update DLL ?
