### ISSUE TITLE
getting #NAME on data cells

### ISSUE THREAD

**Issue by ateschultz** [usnistgov/REFPROP-wrappers#447]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

Whenever we try to get data we get a #287 

### Steps to Reproduce

1. Install
2. Open Excel and it just happens

**Expected behavior:** Update data cells

**Actual behavior:** getting #NAME

### Versions

**REFPROP Version:** [9c8dc04](https://github.com/usnistgov/REFPROP-wrappers/commit/9c8dc043f291b9a05a8fa0be78348b592cb1a9f8)

**Operating System and Version:** Windows 10
**Access Method:** through Excel

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
Did you try to follow the recommendation of #287 to install in ``c:`` rather than ``c:/program files (x86)``?

Make sure you also change the RPPREFIX environment variable to point to your new location.

**Comment by ateschultz** [comment]
I will try that tomorrow.

Thanks!

**Comment by ateschultz** [comment]
okay I am getting a #VALUE error which I am guessing is an issue around the DLL. I was going through https://pages.nist.gov/REFPROP-docs/#resolving-problems-linking-with-excel to see if it had something but the =REFPROP(“DLL#”) command is still bringing the #VALUE error.

**Comment by ianhbell** [comment]
These things are always tricky to debug in Excel. What if you try to re-evaluate that cell? Is the folder containing REFPRP64.DLL added to the PATH environment variable?

**Comment by ateschultz** [comment]
I checked and the path environment seems right. I am also getting a compile error: Expected: String Constant after changing the vba code like I saw in the instructions.

**Comment by ianhbell** [comment]
Can you provide a screenshot of the error?

**Comment by ateschultz** [comment]
oh sorry I got that one going, I am going to try this on a different profile and see maybe if it is just a profile issue.
