### ISSUE TITLE
MATLAB+REFPROP helium viscosity problem

### ISSUE THREAD

**Issue by vitalmouse** [usnistgov/REFPROP-wrappers#449]
### Description

The viscosity of helium returns an incorrect value

### Steps to Reproduce

1. [First Step]

```matlab
clc
clear
close

RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
RP.RPVersion()

MassSI=RP.GETENUMdll(int8(0),'Mass SI').iEnum; %unit in MASS SI
iMass=int8(0); % 0: molar fraction, 1: mass fraction , in this code we only use pure fluid, 0 or 1 either OK. 
iFlag=int8(0); %0  dont't call SATSPLN, 1: call SATSPLN
z={1.0};

r=RP.REFPROPdll('helium','TP','VIS', MassSI,iMass,iFlag,300 , 1,z); 
vis=double(r.Output); 
viscosity_helium=vis(1)

r=RP.REFPROPdll('water','TP','VIS', MassSI,iMass,iFlag,300 , 1,z); 
vis=double(r.Output); 
viscosity_water=vis(1)

r=RP.REFPROPdll('nitrogen','TP','VIS', MassSI,iMass,iFlag,300 , 1,z); 
vis=double(r.Output); 
viscosity_nitrogen=vis(1)

r=RP.REFPROPdll('oxygen','TP','VIS', MassSI,iMass,iFlag,300 , 1,z); 
vis=double(r.Output); 
viscosity_oxygen=vis(1)
```

Run.

**Expected behavior:** [What you expect to happen]
We find the viscosity of helium value. 

**Actual behavior:** [What actually happens]
We can't find the viscosity of helium value. The code returns 0 for the helium viscosity.
Other fluid work ok,
Other properties work OK (heat capacity, enthalpy...)

### Versions

**REFPROP Version:** [REFPROP version you are using]   10.0098
**Operating System and Version:** [OS you are running REFPROP on] Windows 10   
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  MATLAB+REFPROP

### Additional Information

If possible, please post examples and/or screenshots of the issue.

ctREFPROP 0.10.2

**Comment by ianhbell** [comment]
Make sure you check ierr code as well.  And look at herr error message string.

**Comment by ianhbell** [comment]
This works fine in 10.0.0.02:
code:
```python
import ctREFPROP.ctREFPROP as c

RP = c.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
print(RP.RPVersion())

MassSI=RP.GETENUMdll(0,'Mass SI').iEnum; #%unit in MASS SI
iMass=0; #0: molar fraction, 1: mass fraction , in this code we only use pure fluid, 0 or 1 either OK. 
iFlag=0; #0  dont't call SATSPLN, 1: call SATSPLN
z=[1.0];

r=RP.REFPROPdll('helium','TP','VIS', MassSI,iMass,iFlag,300 , 1,z); 
print(r.Output[0])
```
yielding
```
10.0.0.02
19.960868553258628
```

**Comment by ianhbell** [comment]
Looks like a regression introduced since 10.0.0.02

**Comment by vitalmouse** [comment]
r.herr says 
[ETAOHC error 502] Unknown model specified: HE

Other computer runs ok, However the only this machine shows the error.

**Comment by EricLemmon** [comment]
This looks like you have an old Helium.fld file from a previous version of Refprop on your machine somewhere, or possibly you are using an old DLL with the new fluid files from version 10.  You should do a full computer search including system and hidden directories for *.FLD and for REFP*.* and delete anything that is related to Refprop but is not located in your Refprop directory.

**Comment by vitalmouse** [comment]
solved the problem. Thank you very much!
