### ISSUE TITLE
Set Path problem

### ISSUE THREAD

**Issue by ConstiS** [usnistgov/REFPROP-wrappers#45]
Hello,
my Refprop connected with matlab works quite well, but I have the problem that I have to renew the reprop path set each time I want to use it. So I have to go to set path in matlab and there I must move the refprop path up to the first place. Is there any possibility that the Refprop path will always be on the first place by starting Matlab or that it can be read on other positions? Thank you for your answer.

**Comment by ianhbell** [comment]
Have you tried the new Python interface for MATLAB?  It is much nicer.

This is a MATLAB issue, you want to adjust the path, which if I remember correctly is done with the ``addpath`` function, but you should read the MATLAB documentation.

**Comment by ConstiS** [comment]
Thank you for your answer. I haven't tried it with the Python interface because I'm not really familiar with Python and I thought this might lead to more problems as with the wrappers. But if this is the only and easiest way to fix it, I will try your solution.
