### ISSUE TITLE
Refprop with LabView

### ISSUE THREAD

**Issue by VicentCruz** [usnistgov/REFPROP-wrappers#450]
Good afternoon, I recently bought Refprop version 10 to calculate the density and viscosity of fluids from labview, when it comes to a specific fluid I have no problem doing the calculation, however, now I want to calculate the viscosity and density when it comes to a mixture of two fluids with their molecular components entered manually from labview, could you please tell me what are the steps or dll that I have to use?

**Comment by ianhbell** [comment]
What have you tried so far? I didn't develop the wrapper, but I believe there is a place to enter the fluids as an array, and the same thing for molar composition

**Comment by VicentCruz** [comment]
So far I have been able to calculate the viscosity of dry air considering the molar composition: Nitrogen (0.7812), Argon (0.0092) and Oxygen (0.2092) by default. I would like to do the same but adding the three substances independently with their respective molecular components, not only for dry air but also using different gases. 
![1](https://user-images.githubusercontent.com/101591145/158243339-2d6c0e80-62a7-4d6e-a13a-574e1ccf759c.PNG)
![Captura](https://user-images.githubusercontent.com/101591145/158243379-115ea588-0e9a-4566-973c-de239bcbf2bb.PNG)

**Comment by ianhbell** [comment]
Look at the REFPROPdll VI, it allows for multiple inputs

**Comment by VicentCruz** [comment]
do you have any example?

**Comment by ianhbell** [comment]
Open the REFPROPdll VI, I think you can see the inputs that go into it.  I don't have access to Labview at present.
