### ISSUE TITLE
Refprop Integration into LabWindows

### ISSUE THREAD

**Issue by nicholaschowenchan** [usnistgov/REFPROP-wrappers#454]
Hi there,

I was looking into integrating a REFPROP function to calculate gas density into an existing LabWindows program. I noticed there were existing solutions for LabView and was wondering if you knew of existing examples pertaining to LabWindows?

**Comment by ianhbell** [comment]
@damianlauria do you know anything about LabWindows? I'd never heard of it before, and I wonder how hard it would be to modify the existing code for LabWindows.

**Comment by damianlauria** [comment]
Hi Ian,
I have used LabWindows pretty extensively. It's just an IDE for C with some really nice tools for making callback based GUI interfaces. If you know C it's really easy to pick up.
As to how hard it would be to modify something written with it, It's going to be just like any other C project, which is to say that it comes down to how well written the original code is.

If you want, I can give you a basic tutorial to give you an idea about the IDE. I think that would only take about a half an hour. We could talk about your project needs as well at the same time.

Cheers,
       Damian

**Comment by ianhbell** [comment]
@nicholaschowenchan @damianlauria wrote the Labview wrappers of REFPROP, so you don't need the intermediate of the REFPROP-headers that I wrote. You can just jump right into the shared library.

But.... If you are in C land, it is trickier.  Maybe @damianlauria can put together a simple example of calling a shared library with LabWindows? That should be enough to get you going I think.

**Comment by damianlauria** [comment]
I can try to put together an example in the next few days. In the meantime, this article might be helpful: https://www.ni.com/en-us/support/documentation/supplemental/09/calling-a-dll-in-labwindows--cvi---explicit-linking-vs--implicit.html

**Comment by dslauria** [comment]
I have a working example that shows basic functionality. You should be able to use it to verify your connection to the dll and then use the REFPROP Documentation pdf to expand from there. I'm going to try to get Ian to add it to the repository now.

**Comment by ianhbell** [comment]
Example was added to LabWindows folder in https://github.com/usnistgov/REFPROP-wrappers/commit/73728eac6f376528443ed8fa4607712c64e880c7

**Comment by ianhbell** [comment]
@nicholaschowenchan Any luck?

**Comment by nicholaschowenchan** [comment]
Yes, I was able to use the added example to integrate REFPROP into my  application. Thanks @ianhbell and @damianlauria!
