### ISSUE TITLE
Problem with RefPROP Gas Composition

### ISSUE THREAD

**Issue by TommasoMigliorini** [usnistgov/REFPROP-wrappers#459]
Hello everybody,
we are testing the RefPROP 10.0 dll to evaluate whether to insert it in our LabVIEW application. In our executable you can configure multiple gas compositions and calculus are performed continuously (typically 1 iteration per second).
We have read that with RefPROP it is recommended to make only one gas composition merging all elements, leaving the values of the unused elements at 0 (https://pages.nist.gov/REFPROP-docs/#changing-fluids-and-calling-setup-multiple-times).
 
In our example we have:
- Gas Composition 1: Air 100%
- Gas Composition 2: Helium 100%
RefPROP configuration:
- The unit systems is SI WITH C
- State Equation Default
If we calc HN with Air 0%, Helium 100% we receive an error. Otherwise if we calc HN only with Helium 100% we receive the correct value. This behavior is independent of the value of temperature and pressure.

So we want to ask: there are incompatibilities between specific elements? If yes, could you list us?

**Comment by TommasoMigliorini** [comment]
I gave an example by coming to the root of the problem.
I have a gas composition in which there is a minimum percentage of helium and uses the HN function. For other functions I have a 100% air gas composition.
Doing, as recommended, a single gas composition with all the gases I have between the various compositions, running HN with the correct values of the first gas composition and the air value at 0 I get an error, while running without air it works.

**Comment by ianhbell** [comment]
Air is not a pure component, you should add the air constituents and it should work.

**Comment by TommasoMigliorini** [comment]
i tried, but the results are different. if I use the air as a mixture or by putting the single elements, for example the enthalpy is completely different.

**Comment by ianhbell** [comment]
The enthalpy being different could be ok, since enthalpy is a relative property, but things get challenging with mixtures and enthalpy.  What about density or other properties that do not involve reference states?

**Comment by ianhbell** [comment]
For *pure* air, yes, but the situation changes in mixtures.
