### ISSUE TITLE
Transition to ctREFPROP from Bruce Wernick interface

### ISSUE THREAD

**Issue by sonofeft** [usnistgov/REFPROP-wrappers#46]
I’m trying to help some folks transition from the Bruce Wernick interface to Refprop7 to the ctREFPROP interface and newer versions of Refprop.

I understand that simply using a pip install should work on even old versions of Refprop
```
pip install ctREFPROP
```
When I do that and try to run the examples **test_SETREF.py** or **test_PQFLSHdll.py** codes, I get the error with Refprop8

ValueError: The function SETPATHdll could not be loaded from the shared library

Is Refprop8 too old?

### Tracebacks
```
Traceback (most recent call last):
  File "test_PQFLSHdll.py", line 18, in <module>
    R.SETPATHdll(root)
  File "D:\2018_py_proj\PRISM\prism\props\refprop7\IanBell\ctREFPROP.py", line 2897, in SETPATHdll
    if self._SETPATHdll is None: raise ValueError("The function SETPATHdll could not be loaded from the shared library.") 
ValueError: The function SETPATHdll could not be loaded from the shared library.

>C:\Anaconda\pythonw.exe -u "test_SETREF.py"
Traceback (most recent call last):
  File "test_SETREF.py", line 37, in <module>
    r.SETPATHdll(os.environ['RPPREFIX'])
  File "D:\2018_py_proj\PRISM\prism\props\refprop7\IanBell\ctREFPROP.py", line 2897, in SETPATHdll
    if self._SETPATHdll is None: raise ValueError("The function SETPATHdll could not be loaded from the shared library.") 
ValueError: The function SETPATHdll could not be loaded from the shared library.
```
### Versions

**REFPROP Version:** 8
**Operating System and Version:** windows 10
**Access Method:**  Python

**Comment by ianhbell** [comment]
Excellent issue report!!

Yes, the wrapper is intended to be used with REFPROP 9+.  There have been many improvements since REFPROP 8, so an upgrade is very much recommended!
