### ISSUE TITLE
Error in Ammonia/Water mixture properties evaluation with MATLAB wrapper

### ISSUE THREAD

**Issue by giannn97** [usnistgov/REFPROP-wrappers#467]
### Description

Hello everybody, I have an issue using the MATLAB wrapper of REFPROP. The issue is as follows: I would like to calculate temperature, entropy and quality of an ammonia/water mitxure in a subcooled state, however MATLAB gives me an error, while the actual REFPROP  desktop application works fine sometimes (other, instead, it does not converge)

Here's an example of the error I get calculating the temperature of ammonia-water at 831 kPa and enthalpy -64000 J/kg of (I could also try with other parameters but still get the same error) with the following command:

``` python
refpropm('T','H',-64000,'P',831,'Ammonia','Water',[0.58,0.42])
```
From desktop app I get:

T = 275.03 K, which is correct

From MATLAB:
``` python
Error using refpropm (line 519)
[PHFLSH error 3] One or more inputs are out of range; Temperature below triple-point or minimum temperature: T =
151.013 K, Tmin = 163.528 K; Density above upper limit: D = 56.2028 mol/L, Dmax = 55.3543 mol/L. 
```
While using this code in MATLAB:

``` python
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
MASSSI = RP.GETENUMdll(int8(0),'MASS BASE SI').iEnum;
iMass = int8(1);
iFlag = int8(0);
z = {0.58,0.42};
r = RP.REFPROPdll('Ammonia;Water','HP','T',MASSSI,iMass,iFlag,-64000,831000,z);
o = double(r.Output);
o(1)
```
I get T = 151.2853 K

While setting iFlag to 1 I get:

T = 277.8

Hope you could help me, thanks a lot.

### Versions

**REFPROP Version:** [REFPROP 10]  
**Operating System and Version:** [Windows 10 Pro]  
**Access Method:** [MATLAB wrapper)]

**Comment by ianhbell** [comment]
The GUI and DLL use different reference states. See SETREFdll to set them to be the same.

More generally, NEVER input an enthalpy value directly, always start with properties without reference state (e.g., temperature and pressure), calculate enthalpy from that, and then use that enthalpy.
