### ISSUE TITLE
Issue with Excel

### ISSUE THREAD

**Issue by jrtnp** [usnistgov/REFPROP-wrappers#469]
### Description

Unable to get REFPROP Excel add-ins to work properly

### Steps to Reproduce

1. Installed REFPROP 9.1 into C:\REFPROP
2. Verified able to use REFPROP.XLS, Excel files that contain REFPROP functions don't come up with values
3. Verified environment variables PATH for REFPROP is pointed to C:\REFPROP
4. Verified environment variables "RPprefix" are pointed to C:\REFPROP
5. Converted REPROP.XLA into an add-in and verified that it is running as an add in

6. Troubleshooting steps states "Go to the REFPROP.XLA file (assuming that it has already been selected as an Add-in) by pressing Alt-F11. Open up the item labeled REFPROP.XLA in the list on the left, click on Modules, and then on Refprop10Code. Near the top you will find …Sub _REFPROPdll Lib "REFPRP64.DLL"… Change this to …Sub REFPROPdll Lib "c:\Program Files (x86)\REFPROP\REFPRP64.DLL"… If using a 32 bit version of Excel, add the same path to the line two lines below this one."_ 

I don't seem to be able to be able to do the above. I'm not seeing "Refprop10code"

7. Tested by entering =REFPROP("DLL#") and received "NAME"

**Expected behavior:** 
Be able to get output of a file that is verified working with other users that have REFPROP installed.

**Actual behavior:** [What actually happens]
Not getting output on excel files .
### Versions

**REFPROP Version:** 
REFPROP 9.1
**Operating System and Version:** 
WINDOWS 10 PRO
**Access Method:** 

EXCEL add-in

### Additional Information

Any help would be much appreciated. Thank you!

**Comment by ianhbell** [comment]
The new add-in is for REFPROP 10, to which you should upgrade.  The old one is provided with REFPROP 9.1 in its installation directory
