### ISSUE TITLE
Issue with GETENUM

### ISSUE THREAD

**Issue by smtorrez** [usnistgov/REFPROP-wrappers#47]
Hello,

I'm getting the error:

> RP.GETENUMdll(0, "MOLAR BASE SI").iEnum
> Traceback (most recent call last):
> 
>   File "<ipython-input-300-a4843e95b932>", line 1, in <module>
>     RP.GETENUMdll(0, "MOLAR BASE SI").iEnum
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\ctREFPROP\ctREFPROP.py", line 1502, in GETENUMdll
>     if self._GETENUMdll is None: raise ValueError("The function GETENUMdll could not be loaded from the shared library.")
> 
> ValueError: The function GETENUMdll could not be loaded from the shared library.

I'm wondering if I need to upgrade my REFPROP? I had the impression that the code was compatible with REFPROP 9.1.

Thanks.

**Comment by ianhbell** [comment]
You are right, the wrapper is compatible with 9.1, but GETENUM is not present in 9.1.  See the second example here: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python
