### ISSUE TITLE
CO2 Transport Properties in Excel Wrapper Have Slight Error from GUI

### ISSUE THREAD

**Issue by henningjp** [usnistgov/REFPROP-wrappers#474]
### Description

I was verifying some of the Mathcad wrapper functions against Excel wrapper results to automate verification/regression testing.  Transport properties for CO2 were just slightly off from the Mathcad wrapper and the REFPROP GUI (which both agree).  This only happens for CO2 (so far).  When using Water as the verification fluid, transport results all agree to 1E-11.  It's very odd that the Excel wrapper should have an issue like this for just one fluid.  It is only the transport properties that are slightly off, the thermodynamic properties agree to 1E-11 for CO2 as well.  

### Steps to Reproduce

1. Evaluate state points, any phase or saturation, in Excel add-in for CO2 (Carbon Dioxide)
2. Compare with GUI values or results from one of the other wrappers
3. The comparison for one state point evaluated in excel and the relative % error from the GUI results is shown below

**Expected behavior: ** CO2 transport properties should agree exactly REFPROP GUI results (and other wrapper results). 

**Actual behavior: ** CO2 transport properties are slightly in error (1 - 3%) when evaluated using the Excel add-in.

### Versions

**REFPROP Version: ** 10.0.0.2  
**Operating System and Version: ** Windows 10
**Access Method: ** Excel Add-in (`REFPROP()` function calls)

### Additional Information

- Unit system used seems to make no difference.
- Other fluids (water so far) don't experience this problem, only CO2.  I don't know yet if there are others.
- Errors only in transport properties (thermodynamic properties are fine).

Screenshots of the issue for one state point, but similar behavior occurs at all state points.

![image](https://user-images.githubusercontent.com/17114032/187462150-8d8dacea-7946-471f-b902-c05d66b2855a.png)

**Comment by ianhbell** [comment]
This is not good. I confirm the GUI result when calling the DLL from CoolProp, and also when calling from the Python interface:
```
1.319952633449679e-05
1.319952633449679e-05 0 
```
from 
```python
import os 

import CoolProp.CoolProp as CP
AS = CP.AbstractState('REFPROP','CO2')
AS.update(CP.PT_INPUTS, 1.444304e6, 260.361)
print(AS.viscosity())

import ctREFPROP.ctREFPROP as ct
root = os.getenv('RPPREFIX')
RP = ct.REFPROPFunctionLibrary(root)
RP.SETFLUIDSdll('ARGON')
RP.SETFLUIDSdll('CO2')

r = RP.REFPROPdll('','PT','VIS',RP.MOLAR_BASE_SI, 0, 0, 1.444304e6, 260.361,[1.0])
print(r.Output[0], r.ierr, r.herr)
```

**Comment by nist-aharvey** [comment]
Is it possible that this has something to do with the fact that the CO2 transport correlations were replaced between REFPROP 9.1 and 10.0?  So that maybe the Excel is picking up the obsolete models somehow?

I think my guess was right -- I just went into the GUI and changed the viscosity model to the old one (Fenghour) and got 13.288 for that point, which matches the "wrong" value returned from Excel, so I think Excel must be using the obsolete models (or maybe the OP is accessing an obsolete DLL from Excel?).  I can't test that hypothesis on thermal conductivity because the old thermal conductivity model does not seem to be accessible from the GUI.

**Comment by henningjp** [comment]
Well, that did it.

My Excel file says it is accessing REFPROP 10.0.0.02.  That DLL is under C:\Program Files (x86)\REFPROP.  

From the Excel file, however, calling
```
   =REFPROP("FDIR","CO2")
```
is returning a path to an old 9.1.1 version fluids directory that is off in another part of my machine (same hard drive, however, as the Excel file).  Somehow the Excel VBA is picking that up from somewhere.  I'll hunt it down.  Maybe it looks for the fluids directory on the hard drive that that Excel file is on (which in this case is **_not_** C:\).

Thanks for the tip.  I'll post the results of my finding here as this maybe could bite someone else.

**Comment by henningjp** [comment]
There was a residual RPprefix that was pointing to the 9.1.1. files and I didn't know it.

Fixed.  Sorry for the confusion.
