### ISSUE TITLE
RefProp9.1 integration on Linux with Matlab and compilers

### ISSUE THREAD

**Issue by nathanpt1** [usnistgov/REFPROP-wrappers#477]
I have reviewed your material for installation of RefProp with other applications.  I have been successful in integration of RefProp9.1 with MS365/Excel and Matlab2021b on Windows10.  I am looking for information for a Linux (RHEL7/8) integration with a Linux installation of Matlab2021b and GCC/Intel Fortran/C integration.  Do you have any documentation on these steps or procedures you can point me to?

**Comment by ianhbell** [comment]
Same exact procedure. Built it yourself with: https://github.com/usnistgov/refprop-cmake

But recommend to upgrade to REFPROP 10 first.
