### ISSUE TITLE
Ideal gas properties in MATLAB

### ISSUE THREAD

**Issue by mohammadali135** [usnistgov/REFPROP-wrappers#48]
Hi.
I am using REFPROP in MATLAB. In the Version 9.1 User's Guide, it says the ideal gas properties can be calculated (figure attached below). How can I call these ideal gas properties in MATLAB? I couldn't find the variable names. 

![1](https://user-images.githubusercontent.com/40894844/42385691-bdd97698-8152-11e8-94da-061be5a0d811.png)

**Comment by ianhbell** [comment]
You need to use the Python interface to MATLAB, and then you can call the THERM0dll function to get those properties
