### ISSUE TITLE
Triple Point and Max Inputs in MATLAB using REFPROP 9.0

### ISSUE THREAD

**Issue by Andrewj0131** [usnistgov/REFPROP-wrappers#482]
Hello,

I am trying to use refpropm.m to find fluid properties using the inputs 'R' and 'M' for triple point and Tmax/Pmax, respectively. However, I received the following error message:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/115298986/194626740-9cfa773f-3124-4938-8330-24d3863df69f.png)

I checked the refprop.m file and not only do its instructions say that these inputs should be valid, but I cannot find this error message anywhere in the script. The following is the closest message that I was able to find:
![Capture](https://user-images.githubusercontent.com/115298986/194627101-160189fd-4195-4d77-9ae5-ea49fa8be7f1.JPG)
Right above this error statement, there seem to be cases that allow for 'R' and 'M' as inputs as well.

This script was originally written and run using REFPROP 10.0 before being forwarded to me, though since my REFPROP 9.0 add-in file includes these inputs, I don't see how there would be a compatibility issue.

Any help would be greatly appreciated!

**Comment by ianhbell** [comment]
The refpropm wrapper is deprecated and no longer supported.

**Comment by ianhbell** [comment]
Switch your code to use the Python interface
