### ISSUE TITLE
Call self-defined fluids out of Matlab 

### ISSUE THREAD

**Issue by davste2** [usnistgov/REFPROP-wrappers#49]
Hello,

I have a problem while using Refprop out of Matlab. I did everything the way you described it here: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB. 
When I test the example Line : ```r = RP.REFPROPdll('Water','PQ','T',int8(0),int8(0),int8(0),101.325,0.0,{1.0}) everything works.```
Problem:
When I try to use another fluid or mixture Matlab crashes (picture). I tried to use a self-created mixture like it is explained in the API documentation: ```hFld='CO2;0.2 * isobutane;0.3 * propadiene;0.5' 
r = RP.REFPROPdll(hFld,'PQ','T',int8(0),int8(0),int8(0),101.325,0.0,{1.0})```.

I tried many things like create a mixture in Refprop and just call it out of Matlab but nothing works. 

Versions : Refprop 10.0		Matlab 2018a		Windows 10
Thanks David
![image](https://user-images.githubusercontent.com/26458599/42685941-b4d0ec24-8694-11e8-9d2a-751b39ede217.png)

**Comment by ianhbell** [comment]
Can you please post your entire example file so I can run it exactly as you did?  This shouldn't happen, and we'll get to the bottom of it.  

What version of the python wrapper got installed? 0.6.1?

**Comment by davste2** [comment]
My shortened Code:

```import py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary('C:\\Program Files (x86)\\REFPROP\\REFPRP64.DLL');
systemdruck = 4;
temperatur = 20;
output = RP.REFPROPdll('AIR','PT','Bvir Cvir Dvir Evir D ISENK R',int8(10),...
        int8(1),int8(0),systemdruck,temperatur,{1.0}); % this works
%But this not
hFlD_air = 'NITROGEN;0.7552 * ARGON;0.0129 * OXYGEN;0.2314 * CO2;0.0006';
% hFlD_air = 'CO2;0.2 * isobutane;0.3 * propadiene;0.5';
output = RP.REFPROPdll(hFlD_air,'PT','Bvir Cvir Dvir Evir D ISENK R',int8(10),...
       int8(1),int8(0),systemdruck,temperatur,{1.0});
```

> What version of the python wrapper got installed? 0.6.1? 

I have not installed a wrapper. Just Python (3.7.0b4) and Refprob (10.0)

**Comment by ianhbell** [comment]
This is a definite bug in REFPROP.  Confirmed on my side too.

**Comment by jonasT44** [comment]
I am facing the same issue.
Matlab: 2017 b
Python: 3.7.2
Refprop:10
Is there a solution ?

**Comment by davste2** [comment]
I found a workaround by using the python rapper and calling it out of matlab.
My Code:

Python Wrapper Script:
`
import os, numpy as np, sys, string
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

def refprob(air, druck, temp):
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    RP.SETPATHdll(os.environ['RPPREFIX'])
    r = RP.REFPROPdll(air, "PT","Bvir Cvir Dvir M D ISENK R V", 10, 0, 0, druck, temp, [1.0] + [0.0] * 19)
    print(r.Output[0:8], r.ierr, r.herr)


if __name__ == '__main__':

    x = sys.argv[1]
    y = float(sys.argv[2])
    z = float(sys.argv[3])
    # x = 'NITROGEN;0.75519*ARGON;0.01288*OXYGEN;0.23135*CO2;0.00058'
    # y = 9 Pressure
    # z = 20 Temperature
    refprob(x, y, z)
`

Matlab Script:

`
% hFlD_air  =  'NITROGEN;0.75519*ARGON;0.01288*OXYGEN;0.23135*CO2;0.00058'
command = ['PythonPath\python.exe Python_Wrapper.py ',...
           hFlD_air ,' ', num2str(Pressure),' ', num2str(Temperature)];
       [a,b] = system(command);
       refprob_out = str2num(b);`

Hope that helps !

**Comment by ianhbell** [comment]
A couple of comments: 
1) You should not be hard-coding the enumerated value for the unit system (10 in your case).  Retrieve it always from GETENUMdll.
2) If I understand correctly, this code works in Python, but the same code doesn't work in MATLAB?  That's weird.  Must be related to how strings differ in MATLAB and Python

**Comment by ianhbell** [comment]
Fixed.  Problem was in the Python wrapper.  The inout arguments were handled incorrectly.  My mistake.

To update version of ctREFPROP: 
```
[v,e] = pyversion; system([e,' -m pip install --user -U ctREFPROP'])
```
