### ISSUE TITLE
Problem Refprop phase envelope graph calculation in Excel 

### ISSUE THREAD

**Issue by ArezooHa** [usnistgov/REFPROP-wrappers#490]
### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

I am plotting the P-T diagram for natural gas samples with different compositions using Refprop (version 10) in Excel (both compiling directly in Excel or using VBA). I have been able to reproduce the PT diagrams, the same as what Refprop program produces for natural gas compositions. However, those calculations do not converge for hydrogen blends of natural gas compositions. Adding hydrogen to the natural gas composition, the calculations (mostly bubble-point at higher pressures) do not converge . The error is:

"#[SATP error 144] Iteration for saturation state did not converge"

My vba code includes calculation of bubble-point and dew-point temperatures at pressures of 0.01 to 100 MPa and plotting both on the same graph. 
I was wondering if there's any way I can approach for natural gas compositions blended with hydrogen?

### Steps to Reproduce

1. Here's the main calculation lines for the points. Fluidstring is a mixture of mainly methane and some larger hydrocarbons. The problem occurs when some percentage of hydrogen is added to the blend. PressureDataPointArray contains numbers between 0.01 and 100 MPa.

BubbleTDataPointArray(i) = REFPROP("T", Fluidstring, "Pliq", "SI", PressureDataPointArray(i))
DewTDataPointArray(i) = REFPROP("T", Fluidstring, "Pvap", "SI", PressureDataPointArray(i))

**Expected behavior:** 

I expect to be able to calculate all the points in order to plot the PT diagram for all the gas compositions.

**Actual behavior:** 

For blends of hydrogen with natural gas, the calculations mentioned above do not converge in the excel cell or using VBA. The error that appears:
"#[SATP error 144] Iteration for saturation state did not converge"

### Versions

**REFPROP Version:**10 
**Operating System and Version:** Windows 10  
**Access Method:** Excel VBA

**Comment by ianhbell** [comment]
First thing to try is to enable the initialization of the phase boundary in the GUI, or calling SATSPLNdll in the VBA (see the code for some lines to uncomment)

**Comment by ArezooHa** [comment]
I have uncommented iFlag = 1. Is it all needed to be done for calling SATSPLNdll?

**Comment by ianhbell** [comment]
Yes, that's right

**Comment by ArezooHa** [comment]
The problem exists while calling SATSPLNdll ( iFlag = 1).

**Comment by ianhbell** [comment]
Well, you might need to implement the new models for hydrogen models from : https://aip.scitation.org/doi/abs/10.1063/5.0040533 .  Many of the hydrogen containing binary models in REFPROP are placeholders, and I suspect that is causing the problem.

**Comment by ArezooHa** [comment]
The REFPROP software itself does produce the P-T plots for those hydrogen blends (with the GERG 2008 model), however, I am not able to reproduce the same plot using the Excel wrapper, due to bubble-points calculations not converging (I have uncommented the VBA code line related to GERG-2008 equation of state). My assumption was that the same saturation state calculations are performed in the two platforms. Am I right in that assumption?

**Comment by ianhbell** [comment]
The GUI is doing something different, it makes the isopleth of the phase envelope. As you could do too, with something like this: https://nbviewer.org/github/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb#Phase-Boundary-for-Mixtures
