### ISSUE TITLE
Calling alternate equation of state in Refprop wrapper (Excel)

### ISSUE THREAD

**Issue by blobbasaurus** [usnistgov/REFPROP-wrappers#493]
For the fluid xenon.fld (and other fluids) I noticed there are alternative equations of state that permit evaluation of fluid properties at wider ranges of temperatures. 
 
We were unsure how to call this function using the RefProp Excel dll -- For example in Excel can I call this alternative equation of state directly? 
 
If so, what would be the appropriate syntax, eg, in a form similar to this below:
=@Enthalpy(fluid name,"TP","mks",t1,p1,....,…,equation of state??)
 
We can see how it is possible to call alternative EOS or other properties by adjusting the .fld file, but this seems a little barbaric if the alternate functions can be called directly by adjusting flags in the function.  Thanks!

**Comment by henningjp** [comment]
In Excel, open the example file.  There’s plenty of good documentation in there on making calls.  All calls are made through the REFPROP function.  Within the REFPROP.DLL (REFPRP64.DLL) there is also high-level call to the FLAGS function; through which flags can be set to specify alternate EOS.  However, I’m not sure if FLAGS is implemented in the Excel add-in.  This may require you to use another front-end framework, like Python.  Again, there will be an example of what is callable in the Excel example file.

**Comment by ianhbell** [comment]
You want the ``SETMODdll`` function: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SETMODdll. It is not exposed to Excel right now but you could follow the pattern of how the REFPROPdll function is called. Better would be to use Python or similar, as the function is already exposed in the Python interface.
