### ISSUE TITLE
Mathematica 13.2 Breaks Unit Handling in Mathematica Wrapper

### ISSUE THREAD

**Issue by henningjp** [usnistgov/REFPROP-wrappers#495]
### Description

Mathematica 13.2 breaks some unit handling employed in the RefpropLink paclet; Specifically the definition of Newton (N) and Ferenheit (°F) in the underlying RefpropUnits code.

### Steps to Reproduce

1. Just load the RefpropLink wrapper per usual with 
```WL
Needs["RefpropLink`"]
```

**Expected behavior:** No errors on load and accurate behavior of pre-defined units.

**Actual behavior:** 
1. Loading RefpropLink throws an error, at which point there is confusion between N, Newton, and Newtons.
```WL
Quantity: Unable to interpret unit specification 1. N .
```

2. Applying pre-defined unit, °F, results in non-sensical unit conversion
```WL
In[1] T = 72 °F
Out[1] 18426.8 K
```

These are the only issues discovered so far.  Basic REFPROP wrapper functionality is still working.

### Versions

**REFPROP Version:** REFPROP 10  
**Operating System and Version:** Windows 10 
**Access Method:** Mathematica Wrapper (Mathematica 13.2 - Recent Update)

### Additional Information

Working on fixing this.  
**_Suggest not upgrading to 13.2 just yet until a patch is created._**

Suspect some duplicate symbol definitions are now bleeding over to create conflicts with unit symbols initialized when RefpropLink is loaded.
* The symbol "N" has always been a built-in numeric evaluation function, but now seems to be causing a conflict with definition of "Newton".  This wasn't a problem before, but there's a simple fix for this.
* This one may be more problematic as the application of the affine unit, °F, seems to have changed in 13.2.  May need another way to represent this unit easily or limit users to native `Quantity` definitions for "DegreesFerenheit" or absolute units.  Additionally, `K` is now a pre-defined symbol in 13.2 (it wasn't before), which may be causing a conflict.
* Further investigation shows that this second issue may be a bug in Mathematica 13.2.  As of version 13.2, Temperature units now come in two types, `Absolute` and `Difference`.  For example, Rankine units are represented as "DegreesRankine" (Absolute) and "DegreesRankineDifference" (difference unit).  However, some straight-forward unit conversions (without RepropLink loaded) show that when converting to/from affine temperature units of °F and °C,  "DegreesRankine" is being treated as a **_difference_** unit and not an absolute units.  This may be creating all kinds of repercussions.  Currently investigating this issue with Wolfram.

**Comment by ianhbell** [comment]
Would this break backwards compatibility for earlier version of Mathematica?

**Comment by henningjp** [comment]
No.  I can fix the first issue for all versions and have already tested it using a more rigorous unit definition.

The second issue may fix itself if it’s really a Wolfram bug.  If not, a workaround can be made to be version dependent in the paclet code; provided I can find a workaround.

**Comment by ianhbell** [comment]
Did you report the possible bug?

**Comment by henningjp** [comment]
Checked version 3.1 at work this week to verify.  Works fine.
Reporting 13.2 issue with examples this Friday to Wolfram.

**Comment by henningjp** [comment]
Wolfram is aware and working on it.  In the meantime, they've provided a work-around.  I'll issue a patch update this week once I've tested it with the workaround applied only if MM version 13.2 is detected by the paclet scripts.
