### ISSUE TITLE
Cannot calculate EOSMIN temperature of R454C

### ISSUE THREAD

**Issue by PhilippJR** [usnistgov/REFPROP-wrappers#498]
I cannot calculate the EOSMIN temperature of R454C in Excel. It works for other refrigerants, like R455A. Also, EOS**MAX** works.
![image](https://user-images.githubusercontent.com/81237852/213475283-a4c6b44d-9996-4e6d-aabe-8e9cb2990b5a.png)
I cannot remember, if the mix file was delivered with RefProp or if I downloaded it [here](https://github.com/usnistgov/REFPROP-issues/issues/358#issuecomment-872395316) from @ianhbell.

REFPROP Version: 10.0
Operating System and Version: Windows 11
Access Method: Excel 365, 64bit

**Comment by ianhbell** [comment]
Can you roll back to the REFPROP 10.0 HMX please so we can see where the problem comes from?

**Comment by PhilippJR** [comment]
I did not replace the HMX.BNC when I added the new *.mix files. Was I supposed to do that? There is no HMX.BNC in the zip.
However, I replaced it, when I got the R1132a.fld and R473A.mix files from Koura.

I rolled back to the file shipped with RefProp 10 and get exactly the same result.

To make it easier for you to reproduce, please find the Excel file attached.
[Mappe1.xlsx](https://github.com/usnistgov/REFPROP-wrappers/files/10463858/Mappe1.xlsx)

**Comment by PhilippJR** [comment]
Maybe, the following helps:
I just wanted to find the EOSMIN temperature of R454C with the RefProp GUI by entering too low pressures during "Calculate > Saturation Tables". While for R407C there is an error message that tells me the min temp, there is no such message for R454C.
**R407C**
![image](https://user-images.githubusercontent.com/81237852/213642151-1aa8bb9b-65f4-44b0-8a39-b7dae80b424b.png)
**R454C**
![image](https://user-images.githubusercontent.com/81237852/213642279-eefaba28-61a8-45d1-b74f-2a919959c2be.png)

**Comment by ianhbell** [comment]
@PhilippJR You are experiencing something different.  For some fluids (R407C, R410A, R404A, R507C, Air), we have pseudo-pure EOS and for all other mixtures a mixture model is used. It has long been my opinion that we should require users to explicitly specify ``R410A.MIX`` or ``R410A.PPF`` to ensure that they understand what they are actually doing.  The two approaches have some subtle and important differences. For one, with the pseudo-pure EOS, calculations within the two phase dome are not defined. The pseudo-pure EOS is only for homogeneous and saturated states.

**Comment by NickAtNight62** [comment]
What is the most efficient means to obtain the triple point?

For a pure fluid:   Is it stated in the fluid file? 1

For a mixture of a fluid?

——

1 “ REFPROP is a Program, not a Database Containing Measurements
The REFPROP “database” is actually a program and does not contain any experimental information, aside from the critical and triple points of the pure fluids. The program uses equations for the thermodynamic and transport properties to calculate the state points of the fluid or mixture. ”

**Comment by ianhbell** [comment]
Efficient in what sense? If computationally, perhaps one of the legacy low-level functions after you have loaded a model.

**Comment by PhilippJR** [comment]
> For some fluids (R407C, R410A, R404A, R507C, Air), we have pseudo-pure EOS and for all other mixtures a mixture model is used.

Do you mean, there is no EOS for R454C.mix and therefore, EOS**MIN** is not defined? If so, why does the calculation of EOS**MAX** work?

**Comment by ianhbell** [comment]
That is sort of correct.  A mixture model (which is also a sort of EOS depending on who you ask) is used for R454C. EOSMIN, to my knowledge is supposed to be a mole-fraction-weighted average of the minimum temperatures of the pure fluids, so I have no idea why it would ever not be able to be calculated.

Please see https://aip.scitation.org/doi/full/10.1063/5.0135368 for the new model for R32/1234yf that should be used in all new work as it is more accurate.

**Comment by PhilippJR** [comment]
OK, interesting. Do I simply have to copy the files from check_values.zip\FLUIDS to the corresponding RefProp folders? How big are the differences in thermophysical properties compared to the "old" files? Are we talking about 10% or is it more 0.01%?

**Comment by ianhbell** [comment]
Check the paper; the values are compared there.

I will warn you, we have very recently identified a serious bug in REFPROP 10.0 when you have more than 40 departure functions in the HMX.BNC file. We are working on finding a good resolution to that problem at the moment.

**Comment by PhilippJR** [comment]
I do not know what departure functions are but I added only 1 refrigerant (R473A) and all values I calculated the last days seem plausible.
I do not have access to the paper and hope the differences are not to big. I will wait for RefProp 11...

**Comment by ianhbell** [comment]
Please shoot me an email (ian.bell@nist.gov) and I will send you the paper.   You mean you added a predefined mixture file, right?

Sorry to say that you will be waiting a long time for REFPROP 11.

**Comment by PhilippJR** [comment]
Thanks for the paper.
I added several mixture file, that you provided [here](https://github.com/usnistgov/REFPROP-issues/issues/358#issuecomment-872395316).
In addition, I added R1132a.fld and R473A.mix that I received from Koura. I also had to modify the HMX.BNC if I remember correctly.

**Comment by PhilippJR** [comment]
I took a look at your paper and think that the new files could improve my calculations. I do not have the time to implement it now but hopefully in April after a major release.
What is the correct procedure? Do I simply have to override the files in C:\...\REFPROP\FLUIDS with the files attached to the paper \check_values.zip\FLUIDS?

A little off topic but since it is not an issue, I do not want to open a new thread: When I try to use the fluid R1234ze in Excel, RefProp tells me, it is old and I should use R1234ze**e**. Googling the difference between the two refrigerants is a little tricky because there are many useless results. So, what is the background?

**Comment by ianhbell** [comment]
Regarding procedure: Yes and no.  You need to merge the new departure functions from the paper with the existing ones in the HMX.BNC so that you can model not ONLY the new mixtures but also the old ones. The FLD files can be overwritten with the new ones (but keep a backup of the originals). But you may run into a serious bug that we have just identified: there is a hard limit of 40 departure functions in the HMX.BNC in version 10.0 of REFPROP, and if you exceed that, REFPROP will be silently corrupted.  You might want to wait for a bugfix release fixing this limit.

Regarding question 2: this is described in our paper: https://www.researchgate.net/profile/Ian-Bell/publication/352048747_Survey_of_Data_and_Models_for_Refrigerant_Mixtures_Containing_Halogenated_Olefins/links/60d112f892851ca3acbae812/Survey-of-Data-and-Models-for-Refrigerant-Mixtures-Containing-Halogenated-Olefins.pdf. 1234 tells you how many C,F,H there are, the ze gives more specificity, and the (E) or (Z) tells you which 3D conformation of the molecule you have.  If you were using R1234ZE before, that is actually R1234ZEE.  We should have never accepted R1234ZE as a fluid name previously.

**Comment by PhilippJR** [comment]
As mentioned above, I do not have the time right now anyway. I will wait for a bugfix.

Thanks for the ze-explanation.

**Comment by Steph-Huu** [comment]
Hi @PhilippJR,
I saw your comment in issue #498 where you mentioned that you obtained the R1132a.fld and R473A.mix files directly from Koura.
I'm currently doing research on low-GWP refrigerants and would really appreciate it if you could share the R1132a.fld file (and the mix file if possible). I will only use it for non-commercial research/academic purposes and will not redistribute it.
If you're able to share it, I can provide my email address privately. Thank you very much for your help!
Best regards.

**Comment by PhilippJR** [comment]
Sorry @Steph-Huu, I am most probably not allowed to share these files. But why not ask them yourself?
