### ISSUE TITLE
Problem Returning Water State Properties Through Pressure, Enthalpy Lookup

### ISSUE THREAD

**Issue by ishceyhan** [usnistgov/REFPROP-wrappers#499]
### Description

I am trying to look up water state properties through pressure and enthalpy (P,H) lookup.
REFPROP either thinks that the state is in the solid phase (incorrect) or returns an incorrect temperature.

### Steps to Reproduce

1. Enter the following pressure and enthalpy values
P=20.3288192217689 MPa  (into cell B8)
H=464.426995193816 kJ/kg (into cell C8)

2. Enter the following formula into Cell D8:
=REFPROP("T","water","PH","SI with C",B8,C8)

3. I get one of the following (usually the first, sometimes the second).
#[PHFLSH error 16] One or more inputs are out of range; Inputs are within the solid phase.
or 
-76.7701

4. Reverse the lookup
P=20.3288192217689 MPa  (into cell B15)
T=107.187262805806 °C (into cell D15)

5. Enter the following formula into Cell C15:
=REFPROP("H","water","TP","SI with C",D15,B15)

6. This returns
H=464.426976635102 kJ/kg
so the correct temperature from steps 2-3 should be 107.2°C

**Expected behavior:** 
Should return T=107.2°C

**Actual behavior:** 
See step 3 above - either returns "Solid Phase" error or an incorrect temperature. 

### Versions

**REFPROP Version: 10.0 / DLL: 10.0.0.02
**Operating System and Version: MS Windows 10 (64-bit)
**Access Method: Excel REFPROP function 

### Additional Information

See attached Excel file.

[REFPROP_Issue.xlsx](https://github.com/usnistgov/REFPROP-wrappers/files/10475249/REFPROP_Issue.xlsx)

**Comment by ianhbell** [comment]
You should always start such round-trips from a state point with properties with no reference state in them (T, p, rho, etc.). Otherwise you have to worry about the reference state.

**Comment by ishceyhan** [comment]
I am not sure I understand. I am not doing a round-trip. The reverse (1-3 vs. 4-6) is to illustrate that h=f(T,P) works as expected, but T=f(P,h) does not at pressures 20.33 MPa (and possibly higher).

Here are some other data points. Columns A, B and C have numeric values for P, T and H, respectively. 
Column E has =REFPROP("H","water","TP","SI with C",B3,A3); it works fine.
Column F has =REFPROP("T","water","PH","SI with C",A3,C3); it works fine except at one point, where it fails. It shouldn't.

![image](https://user-images.githubusercontent.com/44853764/213945980-a1f2b74c-2236-463b-8367-69f90e98efa2.png)

Again, I am not trying to a round-trip. I have a heat exchanger model. I need to use P and H to define the state in order to handle potential for phase change and look up all the other properties as functions of P and H. This fails at that one point.

If I use P and T as to define the state, REFPROP works, but I can't use this formulation unless I ensure that I stay away from phase change.

**Comment by ianhbell** [comment]
Maybe let's try with the beta. Can you please email me (ian.bell@nist.gov) and I can send you that.

**Comment by nist-aharvey** [comment]
Ian, I note that this calculation works correctly in the GUI version I have on my machine, which is a beta version with DLL version 10.0.0.98.

**Comment by ianhbell** [comment]
Good, so it should work after the updated DLL are used.

**Comment by ishceyhan** [comment]
As nist-aharvey mentioned, the calculation works properly with DLL version 10.0.0.98. Thank you!
