### ISSUE TITLE
Calling REFPROP from Simulink

### ISSUE THREAD

**Issue by akshayas1987** [usnistgov/REFPROP-wrappers#50]
Matlab Version: R2015b
REFPROP version: 9.1
OS: WIndows 7

 Problem: Using matlab function block to call refprop and calculate enthalpy. 

function Hin = fcn(Tfin,p)

Hin =refpropm('H','T',Tfin,'P',p*1e2,'R1233zd');

end

![image](https://user-images.githubusercontent.com/41391994/42902907-27573bec-8a9e-11e8-8d6b-c305c1775e23.png)

When I run the model I get errors stating that codegen doesn’t support a lot of the functions that refrprop uses.
I placed the EX_C2  file in my refprop folder. I am not a software person so please be patient with me! 

I can make maps of enthalpy and put it into simulink but this approach seems so much easier so I'd like to know if it can be done.

**Comment by ianhbell** [comment]
What errors exactly do you get with "errors stating that codegen doesn’t support a lot of the functions that refrprop uses" ?  In the future, please fill out the complete issue template.

**Comment by akshayas1987** [comment]
Here is the full list.

1		
refpropm
190
This operation does not support cell arrays. Use curly braces instead.
2		
refpropm
195
Function 'libisloaded' is not supported for code generation. Consider adding coder.extrinsic('libisloaded') at the top of the function to bypass code generation.
3		
refpropm
204
Function 'exist' is not supported for code generation. Consider adding coder.extrinsic('exist') at the top of the function to bypass code generation.
4		
refpropm
208
Expected a scalar. Non-scalars are not supported in IF or WHILE statements, or with logical operators. Instead, use ALL to convert matrix logicals to their scalar equivalents.
5		
refpropm
211
Anonymous functions are not supported for code generation.
6		
refpropm
219
The function 'strcat' is not supported for standalone code generation. See the documentation for coder.extrinsic to learn how you can use this function in simulation.
7		
refpropm
223
The function 'strcat' is not supported for standalone code generation. See the documentation for coder.extrinsic to learn how you can use this function in simulation.
8		
refpropm
224
The function 'strcat' is not supported for standalone code generation. See the documentation for coder.extrinsic to learn how you can use this function in simulation.
9		
refpropm
227
The function 'strcat' is not supported for standalone code generation. See the documentation for coder.extrinsic to learn how you can use this function in simulation.
10		
refpropm
227
Undefined function or variable 'notfound'. The first assignment to a local variable determines its class.
11		
refpropm
227
Undefined function or variable 'warnings'. The first assignment to a local variable determines its class.
12		
refpropm
231
Attempt to extract field 'FluidType' from 'mxArray'.
13		
refpropm
233
Attempt to extract field 'FluidType' from 'mxArray'.
14		
refpropm
234
Attempt to extract field 'mixFlag' from 'mxArray'.
15		
refpropm
236
Function 'lower' is not defined for values of class 'double'.
16		
refpropm
237
Attempt to extract field 'mixFlag' from 'mxArray'.
17		
refpropm
239
Attempt to extract field 'BasePath' from 'mxArray'.
18		
refpropm
240
Undefined function or variable 'fluidFile'. The first assignment to a local variable determines its class.
19		
refpropm
241
Attempt to extract field 'BasePath' from 'mxArray'.
20		
refpropm
243
Undefined function or variable 'mixFile'. The first assignment to a local variable determines its class.
21		
refpropm
244
Function 'unicode2native' is not supported for code generation. Consider adding coder.extrinsic('unicode2native') at the top of the function to bypass code generation.
22		
refpropm
245
Undefined function or variable 'hmxnme'. The first assignment to a local variable determines its class.
23		
refpropm
245
Undefined function or variable 'hmxnme'. The first assignment to a local variable determines its class.

**Comment by ianhbell** [comment]
Before you dive into Simulink linkage (anyway, not sure if it is possible), you should ensure that your REFPROP installation is working with something like this: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB/legacy#instructions-on-windows : 

``` matlab
>> refpropm('T','P',101.325,'Q',0,'WATER')

ans =

  373.1243
```

I'm not sure if loadlibrary can be used in a Simulink block.  If not, this is a dead end and there is no way it can work.

**Comment by akshayas1987** [comment]
Hi,

Yes. Refprop works well with matlab commands. Looks like codegen with simulink doesn't work with loadlibrary. 

Thanks for looking into this.

**Comment by stephen-hills** [comment]
I've run into the same problem.  Refprop works when using Matlab commands, but when I try to call Refprop in Simulink using a Matlab function block, I get a lot of errors and it doesn't work.  Is there any known way to use Refprop in Simulink?

**Comment by ianhbell** [comment]
Does simulink support calling Python?  If so, then you can use the new interface.  Otherwise, you'll have to contact Mathworks.

**Comment by sabrina-lazzari** [comment]
Hi to everyone, did you solve these problems? I have the same problems. I want to simulate ORC Rankine with simulink using refpropm. This program works on matlab but it produce the same errors of akshayas1987 in simulink. Do you have some kind of information for solve these problems?

**Comment by Rabihalh** [comment]
Hello, Is this issue solved? I am trying to link simulink with refprop and it is not working. 

It is working between matlab and refprop.

**Comment by ianhbell** [comment]
Did you contact Mathworks?

**Comment by Rabihalh** [comment]
Not really. I've been trying to do it myself. 

I will try to contact them.

**Comment by EstebanBarraza** [comment]
i´ve the solution. you must copye this line in your function code ...
coder.extrinsic('refpropm')
so, you'll can to call the refprop code in your matalbfunction
grettings from Chile c:
