### ISSUE TITLE
Does REFPROP have Propylene Glycol?

### ISSUE THREAD

**Issue by MaxD404** [usnistgov/REFPROP-wrappers#508]
### Description

I am looking for Propylene Glycol in the REFPROP fluid directory, but I do not see it. I can only find Ethylene Glycol, is Propylene Glycol under another name?

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 11
**Access Method:** MATLAB

**Comment by ianhbell** [comment]
Please email me: ian.bell@nist.gov; the EOS for propylene glycol is not provided with REFPROP 10.0, but can be made available.
