### ISSUE TITLE
Enterprise License -current version of DLLs

### ISSUE THREAD

**Issue by Olaf-Gerald** [usnistgov/REFPROP-wrappers#514]
Hello,
I have installed REFPROP 10 using an installation routine called 944SETUP.EXE provided with our enterprise license and updated the REFPROP.dll and REFPRP64.dll as instructed using the link https://trc.nist.gov/refprop/10-BETA/REFPROP.HTM.

It indicates version Version 10.0.0.98 being the current one until 2023-02-17.

Opening REFPROP.xls I was informed on the Welcome page that the current version is "10.0a" while my version is correctly indicated being 10.0.0.98. Do I need different / updated DLLs?

CheckSum page shows significant differences especially for the silicone oils.

Your help is most appreciated!

Olaf
![image](https://user-images.githubusercontent.com/125962165/220301082-579caa40-05ee-4e0d-948d-1848411580a3.png)

**Comment by Olaf-Gerald** [comment]
Now the libraries are expired. How do I get a new one?
Can anyone respond to this, please?

![image](https://user-images.githubusercontent.com/125962165/221802406-f16a02e3-d9be-4880-baf6-c2c9dcc05639.png)

**Comment by ianhbell** [comment]
Please re-download the files. The links are the same, but the expiration is set to December 2023. I am working on updating that page.

**Comment by Olaf-Gerald** [comment]
Thank you very much!
