### ISSUE TITLE
[PHFLSH error 224] dew point calculation did not converge within 2-phase iteration:  SATTP error:  Density roots equal

### ISSUE THREAD

**Issue by Francesco983** [usnistgov/REFPROP-wrappers#515]
Hi everyone,
I have a problem with REFPROP in Matlab. I modeled a methane liquefaction plant using a mixed refrigerant (composition in the code line), this error is shown during the simulation:

**[PHFLSH error 224] dew point calculation did not converge within 2-phase iteration:  SATTP error:  Density roots equal**

refering to:

**[T_11c, X_11c] = refpropm('TQ','P',P_11c,'H',h_11c, 'nitrogen', 'methane', 'ethane', 'propane', [0.0521 0.1402 0.1405 0.6672])**

where P_11c (P_11c = 1.113 bar) is fixed and h_11c is updated at each iteration. Initially, the simulation goes, but when the enthalpy is equal to 134.18 kJ/kg, this error appears. In the penultimate iteration, the enthalpy is equal to 187.12 kJ/kg and the simulation goes.
Using these values for P (P_11c = 1.113 bar) and H (h_11c = 134.18 kJ/kg) on REFPROP, the required values are given, then what can be the problem in Matlab?

This is my first time creating an issue on GitHub, I hope I followed the rules and was clear.
Thanks to whoever will answer,
Francesco

**REFPROP Version:** [REFPROP version 9.1]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [MATLAB R2021b]

**Comment by ianhbell** [comment]
The refpropm interface is no longer supported. You need to upgrade to the Python interface version for MATLAB.

Then, you can call the SATSPLNdll function to force the isopleth of the phase envelope to be built. That helps for a lot of cases like this.

**Comment by Francesco983** [comment]
@ianhbell Thanks for the reply. How does the SATSPLNdll function fit in this case? Here's the code line below
[T_11c, X_11c] = refpropm('TQ','P',P_11c,'H',h_11c, 'nitrogen', 'methane', 'ethane', 'propane', [0.0521 0.1402 0.1405 0.6672])

**Comment by ianhbell** [comment]
First step: convert to the python interface

**Comment by Francesco983** [comment]
Already done

**Comment by ianhbell** [comment]
Please show me your code that you are running with the Python interface.

**Comment by Francesco983** [comment]
I connected Python to Matlab and installed ctREFPROP as suggested in this issue https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/MATLAB/README.md then I check the practical example, but it doesn't run, becauce also I don't understand that I didn't understand how it is implemented via python coding.

**Comment by ianhbell** [comment]
We don't really support version 9.1 anymore, the version 10 has a lot of new features and a new more friendly programming interface. The examples are all for version 10.0, using the new functions.

**Comment by ianhbell** [comment]
In version 10.0, both of your calculations work:

```python
import os
os.environ['RPPREFIX'] = os.getenv('HOME')+'/REFPROP10'

import ctREFPROP.ctREFPROP as ct
RP = ct.REFPROPFunctionLibrary(os.getenv('RPPREFIX'))
RP.SETPATHdll(root)
print('version:', RP.RPVersion())

imass = 0
z = [0.0521, 0.1402, 0.1405, 0.6672]
P = 1.113e5

for h in [187.12e3, 134.18e3]:
    r1 = RP.REFPROPdll('NITROGEN;METHANE;ETHANE;PROPANE','PH','T',RP.MASS_BASE_SI,imass,0,P,h,z)
    print(r1.Output[0:1], r1.ierr)
```
yields
```
version: 10.0
array('d', [208.60055889815573]) 0
array('d', [200.99859910490193]) 0
```

**Comment by Francesco983** [comment]
So, I need to switch to version 10, is there an accademic version for students at a discounted price?
Anyway, thank you so much!🙏

**Comment by ianhbell** [comment]
No, I am afraid there isn't an academic version
