### ISSUE TITLE
Possible Incorrect Buffer Lengths in LabVIEW Wrapper

### ISSUE THREAD

**Issue by DBTaylor** [usnistgov/REFPROP-wrappers#518]
It looks like some REFPROP calls in the LabVIEW wrapper are not properly initializing buffers or setting buffer lengths.

I do not have any incorrect behavior that I know is caused by this. The calls seem to be working correctly. I just want to verify correctness.

For example, in this call to REFPROP2dll:
![refprop2dll](https://user-images.githubusercontent.com/4438002/222731250-c5e64287-a3f3-48a0-8340-a2197ef0761d.png)
hFld, hIn and hOut are not padded to 10000, 255, and 255 respectively, but those are the lengths being passed. Also, the herr buffer is not being initialized, despite the DLL being given a length of 255.

If this is an issue, would it be preferable to set the lengths to match the input strings, or to pad the input strings?

**Comment by dslauria** [comment]
LabVIEW actually is padding to the numbers specified for those string lengths. If you open the Call Library Function node, you can see that the minimum length for each of those strings is defined by the length inputs.

![image](https://user-images.githubusercontent.com/34315230/222797647-899b4549-a96e-4946-8cca-691c449ff8a5.png)

It is possible to create a problem if the actual strings passed in are longer than those length values and the length values aren't updated manually. I can see where this could cause confusion, so I'll post an update later today. In the meantime, you can explicitly adjust the field lengths to your input string lengths like this:

![image](https://user-images.githubusercontent.com/34315230/222798559-4c78ca00-7f34-4fd1-b54e-821d6c72da45.png)

If you do that, be sure to modify the minimum value field in the Call Library Function to a static default value that corresponds to those listed in the documentation. That will prevent issues if a blank string is passed in where you could end up with a length of zero, which would cause an error.

**Comment by DBTaylor** [comment]
Thanks for the clarification. I had no idea those minimum size configuration options existed in the node
