### ISSUE TITLE
dll function “setmixdll ”got an error

### ISSUE THREAD

**Issue by birdol** [usnistgov/REFPROP-wrappers#52]
Program with vb.net , Microsoft Visual Studio 2008
```
Public Class Form1

'here show me an error
    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click
        Dim ref As String = "R410A.MIX"
        Dim temp As Double = Temperature(ref, "Pvap", "E", "100")
        MsgBox(temp)
    End Sub

'here is ok
    Private Sub Button2_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button2.Click
        Dim ref As String = "R32.FLD;0.697614699375863;R125.FLD;0.302385300624138"
        Dim temp As Double = Temperature(ref, "Pvap", "E", "100")
        MsgBox(temp)
    End Sub
End Class
```

**Comment by ianhbell** [comment]
Hello! Where on the internet?  And what error code did you get?

**Comment by birdol** [comment]
The url ... lost...  And   the error msg like this : 
module1.vb , line 568
```
Call SETMIXdll(hmxnme, hfmix, hrf, nc2, hfld, xtemp(0), ierr, herr, 255, 255, 3, 10000, 255)

AccessViolationException:
Attempted To Read Or Write Protected Memory. This Is Often An Indication That Other Memory Is Corrupt
```

**Comment by ianhbell** [comment]
That wrapper file was not produced or supported by NIST people.  Can you please try to contact the person that wrote the original file?

Also, you should check out your options at https://github.com/usnistgov/REFPROP-wrappers

**Comment by birdol** [comment]
thanks a lot , and  i got the solution. 

function setmixdll ,  the input： hmxnmeand and hfmix ， in Excel vba，this two string ，length is 255，but vb.net is not。

so lines bellow is ok
hmxnme += New String(" ", 255 - hmxnme.Length)

**Comment by ianhbell** [comment]
Thanks for the feedback and the fix. Can you please close the issue if this is resolved?
