### ISSUE TITLE
Value error on M1 Mac

### ISSUE THREAD

**Issue by achi7-fm** [usnistgov/REFPROP-wrappers#523]
### Description

I've followed the steps noted here to add the RefProp macro in Excel on an M1 Mac. https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/Excel/README.md
However, even after changing the REFPropdll path as noted in step 8, I am still receiving the Value error noted at the top of the Refprop10code. 

### Steps to Reproduce

1. Using the REFPROP Wizard and the default inputs, click calculate. 
2. Alternatively, type `=refprop("D", "Air", "TP", "SI", 273.15, 0.1, 0)` in the cell directly.

**Expected behavior:** [What you expect to happen]
Cell to be populated with density from RefProp. 

**Actual behavior:** [What actually happens]
`Make sure the REFPROP.XLA add-in is enabled to calculate items in the cells.` message appears in the cell when the Wizard is used, #VALUE when the equation is typed directly into the cell.

### Versions

**REFPROP Version:** 10
**Operating System and Version:** M1 Mac
**Access Method:** Excel

### Additional Information
I've ensured the REFPROP AddIns and REFPROP Ribbon check boxes are ticked in the Add-ins pop up. REFPROP appears in the Excel main ribbon.

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
Are you able to call the shared library from other tools like Python?

**Comment by ianhbell** [comment]
In that case I would just use Python. Getting REFPROP to play nicely in Excel is sometimes a bit challenging, especially on mac.

**Comment by achi7-fm** [comment]
Fair enough, thanks for your help!
