### ISSUE TITLE
Matlab fails to solve

### ISSUE THREAD

**Issue by Alhabeeb86** [usnistgov/REFPROP-wrappers#525]
Hi,
In my case:
1- Matlab + refprop  version 9.1 works perfectly with mixtures (e.g. R455A) but fails with pure substances (e.g. R134a , R1234yf or R1234ze) 
2-  Matlab + refprop version 10 works perfectly with pure substances but fails with mixtures 

The failure message is    
Error using refpropm (line 464)
[SHFLSH error 248] single-phase iteration did not converge, T, deltaT = 0.18222E+12 0.45896E-01 K.

I think because I use linking files that corresponding to version 9.1 
refpropm.m
REFPRP64.dll
refprop.h
REFPRP64_thunk_pcwin64.dll
rp_proto64.m 

Thanks

**Comment by Alhabeeb86** [comment]
I want to calculate pressure (P4) depending on HS, and unfortunately I don't have another option.
 
P4=refpropm('P','H',h4_is*1000,'S',s4_is*1000,fluid); % ejector outlet pressure (kPa)

**Comment by ianhbell** [comment]
First: refpropm is deprecated and no longer supported. You need to switch to the python interface which is more full-featured. Not related to this problem though.

You can workaround this problem by doing the iterative calculation yourself, iterating on pressure and quality to get the right enthalpy and entropy. That's the only thing I can recommend at this point.

**Comment by Alhabeeb86** [comment]
You mean to use Python instead of Matlab?

**Comment by ianhbell** [comment]
Yes, that is a good option, but more generally, to call Python _from_ MATLAB: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB

**Comment by ianhbell** [comment]
Yes, please see the page i linked.

**Comment by Alhabeeb86** [comment]
OK Thanks

Also, I would like to let you know that deleting REFPROP and install it again solves the problem.
