### ISSUE TITLE
usage of REFPROP 10 wrapper after reinstall windows system

### ISSUE THREAD

**Issue by LaphykyFang** [usnistgov/REFPROP-wrappers#526]
Hi there, 

I have purchased the REFPROP 10 and used the python wrappers in my win 10 home system. Since now I have to reinstall the system, I am wondering if the above operation will invalidate my purchase and affect my calls to REFPROP.

Thanks a lot in advance!

**Comment by ianhbell** [comment]
Nope, that is fine; the license is per-person.
