### ISSUE TITLE
Refprop 9.1 issue using Python and DLL

### ISSUE THREAD

**Issue by guazzin** [usnistgov/REFPROP-wrappers#527]
Dear Nist,
I am usign Refprop 9.1 in Python 3.9. 
I am trying to use two columns of a dataframe as input for the  `TPFLSHdll`  function, even using the form: T.values and P.values.
With Coolprop it works.

is there a way to use Refprop vectorized?
Thanks

**Comment by ianhbell** [comment]
No, the REFPROP interface does not support vectorization. If you want that, use the high-level interface of CoolProp to call REFPROP. But that comes with its own problems.
