### ISSUE TITLE
Example using REFPROPdll routine for PHASE

### ISSUE THREAD

**Issue by MathieuAssemat31** [usnistgov/REFPROP-wrappers#53]
## Problem description
Hello, 

I don't understand how to get PHASE and/or QMASS using REFPROPDDL routine for MATLAB.

Given information in RefProp Documentation on High-level API, 'PHASE' can be used as hOut. 

https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html?highlight=PHASE#f/_/REFPROPdll

## Example : 
``` matlab
import py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary ;
RP = REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP') ;

RP.REFPROPdll('R1233zde','PT','PHASE',int8(7),int8(0),int8(0),100,320,{1.0});

ans = 

  Python REFPROPdlloutput with properties:

    Output
    hUnits
    herr
    iUCode
    ierr
    q
    x
    x3
    y
    z

    REFPROPdlloutput(z=[1.0], Output=[-9999950.0,...])
```

### Versions

**REFPROP Version:** 10  
**Operating System and Version:** Windows10x64 

<img width="514" alt="refpropddl phase" src="https://user-images.githubusercontent.com/13236147/43711163-254f054a-9972-11e8-9d4d-ff5a55b3493c.PNG">

**Comment by ianhbell** [comment]
In this case, the output string is hiding in hUnits, as is described in the documentation (PHASE: Return the phase of the state for the input fluids and properties. See subroutine PHASE for a listing of all possibilities. The output is sent back in the hUnits variable)

In Python,
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary('D:\REFPROP') ;
RP.SETPATHdll('D:\REFPROP')
r = RP.REFPROPdll('R1233zd(E)','PT','PHASE',7,0,0,100,320,{1.0});
print(r.hUnits)
```
yields 
```
Superheated gas
```

A couple of admonishments:
* You should not hard-code the units system, as this is not guaranteed to be stable, and instead retrieve the value from ``GETENUMdll`` function, as described in the docs (See the section "Information on iUnits")
* You might want to use ``R1233zd(E)`` as the fluid name, it is technically more correct than R1233zde, and REFPROP does the correct file name remapping internally

**Comment by MathieuAssemat31** [comment]
Thank you for this quick and precise answer and for the other advices.

Could you also a provide a short example with the QMASS property ? 
As the output type depend of the state, I suppose it is stored in Output(1) if it's a double (ie the fluid is biphasic) ? I tried to print both hUnits and Output(1) with the same fluid properties but could not get answer.

Could you also provide the link to the PHASE subroutine documentation ? I could not find it neither online or in the .pdf doc. 

Many thanks in advance.

**Comment by ianhbell** [comment]
You are right, but in this case, Qmass is -9999990, indicating that the state is not two-phase.  That is the rule: 
0 < Q < 1 = two-phase
Q < 0 or Q > 1 = homogeneous state point
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary('D:\REFPROP') ;
RP.SETPATHdll('D:\REFPROP')
r = RP.REFPROPdll('R1233zd(E)','PT','PHASE',7,0,0,100,320,{1.0});
print(r.hUnits)
r = RP.REFPROPdll('R1233zd(E)','PT','QMASS',7,0,0,100,320,{1.0});
print(r.Output[0])
```
yields
```
Superheated gas
-9999990.0
```
