### ISSUE TITLE
Extracting quality factor in the saturation zone

### ISSUE THREAD

**Issue by ahmadgad1** [usnistgov/REFPROP-wrappers#530]
Hello there. Hope you are doing well.

I am using MATLAB to extract some thermodynamic data of water using REFPROP. When I try to use the mixture density and mixture internal energy information inside the saturation zone to get the quality factor, I get some errors on the boundaries of the saturation zone. I use the code simplified below,

```
n = 1000
for i = 1:n
    r = RP.REFPROPdll('Water', 'DE', 'QMASS', MOLSI, iMass, iFlag, rho(i), u(i), z);
    r = double(r.Output);
    x(i,1) = r(1);
end
```

where, `rho(i)` and `u(i)` are the inputs to the program. When the density and internal energy combination happens to appear on the saturation line, it should be 1 on the vapor boundary, and 0 on the liquid boundary. However I am getting sometimes -9999990 instead. For any point inside the saturation zone, I have no issues at all.

I know that this may be a precision related issue, but is there any way I can get the quality factor correct on the entire domain of the saturation zone?

Thanks, and best,
Ahmad Gad

**Comment by ianhbell** [comment]
Can you please make your minimal reproducible example runnable? That will help with debugging.
