### ISSUE TITLE
Problem Refprop dew point calculation in Python

### ISSUE THREAD

**Issue by ArezooHa** [usnistgov/REFPROP-wrappers#531]
### Description

I plot a P-T diagrams for natural gas samples with different compositions using Refprop (version 10) integrating Python code with Excel (https://nbviewer.org/github/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb#Phase-Boundary-for-Mixtures).
In the same Python code, I calculate the dew point temperature at maximum cylinder pressure using:
```python
tdewr = RP.REFPROPdll(" ", "PQ", "T", MOLAR_BASE_SI, 0, 0, p_Pa, 1, [MoleF1,MoleF2,MoleF3,MoleF4,MoleF5,MoleF6,MoleF7,MoleF8,MoleF9,MoleF10,MoleF11,MoleF12,MoleF13,MoleF14,MoleF15,MoleF16,MoleF17,MoleF18,MoleF19,MoleF20]).Output[0] 
```
For a specific gas mixture, the tdewr calculation returns an error as -999999. The P-t diagram calculations run correctly.

The composition is (all values are in mole%): Nitrogen 1.22, Carbon dioxide 1.004, Methane 94.96727, Ethane 2.002, Propane 0.1028, Isobutane 0.2031, N-butane 0.1994, Isopentane 0.1016, N-pentane 0.1005, Hexane 0.09933.

If the mole fraction of hexanes in the mixture is changed by 0.00001, the calculation of tdewr will return correct values.

### Steps to Reproduce

Here's the calculation line for the dew point. The pressure is 875 psi.
```python
tdewr = RP.REFPROPdll(" ", "PQ", "T", MOLAR_BASE_SI, 0, 0, p_Pa, 1, [MoleF1,MoleF2,MoleF3,MoleF4,MoleF5,MoleF6,MoleF7,MoleF8,MoleF9,MoleF10,MoleF11,MoleF12,MoleF13,MoleF14,MoleF15,MoleF16,MoleF17,MoleF18,MoleF19,MoleF20]).Output[0]
```
The composition is (all values are in mole%): Nitrogen 1.22, Carbon dioxide 1.004, Methane 94.96727, Ethane 2.002, Propane 0.1028, Isobutane 0.2031, N-butane 0.1994, Isopentane 0.1016, N-pentane 0.1005, Hexane 0.09933.

**Expected behavior:** I expect to be able to calculate the dew point of the above-mentioned mixture at a pressure of 875 psi using the syntax in Python.

**Actual behavior:** The calculation returns a value of -999999. Changing the composition (hexanes by 0.00001 mole%), the calculation runs without error.

### Versions

**REFPROP Version:** 10  
**Operating System and Version:** Windows 10  
**Access Method:** integrating Python code with Excel

**Comment by ianhbell** [comment]
Make sure you have turned on the saturation splines. In your calculation for the ispopleth, everything is fine, but your P-T calculations you have not turned on the splines. 

More generally, please provide runnable examples.

**Comment by ArezooHa** [comment]
Thank you!
