### ISSUE TITLE
Whether the compression factor can be invoked?

### ISSUE THREAD

**Issue by funzeng** [usnistgov/REFPROP-wrappers#535]
There is a function for CompressibilityFactor in excel, but how do you call the CompressibilityFactor in python?

**Comment by ianhbell** [comment]
See https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/ALLPROPSdll and https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll. The output parameter you want is `Z`

**Comment by funzeng** [comment]
Thank you!
