### ISSUE TITLE
codec issue with utf-8

### ISSUE THREAD

**Issue by bw2willi** [usnistgov/REFPROP-wrappers#539]
I had been using REFPROP in python (ctREFPROP.py) without issue.  Recently, I reinstalled my operating system (OPENSUSE LEAP 15.4) and now received an utf-8 codec error when using REFPROP.  In ctREFPROP.py, I replaced 'utf-8' with 'ISO-8859-1' and everything now works fine.

**Comment by bw2willi** [comment]
I spoke too soon on this.  For mixtures, the results are slightly different then expected.  I will compare the python results with those from the Fortran wrapper and continue to look for solutions to the code utf-8 error (image attached)

<img width="898" alt="refprop_error" src="https://github.com/usnistgov/REFPROP-wrappers/assets/138032317/9a839552-9403-4108-98a9-56f0ed81051e">

**Comment by ianhbell** [comment]
Do you know what error you are getting?  The error codes should never have unicode in them, so utf-8, or even ascii should be enough. This suggests a memory corruption on your side. What version of REFPROP do you use?

**Comment by bw2willi** [comment]
I just see 'UnicodeDecodeError' with REFPROP 10.0 (DDL verusion number 10.0.  I should have results from the fortran wrapper soon,

**Comment by ianhbell** [comment]
I mean can you get results to print with any encoding? That would be helpful to pin down the problem. Can you please give a non-working example so I can dig in?

**Comment by bw2willi** [comment]
I confirmed that the Fortran-wrapper and python-wrapper give the same results.  This is when using 'ISO-8859-1' in ctREFPROP.py, instead of 'utf-8'.  The issue with getting slightly different results then expected for mixtures is unrelated.

**Comment by ianhbell** [comment]
In ALLPROPSdll, do you actually get a ¿ in the output string with the corrected encoding? If so, that is a bug somewhere because REFPROP only uses ASCII so UTF-8 should be sufficient

**Comment by bw2willi** [comment]
I have attached the output of the python script (attached as .txt) showing the output from both REFPROPdll and ALLPROPSdll.  All output is shown, not just the string.  I am calling REFPROPdll in order to computes derivatives for two-phase states using a, currently simple, FDM method.  I see the warning in the documentation not to call ALLPROPSdll for two-phase states.

The python script was run using 'ISO-8859-1' in ctREFPROP.py.  The python script is in the attached .txt file, as I could not upload .py  (it is very similar to the one I sent you by email).  I do not see ¿ in the REFPROPdll output, but I do see it in the ALLPROPSdll output.

Not sure if this helps.

![image1](https://github.com/usnistgov/REFPROP-wrappers/assets/138032317/367103f4-97df-4f7f-94ea-70b0b6ad6d5e)

[python_code_R1.txt](https://github.com/usnistgov/REFPROP-wrappers/files/11969051/python_code_R1.txt)

**Comment by ianhbell** [comment]
Something is very wrong for you to get the unicode characters in the output. Do you get the same behavior in FORTRAN?

**Comment by bw2willi** [comment]
Attached is the output (hUnitsArray only) from a call to ALLPROPS in a script using the Fortran wrapper.   The Fortran variables in my script were the same as that defined in PASS_FTN.FOR.  If you need the Fortran script let me know; it is very similar to the python script, just in Fortran.  

![image2](https://github.com/usnistgov/REFPROP-wrappers/assets/138032317/eac51b85-e3f2-4c3b-a944-70db1d06178d)

**Comment by ianhbell** [comment]
I think I can run the python script, but I probably won't be able to get to it for at least a week. I'll try also with our internal development version.

**Comment by ianhbell** [comment]
This is a bug in REFPROP 10, resolved in our internal development version
