### ISSUE TITLE
REFPROPdll seems to not cache values

### ISSUE THREAD

**Issue by milesabarr** [usnistgov/REFPROP-wrappers#54]
I was looking into using this REFPROP wrapper (in Python) in place of CoolProp's call to REFPROP. Before I did this I was trying to compare the speed, and it seems that using this REFPROP wrapper is significantly slower than using CoolProp to call REFPROP. I am not sure if I am things differently between the two (I JUST started using this REFPROP wrapper). Here is one example I have:

Input using CoolProp:
```
import CoolProp
state_CP = CoolProp.AbstractState("REFPROP", "Water")
%timeit state_CP.update(CoolProp.PQ_INPUTS, 1e5, 0)
```

Output  using CoolProp:
```
2.24 µs ± 27.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

Input using this wrapper:
```
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
MOLAR_BASE_SI = RP.GETENUMdll(0, "MOLAR BASE SI").iEnum
%timeit RP.REFPROPdll("Water","PQ","T",MOLAR_BASE_SI,0,0,1e5,0,[1.0])
```

Output using this wrapper:
```
80.9 µs ± 3.78 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
### Versions
I am using the following:
- Python 3.6.5
- REFPROP version 10.0
- CoolProp version 6.0.0
- Windows 10

**Comment by ianhbell** [comment]
Thanks for this very nice report.  Have you looked into the use of SETFLUIDSdll prior to the call to REFPROPdll?  That does the fluid setup, which can indeed take a while.

**Comment by milesabarr** [comment]
I had not, but if I switch the code to this:
```
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
MOLAR_BASE_SI = RP.GETENUMdll(0, "MOLAR BASE SI").iEnum
RP.SETFLUIDSdll("Water")
%timeit RP.REFPROPdll("","PQ","T",MOLAR_BASE_SI,0,0,1e5,0,[1.0])
```
I still get this output:
84.5 µs ± 3.19 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

Am I setting up the fluid incorrectly, or using it incorrectly after it is already set up? On a side note is this all of the documentation available?: 
[Jupyter Tutorial](https://nbviewer.jupyter.org/github/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb) 
[REFPROP 10 Documentation](https://www.nist.gov/sites/default/files/documents/2018/05/23/refprop10a.pdf)?

**Comment by ianhbell** [comment]
One important point, that is not immediately obvious, is that CoolProp still uses the legacy API of REFPROP, which avoids a lot of the string processing, which kills the speed in the REFPROPdll function.  From a speed standpoint, for that reason the other functions in the high-level API, like http://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/ALLPROPSdll should be preferred because they avoid the string processing involved in REFPROPdll.  Can you try that?  I’ll happily add your experiments to my Jupyter notebook if you don’t mind.  It’s not the first time I’ve been asked about this, and I never did the nice test you did.

**Comment by milesabarr** [comment]
Seems to be even slower when I make this call:
```
%timeit RP.ALLPROPSdll("H", iUnits=-1, iMass=1, iFlag=0, T=370, D=961,z=[1])
```
253 µs ± 13.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

Also, maybe I am not understanding the proper inputs/outputs, or the units or something, but it seems to be giving an incorrect enthalpy of 1509143 kJ/kg.

**Comment by ianhbell** [comment]
You're right!  I've identified the problem - conversion of the ctypes arrays back to python lists.  Surprising.  Working on a solution as we speak.

**Comment by ianhbell** [comment]
Ok, pushed version 0.7, which fixes this problem.

**Comment by ianhbell** [comment]
See https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb (last section on Speed!)

**Comment by milesabarr** [comment]
Thanks for the update, and good you made it way faster. Any reason you think it is still 10X slower than the CoolProp call I have in my original post above?

**Comment by EricLemmon** [comment]
I've been looking through some old issues with the "bug" label on them, and have been reading this one.  Refprop does indeed cache values, but I don't think that is the issues here.  The routine ALLPROPS still has a lot of string handling in it; the better routine to call would be ALLPROPS0, which completely bypasses all string handling.  Even faster would be to go directly to the legacy functions such as TPRHO, TPFLSH, THERM, and so on.

**Comment by EricLemmon** [comment]
If this issue has been resolved, could you close it?

**Comment by ianhbell** [comment]
I guess the question then is whether this is just a question of call overhead, in which case we can close this issue.
