### ISSUE TITLE
unable to calculate enthalpy with TPFLSH

### ISSUE THREAD

**Issue by WoltaT** [usnistgov/REFPROP-wrappers#541]
Hello. I am working on a project with IPSEpro and need the properties of ammonia for that. 
I made a .dll to "connect" IPSEpro with REFPROP and after a lot of troubleshooting it finally works. 
I made a function to calculate the entahlpy of ammonia from pressure and temperature. 
EX_C2 was used a blueprint for the function. The SETUPdll gets call first and works perfectly. To calculate the enthalpy i used the TPFLSHdll (ammonia can be a liquied and vapor in my IPSEpro calculations). The TPFLSHdll works without an error but the enthalpy is incorrect or not calculated. The returend value is alsways "-nan(ind)". 
The strange thing is that all the other properties linke density, entropy and so on are correct. 
I tried to calculate the enthalpy afterwards with the THERMdll which gives me the same result "-nan(ind)".

My code:

[Dll.txt](https://github.com/usnistgov/REFPROP-wrappers/files/11952730/Dll.txt)

The results in IPSEpro for 40 bar and 10°C. 
36.832439 is the density in mol/L which is 627,29 kg/m³ (627,27 kg/m³ is the value when i use REFPROP directly).
-nan(ind) is the value of the enthalpy

![Output](https://github.com/usnistgov/REFPROP-wrappers/assets/138631569/5178e390-e067-4a18-9627-8336cb35007b)

**Comment by ianhbell** [comment]
Sounds like a complex memory problem. I recommend you use this header for REFPROP: https://github.com/coolprop/REFPROP-headers. And if you can use C++, to use CoolProp to call REFPROP; it has a clean interface around REFPROP

**Comment by ianhbell** [comment]
Also, test outside of IPSEpro, just a simple C example, before you enter the land of shared libraries.
