### ISSUE TITLE
REFPRP64.dll - Linux web app deployment issue

### ISSUE THREAD

**Issue by baraskarnitin10** [usnistgov/REFPROP-wrappers#544]
**Ian Bell,**
When I am putting REFPRP64.dll on an Azure web app Linux based.

System.DllNotFoundException: Unable to load shared library 'Data\REFPROP10\REFPRP64.dll' or one of its dependencies.

As a c# wrapper file  [DllImport(@"Data\REFPROP10\REFPRP64.dll", CharSet = CharSet.Ansi)] Dot Net Core application.

REFPRP64.dll can be platform independent? Bcos we want to use REFPRP64.dll as a reference.

**Comment by ianhbell** [comment]
The DLL is DEFINITELY not platform independent. You must recompile for any non-windows platforms. Recommend to use: https://github.com/usnistgov/REFPROP-cmake

**Comment by baraskarnitin10** [comment]
Sure, I will try. Thanks
