### ISSUE TITLE
convergence error using refprop.m close to saturation lines

### ISSUE THREAD

**Issue by jillblouse** [usnistgov/REFPROP-wrappers#546]
It has been a while since I use refprop.m from REFPROP 10 in my simulation model in MATLAB. But mostly for fluid such as refrigerants and so, if the condition is close to 2-phase area, in iterations it can happen that the guesses gets in the 2-phase region and I get the error message and the model cannot run further. Since it is an iteration, the program supposed to ignore the error and either go back one step or make another guess to complete the iteration. So the question is how I can go around this error or ignore it somehow?

**Comment by ianhbell** [comment]
1. The refpropm interface is deprecated, please migrate to the python interface for MATLAB
2. Please provide a runnable example demonstrating the problem, otherwise we have no idea where to start debugging

**Comment by jillblouse** [comment]
1. what do you mean using pyton interface? I call the refprop.m in my
matlab code. So you mean it is possible to call the functions from a python
file in matlab? Since I never had big issues with .m file so I could use it
easily, but this error made the life a bit hard.
2. It is a huge program that in every iteration calculates the properties
of the gas in a specific pressure and temperature. However it seems in some
points the quality value gets out of the range and it shows the error and
jumps out.Mainly for water and refriegerants.

**Comment by ianhbell** [comment]
1. Please see https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB . The refpropm interface is no longer supported, and has not been for a few years now.
2. Please provide a runnable example of your failures.
