### ISSUE TITLE
Convergence issue 

### ISSUE THREAD

**Issue by KesriNandan** [usnistgov/REFPROP-wrappers#548]
### Description
I am using MATLAb interface for REFPROP with mixtures. It is generating one error regularly.

[PHFLSH error 248] Single-phase iteration did not converge for P = 6.85002 MPa and H = 13499.6 J/mol.
Error in Cond4_Vapor (line 64)

'''T_WF_2phase(i)=refpropm('T','P',P_1,'H',h_2phase_v(i),comp1,comp2,fraction);'''

But if I check the REFPROP , in there it gives the value . What could be the reason? If anyone has any idea it would mean a lot. Thanks in advance

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

**REFPROP Version: 10.0 a** 
**Operating System and Version: Windows 11  
**Access Method:** [MATLAB]  
![image](https://github.com/usnistgov/REFPROP-wrappers/assets/143711869/2ed0259c-c8d6-4fde-9f5b-91b1496c5e5e)

**Comment by KesriNandan** [comment]
> refpropm is no longer supported. Please switch to the python interface, which will give you the ability to call SATSPLNdll which should help.

Thankyou for your swift response. As you have suggested I have started working with python interface. I will let you know if that works.

**Comment by KesriNandan** [comment]
Hi Ian, 
[diary.txt](https://github.com/usnistgov/REFPROP-wrappers/files/12544346/diary.txt)

I have some doubts related to python wrapper implementation. I am calculating enthalpy values of a mixture (CO2*R32) by keeping the inputs pressure and entropy. While running the code it changes the value slightly. and when running the function on command window, first it gives the wrong value but if you change something in the function then it gives the right value. 
iFlag =1 , iUnits =21, Mixture = (CO2*R32), s_2s = 1.3365e+03
r=RP.REFPROPdll( Mixture, 'PS', 'H', iUnits, iMass, iFlag,20000000,s_2s, fraction).Output(1)
I am attaching a diary of MATLAB where you will understand how it proceeds. 
Will be really grateful to you if this is solved.
Thanks in advance

**Comment by KesriNandan** [comment]
`%% ----- Definitions ------- %% 
%{

% HS:               HEAT SOURCE
% HS_fluid:         type of heat SOURCE fluid
% HS_Pr:            HEAT SOURCE Pressure (in kPa)
% HS_T_in:          HEAT SOURCE inlet Temperature (in K)
% HS_s_in:          HEAT SOURCE entropy at inlet (in kJ/kgK)
% HS_h_in:          HEAT SOURCE enthalpy at inlet (in kJ/kg)
% HS_h_out:         HEAT SOURCE enthalpy at OUTLET (in kJ/kg)
% MFR_HS:           Mass flow rate of HEAT SOURCE - AIR (in kg/s)

% SS:               HEAT SINK 
% SS_fluid:         type of HEAT SINK fluid 
% SS_Pr:            HEAT SINK Pressure (in kPa)
% SS_T_in:          HEAT SINK Inlet Temperature (in T)
% MFR_SS:           Mass flow rate of HEAT SINK - WATER (in kg/s)

% TC:               Critical Temp (in K)
% PC:               Critical Pr (in kPa)
% eta_Turb:         Isentropic efficiency of turbine (in %)
% eta_pump:         Isentropic efficiency of pump (in %)
% MFR_WF:           Mass flow rate of Working Fluid (in kg/s)
% T_Cond_exit:      Condenser exit temperature (in K)
% T_Turb_in:        Turbine inlet temperature (in K)
% T_PP:             Pinch point Temperature (delta)
% delT_HS_Turb_in:  difference between heat source inlet temperature and
                    Turbine inlet (T3) temperature
% eta_I:            Energy (I-law) efficiency (in %) 
% eta_II:           Exergy (II-law) efficiency (in %)

% T_0:              Dead state temperature (in K)
% P_0:              Dead state pressure (in kPa)

% P_1:              Pump inlet pressure (in kPa)
                    This pressure is obtained using T_cond_exit & x=0
% T1_sat:           Saturation temperature (in K)
% h_1:              Saturation liquid enthalpy (in kJ/kg)

% P2 = P3
% h_2s:             Isentropic enthalpy at pump outlet (in kJ/kg)
% h_2a:             Actual enthalpy at pump outlet (in kJ/kg)
% s_2s:             Isentropic entropy at pump outlet (in kJ/kg)
% s_2a:             Actual entropy at pump outlet (in kJ/kg)

% P3_guess:         Guessed value of pressure (P3) at turbine inlet
% h_3:              enthalpy @Turb.inlet
% s_3:              entropy @Turb.inlet

% h_4s:             Isentropic enthalpy at Turbine outlet (in kJ/kg)
% h_4a:             Actual enthalpy at Turbine outlet (in kJ/kg)
% s_4s:             Isentropic entropy at Turbine outlet (in kJ/kg)
% s_4a:             Actual entropy at Turbine outlet (in kJ/kg)

% phi:              Ratio of MRF-air & MFR-WF
 
%XD_pump            Exergy Destruction of pump
%XD_evap            Exergy Destruction of evaporator
%XD_turb            Exergy Destruction of turbine 
%XD_cond            Exergy Destruction of condenser
%XD_Total           Total Exergy Destruction

% ex1               Exergy at state 1
% ex2               Exergy at state 2
% ex3               Exergy at state 3
% ex4               Exergy at state 4
% HS_ex_in          Exergy at heat source inlet
% HS_ex_out         Exergy at heat source outlet
% SS_ex_in          Exergy at cold source inlet
% SS_ex_out         Exergy at cold source outlet

 HS_h_0            Enthalpy at dead state for heat source
 HS_s_0            Entropy at dead state for heat source
 SS_h_0            Enthalpy at dead state for cold source
 SS_s_0            Entropy at dead state for cold source

 HS_s_in            Entropy for heat source at inlet
 HS_h_in            Enthalpy for heat source at inlet
 h_0_WF             Enthalpy for working fluid at dead state
 s_0_WF             Entropy for working fluid at dead state

%}
%% --- Variables (STRUCTURE format) ----- %% 
%{
% hc=4; % includes pure HC's & halogenated /oxygenated HC's
% CO2_HC_H3(hc).T(not)=zeros; % Sat. vap. Enthalpy @ Tsat (Operating T)

%}

%% ------------- INPUT PARAMETERS------ %%

clear;  
close all

%addpath(genpath('C:\Program Files (x86)\REFPROP')); % FOR REFPROP

%To initialize REFPROP, you tell it what the root path of your REFPROP installation is:
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP') ; 
%to confirm that everything is working correctly, let's print out the version of REFPROP that you have loaded:
RP.RPVersion()

iUnits = RP.MASS_BASE_SI;  % K,Pa,KG/M^3,j/kg, m/s %RP.MOLAR_BASE_SI , RP.ENGLISH, RP.MOLAR_ENGLISH, RP.MKS,RP.CGS,RP.MIXED,RP.MEUNITS
iMass = int8(1); % 0: molar fractions; 1: mass fractions
iFlag = int8(1); % 0: don't call SATSPLN; 1: call SATSPLN




T_0 = 24+273.15; 
P_0 = 100000;  


HS_Pr=100000; 
HS_T_in=210+273.15; 
HS_fluid='air'; 


SS_Pr=100000; 
SS_T_in=24+273.15;  
SS_fluid='water';  

``
eta_Turb = 0.65; 
eta_pump = 0.85; 
MFR_WF =  1; 
T_Cond_exit = 30 + 273.15;  

HC={'CO2*R32';'CO2*R41';'CO2*R290';'CO2*DEE'; 'CO2*R152a';'CO2*propane'}; % WF mixture second component
Mixture= HC{1};
T_PP=5;     
delT_HS_Turb_in = 10;  
T_Turb_in= HS_T_in-delT_HS_Turb_in ;     



% ------- P3 guess: --------------%
    P3_guess_start=25;
    P3_guess_step=1;
    P3_guess_end=5;

q=1;
 X = 0.9
    A = X;      % for WF mixture first component (CO2)
    B = 1-A;    % for WF mixture second component (CO2)
    
    fraction={A B};
   % REFPROPdll(hFld, hIn, hOut, iUnits, iMass, iFlag, a, b, z, Output, hUnits, iUCode, x, y, x3, q, ierr, herr, hFld_length, hIn_length, hOut_length, hUnits_length, herr_length)
   
    % Critical Temperature: (K)
    r1 = RP.REFPROPdll( Mixture,'CRIT','P,T',iUnits,iMass,iFlag,0,0,fraction);  % to get the critical pr and Temp of the mixture
    PC= double(r1.Output(1));
    TC = double(r1.Output(2));
   
    % Working fluid thermodynamic properties: 
   
    r2= RP.REFPROPdll( Mixture, 'TQ', 'P,H,S', iUnits, iMass, iFlag, T_Cond_exit, 0, fraction);
    P_1= double(r2.Output(1));  % to get the condenser pr using condenser exit temp & quality 
    h_1= double(r2.Output(2)) % to get the h_1 (enthalpy) at pump inlet 
    s_1= double(r2.Output(3));
   
   % T1_sat(X,1)= refpropm('T','P',P_1,'Q',1,comp1,comp2,fraction); % IS THIS REQUIRED?
    
   
    
    j=1;
    for P=25:-1:5  % the lowest limit is kept as 5 as P_1 is 4.43 MPa at T_Cond_exit  = 30 oC    
       
        P3_guess = P*(10^6); % to convert into Pa        
       if P3_guess > PC  % remove if the second condition is not needed.
            P3_temp1(P,1)=P3_guess;
           
            s_2s=s_1 % isentropic condition
           
            r11=RP.REFPROPdll( Mixture, 'PS', 'H', iUnits, iMass, iFlag,P3_guess,s_1, fraction);
            h_2s= double(r11.Output(1))
            h_2a=h_1 + ((h_2s-h_1)/eta_pump); 
            
            r22=RP.REFPROPdll( Mixture, 'PH', 'S', iUnits, iMass, iFlag,P3_guess,h_2a, fraction);
            s_2a=double(r22.Output(1)); 
            
            % *** ACTION ***: Also get the pump outlet temperatures (isentropic & actual)
            
            %--- TURBINE INLET values:
             r33= RP.REFPROPdll( Mixture, 'TP', 'H,S', iUnits, iMass, iFlag,T_Turb_in, P3_guess, fraction);
            h_3=double(r33.Output(1)); % enthalpy @Turb.inlet using guessed T3, P3.
            s_3=double(r33.Output(2)); % entropy @Turb.inlet using guessed T3, P3.
           
            %--- TURBINE OUTLET OR CONDENSER INLET values:
            s_4s= s_3; % isentropic condition
            r44=RP.REFPROPdll( Mixture, 'PS', 'H', iUnits, iMass, iFlag,P_1,s_4s, fraction);
            h_4s= double(r44.Output(1)); 
           
            % ***** above calculation assumes there is no temp. glide. ***
            
            % *** ACTION ***: Need to find how to get the pressure at
            % turbine exit by considering the mixture temperature glide.
            
            h_4a=h_3-eta_Turb*(h_3-h_4s); % actual enthalpy at turb. outlet
            % for P1 get saturation vapor enthalpy at that pressure P1,
            % compare the enthalpies for quality check
            r55=RP.REFPROPdll( Mixture, 'PH', 'S,T', iUnits, iMass, iFlag,P_1,h_4a, fraction);
            x_4= double(r55.q); % to get the turb. exit quality 
            s_4a=double(r55.Output(1)); % actual entropy at turb. outlet
            T_4a=double(r55.Output(2));
           
            r66=RP.REFPROPdll( Mixture, 'PQ', 'S,H', iUnits, iMass, iFlag,P_1,1, fraction);
            s_5=double(r66.Output(1)); % saturation vapor entropy at P_1 -required for heat transfer analysis
            h_5= double(r66.Output(2));
            
            x4_temp1(P,1)=x_4;             
            
            if x_4>0.9                
                               
               [UA_Ev_avg]= Py_Evap1(RP,h_3,h_2a,P3_guess,Mixture,iUnits,iMass,iFlag,fraction,HS_T_in,s_3,s_2a,T_PP,HS_Pr);
                 j=j+1;
                
            end 
            end
    end   
q=q+1


`   @ianhbell This is is the code I am working on.

**Comment by ianhbell** [comment]
Please reduce your example to the minimal set of code demonstrating the problem. There is too much to sort through.

**Comment by KesriNandan** [comment]
> Please reduce your example to the minimal set of code demonstrating the problem. There is too much to sort through.

I have reduced the code and the function file for this program. I also sent you the mail from bhawandeepsharma@gtiit.edu.cn which includes the function file .

**Comment by ianhbell** [comment]
What is needed is an even simpler example that doesn't call to your own ``RP_Py_Evap1``. One thing I note from your example is that you jump from mixture to air and back (makes sense because you have a HX), but that could cause problems. I recommend to use CoolProp for the air as a pseudo-pure fluid, and do all the refrigerant properties with REFPROP, so that you never need to re-initialize the mixture. Also makes sure you are using the saturation splines.

**Comment by KesriNandan** [comment]
I am trying to reduce it as suggested but combining the function makes it even bigger so I am working on it. Can i use Refpropm function instead of Coolprop? 
Also, I am using iFlag=1 and in the documentation it says it means satspline is On. is it correct? or is there nay other way to use the saturation spline.

**Comment by ianhbell** [comment]
No, refpropm is deprecated and no longer supported. 

Yes, that is how to turn on saturation splines.
