### ISSUE TITLE
Defining a mixture using REFPROP with Labview 

### ISSUE THREAD

**Issue by GaryAtAtmosZero** [usnistgov/REFPROP-wrappers#549]
I am trying to implement a REFPROP call that is working in Excel into Labview. This is the call from Excel:
REFPROP.XLA'!REFPROP("H","Ethylene glycol;water|.5;.5 mass","TP","C",40,0.3)
The result in Excel is -121.734 kj/kg

I am using the provided example REFPROPdll_Test.vi to verify the Labview results but not getting the same result. I am not very familiar with Labview or calculating enthalpy and wondering if I am attempting to make the call correctly?:

<img width="594" alt="MixtureCall" src="https://github.com/usnistgov/REFPROP-wrappers/assets/129773519/e90a4f9c-7bf9-4ce5-9b3e-b6006dec83bb">

Results:
<img width="429" alt="image" src="https://github.com/usnistgov/REFPROP-wrappers/assets/129773519/1f4b969c-37a4-4a9a-af8c-368bd4d16be2">

The result in Labview appears to be -292.612 kj/kg. Is the call being made in Excel the same as the call being made in Labview? Should I expect the same result with the VI and inputs I am using?

**Comment by ianhbell** [comment]
You are running into the typical problem of reference states. They are handled differently in the Excel and GUI by default, so to be sure everything is ok, you should always check _differences_ between two states at different temperatures and pressures and the same composition as those should be the same.

**Comment by GaryAtAtmosZero** [comment]
Thanks Ian. I am not sure if I am on the right path though, am I using the correct call in Labview, is it the same as the Excel call? Do the arguments in Labview correspond to the arguments in the Excel call?
