### ISSUE TITLE
some problems with ctREFPROP in windows11

### ISSUE THREAD

**Issue by NCEPULX** [usnistgov/REFPROP-wrappers#553]
Hi everyone,
   I am a new learner, both python and  REFPROP. I have searched for many answers in these days, but I still don't know how to.
   According to the online tutorial, I installed ctREFPROP via the PIP command, and I ran the instance of the wrapper in the WINDOWS 11 shell window, but there was an error. 
![image](https://github.com/usnistgov/REFPROP-wrappers/assets/145902227/4c975032-40da-42ec-b70e-ba37f3646b0a)

I looked up the source code in ctREFPROP.py and found that none of these functions or properties('SETPATHdll')were defined in the  class--REFPROPFunctionLibrary. I also know there is an hign APL, but the version number of ctREFPROP I installed is 0.10.2. And I also have REFPRP64.DLL files.So, I should do it. I sincerely beg someone to give me some advice or tutorials, thanks again!

**Comment by ianhbell** [comment]
What version of REFPROP do you have? It seems like you have not purchased and installed REFPROP properly. You can buy REFPROP from: https://www.nist.gov/srd/refprop

**Comment by NCEPULX** [comment]
Yes, you are right. I checked the online tutorials again, I found my computer does not have the REFPROP program installed. so I downloaded the REFPROP program and Passed the software test，the result is good. Thank you for your answer and advice sincerely.
