### ISSUE TITLE
Refprop.dll problem with calling mixtures multiple times

### ISSUE THREAD

**Issue by GaryAtAtmosZero** [usnistgov/REFPROP-wrappers#556]
I am using Labview to make multiple calls to refprop.dll in a loop and it is working fine when using a fluid such as water but when I try to call refprop using a mixture multiple times, such as R513A.mix, I get the following error:

[REFPROP error 813] The input composition must match that of the predefined mixture when the mixture name is included in the call to REFPROP.  To use a different composition, leave the fluid name blank.                                                    

This is an example of the multiple calls using the same mixture as the hFld:
![image](https://github.com/usnistgov/REFPROP-wrappers/assets/129773519/6299b705-fab2-4cc7-b94e-819f885cb66d)

This is the output and error message generated by the Get Refprop sub vi:
![image](https://github.com/usnistgov/REFPROP-wrappers/assets/129773519/66a2527b-fc2c-46b4-b17d-343451a2b43f)

If I make multiple calls in the loop to different mixtures, R513A.mix and R513B.mix it works fine.:
![image](https://github.com/usnistgov/REFPROP-wrappers/assets/129773519/a5a73abd-113e-453f-910c-5616bdb408c4)

**Comment by ianhbell** [comment]
Yes, this is arguably a bug, but several different ones interleaved. On the first call, pass the name, on subsequent ones, don't pass the name.
