### ISSUE TITLE
Error messages when trying to generate REFPROP tables from MATLAB

### ISSUE THREAD

**Issue by yahavmorag** [usnistgov/REFPROP-wrappers#559]
### Description

I get Error messages when trying to generate REFPROP tables from MATLAB.

### Steps to Reproduce

1. Purchased REFPROP.
2. Installed REFPROP DLL version number 10.0 in C:\Program Files (x86)\REFPROP
3. Placed the files: refpropm.m, refpropm.m and REFPROP.h in  the REFPROP installation directory
4. Verified that the REFPROP exists in the REFPROP installation directory
5. in MATLAB R2023,  in the working directory put the files: rp_proto.m, rp_proto64.m 
6. called refprop from an m file (attached)

**Expected behavior:** Tables will be generated  in the workspace
**Actual behavior:** 

Received error message: 
Error using loadlibrary
The specified module could not be found. 

Error in refpropm (line 221)
[notfound,warnings]=loadlibrary(strcat(BasePath,dllName),prototype,'alias',libName);

[GenerateREFPROPTables.docx](https://github.com/usnistgov/REFPROP-wrappers/files/13033297/GenerateREFPROPTables.docx)
[GenerateREFPROPTables.pdf](https://github.com/usnistgov/REFPROP-wrappers/files/13033314/GenerateREFPROPTables.pdf)
### Versions

**REFPROP Version DLL version 10.0  
**Operating System and Version: Windows 10 Enterprise, 64-bit operating system, x64-based processor
**Access Method: From MATLAB 2023

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
The refpropm interface is no longer supported, for reasons like you are running into. Please migrate to the Python interface.

**Comment by yahavmorag** [comment]
Thank you!
