### ISSUE TITLE
RP.REFPROPdll() tutorial python wrapper wrong output

### ISSUE THREAD

**Issue by mddewit** [usnistgov/REFPROP-wrappers#56]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

**REFPROP Version:** [REFPROP version you are using]  
**Operating System and Version:** [OS you are running REFPROP on]  
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by mddewit** [comment]
When trying to reproduce the first part of the python wrapper of REFPROP tutorial multiple issues occur. The tutorial can be found here: https://nbviewer.jupyter.org/github/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb

I copied In[2] up until In[5] and removed ; os.environ['RPPREFIX'] = r'D:\REFPROP\\' from In[2] as REFPROP is located in the default folder.

The resulted in the following error from REFPROPFunctionLibrary:
ValueError: Too many loadable shared libraries were found in the folder "C:\Program Files\REFPROP"; obtained libraries were: ['C:\\Program Files\\REFPROP\\MSSTDFMT.DLL', 'C:\\Program Files\\REFPROP\\MSVBVM60.DLL', 'C:\\Program Files\\REFPROP\\REFPROP.DLL'].  You must provide an absolute path to the shared library you would like to load.

As instructed I supplied the absolute path ('C:\\Program Files\\REFPROP\\REFPROP.DLL') to REFPROPFunctionLibrary. As a result the program ran without errors, but now supplied me with a wrong number for the boiling temperature of water at 101325 Pa (20K instead of 373K).

This is my code as of now:

```
import os

from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
import glob
import pandas

RP = REFPROPFunctionLibrary('C:\\Program Files\\REFPROP\\REFPROP.DLL')

RP.SETPATHdll(os.environ['RPPREFIX'])

MOLAR_BASE_SI = RP.GETENUMdll(0, "MOLAR BASE SI").iEnum

p_Pa = 101325
Q = 0.0
r = RP.REFPROPdll('Water',"PQ","T",MOLAR_BASE_SI,0,0,p_Pa,Q,[1.0])
print r.Output[0]
```

The output should be 373.1242958476953, but instead I get:
`20.0`

I am using REFPROP 10 on a 32-bit operating system using Python.

**Comment by ianhbell** [comment]
Indeed, this is odd behavior that I cannot replicate on my side in 32-bit python.  I tried the following:
``` python
import os
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary('D:\\REFPROP\\REFPROP.DLL')
RP.SETPATHdll('D:\\REFPROP')
MOLAR_BASE_SI = RP.GETENUMdll(0, "MOLAR BASE SI").iEnum
p_Pa = 101325
Q = 0.0
r = RP.REFPROPdll('Water',"PQ","T",MOLAR_BASE_SI,0,0,p_Pa,Q,[1.0])
print(r.Output[0])
```
I wonder if it is maybe your call to ``SETPATHdll``?  I modified my call to pass the absolute path rather than relying on the setting of the environment variable ``RPPREFIX``

What version of Python do you use? 2.7 I guess based on your use of the print statement rather than the print function?  Also, have you upgraded to the newest version of ctREFPROP wrapper?

**Comment by mddewit** [comment]
Thank you for your response.

I use Python 2.7.14 and I installed the wrapper using pip the same day I posted this, so I assume it to be the latest version. The environment variable `RPPREFIX` seems to point to the correct folder and when I call the absolute path I still get the same incorrect result. I also tried it without `SETPATHdll` and got the exact same.

Since I could not get it to work properly, I tried using CoolProp as a wrapper and calling the fluids using e.g. `REFPROP::Water`. This seems to work without fault.

**Comment by ianhbell** [comment]
Hmm.  So weird.  I use python 2.7 sometimes too though I have migrated completely to python 3.6 for my day-to-day.  Let me see if I can try with python 2.7  In the interim, CoolProp is a good option.

**Comment by ianhbell** [comment]
Can we close this issue now?

**Comment by maaikedieuwertje** [comment]
Yes
