### ISSUE TITLE
Using Gas Properties (G) Simulink block

### ISSUE THREAD

**Issue by yahavmorag** [usnistgov/REFPROP-wrappers#560]
**REFPROP Version:** 10
Hello,
I am using the "Gas properties (G)" block in Matlab/Simulink
link to Simulink's block help:
https://www.mathworks.com/help/simscape/ref/gaspropertiesg.html?searchHighlight=Gas%20Properties&s_tid=srchtitle_support_results_1_Gas%20Properties

I want to use the "real" gas properties, using tables generated by REFPROP.

My question:
What is the corresponding REFPROP parameters to these two:
1. Isothermal bulk modulus table, designated in the Simulink's block help as:  β=ρ(∂p∂ρ)@T
2.  Isobaric thermal expansion coefficient table, designated in the Simulink's block help as:  α=−1ρ(∂ρ∂T)@p

Thank you

Yahav

**Comment by ianhbell** [comment]
Please see: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/ALLPROPSdll

**Comment by yahavmorag** [comment]
Hello Ian,
I apologize, but I couldn't find the answer
Is the following match correct?
1.   REFPROP parameter, KKT,  | , [Pa] :    Is it  the  Isothermal bulk modulus table, designated in the Simulink's block help as: β=ρ(∂p∂ρ)@t
2. REFPROP parameter,B [1/K]: is it the Isobaric thermal expansion coefficient table, designated in the Simulink's block help as: α=−1ρ(∂ρ∂T)@p
3.
Thank you very much

**Comment by ianhbell** [comment]
Please see this as one example of how we define these terms: [[PDF] @ nist.gov](https://srd.nist.gov/jpcrdreprint/1.1285884.pdf)

**Comment by yahavmorag** [comment]
Thank you!
