### ISSUE TITLE
ABFLSHdll in python

### ISSUE THREAD

**Issue by coderlover-lang** [usnistgov/REFPROP-wrappers#561]
I'm having some problems calling ABFLSHdll using Python, hope you can help

### Description

You can see that I have proportioned a mixture whose components are butane and ethylene respectively. The ratio is 0.6230: 0.3770. I hope to calculate their Liquid density of equilibrium at Q = 0.0895 and the air pressure at P = 113.1 (kPa). phase and Vapor density of equilibrium phase, in the refprop software, I got the results I hoped for, as shown below:

![b0b7c4fa0f86d539f3cbc2b50887860](https://github.com/usnistgov/REFPROP-wrappers/assets/79103096/22c554a3-34b2-4bc9-a01a-a307f86080ae)

I got Liquid density of equilibrium phase = 646.4373, which is reasonable

But when I try to call in Python using

```python
import os
os.environ['RPPREFIX'] = r'C:/Program Files/REFPROP v10'
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

import glob

import pandas

import numpy as np
RP_single = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP_single.SETPATHdll(os.environ['RPPREFIX'])
RP_mix = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP_mix.SETPATHdll(os.environ['RPPREFIX'])

P7, T7 = (113.1, 184.15)
Ref1='butane'     
Ref2='ethylene'   
P8 = P7 
Z_1 = 0.6230 
Z_2 = 1 - Z_1 
Z = [Z_1, Z_2]
xe = 0.0895
RP_mix.ABFLSHdll("PQ", P8, xe, Z, 1) 
```

I received Dl=13.493390361545368, Dv=0.0715316355030999, maybe I should change the last parameter iFlag, but I have traveled all the paremeter as possible , I didm't receive the same output as in refprop;
### Steps to Reproduce

**Actual behavior:** [What actually happens]

### Versions

**REFPROP Version:** [v10.0.0.0]  
**Operating System and Version:** [windows 10]  
**Access Method:** [How you are accessing REFPROP ( Python)]

**Comment by ianhbell** [comment]
Some notes: the way DLL work on windows, ``RP_mix`` and ``RP_single`` point to the same object.  

For mixtures, you should specify Qmass or Qmolar for the vapor quality explictly, so in your case, your inputs should be ``PQMASS``. See also: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html
