### ISSUE TITLE
Error using refpropm [TPFL2 error 226] 2-phase iteration did not converge.

### ISSUE THREAD

**Issue by csbhoir1510** [usnistgov/REFPROP-wrappers#563]
I using REFPROP in MATLAB.
I am trying to find out mixture properties for mixture made up of following components. The AA represents mass fraction of each specie.

It is showing following error:
Error using refpropm
[TPFL2 error 226] 2-phase iteration did not converge.

Error in untitled12 (line 306)
VallW(i)=refpropm('V','T',Twi(i),'P',0.001*P(i),'decane','ethane','cyclohex','benzene','toluene','octane','ebenzene',[AA1(i) AA2(i) AA3(i) AA4(i) AA5(i) AA6(i) AA7(i)]);

**Comment by ianhbell** [comment]
refpropm is deprecated and no longer supported. Please migrate to the Python interface for MATLAB.

**Comment by csbhoir1510** [comment]
Can you provide the sample command for following properties
1) specific heat of decane at 300 K and 2 bar.
2) Viscosity of mixture of decane and ethane at 600 K and 5 bar with mass fraction of 0.6, 0.4 respectively.

Thank you

**Comment by ianhbell** [comment]
Please see the documentation: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB

Documentation for the high-level functions are here: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html
