### ISSUE TITLE
Matlab crashes while calling refprop(9.0/10.0) in a loop

### ISSUE THREAD

**Issue by Qattussen** [usnistgov/REFPROP-wrappers#564]
matlab crashes and is closed immediately. The crash occurs randomly when refprop is called in a loop, i.e. Matlab crashes randomly each time at a different iteration step. It seems that refprop loses the path after a while. Sometimes just before the crash, you can see that the path with the .FLD files is no longer found, although it was reached several times in the previous iteration steps. (not always the case).
I have run the script with the refprop calls on other machines, always the same problem. I have also tried it with refprop 9 and refprop 10.
My current refprop version is 10.0

**Comment by ianhbell** [comment]
Can you please put together a minimal working example demonstrating the problem? Otherwise I have no idea how to help you.

**Comment by ianhbell** [comment]
Given the fact that insufficient information has been provided to reproduce the bug, the issue is being closed
