### ISSUE TITLE
Issues with convergence for 2-phase binary mixture (ammonia/water) on MATLAB

### ISSUE THREAD

**Issue by Andrea-Cornelio** [usnistgov/REFPROP-wrappers#566]
Dear developers, 

I am writing a MATLAB code to solve a power cycle that uses a mixture of ammonia and water with high titles of ammonia (0.95<=x<=0.99) as working fluid.

I am using REFPROP 10 to calculate the mixture properties along the cycle. I have noticed, though, that in some points of the cycle, where the mixture is in 2-phase conditions, REFPROP does not converge. In output I get the message: "[PQFL2 error 226] 2-phase iteration did not converge.".
This is sometimes an issue in solving specific points of the cycle, and I am wondering wheter there is a way to solve this problem. I have activated SATSPLN, but it does not seem to always be enough to avoid the occurrence of these errors. 

I attach a simplified code that simulates the behavior of the solver during evaporation at fixed pressure: 

__
```matlab
%Refprop init & settings:
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('REFPROP PATH');
hFld = 'AMMONIA * WATER';
iUnits = int8(2); %mass ref, T in K
iMass = int8(1); %mass fractions
iFlag = int8(1); %SATSPLN on

%set resolution:
res = 100;

%set fixed T and composition:
t_in = 300; %K
x = 0.99;
c = [x, 1-x];
q_in = 0; %-
p = double(RP.REFPROPdll(hFld, 'tq', 'p', iUnits, iMass, iFlag, t_in, q_in, c).Output(1)); %MPa
q_out = 1; %-

%for a fixed t_in and pressure, calculate the temperature along the
%evaporation line of the mixture:
dq = (q_out-q_in)/res;
q = [q_in:dq:q_out];
dim = size(q);
errors = string(zeros(dim(2),1));

for ii = 1:1:dim(1,2)
    t(ii) = double(RP.REFPROPdll(hFld, 'pq', 't', iUnits, iMass, iFlag, p, q(ii), c).Output(1)); %K
    errors(ii) = (RP.REFPROPdll(hFld, 'pq', 't', iUnits, iMass, iFlag, p, q(ii), c).herr);
end

%double output is equal to -9999990.00 in case of non-convergence of
%REFPROP
%plot(q,t)
errors
count_errors = int8(nnz(errors ~= ""))
```
__

In my case I get in output 14 errors in the case of x = 0.99. The number is different (as far as I have seen, decreases) for different (lower) titles of ammonia. Let me know whether I am doing something wrong and if there is a fix to this issue. Thank you!
Kind regards

Versions:
REFPROP Version: 10
Operating System and Version: Windows 10
Access Method: Python 3.11

**Comment by ianhbell** [comment]
Some comments:

* Never hard code the units, _ALWAYS_ call ``GETENUMdll`` to obtain it. We might change the codes.
* It is sort of an unofficial standard that ``T`` indicates absolute temperature and ``t`` indicates a temperature in Fahrenheit or Celsius
* Do you want the vapor quality on a mass basis or a molar basis? You should specify that explicitly with "qmass" or "qmole"

I confirm the bugs. I translated your code to Python:
```python
import ctREFPROP.ctREFPROP as ct, os
import numpy as np 

root = os.getenv('HOME') + '/REFPROP10'
RP = ct.REFPROPFunctionLibrary(root);
RP.SETPATHdll(root)

hFld = 'AMMONIA * WATER'
iUnits = 2 #mass ref, T in K
iMass = 1 #mass fractions
iFlag = 1 #SATSPLN on

# set fixed T and composition
t_in = 300 # K
x = 0.99
c = [x, 1-x]

q_in = 0
p = RP.REFPROPdll(hFld, 'tqmass', 'p', iUnits, iMass, iFlag, t_in, q_in, c).Output[0]; # MPa
t, errors = [], []
for q in np.linspace(0., 1., 100):
    t.append(RP.REFPROPdll(hFld, 'pqmass', 't', iUnits, iMass, iFlag, p, q, c).Output[0]); # K
    errors.append((RP.REFPROPdll(hFld, 'pqmass', 't', iUnits, iMass, iFlag, p, q, c).herr))

print(len([e for e in errors if e]))
```

**Comment by ianhbell** [comment]
and I got 13 failures

**Comment by Andrea-Cornelio** [comment]
Ok, thank you for the advice about GENENUMdll! Yes I am considering q as mass fraction, so qmass is the correct indicator to use. Regarding the solver error, will it be possible to fix the bug? Do you know what the reason for this error might be?

**Comment by ianhbell** [comment]
Unfortunately no, I don't have great options to recommend for this problem. You could try to use the SATGVdll function which allows you to provide guess values, but that is intended for saturation (Q=0 or Q=1) only.

**Comment by Andrea-Cornelio** [comment]
Ok, I understand. Thank you anyways for giving it a look.
