### ISSUE TITLE
Adding new Low GWP refrigerant mixtures into Refprop old version

### ISSUE THREAD

**Issue by Bakgul77** [usnistgov/REFPROP-wrappers#567]
We had a psychometric test facility controlled with a customized labview program in which we are using a Refprop dll, but I don't have the version information. The low gwp refrigerant mixtures are missing, so we want to add these new mixtures. 

I got the HMX.BNC file and new mixtures folder about adding new mixtures into Refprop. When I copy the HMX.BNC into fluids folder and new mixtures into mixtures folder , it is possible to select the new mixtures such as R454B, but the calculation results are all negative. I checked for R410A, the results are negative again. The files inside refprop folder are shown below, there is refprop.dll file, is it possible to know the version from dll file ? Also when I checked the fluids file, there is svn-base file for HMX.BNC, is this file also need to be updated ? When I checked our existing HMX.BNC file, its last update is from 04-04-07. Could you please advise ?

![IMG-20231124-WA0004](https://github.com/usnistgov/REFPROP-wrappers/assets/151918211/076a44ef-5c75-4e74-a074-a5e89a3737f5)
![IMG-20231124-WA0006](https://github.com/usnistgov/REFPROP-wrappers/assets/151918211/cd1fab68-2c47-490d-b284-7f2c5e6a2433)

![HMXBNC](https://github.com/usnistgov/REFPROP-wrappers/assets/151918211/a0e2cd13-4fc9-42a1-a38e-c436dd453de7)

**Comment by ianhbell** [comment]
The svn-base is not from us, must be version management on your side

**Comment by ianhbell** [comment]
Recommend to upgrade to version 10.0, that includes updated models for mixtures. I have also developed new models not yet included in the HMX.BNC

**Comment by Bakgul77** [comment]
> The svn-base is not from us, must be version management on your side

Thanks alot for your quick feedback. We don't have the source code, we got it as a turnkey solution together with the psychrometric test facility

**Comment by Bakgul77** [comment]
> Recommend to upgrade to version 10.0, that includes updated models for mixtures. I have also developed new models not yet included in the HMX.BNC

As we don't have the source code, it is not possible to upgrade. In fact, we need to add just R454B, we don't need others. Is it possible to add only this mixture by editing an existing mixture ?

**Comment by ianhbell** [comment]
Then I recommend to reach out to your vendor.

**Comment by ianhbell** [comment]
You can also specify the composition directly to REFPROP, the predefined mixture files are only a convenience.

**Comment by Bakgul77** [comment]
> Then I recommend to reach out to your vendor.

The labview software is from 2007 and the vendor informed me that they cannot help about this issue because of not having resources. I just need to add only 1 refrigerant mixture which is R454B. I don't know how the refprop is working, but R454B mixture consists of R32.fld and R1234yf.fld 
When I checked the fluids directory, I saw that R1234yf.fld file is missing. Could you please advise where I can find the R1234yf.fld file ? Could you please also advise how the refrrop dll is using HMX.BNC file ?
Your help will be very appreciated

**Comment by Bakgul77** [comment]
Thanks alot for your quick reply. As I tried to explain that I cannot get a support and I need to solve by myself. Could you please advise how I can find the refprop version and then also how I can upgrade refprop ?

**Comment by ianhbell** [comment]
You can buy Refprop 10 from https://www.nist.gov/srd/refprop and the updated Labview wrapper is available here: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Labview

**Comment by Bakgul77** [comment]
Ok, thannks alot. As I don't have the source  code, will it be Ok, just replace data folder with Refprop files.
