### ISSUE TITLE
Refprop predefined mixture results are different wiht 'MATLAB refpropm'

### ISSUE THREAD

**Issue by Dohyun8599** [usnistgov/REFPROP-wrappers#568]
The results of the refprop predefined mixture loaded from MATLAB are different. In particular, there is a big difference when calculating QUALITY. I am currently using Refprop 10.0v, and errors occur in the values of all predefined mixtures.
how can i solve this? 
please help me
![matlab_refpropm](https://github.com/usnistgov/REFPROP-wrappers/assets/126850120/d6b742d2-6cb8-4702-9efd-0a812fc13432)
![refprop r513a screenshot](https://github.com/usnistgov/REFPROP-wrappers/assets/126850120/edff6d9c-e8f6-44a0-a219-a88c44a50327)

 Calculating quality also incorrect. It means big deviation.
how can I correct it
)The results from pure fluid single and MATLAB results are very consistent.)

**Comment by Dohyun8599** [comment]
The density value came out the same(MATLAB-refprop), but when the values for quality were correlated, the error in the entropy value was large.

here's the my reference state and preference
![reference state](https://github.com/usnistgov/REFPROP-wrappers/assets/126850120/f77c0cb2-6727-4657-a555-ab67ea5cc496)
![preference](https://github.com/usnistgov/REFPROP-wrappers/assets/126850120/46419d06-3eb1-41c0-8ff5-846bf3cd98ae)

**Comment by ianhbell** [comment]
Best would be to set the DLL and GUI to use the same reference state, perhaps IIR in your case

**Comment by Dohyun8599** [comment]
sorry but what is the GUI means...? I'm the beginner sorry sir

**Comment by ianhbell** [comment]
GUI: graphical user interface.

In this case, the executable you pulled the tables from

**Comment by Dohyun8599** [comment]
Thank you for your kind explanation.
Since the REFPROP table is the standard, it seems that the REFPROP table should not be modified. When importing from MATLAB, the numbers seem to be transformed, but I don't know what to do.
