### ISSUE TITLE
High Level API Functions in Matlab

### ISSUE THREAD

**Issue by gruenstern** [usnistgov/REFPROP-wrappers#57]
Is there an available way to access properties only obtainable with the high level API (like Cvliq/Cpliq) through Matlab? The wrapper seems to only support legacy API.

**Comment by ianhbell** [comment]
Yup, you can use the Python interface, it exposes the complete high-level interface.

**Comment by gruenstern** [comment]
Here's what I ended up doing: 

In a python script wrap.py I have:

def get_prop(out,fluid,T,P,molefrac):
  import ctREFPROP as CT
  RP1 = CT.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP\REFPRP64.dll', "dll")
  prop = RP1.REFPROPdll(fluid,'TP',out,2,0,0,T,P,molefrac)
  calc = prop.Output[0]
  return calc

Then in Matlab I made another function that can then be called for a certain property:

function [out] = pywrap(prop,fluid1,fluid2,fluid3,T,P,fluid_mole_frac)
fluid = strcat(fluid1,';',fluid2,';',fluid3,';');
P = P/1000; %From kPa to MPa
[dum dum load] = pyversion;
if load
elseif ~load
    pyversion C:\Users\gruenstern\AppData\Local\Continuum\anaconda3\python.exe
end
wrap = py.importlib.import_module('wrap');
out1 = wrap.get_prop('Cpvap',fluid,T,P,fluid_mole_frac);
out = 1000*out1; % KJ/g-K to J/g-K
end

This seems to work for the properties I am needing.

**Comment by ianhbell** [comment]
I updated your last post with nicer code blocks, check out the edited version.

Thanks for this snippet, it will be useful for other people that come this way!
