### ISSUE TITLE
the name of the equation used to calculate the viscosity, thermal conductivity, and surface tension of natural gas

### ISSUE THREAD

**Issue by Wei112345** [usnistgov/REFPROP-wrappers#572]
I am writing to inquire about the status of the name of the equation used to calculate the viscosity, thermal conductivity, and surface tension of natural gas. In my current work, due to the lack of experimental data, I have used Refprop data as experimental data. When comparing data, it is necessary to involve the names of the equations, but I cannot find the relevant equation names for these three physical properties in the software.

**Comment by nist-aharvey** [comment]
@ianhbell has already described how to get information about the models for the pure components, but your question is about a mixture so more is probably needed.
The models used for mixture calculations for viscosity, thermal conductivity, and surface tension are described in this 2022 article:
https://doi.org/10.1021/acs.iecr.2c01427
Some additional discussion of the surface tension is in this 2023 article:
https://doi.org/10.1007/s10765-023-03216-z

I do not think any of these models have special names, but if you need to describe them in your work the mixture surface tension is a parachor-based model and the mixture viscosity and thermal conductivity both use extended corresponding-states models. These descriptions apply to the mixture model -- the pure-component correlations that go into the mixture model are different models depending on the fluid.
