### ISSUE TITLE
ValueError: The function GETENUMdll could not be loaded from the shared library [Python]

### ISSUE THREAD

**Issue by augustindmbl** [usnistgov/REFPROP-wrappers#578]
Hey, 

I'm trying to use REFPROP with the Python wrapper but when I execute the code of the tutorial an error occured just at the begining and I don't understand why.

Here is my code:

```
import matplotlib.pyplot as plt
import numpy as np
import os
os.environ['RPPREFIX'] = r'C:/Program Files (x86)/REFPROP'

from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
import glob

RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])

print(RP.RPVersion())

MOLAR_BASE_SI = RP.GETENUMdll(0,"MOLAR BASE SI").iEnum
```

and here is the error: 

```
  File "C:\Users\ad278075\AppData\Local\Programs\Python\Python312\Lib\site-packages\ctREFPROP\ctREFPROP.py", line 1577, in GETENUMdll
    if self._GETENUMdll is None: raise ValueError("The function GETENUMdll could not be loaded from the shared library.")
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: The function GETENUMdll could not be loaded from the shared library.
```

Can someone explain me how I should process to solve this problem. 

### Versions

**REFPROP Version:** 9.1
**Operating System and Version:** Windows 10
**Access Method:** Python

Thank you very much !

**Comment by ianhbell** [comment]
That function is not included in REFPROP 9.1. You'll need to upgrade to version 10.0 to make best use of the tutorial and python wrapper, though the old functions from 9.1 are also exposed in the same manner.

**Comment by augustindmbl** [comment]
Is there a way to use REFPROP without this function but still with the python wrapper ?

**Comment by ianhbell** [comment]
You have to use the old, clunky interface. Some docs are here: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python#ctypes-wrapper

**Comment by ianhbell** [comment]
So you would call ``SETUPdll`` first to initialize a model, and then one of the FLSH routines. There is a manual.txt file provided with REFPROP 9.1, and the exposed functions are largely documented here: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html
