### ISSUE TITLE
Documentation [Python]

### ISSUE THREAD

**Issue by augustindmbl** [usnistgov/REFPROP-wrappers#580]
Hi, 

I'm looking for documentation to understand how to use REFPROP 9.1 with the python wrappers. For now I read the Jupyter Notebook and the README and I know that these documents were written for the versions 10.x  but I still don't understand what each parameters mean (PQ, Q, z, ....). Do you know where I can find explanations ? And for version 9.1 if possible (but for version 10.x is already a good help). 

Thank you very much !

**Comment by ianhbell** [comment]
Please read the manual.txt that comes with REFPROP 9.1. I describes the functions that are exposed. You can call those functions from the Python interface
