### ISSUE TITLE
use refprop in mathematica

### ISSUE THREAD

**Issue by Happiness-in-Danger** [usnistgov/REFPROP-wrappers#581]
In MMA14,there are some problems.The version of NIST REFPROP is 10.0. I'm so sorry to pull request there![0fae0e1aeb3976031cb7fe497eac6711a6bea59c3241345ac9089541098b54f5.0.PNG](https://github.com/usnistgov/REFPROP-wrappers/assets/45912561/2a600440-a2db-41b1-b052-c707a0bc0a12)

**Comment by henningjp** [comment]
@Happiness-in-Danger  The `RefProp` function is only available in 10.0.0.0 or higher.  The code checks to make sure that's what you have.

1. Please open the REFPROP GUI.  When the splash screen come up.  Give me the exact version of REFPROP.  Screen grab if you can and post that.
![image](https://github.com/usnistgov/REFPROP-wrappers/assets/17114032/b1b455fc-e0a6-422f-bd52-aafd08e30b39)

2. Open a Mathematica notebook and just execute the ``Needs["RefpropLink`"]`` line by itself in Mathematica.   You should see the following (or a similar version):
![image](https://github.com/usnistgov/REFPROP-wrappers/assets/17114032/5facd4b9-833e-416d-828f-27dd17332e91)

   Post the output here.

3. After the Needs statement above, execute `getversion[]` and post the result.

4. Finally, please execute `setup[{"nitrogen"}, -1,"DEF"]` and post the output of that as well.

There may be a problem with version 10.0 as I think the code is expecting 10.0.0.0 or similar format.  The above output should help me figure it out.   I have 10.0.0.02 and so can't see the problem you are having.  I have an idea what's going on, though, and can probably patch it quickly.

A patch update from NIST would fix this, but I'd rather fix the wrapper code.

**Comment by Happiness-in-Danger** [comment]
![image](https://github.com/usnistgov/REFPROP-wrappers/assets/45912561/4abaff87-6f13-477b-8fcd-c64090f8d2b2)
![image](https://github.com/usnistgov/REFPROP-wrappers/assets/45912561/677334e0-9013-41ce-8c9b-6f18b4ea67d4)
My refprop is in A:\REFPROP

**Comment by henningjp** [comment]
Yes.  That's the problem.  RefpropLink is looking in the default location (`C:\Program Files\REFPROP\REFPRP64.DLL`) for the NIST REFPROP installation.

You can use:

   ```wl
   SetDLL[]
   ```
You'll get a pop-up to browse to and select your REFPRP64.DLL file and **_temporarily_** set it's location.  In your case it will be `A:\REFPROP\REFPRP64.DLL`.

Using a parameter of 1 will set this **_permanently_** in your profile so that to don't have to do this every time you start Mathematica.

   ```wl
   SetDLL[1]
   ```
See the Wolfram Help page on `SetDLL` for more information.

Let me know how it turns out and close this issue if it's working.

**Comment by henningjp** [comment]
@ianhbell - Does the `RPprefix` environment variable **_always_** get set when REFPROP is installed?   This Mathematica wrapper should probably check for that if it does.

**Comment by Happiness-in-Danger** [comment]
> Yes. That's the problem. RefpropLink is looking in the default location (`C:\Program Files\REFPROP\REFPRP64.DLL`) for the NIST REFPROP installation.
> 
> You can use:
> 
> ```mathematica
> SetDLL[]
> ```
> 
> You'll get a pop-up to browse to and select your REFPRP64.DLL file and **_temporarily_** set it's location. In your case it will be `A:\REFPROP\REFPRP64.DLL`.
> 
> Using a parameter of 1 will set this **_permanently_** in your profile so that to don't have to do this every time you start Mathematica.
> 
> ```mathematica
> SetDLL[1]
> ```
> 
> See the Wolfram Help page on `SetDLL` for more information.
> 
> Let me know how it turns out and close this issue if it's working.

I use the SetDLL[1] ,but it doesn't seem to work

**Comment by Happiness-in-Danger** [comment]
I use SetDll[1],but I reopen the new netbook I still set dll.
some unite is not to convert ,like density

**Comment by henningjp** [comment]
Not sure about the SetDLL[1] option. I'll look into it.  It works on my machine if I move REFPROP to a new location.  Best option, however, is to let REFPROP install in its expected default location on `C:\Program Files(x86)\REFPROP`.

On units, it all seems to work as advertised.  Using your example above for CO2, the units are as expected.  Note that by default everything is on a molar-basis; one must multiply/divide by the molecular weight to get the mass-basis values.

![image](https://github.com/usnistgov/REFPROP-wrappers/assets/17114032/f6de828c-0049-421a-bcad-baafe1812a55)

If you have an example where the units are **_not_** as expected, please provide an example.

**Comment by Happiness-in-Danger** [comment]
> Not sure about the SetDLL[1] option. I'll look into it.  It works on my machine if I move REFPROP to a new location.  Best option, however, is to let REFPROP install in its expected default location on `C:\Program Files(x86)\REFPROP`.
> 
> On units, it all seems to work as advertised.  Using your example above for CO2, the units are as expected.  Note that by default everything is on a molar-basis; one must multiply/divide by the molecular weight to get the mass-basis values.
> 
> ![image](https://github.com/usnistgov/REFPROP-wrappers/assets/17114032/f6de828c-0049-421a-bcad-baafe1812a55)
> 
> If you have an example where the units are **_not_** as expected, please provide an example.

OK,i understand how to convert unit.
Can you give me your environment about the REFPROP.I want to make sure my REFPROP environment.Thanks

**Comment by ianhbell** [comment]
@henningjp Yes, the windows installer sets the RPPREFIX variable.

**Comment by henningjp** [comment]
@Happiness-in-Danger - I do not understand your last question about the environment.  Can you be more specific?

**Comment by Happiness-in-Danger** [comment]
> @Happiness-in-Danger - I do not understand your last question about the environment.  Can you be more specific?
> 

I reopen the new netbook I still set dll.However you don't set.

**Comment by henningjp** [comment]
The code is not looking for RPPREFIX and it should.  I'll have to update the code to make use of this.

For now, look at:
`C:\Users\<user>\AppData\Roaming\Mathematica\Paclets\Repository\RefpropLink-1.1.0\TextREsources\Filepaths.txt`

This is where SetDLL[1] stores the path you pick.  Open this file in notepad and let me know what is written there.

Thanks.

**Comment by henningjp** [comment]
@Happiness-in-Danger - Ignore the above request.  This functionality is broken.  It looks like Wolfram changed their paclet resource structure; not sure when as I haven't tested non-default REFPROP locations it in a while.  I can fix this and add the check for RPprefix as well, but it will take a couple of weeks as I have other commitments.

Meanwhile, you'll need to run SetDLL to set the non-standard REFPROP location each time (or install REFROP in its default location on C: drive)

**Comment by Happiness-in-Danger** [comment]
> @Happiness-in-Danger - Ignore the above request.  This functionality is broken.  It looks like Wolfram changed their paclet resource structure; not sure when as I haven't tested non-default REFPROP locations it in a while.  I can fix this and add the check for RPprefix as well, but it will take a couple of weeks as I have other commitments.
> 
> Meanwhile, you'll need to run SetDLL to set the non-standard REFPROP location each time (or install REFROP in its default location on C: drive)

ok，I will wait you fix this problem.Thanks

**Comment by henningjp** [comment]
@Happiness-in-Danger Download and try this new version.  It should fix your problem.  Make sure the environment variable RPprefix is set to your REFPROP location before your run it.

**Comment by Happiness-in-Danger** [comment]
> @Happiness-in-Danger下载并试用此新版本。它应该可以解决您的问题。在运行它之前，请确保环境变量 RPprefix 已设置为您的 REFPROP 位置。

 Sorry, I forget to reply this messages. Thanks, it's worked.

**Comment by henningjp** [comment]
Absolutely!  Documentation on creating and building other language paclet documentation looks like it's supported, but documentation on how to do this is sketchy.  It may take a bit of research.  If you can figure it out, go for it.
