### ISSUE TITLE
MATHCAD WRAPPER NO LONGER FUNCTIONING (RefProp_units.mcdx)

### ISSUE THREAD

**Issue by mdsrjw** [usnistgov/REFPROP-wrappers#585]
### Description

I was using the PrimeREFPROPWrapper dll for some time and the refprop functions mysteriously stopped working for me in the Mathcad Prime 9 environment. I find that there are functions in the mathcad file called RefProp_units (located at C:\Program Files\PTC\Mathcad Prime 9.0.0.0\Custom Functions\RefProp_units.mcdx) that are no longer functional (an error is shown in the mathcad calculation). I see the following non-functioning functions:

A function called rp_GetDel (str)
A function called (rp_IsMulti (vstr_i) [i.e., vstr sub i - I can't show a subscript i]
A function called rp_REFPROP1 ( "", "NCOMP", 0, 0)
A function called StrSplit (hOut))

I am guessing that the version of the refrop dll that I am currently running is not valid. Upon opening the refprop desktop program, I see it report v10.0a in the "about" command. Do you think you can point me in the right direction to get things working again?

### Steps to Reproduce

See description of problem

**Expected behavior:** See description of problem
**Actual behavior:** See description of problem

### Versions

**REFPROP Version:** 10.0a
**Operating System and Version:** WIN 11 version 23H2 Build 22635.3350
**Access Method:** Mathcad Wrapper 

### Additional Information

An example of what I am seeing [rp_GetDel (str)]

![rp_GetDel](https://github.com/usnistgov/REFPROP-wrappers/assets/43067316/e140a7d0-fc3a-4085-83e6-5e62a9d0a226)

**Comment by henningjp** [comment]
Can you screen grab what the GUI is reporting as your version from the opening splash screen, i.e.

![image](https://github.com/usnistgov/REFPROP-wrappers/assets/17114032/fbc998b5-81f1-4fc6-9e52-f928c4599669)

Also, from Mathcad, execute

```
rp_getNIST(0)
```

and let me know what it returns.

Did anything else change on your machine?  REFPROP version?  REFPROP location?

**Comment by mdsrjw** [comment]
Thanks Jeff.

Here is the "About" screen - too hard to capture the opening splash...

![Refprop About Screen](https://github.com/usnistgov/REFPROP-wrappers/assets/43067316/6aafd455-0987-4fc1-88ac-045e2796ab1d)

Here is the DLL version reported by Mathcad...

![Mathcad NIST Version DLL Report](https://github.com/usnistgov/REFPROP-wrappers/assets/43067316/0b757eb6-b861-40a9-8510-8762a32c5ead)

I believe that the version of the DLL that I was previously using expired (?). I eventually reinstalled refprop because I could not get the DLL that I obtained independently to work (the one I discovered during my journey through installing the wrapper so that it functioned as intended). I really think it's the DLL that is incorrect (which seems apparent now) and that my problem is in not knowing how to go about obtaining the latest DLL for the wrapper - I'd really like to learn how to avoid this in the future. Hope this makes sense.

Bob

**Comment by henningjp** [comment]
It's the version 9.9.9.0 that's causing the issue.  I saw this in one other case.  When this add-in was written, I didn't realize that v9.9.9.0 was a thing.

If you check with support at NIST, I'm sure you can get an update to the latest patch release DLLs.  I'm currently on 10.0.0.2, but I think there are more recent patches.

**Comment by mdsrjw** [comment]
Thanks Jeff. Sent the email off and will await their reply. I appreciate your help. BobSent from my iPhoneOn Mar 30, 2024, at 2:16 PM, Jeff Henning ***@***.***> wrote:﻿
It's the version 9.9.9.0 that's causing the issue.  I saw this in one other case.  When this add-in was written, I didn't realize that v9.9.9.0 was a thing.
If you check with support at NIST, I'm sure you can get an update to the latest patch release DLLs.  I'm currently on 10.0.0.2, but I think there are more recent patches.

**Comment by ianhbell** [comment]
Email me at ian.bell@nist.gov for an updated version

**Comment by mdsrjw** [comment]
That was the ticket, Ian. Thank you for the help. However, a follow-up question if you will allow me - how do I discover that there are updates to the DLL available?

**Comment by ianhbell** [comment]
You can email me - that is about the only option available.

**Comment by mdsrjw** [comment]
Ok, sounds good. If the wrapper stops working again, I’ll assume it’s time to contact you. Thank you for your help!BobSent from my iPhoneOn Mar 31, 2024, at 1:24 PM, Ian Bell ***@***.***> wrote:﻿
You can email me - that is about the only option available.
