### ISSUE TITLE
Refprop wrapper for Matlab returns py.str ? 

### ISSUE THREAD

**Issue by kaern** [usnistgov/REFPROP-wrappers#59]
On my computer, the wrapper for matlab returns strings ? 

Python array with properties:
```
    itemsize: [1×1 py.int]
    typecode: [1×1 py.str]

    array('d', [373.1242958476953, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, 
...
-9999990.0, -9999990.0])
```
and it seems not possible to access the output.. (373.124). I can do a char(r.Output) and display the string: 
```
>> char(r.Output)

ans =

    'array('d', [373.1242958476953, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0,
...
 -9999990.0, -9999990.0])'
```

**Comment by ianhbell** [comment]
Hmm, that’s not good.  I had to modify the Python wrapper to return array.array (because making a list took too long), which works brilliantly in Python, and can be indexed, and so on.  But in Matlab that seems to be a problem.

**Comment by ianhbell** [comment]
I’m working on this right now.  Trying to find a “nice” solution, but it may be that you will need to call a function to inform the wrapper that you want lists as output instead of array.array.  Do you think that would be ok?  Alternatively, you can also convert to Python list in MATLAB.  I’ll find an acceptable solution.

**Comment by ianhbell** [comment]
Please let me know if the updates to the docs are not sufficient and I can add more information

**Comment by kaern** [comment]
Jorrit helped me understanding the python array type. thanks now it works. so simple..

**Comment by ianhbell** [comment]
Great! Good to hear and thanks @jowr
