### ISSUE TITLE
Errors when trying to generate tables from MATLAB

### ISSUE THREAD

**Issue by yahavmorag** [usnistgov/REFPROP-wrappers#590]
Hello,
trying to generate REFPROP tables from Matlab using by running thw file refprop_example.m
[refprop_example.txt](https://github.com/usnistgov/REFPROP-wrappers/files/15083669/refprop_example.txt)

REFRPROP (DLL VERSION 10.0) is running in the background

 I get this error:

Error using loadlibrary
Failed to preprocess the input file.
 Output from preprocessor is:'cl' is not recognized as an internal or external command,
operable program or batch file.

Error in refpropm (line 242)
            [~,~] = loadlibrary(strcat(BasePath,dllName),prototype,'alias',libName);.

Thank you!

**Comment by ianhbell** [comment]
The refpropm interface is no longer supported. Please move to the python-based one.

The problem here is that you need to install a compiler.
