### ISSUE TITLE
How to calculate properties based on input Qmass？

### ISSUE THREAD

**Issue by GentleVincent** [usnistgov/REFPROP-wrappers#591]
refprop 10.0，excel VBA：
I am wanting to calculate properties of R448A based on TQ，the known Q is Qmass，but find out that the input value Q in "TQ" must be Qmole，how can I do as I just know T and Qmass.  Thanks!

**Comment by ianhbell** [comment]
Why do you think that TQmass is not supported?

**Comment by GentleVincent** [comment]
> Why do you think that TQmass is not supported?

using EXCEL VBA，I tried many different UNIT type, such as MEUnits, SI, SI with C and so on，input TQ，I find the program using the input Q as Qmole as per the out valer, I don't know how to let the program to use the input Q as Qmass in VBA.

**Comment by ianhbell** [comment]
Do you get an error message?

**Comment by GentleVincent** [comment]
> Do you get an error message?

No, everything is ok except the Q is treated as Qmole.

**Comment by ianhbell** [comment]
[See #2](https://github.com/usnistgov/REFPROP-wrappers/issues/288#issuecomment-2081158034)
