### ISSUE TITLE
Python two phase properties for pure and mixtures

### ISSUE THREAD

**Issue by omarbay** [usnistgov/REFPROP-wrappers#593]
### Description

I am connecting Python to NIST Refporp through your wrapper and getting props out into a csv, I managed to get the properties, however I need the function that gets properties for both liquid and vapor when the is between 0 and 1. Attached below also other properties like viscosity, etc.

![image_2024-05-01_143053269](https://github.com/usnistgov/REFPROP-wrappers/assets/56736042/78215cc2-8f2e-44e8-a62c-69b000582d6b)

**REFPROP Version:** [10]  
**Operating System and Version:** [Windows 11]  
**Access Method:** [How you are accessing REFPROP (i.e. Python, PyCharm)]

**Comment by ianhbell** [comment]
Take a look here: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll . Basically the suffix ``LIQ`` will give you the liquid phase value and ``VAP`` the vapor phase when the inputs are two-phase, so ``DLIQ;DVAP`` would be the co-existing densities
