### ISSUE TITLE
syntax for liquid and vapor mass fraction in single compound (from MATLAB-wrapper of REFPROP)

### ISSUE THREAD

**Issue by RalucaDumitrescu** [usnistgov/REFPROP-wrappers#6]
Hello, 

I don't seem to figure out the syntax for the liquid phase & gas phase composition in single component.
From the example given in refprop.m, the syntax is [x y] = refpropm('X','P',5e2,'Q',0.4,'R134a','R32',[0.8, 0.2]) for mixture, but I don't know how and which property to use for single component. I tried using: 

>> refpropm('X','T',95,'D',3,'methane')

ans =

     1
 
also

>> refpropm('X','T',95,'D',3,'methane','CO2',[1,0])

ans =

     1
     0

but all the trials give answer '1'. I am particularly interested in results for the region below the binodal line of pure methane. Any help is appreciated.

Thanks,
Raluca

**Comment by ianhbell** [comment]
Well, both phases are pure methane (so composition is unity), but if you actually mean vapor quality, you want ‘Q’

**Comment by RalucaDumitrescu** [comment]
Yes, that's it!  Thank you!
