### ISSUE TITLE
R454B Sat Temp

### ISSUE THREAD

**Issue by carltonheard** [usnistgov/REFPROP-wrappers#604]
If you have an issue to report, please continue and fill out the applicable sections below.  The details provided will help to resolve this issue as quickly as possible.

### Prerequisites

**NOTE**: Be aware that all issues are publicly accessible and viewable.  Thus please do not post any code or other content that is protected intellectual property or under copyright.

Before posting an issue, please:  
    * Check the [FAQ](https://pages.nist.gov/REFPROP-docs/) for common solutions.  
    * Check that your issue isn't already filed under [REFPROP Issues](https://github.com/usnistgov/REFPROP-issues/).  
    * Check the [documentation](http://refprop-docs.readthedocs.io/en/latest/).  

You can also use markdown to format your issue: [GitHub guide on Markdown](https://guides.github.com/features/mastering-markdown/). If you have code snippets, please use a code block to ensure that the formatting remains legible in the web interface.  For instance, surround your code in triple backticks:

``` python
print('Hello world!')
```

### Description

I'm using the Refprop DLL in a LabVIEW program and am having some issues pop up. I've successfully used the DLL for a long time but in a new application I'm getting some results I can't explain. I'm trying to get saturation temperature for R454B at different pressures but they aren't matching the expected results. I have the setup function the same as I've always used it where it just calls the SETUPdll function with the following inputs:
ncomp = 2
hfiles = C:\Refprop\fluids\R32.FLD|C:\Refprop\fluids\R1234YF.FLD|         
hFmix = C:\Refprop\fluids\HMX.BNC       
hrf = ASH
The other inputs are defaults of 10000, 255, 3, and 255. Then I run the SATPdll function with the input pressure, phase (1 for liquid, 2 for vapor), and molar fractions of 0.829248 and 0.170752 (from r454b.mix file). When I input a pressure of 130.1 psi (897 kPa) I get a result of 43.9208 F. That's about 6 degrees lower than what I was expecting. The error seems to get wider as the pressure decreases. When doing some software changes a couple weeks ago I kept getting convergence errors so I tried adding in the SATSPLNdll function after the SETUPdll function but took that back out and am still getting the discrepancy. Can someone help me figure out what I've done to cause this to happen with Refprop?

### Steps to Reproduce

Use the inputs described above. I'd be interested to know if anyone else gets different results. I feel like they used to match but I've tried on two different computers, different versions of LabVIEW, and even replaced the Refprop DLL with the one from the original zip file I had gotten and still getting the same values.

**Expected behavior:** Match closely with r454b PT charts like https://www.scribd.com/document/600130238/r454b-pt-chart-pdf

**Actual behavior:** Lower thane expected saturation temperature values. About 6 degrees lower when at around 130 psi.

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 10
**Access Method:** LabVIEW using a call library function node with the Refprop.dll file

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by ianhbell** [comment]
Are you good?

**Comment by carltonheard** [comment]
Yeah I compared the values against the desktop Refprop and they lined up correctly. I think the project manager was pulling PT charts that were not clear on how they were factoring in barometric pressure to their PSIG values.
