### ISSUE TITLE
Error in "RefProp_units" Mathcad Worksheet

### ISSUE THREAD

**Issue by mdsrjw** [usnistgov/REFPROP-wrappers#605]
### Description

I am seeing an error being reported by Mathcad in the "RefProp_units" file. The error reported states "A function or a variable name is required here." The function is in the "Coefficient of Thermal Expansion" section of the Mathcad worksheet. Thoughts on why only this function is a problem?

### Steps to Reproduce

Inherent to the Mathcad Worksheet so nothing required to reproduce the problem.

### Versions

**REFPROP Version:** 10.0.0.98b DLL version 
**Operating System and Version:** Win 11  
**Access Method:** Mathcad wrapper  

### Additional Information

See snippet below from "RefProp_units" worksheet for problem function.
![Function Error](https://github.com/usnistgov/REFPROP-wrappers/assets/43067316/5c56b475-8f70-4e17-9a38-fdfd3e5fbddc)

**Comment by mdsrjw** [comment]
Thanks for the reply, Jeff. I am not certain why, but I could not get my
worksheet to function even with your suggested changes. In the end, I
decided to just disable the equation. I'll try to do some more
investigation, to see if I can overcome this problem.

Thanks,

Bob

**Comment by henningjp** [comment]
@mdsrjw - I'm back to my machine.

Here's the mod I made to the worksheet.  Again, I have no idea why this works in Prime 10 and the original one-line function does not.

![image](https://github.com/user-attachments/assets/a8be59f9-3ed1-462e-af1a-7b93f3c6fec6)  vs the original ![image](https://github.com/user-attachments/assets/3771095a-23f8-4090-af1a-080d2a8ef180)

If this works for you as well, I'll update the include file in the repository.  Let me know.

Also, I'm trying to generate a more generic example for PTC that doesn't require them to install this REFPROP add-in.  If you come up with something that demonstrates the issue simply, let me know.

Jeff

**Comment by mdsrjw** [comment]
Thank you, Jeff. I tested your Mathcad "program" and it works fine as
suggested. I will leave the RefProp_units sheet with your suggested method.
I can submit this to the general Mathcad usage group at the PTC site if
this is OK with you. There are many long-time users that understand the
base program very well and could possibly provide some insight. I'll also
consider a similar function that doesn't necessarily require refprop.

Regards,
Bob Wilson

**Comment by mdsrjw** [comment]
Jeff,

I had a response on the Mathcad community site. They confirm that it is a
bug and had been discovered previously. Here is the thread:

Solved: Function Worked in Prime 9, but not in Prime 10 (w... - PTC
Community
<https://community.ptc.com/t5/Mathcad/Function-Worked-in-Prime-9-but-not-in-Prime-10-without-mods/m-p/962397#M212979>
