### ISSUE TITLE
Matlab wrapper in Ubuntu

### ISSUE THREAD

**Issue by marc-bernades** [usnistgov/REFPROP-wrappers#607]
I have purchased REFPROP 10.

- I only have an Ubuntu machine. I need therefore to install it through Windows and how do I transfer to Ubuntu?
- When I have it in Ubuntu how can I build the wrapper in Matlab, I read the website and I see Fortran is required? I've never used it, are there further details (examples) upon this steps? I want to make sure I can call REFPROP with Matlab in Ubuntu machine.

Thank you in advance.

**Comment by ianhbell** [comment]
I have sent you a link to get the source files directly
