### ISSUE TITLE
Can't use GETENUMdll

### ISSUE THREAD

**Issue by lezhou1999** [usnistgov/REFPROP-wrappers#612]
when a use the function RP.GETENUMdll(0, "MASS BASE SI").iEnum ,some error occuars.I did everything as the tutorial said, and below is the feedback of the syntax: ValueError: The function GETENUMdll could not be loaded from the shared library.

**Comment by ianhbell** [comment]
Sounds like you have REFPROP 9.x. Recommend to upgrade to 10.0, or you can still use the legacy functions from REFPROP 9.
