### ISSUE TITLE
Incorrect use of calllib

### ISSUE THREAD

**Issue by ZZM-iet** [usnistgov/REFPROP-wrappers#613]
Using the 'legacy method' to call 'refpropm('T','P',101.325,'Q',0,'WATER')' in MATLAB，Display it：

Error refprop (line 295)
        [nc,~,~,~,ierr,errTxt] = calllib(libName,'SETUPdll',numComponents,path,hmix,href,0,herr,10000,255,3,255);

The array must be a numerical or logical value, or a pointer to a value

**Comment by ianhbell** [comment]
We no longer support the refpropm interface. Please switch to the Python-based one.

**Comment by ZZM-iet** [comment]
When using the Python-based method, an error occurs in the following steps :

"MOLSI = RP.GETENUMdll(int8(0),'MOLAR BASE SI').iEnum;"

Display it：

incorrect use “ctREFPROP>GETENUMdll”

ValueError: The function GETENUMdll could not be loaded from the shared library.
