### ISSUE TITLE
Add open source license for wrappers

### ISSUE THREAD

**Issue by atomadf** [usnistgov/REFPROP-wrappers#614]
### Description

A license be made available for the wrappers

### Steps to Reproduce
1. N/A

**Expected behavior:** An MIT or GPL Licnese file should be listed to protect contributed software as open-source.

**Actual behavior:** There is no LICENSE file in this repository

### Versions
N/A

### Additional Information

#58 seems to have been closed but no license added.

**Comment by ianhbell** [comment]
I'm sorry but we can't do that due the vagaries of US Federal law.
