### ISSUE TITLE
MATLAB wrapper on Macbook Air M1 not understanding architecture

### ISSUE THREAD

**Issue by Mansi-zei** [usnistgov/REFPROP-wrappers#619]
### Description

I am having trouble getting the MATLAB wrapper to work on my Mac air. I have successfully built the CMake directory, and followed each of the steps on the legacy instructions, but when I try to use refpropm (downloaded from the legacy folder and also placed in the refprop directory off my home directory), the following error message appears:
```
>> refpropm('T','P',101.325,'Q',0,'WATER')
Error using refpropm (line 215)
Architecture[MACA64] is not understood
```
I have attached an image of the file structure on my laptop below. I would have tried to follow the more updated instructions, but they seem to be set up for a Windows interface. Is there a MacOS version of this wrapper beyond the legacy one?

One possible issue I am considering is that my cmake build is on my desktop (home/desktop/refprop-build/cmake-build) and the refprop directory is in my home directory (home/refprop), but it does not seem that that's the problem? I've copied over the files and folders listed as necessary, so I don't think this is actually an issue.

### Versions

**REFPROP Version: 10**   
**Operating System and Version: MacOS Sonoma 14.5, Macbook Air M1 (arm64 architecture)** 
**Access Method: MATLAB R2024a via Python 3.12 with standard installations (IDLE interface)**

### Additional Information

<img width="553" alt="Screenshot 2024-09-13 at 10 43 49 AM" src="https://github.com/user-attachments/assets/970049f6-d170-41f8-937b-5aefe794428e">

**Comment by ianhbell** [comment]
The refpropm interface is no longer supported. Please switch to the Python-based one for MATLAB. What architecture is your MATLAB? Sounds like maybe it is still x86_64.

**Comment by Mansi-zei** [comment]
How can I identify the architecture for my MATLAB? I downloaded the R2024a version for macos from the mathworks website. I would be happy to switch to the Python-based one, I just don't know how to because the commands appear to only work for windows os

**Comment by ianhbell** [comment]
No clue - check out the MATLAB docs. Sometimes it is in the about page.

I use Mac as my primary OS, so the Python interface definitely works, and I have an M2.

**Comment by Mansi-zei** [comment]
I've now successfully managed to follow the steps for the MATLAB wrapper, but am now running into a new problem. I am trying to run a set of files built on REFPROP 9.1 and the old MATLAB wrapper (with the refpropm file). In order to get it working with the new wrapper, do I just need to replace every instance of refpropm with RP? Is there a specific place within my file setup that the downloaded files need to be saved in order to refer to the REFPROP library?

I can also open this as a new issue or change the header on the current issue if either is preferable for your organizational system.

**Comment by ianhbell** [comment]
Yes, that is right, you need to either write your own wrapper function to replace refpropm, or rewrite your code. Also, you should upgrade to version 10.0

**Comment by ianhbell** [comment]
There is also the refmatpy interface which is similar to refpropm: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB#refprop-for-matlab
