### ISSUE TITLE
Critical points differ between matlab and refprop call

### ISSUE THREAD

**Issue by bsondelski** [usnistgov/REFPROP-wrappers#62]
### Description

The critical point data of ammonia/water and co2/water mixtures doesn't match between Matlab and refprop data (see attached photo). I'm just curious which is more accurate? Assuming the refprop GUI data is more accurate and the discrepancy is a communication problem between Matlab and refprop, how reliable is the critical point information for these mixtures taken from the Refprop GUI?

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 10
**Access Method:** Matlab refpropm call

### Additional Information
![matlab refprop critical points](https://user-images.githubusercontent.com/31516748/45043252-478bd580-b032-11e8-8e4f-198b27083345.PNG)

**Comment by ianhbell** [comment]
Good question.  @EricLemmon will have some more input to share on this point, but basically the call through refpropm doesn't do the same calculation as your code in the GUI.  The GUI uses the approximate correlation (not a very good one in this case :/ ) while the call in refpropm calls CRITPdll: https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/MATLAB/legacy/refpropm.m#L395 .


This, among other reasons, is why you should use the new Python-based wrapper for MATLAB.  The code paths are much more similar.

[https://avatars2.githubusercontent.com/u/5330158?s=400&v=4]<https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/MATLAB/legacy/refpropm.m#L395>

REFPROP-wrappers/refpropm.m at master - github.com<https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/MATLAB/legacy/refpropm.m#L395>
github.com
Wrappers around NIST REFPROP for languages such as Python, MATLAB, etc.


________________________________

**Comment by EricLemmon** [comment]
The information here may help to explain the differences you are seeing:
https://pages.nist.gov/REFPROP-docs/#calculation-of-the-critical-point-and-saturation-states-in-the-critical-region
