### ISSUE TITLE
Different calculation results between refprop10 and excel (integrate with refprop10)

### ISSUE THREAD

**Issue by luckonfidence** [usnistgov/REFPROP-wrappers#623]
I recently used refprop10 software and excel (integrate with refprop10) to calculate the density, enthalpy, and entropy of  refrigerant at the same temperature and pressure, found that there is a difference between the enthalpy calculated directly by refprop10 software and the enthalpy of the same refrigerant calculated by excel, the density and entropy are the same (see the 3 pictures in the attachment). I have tried 3 kind refrigerants(R134A, R1233zd(e), R515b, included pure fluid and mixture), and the conclusion is the same, different enthalpy values between refprop10 and excel, the same density and entropy values.    
      What causes this problem? Is there any solution?
     I also tried with refprop9.1(some colleagues installed refprop9.1 software)and excel(integrated with refprop9.1)，the problem disappeared(enthalpy values calculated by refprop9.1 and excel(integrated with refprop9.1) are the same. 
     Are the default reference states of refprop10 and refprop9.1 different?  Because we just installed refprop and integrated refprop into Excel, and then compared them directly without changing any default settings. We also compared the enthalpy, density, and entropy values ​​of the same refrigerant (R134A, R1233zd(e)) calculated by refprop10 and refprop9.1 at the same temperature and pressure, the values ​​calculated by the 2 versions of refprop software are equal. So the problem is that the enthalpy value calculated by Excel integrated with refprop10 is different from the enthalpy value calculated by refprop10, repfprop9.1, and Excel integrated with refprop9.1, that's strange, hope your help.

<img width="960" alt="R134A" src="https://github.com/user-attachments/assets/233ff997-5455-4c87-b41f-4a5ce9d92e09">
<img width="960" alt="R1233ZD(E)" src="https://github.com/user-attachments/assets/5a2e7be5-5e82-4aec-a6f6-a7eeefd407eb">
<img width="960" alt="R515B" src="https://github.com/user-attachments/assets/43d230b6-d7fc-4323-9b15-c09efa47549c">

**Comment by ianhbell** [comment]
Excel and the GUI use different reference states by default for historical reasons. You can select the reference state in both the VBA code and the GUI to make them be the same. But I always council to a) use base SI units for checking with REFPROP b) don't worry about reference states and only compare differences between statepoints which must always be the same.

Between versions, you should also check that the EOS in use are the same.

**Comment by luckonfidence** [comment]
Thank you ianhbell for the patient answer! 
And I have 4 questions:
a) Regarding the first sentence in your answer, what is the default reference states in GUI?  I just need to change the reference states in VBA of Excel to be consistent with that in GUI;
b) Are there any differences calculated by refprop10 if use different system of units? like "English system" or "SI system", for in our project, we used to the "English system";
c) In the attachment pictures I added, we can see obviously  that the differences between state points of GUI and excel were not the same, why?
d) How to check the EOS in refprop? Can you please give a simple tutorial, about some steps to check the EOS.

**Comment by nist-aharvey** [comment]
For mixtures, there is an additional issue with reference states, which is whether the reference state is applied to the mixture as a whole or to each pure component.  I believe that the Excel uses "each pure component" as its default, but the GUI is the opposite.  You can change that setting in the GUI by going to Options, Reference State, and changing the selection in the box above the OK button.

@ianhbell, for item c) above I think the user is talking about the pictures with their original question. It does appear that there are pairs of points where the difference in enthalpy is not the same between the GUI and Excel.  Look at the last 2 points for R134a (first set of pictures), for example -- a difference of 1.3 Btu/lbm in Excel versus a difference of 1.5 in the GUI.  I confirm that I reproduce the GUI results (and the EOS for R134a should not have changed between versions 9.1 and 10 since the default EOS is from 1994).

**Comment by nist-aharvey** [comment]
The difference you circled between Excel and the GUI is not unexpected, because of the issue of reference states as already mentioned.  The only thing that matters in thermodynamics is the enthalpy **difference** between states. You can see what Reference state it is using in the GUI by going under Options, Reference State.
However, it does look like something inconsistent is happening, since I can see that the difference between the last two points in the table is about 3.5 in one case and 3.0 in the other.

The next thing might be to check and be sure the same equation of state is being used in both places, or if somehow you have accessed an alternate EOS in one place. For the GUI, this is under Fluid Information in the Substance menu (should show Tillner-Roth and Baehr EOS, which it is probably using since I can match your results).  I'm not familiar with using Refprop in Excel so somebody else will have to tell you how to access that information there.

**Comment by nist-aharvey** [comment]
It might also be worth trying using molar units. Refprop (and chemical thermodynamics in general) works in moles, not mass. I know there are some bugs in REFPROP 10 for mixtures when mass fractions are used. I can't imagine that causing a problem like this for pure components, but it is probably worth checking.

**Comment by luckonfidence** [comment]
> For mixtures, there is an additional issue with reference states, which is whether the reference state is applied to the mixture as a whole or to each pure component. I believe that the Excel uses "each pure component" as its default, but the GUI is the opposite. You can change that setting in the GUI by going to Options, Reference State, and changing the selection in the box above the OK button.
> 
> @ianhbell, for item c) above I think the user is talking about the pictures with their original question. It does appear that there are pairs of points where the difference in enthalpy is not the same between the GUI and Excel. Look at the last 2 points for R134a (first set of pictures), for example -- a difference of 1.3 Btu/lbm in Excel versus a difference of 1.5 in the GUI. I confirm that I reproduce the GUI results (and the EOS for R134a should not have changed between versions 9.1 and 10 since the default EOS is from 1994).

Thank you very much, nist-aharvey. According to your instruction, I changed the setting in the refprop10 GUI by going to Options-Reference State-Apply reference state to-each pure component and currently defined mixture respectively, as can be seen in pictures below, and the results remains almost the same, but both enthalpy results were different from results calculated by excel, as showed in picture.
![Uploading 2.jpg…]()

**Comment by luckonfidence** [comment]
![3](https://github.com/user-attachments/assets/94070548-283f-4cdd-a4cf-602b017c5db8)
![4](https://github.com/user-attachments/assets/6440486c-765d-4fd0-b42e-65088f6050ae)


> The difference you circled between Excel and the GUI is not unexpected, because of the issue of reference states as already mentioned. The only thing that matters in thermodynamics is the enthalpy **difference** between states. You can see what Reference state it is using in the GUI by going under Options, Reference State. However, it does look like something inconsistent is happening, since I can see that the difference between the last two points in the table is about 3.5 in one case and 3.0 in the other.
> 
> The next thing might be to check and be sure the same equation of state is being used in both places, or if somehow you have accessed an alternate EOS in one place. For the GUI, this is under Fluid Information in the Substance menu (should show Tillner-Roth and Baehr EOS, which it is probably using since I can match your results). I'm not familiar with using Refprop in Excel so somebody else will have to tell you how to access that information there.

Thank you nist-aharvey, as can be seen in picture1 below, the EOS of R134A was correctly what you said, Tillner-Roth and Baehr.  And the reference state of R134A was showed in picture2 and pictuer3 (I tried to change the item "Apply reference state to", but the calculation results remains the same, and both enthalpy results were different from that of excel). I do need help from NIST to tell me how to check EOS information in excel, thanks a lot.
![Uploading 5.jpg…]()

**Comment by luckonfidence** [comment]
![6](https://github.com/user-attachments/assets/b6c8fe1a-0360-44ba-9476-5fb9cd9bfbc3)
![7](https://github.com/user-attachments/assets/10e4e2ea-bd82-4bb1-b81a-e5496aee0e72)


> It might also be worth trying using molar units. Refprop (and chemical thermodynamics in general) works in moles, not mass. I know there are some bugs in REFPROP 10 for mixtures when mass fractions are used. I can't imagine that causing a problem like this for pure components, but it is probably worth checking.

Thank you nist-aharvey. I have compared the calculation results of pure substance-R134A by refprop 10 and excel(integrated with refprop 10) when use molar units, as can be seen in picture below. The conclusions were the same, equal values of density and entropy, different values of enthalpy as well as the enthalpy difference between 2 points.
![Uploading 8.jpg…]()

**Comment by luckonfidence** [comment]
> What version of REFPROP do you use? You can email me ([ian.bell@nist.gov](mailto:ian.bell@nist.gov)) for access to our beta which fixes some issues with reference states.

I use REFPROP 10.0
Ok, I will email you, thanks.

**Comment by luckonfidence** [comment]
Hi, Ianhbell sent me a beta version of refprop10 last week, and I did the compare works in the same way as described above, but the  problems still exists: different enthalpy value as well as enthalpy difference between refprop10 GUI and EXCEL(integrated with refprop10) , at the same temperature and pressure, buthe density and entropy remains the same between refprop10 GUI and excel (as showed in figure below). For the calculation results (density, enthalpy, entropy) of refprop9.1 GUI, EXCEL(integrated with refprop9.1), and refprop10 GUI are the same, so, I think there might be some problems when EXCEL call refprop10, but I cannot figure out where is the problem.
![Uploading 1.jpg…]()

**Comment by ianhbell** [comment]
You still need to ensure that both are using the same reference state. The beta doesn't resolve that.

**Comment by nist-aharvey** [comment]
> You still need to ensure that both are using the same reference state. The beta doesn't resolve that.

Although if the user is still getting different enthalpy DIFFERENCES between state points as reported, that is not a matter of reference states and would indicate some other inconsistency between Excel and the GUI.
The pictures in the last comment don't show up for me, so I can't verify that.
@luckonfidence, for further debugging I suggest simplifying your example so you are just showing us two temperature/pressure state points, for a pure fluid like R134A, with a different enthalpy difference between the GUI and Excel (preferably with the same referenced state chosen for the GUI and Excel). It becomes difficult to follow if the example has 15 different points.

**Comment by luckonfidence** [comment]
> > You still need to ensure that both are using the same reference state. The beta doesn't resolve that.
> 
> Although if the user is still getting different enthalpy DIFFERENCES between state points as reported, that is not a matter of reference states and would indicate some other inconsistency between Excel and the GUI. The pictures in the last comment don't show up for me, so I can't verify that. @luckonfidence, for further debugging I suggest simplifying your example so you are just showing us two temperature/pressure state points, for a pure fluid like R134A, with a different enthalpy difference between the GUI and Excel (preferably with the same referenced state chosen for the GUI and Excel). It becomes difficult to follow if the example has 15 different points.

Ok, as you recommended, I only list 2 temperature/pressure state points to calculate the density, enthalpy, entropy(seen pictures below ). Picture1 is results calculated by refprop10 GUI, picture2 is results calculated by refprop10.0.0.98b GUI, picture3 is calculated by EXCEL(integrated with refprop 10 and refprop 10.0.0.98b, results of these two EXCEL are the same). I think the reference state are the same because the entropy value of refprop10 GUI and EXCEL are the same. Can you also try using Excel to call refprop10 software internally for calculation comparison? I believe the conclusion will be the same as mine. But when using EXCEL to call refprop9.1, the results will be the same with refprop GUI. 
In our company (as well as many other companies), we use EXCEL call refprop to calculate the air-conditioning unit performances, we found that the performance results were obviously different from previous performance data, even use the same states points, and then, we found the results differences between refprop10 GUI and EXCEL.
![3 1](https://github.com/user-attachments/assets/90d5da10-52da-4b75-a16f-0c15d5981930)
![1 1](https://github.com/user-attachments/assets/4c032b33-d886-44d6-b87a-204761ee126e)
![2 1](https://github.com/user-attachments/assets/96eae924-21ac-4822-af8e-5efb1b56c130)

**Comment by ianhbell** [comment]
I think you want "H" for enthalpy instead of "E"

**Comment by nist-aharvey** [comment]
Indeed, "E" is the label for the Internal Energy which is a different property. That is almost certainly the source of your problem.

**Comment by luckonfidence** [comment]
> Indeed, "E" is the label for the Internal Energy which is a different property. That is almost certainly the source of your problem.
> I think you want "H" for enthalpy instead of "E"

Oh, yeah! you are exactly right, I used wrong code for the codes of enthalpy and internal energy in REFPROP.XLS are adjacent, I still used to the input method like in refprop9.1, if want to calculate enthalpy, just input the "enthalpy", haha. And now there in no problem, thank you very much!

**Comment by ianhbell** [comment]
Glad this had a clear solution

**Comment by luckonfidence** [comment]
> Glad this had a clear solution

Thanks a lot!
