### ISSUE TITLE
Issue#|LabVIEW| Some mixture encouter error when use T or P function

### ISSUE THREAD

**Issue by RalphPang** [usnistgov/REFPROP-wrappers#625]
Dears,
Firstly I'm using 64bit LabVIEW 2018, I downgrade the package using LabVIEW 2023. Since I'm using 64bit LabVIEW I invoked "REFPRP64.DLL"
All fluids didn't encouter any issue but most of the mixtures encoutered couldn't convert from temperature to pressure vice versa as below:
![image](https://github.com/user-attachments/assets/ae8288fe-1c1b-4a24-ba8d-9dde5b6db98e)
In the picture we could see there is an error message "[ROOTFIND error 151] Iteration failed to converge." 
I want to use R404A convert only from T to P or P to T.
Could you advise how to do it?
![image](https://github.com/user-attachments/assets/4e727866-adce-42f0-815c-3996022a9268)

**Comment by RalphPang** [comment]
I want to use R404A, the error message is excat the same with above:

**Comment by ianhbell** [comment]
Have you turned on the saturation splines? That is about the only advice we can offer for problems such as these

**Comment by ianhbell** [comment]
I would recommend to check the calculations outside of Labview in something like Python to ensure you know how things should work. Labview is a bit tricky due to the order of evaluation of things.

**Comment by RalphPang** [comment]
I have discovered more symptom by downloading the Refpropmini version 10.
After installation of Refprop mini I substituted "Fluids" and "Mixture" folders since the default folder doesn't contains the mixture I want to use, then I follow the procedure below: 
Fisrtly,I opened Refprop mini and go to Substance -> Predefined mixture as below figure:
![image](https://github.com/user-attachments/assets/4bf6f66f-0a83-4098-9a8a-85bbc6f1a843)
After that I opened any fluids in the list but it pops up an error as below:
![image](https://github.com/user-attachments/assets/6d2d6304-03ae-4704-94ff-ce1349054562)
I looked at the folder fluids and I'm pretty sure the R125.FLD is exist, then I copied the Fluids folder and all fluids under Mixture folder but no help.
Can you advise based on my findings?
Thank you so much

**Comment by RalphPang** [comment]
> I would recommend to check the calculations outside of Labview in something like Python to ensure you know how things should work. Labview is a bit tricky due to the order of evaluation of things.

I've tried Python but my skill set is quiet low, didn't figure out any of the folders under wrapper, sorry

**Comment by RalphPang** [comment]
> I have discovered more symptom by downloading the Refpropmini version 10. After installation of Refprop mini I substituted "Fluids" and "Mixture" folders since the default folder doesn't contains the mixture I want to use, then I follow the procedure below: Fisrtly,I opened Refprop mini and go to Substance -> Predefined mixture as below figure: ![image](https://private-user-images.githubusercontent.com/84825144/378126648-4bf6f66f-0a83-4098-9a8a-85bbc6f1a843.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNzgzNDUsIm5iZiI6MTcyOTM3ODA0NSwicGF0aCI6Ii84NDgyNTE0NC8zNzgxMjY2NDgtNGJmNmY2NmYtMGE4My00MDk4LTlhOGEtODViYmM2ZjFhODQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDIyNDcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNGQxNjNlZmEwY2QwYTU5Nzg2YmM4ZWM1Y2QzZmQ5YjUyMzkzNTU1MTI5Yjc2OTU5ZGQ3ODUwMmE3OWRiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Es8pB_HJq1fvOdP_gIZLDzgTGUm7wwMXcwRjssoqLd4) After that I opened any fluids in the list but it pops up an error as below: ![image](https://private-user-images.githubusercontent.com/84825144/378127222-6d2d6304-03ae-4704-94ff-ce1349054562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNzgzNDUsIm5iZiI6MTcyOTM3ODA0NSwicGF0aCI6Ii84NDgyNTE0NC8zNzgxMjcyMjItNmQyZDYzMDQtMDNhZS00NzA0LTk0ZmYtY2UxMzQ5MDU0NTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDIyNDcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYjQ2MzQ3ODMwNTJmMWM1YTc2MjE4YTU0NzYwNWE1NTY4MTdiMmE3OGQwNDJiNTVjMWU1NTE1NjhhM2QzNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6en3RuLkwkNn6YxtU4RVvg5PMqPsifGPkcMBIPtLXEM) I looked at the folder fluids and I'm pretty sure the R125.FLD is exist, then I copied the Fluids folder and all fluids under Mixture folder but no help. Can you advise based on my findings? Thank you so much

Sorry I discovered in the link I downloaded Refprop10 mini there is a link to download the exe file to replace the original exe file, after replacement the original error disappeared and after I goto Calculate -> Saturation tables -> follow default setup click OK twice the error message pops up as below:
![image](https://github.com/user-attachments/assets/e1f830ac-4daf-4396-9581-bea8d2e5c046)
If I click yes or yes to all the table appears, is this error considered an issue for LabVIEW?

**Comment by nist-aharvey** [comment]
By "Convert from P to T" I assume you are trying to find the saturation temperature associated with a pressure, or vice versa?  That is not a unique answer for a mixture like it is for a pure fluid, so talking about "converting" in that way is not meaningful.  You get a different answer depending on whether you ask for the bubble point (boiling point of saturated liquid) or the dew point (condensation point of saturated vapor). Depending on what functions you are trying to call in LabView (I don't know anything about LabView), that may be part of your problem with mixtures.

But I also note that the two sample calculations in your original example do not make sense. You are asking for calculations in SI units.  The first example, you have set the pressure to 40, which means 40 MPa.  This is far above the mixture critical pressure, so there is no corresponding saturation temperature.  Then in the second one you have set the temperature to 55 K, which is far below freezing (probably why you get an error about a melting equation).
So you might try these again with reasonable inputs, like a pressure of 1 MPa or a temperature of 250 K.

**Comment by RalphPang** [comment]
> By "Convert from P to T" I assume you are trying to find the saturation temperature associated with a pressure, or vice versa? That is not a unique answer for a mixture like it is for a pure fluid, so talking about "converting" in that way is not meaningful. You get a different answer depending on whether you ask for the bubble point (boiling point of saturated liquid) or the dew point (condensation point of saturated vapor). Depending on what functions you are trying to call in LabView (I don't know anything about LabView), that may be part of your problem with mixtures.
> 
> But I also note that the two sample calculations in your original example do not make sense. You are asking for calculations in SI units. The first example, you have set the pressure to 40, which means 40 MPa. This is far above the mixture critical pressure, so there is no corresponding saturation temperature. Then in the second one you have set the temperature to 55 K, which is far below freezing (probably why you get an error about a melting equation). So you might try these again with reasonable inputs, like a pressure of 1 MPa or a temperature of 250 K.

You nailed
