### ISSUE TITLE
[PQFLSH error  5] one or more inputs are out of range

### ISSUE THREAD

**Issue by raffcil** [usnistgov/REFPROP-wrappers#626]
Hi everyone, I think that I correctly managed to install the refprop 9.1 wrapper for MATLAB on my macbook (intel). I followed [this](https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB) guide to do so. However, I cannot figure out how to make it work properly.
I get "[PQFLSH error  5] one or more inputs are out of range:  temperature > 1.5 x upper limit, T =  80.000 K, Tmax =  0.0000 K  pressure > 2 x upper limit, P = 0.50000 MPa, Pmax =  0.0000 MPa" or even sometimes matlab crashes. 
Any tought on how to resolve?

### Steps to Reproduce
1. RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('.../REFPROP');
2. RP.RPVersion()

ans = 

  Python str with no properties.

    9.1

3. RP.SETPATHdll('.../REFPROP');
4. r=RP.SETUPdll(int8(1),":FLUIDS:PROPANE.FLD",":FLUIDS:HMX.BNC","DEF");
5. RP.PQFLSHdll(500, 0, {1.0},int8(0));

**Actual behavior:** 
Code runs but the PQFLSHdlloutput gives all zeros, T=80K and this error in "herr"

### Versions

**REFPROP Version:** 9.1
**Operating System and Version:** Mac Os Sonoma 14.6.1
**Access Method:** Refprop wrapper via python on matlab

### Additional Information

<img width="244" alt="image" src="https://github.com/user-attachments/assets/938a782d-48c4-4027-bec5-57efef9ffd63">

Thanks for your precious help!

**Comment by ianhbell** [comment]
What is your ierr and herr when you do the SETUP call?

**Comment by raffcil** [comment]
Your speed in replying is something just insane.
Btw I checked the herr and it was: 

[SETUP error 101] error in opening file for component #  1 filename = (:FLUIDS:PROPANE.FLD).

I obviously switched back to propane.fld and now it's working. Thanks
