### ISSUE TITLE
Broken links: other third party wrappers

### ISSUE THREAD

**Issue by acjoven** [usnistgov/REFPROP-wrappers#63]
### Description

Broken links to updated third party wrappers linked to from trc.nist.gov website in README.md

* http://trc.nist.gov/refprop/LINKING/WERNICK.ZIP
* http://trc.nist.gov/refprop/LINKING/THELEN.ZIP

**Comment by acjoven** [comment]
You're correct: the path for the links is REFPROP-wrappers/wrappers/python/README.md

**Comment by ianhbell** [comment]
We are getting to the bottom of these links, but really, you should use my new Python wrapper; it is much, much easier to use.

**Comment by ianhbell** [comment]
Links removed, my new wrapper supercedes the older wrappers
