### ISSUE TITLE
Failing in calling the  subroutines in refprop.dll in VB.NET 

### ISSUE THREAD

**Issue by maxwellxuze** [usnistgov/REFPROP-wrappers#64]
``` VB(.NET)
Public Declare Sub SETUPdll Lib "refprop.dll" (i As Long, ByVal hfld As String, ByVal hfmix As String, ByVal hrf As String, ierr As Long, ByVal herr As String, ln1 As Long, ln2 As Long, ln3 As Long, ln4 As Long)
Public Declare Sub ABFL1dll Lib "refprop.dll" (a As Double, b As Double, x As Double, i As Long, ByVal ab As String, dmin As Double, dmax As Double, t As Double, p As Double, d As Double, ierr As Long, ByVal herr As String, ln1 As Long, ln2 As Long)
Public Declare Sub ABFL2dll Lib "refprop.dll" (a As Double, b As Double, x As Double, kq As Long, ksat As Long, ByVal ab As String, tbub As Double, tdew As Double, pbub As Double, pdew As Double, Dlbub As Double, Dvdew As Double, ybub As Double, xdew As Double, t As Double, p As Double, Dl As Double, Dv As Double, x As Double, y As Double, q As Double, ierr As Long, ByVal herr As String, ln As Long, ln2 As Long)
Public Declare Sub TPFLSHdll Lib "refprop.dll" (t As Double, p As Double, x As Double, d As Double, Dl As Double, Dv As Double, xliq As Double, xvap As Double, q As Double, e As Double, h As Double, s As Double, Cv As Double, Cp As Double, w As Double, ierr As Long, ByVal herr As String, ln As Long)
Public Const MaxComps As Integer = 20
Public herr As String, hfmix As String, htyp As String
Public hrf As String
Public htype As String, hmix As String, hcomp As String
Public hfld As String, hmxnme As String, nc As Long = 1
Public x(0 To MaxComps) As Double, xmm(0 To MaxComps) As Double
Public xliq(0 To MaxComps) As Double, xvap(0 To MaxComps) As Double
Public xv(0 To MaxComps) As Double, rhov As Double, hv As Double
Public ierr As Long, kq As Long, kr As Long, nroot As Long, ix As Long
Public t As Double, p As Double, d As Double, Dl As Double, Dv As Double, q As Double, wm As Double
Public en As Double, h As Double, s As Double, Cv As Double, Cp As Double, w As Double
Public z As Double, hjt As Double, a As Double, g As Double, xkappa As Double, beta As Double, dPdD As Double, d2PdD2 As Double, dPdT As Double, dDdT As Double, dDdP As Double, d2PT2 As Double, d2PdTD As Double, spare3 As Double, spare4 As Double
Public b As Double, c As Double, de As Double, eta As Double, tcx As Double, hvap As Double
Public tmin As Double, tmax As Double, dmax As Double, pmax As Double
Public tc As Double, pc As Double, dc As Double
Public Tref As Double, pref As Double, hRef As Double, sRef As Double
Public f(0 To MaxComps) As Double, sigma As Double
Public k1 As Long, k2 As Long, k3 As Long
Public t1 As Double, p1 As Double, D1 As Double
Public t2 As Double, p2 As Double, d2 As Double
Public t3 As Double, p3 As Double, d3 As Double
Public wmm As Double, ttrp As Double, tnbpt As Double, Zc As Double, acf As Double, dip As Double, Rgas As Double

Private Sub 计算_Click(sender As Object, e As EventArgs) Handles 计算.Click
        Dim nc As Integer = 1
        hfld = "C:\Program Files (x86)\REFPROP\fluids\WATER.FLD"
        hfmix = "C:\Program Files (x86)\REFPROP\fluids\hmx.bnc"
        hrf = "DEF"
        t = 300
        p = 10000
        SETUPdll(nc, hfld, hfmix, hrf, ierr, herr, 10000, 255, 3, 255)
        Call TPFLSHdll(t, p, x(1), d, Dl, Dv, xliq(1), xvap(1), q, en, h, s, Cv, Cp, w, ierr, herr, 255&)
        TextBox2.Text = d
End Sub`
```

### Description

I am a newer in VB(.NET). 
I failed in calling the  subroutines in refprop.dll in VB.NET 
The problem happended in this sentence:
`  Call SETUPdll(nc, hfld, hfmix, hrf, ierr, herr, 10000, 255, 3, 255)`

And I do not know how to solve this problem

**Expected behavior:** call the  subroutines and get the value of 'd' in the textbox
**Actual behavior:** 
`SETUPdll(nc, hfld, hfmix, hrf, ierr, herr, 10000, 255, 3, 255)`
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt

### Versions

**REFPROP Version:** 9.0  
**Operating System and Version:** win 10
**Access Method:** VB(.NET)

**Comment by ianhbell** [comment]
All strings need to be padded with spaces to the correct length (herr, hfld, etc.) as specified in the PASS_FTN.FOR file.  Please see the VBA code that comes in the Excel spreadsheet to see how to properly call the DLL from VBA; it's the same procedure in .NET frameworks.
________________________________

**Comment by maxwellxuze** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thanks for your update on the issues! You're really a good author and teacher!I will have a try!
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                570441171
                            
                    
                        
                            
                                    570441171@qq.com
 

    On 9/26/2018 01:27，Eric Lemmon<notifications@github.com> wrote： 


I have been working on new sample code that shows how to call the Refprop routines through VB6.  Perhaps this preliminary code can help with the VB.NET language?  The code is attached in the sample.txt file.




Attribute VB_Name = "Module1"

DefDbl A-H, O-Z

DefLng I-N

Const ncmax = 20   'Maximum number of components in the mixture (do not change unless the Refprop Fortran code is also changed with the same number in the CONSTS.INC file)

Const iPropMax = 200 'Number of output properties available in ALLPROPS (also do not change).



Private Declare Sub REFPROPdll Lib "REFPROP.DLL" (ByVal hFld As String, ByVal hIn As String, ByVal hOut As String, iUnitNumb As Long, iMass As Long, iFlag As Long, a As Double, b As Double, zm As Double, Output As Double, ByVal hUnits As String, iUnits As Long, x As Double, y As Double, x3 As Double, q As Double, ierr As Long, ByVal herr As String, ln1 As Long, ln2 As Long, ln3 As Long, ln4 As Long, ln5 As Long)



Sub Example()



'     Example program that uses the routines in REFPROP.

'

'     Refprop uses a default set of units, these being:

'       K, kPa, mol/dm^3, mole fraction, J/mol, J/mol-K, m/s, uPa-s, W/m-K, and N/m

'

'     Refprop 10 comes with two new subroutines, labeled as ALLPROPS and REFPROP,

'       that allow the user to access nearly all properties in the Refprop program.

'       One additional routine allows the setting of options and flags to change

'       how the program works.  The details of these routines are given at the top

'       of the file REFPROP.FOR for the first two, and at the bottom for the last one.

'       Examples are given below.

'

'     The examples here are split into two pieces.  The first shows the new method

'       to obtain properties.  The second shows the old method.  The method to use

'       depends on your needs.  For simple calculations, then the use of the

'       techniques in the first method works very well.  For applications

'       that require heavy computational needs, the second method will be faster

'       by calling directly the routines needed due to the higher overhead required

'       in the ALLPROPS and REFPROP routines to search for the correct routines

'       to call for each calculation.

'

      Dim hFld As String, hIn As String, hOut As String, hUnits As String, herr As String

      Dim Output(iPropMax) As Double, Z(ncmax) As Double, x(ncmax) As Double, y(ncmax) As Double, x3(ncmax) As Double

      Dim ymass(ncmax) As Double, ymole(ncmax) As Double

      o = 1000#





'***New methods for obtaining properties from the REFPROP and ALLPROPS subroutines***  (see notes at top of file)



'...Get the DLL number of the REFPROP DLL.

      Call REFPROP(" ", " ", "DLL#", 0, 0, 0, 0, 0, Z, Output, hUnits, q, ierr, herr)



'...When Refprop was installed, an environmental variable called RPPrefix was setup so that Refprop can find

'   the fluid files.  To manually set the path to these files, use the following lines.

'     Call REFPROPdll ("c:\Program Files (x86)\Refprop","Path"," ",

'    &       0,0,0,0d0,0d0,z,Output,hUnits,iUnit,x,y,x3,q,ierr,herr)

'     if (ierr>0) then msgbox herr



'...Load nitrogen as a pure fluid (this can also be done in the call to REFPROP).

      'Call SETFLUIDS("nitrogen", ierr)

      'Call ERRMSG(ierr, herr)  'If the error message is desired, call ERRMSG with the value of ierr returned from the line above.

      If (ierr > 0) Then MsgBox herr



'...Calculate the density, isobaric heat capacity, viscosity, and thermal conductivity at a given

'...temperature and pressure with the REFPROP subroutine.

      T = 300 'K

      P = 1   'MPa

      iU = 2  'Units in mass SI (see the REFPROP.FOR file for a complete list of the unit systems available).

      Call REFPROP("nitrogen", "TP", "D,Cp,Vis,Tcx", iU, iMass, 0, T, P, Z, Output, hUnits, q, ierr, herr)

      If (ierr > 0) Then MsgBox herr

      'write (*,1000) 'T,P,D,Cp,Vis,Tcx    ",ierr,iU,T,P,Output(1:4)

      D = Output(1)   'Density - kg/m^3

      Cp = Output(2)  'Cp - kJ/(kg-K)

      eta = Output(3) 'Viscosity - uPa-s

      tcx = Output(4) 'Thermal conductivity - mW/(m-K)



'...Calculate the specific volume at a given temperature and pressure with the REFPROP1 subroutine

'...in English units and composition in mass fractions for 70% methane and 30% ethane.

      'Call SETFLUIDS("methane;ethane", ierr)

      'If (ierr > 0) Then MsgBox herr

      Z(1) = 0.7

      Z(2) = 0.3

      iMass = 1 'Mass fractions for composition

      iU = 5  'Flag to use English units

      T = 50  'F

      P = 100 'psia

      Call REFPROP("methane;ethane", "TP", "V", iU, iMass, 0, T, P, Z, Output, hUnits, q, ierr, herr) 'Volume in ft^3/lbm

      v = Output(1)

      If (ierr > 0) Then MsgBox herr

      'write (*,1000) "T,P,V               ",ierr,iU,T,P,V



'...Calculate other thermodynamic properties with a call to ALLPROPS now that

'...the temperature and density are known.  Use molar SI as input units.

      'Call REFPROPdll1(" ", "m", 0, iMass, 0#, 0#, z, wm, q, ierr, herr) 'Get the molar mass.

      Call REFPROP("F", "K", "UNITCONV_T", 0, 0, 0, T, 0#, Z, Output, hUnits, q, ierr, herr)  'Convert the temperature from F to K.

      T = Output(1)

      Call REFPROP("ft^3/lbm", "mol/dm^3", "UNITCONV_D", 0, 0, 0, v, wm, Z, Output, hUnits, q, ierr, herr)  'Convert the volume in ft^3/lbm to density in mol/dm^3.

      D = Output(1)



      'iU = 1   'Molar SI

      'iMass = 1 'Mass fractions

      'hOut = "Z,s,Cv,Cp,W"

      'Call ALLPROPS(hOut, iU, iMass, 1, t, d, z, Output, hUArray, iUArray, i, herr)

      'If (i > 0) Then MsgBox herr

      'write (*,1000) 'D,Z,s,Cv,Cp,w     ",ierr,iU,D,Output(1:5)

      'zz = Output(1) 'Compressibility factor

      's = Output(2) 'Entropy - J/(mol-K)    This entropy will not match that from the GUI because the reference state applied to the mixture is set differently.  See the call to SETREF below to change this.

      'w = Output(5) 'Speed of sound - m/s



'...Calculate the liquid saturation pressure and the mole and mass fractions in the vapor phase.

      'Call SETFLUIDS("methane;ethane;propane", ierr)  'Either this or the call to REFPROP in the next section is valid.

      iU = 2 'Flag to use mass SI units, for SI units with celsius, use 3.

      iMass = 1

      T = 200 'K

      Z(1) = 0.8

      Z(2) = 0.15

      Z(3) = 0.05

      hOut = "P,Dliq,Dvap,xmassliq,xmassvap,xmoleliq,xmolevap" 'The string "xmassvap" is the y mass fractions because of the "vap" appended to the end.  The string "xmass" simply means composition on a mass basis.

      Call REFPROP(" ", "Tliq", hOut, iU, iMass, 0, T, 0#, Z, Output, hUnits, q, ierr, herr) 'The liquid and vapor mole fractions are returned in the x and y arrays.  Note:  Always mole fractions for x, y, and x3.

      If (ierr > 0) Then MsgBox herr

      P = Output(1)  'MPa

      Dl = Output(2) 'Saturated liquid density - kg/m^3

      Dv = Output(3) 'Saturated vapor density  - kg/m^3

      'ymass(1:3)=Output(7:9)     'Because the xmass and xmole inputs to REFPROP have more than one output, the Output() array does not line up with the inputs.  Thus, the outputs for xmassliq are in slots 7 to 9, for xmassvap in 10 to 12, etc.

      'ymole(1:3)=Output(13:15)   'The ymole outputs are in slots 13 to 15, but are actually the same as the values returned in the array y in the call to the REFPROP routine.  This example shows how the pieces are linked together.

      'write (*,1000) 'P,Dl,Dv,ymass     ",ierr,iU,P,Dl,Dv,ymass(1:3)

      'write (*,1000) '  xmole,ymole     ",ierr,iU,x(1:3),ymole(1:3)    'The x() array values returned from the REFPROP routine are the same as those in slots 10 to 12 for the xmoleliq string, and in this example are also the same as the input array z() except on a molar basis.



'...Setup a mixture of natural gas components and calculate the enthalpy given pressure and entropy.

      D = 2     'kg/m^3

      iU = 3    'Use mass SI with T in Celsius

      iMass = 0 'Use molar composition

      Z(1) = 0.7

      Z(2) = 0.2

      Z(3) = 0.1

      Call REFPROP("methane;ethane;propane", "Dliq", "T,P,S,H,W", iU, iMass, 0, D, 0#, Z, Output, hUnits, q, ierr, herr)

      If (ierr > 0) Then MsgBox herr

      'write (*,1000) 'D,T,P,S,H,W       ",ierr,iU,D,Output(1:5)

      T = Output(1) 'C

      P = Output(2) 'MPa

      h = Output(4) 'kJ/kg



'...Setup the predefined mixture R410A.MIX and calculate the liquid state at 300 K and the properties of the vapor state in equilibrium with the liquid state.

      T = 300    'K

      iU = 2     'Use mass SI

      iMass = 1  'Use mass composition

      Call REFPROP("R410A.MIX", "Tliq", "Pliq,Dliq,Dvap,xmassliq(1),xmassliq(2),xmassvap(1),xmassvap(2)", iU, iMass, 0, T, 0#, Z, Output, hUnits, q, ierr, herr)

      If (ierr > 0) Then MsgBox herr

      P = Output(1) 'MPa

      Dliq = Output(2): Dvap = Output(3)   'kq/m^3    Note carefully:  Dvap is not at the input composition (50/50 R32/R125), but at the equilibrium composition given by y1 and y2 below.

      X1 = Output(4): X2 = Output(5)       'These should be 50 and 50, the liquid composition for this state.

      Y1 = Output(6): Y2 = Output(7)       'These will be the equilibrium composition in the vapor phase.



      'For additional calculations, there is no need to send the fluid file name again.

      Call REFPROP("", "TP", "D", iU, iMass, 0, T, P, Z, Output, hUnits, q, ierr, herr)



      End





End Sub



Sub REFPROP(hFld As String, hIn As String, hOut As String, iUnits As Long, iMass As Long, iFlag As Long, a As Double, b As Double, Z() As Double, Output() As Double, hUnits As String, q As Double, ierr As Long, herr As String)

Dim hFld2 As String * 10000, hIn2 As String * 255, hOut2 As String * 255, hUnits2 As String * 255, herr2 As String * 255

Dim iUnits2 As Long, iMass2 As Long, iFlag2 As Long, iUCode2 As Long, ierr2 As Long

Dim a2 As Double, b2 As Double, z2(ncmax) As Double, x(ncmax) As Double, y(ncmax) As Double, x3(ncmax) As Double, q2 As Double, Output2(iPropMax) As Double



  hFld2 = hFld: hIn2 = hIn: hOut2 = hOut

  iUnits2 = iUnits: iMass2 = iMass: iFlag2 = iFlag

  a2 = a: b2 = b

  For i = 1 To ncmax: z2(i) = Z(i): Next

  Call REFPROPdll(hFld2, hIn2, hOut2, iUnits2, iMass2, iFlag2, a2, b2, z2(1), Output2(1), hUnits2, iUCode2, x(1), y(1), x3(1), q2, ierr2, herr2, 10000&, 255&, 255&, 255&, 255&)

  For i = 1 To iPropMax: Output(i) = Output2(i): Next

  hUnits = hUnits2

  iUCode = iUCode2

  hUnits = hUnits2

  q = q2

  ierr = ierr2

  herr = herr2

  If Trim(hFld2) <> "" Then

    For i = 1 To ncmax: Z(i) = z2(i): Next

  End If



End Sub









—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by EricLemmon** [comment]
Can this issue be closed now?
