### ISSUE TITLE
REFPROP 10 for Excel 2016 gives #VALUE

### ISSUE THREAD

**Issue by imanlas** [usnistgov/REFPROP-wrappers#65]
Hi,

I am trying to setup REFPROP 10 for Excel  for some colleagues. It is working perfectly for all of them except one. She always gets #VALUE when trying to calculate a thermodynamic property. Here I am going to elaborate the problem:
- She has WINDOWS 10 64-bit similar to some of us, but she has OFFICE 2016 in contrast to us which we all have OFFICE 365.
- Debugging the Macro, I see that the code stops on the first call to a PERFPROP subroutine.
- As noted in the beginning of "Refprop10Code" module the problem possibly links to the disconnection of Excel and DLL. So, I have tried/checked the followings:
1) Scan her system to ensure that she has only one REFPROP.DLL which is located under the installation directory (c:\Program Files (x86)\REFPROP)
2) Check the user and system environmental variables and observe that the REFPROP installation directory is included.
3) Give the address of the REFPROP installation, in the beginning of the macro.
4) Copy the REFPROP DLL under system32 Windows folder. 
5) Run Excel as administrator
 
- Finally, I should note that I have followed all the sub steps under installations and tips in this link:
https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Excel

Unfortunately, none of these attempts are not helping!

Cheers

**Comment by ianhbell** [comment]
Is it possible that her Excel is 64-bit while the others are all 32-bit?  And therefore, you should be searching for REFPRP64.DLL, and deleting any other copies of that that you find, rather than REFPROP.DLL.

________________________________

**Comment by EricLemmon** [comment]
I’ve seen cases where updates had not been done on a machine (make sure you go to “Windows Update” as well to be sure that all important updates have been done) or where the machine simply needed to be rebooted.  Give this a try as well as Ian’s suggestion and let us know if the problem has been fixed.  If not, please email me directly as I have another possible route we can try:  Eric.Lemmon@nist.gov

**Comment by imanlas** [comment]
Hi again,
After updating Windows and Microsoft Office, the problem is solved :) Thanks for the tips.

Cheers
Ps: She has also Excel 32-bit.
