### ISSUE TITLE
the Results have some differences between python and refprop version10.0

### ISSUE THREAD

**Issue by lxh3251335** [usnistgov/REFPROP-wrappers#66]
### Description
The results checked from App Refprop(version 10) are some differences with python wrapper's for predefined mixtures

Use python wrapper,I called the REFPROPdll routine,Calculated properties include h and s.

### Steps to Reproduce

1. [First Step] define RP (call REFPROPFunctionLibrary)
2. [Second Step] set fluids: SETMIXdll
3. [and so on...] call REFPROPdll

**Expected behavior:** the same results 

**Actual behavior:** the difference results

### Versions

**REFPROP Version:10 
**Operating System and Version:Windows 10 
**Access Method: Python 

### Additional Information

e.g.

hIn is "TQ" and T=273.15,Q=1
hFld = 'R449A.MIX'
z (molar fractions) = [0.407364566995509, 0.179481207732065, 0.193480840388364, 0.219673384884062, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 

python wrapper's results: h=402.4587kJ/kg, s=1.868437 kJ/kg K

Refprop version10.0 results: h=398.69kJ/kg, s=1.7353 kJ/kg K

**Comment by EricLemmon** [comment]
Take a look at the following website and see if it answers your questions:

https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences
