### ISSUE TITLE
REFPROP10: PHFLSH error 16 for a specific case of WATER

### ISSUE THREAD

**Issue by imanlas** [usnistgov/REFPROP-wrappers#67]
Hi,

We got an unexpected error (PHFLSH error 16) in calculating a specific case using REFPROP10 interface:

Fluid: WATER 
Pressure: 34 bara
Enthalpy: 354.45 kJ/kg (Use the default reference state)

The same  case can be calculated without a problem using (Pressure, Temperature), (Pressure, Int. Energy), (Pressure, Entropy), (Pressure, Density) and ... as inputs.

Here I have attached the snapshot:

![refprop_bug](https://user-images.githubusercontent.com/22888594/46394461-73f64880-c6e9-11e8-92fd-6645287e9af5.PNG)
.

**Comment by EricLemmon** [comment]
This bug has now been fixed, if you would like an updated DLL, please contact us directly (eric.lemmon@nist.gov)
