### ISSUE TITLE
Get different Results when we calculate the molar mass with different methods

### ISSUE THREAD

**Issue by lxh3251335** [usnistgov/REFPROP-wrappers#68]
Mixture name:R448A

The first method：
use refprop v10.0.
![image](https://user-images.githubusercontent.com/25289417/46525765-10be0f00-c8bf-11e8-8c7e-fe4660a1a53b.png)
the result of Molar Mass: **86.283** kg/kmol

The second method:
use subroutine INFOdll([[0.431218201988559, 0.186914131481992, 0.151319256485899, 0.177586673617217, 0.0529617364263329, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])

the result of Molar Mass: **114.0416** kg/kmol

INFOdlloutput(wmm=114.0416, Ttrp=169.0, Tnbpt=254.177, Tc=382.513, Pc=3634.9, Dc=4.29, Zc=0.26641270849539084, acf=0.313, dip=1.27, Rgas=8.3144598)

**Comment by lxh3251335** [comment]
can you help me slove the problem?@ianhbell

**Comment by EricLemmon** [comment]
Subroutine INFOdll returns the properties of the pure fluid only.  In this case the molar mass is the value of R1234ze.  If you go to Substance/Fluid Search, you can use that menu to input a molar mass and see what fluids are in a certain range as I did in the picture below.  To get the properties of the mixture, you need to use other routines such as WMOLdll, as detailed in the manual on page 131 here:
https://trc.nist.gov/refprop/REFPROP.PDF
But a much better way to use the program would be through subroutine REFPROPdll described on page 45.  That one will do everything for you, and you will not need any other routine documented in the help file to obtain all outputs available in the program.  This even includes the use of different unit systems or the ability to input/output compositions on either a molar or mass basis.

![image](https://user-images.githubusercontent.com/42392984/46578085-b7cfa300-c9b2-11e8-95f8-8cdd8ece5f43.png)

**Comment by lxh3251335** [comment]
@EricLemmon now,I try to use the Subroutine  TPFLASHdll or ABFLASHdll to caluculate the common properties,because it has a faster calculation speed.
first, I define a RP,second,set a fluid(purefluids or premixfluids),third use TPFLASHdll or ABFLASHdll to return the properties.
Is it a better method?

**Comment by ianhbell** [comment]
@lxh3251335 That's right!  Can you please post your running code so I can see if you are missing anything?  Ideally you do the setup only once; that's quite slow.  Then pass around your RP instance where you need it.

**Comment by lxh3251335** [comment]
@ianhbell have you received my code files? I have answer your emails with accessory

**Comment by ianhbell** [comment]
I didn't get anything...  If it is just a small script, better to paste it in the github web interface.

**Comment by ianhbell** [comment]
Is there any update to this issue? If not, I think we can close it.
