### ISSUE TITLE
How to define/change reference sate?

### ISSUE THREAD

**Issue by hohiroki** [usnistgov/REFPROP-wrappers#7]
Information on reference state refer to "the reference state can be set manually by specifying values of the enthalpy (h) and entropy (s) at arbitrary values of temperature (T) and pressure (P)".  How to define/change reference state by 'refpropm'.

**Comment by ianhbell** [comment]
What information are you referring to?  In principle you could call the SETREF function to do what you request.  What language are you calling REFPROP from?

**Comment by hohiroki** [comment]
Thanks in advance.

 I am using Matlab as complier calling REFPROP. The input code- "refpropm('h', 'T', 300, 'P', 2400, 'nitrogen')" , will get an defult reference state enthalpy retuen value. In oder to avoid nagetive enthalpy, I want to specify the reference state value h=100, s=10, at T=70, P=0.038545(or x=0). 

From the "refpropm.m", there are some commetn mentioned that 
"% Use the following line to calculate enthalpies and entropies on a reference state
% based on the currently defined mixture, or to change to some other reference state.
% The routine does not have to be called, but doing so will cause calculations
% to be the same as those produced from the graphical interface for mixtures.
%   [href dummy dummy dummy dummy dummy ierr2 errTxt] = calllib(libName, 'SETREFdll', href, 2, z, 0, 0, 0, 0, 0, 32*ones(255,1), 3, 255);".
But it seemingly doesn't work, when i try specify the reference value.

**Comment by ianhbell** [comment]
Well, you should read the docs for SETREF in the manual.txt file in the fortran directory of your installation to figure out how to call SETREF appropriately.

What does "seemingly doesn't work" mean?  Please see https://pages.nist.gov/REFPROP-docs/#getting-help
