### ISSUE TITLE
Toluene properties not calculating in Matlab Wrapper

### ISSUE THREAD

**Issue by GaneshDoiphode** [usnistgov/REFPROP-wrappers#72]
Using REFPROP 10 (DLL version 10.0.0.55)

I am trying to calculate Toluene properties (P= 0.01 MPa and Q= 0), it gives me
r= RP.REFPROPdll('Toluene', 'PQ', 'T, H, S', int8(3), int8(1),int8(0),0.01,0,{1.0});
o = double(r.Output);
T13= o(1) 
h13= o(2) 
s13= o(3) 

T13 =
    -9999990
h13 =
    -9999990
s13 =
    -9999990

However, REFPROP GUI does give me appropriate answers. 
![image](https://user-images.githubusercontent.com/43588320/48025566-d213b280-e111-11e8-95b0-397328cbe8cc.png)

Please, let me know where am I making mistake or how to resolve this problem. Thank you.

**Comment by ianhbell** [comment]
Must be a unit system issue...  You did read the docs about calling GETENUMdll rather than hard-coding the unit system, right?


What are herr and ierr?

________________________________

**Comment by GaneshDoiphode** [comment]
Hello Ian, 

Honestly speaking I am fairly new to the REFPROP DLL function environment and I do not find enough examples to properly use GETNUMdll. Where do I find such examples? 

Since I am concerned about the unit system, I used following SILLY trials with flag as 1, 

herr= 'error';

>> r= RP.GETENUMdll(1, 'ENTROPY', a, b,herr, 255, 255)
No appropriate method, property, or field 'GETENUMdll' for class 'py.ctREFPROP.ctREFPROP.REFPROPInstance'.
 
>> r= RP.GETENUMdll(1, 'Temperature', a, b,herr, 255, 255)
No appropriate method, property, or field 'GETENUMdll' for class 'py.ctREFPROP.ctREFPROP.REFPROPInstance'.
 
>> r= RP.GETENUMdll(1, 'TEMPERATURE', a, b,herr, 255, 255)
No appropriate method, property, or field 'GETENUMdll' for class 'py.ctREFPROP.ctREFPROP.REFPROPInstance'.

Where can I get details about the proper use of these functions? Please help.

**Comment by ianhbell** [comment]
The GETENUMdll function is used only to get the enumerated values, in this case the unit system.  This function was added in REFPROP 10, and is not present in REFPROP 9.x, which is likely why you see this error.

Did you check out the tutorial for Python : https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb ?  That includes quite a few more illustrative examples.
