### ISSUE TITLE
RP.RPVersion() returns version ******

### ISSUE THREAD

**Issue by scpowers** [usnistgov/REFPROP-wrappers#73]
### Description

After following the installation instructions, I call RP.RPVersion() and the output shows "******" where "10.0" should appear. 

### Steps to Reproduce

1. Follow install instructions through end. 

**Expected behavior:** [What you expect to happen]
When calling RP.RPVersion(), the output should show "10.0". 

**Actual behavior:** [What actually happens]
When calling RP.RPVersion(), the output shows "******".

### Versions

**REFPROP Version:** 10.0  
**Operating System and Version:** Windows 10 (64-bit)  
**Access Method:** MATLAB (via Python interface)

### Additional Information

![image](https://user-images.githubusercontent.com/20448418/48680894-fa5cd180-eb53-11e8-9885-0b196cd1b98c.png)

**Comment by EricLemmon** [comment]
This is a known bug in Refprop, please contact us directly (eric.lemmon@nist.gov) to obtain an updated DLL.
