### ISSUE TITLE
The out of memroy error in REFPROP10 with matlab

### ISSUE THREAD

**Issue by hushuoz** [usnistgov/REFPROP-wrappers#76]
### Description

We recently update REFPROP 9.1 to version 10 working with matlab 2015b via python interface in windows 10. but the out of memory error would happen when working.

For example, if we only call the database of REFPROP10 several times in one circle, it runs quite well. But if our program runs for thirty minutes or longer and frequently calls the database of REFPROP10, error seems to be common. But everything develops well if using REFPROP9.1. 

The error codes with REFPROP10 are recorded  below:

1.[SETUP error 101] Error in opening file for component 1: filename =WATER.fld in the path C:\Program Files\REFPROP\fluids\   

2.Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: unable to create new native thread

### Steps to Reproduce

creat numerous small matrix and frequently call database of REFPROP10
then it will be out of memory after about thirty minutes

### Versions

**REFPROP Version:** [REFPROP 10.0.0]  
**Operating System and Version:** [windows 10]  
**Access Method:** [matlab via python interface]  

### Additional Information

We tried the patch for version 10 and it solved the out of memory error that we were having with matlab2015b via the python interface.  Now everything works well in our caculation and your kind assistance on this is very much appreciated.

**Comment by TigR77** [comment]
I know this is closed but what was the patch? Was it v10.1? What is the best way to obtain it? I am also getting memory related MATLAB crashes with 10.0. Thanks.

**Comment by ianhbell** [comment]
Can you please email me at ian.bell@nist.gov<mailto:ian.bell@nist.gov> and I can send you a link to the patch and we can see if that fixes it?
