### ISSUE TITLE
Ammonia-Water properties trend conflict between GUI and REFPROP 10 MATLAB-wrapper 

### ISSUE THREAD

**Issue by GaneshDoiphode** [usnistgov/REFPROP-wrappers#77]
I have a pumping operation of an 'ammonia-water' mixture (43/57) with two states being 23(P= 4.7 bar, Q=0) and 24s(P=20.33 bar, S= s23). 

REFPROP GUI gives me the correct trends for enthalpy and temperature as 
**h_24s>h_23 and t_24s>t_23**

![image](https://user-images.githubusercontent.com/43588320/49288553-107d6280-f46f-11e8-8fc4-7b1ac2af7ed2.png)
in above screenshot, 
1=> state 23 and 2=> state 24s
  
BUT, while using wrapper 

RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files x86)\REFPROP\REFPRP64.DLL');
iUnit = RP.GETENUMdll(int8(0), 'SI WITH C').iEnum;
iMass = int8(1);
iFlag = int8(1);
r=RP.REFPROPdll('AMMONIA;WATER','PQ','T,H,S',iUnit,iMass,iFlag,0.47,0,[0.43, (1-0.43)]);
o = double(r.Output);
T23=o(1);h23=o(2); s23=o(3);
r=RP.REFPROPdll('AMMONIA;WATER','PS','T,H',iUnit,iMass,iFlag,2.033,s23,[0.43, (1-0.43)]);
o = double(r.Output);
T24s=o(1);h24s=o(2);

OUTPUT
T23=51.823933539475830 ; 
T24s= 50.699722198831864; 
h23=1.217643610473091e+02 ; 
h24s= 1.208914032733694e+02; 

gives opposite trend which is wrong  
**h_24s<h_23 and t_24s<t_23**

I understand the values are different because of reference states in GUI and DLL but the trend should remain similar, right? It making a huge difference in my code later.
  
Any suggestions?

REFPROP Version: 10.0.0.55
Operating System and Version: Win 10 64-bit

**Comment by ianhbell** [comment]
Did you get an ierr != 0 and/or a message in herr for either of your calls to REFPROPdll?  This seems like a bug I have to say.

**Comment by GaneshDoiphode** [comment]
I get 
**"ierr=0, herr="**

r = 

  Python REFPROPdlloutput with properties:

    Output
    hUnits
    herr
    iUCode
    ierr
    q
    x
    x3
    y
    z

    REFPROPdlloutput(z=array('d', [0.4162798932947176, 0.5837201067052824]), Output=array('d', [51.82393353947583, 121.76436104730905, 1.1507960726363786, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0]), hUnits='C', iUCode=1, x=array('d', [0.43, 0.5700000000000001, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), y=array('d', [0.9875649237494771, 0.012435076250522868, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), x3=array('d', [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), q=0.0, ierr=0, herr='')

**Comment by ianhbell** [comment]
Unfortunately @EricLemmon won't be able to look into this right now, but we'll make sure to resolve this as soon as we can.  We've been getting a number of reports of issues with ammonia + water, and some are to be expected, but it does seem that there are a few bugs hiding out for ammonia + water.

**Comment by GaneshDoiphode** [comment]
Any update over this bug?

**Comment by EricLemmon** [comment]
It is possible that you have another ammonia.fld, water.fld, or hmx.bnc file on your machine that is not from version 10. Can you do a full system search looking for each of these files (also look for Refprop.dll) and get rid of anything that is not in your Refprop directory? Be sure to search Windows, System, and hidden files to find them all.

**Comment by GaneshDoiphode** [comment]
Eric,

Apart from Refprop directory, I found ammonia.fld, water.fld and hmx.bnc present in Ansys Inc directory. I do not feel good about deleting these files from Ansys directory. 

What next should I do?

**Comment by GaneshDoiphode** [comment]
Any update, Eric?

Also. I have one more question,

how do I find composition of Ammonia-Water mixture when 3 other inputs are given?
inputs: P= 1.5554 Kpa, T= 90 C  and Q= 0

(If possible, please provide the syntax that can be used in Matlab)

**Comment by EricLemmon** [comment]
If Q is zero, then the composition is the same as the overall bulk composition.  Are you using qualities between 0 and 1?  If so, Ian can provide the syntax.  

Is everything else working now?

**Comment by EricLemmon** [comment]
Can this issue be closed now?
