### ISSUE TITLE
Transport property lookup in Excel for aqueous solutions fails silently

### ISSUE THREAD

**Issue by ckm47** [usnistgov/REFPROP-wrappers#79]
### Description

Custom mixtures (ie ethylene glycol and water 50/50 by vol) with water do not allow calculation of transport properties when molar mass of water is greater than 5%. However, excel property lookup fails silently and produces a value.

### Steps to Reproduce

1. Create a custom mixture text file for ethylene glycol/water 
```
EGW50
0 0 0 0
2
EGLYCOL.FLD
WATER.FLD
0.244032
0.755968
0
```
2. Call a lookup for viscosity from excel
```
refprop("VIS","EGW50.MIX","PT","C",0.101325,25)
```
3. Function will produce a numerical output, even though the same lookup within the desktop app produces an error message.

### Versions

**REFPROP Version:** 10 
**Operating System and Version:** Windows 10 Professional 
**Access Method:** Excel and Refprop Desktop

### Additional Information
![image](https://user-images.githubusercontent.com/7969869/49553973-fef0ec00-f8ae-11e8-9c77-928a11a0666a.png)

**Comment by ianhbell** [comment]
Thanks for the report.  This is a bug that we should be able to fix.

**Comment by ianhbell** [comment]
P.S. I modified your post to fix the blocks  (backticks instead of quotes)

**Comment by NickAtNight2017** [comment]
Is this one fixed then?  

I get this error in the Wizard
  #[TRNPRP error 541] Transport equations are not available for mixtures with water at molar concentrations greater than 5%.

**Comment by ianhbell** [comment]
Nope, this one needs the magical touch of Eric Lemmon, he’s the Excel guru amongst us.

**Comment by EricLemmon** [comment]
I cannot get an instance where the error message does not occur.  It may be possible that some of the fixes we have applied for other bugs have also fixed this one.

**Comment by EricLemmon** [comment]
Has this issue been resolved?  If so, could you close it?
