### ISSUE TITLE
Issue with loadlibrary

### ISSUE THREAD

**Issue by wesleykimmel** [usnistgov/REFPROP-wrappers#8]
I'm having trouble getting the program to work. 
I've had it working in the past on a past computer and on my current computer by adding a few extra paths  to redundant directories into Matlab. After restarting my computer, the following errors reappeared while trying to use the program. I made sure to follow the instructions and get rid of the redundant paths that I was using and that hasn't helped. 

>>refpropm('T','P',101.325,'Q',0,'WATER')
Error using loadlibrary
Too many input arguments.
Error in ==>@()rp_proto64(BasePath) at 211
There was an error running C:\Program Files (x86)\REFPROP\refpropm.m.
Run @()rp_proto64(BasePath) from the command line to reproduce the error and fix it.

Error in refpropm (line 227)
    [notfound,warnings]=loadlibrary(strcat(BasePath,dllName),prototype,'alias',libName);

Caused by:
    Error using rp_proto64
    Too many input arguments.

Thanks for the help,
Wes

**Comment by wesleykimmel** [comment]
If I put refpropm.m into my working directory, the following error message appears, if that helps at all. 

 refpropm('T','P',101.325,'Q',0,'WATER')
Error using calllib
Method was not found.

Error in refpropm (line 262)
        [nc path hmix href ierr errTxt] = calllib(libName,'SETUPdll',numComponents,path,hmix,href,0,32*ones(255,1),10000,255,3,255);

**Comment by ianhbell** [comment]
I've been having a lot of problems with this sort of thing with MATLAB.  The only approach that seems to work is:
1) Uninstall REFPROP, delete all traces of REFPROP you can find on your computer.  Remove the REFPROP installation folder, remove any files that are refpropm (refpropm.m, refpropm.mexw32, etc.)
2) Install REFPROP, apply the 9.1.1 patch
3) Follow very carefully the MATLAB installation instructions, doing exactly what they recommend.
