### ISSUE TITLE
Refprop in matlab 2012b

### ISSUE THREAD

**Issue by hermez19** [usnistgov/REFPROP-wrappers#80]
Hi, I bought REFPROP 10 and currently I have MATLAB 2012b. I tried to wrapper REFPROP to MATLAB through Legacy (https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB/legacy)
However an issue shows up, I look into the issues and try to solve with #29 (https://github.com/usnistgov/REFPROP-wrappers/issues/29) however another issue appears. I'm thinking about using the python wrapper but I don't know if MATLAB 2012b can be wrapper REFPROP 10. 
Is there a problem of using MATLAB 2012b?

**Comment by hermez19** [comment]
Ok so, I use the thread #29 until the additional changes (line 522, line 534 ....) So when y tried to do a test this is the answer... 
![problem refprop](https://user-images.githubusercontent.com/45673916/49658490-332fee00-fa10-11e8-945c-45d7933d0856.png)

**Comment by hermez19** [comment]
No, when i do what #29 told me, this error show up

**Comment by hermez19** [comment]
Sadly I can't I'm using an Educational License from my University and this version is the only we have

**Comment by ianhbell** [comment]
This is a much older version of the refpropm.m wrapper before we made the changes to the syntax, does it work for you: https://raw.githubusercontent.com/usnistgov/REFPROP-wrappers/79e157d57495d2ec4697e5c4a43808dc550f8152/wrappers/MATLAB/refpropm.m ?

**Comment by hermez19** [comment]
Yes, this wrapper worked! thank you very much!

**Comment by ianhbell** [comment]
Ok, good to hear!
