### ISSUE TITLE
Excel 'HelpPDF' opens REFPROP91.pdf not REFPROP.PDF

### ISSUE THREAD

**Issue by NickAtNight2017** [usnistgov/REFPROP-wrappers#85]
### Description
  Excel 'HelpPDF' opens REFPROP91.pdf not REFPROP.PDF

**Expected behavior:** 
  [Open current version of help file - v10]

**Actual behavior:** 
  [Opens previous version help file - v9.1]

### Versions
**REFPROP Version:** [10]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [Via Excel refprop Add-in]  

![image](https://user-images.githubusercontent.com/31464824/49820895-bb7aff80-fd3e-11e8-8f95-f65266348603.png)

**Comment by ianhbell** [comment]
? How is that possible?  We don’t (or shouldn’t) distribute REFPRP91.PDF with the REFPROP 10 installation.  Weird. I’ll look into it

**Comment by EricLemmon** [comment]
Can this issue be closed now?

**Comment by ianhbell** [comment]
Can you set it to read the RPPREFIX environment variable and look for the PDF relative to that?
