### ISSUE TITLE
gibberish in Cautions .  uncertainty about enthalpy

### ISSUE THREAD

**Issue by yangmengnist** [usnistgov/REFPROP-wrappers#86]
hi, there is a gibberish in the Cautions (like the picture below), how can I do for this problem?

![image](https://user-images.githubusercontent.com/42392984/50389725-f855d780-06ea-11e9-86fd-ea8e4defcdaa.png)

In addition, I see the uncertainty of the equation in Fluid Information, like the picture below, and I want to know the uncertainty of the enthalpy, where can I look up? If there are the uncertainties about the whole parameters about the refrigerants?

![image](https://user-images.githubusercontent.com/42392984/50389730-04419980-06eb-11e9-8460-078afa9603d1.png)

**Comment by EricLemmon** [comment]
I hope it is OK for me to take the information from your Word file and paste it directly into your text box.  That way other people can see it immediately and can search for the words in your text.  

The problem with the gibberish appears to be the extended ASCII characters that are embedded in the help file, and which did not come across correctly in your editor.  I'll ask Ian to look into that and see if we can correct it in the next edition that comes out.

**Comment by EricLemmon** [comment]
Concerning uncertainties in properties that are typically “unmeasurable”, such as entropy, one method we use to estimate the uncertainties depends on the magnitude of the derivatives of the Helmholtz energy, which is the property upon which the equation of state is based.  All thermodynamic properties are derivatives of the Helmholtz energy, for example, pressure is the first derivative of this with respect to density, and heat capacity is the second derivative with respect to temperature.  Energy, enthalpy, and entropy are basically first derivatives of the Helmholtz energy with respect to temperature.  The uncertainty in properties often increases with the order of magnitude of the derivatives (but not always, such as with the speed of sound), thus we often say that these three properties (e, h, and s) have an uncertainty of approximately one fourth to one half of that for the heat capacity.  In the case of R1234ze(Z), no heat capacities were available when the equation was made, so with our modern fitting techniques, the uncertainties in the liquid phase heat capacities when speed of sound measurements are available are probably between 5 and 10%.  Thus, e, h, and s would have an approximate uncertainty of 1 to 4%.  These are only rough estimates based upon our experience from fitting over many years.  There are much better ways to make such estimates, but they require a significant amount of work.
