### ISSUE TITLE
Error using calllib Array must be numeric or logical or a pointer to one

### ISSUE THREAD

**Issue by jonasT44** [usnistgov/REFPROP-wrappers#87]
Hi,
In refprop.m
``` matlab 
        [nc,~,~,~,ierr,errTxt] = calllib(libName,'SETUPdll',  numComponents,path,hmix,href,0,herr,10000,255,3,255);
```

### Description

The following line in refprop.m generates an error:
```
Error using calllib
Array must be numeric or logical or a pointer to one
```

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 10
**Access Method:** Matlab Legacy

### Additional Information

I have tried to uninstall/install REFPROP but the issue remains.

Anyone has a clue on this ? 
Regards,

**Comment by ianhbell** [comment]
Can you move to the Python interface?  The refpropm interface is deprecated.

**Comment by jonasT44** [comment]
Thank you for your answer.
I cannot use the new wrapper Matlab/Python with mixtures because of the open bug #49.
Hence, I am still using the deprecated Matlab wrapper. Would you need any information to solve bug #49 ?
Just in case it could help other users, replacing ~ in callib function solved my problem (see below). I cannot explain it so far. Any clue ?
Everywhere else, replace all ~ by (dummy).

`[nc path hmix href ierr errTxt] = calllib(libName,'SETUPdll',numComponents,path,hmix,href,0,32*ones(255,1),10000,255,3,255);`

**Comment by ianhbell** [comment]
This issue can be closed now since the bug in the Python wrapper has been fixed
