### ISSUE TITLE
getenumdll issue

### ISSUE THREAD

**Issue by nick-alexander** [usnistgov/REFPROP-wrappers#89]
### Versions

**REFPROP Version:** 9.1 
**Operating System and Version:** Windows 7
**Access Method:** Python 

### Additional Information

Input code:
``` python
import os; os.environ['RPPREFIX'] = r'C:\Program Files (x86)\REFPROP'

import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
MOLAR_BASE_SI = RP.GETENUMdll(0, "MOLAR BASE SI").iEnum

p_Pa = 101325
Q = 0.0
r = RP.REFPROPdll(os.path.join(os.environ['RPPREFIX'],"FLUIDS","WATER.FLD"),"PQ","T",MOLAR_BASE_SI,0,0,p_Pa,Q,[1.0])
r.Output[0]
```
Output error:
getenumdll could not be loaded, checking the directory and I couldn't see this dll. I'm assuming this should be there. Any ideas on how to fix this? Thank you

**Comment by ianhbell** [comment]
GETENUMdll is only available in REFPROP 10, you use REFPROP 9.x, so no dice.  Did you see this section: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python#ctypes-wrapper ?
