### ISSUE TITLE
Excel Spreadsheet update

### ISSUE THREAD

**Issue by NickAtNight2017** [usnistgov/REFPROP-wrappers#9]
What is the path forward for the Excel add-in.

- Add Menu (RefProp) with Ribbon ?

- Just experimenting a bit here.

1.	Such as putting in a custom Ribbon (example attached – RefProp) 
  a.	Positioned just after the developer tab in this case.
 
2.	I put all of the existing macros into the test Ribbon. 
  a.	Pictures were arbitrary.  They don’t have a good default selection.

3.	I only made one substantive change.  I created a new Macro to show a Userform window (RefPropSummary). 
  a.	There are 9 objects in the window.
    i.	NIST – hotlinks to NIST
    ii.	MML – hotlinks to MML
    iii.	ACMD – hotlinks to ACMD
    iv.	Dr. Lemmon – hotlinks to your page
    v.	Dr Huber – hotlinks to Dr. Hubers page
    vi.	Dr McLinden – hotlinks to Dr McLInens page
      1.	Note: Current summary page sends emails instead of hotlinks
    vii.	Refprop – hotlinks to the RefProp location
    viii.	FAQ – hotlinks to the Frequently Asked Questions page
    ix.	Close – closes the Window.

[Test.zip](https://github.com/usnistgov/REFPR

**Comment by NickAtNight2017** [comment]
Test

**Comment by NickAtNight2017** [comment]
Thank you.  The new Excel spreadsheet looks great.  

Please close.

**Comment by ianhbell** [comment]
I've closed it, there is also a "Close and Comment" button below your message in the github interface :)
