### ISSUE TITLE
Installation RefProp on MatLab issues

### ISSUE THREAD

**Issue by Yili-Zhang** [usnistgov/REFPROP-wrappers#91]
Hi all,

I've had successfully installed the RefProp on Excel, and wanted to install it onto Matlab by following link below: [https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB](url).

For the "Setup" session, I downloaded the latest version of the Anaconda, and every comment was smoothly executed. 

Then when I tried to run the `[v,e] = pyversion; system([e,' -m pip install --user -U ctREFPROP'])` comment in the "Install ctREFPROP", I got the following:
```
> pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. 
Collecting ctREFPROP 
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ctrefprop/ 
  Could not fetch URL https://pypi.org/simple/ctrefprop/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ctrefprop/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping 
  Could not find a version that satisfies the requirement ctREFPROP (from versions: ) 
No matching distribution found for ctREFPROP 
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. 
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping 

ans =

     1
```
It seems the problem was " **the ssl module in Python is not available**". But I can find the ssl folder under library: "C:\Users\A02295947\AppData\Local\Continuum\anaconda3\Library\ssl". Where the Python Application is located at "C:\Users\A02295947\AppData\Local\Continuum\anaconda3". 

In  addition, when I tried to run `[v,e] = pyversion; system([e,' -m easy_install pip'])`, it was successful.

I tried to continue to run  `RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')` under the "Use" Section,, I got:
```
> Undefined variable "py" or class "py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary".
```
I am really confused why it would not work. If anyone could give me some suggestions, I would really appreciate it!

Thanks!

-Yili

**Comment by ianhbell** [comment]
I made some little tidying up of your issue with formatting, but I have to say that this a stumper for me.  Some things that come to mind:
1) Is it possible somehow that your IT system is blocking SSL connections?  This I would have a hard time believing, but anything is possible.
2) Have you tried uninstalling Anaconda and reinstalling?  Perhaps that would fix the ssl bug, and that is definitely a bug.  I have found some other SSL issues in Anaconda, but they are not the issue that you are having: https://stackoverflow.com/questions/33699577/conda-update-failed-ssl-error-ssl-certificate-verify-failed-certificate-ver

**Comment by Yili-Zhang** [comment]
Hi Lan,

Thanks for getting back to me. I uninstalled the current version of Anaconda and reinstalled the 2.7 version. Then I run all the way to the "Use" session successfully.

When I executed the comment `RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP')`, I got:

> RP = 

  Python REFPROPInstance with properties:

    managed_handle: [1×1 py.NoneType]
               dll: [1×1 py.ctypes.WinDLL]

    <ctREFPROP.ctREFPROP.REFPROPInstance object at 0x000000000AB6F710>

Then I run the `RP.RPVersion()`, I got:

> ans = 

  Python unicode with no properties.

    9.1

However, when I tried to run the example: `r = RP.REFPROPdll('Water','PQ','T',int8(0),int8(0),int8(0),101.325,0.0,{1.0})`, I got errors:

> Error using ctREFPROP>REFPROPdll (line 2478)
Python Error: ValueError: The function REFPROPdll could not be loaded from the shared library.

Then, I found another code online and tried ` water=water_sat('T',10,'v',50,1)`, I still got errors:

> Undefined function or variable 'water_sat'.

I tried to find the reason online, and from the link [https://github.com/usnistgov/REFPROP-wrappers/issues/43](url), it seems the problem to be my refprop version is <10. 

If that were the case, may I know if I could run the refprop in Matlab with my current version? If not, do I  have to spend $125 to update the refprop version from 9.1 to 10, according to the website [https://www.nist.gov/srd/refprop](url)? In either way, may I also have the tutorials on using refprop functionalities on Matlab so that I could get started to use it?

Looking forward to hearing back from you soon!

Best,

-Yili

**Comment by ianhbell** [comment]
That's right - that function is only in REFPROP10.  You can use the legacy API if you like, but I recommend to upgrade to REFPROP 10.

**Comment by Yili-Zhang** [comment]
Hi Lan,

Thanks for the prompt reply. I will work on the upgrade. Besides, as I asked before, may I have a reference guide or tutorial for using Refprop functions in matlab, as the one for the Excel??

It is very important for me. Thanks!

-Yili

**Comment by ianhbell** [comment]
There's documentation online: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html  And a tutorial for Python: https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/notebooks/Tutorial.ipynb .  If there are other important issues missing there, please open a new issue and list what you think is missing.

**Comment by Yili-Zhang** [comment]
Thanks!
