### ISSUE TITLE
REFPROP Viscosity and Transport properties for LabView

### ISSUE THREAD

**Issue by lordQuant** [usnistgov/REFPROP-wrappers#92]
Hello,

First, my compliments for the nice LabView example code provided by the NIST team. 
In reviewing the output I was hoping to also find Viscosity and Thermal Conductivity (which are standard outputs from regular REFPROP).

How do I get access to these properties also?

Thanks!

**Comment by ianhbell** [comment]
Hello! All outputs to REFPROPdll function are valid, so "VIS" and "TCX" are viscosity and thermal conductivity, in your case.  Please see https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html for more info.

**Comment by lordQuant** [comment]
Thanks I am going to give that a try. Appreciate the super quick response !

**Comment by lordQuant** [comment]
Ian, I think what you are saying is that I cannot the Refprop_Example_main.vi, as it does not have VIS and TCX as parameters, but instead need to run the REFPROP high level API Tester.vi where VIS and TCX can probably be input.

Per instructions I moved my refprop.dll from my acquired refprop copy to the labview folder as well as the fluids and mixtures folders. However, the "REFPROP high level API Tester.vi" seems unable to run and shows broken due to absence of Setmixture.dll .

Is this from a newer version of refprop? I have version 9.1

How can I run "REFPROP high level API Tester.vi"? thanks

**Comment by lordQuant** [comment]
there are actually several DLLs missing, also getenum.dll, allprops0.dll etc.

**Comment by ianhbell** [comment]
The new Labview interface is intended for use with REFPROP 10, our new version to which you should upgrade if possible.  All the legacy functions are also exposed via separate VI.  If you want transport properties, then you want the TRNPRPdll function: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/TRNPRPdll .

The missing DLL you refer to are functions that were added in REFPROP 10.

**Comment by lordQuant** [comment]
Thank you, I will upgrade!
