### ISSUE TITLE
Find thermal conductivity with refprop?

### ISSUE THREAD

**Issue by Yili-Zhang** [usnistgov/REFPROP-wrappers#93]
Hi,

Does anyone knows exactly how to find a newly-defined mixture's thermal conductivity with RefProp?

Any help would be appreciated.

Thanks,

-Yili

**Comment by EricLemmon** [comment]
Hi Yili,

You just ask it to calculate it like any other property.  To do this from the new REFPROP subroutine, just use the codes "VIS" for viscosity and "TCX" for thermal conductivity.

Eric

**Comment by Yili-Zhang** [comment]
Hi Eric,

Thanks so much for your help! I just updated my Refprop from version 9.1 to version 10, and I found it in the instruction sheet. 

Have a good day.

Best,

-Yili
