### ISSUE TITLE
Critical Temperature and Pressure lost in Excel with upgraded RefProp

### ISSUE THREAD

**Issue by Yili-Zhang** [usnistgov/REFPROP-wrappers#95]
Hi,

After I upgraded the RefProp from version 9 to 10, and adapted the updated codes, I got the following error for finding the critical temperature and pressure of dry mixtures: 

> #[CRTHMX error 313] Coefficients are not available for critical calculations (which generally occurs for binary mixtures that are not in the HMX.BNC, or for beta versions of the program where the critical lines have not yet been fitted.

Strangely, this issue didn't happen for pure fluids or wet mixtures. And here is the code I used for finding the critical temperature:
`=refprop("TC", K36,"Crit","SI",,)`
Where K36 is my mixture:
`R245fa;0.1;cyclohexane;0.9`

Any one has any idea on where the problem was?

Thanks,

-Yili

**Comment by EricLemmon** [comment]
This message indicates that we have not fitted interaction parameters to experimental measurements;  rather the interaction parameters come from estimated methods and thus the calculations will be much less accurate.  In particular, critical point calculations could be significantly wrong depending on the type of mixture.  To help get an idea of how non-ideal the system is, look at P-T and P-x diagrams generated from the GUI.  I've pasted two below for you to look at.  This system seems to be fairly ideal and so the calculated values will be better than something like R245fa and ammonia.  But you still need to be careful and try to verify the calculations by finding experimental data if they are available and comparing the two.

![image](https://user-images.githubusercontent.com/42392984/53523447-0ed93000-3a9a-11e9-8f35-f93d6f753c3f.png)
![image](https://user-images.githubusercontent.com/42392984/53523595-74c5b780-3a9a-11e9-94a3-fce216a84c5d.png)

**Comment by EricLemmon** [comment]
Can this issue be closed now?

**Comment by Yili-Zhang** [comment]
Yes. Thanks.

-Yili
