### ISSUE TITLE
wrong results with mixture

### ISSUE THREAD

**Issue by way101** [usnistgov/REFPROP-wrappers#96]
Hi, I am a newer in programming. I have a problem while using Refprop out of Visual Studio.  When I tested the fluids, it went well. While when I tried to use it for mixtures, the results I got from the program differ from the REFPROP.

Here are the code and results.（mixture:r401b, subroutine THERMdll. For other mixtures and subroutin, I have the same problem.）
``` C
        const char *FLD_PATH;
        FLD_PATH = "C:\\Users\\Desktop\\Project3\\Project3\\fluids\\";
         strcpy_s(hf, FLD_PATH);
         i = 3; 
        strcpy_s(hf, "r22.fld");
	strcat_s(hf, "|r152a.fld");
	strcat_s(hf, "|r124.fld");
	strcpy_s(hfmix, "HMX.BNC");
	strcpy_s(hrf, "DEF");
	strcpy_s(herr, "Ok");
	z[0] = 0.65492;
	z[1] = 0.15461;
	z[2] = 0.19047;
	SETUPdll(i, hf, hfmix, hrf, ierr, herr,refpropcharlength*ncmax, refpropcharlength,lengthofreference, errormessagelength);
	double T, P, D, s, e, h, Cv, Cp, w, hjt, Dl, Dv, q;
	T = 300;
	D = 0.04;
	THERMdll(T, D, z, P, e, h, s, Cv, Cp, w, hjt);
	printf("w, D, hjt   %10.4f,%10.4f,%10.4f\n", w, D, hjt);
	printf("T, P, e   %10.4f,%10.4f,%10.4f\n", T, P, e);
	printf("h, s, Cv, Cp   %10.4f,%10.4f,%10.4f,%10.4f\n", h, s, Cv, Cp);
```
       I am using the following versions:
       Microsoft Visual Studio 2017
       REFPROP version 9.0
       Windows 10

**Comment by ianhbell** [comment]
What values did you get and what values did you expect?  If your problem is H and S, see https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences .  The DLL and GUI use different reference states by default.

Also, you have a pretty serious problem with your strings.  They are far too small, they MUST be padded to the specified size with spaces.  Otherwise, a subtle memory bug can occur.

P.S. I have modified your issue with formatting.

**Comment by way101** [comment]
But I used TPFLSHdll and THFLSHdll for the same state, it still went back with different results.
        `T = 300;`
	`P = 100;`
	`TPFLSHdll(T,P, z, D, Dl, Dv, x, y, q, e, h, s, Cv, Cp, w, ierr, herr, herr_length);`
	`THFLSHdll(T, h, z, kr, P, D, Dl, Dv, x, y, q, e, s, Cv, Cp, w, ierr, herr, herr_length);`
	`printf("P %10.4f\n", P);`
output P=0.2494.

**Comment by ianhbell** [comment]
TH can yield multiple solutions.  Please see https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/ABFLSHdll for a description of ``kr`` flag.  

In general, you'll get more comprehensive help if you post complete and runnable examples

**Comment by way101** [comment]
Thank you. It seems there is something wrong with my old project. I have solved the problem by building a new project and changing the reference state.
