### ISSUE TITLE
Error in loadlibrary

### ISSUE THREAD

**Issue by djtj2501** [usnistgov/REFPROP-wrappers#98]
After following the instructions, an error has occured. I'm using matlab 2018a

Error in loadlibrary

Error in refpropm (line 242)
            [~,~] = loadlibrary(strcat(BasePath,dllName),prototype,'alias',libName);

How can we solve this problem

**Comment by ianhbell** [comment]
In the future, please fill out the entire template; it is also helpful to provide an example of what you tried to do.  I can't tell what call you tried to make to get this error message.

The refpropm wrapper for MATLAB is no longer supported, but should still work.  We are supporting the Python interface only from here on out: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB
