### ISSUE TITLE
Excel REFPROP v10 Add-In Broken Link

### ISSUE THREAD

**Issue by grgrynlds** [usnistgov/REFPROP-wrappers#99]
### Description
Refprop function references are not recognized in Excel.

### Steps to Reproduce

1. REFPROP v10 installed on W10 computer
2. File\Options\Trust Center used to define REFPROP.DLL location in C:\Program Files (x86)\REFPROP\
3. File\Options\Add-Ins used to identify the add-in REFPROP.XLA (included with install)
4. Data\Edit Links used to confirm the link to the Add-In identified above

**Expected behavior:** Excel would recognize REFPROP calls used in a cell
**Actual behavior:** REFPROP calls not recognized

**REFPROP Version:** V10
**Operating System and Version:** W10
**Access Method:** Excel

### Additional Information
We had several problems, I think due to
1. Things weren't working so we tried to generate the Add-In ourselves by Save-As *.XLA using the REFPROP.XLS file.  This did not work and we went back to the preexisting REFPROP.XLA.
2. When completing step #4. above, we notices the REFPROP_Ribbon.xlam was included in the link listing.  Not sure how this got there. We removed it, **and everything worked.**

**Comment by NickAtNight2017** [comment]
Describe the refprop function you were seeking to use.  I suspect it was the old style refprop function.

The new style refprop function is significantly different.

The .xlam file is used to run the wizard.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NickAtNight2017** [comment]
Here is the new wizard running.

The new excel function is:
  =refprop(“D”,”Air”,”TP”,”SI”,273,0.2,0)

Fields are
  Selected property ... D for density 
  Fluid ... air
  2 specified propertys ... TP for temp and pressure
   Units... SI system 
   First property.  Temp is 273 K
   Second property. pressure is 0.1
   Third property.  Not used in this case.

When using the popup wizard, you can see the result already as 1.276 kg/m3

Always fun to use the down arrow and scroll quickly through all of the property results...

[
![9eee4a40-e4e2-4384-89ca-cc865cc024ca](https://user-images.githubusercontent.com/31464824/53918184-f2a23980-402b-11e9-845e-24100673a91d.jpeg)

**Comment by NickAtNight2017** [comment]
Start over.  You need both the uncorrupted  .xla and the .xlam files installed

![488f69af-5060-4ef1-a10d-f6b5f857b5cf](https://user-images.githubusercontent.com/31464824/53918684-43666200-402d-11e9-9f2c-ed14ed0e0e0f.jpeg)
![fa16309a-cabb-4d66-9607-4b52cd4717fc](https://user-images.githubusercontent.com/31464824/53918686-43666200-402d-11e9-98ff-cb7844fd4b7c.jpeg)

**Comment by NickAtNight2017** [comment]
I think the refprop91.xla is for the old version 9.1.  
You do not need that.

**Comment by NickAtNight2017** [comment]
With the refprop.xlam file installed, you should get the new REFPROP menu item.  (Circled in yellow top right)

This loads the Refprop ribbon.  

It was kept sparse for the new system.  There are only five items.

The insert function is just the standard insert function button.  More on had later.

Wizard is the main feature.  Click on that for a popup menu to generate your function.  No more trying to remember the formulas.  See prior picture.

About tells you about the NIST REFPROP system designers ands sponsors.  It takes you to their respective web sites.

Help opens the new help files !!!

2 styles -  a pdf. And a windows help style.

Help 


![e83c6f1d-9a36-4da0-aef7-986c12c4a912](https://user-images.githubusercontent.com/31464824/53918873-dc957880-402d-11e9-84ed-2ba13e57872a.jpeg)

**Comment by NickAtNight2017** [comment]
Wizard.

Set your inputs.

Calculate - just the formula to your active cell.  Slim, minimal design 

Compose - same but adds the property name to the left of the result and the units to the right.  Much better cause it reminds you what you did.

Compose all - For the OCD types (me).  Puts ALL the properties to your spreadsheet - property name, then formula and then units. Every last one.  Keep the ones you need and trash the rest.  

At the top you have your help message and the disclaimer.

Drop down fields for all the inputs.  The custom fluids fields is stilll not very user friendly.

Set your fluid, your units, your two input properties, enter their values.

Select your result.  

Select sat vapor or liquid with the check box to set the quality.

The ‘enable instant calc’ Let’s you see the result right away.  You can turn this off, but why would you?

The formula is built at the bottom !  Suitable to cut and paste.
 
![b927760a-46d0-46cb-8dca-0704cadc5a01](https://user-images.githubusercontent.com/31464824/53919292-33e81880-402f-11e9-9cfa-d85a55dbcf5d.jpeg)
Um, don’t start in column A !  It needs to write one to the left.

**Comment by NickAtNight2017** [comment]
Function
- just the classic function button.  Out here for convenience.

- there is now a ‘refprop’ category.  But with the new scheme, there are just two functions to show.
— Fluidstring10 for building a fluid string 
— Refprop to calculate the property

Help on this function loads the help documentation.

At the bottom of the window we tell you how to complete the new formula.

If you spelect OK, you go to the second screen.

Fill in all the fields and see the result.

The Wizard is easier and nicer to use though.

But since this is a classic Excel feature, it is available.


![bd924d9b-c79b-486d-9748-11d7b888f086](https://user-images.githubusercontent.com/31464824/53919683-61819180-4030-11e9-894d-9a9fdef239b1.jpeg)
![2fd36cb5-f592-46b5-97da-6de6ae50b9ab](https://user-images.githubusercontent.com/31464824/53919684-61819180-4030-11e9-9268-e56094b09c29.jpeg)
![486556c3-d393-4ed8-b35e-5a6ee44d27b0](https://user-images.githubusercontent.com/31464824/53919685-61819180-4030-11e9-8f8b-ad2419ffec91.jpeg)
![ce696527-846b-417f-b487-a28c4879a8d8](https://user-images.githubusercontent.com/31464824/53919686-61819180-4030-11e9-9c51-e4d5aaa18de6.jpeg)

**Comment by NickAtNight2017** [comment]
The last person with this problem was trying to write functions using the old version 9 style.

Have fun.

**Comment by grgrynlds** [comment]
I am using the v10 calls, for example:
=REFPROP("D","water","TQ","English",70,0,0)
and this works fine,

But I did not understand the function of the REFPROP_Ribbon.xlam
I have it identified in my Add-Ins, 
![image](https://user-images.githubusercontent.com/41301795/53919914-0e5c0e80-4031-11e9-9ba0-4d4d67703e4b.png)

but I do not have it selected in my Data\Edit Links (below)
![image](https://user-images.githubusercontent.com/41301795/53919841-d2c14480-4030-11e9-8fee-b6c655b785f4.png)

My ribbon, and the Wizard seem to work fine.
![image](https://user-images.githubusercontent.com/41301795/53919994-43686100-4031-11e9-9ad8-33516f78545b.png)

**Comment by EricLemmon** [comment]
First off, if you do not realize this, @NickAtNight2017 is the one who wrote the wizard and I thank him tremendously for his help in making Refprop better, and also for the documentation he wrote above.

I'm not sure if you have seen the welcome page in the Refprop.xls file.  If not, there's a lot of documentation there about some of this.  Also, be sure to look at:

https://github.com/usnistgov/REFPROP-issues/issues/105

**Comment by NickAtNight2017** [comment]
Eric is being modest.  I just started him down this path.  Once he got going, he took off with it.

**Comment by NickAtNight2017** [comment]
So where are we up to?  What seems to be broken?
-- Wizard is working fine.
-- I think your data links are working fine.

Details:
With a new worksheet, I have no data links.

Run the Wizard to generate a formula.  Now I have a data link to Refprop.xla.  This is the routine that holds all of the functions.  

![Capture](https://user-images.githubusercontent.com/31464824/54129654-bcbed580-43dc-11e9-816a-6e2b861c79d4.PNG)

I have no data link to the Wizard.

If I delete that formula, my data link goes away.

![Untitled](https://user-images.githubusercontent.com/31464824/54129802-10312380-43dd-11e9-9497-6d29e3a7affa.png)

Excel is working as it should work.  Only if you have a formula from refprop.xla on your worksheet should you have a data link to refprop.

**Comment by EricLemmon** [comment]
Has this issue been resolved?  If so, could you close it?
